[package]
name = "common-continuous-profiling"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
envconfig = { workspace = true }
pyroscope = { version = "2", features = ["backend-pprof-rs", "backend-jemalloc"] }
thiserror = { workspace = true }
tracing = { workspace = true }
