from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Descriptions sourced from the Phyllo API reference (https://docs.getphyllo.com).
# Partial coverage is fine — uncovered columns fall back to LLM enrichment.
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "work_platforms": {
        "description": "A platform Phyllo can pull creator data from, such as YouTube, Instagram, TikTok, Twitch, or Spotify.",
        "docs_url": "https://docs.getphyllo.com",
        "columns": {
            "id": "The unique ID of the work platform.",
            "name": "The name of the work platform.",
            "logo_url": "URL of the platform's logo image.",
            "category": "The category of the platform (e.g. MEDIA, EDUCATION).",
            "status": "Whether the platform integration is active on Phyllo.",
            "url": "The website URL of the platform.",
            "products": "Which Phyllo products (identity, engagement, income, etc.) the platform supports.",
            "created_at": "When the work platform was added to Phyllo.",
            "updated_at": "When the work platform record was last updated.",
        },
    },
    "users": {
        "description": "A creator registered in your Phyllo workspace, identified by your own external ID, who links platform accounts via Phyllo Connect.",
        "docs_url": "https://docs.getphyllo.com",
        "columns": {
            "id": "The unique ID of the user.",
            "name": "The display name of the user.",
            "external_id": "Your own identifier for the user, supplied when the user was created.",
            "status": "The current status of the user.",
            "created_at": "When the user was created.",
            "updated_at": "When the user was last updated.",
        },
    },
    "accounts": {
        "description": "A platform account (e.g. a YouTube channel or Instagram account) a creator has connected through Phyllo Connect.",
        "docs_url": "https://docs.getphyllo.com",
        "columns": {
            "id": "The unique ID of the connected account.",
            "user": "The Phyllo user the account belongs to.",
            "work_platform": "The platform the account lives on.",
            "platform_username": "The creator's username on the platform.",
            "status": "The connection status of the account (e.g. CONNECTED, NOT_CONNECTED, SESSION_EXPIRED).",
            "data": "Per-product (identity, engagement, income) data availability and sync status for the account.",
            "created_at": "When the account was connected.",
            "updated_at": "When the account was last updated.",
        },
    },
    "profiles": {
        "description": "The identity profile of a connected account: name, contact details, audience reputation, and platform metadata.",
        "docs_url": "https://docs.getphyllo.com",
        "columns": {
            "id": "The unique ID of the profile.",
            "account": "The connected account the profile belongs to.",
            "user": "The Phyllo user the profile belongs to.",
            "work_platform": "The platform the profile lives on.",
            "username": "The creator's username on the platform.",
            "full_name": "The creator's full name.",
            "url": "URL of the creator's profile page on the platform.",
            "image_url": "URL of the creator's profile image.",
            "reputation": "Audience reputation metrics such as follower and subscriber counts.",
            "is_verified": "Whether the platform has verified the profile.",
            "is_business": "Whether the profile is a business account.",
            "created_at": "When the profile record was created in Phyllo.",
            "updated_at": "When the profile record was last updated.",
        },
    },
    "social_contents": {
        "description": "A content item published by a connected account — videos, posts, stories, tweets, or tracks — with its engagement metrics.",
        "docs_url": "https://docs.getphyllo.com",
        "columns": {
            "id": "The unique ID of the content item.",
            "account": "The connected account that published the content.",
            "user": "The Phyllo user the content belongs to.",
            "work_platform": "The platform the content was published on.",
            "external_id": "The platform's own identifier for the content item.",
            "title": "The title of the content item.",
            "format": "The media format of the content (e.g. VIDEO, IMAGE, AUDIO).",
            "type": "The platform-specific content type (e.g. POST, STORY, REEL, TWEET).",
            "url": "URL of the content on the platform.",
            "description": "The description or caption of the content.",
            "visibility": "The visibility of the content (e.g. PUBLIC, PRIVATE).",
            "engagement": "Engagement metrics such as like, comment, view, and share counts.",
            "published_at": "When the content was published on the platform.",
            "created_at": "When the content record was created in Phyllo.",
            "updated_at": "When the content record was last updated.",
        },
    },
    "income_transactions": {
        "description": "An earnings transaction of a connected account, such as ad revenue, subscription payments, tips, or royalties.",
        "docs_url": "https://docs.getphyllo.com",
        "columns": {
            "id": "The unique ID of the transaction.",
            "account": "The connected account the transaction belongs to.",
            "user": "The Phyllo user the transaction belongs to.",
            "work_platform": "The platform the transaction occurred on.",
            "external_id": "The platform's own identifier for the transaction.",
            "amount": "The monetary amount of the transaction.",
            "currency": "The currency of the transaction amount.",
            "type": "The earnings type of the transaction (e.g. AD_REVENUE, SUBSCRIPTION, TIP).",
            "status": "The status of the transaction.",
            "transaction_at": "When the transaction occurred on the platform.",
            "created_at": "When the transaction record was created in Phyllo.",
            "updated_at": "When the transaction record was last updated.",
        },
    },
    "income_payouts": {
        "description": "A payout made by a platform to a connected account's bank account or payment method.",
        "docs_url": "https://docs.getphyllo.com",
        "columns": {
            "id": "The unique ID of the payout.",
            "account": "The connected account the payout belongs to.",
            "user": "The Phyllo user the payout belongs to.",
            "work_platform": "The platform that made the payout.",
            "external_id": "The platform's own identifier for the payout.",
            "amount": "The monetary amount of the payout.",
            "currency": "The currency of the payout amount.",
            "status": "The status of the payout.",
            "payout_interval": "How often the platform pays out (e.g. MONTHLY).",
            "payout_at": "When the payout was made.",
            "created_at": "When the payout record was created in Phyllo.",
            "updated_at": "When the payout record was last updated.",
        },
    },
}
