from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "syncs": {
        "description": "A Census sync: the configuration that moves data from a source model to a destination object, including its schedule, field mappings, and alerting.",
        "docs_url": "https://fivetran.com/docs/activations/rest-api/api-reference/workspace-apis/syncs/get-syncs",
        "columns": {
            "id": "Unique identifier for the sync.",
            "status": "Current status of the sync configuration (e.g. ready, paused, broken).",
            "label": "Human-readable name of the sync.",
            "operation": "The sync operation type (e.g. mirror, append, update, upsert).",
            "paused": "Whether the sync is currently paused and will not run on schedule.",
            "created_at": "Timestamp the sync was created.",
            "updated_at": "Timestamp the sync configuration was last updated.",
            "source_attributes": "The source connection and model/table this sync reads from.",
            "destination_attributes": "The destination connection and object this sync writes to.",
            "mappings": "The field mappings between the source model and destination object.",
            "mode": "The sync's trigger mode (e.g. triggered on a schedule, or continuous).",
            "high_water_mark_attribute": "The source column Census uses to detect changed records between runs.",
            "field_behavior": "Which destination fields are synced (e.g. sync all properties, or only mapped fields).",
            "mirror_strategy": "For mirror syncs, whether deletes are propagated to the destination.",
            "historical_sync_operation": "How the initial (historical) sync run backfills records.",
            "match_rate_details": "The most recently calculated match rate between source and destination records.",
        },
    },
    "sync_runs": {
        "description": "A single execution of a Census sync, including its status, timing, and per-run record counts.",
        "docs_url": "https://fivetran.com/docs/activations/rest-api/api-reference/workspace-apis/sync-runs/list-sync-runs",
        "columns": {
            "id": "Unique identifier for the sync run.",
            "sync_id": "Identifier of the sync this run belongs to.",
            "status": "Final or current status of the run (e.g. completed, failed, working).",
            "created_at": "Timestamp the run was created/queued.",
            "updated_at": "Timestamp the run was last updated.",
            "completed_at": "Timestamp the run finished, if completed.",
            "canceled": "Whether the run was canceled before completion.",
            "current_step": "The processing step the run is currently on or last reported.",
            "full_sync": "Whether this run was a full (historical) sync rather than an incremental one.",
            "error_code": "Machine-readable error code if the run failed.",
            "error_message": "Short human-readable error message if the run failed.",
            "error_detail": "Extended error detail for troubleshooting a failed run.",
            "source_record_count": "Number of records read from the source for this run.",
            "records_processed": "Number of records processed by the sync during this run.",
            "records_updated": "Number of destination records updated during this run.",
            "records_failed": "Number of records that failed to sync during this run.",
            "records_invalid": "Number of records rejected as invalid during this run.",
            "source_record_updates": "Number of source records detected as updates for this run.",
            "source_record_deletes": "Number of source records detected as deletes for this run.",
            "source_record_invalids": "Number of source records flagged invalid for this run.",
            "scheduled_execution_time": "The time the run was scheduled to execute.",
            "sync_trigger_reason": "What triggered the run (e.g. manual, scheduled).",
        },
    },
    "sources": {
        "description": "A Census data source: a connected warehouse or database Census reads records from.",
        "docs_url": "https://fivetran.com/docs/activations/rest-api/api-reference/workspace-apis/sources/list-sources",
        "columns": {
            "id": "Unique identifier for the source connection.",
            "name": "Internal name of the source connection.",
            "label": "Human-readable label of the source connection.",
            "type": "The warehouse/database type (e.g. snowflake, bigquery, postgres).",
            "sync_engine": "The engine Census uses to query this source.",
            "created_at": "Timestamp the source connection was created.",
            "last_tested_at": "Timestamp connectivity to the source was last tested.",
            "last_test_succeeded": "Whether the most recent connectivity test succeeded.",
            "last_test_results": "Detailed results of the most recent connectivity test.",
            "warehouse_writeback_retention_in_days": "How many days of writeback/sync history Census retains for this source.",
        },
    },
    "destinations": {
        "description": "A Census destination: a connected SaaS tool or warehouse Census writes records to.",
        "docs_url": "https://fivetran.com/docs/activations/rest-api/api-reference/workspace-apis/destinations/list-destinations",
        "columns": {
            "id": "Unique identifier for the destination connection.",
            "name": "Name of the destination connection.",
            "created_at": "Timestamp the destination connection was created.",
            "last_tested_at": "Timestamp connectivity to the destination was last tested.",
            "last_test_succeeded": "Whether the most recent connectivity test succeeded.",
            "last_test_results": "Detailed results of the most recent connectivity test.",
            "is_file_system_destination": "Whether this destination writes to a file system rather than an API.",
        },
    },
}
