import { MakeLogicType, actions, afterMount, connect, kea, listeners, path, selectors } from 'kea'
import { loaders } from 'kea-loaders'

import { lemonToast } from '@posthog/lemon-ui'

import api from 'lib/api'
import { teamLogic } from 'scenes/teamLogic'

export interface TerraformAccessControlSettings {
    lock_terraform_managed_rules: boolean
    has_terraform_managed_rules: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface terraformAccessControlLogicValues {
    currentProjectId: number | string // teamLogic
    settings: TerraformAccessControlSettings | null
    settingsLoading: boolean
    shouldShowSetting: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface terraformAccessControlLogicActions {
    loadSettings: () => any
    loadSettingsFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadSettingsSuccess: (
        settings: TerraformAccessControlSettings,
        payload?: any
    ) => {
        settings: TerraformAccessControlSettings
        payload?: any
    }
    setLock: (locked: boolean) => {
        locked: boolean
    }
    setLockFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    setLockSuccess: (
        settings: TerraformAccessControlSettings,
        payload?: {
            locked: boolean
        }
    ) => {
        settings: TerraformAccessControlSettings
        payload?: {
            locked: boolean
        }
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface terraformAccessControlLogicMeta {
    __keaTypeGenInternalSelectorTypes: {
        shouldShowSetting: (settings: any) => boolean
    }
}

export type terraformAccessControlLogicType = MakeLogicType<
    terraformAccessControlLogicValues,
    terraformAccessControlLogicActions,
    Record<string, any>,
    terraformAccessControlLogicMeta
>

export const terraformAccessControlLogic = kea<terraformAccessControlLogicType>([
    path(['layout', 'navigation-3000', 'sidepanel', 'panels', 'access_control', 'terraformAccessControlLogic']),

    connect(() => ({
        values: [teamLogic, ['currentProjectId']],
    })),

    actions({
        setLock: (locked: boolean) => ({ locked }),
    }),

    loaders(({ values }) => ({
        settings: [
            null as TerraformAccessControlSettings | null,
            {
                loadSettings: async () =>
                    await api.get<TerraformAccessControlSettings>(
                        `api/projects/${values.currentProjectId}/access_control_management_settings`
                    ),
                setLock: async ({ locked }) =>
                    await api.update<TerraformAccessControlSettings>(
                        `api/projects/${values.currentProjectId}/access_control_management_settings`,
                        { lock_terraform_managed_rules: locked }
                    ),
            },
        ],
    })),

    selectors({
        // The setting is meaningless until Terraform manages something, so it stays hidden until
        // then. It also stays visible while the lock is on, otherwise turning it back off would
        // be impossible once the last managed rule went away.
        shouldShowSetting: [
            (s) => [s.settings],
            (settings: TerraformAccessControlSettings | null): boolean =>
                !!settings && (settings.has_terraform_managed_rules || settings.lock_terraform_managed_rules),
        ],
    }),

    listeners({
        setLockFailure: () => {
            lemonToast.error('Could not change the Terraform lock. Try again.')
        },
    }),

    afterMount(({ actions }) => {
        actions.loadSettings()
    }),
])
