import { MakeLogicType, connect, kea, key, path, props, selectors } from 'kea'
import { loaders } from 'kea-loaders'
import { subscriptions } from 'kea-subscriptions'

import { FEATURE_FLAGS } from 'lib/constants'
import { featureFlagLogic } from 'lib/logic/featureFlagLogic'
import type { FeatureFlagsSet } from 'lib/logic/featureFlagLogic'
import { getCurrentTeamId } from 'lib/utils/getAppContext'

import * as api from '../../generated/api'
import type { TicketPatternApi } from '../../generated/api.schemas'

export interface TicketPatternPanelLogicProps {
    ticketId: string
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface ticketPatternPanelLogicValues {
    featureFlags: FeatureFlagsSet // featureFlagLogic
    patterns: TicketPatternApi[]
    patternsEnabled: boolean
    patternsLoading: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface ticketPatternPanelLogicActions {
    loadPatterns: () => any
    loadPatternsFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadPatternsSuccess: (
        patterns: TicketPatternApi[],
        payload?: any
    ) => {
        patterns: TicketPatternApi[]
        payload?: any
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface ticketPatternPanelLogicMeta {
    key: string
    __keaTypeGenInternalSelectorTypes: {
        patternsEnabled: (featureFlags: FeatureFlagsSet) => boolean
    }
}

export type ticketPatternPanelLogicType = MakeLogicType<
    ticketPatternPanelLogicValues,
    ticketPatternPanelLogicActions,
    TicketPatternPanelLogicProps,
    ticketPatternPanelLogicMeta
>

export const ticketPatternPanelLogic = kea<ticketPatternPanelLogicType>([
    props({} as TicketPatternPanelLogicProps),
    key((props) => props.ticketId),
    path((key) => ['products', 'conversations', 'frontend', 'scenes', 'ticket', 'ticketPatternPanelLogic', key]),
    connect(() => ({ values: [featureFlagLogic, ['featureFlags']] })),
    loaders(({ props }) => ({
        patterns: [
            [] as TicketPatternApi[],
            {
                loadPatterns: async () => {
                    const response = await api.conversationsPatternsList(String(getCurrentTeamId()), {
                        ticket_id: props.ticketId,
                        status: 'open,confirmed',
                    })
                    return [...response.results]
                },
            },
        ],
    })),
    selectors({
        patternsEnabled: [
            (s) => [s.featureFlags],
            (featureFlags: Record<string, boolean | string | undefined>): boolean =>
                !!featureFlags[FEATURE_FLAGS.PRODUCT_SUPPORT_TICKET_PATTERNS],
        ],
    }),
    // A subscription instead of afterMount: flags can resolve after the logic mounts, and a
    // one-time mount check would then never load. This fires with the value at mount and again
    // when the flag turns on, so only flagged teams pay for the lookup query.
    subscriptions(({ actions }) => ({
        patternsEnabled: (patternsEnabled: boolean, wasEnabled: boolean | undefined) => {
            if (patternsEnabled && !wasEnabled) {
                actions.loadPatterns()
            }
        },
    })),
])
