import RE2 from 're2'
import { exec, execAsync, execSync } from '../execute'
import { Operation as op } from '../operation'
import { UncaughtHogVMException } from '../utils'

const event = {
    uuid: '01921df6-530f-7148-801c-fabf0abffd1a',
    event: '$pageview',
    properties: {
        $os: 'Mac OS X',
        $os_version: '10.15.7',
        $browser: 'Chrome',
        $device_type: 'Desktop',
        $current_url:
            'https://eu.posthog.com/organization/billing?utm_source=transactional&utm_medium=email&utm_campaign=billing_invoice_payment_failed',
        $host: 'eu.posthog.com',
        $pathname: '/organization/billing',
        $raw_user_agent:
            'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36',
        $browser_version: 129,
        $browser_language: 'en-GB',
        $screen_height: 982,
        $screen_width: 1512,
        $viewport_height: 823,
        $viewport_width: 1512,
        $lib: 'web',
        $lib_version: '1.163.0',
        $insert_id: 'g4dtwps2d823tvxp',
        $time: 1727079535.376,
        distinct_id: 'wncF8BcNyRrHBlNU5pYZGS3bPSUNcNa7JJa0zSORJ5r',
        $device_id: '186b67b6421cd-0b885abde22e0b-1f525634-4b9600-186b67b64222599',
        $referrer: '$direct',
        $referring_domain: '$direct',
        realm: 'cloud',
        email_service_available: true,
        slack_service_available: true,
        $session_recording_recorder_version_server_side: 'v2',
        $active_feature_flags: [
            'onboarding-dashboard-templates',
            'survey-targeting-next-five-great-session-replay-things',
            'settings-session-table-version',
            'changelog-notification',
            'web-analytics-last-click',
            'web-analytics-conversion-goals',
            'mssql_source',
            'test-juraj-trend',
            'experiment-make-decision',
            'query-based-insights-saving',
            'web-analytics-replay',
            'first-time-for-user-math',
            'multiple-breakdowns',
            'web-vitals-autocapture',
            'query-based-dashboard-cards',
            'session-replay-universal-filters',
            'person-batch-exports',
            'surveys-branching-logic',
            'web-analytics-live-user-count',
            'pricing-test',
            'insight-loading-bar',
            'tabbed-pricing-page-v2',
            'surveys-events',
            'surveys-recurring',
            'live-events',
            'invite-team-member-onboarding',
            'product-analytics-insight-activation-email-campaign',
            'product-analytics-ingestion-activation-email-campaign',
            'redirect-web-analytics-product-analytics-onboarding',
            'redirect-insight-creation-product-analytics-onboarding',
            'enterprise-pricing-table',
            'persons-on-events-person-id-override-properties-joined',
            'tabbed-pricing-page',
            'data-warehouse',
            'session-replay-hogql-filtering',
            'hogql-insights-preview',
            'artificial-lag-query-performance',
            'persons-hogql-query',
            'hogql-insights-funnels',
            'session-replay-mobile-onboarding',
            'query-async',
            'hogql-insights-trends',
            'feature-flag-phani-test',
            'session-table-property-filters',
            'ip-allowlist-setting',
            'test-juraj-2',
            'survey-test-target',
            'new-experiments-ui',
            'test-juraj',
            'hogql-insights-paths',
            'web-analytics',
            'generic-signup-benefits',
            'show-troubleshooting-docs-in-support-form',
            'reverse-proxy-onboarding',
            'subscribe-from-paygate',
            'test-trends',
            'exports-sidepanel',
            'new-feature-flag-operators',
            'saved-not-pinned',
            'data-warehouse-postgres-import',
            'datanode-concurrency-limit',
            'hogql-insights-retention',
            'hogql-insights-stickiness',
            'scheduled-changes-feature-flags',
            'replay-activation-email-campaign',
            'lior-test-flag-copy',
            'hogql-insights-lifecycle',
            'surveys-open-choice',
            'surveys-paygates',
            'surveys-multiple-questions',
            'surveys-new-creation-flow',
            'product-book-a-demo',
            'stale-cache-invalidation-enabled',
            'product-ctas',
            'apps-and-exports-ui',
            'early-access-feature-site-button',
            'session-recording-player-preview',
            'new-empty-states',
            'survey-targeting-surveys-beta-users-interest',
            'more-foss-friendly-language',
            'session-recording-infinite-list',
            'billing-by-products',
            'data-exploration-insights',
            'auto-redirect',
            'recordings-list-v2-enabled',
            'exposures-on-feature-flags',
            'sampling',
            'person-groups-property-definitions',
            'web-pricing-cta',
            'join-algorithm',
            'website-pricing-page-test',
            'cta-button-color',
            'button-color',
            'recordings-inspector-v2',
            'onboarding-v2-demo',
            'role-based-access',
            'billing-lock-everything',
            'billing-features-experiment',
            'ingestion-warnings-enabled',
            'billing-v2-enabled',
            'app-metrics',
            'region-select',
            'historical-exports-v2',
            'experiment-pricing-calculator',
            'save-cohort-on-modal',
            're-engagement-emails',
            'smoothing-interval',
            'event-count-per-actor',
            'auto-refresh-dashboards',
            'homepage-lists-experiment',
            '7569-insight-cohorts',
            'homepage-feature-slider',
            'email-gated-signup-control',
        ],
        '$feature/onboarding-dashboard-templates': 'control',
        '$feature/survey-targeting-next-five-great-session-replay-things': true,
        '$feature/settings-session-table-version': true,
        '$feature/changelog-notification': true,
        '$feature/web-analytics-last-click': true,
        '$feature/web-analytics-conversion-goals': true,
        '$feature/mssql_source': true,
        '$feature/test-juraj-trend': 'test_2',
        '$feature/experiment-make-decision': true,
        '$feature/query-based-insights-saving': true,
        '$feature/web-analytics-replay': true,
        '$feature/first-time-for-user-math': true,
        '$feature/multiple-breakdowns': true,
        '$feature/web-vitals-autocapture': true,
        '$feature/query-based-dashboard-cards': true,
        '$feature/session-replay-universal-filters': true,
        '$feature/person-batch-exports': true,
        '$feature/surveys-branching-logic': true,
        '$feature/web-analytics-live-user-count': true,
        '$feature/pricing-test': 'control',
        '$feature/insight-loading-bar': true,
        '$feature/tabbed-pricing-page-v2': 'test',
        '$feature/surveys-events': true,
        '$feature/surveys-recurring': true,
        '$feature/live-events': true,
        '$feature/invite-team-member-onboarding': 'control',
        '$feature/product-analytics-insight-activation-email-campaign': 'test',
        '$feature/product-analytics-ingestion-activation-email-campaign': 'test',
        '$feature/redirect-web-analytics-product-analytics-onboarding': 'control',
        '$feature/redirect-insight-creation-product-analytics-onboarding': 'test',
        '$feature/enterprise-pricing-table': 'control',
        '$feature/persons-on-events-person-id-override-properties-joined': true,
        '$feature/tabbed-pricing-page': 'control',
        '$feature/data-warehouse': true,
        '$feature/session-replay-hogql-filtering': true,
        '$feature/hogql-insights-preview': true,
        '$feature/artificial-lag-query-performance': 'control',
        '$feature/persons-hogql-query': true,
        '$feature/hogql-insights-funnels': true,
        '$feature/session-replay-mobile-onboarding': true,
        '$feature/query-async': true,
        '$feature/hogql-insights-trends': true,
        '$feature/feature-flag-phani-test': 'control',
        '$feature/session-table-property-filters': true,
        '$feature/ip-allowlist-setting': true,
        '$feature/test-juraj-2': 'test',
        '$feature/survey-test-target': true,
        '$feature/new-experiments-ui': true,
        '$feature/test-juraj': 'control',
        '$feature/hogql-insights-paths': true,
        '$feature/web-analytics': true,
        '$feature/generic-signup-benefits': 'test',
        '$feature/show-troubleshooting-docs-in-support-form': 'test-replay-banner',
        '$feature/reverse-proxy-onboarding': 'test',
        '$feature/subscribe-from-paygate': 'test',
        '$feature/test-trends': 'control',
        '$feature/exports-sidepanel': true,
        '$feature/new-feature-flag-operators': true,
        '$feature/saved-not-pinned': 'control',
        '$feature/data-warehouse-postgres-import': true,
        '$feature/datanode-concurrency-limit': true,
        '$feature/hogql-insights-retention': true,
        '$feature/hogql-insights-stickiness': true,
        '$feature/scheduled-changes-feature-flags': true,
        '$feature/replay-activation-email-campaign': 'test',
        '$feature/lior-test-flag-copy': true,
        '$feature/hogql-insights-lifecycle': true,
        '$feature/surveys-open-choice': true,
        '$feature/surveys-paygates': true,
        '$feature/surveys-multiple-questions': true,
        '$feature/surveys-new-creation-flow': true,
        '$feature/product-book-a-demo': 'control',
        '$feature/stale-cache-invalidation-enabled': true,
        '$feature/product-ctas': 'book-a-demo',
        '$feature/apps-and-exports-ui': true,
        '$feature/early-access-feature-site-button': 'native',
        '$feature/session-recording-player-preview': true,
        '$feature/new-empty-states': 'test',
        '$feature/survey-targeting-surveys-beta-users-interest': true,
        '$feature/more-foss-friendly-language': 'test',
        '$feature/session-recording-infinite-list': true,
        '$feature/billing-by-products': 'test',
        '$feature/data-exploration-insights': true,
        '$feature/auto-redirect': true,
        '$feature/recordings-list-v2-enabled': true,
        '$feature/exposures-on-feature-flags': true,
        '$feature/sampling': true,
        '$feature/person-groups-property-definitions': true,
        '$feature/web-pricing-cta': 'test',
        '$feature/join-algorithm': 'parallel_hash',
        '$feature/website-pricing-page-test': 'test',
        '$feature/cta-button-color': 'light-blue',
        '$feature/button-color': 'dark-blue',
        '$feature/recordings-inspector-v2': true,
        '$feature/onboarding-v2-demo': 'control',
        '$feature/role-based-access': 'control',
        '$feature/billing-lock-everything': true,
        '$feature/billing-features-experiment': 'test',
        '$feature/ingestion-warnings-enabled': true,
        '$feature/billing-v2-enabled': true,
        '$feature/app-metrics': true,
        '$feature/region-select': true,
        '$feature/historical-exports-v2': true,
        '$feature/experiment-pricing-calculator': 'control',
        '$feature/save-cohort-on-modal': true,
        '$feature/re-engagement-emails': true,
        '$feature/smoothing-interval': true,
        '$feature/event-count-per-actor': true,
        '$feature/auto-refresh-dashboards': true,
        '$feature/homepage-lists-experiment': 'test',
        '$feature/7569-insight-cohorts': true,
        '$feature/homepage-feature-slider': 'slider_on',
        '$feature/email-gated-signup-control': true,
        $feature_flag_payloads: {},
        $user_id: 'wncF8BcNyRrHBlNU5pYZGS3bPSUNcNa7JJa0zSORJ5r',
        is_demo_project: false,
        $groups: {
            project: '0185e861-1cbc-0000-34af-61669babf5d7',
            organization: '0185bfcf-f208-0000-7530-6be2046448e8',
            customer: 'cus_NEYt9TNQDy0wLw',
            instance: 'https://eu.posthog.com',
        },
        posthog_version: '1.43.0',
        has_billing_plan: true,
        event_allocation: 1000000,
        allocation_used: 0.11873,
        customer_deactivated: false,
        current_total_amount_usd: '401.41',
        'custom_limits_usd.events': '150',
        'custom_limits_usd.recordings': '20',
        'percentage_usage.events': 0.14531178632794658,
        'current_amount_usd.events': '0.00',
        'unit_amount_usd.events': null,
        'usage_limit.events': 1333333,
        'current_usage.events': 193749,
        'projected_usage.events': 589137,
        'free_allocation.events': 0,
        'percentage_usage.recordings': 0,
        'current_amount_usd.recordings': '0.00',
        'unit_amount_usd.recordings': null,
        'usage_limit.recordings': 19000,
        'current_usage.recordings': 0,
        'projected_usage.recordings': 0,
        'free_allocation.recordings': 0,
        billing_period_start: '2024-08-25T09:59:57.000Z',
        billing_period_end: '2024-09-25T09:59:57.000Z',
        license_plan: 'cloud',
        $autocapture_disabled_server_side: false,
        'custom_limits_usd.session_replay': 20,
        'custom_limits_usd.product_analytics': 500,
        'percentage_usage.product_analytics': 0.7806390840451273,
        'current_amount_usd.product_analytics': '401.41',
        'unit_amount_usd.product_analytics': null,
        'usage_limit.product_analytics': '2744240',
        'current_usage.product_analytics': 2142261,
        'projected_usage.product_analytics': 2683322,
        'free_allocation.product_analytics': 0,
        'percentage_usage.session_replay': 0,
        'current_amount_usd.session_replay': '0.00',
        'unit_amount_usd.session_replay': null,
        'usage_limit.session_replay': 9000,
        'current_usage.session_replay': 0,
        'projected_usage.session_replay': 0,
        'free_allocation.session_replay': 0,
        'percentage_usage.feature_flags': 0,
        'current_amount_usd.feature_flags': '0.00',
        'unit_amount_usd.feature_flags': null,
        'usage_limit.feature_flags': 10000000,
        'current_usage.feature_flags': 0,
        'projected_usage.feature_flags': 0,
        'free_allocation.feature_flags': 0,
        'percentage_usage.integrations': 0,
        'current_amount_usd.integrations': null,
        'unit_amount_usd.integrations': null,
        'usage_limit.integrations': 0,
        'current_usage.integrations': 0,
        'projected_usage.integrations': 0,
        'free_allocation.integrations': 0,
        'percentage_usage.platform_and_support': 0,
        'current_amount_usd.platform_and_support': null,
        'unit_amount_usd.platform_and_support': null,
        'usage_limit.platform_and_support': 0,
        'current_usage.platform_and_support': 0,
        'projected_usage.platform_and_support': 0,
        'free_allocation.platform_and_support': 0,
        $initial_person_info: {
            r: '$direct',
            u: 'https://eu.posthog.com/login?next=/',
        },
        commit_sha: '9bf99b3fb8',
        $session_recording_network_payload_capture: {
            capturePerformance: {
                network_timing: true,
                web_vitals: true,
                web_vitals_allowed_metrics: null,
            },
            recordBody: true,
            recordHeaders: true,
        },
        $session_recording_canvas_recording: {},
        $replay_sample_rate: null,
        $replay_minimum_duration: 2000,
        $web_vitals_enabled_server_side: true,
        $exception_capture_enabled_server_side: true,
        $exception_capture_endpoint: '/e/',
        'percentage_usage.surveys': 0,
        'current_amount_usd.surveys': '0.00',
        'unit_amount_usd.surveys': null,
        'usage_limit.surveys': 250,
        'current_usage.surveys': 0,
        'projected_usage.surveys': 0,
        'free_allocation.surveys': 0,
        $surveys_activated: [],
        'custom_limits_usd.data_warehouse': 500,
        'percentage_usage.data_warehouse': 0,
        'current_amount_usd.data_warehouse': '0.00',
        'unit_amount_usd.data_warehouse': null,
        'usage_limit.data_warehouse': 46500000,
        'current_usage.data_warehouse': 0,
        'projected_usage.data_warehouse': 0,
        'free_allocation.data_warehouse': 0,
        $console_log_recording_enabled_server_side: true,
        'custom_limits_usd.surveys': 0,
        'custom_limits_usd.feature_flags': 0,
        $exception_capture_endpoint_suffix: '/e/',
        $web_vitals_allowed_metrics: null,
        utm_source: 'transactional',
        utm_medium: 'email',
        utm_campaign: 'billing_invoice_payment_failed',
        title: 'PostHog',
        token: 'sTMFPsFhdP1Ssg',
        $session_id: '01921df6-5303-7b86-8869-ce41a1dbc1f8',
        $window_id: '01921df6-5303-7b86-8869-ce4250ea5b9a',
        $lib_custom_api_host: 'https://internal-t.posthog.com',
        $is_identified: true,
        $lib_rate_limit_remaining_tokens: 98.07,
        $set_once: {
            $initial_os: 'Mac OS X',
            $initial_os_version: '10.15.7',
            $initial_browser: 'Chrome',
            $initial_device_type: 'Desktop',
            $initial_current_url: 'https://eu.posthog.com/login?next=/',
            $initial_pathname: '/login',
            $initial_browser_version: 129,
            $initial_referrer: '$direct',
            $initial_referring_domain: '$direct',
            $initial_utm_source: 'transactional',
            $initial_utm_medium: 'email',
            $initial_utm_campaign: 'billing_invoice_payment_failed',
            $initial_geoip_city_name: 'Stockholm',
            $initial_geoip_city_confidence: null,
            $initial_geoip_subdivision_2_name: null,
            $initial_geoip_subdivision_2_code: null,
            $initial_geoip_subdivision_2_confidence: null,
            $initial_geoip_subdivision_1_name: 'Stockholm County',
            $initial_geoip_subdivision_1_code: 'AB',
            $initial_geoip_subdivision_1_confidence: null,
            $initial_geoip_country_name: 'Sweden',
            $initial_geoip_country_code: 'SE',
            $initial_geoip_country_confidence: null,
            $initial_geoip_continent_name: 'Europe',
            $initial_geoip_continent_code: 'EU',
            $initial_geoip_postal_code: '113 65',
            $initial_geoip_postal_code_confidence: null,
            $initial_geoip_latitude: 59.3241,
            $initial_geoip_longitude: 18.0517,
            $initial_geoip_accuracy_radius: 5,
            $initial_geoip_time_zone: 'Europe/Stockholm',
            $initial_host: 'eu.posthog.com',
        },
        $ip: '85.230.98.14',
        $set: {
            $os: 'Mac OS X',
            $os_version: '10.15.7',
            $browser: 'Chrome',
            $device_type: 'Desktop',
            $current_url:
                'https://eu.posthog.com/organization/billing?utm_source=transactional&utm_medium=email&utm_campaign=billing_invoice_payment_failed',
            $pathname: '/organization/billing',
            $browser_version: 129,
            $referrer: '$direct',
            $referring_domain: '$direct',
            utm_source: 'transactional',
            utm_medium: 'email',
            utm_campaign: 'billing_invoice_payment_failed',
            $geoip_city_name: 'Stockholm',
            $geoip_city_confidence: null,
            $geoip_subdivision_2_name: null,
            $geoip_subdivision_2_code: null,
            $geoip_subdivision_2_confidence: null,
            $geoip_subdivision_1_name: 'Stockholm County',
            $geoip_subdivision_1_code: 'AB',
            $geoip_subdivision_1_confidence: null,
            $geoip_country_name: 'Sweden',
            $geoip_country_code: 'SE',
            $geoip_country_confidence: null,
            $geoip_continent_name: 'Europe',
            $geoip_continent_code: 'EU',
            $geoip_postal_code: '113 65',
            $geoip_postal_code_confidence: null,
            $geoip_latitude: 59.3241,
            $geoip_longitude: 18.0517,
            $geoip_accuracy_radius: 5,
            $geoip_time_zone: 'Europe/Stockholm',
        },
        $sent_at: '2024-09-23T08:18:55.377000+00:00',
        $geoip_city_name: 'Stockholm',
        $geoip_city_confidence: null,
        $geoip_country_name: 'Sweden',
        $geoip_country_code: 'SE',
        $geoip_country_confidence: null,
        $geoip_continent_name: 'Europe',
        $geoip_continent_code: 'EU',
        $geoip_postal_code: '113 65',
        $geoip_postal_code_confidence: null,
        $geoip_latitude: 59.3241,
        $geoip_longitude: 18.0517,
        $geoip_accuracy_radius: 5,
        $geoip_time_zone: 'Europe/Stockholm',
        $geoip_subdivision_1_code: 'AB',
        $geoip_subdivision_1_name: 'Stockholm County',
        $geoip_subdivision_1_confidence: null,
        $initial_person_info__r: '$direct',
        $initial_person_info__u: 'https://eu.posthog.com/login?next=/',
        $session_recording_network_payload_capture__capturePerformance__network_timing: true,
        $session_recording_network_payload_capture__capturePerformance__web_vitals: true,
        $session_recording_network_payload_capture__capturePerformance__web_vitals_allowed_metrics: null,
        $session_recording_network_payload_capture__recordBody: true,
        $session_recording_network_payload_capture__recordHeaders: true,
        $lib_version__major: 1,
        $lib_version__minor: 163,
        $lib_version__patch: 0,
        $group_2: '0185e861-1cbc-0000-34af-61669babf5d7',
        $group_0: '0185bfcf-f208-0000-7530-6be2046448e8',
        $group_3: 'cus_NEYt9TNQDy0wLw',
        $group_1: 'https://eu.posthog.com',
    },
    timestamp: '2024-09-23T01:18:55.837000-07:00',
    team_id: 2,
    distinct_id: 'wncF8BcNyRrHBlNU5pYZGS3bPSUNcNa7JJa0zSORJ5r',
    elements_chain: '',
    created_at: '2024-09-23T01:19:08.402000-07:00',
}

const person = {
    type: 'person',
    id: '0186b67d-e422-0000-039d-a56442580ed1',
    uuid: '0186b67d-e422-0000-039d-a56442580ed1',
    created_at: '2023-03-06T10:33:05.654000Z',
    properties: {
        $os: 'Mac OS X',
        email: 'herman.niclazon@ingrid.com',
        realm: 'cloud',
        $browser: 'Chrome',
        clearbit: {
            person: null,
            company: {
                id: 'a8f1d50f-1c8c-426b-ac45-248431a0a139',
                geo: {
                    lat: 59.33565209999999,
                    lng: 18.0630705,
                    city: 'Stockholm',
                    state: 'Stockholms län',
                    country: 'Sweden',
                    stateCode: null,
                    postalCode: '111 34',
                    streetName: 'Sveavägen',
                    subPremise: null,
                    countryCode: 'SE',
                    streetNumber: '21',
                    streetAddress: '21 Sveavägen',
                },
                logo: 'https://logo.clearbit.com/ingrid.com',
                name: 'Ingrid',
                site: {
                    phoneNumbers: ['+48 576 079 692'],
                    emailAddresses: [
                        'hello@ingrid.com',
                        'support@ingrid.com',
                        'anders@ingrid.com',
                        'privacy@ingrid.com',
                    ],
                },
                tags: ['Information Technology & Services', 'Technology', 'B2B', 'Marketplace'],
                tech: [
                    'hubspot',
                    'google_analytics',
                    'google_apps',
                    'hotjar',
                    'grafana',
                    'splunk',
                    'apache_tomcat',
                    'mongodb',
                    'github',
                    'klarna',
                    'postgresql',
                    'mysql',
                    'atlassian_jira',
                ],
                type: 'private',
                phone: null,
                domain: 'ingrid.com',
                parent: {
                    domain: null,
                },
                ticker: null,
                metrics: {
                    raised: 1400000,
                    employees: 90,
                    marketCap: null,
                    alexaUsRank: null,
                    trafficRank: 'medium_low',
                    annualRevenue: null,
                    fiscalYearEnd: null,
                    employeesRange: '51-250',
                    alexaGlobalRank: 795131,
                    estimatedAnnualRevenue: '$10M-$50M',
                },
                twitter: {
                    id: '2198924627',
                    bio: 'Ingrid Delivery Platform connects e-commerce merchants, carriers, and consumers to create a better shopping experience for everyone.',
                    site: 'https://t.co/G6cbVd8125',
                    avatar: 'https://pbs.twimg.com/profile_images/1580866190842404864/lA5Wl2b-_normal.jpg',
                    handle: 'poweredbyingrid',
                    location: 'Stockholm, Sweden',
                    followers: 484,
                    following: 278,
                },
                category: {
                    sector: 'Information Technology',
                    sicCode: '48',
                    industry: 'Internet Software & Services',
                    naicsCode: '51',
                    subIndustry: 'Internet Software & Services',
                    industryGroup: 'Software & Services',
                },
                facebook: {
                    likes: null,
                    handle: null,
                },
                linkedin: {
                    handle: 'company/ingridhq',
                },
                location: 'Sveavägen 21, 111 34 Stockholm, Sweden',
                timeZone: 'Europe/Stockholm',
                indexedAt: '2023-02-25T00:29:08.115Z',
                legalName: null,
                utcOffset: 1,
                crunchbase: {
                    handle: null,
                },
                identifiers: {
                    usEIN: null,
                },
                domainAliases: ['shipwallet.se', 'shipwallet.com'],
                emailProvider: false,
                techCategories: [
                    'marketing_automation',
                    'analytics',
                    'productivity',
                    'website_optimization',
                    'monitoring',
                    'data_processing',
                    'web_servers',
                    'database',
                    'payment',
                    'project_management_software',
                ],
                ultimateParent: {
                    domain: null,
                },
            },
        },
        utm_term: null,
        $pathname: '/project/14701/data-warehouse',
        $referrer: '$direct',
        joined_at: '2023-03-06T10:35:48.706085+00:00',
        org__name: 'Ingrid',
        strapi_id: null,
        project_id: '0185bfcf-f216-0000-9c8d-61e5ebac5405',
        utm_medium: 'email',
        utm_source: 'transactional',
        $initial_os: 'Mac OS X',
        $os_version: '10.15.7',
        utm_content: null,
        $current_url: 'https://eu.posthog.com/project/14701/data-warehouse',
        $device_type: 'Desktop',
        billing_plan: null,
        email_opt_in: false,
        instance_tag: 'none',
        instance_url: 'https://eu.posthog.com',
        is_signed_up: true,
        utm_campaign: 'billing_invoice_payment_failed',
        $initial_host: 'eu.posthog.com',
        hubspot_score: 18,
        is_first_user: false,
        project_count: 5,
        anonymize_data: false,
        $geoip_latitude: 59.3241,
        has_social_auth: false,
        organization_id: '0185bfcf-f208-0000-7530-6be2046448e8',
        referral_source: 'signed up from invite link',
        $browser_version: 129,
        $geoip_city_name: 'Stockholm',
        $geoip_longitude: 18.0517,
        $geoip_time_zone: 'Europe/Stockholm',
        $initial_browser: 'Chrome',
        has_password_set: true,
        social_providers: [],
        $initial_pathname: '/login',
        $initial_referrer: '$direct',
        $initial_utm_term: null,
        $referring_domain: '$direct',
        is_email_verified: true,
        org__member_count: 9,
        org__person_count: 301272,
        $geoip_postal_code: '113 65',
        org__project_count: 5,
        organization_count: 1,
        $creator_event_uuid: '0186b67d-e3ee-0002-2095-3ca556e3b8d8',
        $geoip_country_code: 'SE',
        $geoip_country_name: 'Sweden',
        $initial_os_version: '10.15.7',
        $initial_utm_medium: null,
        $initial_utm_source: null,
        $initial_current_url: 'https://eu.posthog.com/login?next=/home',
        $initial_device_type: 'Desktop',
        $initial_utm_content: null,
        role_at_organization: '',
        $geoip_continent_code: 'EU',
        $geoip_continent_name: 'Europe',
        $initial_utm_campaign: null,
        team_member_count_all: 12,
        $geoip_accuracy_radius: 5,
        $geoip_city_confidence: null,
        $initial_search_engine: 'google',
        new_onboarding_enabled: false,
        project_setup_complete: true,
        signup_social_provider: '',
        $initial_geoip_latitude: 50.1188,
        $initial_browser_version: 110,
        $initial_geoip_city_name: 'Frankfurt am Main',
        $initial_geoip_longitude: 8.6843,
        $initial_geoip_time_zone: 'Europe/Berlin',
        signup_backend_processor: 'OrganizationInviteSignupSerializer',
        $geoip_country_confidence: null,
        $geoip_subdivision_1_code: 'AB',
        $geoip_subdivision_1_name: 'Stockholm County',
        $geoip_subdivision_2_code: null,
        $geoip_subdivision_2_name: null,
        $initial_referring_domain: '$direct',
        completed_onboarding_once: true,
        $initial_geoip_postal_code: '60313',
        has_seen_product_intro_for: null,
        is_organization_first_user: false,
        $initial_geoip_country_code: 'DE',
        $initial_geoip_country_name: 'Germany',
        $geoip_postal_code_confidence: null,
        $initial_geoip_continent_code: 'EU',
        $initial_geoip_continent_name: 'Europe',
        $initial_geoip_accuracy_radius: 1000,
        $initial_geoip_city_confidence: null,
        $geoip_subdivision_1_confidence: null,
        $geoip_subdivision_2_confidence: null,
        $initial_geoip_country_confidence: null,
        $initial_geoip_subdivision_1_code: 'HE',
        $initial_geoip_subdivision_1_name: 'Hesse',
        $initial_geoip_subdivision_2_code: null,
        $initial_geoip_subdivision_2_name: null,
        $initial_geoip_postal_code_confidence: null,
        current_organization_membership_level: 1,
        $initial_geoip_subdivision_1_confidence: null,
        $initial_geoip_subdivision_2_confidence: null,
        '$survey_dismissed/0190ff15-5032-0000-722a-e13933c140ac': true,
    },
    is_identified: true,
    name: 'herman.niclazon@ingrid.com',
    distinct_ids: [
        'invite_0186b67d-5d5b-0000-cf40-7affc9b3dd98',
        'wncF8BcNyRrHBlNU5pYZGS3bPSUNcNa7JJa0zSORJ5r',
        '186b67b6421cd-0b885abde22e0b-1f525634-4b9600-186b67b64222599',
    ],
    matched_recordings: [],
    value_at_data_point: null,
}

describe.skip('benchamrk', () => {
    test('benchamrk', () => {
        const bytecode = [
            '_H',
            1,
            32,
            '%posthog.com%',
            32,
            'email',
            32,
            'properties',
            32,
            'person',
            1,
            3,
            20,
            32,
            '127.0.0.1:3000',
            32,
            '$host',
            32,
            'properties',
            1,
            2,
            12,
            32,
            '127.0.0.1:5000',
            32,
            '$host',
            32,
            'properties',
            1,
            2,
            12,
            32,
            'localhost:5000',
            32,
            '$host',
            32,
            'properties',
            1,
            2,
            12,
            32,
            'localhost:8000',
            32,
            '$host',
            32,
            'properties',
            1,
            2,
            12,
            32,
            'localhost:8001',
            32,
            '$host',
            32,
            'properties',
            1,
            2,
            12,
            32,
            'localhost',
            32,
            '$host',
            32,
            'properties',
            1,
            2,
            12,
            3,
            6,
            32,
            '%posthog.com%',
            32,
            'distinct_id',
            32,
            'properties',
            1,
            2,
            20,
            32,
            'capturi@capturi.com',
            32,
            'email',
            32,
            'properties',
            32,
            'person',
            1,
            3,
            12,
            32,
            'fuziontech@gmail.com',
            32,
            'email',
            32,
            'properties',
            32,
            'person',
            1,
            3,
            12,
            32,
            'demo',
            32,
            'realm',
            32,
            'properties',
            1,
            2,
            12,
            32,
            '71.84.26.175',
            32,
            '$ip',
            32,
            'properties',
            1,
            2,
            12,
            32,
            'corywatilo@gmail.com',
            32,
            'email',
            32,
            'properties',
            32,
            'person',
            1,
            3,
            12,
            32,
            '$pageview',
            32,
            'event',
            1,
            1,
            11,
            32,
            '%posthog.com/organization/billing%',
            32,
            '$current_url',
            32,
            'properties',
            1,
            2,
            17,
            31,
            32,
            '$group_0',
            32,
            'properties',
            1,
            2,
            12,
            3,
            3,
            3,
            9,
            4,
            1,
        ]
        const globals = {
            ...event,
            person,
        }
        const options = {
            globals,
            external: {
                regex: {
                    match: (regex: string, value: string) => new RE2(regex).test(value),
                },
            },
            telemetry: true,
        }
        // measure time
        const start = Date.now()
        for (let i = 0; i < 1000; i++) {
            exec(bytecode, options)
        }
        const end = Date.now()
        console.log('Execution time: %dms', end - start)

        const response = exec(bytecode, options)
        console.log(response)
        console.log(response.state?.telemetry)
    })
})
