from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Descriptions taken from the official SafetyCulture Data Feeds API docs
# (https://developer.safetyculture.com/reference/data-feeds).
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "inspections": {
        "description": "An inspection (audit) conducted from a template, with its score, timings, and location.",
        "docs_url": "https://developer.safetyculture.com/reference/thepubservice_feedinspections",
        "columns": {
            "id": "The ID of this inspection.",
            "name": "The name of this inspection.",
            "archived": "If this inspection is archived.",
            "organisation_id": "The organisation this inspection belongs to.",
            "owner_name": "The name of the user who created this inspection.",
            "owner_id": "The ID of the user who created this inspection.",
            "author_name": "The name of the user who last updated this inspection.",
            "author_id": "The ID of the user who last updated this inspection.",
            "score": "The score of this inspection.",
            "max_score": "The maximum score of this inspection.",
            "score_percentage": "The percentage of the inspection score.",
            "site_id": "The site this inspection was conducted at.",
            "template_id": "The ID of the template this inspection was conducted from.",
            "template_name": "The name of the template this inspection was conducted from.",
            "template_author": "The author of the template.",
            "date_started": "The date this inspection was started.",
            "date_completed": "The date this inspection was completed.",
            "date_modified": "The date this inspection was last updated.",
            "created_at": "The date this inspection was created on the server.",
            "modified_at": "The date this inspection was last updated on the server.",
            "latitude": "The latitude this inspection was conducted at.",
            "longitude": "The longitude this inspection was conducted at.",
            "document_no": "The document number of this inspection.",
            "prepared_by": "The user who created this inspection.",
            "location": "The location this inspection was conducted at.",
            "conducted_on": "The date this inspection was conducted.",
            "personnel": "The people involved in this inspection.",
            "client_site": "The site this inspection was conducted at.",
            "web_report_link": "The URL to the web report for this inspection.",
        },
    },
    "inspection_items": {
        "description": "A single question/item answered within an inspection, with its response, score, and media.",
        "docs_url": "https://developer.safetyculture.com/reference/thepubservice_feedinspectionitems",
        "columns": {
            "id": "Combined inspection item ID.",
            "item_id": "Item ID.",
            "audit_id": "Inspection ID.",
            "template_id": "Template ID.",
            "parent_id": "Parent item ID.",
            "organisation_id": "Organization that owns this inspection.",
            "created_at": "Created date for the inspection.",
            "modified_at": "Modified date for the inspection.",
            "type": "Type of question.",
            "category": "Name of the section this falls under.",
            "category_id": "ID of the section this falls under.",
            "parent_ids": "All parent IDs for this item.",
            "label": "Label of the item.",
            "response": "Response for the item.",
            "response_id": "ID of the response in the response set.",
            "response_set_id": "ID of the response set used for this item.",
            "is_failed_response": "If the response indicates a failure.",
            "comment": "Notes for the item.",
            "media_files": "Names of media files associated with this item.",
            "media_ids": "IDs of media files associated with this item.",
            "media_hypertext_reference": "URLs of media files associated with this item.",
            "score": "Score for this item; where this item has children it is the combined score of those children.",
            "max_score": "Max score for this item; where this item has children it is the combined max score of those children.",
            "score_percentage": "Score percentage for this item; where this item has children it is the combined score percentage of those children.",
            "combined_score": "Where this item has children, the combined score of those children, otherwise null.",
            "combined_max_score": "Where this item has children, the combined max score of those children, otherwise null.",
            "combined_score_percentage": "Where this item has children, the combined score percentage of those children, otherwise null.",
            "mandatory": "Item mandatory requirement.",
            "inactive": "Item visibility.",
            "location_latitude": "The latitude this inspection was conducted at.",
            "location_longitude": "The longitude this inspection was conducted at.",
            "primeelement_id": "For repeated sections/dynamic fields; consistent for every item under a repeated section.",
        },
    },
    "templates": {
        "description": "An inspection template that inspections are conducted from.",
        "docs_url": "https://developer.safetyculture.com/reference/thepubservice_feedtemplates",
        "columns": {
            "id": "Template ID.",
            "archived": "Indicates if the template is archived or not.",
            "name": "Template name.",
            "owner_name": "Owner name.",
            "owner_id": "ID of the owner.",
            "author_name": "Author name.",
            "author_id": "ID of the author.",
            "organisation_id": "ID of the organisation.",
            "created_at": "Date and time when the template was created.",
            "modified_at": "Date and time when the template was modified.",
        },
    },
    "actions": {
        "description": "A corrective action, optionally raised against an inspection item, with its priority, status, and assignment context.",
        "docs_url": "https://developer.safetyculture.com/reference/thepubservice_feedactions",
        "columns": {
            "id": "ID of the action.",
            "title": "Title of the action.",
            "site_id": "Site ID associated with the action.",
            "description": "Description of the action.",
            "priority": "Priority of the action.",
            "status": "Status of the action.",
            "due_date": "Due date of the action.",
            "creator_user_id": "User ID of the user who created this action.",
            "creator_user_name": "Name of the user who created this action.",
            "created_at": "Date this action was created.",
            "modified_at": "Date this action was last modified.",
            "template_id": "ID of the template this action was created against.",
            "organisation_id": "ID of the organisation that owns this action.",
            "audit_id": "ID of the inspection this action was created against.",
            "audit_title": "Title of the inspection this action was created against.",
            "audit_item_id": "ID of the item this action was created against.",
            "audit_item_label": "Label of the item this action was created against.",
            "completed_at": "Date this action was completed.",
            "action_label": "Action labels associated with the action in pipe-delimited format.",
            "unique_id": "Action unique ID.",
            "type_id": "Action type unique ID.",
            "type_name": "Action type name.",
        },
    },
    "issues": {
        "description": "An issue reported in SafetyCulture, with its category, priority, status, and linked inspection/site.",
        "docs_url": "https://developer.safetyculture.com/reference/thepubservice_feedissues",
        "columns": {
            "id": "ID of the issue.",
            "title": "Title of the issue.",
            "description": "Description of the issue.",
            "creator_id": "User ID of the user who created this issue.",
            "creator_user_name": "Name of the user who created this issue.",
            "created_at": "Date this issue was created.",
            "due_at": "Due date of the issue.",
            "priority": "Priority of the issue.",
            "status": "Status of the issue.",
            "template_id": "ID of the template this issue was created against.",
            "inspection_id": "ID of the inspection this issue was created against.",
            "inspection_name": "Title of the inspection this issue was created against.",
            "site_id": "Site ID associated with the issue.",
            "site_name": "Site name associated with the issue.",
            "location_name": "Location name associated with the issue.",
            "category_id": "Issue category ID.",
            "category_label": "Issue category label.",
            "category_description": "Issue category description.",
            "modified_at": "Date this issue was last modified.",
            "completed_at": "Date this issue was completed.",
            "unique_id": "Unique ID for the issue.",
            "occurred_at": "The configurable date that indicates when the issue occurred.",
        },
    },
    "assets": {
        "description": "An asset tracked in SafetyCulture, with its type, custom fields, site, and state.",
        "docs_url": "https://developer.safetyculture.com/reference/thepubservice_feedassets",
        "columns": {
            "id": "ID of the asset.",
            "code": "User-defined ID of the asset.",
            "type_id": "Type ID of the asset.",
            "type_name": "Type name of the asset.",
            "fields": "Fields associated to the asset type.",
            "created_at": "Date and time the asset was created in Coordinated Universal Time (UTC).",
            "modified_at": "Date and time the asset was modified in Coordinated Universal Time (UTC).",
            "site_id": "ID of the site associated with the asset.",
            "state": "Current state of the asset.",
        },
    },
    "users": {
        "description": "A user in your SafetyCulture organization.",
        "docs_url": "https://developer.safetyculture.com/reference/thepubservice_feedusers",
        "columns": {
            "id": "ID of the user.",
            "organisation_id": "ID of the organisation.",
            "email": "Email of the user.",
            "firstname": "First name of the user.",
            "lastname": "Last name of the user.",
            "active": "Indicates if the user is active or not.",
            "last_seen_at": "Date when the user was last seen.",
            "seat_type": "Seat type.",
            "created_at": "Created date for the user.",
        },
    },
    "groups": {
        "description": "A user group in your SafetyCulture organization.",
        "docs_url": "https://developer.safetyculture.com/reference/thepubservice_feedgroups",
        "columns": {
            "id": "ID of the group.",
            "organisation_id": "ID of the organisation.",
            "name": "Name of the group.",
        },
    },
    "sites": {
        "description": "A site (location, area, region, state, or country) in your SafetyCulture organization.",
        "docs_url": "https://developer.safetyculture.com/reference/thepubservice_feedsites",
        "columns": {
            "id": "ID of the site.",
            "site_uuid": "UUID of the site.",
            "name": "Site name.",
            "creator_id": "ID of the site creator.",
            "organisation_id": "ID of the organisation.",
            "deleted": "Indicates if the site is deleted or not.",
            "meta_label": "Type of site (location, area, region, state, country).",
            "parent_id": "ID of the parent of this site.",
        },
    },
    "schedules": {
        "description": "A recurring inspection schedule, with its recurrence pattern, template, and site.",
        "docs_url": "https://developer.safetyculture.com/reference/thepubservice_feedschedules",
        "columns": {
            "id": "ID of the schedule.",
            "description": "Description of the schedule.",
            "recurrence": "Recurrence pattern.",
            "duration": "Duration of the schedule.",
            "organisation_id": "ID of the organisation.",
            "from_date": "Start date.",
            "to_date": "End date.",
            "modified_at": "Last modified date.",
            "all_must_complete": "Whether all assignees must complete the schedule.",
            "timezone": "Timezone of the schedule.",
            "can_late_submit": "Allow inspections to be submitted after the due date.",
            "site_id": "ID of the site.",
            "template_id": "ID of the template.",
            "creator_user_id": "ID of the creator user.",
        },
    },
}
