from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Sourced from KnowBe4's Reporting API docs (https://developer.knowbe4.com/rest/reporting). Columns
# not covered here fall back to LLM enrichment, so partial coverage is fine; keys match the
# endpoint/schema names returned by `get_schemas`.
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "users": {
        "description": "Every user in the KnowBe4 account, one row per user, including their current phishing risk score.",
        "docs_url": "https://developer.knowbe4.com/rest/reporting#tag/Users/paths/~1v1~1users/get",
        "columns": {
            "id": "User ID.",
            "employee_number": "Employee number.",
            "first_name": "First name.",
            "last_name": "Last name.",
            "job_title": "Job title.",
            "email": "Email address.",
            "phish_prone_percentage": "Phish-prone percentage.",
            "phone_number": "Phone number.",
            "location": "Location.",
            "division": "Division.",
            "manager_name": "Manager's name.",
            "manager_email": "Manager's email.",
            "groups": "Array of group IDs (active or archived) the user is a member of.",
            "current_risk_score": "The user's current risk score.",
            "joined_on": "Date the user was added to the KnowBe4 account.",
            "last_sign_in": "Date the user last signed in to their KnowBe4 account.",
            "status": "Status of the user (active or archived).",
            "organization": "Organization.",
            "department": "Department.",
            "employee_start_date": "Employee start date.",
            "archived_at": "Date the user was archived, if applicable.",
        },
    },
    "groups": {
        "description": "Every group configured in the KnowBe4 account, one row per group.",
        "docs_url": "https://developer.knowbe4.com/rest/reporting#tag/Groups/paths/~1v1~1groups/get",
        "columns": {
            "id": "Group ID.",
            "name": "Group name.",
            "group_type": "Group type (console_group, smart_group, or provisioning_managed_group).",
            "member_count": "Number of members in the group.",
            "current_risk_score": "The group's current risk score.",
            "status": "Status of the group (active or archived).",
        },
    },
    "group_members": {
        "description": "Membership rows linking each group to its member users.",
        "docs_url": "https://developer.knowbe4.com/rest/reporting#tag/Users/paths/~1v1~1groups~1%7Bgroup_id%7D~1members/get",
        "columns": {
            "group_id": "ID of the group this membership row belongs to.",
            "id": "User ID of the member.",
            "email": "Member's email address.",
            "first_name": "Member's first name.",
            "last_name": "Member's last name.",
            "status": "Status of the member (active or archived).",
        },
    },
    "phishing_campaigns": {
        "description": "Phishing campaigns configured in the account, including aggregate results across all of the campaign's security tests.",
        "docs_url": "https://developer.knowbe4.com/rest/reporting#tag/Phishing/paths/~1v1~1phishing~1campaigns/get",
        "columns": {
            "campaign_id": "Unique ID of the phishing campaign.",
            "name": "Name of the phishing campaign.",
            "groups": "Array of groups targeted by the campaign.",
            "last_phish_prone_percentage": "Last phish-prone percentage recorded on the campaign.",
            "last_run": "Date and time of the last phishing security test in the campaign.",
            "status": "Status of the campaign.",
            "frequency": "How often the phishing campaign is configured to run.",
            "create_date": "Date and time the campaign was created.",
            "psts_count": "Number of phishing security tests in the campaign.",
            "psts": "Array of phishing security tests belonging to the campaign.",
        },
    },
    "phishing_security_tests": {
        "description": "Individual phishing security tests (PSTs), including delivery and interaction result counts.",
        "docs_url": "https://developer.knowbe4.com/rest/reporting#tag/Phishing/paths/~1v1~1phishing~1security_tests/get",
        "columns": {
            "campaign_id": "Unique ID of the phishing campaign the test belongs to.",
            "pst_id": "Unique ID of the phishing security test.",
            "status": "Status of the phishing security test.",
            "name": "Name of the phishing security test.",
            "phish_prone_percentage": "Phish-prone percentage on the test, in decimal form.",
            "started_at": "Date and time the phishing security test started.",
            "duration": "Duration of the phishing security test in calendar days.",
            "scheduled_count": "Number of users scheduled to receive phishing emails.",
            "delivered_count": "Number of users who received phishing emails.",
            "opened_count": "Number of users who opened the email.",
            "clicked_count": "Number of users who clicked.",
            "replied_count": "Number of users who replied.",
            "attachment_open_count": "Number of users who opened an attachment.",
            "data_entered_count": "Number of users who entered data on a landing page.",
            "qr_code_scanned_count": "Number of users who scanned a QR code.",
            "reported_count": "Number of users who reported the email using the Phish Alert Button.",
            "bounced_count": "Number of users whose phishing email bounced.",
        },
    },
    "phishing_security_test_recipients": {
        "description": "Per-recipient results for a phishing security test, one row per user targeted by the test.",
        "docs_url": "https://developer.knowbe4.com/rest/reporting#tag/Phishing/paths/~1v1~1phishing~1security_tests~1%7Bpst_id%7D~1recipients/get",
        "columns": {
            "recipient_id": "Unique ID of the recipient (user) within the phishing security test.",
            "pst_id": "Unique ID of the phishing security test this result belongs to.",
            "user": "Recipient user details (id, name, email).",
            "template": "The phishing template the recipient received.",
            "scheduled_at": "Date and time the user was scheduled to receive the phishing security test.",
            "delivered_at": "Date and time the user received the phishing security test.",
            "opened_at": "Date and time the user opened the phishing security test.",
            "clicked_at": "Date and time the user clicked.",
            "replied_at": "Date and time the user replied.",
            "attachment_opened_at": "Date and time the user opened an attachment.",
            "data_entered_at": "Date and time the user entered data on a landing page.",
            "qr_code_scanned": "Date and time the user scanned a QR code.",
            "reported_at": "Date and time the user reported the email using the Phish Alert Button.",
            "bounced_at": "Date and time the phishing email designated for this user bounced.",
            "ip": "User's IP address.",
            "ip_location": "User's geolocation.",
            "browser": "User's browser.",
            "os": "User's operating system.",
        },
    },
    "training_campaigns": {
        "description": "Training campaigns configured in the account, including assigned content and completion status.",
        "docs_url": "https://developer.knowbe4.com/rest/reporting#tag/Training/paths/~1v1~1training~1campaigns/get",
        "columns": {
            "campaign_id": "Campaign ID.",
            "name": "Campaign name.",
            "groups": "Array of groups targeted by the campaign.",
            "status": "Campaign status (Created, Enrolling, In Progress, Completed, Cancelled).",
            "content": "Array of Store Purchases and uploaded policies included in the campaign.",
            "duration_type": "Duration type (Specific End Date, Relative End Date, No End Date).",
            "start_date": "Start date/time.",
            "end_date": "End date/time.",
            "auto_enroll": "Whether users added to the targeted groups are automatically enrolled.",
            "completion_percentage": "Percentage of completed enrollments (-1 if too large to calculate).",
        },
    },
    "training_enrollments": {
        "description": "Individual user enrollments in training campaign content (modules or uploaded policies).",
        "docs_url": "https://developer.knowbe4.com/rest/reporting#tag/Training/paths/~1v1~1training~1enrollments/get",
        "columns": {
            "enrollment_id": "Enrollment ID.",
            "content_type": "Whether the enrollment is for a Store Purchase or an Uploaded Policy.",
            "module_name": "Name of the module or title of the uploaded policy.",
            "user": "Enrolled user's id, name, and email.",
            "campaign_name": "Name of the training campaign the enrollment belongs to.",
            "enrollment_date": "Enrollment date.",
            "start_date": "Assignment start date.",
            "completion_date": "Assignment completion date.",
            "status": "Completion status (Not Started, In Progress, Completed, Passed, Past Due).",
            "time_spent": "Time spent on the assignment, in seconds.",
            "policy_acknowledged": "Whether the course-attached URL policy was acknowledged, if applicable.",
        },
    },
}
