import os

AIRBYTE_API_KEY = os.getenv("AIRBYTE_API_KEY", None)
AIRBYTE_WORKSPACE_ID = os.getenv("AIRBYTE_WORKSPACE_ID", None)
AIRBYTE_INSTANCE_NAME = os.getenv("AIRBYTE_INSTANCE_NAME", None)
AIRBYTE_DESTINATION_ID = os.getenv("AIRBYTE_DESTINATION_ID", None)
