import { Meta, StoryFn, StoryObj } from '@storybook/react'
import { now } from 'lib/dayjs'
import { LemonDivider } from 'lib/lemon-ui/LemonDivider'
import { ItemEvent, ItemEventProps } from 'scenes/session-recordings/player/inspector/components/ItemEvent'
import { InspectorListItemEvent } from 'scenes/session-recordings/player/inspector/playerInspectorLogic'

import { mswDecorator } from '~/mocks/browser'
import { RecordingEventType, SessionRecordingPlayerTab } from '~/types'

type Story = StoryObj<typeof ItemEvent>
const meta: Meta<typeof ItemEvent> = {
    title: 'Components/PlayerInspector/ItemEvent',
    component: ItemEvent,
    decorators: [
        mswDecorator({
            get: {},
        }),
    ],
}
export default meta

function makeItem(
    itemOverrides: Partial<InspectorListItemEvent> = {},
    dataOverrides: Partial<RecordingEventType> = {},
    propertiesOverrides: Record<string, any> = {}
): InspectorListItemEvent {
    const data: RecordingEventType = {
        elements: [],
        event: '',
        fullyLoaded: true,
        id: '',
        playerTime: 0,

        timestamp: '',
        ...dataOverrides,
        // this is last so that it overrides data overrides sensibly 🙃
        properties: {
            ...propertiesOverrides,
        },
    }
    return {
        data: data,
        search: '',
        timeInRecording: 0,
        timestamp: now(),
        type: SessionRecordingPlayerTab.EVENTS,
        ...itemOverrides,
    }
}

const BasicTemplate: StoryFn<typeof ItemEvent> = (props: Partial<ItemEventProps>) => {
    const item = makeItem()
    props.item = props.item || item
    props.setExpanded = props.setExpanded || (() => {})

    const propsToUse = props as ItemEventProps

    return (
        <div className="flex flex-col gap-2">
            <h3>Collapsed</h3>
            <ItemEvent {...propsToUse} expanded={false} />
            <LemonDivider />
            <h3>Expanded</h3>
            <ItemEvent {...propsToUse} expanded={true} />
        </div>
    )
}

export const Default: Story = BasicTemplate.bind({})
Default.args = {}

export const PageViewWithPath: Story = BasicTemplate.bind({})
PageViewWithPath.args = {
    item: makeItem({}, { event: '$pageview' }, { $pathname: '/some/path' }),
}

export const PageViewWithCurrentURL: Story = BasicTemplate.bind({})
PageViewWithCurrentURL.args = {
    item: makeItem({}, { event: '$pageview' }, { $current_url: 'https://my-site.io/some/path' }),
}

export const ErrorEvent: Story = BasicTemplate.bind({})
ErrorEvent.args = {
    item: makeItem(
        {},
        { event: '$exception' },
        {
            $exception_message: 'Something went wrong',
            $exception_type: 'Error',
            $exception_personURL: 'https://my-site.io/person/123',
            $lib: 'web',
            $lib_version: '1.187.234',
            $browser: 'Chrome',
            $browser_version: 180,
            $os: 'Windows',
            $os_version: '11',
        }
    ),
}

export const SentryErrorEvent: Story = BasicTemplate.bind({})
SentryErrorEvent.args = {
    item: makeItem(
        {},
        { event: '$exception' },
        {
            $sentry_url: 'https://some-sentry-url',
            $exception_message: 'Something went wrong',
            $exception_type: 'Error',
            $exception_personURL: 'https://my-site.io/person/123',
            $lib: 'web',
            $lib_version: '1.187.234',
            $browser: 'Chrome',
            $browser_version: 180,
            $os: 'Windows',
            $os_version: '11',
        }
    ),
}

export const WebVitalsEvent: Story = BasicTemplate.bind({})
WebVitalsEvent.args = {
    item: makeItem(
        {},
        { event: '$web_vitals' },
        {
            $os: 'Mac OS X',
            $os_version: '10.15.7',
            $browser: 'Chrome',
            $device_type: 'Desktop',
            $current_url:
                'http://localhost:8000/project/1/activity/explore?simpleFilters=%7B%22events%22%3A%5B%5D%2C%22properties%22%3A%5B%5D%7D&advancedFilters=%7B%22session_recording_duration%22%3A%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A1%2C%22operator%22%3A%22gt%22%7D%2C%22properties%22%3A%5B%5D%2C%22events%22%3A%5B%5D%2C%22actions%22%3A%5B%5D%2C%22date_from%22%3A%22-3d%22%2C%22date_to%22%3Anull%2C%22console_logs%22%3A%5B%5D%2C%22snapshot_source%22%3Anull%2C%22console_search_query%22%3A%22%22%2C%22operand%22%3A%22AND%22%7D',
            $host: 'localhost:8000',
            $pathname: '/project/1/activity/explore',
            $raw_user_agent:
                'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
            $browser_version: 126,
            $browser_language: 'en-GB',
            $screen_height: 982,
            $screen_width: 1512,
            $viewport_height: 823,
            $viewport_width: 1512,
            $lib: 'web',
            $lib_version: '1.141.4',
            $insert_id: 'f1bpyyju917oeue3',
            $time: 1719484490.695,
            distinct_id: 'tlqVVCkzXPYJFDgN0Wh4kEZELMQSgCaX97Ny43YoCZd',
            $device_id: '019036ae-41ee-796e-ac21-071d67db33a8',
            $initial_person_info: {
                r: 'http://localhost:8000/signup',
                u: 'http://localhost:8000/',
            },
            $user_id: 'tlqVVCkzXPYJFDgN0Wh4kEZELMQSgCaX97Ny43YoCZd',
            is_demo_project: false,
            $groups: {
                project: '019036ae-3cc2-0000-cba9-085984a69382',
                organization: '019036ae-3560-0000-15ce-fb156f28f55f',
                instance: 'http://localhost:8000',
                customer: 'cus_QKuQnfRGeqqdm4',
            },
            realm: 'hosted-clickhouse',
            email_service_available: false,
            slack_service_available: false,
            commit_sha: '8cda57c195',
            $active_feature_flags: [
                'funnels-cue-opt-out-7301',
                'billing-limit',
                'kafka-inspector',
                'historical-exports-v2',
                'person-on-events-enabled',
                'ingestion-warnings-enabled',
                'debug-react-renders',
                'auto-rollback-feature-flags',
                'onboarding-v2-demo',
                'query_running_time',
                'query-timings',
                'query-async',
                'hedgehog-mode',
                'hedgehog-mode-debug',
                'high-frequency-batch-exports',
                'person-batch-exports',
                'exception-autocapture',
                'data-warehouse',
                'ff-dashboard-templates',
                'show-product-intro-existing-products',
                'artificial-hog',
                'cs-dashboards',
                'product-specific-onboarding',
                'redirect-signups-to-instance',
                'apps-and-exports-ui',
                'hogql-dashboard-cards',
                'hogql-dashboard-async',
                'webhooks-denylist',
                'persons-hogql-query',
                'pipeline-ui',
                'person-feed-canvas',
                'feature-flag-cohort-creation',
                'insight-horizontal-controls',
                'surveys-widgets',
                'surveys-events',
                'surveys-recurring',
                'year-in-hog',
                'session-replay-export-mobile-data',
                'discussions',
                'redirect-insight-creation-product-analytics-onboarding',
                'ai-session-summary',
                'ai-session-permissions',
                'product-intro-pages',
                'session-replay-doctor',
                'session-replay-similar-recordings',
                'saved-not-pinned',
                'new-experiments-ui',
                'session-replay-filter-ordering',
                'session-replay-error-clustering',
                'audit-logs-access',
                'subscribe-from-paygate',
                'session-replay-mobile-onboarding',
                'heatmaps-ui',
                'theme',
                'plugins-filtering',
                'session-replay-hogql-filtering',
                'insight-loading-bar',
                'proxy-as-a-service',
                'live-events',
                'session-replay-network-view',
                'settings-persons-join-mode',
                'settings-persons-on-events-hidden',
                'hog',
                'hog-functions',
                'personless-events-not-supported',
                'session-replay-universal-filters',
                'alerts',
                'error-tracking',
                'settings-bounce-rate-page-view-mode',
                'surveys-branching-logic',
                'subscribe-to-all-products',
            ],
            '$feature/funnels-cue-opt-out-7301': true,
            '$feature/billing-limit': true,
            '$feature/kafka-inspector': true,
            '$feature/historical-exports-v2': true,
            '$feature/person-on-events-enabled': true,
            '$feature/ingestion-warnings-enabled': true,
            '$feature/debug-react-renders': true,
            '$feature/auto-rollback-feature-flags': true,
            '$feature/onboarding-v2-demo': true,
            '$feature/query_running_time': true,
            '$feature/query-timings': true,
            '$feature/query-async': true,
            '$feature/hedgehog-mode': true,
            '$feature/hedgehog-mode-debug': true,
            '$feature/high-frequency-batch-exports': true,
            '$feature/person-batch-exports': true,
            '$feature/exception-autocapture': true,
            '$feature/data-warehouse': true,
            '$feature/ff-dashboard-templates': true,
            '$feature/show-product-intro-existing-products': true,
            '$feature/artificial-hog': true,
            '$feature/cs-dashboards': true,
            '$feature/product-specific-onboarding': true,
            '$feature/redirect-signups-to-instance': true,
            '$feature/apps-and-exports-ui': true,
            '$feature/hogql-dashboard-cards': true,
            '$feature/hogql-dashboard-async': true,
            '$feature/webhooks-denylist': true,
            '$feature/persons-hogql-query': true,
            '$feature/pipeline-ui': true,
            '$feature/person-feed-canvas': true,
            '$feature/feature-flag-cohort-creation': true,
            '$feature/insight-horizontal-controls': true,
            '$feature/surveys-widgets': true,
            '$feature/surveys-events': true,
            '$feature/surveys-recurring': true,
            '$feature/year-in-hog': true,
            '$feature/session-replay-export-mobile-data': true,
            '$feature/discussions': true,
            '$feature/redirect-insight-creation-product-analytics-onboarding': true,
            '$feature/ai-session-summary': true,
            '$feature/ai-session-permissions': true,
            '$feature/product-intro-pages': true,
            '$feature/session-replay-doctor': true,
            '$feature/session-replay-similar-recordings': true,
            '$feature/saved-not-pinned': true,
            '$feature/new-experiments-ui': true,
            '$feature/session-replay-filter-ordering': true,
            '$feature/session-replay-error-clustering': true,
            '$feature/audit-logs-access': true,
            '$feature/subscribe-from-paygate': true,
            '$feature/session-replay-mobile-onboarding': true,
            '$feature/heatmaps-ui': true,
            '$feature/theme': true,
            '$feature/plugins-filtering': true,
            '$feature/session-replay-hogql-filtering': true,
            '$feature/insight-loading-bar': true,
            '$feature/proxy-as-a-service': true,
            '$feature/live-events': true,
            '$feature/session-replay-network-view': true,
            '$feature/settings-persons-join-mode': true,
            '$feature/settings-persons-on-events-hidden': true,
            '$feature/hog': true,
            '$feature/hog-functions': true,
            '$feature/personless-events-not-supported': true,
            '$feature/session-replay-universal-filters': true,
            '$feature/alerts': true,
            '$feature/error-tracking': true,
            '$feature/settings-bounce-rate-page-view-mode': true,
            '$feature/surveys-branching-logic': true,
            '$feature/subscribe-to-all-products': true,
            $feature_flag_payloads: {},
            $session_recording_network_payload_capture: {
                capturePerformance: true,
            },
            $session_recording_canvas_recording: {},
            $replay_sample_rate: null,
            $replay_minimum_duration: null,
            $autocapture_disabled_server_side: false,
            has_billing_plan: true,
            $console_log_recording_enabled_server_side: true,
            $exception_capture_enabled_server_side: true,
            customer_deactivated: false,
            current_total_amount_usd: '0.00',
            'percentage_usage.product_analytics': 0,
            'current_amount_usd.product_analytics': null,
            'unit_amount_usd.product_analytics': null,
            'usage_limit.product_analytics': 1000000,
            'current_usage.product_analytics': 0,
            'projected_usage.product_analytics': 0,
            'free_allocation.product_analytics': 1000000,
            'percentage_usage.session_replay': 0,
            'current_amount_usd.session_replay': '0.00',
            'unit_amount_usd.session_replay': null,
            'usage_limit.session_replay': null,
            'current_usage.session_replay': 0,
            'projected_usage.session_replay': 0,
            'free_allocation.session_replay': 0,
            'percentage_usage.feature_flags': 0,
            'current_amount_usd.feature_flags': null,
            'unit_amount_usd.feature_flags': null,
            'usage_limit.feature_flags': 1000000,
            'current_usage.feature_flags': 0,
            'projected_usage.feature_flags': 0,
            'free_allocation.feature_flags': 1000000,
            'percentage_usage.surveys': 0,
            'current_amount_usd.surveys': null,
            'unit_amount_usd.surveys': null,
            'usage_limit.surveys': 250,
            'current_usage.surveys': 0,
            'projected_usage.surveys': 0,
            'free_allocation.surveys': 250,
            'percentage_usage.integrations': 0,
            'current_amount_usd.integrations': null,
            'unit_amount_usd.integrations': null,
            'usage_limit.integrations': 0,
            'current_usage.integrations': 0,
            'projected_usage.integrations': 0,
            'free_allocation.integrations': 0,
            'percentage_usage.platform_and_support': 0,
            'current_amount_usd.platform_and_support': null,
            'unit_amount_usd.platform_and_support': null,
            'usage_limit.platform_and_support': 0,
            'current_usage.platform_and_support': 0,
            'projected_usage.platform_and_support': 0,
            'free_allocation.platform_and_support': 0,
            billing_period_start: {
                $L: 'en',
                $d: {},
                $x: {},
                $y: 2024,
                $M: 5,
                $D: 21,
                $W: 5,
                $H: 22,
                $m: 3,
                $s: 0,
                $ms: 0,
            },
            billing_period_end: {
                $L: 'en',
                $d: {},
                $x: {},
                $y: 2024,
                $M: 6,
                $D: 21,
                $W: 0,
                $H: 22,
                $m: 3,
                $s: 0,
                $ms: 0,
            },
            $web_vitals_enabled_server_side: false,
            $exception_capture_endpoint: '/e/',
            $referrer: '$direct',
            $referring_domain: '$direct',
            $web_vitals_INP_event: {
                name: 'INP',
                value: 72,
                rating: 'good',
                delta: 72,
                entries: [{}, {}],
                id: 'v4-1719484470693-6845621238957',
                navigationType: 'reload',
                $current_url:
                    'http://localhost:8000/project/1/activity/explore?simpleFilters=%7B%22events%22%3A%5B%5D%2C%22properties%22%3A%5B%5D%7D&advancedFilters=%7B%22session_recording_duration%22%3A%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A1%2C%22operator%22%3A%22gt%22%7D%2C%22properties%22%3A%5B%5D%2C%22events%22%3A%5B%5D%2C%22actions%22%3A%5B%5D%2C%22date_from%22%3A%22-3d%22%2C%22date_to%22%3Anull%2C%22console_logs%22%3A%5B%5D%2C%22snapshot_source%22%3Anull%2C%22console_search_query%22%3A%22%22%2C%22operand%22%3A%22AND%22%7D',
                $session_id: '0190593b-0f3c-7e04-846a-f3515aa31c2f',
                $window_id: '01905942-b7ba-7c05-85d3-5d7548868b44',
                timestamp: 1719484490693,
            },
            $web_vitals_INP_value: 72,
            $web_vitals_CLS_event: {
                name: 'CLS',
                value: 0.10656105463687347,
                rating: 'needs-improvement',
                delta: 0.10656105463687347,
                entries: [{}, {}, {}, {}, {}, {}, {}, {}, {}],
                id: 'v4-1719484470710-6118725051157',
                navigationType: 'reload',
                $current_url:
                    'http://localhost:8000/project/1/activity/explore?simpleFilters=%7B%22events%22%3A%5B%5D%2C%22properties%22%3A%5B%5D%7D&advancedFilters=%7B%22session_recording_duration%22%3A%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A1%2C%22operator%22%3A%22gt%22%7D%2C%22properties%22%3A%5B%5D%2C%22events%22%3A%5B%5D%2C%22actions%22%3A%5B%5D%2C%22date_from%22%3A%22-3d%22%2C%22date_to%22%3Anull%2C%22console_logs%22%3A%5B%5D%2C%22snapshot_source%22%3Anull%2C%22console_search_query%22%3A%22%22%2C%22operand%22%3A%22AND%22%7D',
                $session_id: '0190593b-0f3c-7e04-846a-f3515aa31c2f',
                $window_id: '01905942-b7ba-7c05-85d3-5d7548868b44',
                timestamp: 1719484490693,
            },
            $web_vitals_CLS_value: 0.10656105463687347,
            token: 'phc_R1mwJgw25z5NnoMZkw64siDL7bwJH5A2FyldUmhCRG7',
            $session_id: '0190593b-0f3c-7e04-846a-f3515aa31c2f',
            $window_id: '01905942-b7ba-7c05-85d3-5d7548868b44',
            $lib_custom_api_host: 'http://localhost:8000',
            $is_identified: true,
            $lib_rate_limit_remaining_tokens: 99,
            $set_once: {
                $initial_os: 'Mac OS X',
                $initial_os_version: '10.15.7',
                $initial_browser: 'Chrome',
                $initial_device_type: 'Desktop',
                $initial_current_url: 'http://localhost:8000/',
                $initial_pathname: '/',
                $initial_browser_version: 126,
                $initial_referrer: 'http://localhost:8000/signup',
                $initial_referring_domain: 'localhost:8000',
                $initial_host: 'localhost:8000',
            },
            $ip: '127.0.0.1',
            $set: {
                $os: 'Mac OS X',
                $os_version: '10.15.7',
                $browser: 'Chrome',
                $device_type: 'Desktop',
                $current_url:
                    'http://localhost:8000/project/1/activity/explore?simpleFilters=%7B%22events%22%3A%5B%5D%2C%22properties%22%3A%5B%5D%7D&advancedFilters=%7B%22session_recording_duration%22%3A%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A1%2C%22operator%22%3A%22gt%22%7D%2C%22properties%22%3A%5B%5D%2C%22events%22%3A%5B%5D%2C%22actions%22%3A%5B%5D%2C%22date_from%22%3A%22-3d%22%2C%22date_to%22%3Anull%2C%22console_logs%22%3A%5B%5D%2C%22snapshot_source%22%3Anull%2C%22console_search_query%22%3A%22%22%2C%22operand%22%3A%22AND%22%7D',
                $pathname: '/project/1/activity/explore',
                $browser_version: 126,
                $referrer: '$direct',
                $referring_domain: '$direct',
            },
            $sent_at: '2024-06-27T10:34:53.804000+00:00',
            $geoip_city_name: 'Sydney',
            $geoip_country_name: 'Australia',
            $geoip_country_code: 'AU',
            $geoip_continent_name: 'Oceania',
            $geoip_continent_code: 'OC',
            $geoip_postal_code: '2000',
            $geoip_latitude: -33.8715,
            $geoip_longitude: 151.2006,
            $geoip_time_zone: 'Australia/Sydney',
            $geoip_subdivision_1_code: 'NSW',
            $geoip_subdivision_1_name: 'New South Wales',
            $plugins_succeeded: ['GeoIP (1)'],
            $plugins_failed: [],
            $group_0: '019036ae-3cc2-0000-cba9-085984a69382',
            $group_1: '019036ae-3560-0000-15ce-fb156f28f55f',
            $group_2: 'http://localhost:8000',
            $group_3: 'cus_QKuQnfRGeqqdm4',
        }
    ),
}
