from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "mentions": {
        "description": "Posts Octolens collected from social, community and developer platforms because they matched one of the workspace's monitored keywords, each scored by the AI for relevance and sentiment.",
        "docs_url": "https://octolens.com/docs/api-reference/mentions/list-mentions",
        "columns": {
            "id": "Internal numeric post id.",
            "sourceId": "Stable composite key for the mention across the collection pipeline, for example `reddit_t3_1abc234`.",
            "url": "Canonical URL of the original post.",
            "title": "Post title. Null on platforms that have no titles, such as X posts.",
            "body": "Post body or content. May be empty or null for posts with no text.",
            "source": "Platform the mention was collected from, for example `reddit`, `twitter` or `linkedin`. Historical rows may be uppercase.",
            "timestamp": "When the mention was posted, as `YYYY-MM-DD HH:MM:SS.SSS` in UTC with no offset suffix.",
            "author": "Handle or username of the author. Null if not captured.",
            "authorName": "Display name of the author, when it differs from the handle.",
            "authorAvatar": "URL of the author's avatar image.",
            "authorUrl": "URL of the author's profile page.",
            "authorFollowers": "Author's follower count at collection time.",
            "relevance": "AI relevance verdict, either `relevant` or `not_relevant`. Unscored posts collapse to `not_relevant`.",
            "relevanceScore": "Raw internal relevance score: 0 is high, 1 is medium, 2 is low. `relevance` is derived from this.",
            "relevanceComment": "Free-text justification the AI produced for its relevance verdict.",
            "sentiment": "AI sentiment classification: `Positive`, `Neutral` or `Negative`. Null until the mention has been scored.",
            "language": "ISO 639-1 language code detected by the pipeline.",
            "tags": "AI-assigned topic tags applied to the mention, for example `buy_intent`, `bug_report` or `pricing`.",
            "keywords": "Monitored keywords this mention matched, each with its id and display text.",
            "keywordId": "First matched keyword id, denormalized so callers do not have to scan `keywords`.",
            "engaged": "Whether a workspace member marked this mention as engaged with, for example replied to or liked on the platform.",
            "feedbackRelevant": "Relevance feedback a member left on this mention: 1 for thumbs up, -1 for thumbs down, 0 for none.",
            "imageUrl": "URL of a preview image attached to the post, when present.",
        },
    },
    "keywords": {
        "description": "Phrases the workspace monitors. Each keyword drives collection on the platforms it is enabled for and carries the matching rules and exclusions applied before a post becomes a mention.",
        "docs_url": "https://octolens.com/docs/api-reference/keywords/list-keywords",
        "columns": {
            "id": "Stable numeric keyword id.",
            "keyword": "The phrase being tracked.",
            "context": "Short sentence disambiguating the keyword for AI relevance scoring.",
            "additionalTerms": "Comma-separated terms that must appear alongside the main keyword.",
            "additionalTermsAndOr": "How `additionalTerms` combine: true means any one must appear, false means all must appear.",
            "caseSensitive": "Whether matching is case-sensitive.",
            "symbolSensitive": "Exact match in the UI. When true, the words of a multi-word keyword must appear together.",
            "platforms": "Platforms this keyword is monitored on.",
            "excludeWords": "Comma-separated words that disqualify a post if present.",
            "wildcardExcludeWords": "Comma-separated wildcard exclusion patterns, where `*` matches a prefix or suffix.",
            "excludeAuthors": "Comma-separated author handles whose posts are filtered out.",
            "tag": "Classification of the keyword: `own_brand`, `competitor` or `industry_term`. Null for legacy keywords.",
            "paused": "When true, data collection is paused for this keyword.",
            "isSubReddit": "When true, the keyword is a subreddit to monitor rather than a free-text phrase.",
        },
    },
    "feeds": {
        "description": "Saved filters over the mentions stream. A feed combines a filter definition with the notification destinations attached to it.",
        "docs_url": "https://octolens.com/docs/api-reference/feeds/list-feeds",
        "columns": {
            "id": "Feed id.",
            "name": "Display name shown in the app and included in notifications.",
            "icon": "Icon identifier used for display.",
            "simpleFilters": "Flat filter definition, as field to values pairs.",
            "advancedFilters": "Grouped filter definition with AND/OR operators.",
            "isDefault": "Whether this feed is pinned as the workspace's default view.",
            "destinations": "Notification destinations attached to the feed. An empty array means the feed sends nothing.",
            "createdAt": "When the feed was created.",
            "updatedAt": "When the feed was last updated.",
        },
    },
    "notifications": {
        "description": "Delivery rules. Mentions matching the linked feed's filters are sent to the notification's configured email, Slack or webhook destinations.",
        "docs_url": "https://octolens.com/docs/api/v2/overview",
        "columns": {
            "id": "Notification id.",
            "name": "Display name shown in the app and included in deliveries.",
            "enabled": "When false, the notification is paused and nothing is delivered.",
            "feedId": "The feed whose filters decide which mentions trigger this notification.",
            "feedName": "Display name of the linked feed.",
            "destinations": "Configured delivery destinations, at most one per type of `EMAIL`, `SLACK` or `WEBHOOK`.",
            "createdAt": "When the notification was created.",
            "updatedAt": "When the notification was last updated.",
        },
    },
    "org_members": {
        "description": "People who belong to the authenticated Octolens workspace.",
        "docs_url": "https://octolens.com/docs/api/v2/overview",
        "columns": {
            "id": "Membership id. This is not the user id.",
            "userId": "User id of the member.",
            "email": "Primary email on the member's profile.",
            "firstName": "First name, if set on the profile.",
            "lastName": "Last name, if set on the profile.",
            "role": "Role within the workspace, either `admin` or `member`.",
            "createdAt": "When the member joined the workspace.",
        },
    },
}
