"""Canonical, documentation-sourced descriptions for Lightspeed Retail (X-Series) endpoints and columns.

Sourced from the official Lightspeed X-Series (formerly Vend) API 2.0 reference
(https://x-series-api.lightspeedhq.com/reference). Keyed by the endpoint names in `settings.py`
`LIGHTSPEED_RETAIL_ENDPOINTS`, which match the `ExternalDataSchema.name` of a synced table. Every
record carries a monotonically increasing integer `version` used as the incremental cursor. Columns
absent here fall back to LLM enrichment.
"""

from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Fields shared by most X-Series objects; merged into each entry so we don't repeat them.
_COMMON_COLUMNS = {
    "id": "Unique identifier for the object.",
    "version": "Monotonically increasing version number, incremented whenever the record changes.",
    "deleted_at": "Time at which the object was deleted, if it has been deleted.",
}


def _columns(**overrides: str) -> dict[str, str]:
    return {**_COMMON_COLUMNS, **overrides}


CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "sales": {
        "description": "A point-of-sale transaction (a register sale) in Lightspeed Retail.",
        "docs_url": "https://x-series-api.lightspeedhq.com/reference/listsales",
        "columns": _columns(
            outlet_id="ID of the outlet where the sale took place.",
            register_id="ID of the register the sale was made on.",
            user_id="ID of the user (cashier) who made the sale.",
            customer_id="ID of the customer the sale is associated with, if any.",
            status="Status of the sale (e.g. CLOSED, OPEN, ONACCOUNT, LAYBY, VOIDED).",
            total_price="Total price of the sale excluding tax.",
            total_tax="Total tax charged on the sale.",
            note="Free-form note attached to the sale.",
            line_items="The products sold in this transaction.",
            payments="Payments applied to the sale.",
            sale_date="Date and time the sale occurred.",
            created_at="Time at which the sale record was created.",
            updated_at="Time at which the sale was last updated.",
        ),
    },
    "customers": {
        "description": "A customer record in Lightspeed Retail.",
        "docs_url": "https://x-series-api.lightspeedhq.com/reference/listcustomers",
        "columns": _columns(
            customer_code="Your own code identifying the customer.",
            first_name="The customer's first name.",
            last_name="The customer's last name.",
            company_name="The customer's company name, if any.",
            email="The customer's email address.",
            phone="The customer's phone number.",
            mobile="The customer's mobile number.",
            customer_group_id="ID of the customer group the customer belongs to.",
            balance="The customer's outstanding account balance.",
            year_to_date="Total the customer has spent year to date.",
            created_at="Time at which the customer was created.",
            updated_at="Time at which the customer was last updated.",
        ),
    },
    "products": {
        "description": "A product in the Lightspeed Retail catalog.",
        "docs_url": "https://x-series-api.lightspeedhq.com/reference/listproducts",
        "columns": _columns(
            name="The product's name.",
            handle="The product's URL-friendly handle.",
            sku="The product's stock-keeping unit (SKU).",
            description="Description of the product.",
            supply_price="Cost price paid to acquire the product.",
            brand_id="ID of the product's brand.",
            supplier_id="ID of the product's supplier.",
            product_type_id="ID of the product's type.",
            active="Whether the product is active.",
            is_composite="Whether the product is a composite (bundle) of other products.",
            has_variants="Whether the product has variants.",
            variant_parent_id="ID of the parent product if this is a variant.",
            created_at="Time at which the product was created.",
            updated_at="Time at which the product was last updated.",
        ),
    },
    "inventory": {
        "description": "Per-outlet stock levels for a product in Lightspeed Retail.",
        "docs_url": "https://x-series-api.lightspeedhq.com/reference/listinventory",
        "columns": _columns(
            product_id="ID of the product this inventory record is for.",
            outlet_id="ID of the outlet the stock is held at.",
            current_amount="Current quantity on hand at the outlet.",
            reorder_point="Stock level at which the product should be reordered.",
            reorder_amount="Quantity to reorder when the reorder point is reached.",
        ),
    },
    "outlets": {
        "description": "A physical store location (outlet) in Lightspeed Retail.",
        "docs_url": "https://x-series-api.lightspeedhq.com/reference/listoutlets",
        "columns": _columns(
            name="The outlet's name.",
            time_zone="The outlet's time zone.",
            currency="The currency the outlet trades in.",
            physical_address_1="First line of the outlet's physical address.",
            physical_city="City of the outlet's physical address.",
            physical_country_id="Country of the outlet's physical address.",
        ),
    },
    "registers": {
        "description": "A point-of-sale register (till) at an outlet in Lightspeed Retail.",
        "docs_url": "https://x-series-api.lightspeedhq.com/reference/listregisters",
        "columns": _columns(
            name="The register's name.",
            outlet_id="ID of the outlet the register belongs to.",
            is_open="Whether the register currently has an open session.",
        ),
    },
    "users": {
        "description": "A staff user account in Lightspeed Retail.",
        "docs_url": "https://x-series-api.lightspeedhq.com/reference/listusers",
        "columns": _columns(
            username="The user's login username.",
            display_name="The user's display name.",
            email="The user's email address.",
            account_type="The user's account type / permission level.",
            target_daily="The user's daily sales target, if set.",
            created_at="Time at which the user was created.",
            updated_at="Time at which the user was last updated.",
        ),
    },
    "taxes": {
        "description": "A sales tax rate configured in Lightspeed Retail.",
        "docs_url": "https://x-series-api.lightspeedhq.com/reference/listtaxes",
        "columns": _columns(
            name="The tax's name.",
            rate="The tax rate, as a decimal fraction.",
            is_default="Whether this is the default tax applied to sales.",
        ),
    },
    "consignments": {
        "description": "An inventory movement in Lightspeed Retail: a supplier order, outlet transfer, stocktake or supplier return.",
        "docs_url": "https://x-series-api.lightspeedhq.com/reference/getconsignments",
        "columns": _columns(
            type="Consignment type: SUPPLIER, OUTLET, STOCKTAKE or RETURN.",
            status="Workflow status of the consignment (e.g. OPEN, SENT, DISPATCHED, RECEIVED, CANCELLED, STOCKTAKE_COMPLETE).",
            name="Consignment name. For orders, this is the note shown in the UI.",
            reference="Order number.",
            outlet_id="ID of the outlet where the stock is received.",
            source_outlet_id="ID of the outlet the stock comes from. Set for stock transfers only.",
            supplier_id="ID of the supplier the stock is ordered from.",
            supplier_invoice="Supplier invoice number.",
            consignment_date="Date the consignment was created.",
            due_at="Date the consignment is due.",
            received_at="Date the consignment was received.",
            total_count_gain="Number of items over the expected level.",
            total_count_loss="Number of items below the expected level.",
            total_cost_gain="Cost of items over the expected level.",
            total_cost_loss="Cost of items below the expected level.",
            created_at="Time at which the consignment was created.",
            updated_at="Time at which the consignment was last updated.",
        ),
    },
    "consignment_products": {
        "description": "A product line item on a Lightspeed Retail consignment, with the expected and received counts.",
        "docs_url": "https://x-series-api.lightspeedhq.com/reference/listproductsbyconsignmentid",
        "columns": {
            "consignment_id": "ID of the consignment the line item belongs to.",
            "product_id": "ID of the product.",
            "product_sku": "SKU of the product.",
            "count": "Expected item count.",
            "received": "Observed (received) item count.",
            "cost": "Cost of the item.",
            "status": "Status of the item: PENDING or SUCCESS.",
            "is_included": "Whether the item was included via a filter. Always true for a full count with no filters.",
            "version": _COMMON_COLUMNS["version"],
            "created_at": "Time at which the line item was created.",
            "updated_at": "Time at which the line item was last updated.",
            "deleted_at": _COMMON_COLUMNS["deleted_at"],
        },
    },
    "suppliers": {
        "description": "A supplier that products are ordered from in Lightspeed Retail.",
        "docs_url": "https://x-series-api.lightspeedhq.com/reference/listsuppliers",
        "columns": _columns(
            name="The supplier's name.",
            description="The supplier's description.",
            source="Origin of the supplier record (e.g. USER, SHOPIFY).",
            default_markup="Default markup for the supplier. Used for record keeping only; it does not affect products.",
            contact="Contact information for the supplier.",
        ),
    },
    "payment_types": {
        "description": "A payment type (e.g. cash, card, gift card) configured in Lightspeed Retail.",
        "docs_url": "https://x-series-api.lightspeedhq.com/reference/listpaymenttypes",
        "columns": _columns(
            name="The payment type's name.",
            type_id="ID of the global payment type. Several payment types can share the same type_id.",
            payment_type="The global payment type this payment type is based on.",
            config="Payment type configuration. The shape varies by payment type.",
            outlet_ids="IDs of the outlets this payment type is associated with.",
            disabled="Whether the payment type is disabled.",
            gateway="Whether the payment type is a payment gateway type.",
            internal="Whether the payment type is for internal use only.",
            is_editable="Whether the payment type can be edited.",
            name_changed_by_user="Whether the retailer customized the name.",
            created_at="Time at which the payment type was created.",
        ),
    },
    "product_categories": {
        "description": "A product category in the Lightspeed Retail category hierarchy.",
        "docs_url": "https://x-series-api.lightspeedhq.com/reference/listproductcategories",
        "columns": {
            "id": "The category ID.",
            "name": "The name of the category.",
            "parent_category_id": "ID of the parent category, or null for a root category.",
            "root_category_id": "ID of the root of the category tree. A root category references itself.",
            "leaf_category": "Whether the category has no child categories.",
            "category_path": "The categories from the root down to this category, each with its ID and name.",
        },
    },
    "stock_adjustments": {
        "description": "A manual stock adjustment for a product at an outlet in Lightspeed Retail, e.g. damage, theft or stock found.",
        "docs_url": "https://x-series-api.lightspeedhq.com/reference/liststockadjustments",
        "columns": _columns(
            product_id="ID of the product that was adjusted.",
            outlet_id="ID of the outlet where the adjustment was recorded.",
            user_id="ID of the user who created the adjustment.",
            quantity="Quantity adjusted. Negative for stock removed, positive for stock added.",
            reason="Reason for the adjustment: DAMAGE, EXPIRY, INTERNAL_USE, THEFT, DONATION, STOCK_FOUND, SAMPLE_FOR_SALE or CUSTOM.",
            custom_inventory_adjustment_reason_id="ID of the custom reason. Set only when reason is CUSTOM.",
            created_at="Time at which the adjustment was created.",
            updated_at="Time at which the adjustment was last updated.",
        ),
    },
    "promotions": {
        "description": "A promotion in Lightspeed Retail: the rules and discount applied to the products it covers.",
        "docs_url": "https://x-series-api.lightspeedhq.com/reference/listpromotions",
        "columns": {
            "id": "Unique identifier for the promotion.",
            "name": "The name of the promotion.",
            "description": "A short description of the promotion.",
            "status": "The status of the promotion.",
            "start_time": "Time the promotion begins, in UTC.",
            "end_time": "Time the promotion ends, in UTC.",
            "condition": "Condition a sale must meet for the promotion to apply, with the product filters it includes and excludes.",
            "action": "Discount the promotion applies (type and value), with the product filters it includes and excludes.",
            "channels": "Channels the promotion applies to: Register, Ecommerce.",
            "outlet_ids": "IDs of the outlets the promotion applies at.",
            "customer_group_ids": "IDs of the customer groups the promotion applies to.",
            "online_channel_ids": "IDs of the online channels the promotion applies to.",
            "use_promo_code": "Whether the promotion requires a promo code.",
            "promo_code_summary": "Totals for the promotion's promo codes, including the redeemed amount.",
            "combinable_with_coupon": "Whether the promotion can be combined with an online coupon.",
            "loyalty_multiplier": "The loyalty multiplier for the promotion.",
        },
    },
    "promo_codes": {
        "description": "A promo code that unlocks a Lightspeed Retail promotion.",
        "docs_url": "https://x-series-api.lightspeedhq.com/reference/getpromotionpromocodes",
        "columns": {
            "id": "Unique identifier for the promo code.",
            "promotion_id": "ID of the promotion the code unlocks.",
            "code": "The code a customer enters.",
            "group_name": "Name of the group the code belongs to.",
            "limit": "Redemption limit for the code.",
            "redeemed": "Number of times the code has been redeemed.",
            "created_user_id": "ID of the user who created the code.",
            "created_at": "Time at which the code was created.",
        },
    },
    "gift_cards": {
        "description": "A Lightspeed Retail gift card with its balance and transaction history.",
        "docs_url": "https://x-series-api.lightspeedhq.com/reference/listgiftcards",
        "columns": {
            "id": "Unique identifier for the gift card.",
            "number": "The gift card number.",
            "status": "Status of the gift card: ACTIVE, INACTIVE, REDEEMED, VOIDED or EXPIRED.",
            "balance": "Remaining balance on the gift card.",
            "total_sold": "Amount loaded onto the gift card when activated or reloaded.",
            "total_redeemed": "Amount redeemed with the gift card.",
            "sale_id": "ID of the sale that created the gift card. Null when it was created through the API.",
            "sale_source": "System the gift card was created in (e.g. x-series, e-series).",
            "gift_card_transactions": "The gift card's transactions.",
            "expires_at": "Time at which the gift card expires, in UTC.",
            "created_at": "Time at which the gift card was created, in UTC.",
        },
    },
    "gift_card_transactions": {
        "description": "A transaction on a Lightspeed Retail gift card, such as an activation, redemption or reload.",
        "docs_url": "https://x-series-api.lightspeedhq.com/reference/listgiftcards",
        "columns": {
            "id": "Unique identifier for the transaction.",
            "gift_card_id": "ID of the gift card the transaction belongs to.",
            "type": "Transaction type: ACTIVATION, REDEEMING, IMPORTING, VOIDING, EXPIRING, REVERSING or RELOADING.",
            "amount": "Transaction amount. Redemptions are negative.",
            "client_id": "Unique transaction identifier from the client system that created it.",
            "source": "Source of the transaction.",
            "source_id": "Identifier of the transaction in the source system.",
            "user_id": "ID of the user associated with the transaction.",
            "created_at": "Time at which the transaction was created, in UTC.",
        },
    },
}
