from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "Documents": {
        "description": "Dashboards and workbooks in your Omni instance, with their owner, folder, and access scope.",
        "docs_url": "https://docs.omni.co/api/documents/list-documents",
        "columns": {
            "identifier": "Unique identifier for the document, used in its URL. Omni documents have no separate `id` field.",
            "name": "Document name.",
            "description": "Description of the document.",
            "connectionId": "ID of the database connection the document is built on.",
            "deleted": "Whether the document is deleted (archived).",
            "hasDashboard": "Whether the document has an associated dashboard.",
            "scope": "Document access scope: `restricted` or `organization`.",
            "type": "Content type, always `document`.",
            "updatedAt": "Timestamp the document was last updated.",
            "url": "URL to view the document (dashboard URL if it has one, otherwise workbook URL).",
            "owner": "Owner of the document (membership id and display name).",
            "folder": "Folder containing the document (id, name, path, scope), or null if not in a folder.",
            "labels": "Labels applied to the document.",
        },
    },
    "Folders": {
        "description": "Folders organizing documents in your Omni instance.",
        "docs_url": "https://docs.omni.co/api/folders/list-folders",
        "columns": {
            "id": "Unique identifier for the folder.",
            "name": "Display name of the folder.",
            "path": "Full path to the folder.",
            "scope": "Folder access scope: `organization` or `restricted`.",
            "url": "Direct link to the folder in the Omni UI.",
            "owner": "Owner of the folder (id and display name).",
            "labels": "Labels associated with the folder.",
        },
    },
    "Connections": {
        "description": "Database connections configured in your Omni instance.",
        "docs_url": "https://docs.omni.co/api/connections/list-connections",
        "columns": {
            "id": "The connection's unique ID.",
            "name": "A descriptive name for the connection.",
            "dialect": "The type of database (e.g. postgres, snowflake, bigquery).",
            "database": "The default database/catalog the connection connects to.",
            "baseRole": "The default role for users accessing the connection.",
            "defaultSchema": "The default schema used by the connection.",
            "createdAt": "The time the connection was created.",
            "updatedAt": "The time the connection was last updated.",
            "deletedAt": "The time the connection was deleted, if applicable.",
        },
    },
    "Schedules": {
        "description": "Scheduled deliveries and alerts configured for dashboards in your Omni instance.",
        "docs_url": "https://docs.omni.co/api/schedules/list-schedules",
        "columns": {
            "id": "The schedule's unique ID.",
            "name": "The name of the schedule.",
            "schedule": "The cron expression defining when the schedule runs.",
            "timezone": "The IANA timezone the schedule runs in.",
            "identifier": "The ID of the dashboard associated with the schedule.",
            "dashboardName": "The name of the dashboard associated with the schedule.",
            "ownerId": "The membership ID of the schedule owner.",
            "ownerName": "The name of the schedule owner.",
            "destinationType": "The delivery destination: `email`, `slack`, `webhook`, `sftp`, or `s3`.",
            "format": "The output format of the schedule (e.g. `csv`, `pdf`, `xlsx`).",
            "content": "Content type: `dashboard` or `single tile`.",
            "recipientCount": "Number of recipients. Returns `-1` for webhook destinations.",
            "lastCompletedAt": "Timestamp of the last completed run.",
            "lastStatus": "Status of the last run (e.g. `COMPLETE`, `ERROR_DELIVERED`).",
            "disabledAt": "Timestamp when the schedule was paused, if applicable.",
        },
    },
    "Users": {
        "description": "Users provisioned in your Omni organization (SCIM).",
        "docs_url": "https://docs.omni.co/api/users/list-users",
        "columns": {
            "id": "Unique identifier for the user.",
            "userName": "The user's email address.",
            "displayName": "The user's display name.",
            "active": "Whether the user is active.",
            "emails": "The user's email addresses.",
            "groups": "User groups the user belongs to.",
            "meta": "Resource metadata, including `created` and `lastModified` timestamps.",
        },
    },
    "UserGroups": {
        "description": "User groups provisioned in your Omni organization (SCIM).",
        "docs_url": "https://docs.omni.co/api/user-groups/list-user-groups",
        "columns": {
            "id": "Unique identifier for the group.",
            "displayName": "The name of the group.",
            "members": "The list of users in the group.",
            "meta": "Resource metadata, including `created` and `lastModified` timestamps.",
        },
    },
}
