from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "campaigns": {
        "description": "A cold email outreach campaign with its status, sending schedule, tracking settings, and sending limits.",
        "docs_url": "https://api.smartlead.ai/api-reference/campaigns/get-all",
        "columns": {
            "id": "Unique campaign identifier.",
            "user_id": "ID of the Smartlead user who owns this campaign.",
            "name": "Campaign name set by the user.",
            "status": "Current campaign status: ACTIVE, PAUSED, STOPPED, ARCHIVED, or DRAFTED.",
            "created_at": "ISO 8601 timestamp when the campaign was created.",
            "updated_at": "ISO 8601 timestamp of the last modification.",
            "track_settings": "Tracking configuration flags, e.g. DONT_EMAIL_OPEN or DONT_LINK_CLICK.",
            "scheduler_cron_value": "Sending schedule: timezone, days of week, and start/end hours.",
            "min_time_btwn_emails": "Minimum minutes to wait between consecutive emails.",
            "max_leads_per_day": "Maximum number of leads to contact per day across all email accounts.",
            "stop_lead_settings": "When to stop emailing a lead: REPLY_TO_AN_EMAIL, OPENED_EMAIL, CLICKED_LINK, or NEVER.",
            "schedule_start_time": "Scheduled start time for the campaign, null if starting immediately.",
            "enable_ai_esp_matching": "Whether Smartlead's AI matches leads with email accounts by provider.",
            "send_as_plain_text": "Whether emails are sent as plain text instead of HTML.",
            "follow_up_percentage": "Percentage of leads that receive follow-up emails (0-100).",
            "parent_campaign_id": "Parent campaign ID when this is a subsequence, null for main campaigns.",
            "client_id": "Associated client ID for agency accounts, null for direct user campaigns.",
        },
    },
    "campaign_sequences": {
        "description": "An email sequence step configured in a campaign, including subject, body, delay, and A/B test variants.",
        "docs_url": "https://api.smartlead.ai/api-reference/campaigns/get-sequences",
        "columns": {
            "id": "Unique sequence step identifier.",
            "campaign_id": "ID of the campaign this sequence step belongs to.",
            "email_campaign_id": "ID of the campaign as reported by the sequence record itself.",
            "seq_number": "Position of this step in the sequence (1, 2, 3, ...).",
            "subject": "Email subject line, may include template variables.",
            "follow_up_subject": "Subject a follow-up step actually sends with, inherited from the most recent earlier step that set one.",
            "email_body": "Email content as HTML or plain text.",
            "seq_delay_details": "Delay configuration, including days to wait before sending this step.",
            "sequence_variants": "A/B test variants for this step, each with its own subject and body.",
            "created_at": "ISO 8601 timestamp when the sequence step was created.",
            "updated_at": "ISO 8601 timestamp of the last modification.",
        },
    },
    "campaign_leads": {
        "description": "A lead's membership in a campaign, with the lead's contact details and campaign-specific status.",
        "docs_url": "https://api.smartlead.ai/api-reference/leads/get-by-campaign",
        "columns": {
            "campaign_lead_map_id": "Unique identifier for the lead-to-campaign mapping.",
            "campaign_id": "ID of the campaign the lead belongs to.",
            "lead_category_id": "Category ID assigned to this lead, null if uncategorized.",
            "status": "Lead status in this campaign: STARTED, INPROGRESS, COMPLETED, PAUSED, or STOPPED.",
            "created_at": "ISO 8601 timestamp when the lead was added to the campaign.",
            "lead": "Lead contact details: email, name, company, phone, location, LinkedIn profile, and custom fields.",
        },
    },
    "campaign_statistics": {
        "description": "Per-email send statistics for a campaign: one row per sent email with open, click, reply, and bounce outcomes.",
        "docs_url": "https://api.smartlead.ai/api-reference/campaigns/statistics",
        "columns": {
            "stats_id": "Unique identifier of the sent-email statistics record.",
            "campaign_id": "ID of the campaign the email was sent from.",
            "lead_name": "Recipient lead's full name.",
            "lead_email": "Recipient lead's email address.",
            "sequence_number": "Which sequence step the email belongs to (1, 2, 3, ...).",
            "email_subject": "Subject of the sent email.",
            "sent_time": "When the email was sent.",
            "open_time": "When the email was first opened, null if never opened.",
            "click_time": "When a link was first clicked, null if never clicked.",
            "reply_time": "When the lead replied, null if no reply.",
            "open_count": "Number of times the email was opened.",
            "click_count": "Number of times a link in the email was clicked.",
            "is_unsubscribed": "Whether the lead unsubscribed from this email.",
            "is_bounced": "Whether the email bounced.",
        },
    },
    "campaign_analytics": {
        "description": "Aggregate performance metrics for a campaign: totals and rates for sends, opens, clicks, replies, and bounces.",
        "docs_url": "https://api.smartlead.ai/api-reference/campaigns/get-analytics",
        "columns": {
            "campaign_id": "ID of the campaign the metrics belong to.",
            "total_sent": "Total emails sent by the campaign.",
            "total_opened": "Total emails opened.",
            "total_clicked": "Total emails with a clicked link.",
            "total_replied": "Total leads that replied.",
            "open_rate": "Percentage of sent emails that were opened.",
            "click_rate": "Percentage of sent emails with a clicked link.",
            "reply_rate": "Percentage of sent emails that received a reply.",
            "bounce_rate": "Percentage of sent emails that bounced.",
            "unsubscribe_rate": "Percentage of leads that unsubscribed.",
        },
    },
    "email_accounts": {
        "description": "A sending email account connected to Smartlead, with SMTP/IMAP connection state, sending limits, and warmup status. Mailbox passwords are stripped before rows are stored.",
        "docs_url": "https://api.smartlead.ai/api-reference/email-accounts/get-all",
        "columns": {
            "id": "Unique email account identifier.",
            "from_name": "Display name for outgoing emails.",
            "from_email": "Email address the account sends from.",
            "username": "Email account username.",
            "type": "Account type: GMAIL, OUTLOOK, or SMTP.",
            "smtp_host": "SMTP server hostname.",
            "smtp_port": "SMTP server port.",
            "is_smtp_success": "Whether the SMTP connection is working.",
            "imap_host": "IMAP server hostname.",
            "imap_port": "IMAP server port.",
            "is_imap_success": "Whether the IMAP connection is working.",
            "message_per_day": "Maximum messages this account may send per day.",
            "daily_sent_count": "Messages sent today.",
            "warmup_details": "Warmup status and metrics: status, sent count, spam count, and reputation.",
            "client_id": "Associated client ID for agency accounts, null otherwise.",
            "created_at": "ISO 8601 timestamp when the account was added.",
            "updated_at": "ISO 8601 timestamp of the last modification.",
        },
    },
    "clients": {
        "description": "A whitelabel client sub-account under the main Smartlead account.",
        "docs_url": "https://api.smartlead.ai/api-reference/clients/get-all",
        "columns": {
            "id": "Unique client identifier.",
            "name": "Client name.",
            "email": "Client account email address.",
            "created_at": "ISO 8601 timestamp when the client was created.",
        },
    },
}
