from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Descriptions sourced from the official Codacy API v3 reference (https://api.codacy.com/api/api-docs).

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "organizations": {
        "description": "Organizations on Codacy that the account API token belongs to, across Git providers.",
        "docs_url": "https://api.codacy.com/api/api-docs#listuserorganizations",
        "columns": {
            "identifier": "Codacy identifier of the organization.",
            "remoteIdentifier": "Unique identifier of the organization on the Git provider.",
            "name": "Name of the organization on the Git provider.",
            "provider": "Git provider hosting the organization (gh for GitHub, gl for GitLab, bb for Bitbucket).",
            "created": "Timestamp when the organization was added to Codacy.",
            "type": "Type of the organization (e.g. Organization, User).",
            "joinMode": "How new members join the organization on Codacy.",
            "avatar": "URL of the organization's avatar image.",
        },
    },
    "repositories": {
        "description": "Repositories in the configured organization, with the most recent analysis snapshot: quality grade, issue counts, complexity, duplication, coverage, and lines of code.",
        "docs_url": "https://api.codacy.com/api/api-docs#listorganizationrepositorieswithanalysis",
        "columns": {
            "repositoryId": "Codacy identifier for the repository.",
            "provider": "Git provider hosting the repository (gh for GitHub, gl for GitLab, bb for Bitbucket).",
            "owner": "Name of the organization that owns the repository.",
            "name": "Name of the repository.",
            "fullPath": "Full path of the repository on the Git provider.",
            "visibility": "Visibility of the repository (Public, Private, or LoginPublic).",
            "remoteIdentifier": "Unique identifier of the repository on the Git provider.",
            "lastUpdated": "Timestamp when the repository was last updated on the Git provider.",
            "languages": "List of the programming languages in the repository.",
            "grade": "Quality grade of the repository as a number between 100 (highest) and 0 (lowest).",
            "gradeLetter": "Quality grade of the repository as a letter between A (highest) and F (lowest).",
            "issuesPercentage": "Percentage of the repository's lines of code with issues.",
            "issuesCount": "Number of issues in the repository.",
            "loc": "Lines of code of the repository.",
            "complexFilesPercentage": "Percentage of complex files in the repository.",
            "complexFilesCount": "Number of complex files in the repository.",
            "duplicationPercentage": "Percentage of duplicated lines in the repository.",
            "coverage": "Test coverage information for the most recent analyzed commit.",
            "lastAnalysedCommit": "Most recent commit analyzed by Codacy.",
            "selectedBranch": "Branch the analysis snapshot refers to.",
        },
    },
    "files": {
        "description": "Most recent analysis information for the files in each repository: per-file grade, issue count, complexity, duplication, and coverage. Files ignored on Codacy aren't returned.",
        "docs_url": "https://api.codacy.com/api/api-docs#listfiles",
        "columns": {
            "repository": "Name of the repository the file belongs to.",
            "fileId": "Identifier of the file in a specific branch and commit.",
            "branchId": "Identifier for the branch the file belongs to.",
            "path": "Relative path of the file in the repository.",
            "totalIssues": "Number of issues in the file.",
            "complexity": "Complexity level of the file.",
            "grade": "Quality grade of the file as a number between 100 (highest) and 0 (lowest).",
            "gradeLetter": "Quality grade of the file as a letter between A (highest) and F (lowest).",
            "coverageWithDecimals": "Test coverage percentage of the file.",
            "duplication": "Number of duplicated lines in the file.",
            "linesOfCode": "Lines of code in the file.",
            "sourceLinesOfCode": "Coverable lines of code in the file.",
            "numberOfMethods": "Number of methods in the file.",
        },
    },
    "issues": {
        "description": "Current issues that Codacy found in each repository's main branch, as shown on the repository Issues page.",
        "docs_url": "https://api.codacy.com/api/api-docs#searchrepositoryissues",
        "columns": {
            "repository": "Name of the repository the issue belongs to.",
            "issueId": "ID of the issue.",
            "resultDataId": "Stable ID for the issue.",
            "filePath": "Path of the file where the issue was found.",
            "fileId": "Identifier of the file where the issue was found.",
            "patternInfo": "Details of the code pattern that detected the issue, including category and severity level.",
            "toolInfo": "Details of the tool that detected the issue.",
            "lineNumber": "Line where the issue was found.",
            "message": "Detailed cause of the issue.",
            "suggestion": "The suggested fix for the issue.",
            "language": "Language of the file where the issue was found.",
            "lineText": "Contents of the line where the issue was found.",
            "commitInfo": "Details of the commit that originated the issue.",
        },
    },
    "pull_requests": {
        "description": "Pull requests in each repository with Codacy's analysis results: new and fixed issues, complexity and duplication deltas, coverage, and whether the pull request is up to the quality standards.",
        "docs_url": "https://api.codacy.com/api/api-docs#listrepositorypullrequests",
        "columns": {
            "repository": "Name of the repository the pull request belongs to.",
            "id": "Codacy identifier of the pull request.",
            "number": "Number of the pull request on the Git provider.",
            "updated": "Timestamp when the pull request was last updated.",
            "status": "Pull request status.",
            "title": "Title of the pull request.",
            "owner": "Author of the pull request.",
            "headCommitSha": "Commit SHA of the pull request head.",
            "commonAncestorCommitSha": "Commit SHA of the common ancestor with the target branch.",
            "originBranch": "Source branch of the pull request.",
            "targetBranch": "Target branch of the pull request.",
            "gitHref": "URL to the pull request on the Git provider.",
            "isUpToStandards": "True if metrics are at or above the quality gate thresholds.",
            "isAnalysing": "True if Codacy is still analyzing the pull request.",
            "newIssues": "Number of issues introduced by the pull request.",
            "fixedIssues": "Number of issues fixed by the pull request.",
            "deltaComplexity": "Difference in cyclomatic complexity introduced by the pull request.",
            "deltaClonesCount": "Difference in number of duplicated blocks of code introduced by the pull request.",
            "coverage": "Coverage analysis for the pull request.",
            "quality": "Quality gate analysis for the pull request.",
        },
    },
    "commits": {
        "description": "Analysis results for the commits in each repository's main branch on Codacy, including quality and coverage gate outcomes per commit.",
        "docs_url": "https://api.codacy.com/api/api-docs#listrepositorycommits",
        "columns": {
            "repository": "Name of the repository the commit belongs to.",
            "sha": "Commit SHA.",
            "id": "Internal Codacy commit identifier.",
            "commitTimestamp": "Timestamp when the commit was created.",
            "authorName": "Name of the commit author.",
            "authorEmail": "Email address of the commit author.",
            "message": "Commit message.",
            "startedAnalysis": "Timestamp when Codacy started the last analysis of the commit.",
            "endedAnalysis": "Timestamp when Codacy finished the last analysis of the commit.",
            "isMergeCommit": "True if the commit is a merge commit.",
            "gitHref": "URL to the commit on the Git provider.",
            "parents": "SHA-1 hashes of the parents of the commit.",
            "quality": "Quality gate analysis results for the commit, including new and fixed issues.",
            "coverage": "Coverage analysis results for the commit.",
        },
    },
    "people": {
        "description": "People in the organization on Codacy: members and the commit authors Codacy saw, resolving the author identities on the commits and pull requests already synced.",
        "docs_url": "https://api.codacy.com/api/api-docs#listpeoplefromorganization",
        "columns": {
            "name": "Name of the person.",
            "email": "Primary email address of the person.",
            "emails": "All email addresses Codacy knows for the person.",
            "userId": "User ID internal to Codacy. Null for commit authors who aren't Codacy users.",
            "committerId": "Commit author ID.",
            "lastLogin": "Timestamp when the person last logged in to Codacy.",
            "lastAnalysis": "Timestamp when Codacy last analyzed a commit from this person.",
            "isActive": "True if the person is an active committer on Codacy.",
            "canBeRemoved": "True if the person can be removed from the organization.",
            "lastCommitId": "Identifier of the last commit by the person.",
            "providerId": "ID of the person on the Git provider.",
            "providerLogin": "Username of the person on the Git provider.",
            "isProviderRegistered": "True if the person is registered on the Git provider.",
        },
    },
    "commit_delta_issues": {
        "description": "Issues that each analyzed commit introduced or fixed, compared against its parent commit. Unlike the issues table, which holds the issues currently open, this records the change each commit made.",
        "docs_url": "https://api.codacy.com/api/api-docs#listcommitdeltaissues",
        "columns": {
            "repository": "Name of the repository the commit belongs to.",
            "commitSha": "SHA of the commit that introduced or fixed the issue.",
            "deltaType": "Whether the commit added or fixed the issue.",
            "issueId": "ID of the issue.",
            "resultDataId": "Stable ID for the issue.",
            "filePath": "Path of the file where the issue was found.",
            "fileId": "Identifier of the file where the issue was found.",
            "patternInfo": "Details of the code pattern that detected the issue, including category and severity level.",
            "toolInfo": "Details of the tool that detected the issue.",
            "lineNumber": "Line where the issue was found.",
            "message": "Detailed cause of the issue.",
            "suggestion": "The suggested fix for the issue.",
            "language": "Language of the file where the issue was found.",
            "lineText": "Contents of the line where the issue was found.",
            "commitInfo": "Details of the commit that originated the issue.",
        },
    },
    "tools": {
        "description": "Codacy's catalog of static analysis tools, resolving the tool UUID carried by every issue row. The catalog is the same for every Codacy account.",
        "docs_url": "https://api.codacy.com/api/api-docs#listtools",
        "columns": {
            "uuid": "Tool unique identifier.",
            "name": "Name of the tool.",
            "shortName": "Tool unique short name.",
            "version": "Original tool version used by the Codacy tool wrapper.",
            "documentationUrl": "Original tool documentation URL.",
            "sourceCodeUrl": "Codacy tool wrapper source code URL.",
            "prefix": "Tool prefix used to make pattern names unique.",
            "needsCompilation": "True if the tool requires compilation to run.",
            "configurationFilenames": "Configuration filenames the tool reads.",
            "description": "Tool description.",
            "dockerImage": "Docker image used to launch the tool.",
            "languages": "Languages the tool supports.",
            "clientSide": "True if the tool runs on the client machine and sends results to Codacy.",
            "standalone": "True if the client-side tool runs outside of the Codacy CLI.",
            "enabledByDefault": "True if the tool is enabled by default for new repositories.",
            "configurable": "True if the tool is configurable on Codacy's UI.",
        },
    },
    "tool_patterns": {
        "description": "Code patterns (rules) each Codacy tool can flag, resolving the pattern ID carried by every issue row so issues can be grouped by rule, category, and severity.",
        "docs_url": "https://api.codacy.com/api/api-docs#listpatterns",
        "columns": {
            "toolUuid": "Unique identifier of the tool that owns the pattern.",
            "id": "Pattern identifier, unique per tool.",
            "title": "Pattern title.",
            "category": "Pattern category.",
            "subCategory": "Pattern subcategory, when the pattern has one.",
            "level": "Deprecated severity of the pattern. Use severityLevel instead.",
            "severityLevel": "Severity of the issues the pattern detects: Info, Warning, High, or Error.",
            "description": "Short description of the code pattern.",
            "explanation": "Full description of the code pattern, in CommonMark.",
            "enabled": "True if the pattern is on by default for new repositories.",
            "languages": "Languages the pattern supports.",
            "timeToFix": "Average time to fix an issue the pattern detects, in minutes.",
            "parameters": "Configurable parameters of the pattern.",
            "rationale": "Rationale for the pattern.",
            "solution": "Suggested solution for issues the pattern detects.",
            "goodExamples": "Examples of code that satisfies the pattern.",
            "badExamples": "Examples of code that violates the pattern.",
            "tags": "Tags associated with the pattern.",
        },
    },
    "security_items": {
        "description": "Security and risk management items for the organization: vulnerabilities, secrets, licence and dependency findings, each with a priority, an SLA status and its due date.",
        "docs_url": "https://api.codacy.com/api/api-docs#searchsecurityitems",
        "columns": {
            "id": "Codacy identifier of the security item.",
            "itemSource": "System that reported the item: Codacy, Jira, PenTest, ZAP, or Trivy.",
            "itemSourceId": "Identifier of the item in the reporting system.",
            "title": "Human-readable title of the item.",
            "repository": "Name of the repository the item was found in.",
            "openedAt": "Timestamp when the item was detected.",
            "closedAt": "Timestamp when the item was closed, if it has been.",
            "dueAt": "Timestamp the item must be fixed by, from the organization's SLA settings.",
            "ignored": "Details of who ignored the item and why, when it has been ignored.",
            "priority": "Priority of the item: Low, Medium, High, or Critical.",
            "status": "SLA status of the item: Overdue, OnTrack, DueSoon, ClosedOnTime, ClosedLate, or Ignored.",
            "htmlUrl": "Link to the underlying issue on Codacy.",
            "projectKey": "Jira project key of the underlying issue.",
            "securityCategory": "Security category of the item, such as Cryptography.",
            "scanType": "Type of scan that found the item, such as SAST, SCA, Secrets, IaC, or DAST.",
            "summary": "Brief description of the issue. Penetration testing items only.",
            "cvssScore": "CVSS severity score of the vulnerability. Penetration testing items only.",
            "cvssVector": "CVSS scoring vector detailing the nature and impact of the vulnerability.",
            "cwe": "CWE software weakness identifier of the vulnerability.",
            "cve": "CVE identifiers of the vulnerability.",
            "affectedVersion": "Version the vulnerability was first detected in.",
            "fixedVersion": "Versions, tags or commit SHAs where the vulnerability was fixed.",
            "application": "URL of the affected application. DAST items only.",
            "affectedTargets": "Targets affected by the security issue.",
            "additionalInfo": "Additional information about the issue.",
            "likelihood": "Likelihood of the issue being exploited. Penetration testing items only.",
            "effortToFix": "Estimated effort to fix the issue. Penetration testing items only.",
            "remediation": "Recommended steps to fix the issue.",
            "dastTargetUrls": "Target URLs that were scanned.",
            "imageName": "Name of the scanned container image.",
            "imageTag": "Tag of the scanned container image.",
            "dependencyChains": "Ordered package chains showing how the vulnerable package is reached. Dependency scanning items only.",
            "advisoryInformation": "Advisory the finding is based on.",
        },
    },
    "commit_statistics": {
        "description": "Analysis totals for each analysed commit of a repository, giving repository health a trend over time instead of only the latest snapshot.",
        "docs_url": "https://api.codacy.com/api/api-docs#listcommitanalysisstats",
        "columns": {
            "repository": "Name of the repository the commit belongs to.",
            "repositoryId": "Codacy identifier of the repository.",
            "commitId": "Codacy identifier of the commit.",
            "commitShortUUID": "Short SHA of the commit.",
            "commitTimestamp": "Timestamp of the commit.",
            "commitAuthorName": "Name of the commit author.",
            "numberIssues": "Number of issues in the repository at this commit.",
            "numberLoc": "Lines of code in the repository at this commit.",
            "issuesPerCategory": "Number of issues per issue category at this commit.",
            "issuePercentage": "Percentage of lines of code with issues, truncated.",
            "totalComplexity": "Total complexity of the repository at this commit.",
            "numberComplexFiles": "Number of complex files at this commit.",
            "complexFilesPercentage": "Percentage of complex files, truncated.",
            "filesChangedToIncreaseComplexity": "Number of files the commit changed that increased complexity.",
            "numberDuplicatedLines": "Number of duplicated lines at this commit.",
            "duplicationPercentage": "Percentage of duplicated lines, truncated.",
            "coveragePercentage": "Test coverage percentage, truncated. Only present when a coverage report was processed for the commit.",
            "coveragePercentageWithDecimals": "Test coverage percentage. Only present when a coverage report was processed for the commit.",
            "numberFilesUncovered": "Number of files with no test coverage.",
            "techDebt": "Estimated time to fix all issues, in minutes.",
            "totalFilesAdded": "Number of files the commit added.",
            "totalFilesRemoved": "Number of files the commit removed.",
            "totalFilesChanged": "Number of files the commit changed.",
        },
    },
    "category_overviews": {
        "description": "Issue counts per analysis category for the latest analysed commit of each repository, the breakdown behind the repository quality grade.",
        "docs_url": "https://api.codacy.com/api/api-docs#listcategoryoverviews",
        "columns": {
            "repository": "Name of the repository the overview belongs to.",
            "commitId": "Codacy identifier of the commit the overview was computed for.",
            "categoryName": "Name of the analysis category, such as Security or ErrorProne.",
            "categoryType": "Type of the analysis category.",
            "categoryDescription": "Description of the analysis category.",
            "percentage": "Percentage of the repository's issues in this category.",
            "totalResults": "Number of issues in this category.",
        },
    },
    "issues_overview": {
        "description": "Issue counts for each repository broken down by category, severity level, language, code pattern, tag, commit author, and false-positive probability. One row per breakdown value.",
        "docs_url": "https://api.codacy.com/api/api-docs#issuesoverview",
        "columns": {
            "repository": "Name of the repository the count belongs to.",
            "dimension": "Breakdown the count belongs to: categories, levels, languages, tags, patterns, authors, or potentialFalsePositives.",
            "name": "Value within the breakdown, such as the category name, severity level, or code pattern identifier.",
            "total": "Number of issues with this value.",
            "title": "Human-readable title of the code pattern. Only set for the patterns breakdown.",
        },
    },
    "pull_request_coverage": {
        "description": "Test coverage of each analysed pull request: how coverage moved against the common ancestor commit, and how well the lines the pull request touched are covered.",
        "docs_url": "https://api.codacy.com/api/api-docs#getrepositorypullrequestcoverage",
        "columns": {
            "repository": "Name of the repository the pull request belongs to.",
            "pullRequestNumber": "Number of the pull request on the Git provider.",
            "id": "Codacy identifier of the pull request.",
            "number": "Number of the pull request on the Git provider.",
            "updated": "Timestamp when the pull request was last updated.",
            "status": "Status of the pull request, such as open or merged.",
            "title": "Title of the pull request.",
            "owner": "Author of the pull request.",
            "headCommitSha": "SHA of the pull request's head commit.",
            "commonAncestorCommitSha": "SHA of the common ancestor commit coverage is compared against.",
            "originBranch": "Branch the pull request comes from.",
            "targetBranch": "Branch the pull request targets.",
            "gitHref": "URL of the pull request on the Git provider.",
            "deltaCoverage": "Difference between the coverage of the head commit and the common ancestor commit.",
            "diffCoverage": "Coverage of the lines the pull request added or changed, with the covered and coverable line counts.",
            "isUpToStandards": "True when the coverage metrics are at or above the quality gate thresholds.",
            "resultReasons": "Per-gate results explaining the coverage verdict.",
        },
    },
    "pull_request_file_coverage": {
        "description": "Test coverage of each file changed by a pull request, so uncovered changes can be traced to the file that introduced them.",
        "docs_url": "https://api.codacy.com/api/api-docs#getrepositorypullrequestfilescoverage",
        "columns": {
            "repository": "Name of the repository the pull request belongs to.",
            "pullRequestNumber": "Number of the pull request on the Git provider.",
            "fileName": "Path of the file in the repository.",
            "coverage": "Coverage of the file on the pull request's head commit.",
            "variation": "Change in the file's coverage caused by the pull request.",
            "diff": "Coverage of the lines the pull request added or changed in this file.",
            "diffLineHits": "Number of test hits per line added or changed in this file.",
        },
    },
    "metrics_timerange": {
        "description": "Organization quality metrics over time, broken down by repository. These are the precomputed numbers behind Codacy's own dashboards, one row per metric, period, and repository.",
        "docs_url": "https://api.codacy.com/api/api-docs#retrievetimerangemetricvalues",
        "columns": {
            "metricName": "Name of the metric, such as openissues.",
            "date": "Start date of the period the value covers.",
            "organization": "Name of the organization the value belongs to.",
            "repository": "Name of the repository the value belongs to. Empty when the value isn't broken down per repository.",
            "dimensions": "Additional dimensions the value is grouped by, such as issue category or severity.",
            "value": "Value of the metric for the period. Aggregating metrics give the average, accumulating metrics give the sum.",
            "latestValue": "Most recent value of the metric.",
        },
    },
}
