import type { CommonConfig } from '../common/config'
import {
    KAFKA_APP_METRICS_2,
    KAFKA_CLICKHOUSE_AI_EVENTS_JSON,
    KAFKA_CLICKHOUSE_HEATMAP_EVENTS,
    KAFKA_CLICKHOUSE_TOPHOG,
    KAFKA_EVENTS_JSON,
    KAFKA_EVENTS_PLUGIN_INGESTION,
    KAFKA_EVENTS_PLUGIN_INGESTION_ASYNC,
    KAFKA_EVENTS_PLUGIN_INGESTION_DLQ,
    KAFKA_EVENTS_PLUGIN_INGESTION_OVERFLOW,
    KAFKA_GROUPS,
    KAFKA_INGESTION_WARNINGS,
    KAFKA_LOG_ENTRIES,
    KAFKA_PERSON,
    KAFKA_PERSON_DISTINCT_ID,
} from '../config/kafka-topics'
import type { PostgresRouterConfig } from '../utils/db/postgres'
import { isDevEnv, isProdEnv } from '../utils/env-utils'
import { DEFAULT_PRODUCER, type ProducerName } from './common/outputs'
import type { DualWriteMode } from './outputs/types'

// =============================================================================
// Infrastructure sub-config types
// These group CommonConfig keys by infrastructure concern for use in server
// config types. Defined here (rather than common/config.ts) because they are
// ingestion-specific groupings — other domains may slice CommonConfig differently.
// =============================================================================

/** Kafka broker connection and authentication config */
export type KafkaBrokerConfig = Pick<
    CommonConfig,
    | 'KAFKA_HOSTS'
    | 'KAFKA_CLIENT_RACK'
    | 'KAFKA_CLIENT_CERT_B64'
    | 'KAFKA_CLIENT_CERT_KEY_B64'
    | 'KAFKA_TRUSTED_CERT_B64'
    | 'KAFKA_SASL_MECHANISM'
    | 'KAFKA_SASL_USER'
    | 'KAFKA_SASL_PASSWORD'
>

/** PostgreSQL connection config for the ingestion server — excludes behavioral cohorts */
export type DatabaseConnectionConfig = Omit<PostgresRouterConfig, 'BEHAVIORAL_COHORTS_DATABASE_URL'>

/** Redis connection config — URLs, hosts, and pool sizing */
export type RedisConnectionsConfig = Pick<
    CommonConfig,
    | 'REDIS_URL'
    | 'REDIS_POOL_MIN_SIZE'
    | 'REDIS_POOL_MAX_SIZE'
    | 'INGESTION_REDIS_HOST'
    | 'INGESTION_REDIS_PORT'
    | 'POSTHOG_REDIS_HOST'
    | 'POSTHOG_REDIS_PORT'
    | 'POSTHOG_REDIS_PASSWORD'
>

/** PersonHog gRPC client config */
export type PersonHogConfig = Pick<
    CommonConfig,
    | 'PERSONHOG_ENABLED'
    | 'PERSONHOG_ADDR'
    | 'PERSONHOG_GROUPS_ROLLOUT_PERCENTAGE'
    | 'PERSONHOG_GROUPS_ROLLOUT_TEAM_IDS'
    | 'PERSONHOG_PERSONS_ROLLOUT_PERCENTAGE'
    | 'PERSONHOG_PERSONS_ROLLOUT_TEAM_IDS'
    | 'PERSONHOG_TLS'
    | 'PERSONHOG_TIMEOUT_MS'
    | 'PERSONHOG_READ_MAX_BYTES'
    | 'PERSONHOG_WRITE_MAX_BYTES'
    | 'PERSONHOG_PING_INTERVAL_MS'
    | 'PERSONHOG_PING_TIMEOUT_MS'
    | 'PERSONHOG_PING_IDLE_CONNECTION'
    | 'PERSONHOG_IDLE_CONNECTION_TIMEOUT_MS'
    | 'PERSONHOG_STATE_MONITOR_POLL_INTERVAL_MS'
    | 'PLUGIN_SERVER_MODE'
>

/** Kafka consumer loop tuning config */
export type KafkaConsumerBaseConfig = Pick<
    CommonConfig,
    | 'CONSUMER_BATCH_SIZE'
    | 'CONSUMER_MAX_HEARTBEAT_INTERVAL_MS'
    | 'CONSUMER_LOOP_STALL_THRESHOLD_MS'
    | 'CONSUMER_LOG_STATS_LEVEL'
    | 'CONSUMER_LOOP_BASED_HEALTH_CHECK'
    | 'CONSUMER_MAX_BACKGROUND_TASKS'
    | 'CONSUMER_WAIT_FOR_BACKGROUND_TASKS_ON_REBALANCE'
    | 'CONSUMER_AUTO_CREATE_TOPICS'
>

export type PersonBatchWritingDbWriteMode = 'NO_ASSERT' | 'ASSERT_VERSION'
export type PersonBatchWritingMode = 'BATCH' | 'SHADOW' | 'NONE'

export type IngestionLane = 'main' | 'overflow' | 'historical' | 'async'

export type IngestionConsumerConfig = {
    INGESTION_LANE: IngestionLane | null

    // Kafka consumer config
    INGESTION_CONSUMER_GROUP_ID: string
    INGESTION_CONSUMER_CONSUME_TOPIC: string
    INGESTION_CONSUMER_DLQ_TOPIC: string
    INGESTION_CONSUMER_OVERFLOW_TOPIC: string

    // Ingestion pipeline config
    INGESTION_BATCH_SIZE: number
    INGESTION_OVERFLOW_ENABLED: boolean
    INGESTION_FORCE_OVERFLOW_BY_TOKEN_DISTINCT_ID: string
    INGESTION_OVERFLOW_PRESERVE_PARTITION_LOCALITY: boolean

    // Person batch writing config
    PERSON_BATCH_WRITING_DB_WRITE_MODE: PersonBatchWritingDbWriteMode
    PERSON_BATCH_WRITING_USE_BATCH_UPDATES: boolean
    PERSON_BATCH_WRITING_OPTIMISTIC_UPDATES_ENABLED: boolean
    PERSON_BATCH_WRITING_MAX_CONCURRENT_UPDATES: number
    PERSON_BATCH_WRITING_MAX_OPTIMISTIC_UPDATE_RETRIES: number
    PERSON_BATCH_WRITING_OPTIMISTIC_UPDATE_RETRY_INTERVAL_MS: number
    PERSONS_PREFETCH_ENABLED: boolean

    // Person properties config
    PERSON_UPDATE_CALCULATE_PROPERTIES_SIZE: number
    PERSON_PROPERTIES_DB_CONSTRAINT_LIMIT_BYTES: number
    PERSON_PROPERTIES_TRIM_TARGET_BYTES: number
    PERSON_PROPERTIES_UPDATE_ALL: boolean
    PERSON_JSONB_SIZE_ESTIMATE_ENABLE: number

    // Person merge config
    PERSON_MERGE_MOVE_DISTINCT_ID_LIMIT: number
    PERSON_MERGE_ASYNC_TOPIC: string
    PERSON_MERGE_ASYNC_ENABLED: boolean
    PERSON_MERGE_SYNC_BATCH_SIZE: number

    // Group batch writing config
    GROUP_BATCH_WRITING_MAX_CONCURRENT_UPDATES: number
    GROUP_BATCH_WRITING_MAX_OPTIMISTIC_UPDATE_RETRIES: number
    GROUP_BATCH_WRITING_OPTIMISTIC_UPDATE_RETRY_INTERVAL_MS: number

    // Event overflow config
    EVENT_OVERFLOW_BUCKET_CAPACITY: number
    EVENT_OVERFLOW_BUCKET_REPLENISH_RATE: number

    // Stateful overflow config
    INGESTION_STATEFUL_OVERFLOW_ENABLED: boolean
    INGESTION_STATEFUL_OVERFLOW_REDIS_TTL_SECONDS: number
    INGESTION_STATEFUL_OVERFLOW_LOCAL_CACHE_TTL_SECONDS: number

    // Per-token/distinct_id restrictions
    DROP_EVENTS_BY_TOKEN_DISTINCT_ID: string
    SKIP_PERSONS_PROCESSING_BY_TOKEN_DISTINCT_ID: string
    MAX_TEAM_ID_TO_BUFFER_ANONYMOUS_EVENTS_FOR: number

    // Pipeline step config
    SKIP_UPDATE_EVENT_AND_PROPERTIES_STEP: boolean
    EVENT_SCHEMA_ENFORCEMENT_ENABLED: boolean
    KAFKA_BATCH_START_LOGGING_ENABLED: boolean

    // AI event splitting config
    INGESTION_AI_EVENT_SPLITTING_ENABLED: boolean
    /** '*' for all teams, or comma-separated team IDs always routed to ai_events */
    INGESTION_AI_EVENT_SPLITTING_TEAMS: string
    /**
     * Sticky percentage rollout (0-100), unioned with INGESTION_AI_EVENT_SPLITTING_TEAMS.
     * Bucketed deterministically on team_id so increases are monotonic and per-team writes don't flap.
     */
    INGESTION_AI_EVENT_SPLITTING_PERCENTAGE: number
    /**
     * Teams whose events copy should have heavy AI properties stripped — i.e. the post-migration final state
     * where heavy columns live only in the AI events table. '*' for all teams, or comma-separated team IDs.
     * Defaults to '' (no stripping → double-write the full event for everyone).
     */
    INGESTION_AI_EVENT_SPLITTING_STRIP_HEAVY_TEAMS: string

    // Clickhouse topics
    CLICKHOUSE_JSON_EVENTS_KAFKA_TOPIC: string
    CLICKHOUSE_AI_EVENTS_KAFKA_TOPIC: string
    CLICKHOUSE_HEATMAPS_KAFKA_TOPIC: string

    // Cookieless server hash mode config
    COOKIELESS_DISABLED: boolean
    COOKIELESS_FORCE_STATELESS_MODE: boolean
    COOKIELESS_DELETE_EXPIRED_LOCAL_SALTS_INTERVAL_MS: number
    COOKIELESS_SESSION_TTL_SECONDS: number
    COOKIELESS_SALT_TTL_SECONDS: number
    COOKIELESS_SESSION_INACTIVITY_MS: number
    COOKIELESS_IDENTIFIES_TTL_SECONDS: number
    COOKIELESS_REDIS_HOST: string
    COOKIELESS_REDIS_PORT: number

    // Property definitions
    PROPERTY_DEFS_CONSUMER_GROUP_ID: string
    PROPERTY_DEFS_CONSUMER_CONSUME_TOPIC: string
    PROPERTY_DEFS_CONSUMER_ENABLED_TEAMS: string
    PROPERTY_DEFS_WRITE_DISABLED: boolean

    // Ingestion caching
    DISTINCT_ID_LRU_SIZE: number
    EVENT_PROPERTY_LRU_SIZE: number
    PERSON_INFO_CACHE_TTL: number

    // Ingestion pipeline
    INGESTION_PIPELINE: string | null
    PLUGIN_SERVER_EVENTS_INGESTION_PIPELINE: string | null
}

export function getDefaultIngestionConsumerConfig(): IngestionConsumerConfig {
    return {
        INGESTION_LANE: null,

        // Kafka consumer config
        INGESTION_CONSUMER_GROUP_ID: 'events-ingestion-consumer',
        INGESTION_CONSUMER_CONSUME_TOPIC: KAFKA_EVENTS_PLUGIN_INGESTION,
        INGESTION_CONSUMER_DLQ_TOPIC: KAFKA_EVENTS_PLUGIN_INGESTION_DLQ,
        INGESTION_CONSUMER_OVERFLOW_TOPIC: KAFKA_EVENTS_PLUGIN_INGESTION_OVERFLOW,

        // Ingestion pipeline config
        INGESTION_BATCH_SIZE: 500,
        INGESTION_OVERFLOW_ENABLED: false,
        INGESTION_FORCE_OVERFLOW_BY_TOKEN_DISTINCT_ID: '',
        INGESTION_OVERFLOW_PRESERVE_PARTITION_LOCALITY: false,

        // Person batch writing config
        PERSON_BATCH_WRITING_DB_WRITE_MODE: 'NO_ASSERT',
        PERSON_BATCH_WRITING_USE_BATCH_UPDATES: true,
        PERSON_BATCH_WRITING_OPTIMISTIC_UPDATES_ENABLED: false,
        PERSON_BATCH_WRITING_MAX_CONCURRENT_UPDATES: 10,
        PERSON_BATCH_WRITING_MAX_OPTIMISTIC_UPDATE_RETRIES: 5,
        PERSON_BATCH_WRITING_OPTIMISTIC_UPDATE_RETRY_INTERVAL_MS: 50,
        PERSONS_PREFETCH_ENABLED: false,

        // Person properties config
        PERSON_UPDATE_CALCULATE_PROPERTIES_SIZE: 0,
        PERSON_PROPERTIES_DB_CONSTRAINT_LIMIT_BYTES: 655360,
        PERSON_PROPERTIES_TRIM_TARGET_BYTES: 512 * 1024,
        PERSON_PROPERTIES_UPDATE_ALL: false,
        PERSON_JSONB_SIZE_ESTIMATE_ENABLE: 0,

        // Person merge config
        PERSON_MERGE_MOVE_DISTINCT_ID_LIMIT: 0,
        PERSON_MERGE_ASYNC_TOPIC: '',
        PERSON_MERGE_ASYNC_ENABLED: false,
        PERSON_MERGE_SYNC_BATCH_SIZE: 0,

        // Group batch writing config
        GROUP_BATCH_WRITING_MAX_CONCURRENT_UPDATES: 10,
        GROUP_BATCH_WRITING_MAX_OPTIMISTIC_UPDATE_RETRIES: 5,
        GROUP_BATCH_WRITING_OPTIMISTIC_UPDATE_RETRY_INTERVAL_MS: 50,

        // Event overflow config
        EVENT_OVERFLOW_BUCKET_CAPACITY: 1000,
        EVENT_OVERFLOW_BUCKET_REPLENISH_RATE: 1.0,

        // Stateful overflow config
        INGESTION_STATEFUL_OVERFLOW_ENABLED: false,
        INGESTION_STATEFUL_OVERFLOW_REDIS_TTL_SECONDS: 300,
        INGESTION_STATEFUL_OVERFLOW_LOCAL_CACHE_TTL_SECONDS: 60,

        // Per-token/distinct_id restrictions
        DROP_EVENTS_BY_TOKEN_DISTINCT_ID: '',
        SKIP_PERSONS_PROCESSING_BY_TOKEN_DISTINCT_ID: '',
        MAX_TEAM_ID_TO_BUFFER_ANONYMOUS_EVENTS_FOR: 0,

        // Pipeline step config
        SKIP_UPDATE_EVENT_AND_PROPERTIES_STEP: false,
        EVENT_SCHEMA_ENFORCEMENT_ENABLED: true,
        KAFKA_BATCH_START_LOGGING_ENABLED: false,

        // AI event splitting config
        INGESTION_AI_EVENT_SPLITTING_ENABLED: false,
        INGESTION_AI_EVENT_SPLITTING_TEAMS: '*',
        INGESTION_AI_EVENT_SPLITTING_PERCENTAGE: 0,
        INGESTION_AI_EVENT_SPLITTING_STRIP_HEAVY_TEAMS: '',

        // Clickhouse topics
        CLICKHOUSE_JSON_EVENTS_KAFKA_TOPIC: KAFKA_EVENTS_JSON,
        CLICKHOUSE_AI_EVENTS_KAFKA_TOPIC: KAFKA_CLICKHOUSE_AI_EVENTS_JSON,
        CLICKHOUSE_HEATMAPS_KAFKA_TOPIC: KAFKA_CLICKHOUSE_HEATMAP_EVENTS,

        // Cookieless server hash mode config
        COOKIELESS_DISABLED: false,
        COOKIELESS_FORCE_STATELESS_MODE: false,
        COOKIELESS_DELETE_EXPIRED_LOCAL_SALTS_INTERVAL_MS: 60 * 60 * 1000,
        COOKIELESS_SESSION_TTL_SECONDS: 60 * 60 * (72 + 24),
        COOKIELESS_SALT_TTL_SECONDS: 60 * 60 * (72 + 24),
        COOKIELESS_SESSION_INACTIVITY_MS: 30 * 60 * 1000,
        COOKIELESS_IDENTIFIES_TTL_SECONDS: (72 + 12 + 14 + 24) * 60 * 60,
        COOKIELESS_REDIS_HOST: '',
        COOKIELESS_REDIS_PORT: 6379,

        // Property definitions
        PROPERTY_DEFS_CONSUMER_GROUP_ID: 'property-defs-consumer',
        PROPERTY_DEFS_CONSUMER_CONSUME_TOPIC: KAFKA_EVENTS_JSON,
        PROPERTY_DEFS_CONSUMER_ENABLED_TEAMS: isDevEnv() ? '*' : '',
        PROPERTY_DEFS_WRITE_DISABLED: isProdEnv() ? true : false,

        // Ingestion caching
        DISTINCT_ID_LRU_SIZE: 10000,
        EVENT_PROPERTY_LRU_SIZE: 10000,
        PERSON_INFO_CACHE_TTL: 5 * 60,

        // Ingestion pipeline
        INGESTION_PIPELINE: null,
        PLUGIN_SERVER_EVENTS_INGESTION_PIPELINE: null,
    }
}

/** Config type for all analytics ingestion output keys. */
export type IngestionOutputsConfig = {
    INGESTION_OUTPUT_EVENTS_TOPIC: string
    INGESTION_OUTPUT_EVENTS_PRODUCER: ProducerName
    INGESTION_OUTPUT_EVENTS_SECONDARY_TOPIC: string
    INGESTION_OUTPUT_EVENTS_SECONDARY_PRODUCER: ProducerName
    INGESTION_OUTPUT_EVENTS_SECONDARY_MODE: DualWriteMode
    INGESTION_OUTPUT_EVENTS_SECONDARY_PERCENTAGE: number
    INGESTION_OUTPUT_EVENTS_SECONDARY_TEAM_DENYLIST: string

    INGESTION_OUTPUT_AI_EVENTS_TOPIC: string
    INGESTION_OUTPUT_AI_EVENTS_PRODUCER: ProducerName
    INGESTION_OUTPUT_AI_EVENTS_SECONDARY_TOPIC: string
    INGESTION_OUTPUT_AI_EVENTS_SECONDARY_PRODUCER: ProducerName
    INGESTION_OUTPUT_AI_EVENTS_SECONDARY_MODE: DualWriteMode
    INGESTION_OUTPUT_AI_EVENTS_SECONDARY_PERCENTAGE: number
    INGESTION_OUTPUT_AI_EVENTS_SECONDARY_TEAM_DENYLIST: string

    INGESTION_OUTPUT_HEATMAPS_TOPIC: string
    INGESTION_OUTPUT_HEATMAPS_PRODUCER: ProducerName
    INGESTION_OUTPUT_HEATMAPS_SECONDARY_TOPIC: string
    INGESTION_OUTPUT_HEATMAPS_SECONDARY_PRODUCER: ProducerName
    INGESTION_OUTPUT_HEATMAPS_SECONDARY_MODE: DualWriteMode
    INGESTION_OUTPUT_HEATMAPS_SECONDARY_PERCENTAGE: number
    INGESTION_OUTPUT_HEATMAPS_SECONDARY_TEAM_DENYLIST: string

    INGESTION_OUTPUT_INGESTION_WARNINGS_TOPIC: string
    INGESTION_OUTPUT_INGESTION_WARNINGS_PRODUCER: ProducerName
    INGESTION_OUTPUT_INGESTION_WARNINGS_SECONDARY_TOPIC: string
    INGESTION_OUTPUT_INGESTION_WARNINGS_SECONDARY_PRODUCER: ProducerName
    INGESTION_OUTPUT_INGESTION_WARNINGS_SECONDARY_MODE: DualWriteMode
    INGESTION_OUTPUT_INGESTION_WARNINGS_SECONDARY_PERCENTAGE: number

    INGESTION_OUTPUT_DLQ_TOPIC: string
    INGESTION_OUTPUT_DLQ_PRODUCER: ProducerName
    INGESTION_OUTPUT_DLQ_SECONDARY_TOPIC: string
    INGESTION_OUTPUT_DLQ_SECONDARY_PRODUCER: ProducerName
    INGESTION_OUTPUT_DLQ_SECONDARY_MODE: DualWriteMode
    INGESTION_OUTPUT_DLQ_SECONDARY_PERCENTAGE: number

    INGESTION_OUTPUT_OVERFLOW_TOPIC: string
    INGESTION_OUTPUT_OVERFLOW_PRODUCER: ProducerName
    INGESTION_OUTPUT_OVERFLOW_SECONDARY_TOPIC: string
    INGESTION_OUTPUT_OVERFLOW_SECONDARY_PRODUCER: ProducerName
    INGESTION_OUTPUT_OVERFLOW_SECONDARY_MODE: DualWriteMode
    INGESTION_OUTPUT_OVERFLOW_SECONDARY_PERCENTAGE: number

    INGESTION_OUTPUT_ASYNC_TOPIC: string
    INGESTION_OUTPUT_ASYNC_PRODUCER: ProducerName
    INGESTION_OUTPUT_ASYNC_SECONDARY_TOPIC: string
    INGESTION_OUTPUT_ASYNC_SECONDARY_PRODUCER: ProducerName
    INGESTION_OUTPUT_ASYNC_SECONDARY_MODE: DualWriteMode
    INGESTION_OUTPUT_ASYNC_SECONDARY_PERCENTAGE: number

    INGESTION_OUTPUT_GROUPS_TOPIC: string
    INGESTION_OUTPUT_GROUPS_PRODUCER: ProducerName
    INGESTION_OUTPUT_GROUPS_SECONDARY_TOPIC: string
    INGESTION_OUTPUT_GROUPS_SECONDARY_PRODUCER: ProducerName
    INGESTION_OUTPUT_GROUPS_SECONDARY_MODE: DualWriteMode
    INGESTION_OUTPUT_GROUPS_SECONDARY_PERCENTAGE: number
    INGESTION_OUTPUT_GROUPS_SECONDARY_TEAM_DENYLIST: string

    INGESTION_OUTPUT_PERSONS_TOPIC: string
    INGESTION_OUTPUT_PERSONS_PRODUCER: ProducerName
    INGESTION_OUTPUT_PERSONS_SECONDARY_TOPIC: string
    INGESTION_OUTPUT_PERSONS_SECONDARY_PRODUCER: ProducerName
    INGESTION_OUTPUT_PERSONS_SECONDARY_MODE: DualWriteMode
    INGESTION_OUTPUT_PERSONS_SECONDARY_PERCENTAGE: number
    INGESTION_OUTPUT_PERSONS_SECONDARY_TEAM_DENYLIST: string

    INGESTION_OUTPUT_PERSON_DISTINCT_IDS_TOPIC: string
    INGESTION_OUTPUT_PERSON_DISTINCT_IDS_PRODUCER: ProducerName
    INGESTION_OUTPUT_PERSON_DISTINCT_IDS_SECONDARY_TOPIC: string
    INGESTION_OUTPUT_PERSON_DISTINCT_IDS_SECONDARY_PRODUCER: ProducerName
    INGESTION_OUTPUT_PERSON_DISTINCT_IDS_SECONDARY_MODE: DualWriteMode
    INGESTION_OUTPUT_PERSON_DISTINCT_IDS_SECONDARY_PERCENTAGE: number
    INGESTION_OUTPUT_PERSON_DISTINCT_IDS_SECONDARY_TEAM_DENYLIST: string

    INGESTION_OUTPUT_APP_METRICS_TOPIC: string
    INGESTION_OUTPUT_APP_METRICS_PRODUCER: ProducerName
    INGESTION_OUTPUT_APP_METRICS_SECONDARY_TOPIC: string
    INGESTION_OUTPUT_APP_METRICS_SECONDARY_PRODUCER: ProducerName
    INGESTION_OUTPUT_APP_METRICS_SECONDARY_MODE: DualWriteMode
    INGESTION_OUTPUT_APP_METRICS_SECONDARY_PERCENTAGE: number
    INGESTION_OUTPUT_APP_METRICS_SECONDARY_TEAM_DENYLIST: string

    INGESTION_OUTPUT_LOG_ENTRIES_TOPIC: string
    INGESTION_OUTPUT_LOG_ENTRIES_PRODUCER: ProducerName
    INGESTION_OUTPUT_LOG_ENTRIES_SECONDARY_TOPIC: string
    INGESTION_OUTPUT_LOG_ENTRIES_SECONDARY_PRODUCER: ProducerName
    INGESTION_OUTPUT_LOG_ENTRIES_SECONDARY_MODE: DualWriteMode
    INGESTION_OUTPUT_LOG_ENTRIES_SECONDARY_PERCENTAGE: number

    INGESTION_OUTPUT_TOPHOG_TOPIC: string
    INGESTION_OUTPUT_TOPHOG_PRODUCER: ProducerName
    INGESTION_OUTPUT_TOPHOG_SECONDARY_TOPIC: string
    INGESTION_OUTPUT_TOPHOG_SECONDARY_PRODUCER: ProducerName
    INGESTION_OUTPUT_TOPHOG_SECONDARY_MODE: DualWriteMode
    INGESTION_OUTPUT_TOPHOG_SECONDARY_PERCENTAGE: number
}

export function getDefaultIngestionOutputsConfig(): IngestionOutputsConfig {
    return {
        INGESTION_OUTPUT_EVENTS_TOPIC: KAFKA_EVENTS_JSON,
        INGESTION_OUTPUT_EVENTS_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_EVENTS_SECONDARY_TOPIC: '',
        INGESTION_OUTPUT_EVENTS_SECONDARY_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_EVENTS_SECONDARY_MODE: 'off',
        INGESTION_OUTPUT_EVENTS_SECONDARY_PERCENTAGE: 0,
        INGESTION_OUTPUT_EVENTS_SECONDARY_TEAM_DENYLIST: '',
        INGESTION_OUTPUT_AI_EVENTS_TOPIC: KAFKA_CLICKHOUSE_AI_EVENTS_JSON,
        INGESTION_OUTPUT_AI_EVENTS_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_AI_EVENTS_SECONDARY_TOPIC: '',
        INGESTION_OUTPUT_AI_EVENTS_SECONDARY_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_AI_EVENTS_SECONDARY_MODE: 'off',
        INGESTION_OUTPUT_AI_EVENTS_SECONDARY_PERCENTAGE: 0,
        INGESTION_OUTPUT_AI_EVENTS_SECONDARY_TEAM_DENYLIST: '',
        INGESTION_OUTPUT_HEATMAPS_TOPIC: KAFKA_CLICKHOUSE_HEATMAP_EVENTS,
        INGESTION_OUTPUT_HEATMAPS_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_HEATMAPS_SECONDARY_TOPIC: '',
        INGESTION_OUTPUT_HEATMAPS_SECONDARY_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_HEATMAPS_SECONDARY_MODE: 'off',
        INGESTION_OUTPUT_HEATMAPS_SECONDARY_PERCENTAGE: 0,
        INGESTION_OUTPUT_HEATMAPS_SECONDARY_TEAM_DENYLIST: '',
        INGESTION_OUTPUT_INGESTION_WARNINGS_TOPIC: KAFKA_INGESTION_WARNINGS,
        INGESTION_OUTPUT_INGESTION_WARNINGS_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_INGESTION_WARNINGS_SECONDARY_TOPIC: '',
        INGESTION_OUTPUT_INGESTION_WARNINGS_SECONDARY_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_INGESTION_WARNINGS_SECONDARY_MODE: 'off',
        INGESTION_OUTPUT_INGESTION_WARNINGS_SECONDARY_PERCENTAGE: 0,
        INGESTION_OUTPUT_DLQ_TOPIC: KAFKA_EVENTS_PLUGIN_INGESTION_DLQ,
        INGESTION_OUTPUT_DLQ_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_DLQ_SECONDARY_TOPIC: '',
        INGESTION_OUTPUT_DLQ_SECONDARY_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_DLQ_SECONDARY_MODE: 'off',
        INGESTION_OUTPUT_DLQ_SECONDARY_PERCENTAGE: 0,
        INGESTION_OUTPUT_OVERFLOW_TOPIC: KAFKA_EVENTS_PLUGIN_INGESTION_OVERFLOW,
        INGESTION_OUTPUT_OVERFLOW_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_OVERFLOW_SECONDARY_TOPIC: '',
        INGESTION_OUTPUT_OVERFLOW_SECONDARY_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_OVERFLOW_SECONDARY_MODE: 'off',
        INGESTION_OUTPUT_OVERFLOW_SECONDARY_PERCENTAGE: 0,
        INGESTION_OUTPUT_ASYNC_TOPIC: KAFKA_EVENTS_PLUGIN_INGESTION_ASYNC,
        INGESTION_OUTPUT_ASYNC_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_ASYNC_SECONDARY_TOPIC: '',
        INGESTION_OUTPUT_ASYNC_SECONDARY_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_ASYNC_SECONDARY_MODE: 'off',
        INGESTION_OUTPUT_ASYNC_SECONDARY_PERCENTAGE: 0,
        INGESTION_OUTPUT_GROUPS_TOPIC: KAFKA_GROUPS,
        INGESTION_OUTPUT_GROUPS_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_GROUPS_SECONDARY_TOPIC: '',
        INGESTION_OUTPUT_GROUPS_SECONDARY_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_GROUPS_SECONDARY_MODE: 'off',
        INGESTION_OUTPUT_GROUPS_SECONDARY_PERCENTAGE: 0,
        INGESTION_OUTPUT_GROUPS_SECONDARY_TEAM_DENYLIST: '',
        INGESTION_OUTPUT_PERSONS_TOPIC: KAFKA_PERSON,
        INGESTION_OUTPUT_PERSONS_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_PERSONS_SECONDARY_TOPIC: '',
        INGESTION_OUTPUT_PERSONS_SECONDARY_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_PERSONS_SECONDARY_MODE: 'off',
        INGESTION_OUTPUT_PERSONS_SECONDARY_PERCENTAGE: 0,
        INGESTION_OUTPUT_PERSONS_SECONDARY_TEAM_DENYLIST: '',
        INGESTION_OUTPUT_PERSON_DISTINCT_IDS_TOPIC: KAFKA_PERSON_DISTINCT_ID,
        INGESTION_OUTPUT_PERSON_DISTINCT_IDS_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_PERSON_DISTINCT_IDS_SECONDARY_TOPIC: '',
        INGESTION_OUTPUT_PERSON_DISTINCT_IDS_SECONDARY_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_PERSON_DISTINCT_IDS_SECONDARY_MODE: 'off',
        INGESTION_OUTPUT_PERSON_DISTINCT_IDS_SECONDARY_PERCENTAGE: 0,
        INGESTION_OUTPUT_PERSON_DISTINCT_IDS_SECONDARY_TEAM_DENYLIST: '',
        INGESTION_OUTPUT_APP_METRICS_TOPIC: KAFKA_APP_METRICS_2,
        INGESTION_OUTPUT_APP_METRICS_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_APP_METRICS_SECONDARY_TOPIC: '',
        INGESTION_OUTPUT_APP_METRICS_SECONDARY_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_APP_METRICS_SECONDARY_MODE: 'off',
        INGESTION_OUTPUT_APP_METRICS_SECONDARY_PERCENTAGE: 0,
        INGESTION_OUTPUT_APP_METRICS_SECONDARY_TEAM_DENYLIST: '',
        INGESTION_OUTPUT_LOG_ENTRIES_TOPIC: KAFKA_LOG_ENTRIES,
        INGESTION_OUTPUT_LOG_ENTRIES_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_LOG_ENTRIES_SECONDARY_TOPIC: '',
        INGESTION_OUTPUT_LOG_ENTRIES_SECONDARY_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_LOG_ENTRIES_SECONDARY_MODE: 'off',
        INGESTION_OUTPUT_LOG_ENTRIES_SECONDARY_PERCENTAGE: 0,
        INGESTION_OUTPUT_TOPHOG_TOPIC: KAFKA_CLICKHOUSE_TOPHOG,
        INGESTION_OUTPUT_TOPHOG_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_TOPHOG_SECONDARY_TOPIC: '',
        INGESTION_OUTPUT_TOPHOG_SECONDARY_PRODUCER: DEFAULT_PRODUCER,
        INGESTION_OUTPUT_TOPHOG_SECONDARY_MODE: 'off',
        INGESTION_OUTPUT_TOPHOG_SECONDARY_PERCENTAGE: 0,
    }
}
