import { MakeLogicType, actions, afterMount, connect, kea, listeners, path, reducers } from 'kea'
import { loaders } from 'kea-loaders'

import { lemonToast } from '@posthog/lemon-ui'

import { projectLogic } from 'scenes/projectLogic'

import {
    hogFlowsBatchJobsList,
    hogFlowsList,
    hogFlowsMetricsTotalsRetrieve,
} from 'products/workflows/frontend/generated/api'
import type {
    HogFlowBatchJobApi,
    HogFlowMinimalApi,
    PaginatedHogFlowMinimalListApi,
} from 'products/workflows/frontend/generated/api.schemas'

export type BroadcastStatus = 'draft' | 'scheduled' | 'sending' | 'sent' | 'archived'

export interface BroadcastRowDetails {
    latestBatchJob: HogFlowBatchJobApi | null
    totals: Record<string, number>
}

export function getBroadcastStatus(
    broadcast: HogFlowMinimalApi,
    details: BroadcastRowDetails | undefined
): BroadcastStatus {
    if (broadcast.status === 'draft') {
        return 'draft'
    }
    if (broadcast.status === 'archived') {
        return 'archived'
    }
    const latestJob = details?.latestBatchJob
    if (latestJob) {
        if (['waiting', 'queued', 'active'].includes(latestJob.status ?? '')) {
            return 'sending'
        }
        if (latestJob.status === 'completed') {
            return 'sent'
        }
    }
    // Active with no batch job yet: it's waiting on its schedule (or a manual send).
    return 'scheduled'
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface broadcastsLogicValues {
    currentProjectId: number | null // projectLogic
    broadcasts: PaginatedHogFlowMinimalListApi
    broadcastsLoading: boolean
    hasLoadedBroadcasts: boolean
    rowDetailsById: Record<string, BroadcastRowDetails>
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface broadcastsLogicActions {
    loadBroadcasts: () => {
        value: true
    }
    loadBroadcastsFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadBroadcastsSuccess: (
        broadcasts: PaginatedHogFlowMinimalListApi,
        payload?: {
            value: true
        }
    ) => {
        broadcasts: PaginatedHogFlowMinimalListApi
        payload?: {
            value: true
        }
    }
    setRowDetails: (
        id: string,
        details: BroadcastRowDetails
    ) => {
        details: BroadcastRowDetails
        id: string
    }
}

export type broadcastsLogicType = MakeLogicType<broadcastsLogicValues, broadcastsLogicActions>

export const broadcastsLogic = kea<broadcastsLogicType>([
    path(['products', 'workflows', 'frontend', 'Broadcasts', 'broadcastsLogic']),
    connect(() => ({
        values: [projectLogic, ['currentProjectId']],
    })),
    actions({
        loadBroadcasts: true,
        setRowDetails: (id: string, details: BroadcastRowDetails) => ({ id, details }),
    }),
    loaders(({ values }) => ({
        broadcasts: [
            { results: [], count: 0 } as PaginatedHogFlowMinimalListApi,
            {
                loadBroadcasts: async () => {
                    if (!values.currentProjectId) {
                        return values.broadcasts
                    }
                    return await hogFlowsList(String(values.currentProjectId), { kind: 'broadcast', limit: 100 })
                },
            },
        ],
    })),
    reducers({
        rowDetailsById: [
            {} as Record<string, BroadcastRowDetails>,
            {
                setRowDetails: (state, { id, details }) => ({ ...state, [id]: details }),
            },
        ],
        hasLoadedBroadcasts: [
            false as boolean,
            {
                loadBroadcastsSuccess: () => true,
            },
        ],
    }),
    listeners(({ actions, values }) => ({
        loadBroadcastsSuccess: ({ broadcasts }) => {
            const projectId = values.currentProjectId
            if (!projectId) {
                return
            }
            // Best-effort per-row enrichment: batch jobs decide the status chip, metric totals fill
            // the engagement counts. Rows without details just show their fallbacks.
            for (const broadcast of broadcasts.results ?? []) {
                void (async () => {
                    try {
                        const [batchJobs, totals] = await Promise.all([
                            broadcast.status === 'draft'
                                ? Promise.resolve([] as HogFlowBatchJobApi[])
                                : hogFlowsBatchJobsList(String(projectId), broadcast.id),
                            broadcast.status === 'draft'
                                ? Promise.resolve({ totals: {} })
                                : hogFlowsMetricsTotalsRetrieve(String(projectId), broadcast.id, {
                                      breakdown_by: 'name',
                                      after: '-90d',
                                  }),
                        ])
                        actions.setRowDetails(broadcast.id, {
                            latestBatchJob: batchJobs[0] ?? null,
                            totals: totals.totals ?? {},
                        })
                    } catch {
                        // Leave the row on its fallbacks; the list itself already loaded.
                    }
                })()
            }
        },
        loadBroadcastsFailure: () => {
            lemonToast.error("Couldn't load broadcasts. Refresh the page to try again.")
        },
    })),
    afterMount(({ actions }) => {
        actions.loadBroadcasts()
    }),
])
