import {
    HTMLSnippetInstructions,
    JSWebInstructions,
    ProductAnalyticsAPIInstructions,
    ProductAnalyticsAndroidInstructions,
    ProductAnalyticsAngularInstructions,
    ProductAnalyticsAstroInstructions,
    ProductAnalyticsBubbleInstructions,
    ProductAnalyticsDjangoInstructions,
    ProductAnalyticsDocusaurusInstructions,
    ProductAnalyticsElixirInstructions,
    ProductAnalyticsFlutterInstructions,
    ProductAnalyticsFramerInstructions,
    ProductAnalyticsGoInstructions,
    ProductAnalyticsGoogleTagManagerInstructions,
    ProductAnalyticsHeliconeInstructions,
    ProductAnalyticsIOSInstructions,
    ProductAnalyticsLangfuseInstructions,
    ProductAnalyticsLaravelInstructions,
    ProductAnalyticsMoEngageInstructions,
    ProductAnalyticsN8nInstructions,
    ProductAnalyticsNextJSInstructions,
    ProductAnalyticsNodeInstructions,
    ProductAnalyticsNuxtJSInstructions,
    ProductAnalyticsPHPInstructions,
    ProductAnalyticsPythonInstructions,
    ProductAnalyticsRNInstructions,
    ProductAnalyticsReactInstructions,
    ProductAnalyticsRemixJSInstructions,
    ProductAnalyticsRetoolInstructions,
    ProductAnalyticsRubyInstructions,
    ProductAnalyticsRudderstackInstructions,
    ProductAnalyticsSegmentInstructions,
    ProductAnalyticsSentryInstructions,
    ProductAnalyticsShopifyInstructions,
    ProductAnalyticsSvelteJSInstructions,
    ProductAnalyticsTraceloopInstructions,
    ProductAnalyticsVueInstructions,
    ProductAnalyticsWebflowInstructions,
    ProductAnalyticsWordpressInstructions,
    ProductAnalyticsZapierInstructions,
} from '.'

import { SDKInstructionsMap, SDKKey } from '~/types'

export const ProductAnalyticsSDKInstructions: SDKInstructionsMap = {
    [SDKKey.JS_WEB]: JSWebInstructions,
    [SDKKey.ANDROID]: ProductAnalyticsAndroidInstructions,
    [SDKKey.ANGULAR]: ProductAnalyticsAngularInstructions,
    [SDKKey.REACT]: ProductAnalyticsReactInstructions,
    [SDKKey.API]: ProductAnalyticsAPIInstructions,
    [SDKKey.ASTRO]: ProductAnalyticsAstroInstructions,
    [SDKKey.BUBBLE]: ProductAnalyticsBubbleInstructions,
    [SDKKey.DJANGO]: ProductAnalyticsDjangoInstructions,
    [SDKKey.DOCUSAURUS]: ProductAnalyticsDocusaurusInstructions,
    [SDKKey.ELIXIR]: ProductAnalyticsElixirInstructions,
    [SDKKey.FLUTTER]: ProductAnalyticsFlutterInstructions,
    [SDKKey.FRAMER]: ProductAnalyticsFramerInstructions,
    [SDKKey.GO]: ProductAnalyticsGoInstructions,
    [SDKKey.GOOGLE_TAG_MANAGER]: ProductAnalyticsGoogleTagManagerInstructions,
    [SDKKey.HELICONE]: ProductAnalyticsHeliconeInstructions,
    [SDKKey.HTML_SNIPPET]: HTMLSnippetInstructions,
    [SDKKey.IOS]: ProductAnalyticsIOSInstructions,
    [SDKKey.LANGFUSE]: ProductAnalyticsLangfuseInstructions,
    [SDKKey.LARAVEL]: ProductAnalyticsLaravelInstructions,
    [SDKKey.MOENGAGE]: ProductAnalyticsMoEngageInstructions,
    [SDKKey.N8N]: ProductAnalyticsN8nInstructions,
    [SDKKey.NEXT_JS]: ProductAnalyticsNextJSInstructions,
    [SDKKey.NODE_JS]: ProductAnalyticsNodeInstructions,
    [SDKKey.NUXT_JS]: ProductAnalyticsNuxtJSInstructions,
    [SDKKey.PHP]: ProductAnalyticsPHPInstructions,
    [SDKKey.PYTHON]: ProductAnalyticsPythonInstructions,
    [SDKKey.REACT_NATIVE]: ProductAnalyticsRNInstructions,
    [SDKKey.REMIX]: ProductAnalyticsRemixJSInstructions,
    [SDKKey.RETOOL]: ProductAnalyticsRetoolInstructions,
    [SDKKey.RUBY]: ProductAnalyticsRubyInstructions,
    [SDKKey.RUDDERSTACK]: ProductAnalyticsRudderstackInstructions,
    [SDKKey.SEGMENT]: ProductAnalyticsSegmentInstructions,
    [SDKKey.SENTRY]: ProductAnalyticsSentryInstructions,
    [SDKKey.SHOPIFY]: ProductAnalyticsShopifyInstructions,
    [SDKKey.SVELTE]: ProductAnalyticsSvelteJSInstructions,
    [SDKKey.TANSTACK_START]: ProductAnalyticsReactInstructions,
    [SDKKey.TRACELOOP]: ProductAnalyticsTraceloopInstructions,
    [SDKKey.VITE]: ProductAnalyticsReactInstructions,
    [SDKKey.VUE_JS]: ProductAnalyticsVueInstructions,
    [SDKKey.WEBFLOW]: ProductAnalyticsWebflowInstructions,
    [SDKKey.WORDPRESS]: ProductAnalyticsWordpressInstructions,
    [SDKKey.ZAPIER]: ProductAnalyticsZapierInstructions,
}
