from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "syncs": {
        "description": "Syncs define how data from models is mapped to destinations. Each time a sync runs, Hightouch calculates the rows that changed since the last run and syncs them to the destination.",
        "docs_url": "https://hightouch.com/docs/api-reference",
        "columns": {
            "id": "The sync's id.",
            "slug": "The sync's slug.",
            "workspaceId": "The id of the workspace that the sync belongs to.",
            "createdAt": "The timestamp when the sync was created.",
            "updatedAt": "The timestamp when the sync was last updated.",
            "destinationId": "The id of the destination that the sync is connected to.",
            "modelId": "The id of the model that the sync is connected to.",
            "schedule": "The scheduling configuration: interval, cron expression, visual cron, or dbt Cloud job.",
            "status": "The sync's status (e.g. disabled, pending, cancelled, failed, queued, success, warning, querying, processing, reporting, interrupted).",
            "disabled": "Whether the sync has been disabled by the user.",
            "lastRunAt": "The timestamp of the last sync run.",
            "primaryKey": "The primary key the sync uses to identify data from the source.",
            "referencedColumns": "The reference columns that the sync depends on to sync data from the source.",
        },
    },
    "sync_runs": {
        "description": "One row per execution of a sync: its status, row counts, and timing. Runs are fetched per sync and carry the parent sync id in `sync_id`.",
        "docs_url": "https://hightouch.com/docs/api-reference",
        "columns": {
            "id": "The sync run's id, unique within its sync.",
            "sync_id": "The id of the sync this run belongs to (from the parent sync).",
            "status": "The status of the sync run (e.g. queued, querying, processing, reporting, success, failed, cancelled, warning, interrupted).",
            "createdAt": "The timestamp when the sync run was created. Usually equal to startedAt, but earlier if the run was queued behind another run.",
            "startedAt": "The timestamp when the sync run started.",
            "finishedAt": "The timestamp when the sync run finished.",
            "plannedRows": "The number of rows (added/changed/removed) that this run was supposed to execute.",
            "successfulRows": "The number of rows (added/changed/removed) successfully processed by the destination.",
            "failedRows": "The number of rows (added/changed/removed) that were attempted but rejected by the destination.",
            "querySize": "The number of rows in the query.",
            "completionRatio": "The completion ratio of the sync run, showing its progress.",
            "error": "Error message if the sync run didn't finish successfully.",
        },
    },
    "models": {
        "description": "Models define the data to pull from a source, via raw SQL, a table reference, a dbt model, or a visual (audience) query.",
        "docs_url": "https://hightouch.com/docs/api-reference",
        "columns": {
            "id": "The id of the model.",
            "name": "The name of the model.",
            "slug": "The slug of the model.",
            "workspaceId": "The id of the workspace the model belongs to.",
            "createdAt": "The timestamp when the model was created.",
            "updatedAt": "The timestamp when the model was last updated.",
            "sourceId": "The id of the source the model is connected to.",
            "queryType": "The type of the query: custom, raw_sql, table, dbt, or visual.",
            "primaryKey": "The model's primary key. Null if the query isn't directly synced (e.g. a relationship table for visual querying).",
            "isSchema": "Whether the model is only used to build other models (as part of visual querying, or as the root of a visual query).",
            "raw": "The raw SQL query, for raw_sql models.",
            "table": "The table reference, for table-based models.",
            "dbt": "The dbt model reference, for dbt-based models.",
            "visual": "The visual (audience) query definition.",
            "custom": "Custom query for sources that don't support SQL (e.g. Airtable).",
            "syncs": "The ids of syncs that use this model.",
            "tags": "The tags of the model.",
        },
    },
    "sources": {
        "description": "Sources are the databases and warehouses Hightouch reads data from (e.g. Snowflake, BigQuery, Postgres).",
        "docs_url": "https://hightouch.com/docs/api-reference",
        "columns": {
            "id": "The source's id.",
            "name": "The source's name.",
            "slug": "The source's slug.",
            "type": "The source's type (e.g. snowflake or postgres).",
            "workspaceId": "The id of the workspace that the source belongs to.",
            "createdAt": "The timestamp when the source was created.",
            "updatedAt": "The timestamp when the source was last updated.",
        },
    },
    "destinations": {
        "description": "Destinations are the SaaS tools and services Hightouch syncs data into (e.g. Salesforce, HubSpot, Google Ads).",
        "docs_url": "https://hightouch.com/docs/api-reference",
        "columns": {
            "id": "The destination's id.",
            "name": "The destination's name.",
            "slug": "The destination's slug.",
            "type": "The destination's type (e.g. salesforce or hubspot).",
            "workspaceId": "The id of the workspace that the destination belongs to.",
            "createdAt": "The timestamp when the destination was created.",
            "updatedAt": "The timestamp when the destination was last updated.",
            "syncs": "The ids of syncs that sync to this destination.",
        },
    },
}
