from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Descriptions sourced from the Koyeb public API reference (https://developer.koyeb.com/public),
# generated from the spec at https://api.prod.koyeb.com/public.swagger.json.
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "projects": {
        "description": "Projects in your Koyeb organization. A project groups related apps and services.",
        "docs_url": "https://developer.koyeb.com/public#tag/projects",
        "columns": {
            "id": "Unique identifier of the project.",
            "name": "Name of the project.",
            "description": "Description of the project.",
            "organization_id": "Identifier of the organization owning the project.",
            "service_count": "Number of services in the project.",
            "created_at": "When the project was created.",
            "updated_at": "When the project was last updated.",
        },
    },
    "apps": {
        "description": "Applications in your Koyeb organization. An app groups services and holds the public *.koyeb.app domains assigned to them.",
        "docs_url": "https://developer.koyeb.com/public#tag/apps",
        "columns": {
            "id": "Unique identifier of the app.",
            "name": "Name of the app, used in the auto-assigned <app>-<org>.koyeb.app domain.",
            "organization_id": "Identifier of the organization owning the app.",
            "status": "Current status of the app (e.g. STARTING, HEALTHY, DELETED).",
            "domains": "Domains attached to the app, including the auto-assigned koyeb.app domain.",
            "created_at": "When the app was created.",
            "updated_at": "When the app was last updated.",
        },
    },
    "services": {
        "description": "Services running inside your Koyeb apps: web services, workers, and databases.",
        "docs_url": "https://developer.koyeb.com/public#tag/services",
        "columns": {
            "id": "Unique identifier of the service.",
            "name": "Name of the service.",
            "type": "Type of the service (WEB, WORKER, or DATABASE).",
            "app_id": "Identifier of the app the service belongs to.",
            "organization_id": "Identifier of the organization owning the service.",
            "status": "Current status of the service (e.g. STARTING, HEALTHY, PAUSED, DELETED).",
            "active_deployment_id": "Identifier of the deployment currently serving traffic.",
            "latest_deployment_id": "Identifier of the most recent deployment of the service.",
            "created_at": "When the service was created.",
            "updated_at": "When the service was last updated.",
        },
    },
    "deployments": {
        "description": "Deployments of your Koyeb services. Each deployment captures the full definition of a service version and its rollout status.",
        "docs_url": "https://developer.koyeb.com/public#tag/deployments",
        "columns": {
            "id": "Unique identifier of the deployment.",
            "app_id": "Identifier of the app the deployment belongs to.",
            "service_id": "Identifier of the service the deployment belongs to.",
            "parent_id": "Identifier of the deployment this one was created from.",
            "status": "Current status of the deployment (e.g. PENDING, HEALTHY, ERROR, STOPPED).",
            "definition": "Full definition of the deployment: image or git source, regions, ports, instance types, scaling, and environment.",
            "started_at": "When the deployment started.",
            "succeeded_at": "When the deployment succeeded.",
            "terminated_at": "When the deployment terminated.",
            "created_at": "When the deployment was created.",
            "updated_at": "When the deployment was last updated.",
        },
    },
    "regional_deployments": {
        "description": "Per-region rollouts of a deployment, one row per region a deployment runs in.",
        "docs_url": "https://developer.koyeb.com/public#tag/regional-deployments",
        "columns": {
            "id": "Unique identifier of the regional deployment.",
            "region": "Region the deployment runs in (e.g. fra, was, sin).",
            "status": "Current status of the regional deployment.",
            "created_at": "When the regional deployment was created.",
            "updated_at": "When the regional deployment was last updated.",
        },
    },
    "instances": {
        "description": "Compute instances backing your Koyeb services, one row per instance (replica) of a regional deployment.",
        "docs_url": "https://developer.koyeb.com/public#tag/instances",
        "columns": {
            "id": "Unique identifier of the instance.",
            "app_id": "Identifier of the app the instance belongs to.",
            "service_id": "Identifier of the service the instance belongs to.",
            "regional_deployment_id": "Identifier of the regional deployment the instance belongs to.",
            "replica_index": "Index of the replica within the regional deployment.",
            "region": "Region the instance runs in.",
            "datacenter": "Datacenter the instance runs in.",
            "type": "Instance type (e.g. nano, small, or a GPU type).",
            "status": "Current status of the instance (e.g. ALLOCATING, HEALTHY, STOPPED).",
            "created_at": "When the instance was created.",
            "updated_at": "When the instance was last updated.",
        },
    },
    "domains": {
        "description": "Domains in your Koyeb organization: auto-assigned *.koyeb.app domains and verified custom domains.",
        "docs_url": "https://developer.koyeb.com/public#tag/domains",
        "columns": {
            "id": "Unique identifier of the domain.",
            "name": "Fully qualified domain name.",
            "type": "Type of the domain (AUTOASSIGNED or CUSTOM).",
            "status": "Current status of the domain (e.g. PENDING, ACTIVE, ERROR).",
            "app_id": "Identifier of the app the domain is attached to.",
            "intended_cname": "CNAME record a custom domain must point at to be verified.",
            "verified_at": "When the domain was verified.",
            "created_at": "When the domain was created.",
        },
    },
    "secrets": {
        "description": "Secrets defined in your Koyeb organization. Metadata only — secret values are never returned by the list API and are not synced.",
        "docs_url": "https://developer.koyeb.com/public#tag/secrets",
        "columns": {
            "id": "Unique identifier of the secret.",
            "name": "Name of the secret.",
            "type": "Type of the secret (SIMPLE, REGISTRY, or MANAGED).",
            "created_at": "When the secret was created.",
            "updated_at": "When the secret was last updated.",
        },
    },
    "volumes": {
        "description": "Persistent volumes attached to your Koyeb services.",
        "docs_url": "https://developer.koyeb.com/public#tag/persistent-volumes",
        "columns": {
            "id": "Unique identifier of the volume.",
            "name": "Name of the volume.",
            "service_id": "Identifier of the service the volume is attached to.",
            "region": "Region the volume lives in.",
            "max_size": "Maximum size of the volume in GB.",
            "cur_size": "Current size of the volume in GB.",
            "status": "Current status of the volume (e.g. ATTACHED, DETACHED, DELETED).",
            "created_at": "When the volume was created.",
        },
    },
    "snapshots": {
        "description": "Snapshots of your Koyeb persistent volumes.",
        "docs_url": "https://developer.koyeb.com/public#tag/snapshots",
        "columns": {
            "id": "Unique identifier of the snapshot.",
            "name": "Name of the snapshot.",
            "parent_volume_id": "Identifier of the volume the snapshot was taken from.",
            "region": "Region the snapshot lives in.",
            "size": "Size of the snapshot in GB.",
            "status": "Current status of the snapshot.",
            "type": "Type of the snapshot (LOCAL or REMOTE).",
            "created_at": "When the snapshot was created.",
        },
    },
    "organization_members": {
        "description": "Members of the Koyeb organization the API token is scoped to.",
        "docs_url": "https://developer.koyeb.com/public#tag/organization-members",
        "columns": {
            "id": "Unique identifier of the membership.",
            "user_id": "Identifier of the member's user account.",
            "organization_id": "Identifier of the organization.",
            "role": "Role of the member within the organization (e.g. OWNER, MEMBER).",
            "status": "Current status of the membership.",
            "joined_at": "When the member joined the organization.",
        },
    },
    "activities": {
        "description": "Audit trail of actions performed in your Koyeb organization: who did what to which object.",
        "docs_url": "https://developer.koyeb.com/public#tag/activities",
        "columns": {
            "id": "Unique identifier of the activity.",
            "actor": "User or system that performed the action.",
            "object": "Object the action was performed on.",
            "verb": "Action performed (e.g. created, updated, deleted).",
            "metadata": "Additional context about the action.",
            "created_at": "When the activity occurred.",
        },
    },
    "app_events": {
        "description": "Append-only stream of lifecycle events for your Koyeb apps.",
        "docs_url": "https://developer.koyeb.com/public#tag/apps",
        "columns": {
            "id": "Unique identifier of the event.",
            "app_id": "Identifier of the app the event relates to.",
            "type": "Type of the event.",
            "message": "Human-readable description of the event.",
            "metadata": "Additional context about the event.",
            "when": "When the event occurred.",
        },
    },
    "service_events": {
        "description": "Append-only stream of lifecycle events for your Koyeb services.",
        "docs_url": "https://developer.koyeb.com/public#tag/services",
        "columns": {
            "id": "Unique identifier of the event.",
            "service_id": "Identifier of the service the event relates to.",
            "type": "Type of the event.",
            "message": "Human-readable description of the event.",
            "metadata": "Additional context about the event.",
            "when": "When the event occurred.",
        },
    },
    "deployment_events": {
        "description": "Append-only stream of lifecycle events for your Koyeb deployments.",
        "docs_url": "https://developer.koyeb.com/public#tag/deployments",
        "columns": {
            "id": "Unique identifier of the event.",
            "deployment_id": "Identifier of the deployment the event relates to.",
            "type": "Type of the event.",
            "message": "Human-readable description of the event.",
            "metadata": "Additional context about the event.",
            "when": "When the event occurred.",
        },
    },
    "instance_events": {
        "description": "Append-only stream of lifecycle events for your Koyeb instances.",
        "docs_url": "https://developer.koyeb.com/public#tag/instances",
        "columns": {
            "id": "Unique identifier of the event.",
            "instance_id": "Identifier of the instance the event relates to.",
            "type": "Type of the event.",
            "message": "Human-readable description of the event.",
            "metadata": "Additional context about the event.",
            "when": "When the event occurred.",
        },
    },
    "usage_details": {
        "description": "Per-instance usage records for your Koyeb organization: one row per instance run with its duration, used for billing.",
        "docs_url": "https://developer.koyeb.com/public#tag/usages",
        "columns": {
            "instance_id": "Identifier of the instance the usage relates to.",
            "instance_type": "Instance type the usage was billed as.",
            "app_id": "Identifier of the app the instance belonged to.",
            "app_name": "Name of the app the instance belonged to.",
            "service_id": "Identifier of the service the instance belonged to.",
            "service_name": "Name of the service the instance belonged to.",
            "region": "Region the instance ran in.",
            "duration_seconds": "How long the instance ran, in seconds.",
            "started_at": "When the instance run started.",
            "terminated_at": "When the instance run terminated.",
        },
    },
    "catalog_instances": {
        "description": "Catalog of Koyeb instance types with their resources, pricing, and availability. Join on instance_type to size and price services, deployments, and usage.",
        "docs_url": "https://developer.koyeb.com/public#tag/catalog-instances",
        "columns": {
            "id": "Name of the instance type (e.g. nano, small).",
            "display_name": "Display name of the instance type.",
            "description": "Short description of the instance type.",
            "type": "Type of the instance (e.g. gpu).",
            "vcpu": "Number of CPUs. Deprecated in favor of vcpu_shares.",
            "vcpu_shares": "Number of vCPU shares reserved for the instance.",
            "memory": "Memory of the instance, in a format like 5MB.",
            "disk": "Disk size of the instance, in a format like 5MB.",
            "gpu": "GPU details (count, brand, memory, name) for GPU instance types.",
            "price_per_second": "Price per second of running the instance.",
            "price_hourly": "Price per hour of running the instance.",
            "price_monthly": "Price per month of running the instance.",
            "regions": "Regions where the instance type is available.",
            "service_types": "Service types allowed on the instance type (e.g. web, worker).",
            "require_plan": "Plans required to use the instance type.",
            "aliases": "Alternative names for the instance type.",
            "volumes_enabled": "Whether volumes can be attached to the instance type.",
            "light_sleep_enabled": "Whether light sleep is available for the instance type.",
            "status": "Availability status of the instance type.",
        },
    },
    "catalog_regions": {
        "description": "Catalog of Koyeb regions with their location and the instance types available in each. Join on region to resolve the region codes on deployments, instances, and usage.",
        "docs_url": "https://developer.koyeb.com/public#tag/catalog-regions",
        "columns": {
            "id": "Code of the region (e.g. fra, was).",
            "name": "Name of the region.",
            "coordinates": "Latitude and longitude of the region.",
            "scope": "Scope of the region, such as continent or metropolitan area.",
            "status": "Availability status of the region.",
            "instances": "Instance types available in the region.",
            "datacenters": "Datacenters available in the region.",
            "volumes_enabled": "Whether volumes are available in the region.",
        },
    },
}
