import { MakeLogicType, actions, afterMount, connect, kea, listeners, path, reducers } from 'kea'
import { loaders } from 'kea-loaders'
import { subscriptions } from 'kea-subscriptions'

import { lemonToast } from '@posthog/lemon-ui'

import { dayjs } from 'lib/dayjs'
import { teamLogic } from 'scenes/teamLogic'

import { resolveSnoozeUntil } from 'products/alerts/frontend/utils'
import {
    tracingAlertsDestroy,
    tracingAlertsList,
    tracingAlertsPartialUpdate,
    tracingAlertsResetCreate,
} from 'products/tracing/frontend/generated/api'

import { PatchedTracingAlertConfigurationApi, TracingAlertConfigurationApi } from '../generated/api.schemas'

const ALERT_POLL_INTERVAL_MS = 30_000

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface tracingAlertingLogicValues {
    currentTeamId: number | null // teamLogic
    alerts: TracingAlertConfigurationApi[]
    alertsLoading: boolean
    createdByFilter: string | null
    editingAlert: TracingAlertConfigurationApi | null
    isCreateAlertModalOpen: boolean
    resettingAlertIds: Set<string>
    snoozingAlertIds: Set<string>
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface tracingAlertingLogicActions {
    closeCreateAlertModal: () => { value: true }
    closeEditAlertModal: () => { value: true }
    deleteAlert: (id: string, onSuccess?: () => void) => { id: string; onSuccess: (() => void) | undefined }
    loadAlerts: (_?: any) => any
    loadAlertsFailure: (error: string, errorObject?: any) => { error: string; errorObject?: any }
    loadAlertsSuccess: (
        alerts: TracingAlertConfigurationApi[],
        payload?: any
    ) => { alerts: TracingAlertConfigurationApi[]; payload?: any }
    openCreateAlertModal: () => { value: true }
    openEditAlertModal: (alert: TracingAlertConfigurationApi) => { alert: TracingAlertConfigurationApi }
    resetAlert: (id: string) => { id: string }
    setCreatedByFilter: (createdByFilter: string | null) => { createdByFilter: string | null }
    setResettingAlertId: (id: string, resetting: boolean) => { id: string; resetting: boolean }
    setSnoozingAlertId: (id: string, snoozing: boolean) => { id: string; snoozing: boolean }
    snoozeAlert: (alertId: string, durationMinutes: number) => { alertId: string; durationMinutes: number }
    snoozeAlertUntil: (alertId: string, snoozeUntil: string) => { alertId: string; snoozeUntil: string }
    toggleAlertEnabled: (alert: TracingAlertConfigurationApi) => { alert: TracingAlertConfigurationApi }
    unsnoozeAlert: (alertId: string) => { alertId: string }
    updateEditingAlert: (alert: TracingAlertConfigurationApi) => { alert: TracingAlertConfigurationApi }
}

export type tracingAlertingLogicType = MakeLogicType<tracingAlertingLogicValues, tracingAlertingLogicActions>

export const tracingAlertingLogic = kea<tracingAlertingLogicType>([
    path(['products', 'tracing', 'frontend', 'alerting', 'tracingAlertingLogic']),

    connect(() => ({
        values: [teamLogic, ['currentTeamId']],
    })),

    actions({
        setCreatedByFilter: (createdByFilter: string | null) => ({ createdByFilter }),
        deleteAlert: (id: string, onSuccess?: () => void) => ({ id, onSuccess }),
        toggleAlertEnabled: (alert: TracingAlertConfigurationApi) => ({ alert }),
        resetAlert: (id: string) => ({ id }),
        setResettingAlertId: (id: string, resetting: boolean) => ({ id, resetting }),
        setSnoozingAlertId: (id: string, snoozing: boolean) => ({ id, snoozing }),
        snoozeAlert: (alertId: string, durationMinutes: number) => ({ alertId, durationMinutes }),
        snoozeAlertUntil: (alertId: string, snoozeUntil: string) => ({ alertId, snoozeUntil }),
        unsnoozeAlert: (alertId: string) => ({ alertId }),
        openCreateAlertModal: true,
        closeCreateAlertModal: true,
        openEditAlertModal: (alert: TracingAlertConfigurationApi) => ({ alert }),
        closeEditAlertModal: true,
        updateEditingAlert: (alert: TracingAlertConfigurationApi) => ({ alert }),
    }),

    reducers({
        createdByFilter: [
            null as string | null,
            {
                setCreatedByFilter: (_, { createdByFilter }) => createdByFilter,
            },
        ],
        resettingAlertIds: [
            new Set<string>(),
            {
                setResettingAlertId: (state, { id, resetting }) =>
                    resetting ? new Set([...state, id]) : new Set([...state].filter((x) => x !== id)),
            },
        ],
        snoozingAlertIds: [
            new Set<string>(),
            {
                setSnoozingAlertId: (state, { id, snoozing }) =>
                    snoozing ? new Set([...state, id]) : new Set([...state].filter((x) => x !== id)),
            },
        ],
        isCreateAlertModalOpen: [
            false,
            {
                openCreateAlertModal: () => true,
                closeCreateAlertModal: () => false,
            },
        ],
        editingAlert: [
            null as TracingAlertConfigurationApi | null,
            {
                openEditAlertModal: (_, { alert }) => alert,
                closeEditAlertModal: () => null,
                updateEditingAlert: (editingAlert, { alert }) => (editingAlert?.id === alert.id ? alert : editingAlert),
            },
        ],
    }),

    loaders(({ values }) => ({
        alerts: [
            [] as TracingAlertConfigurationApi[],
            {
                loadAlerts: async (_ = null, breakpoint) => {
                    const projectId = String(values.currentTeamId)
                    const response = await tracingAlertsList(projectId, {
                        limit: 500,
                        ...(values.createdByFilter ? { created_by: values.createdByFilter } : {}),
                    })
                    breakpoint()
                    return response.results
                },
            },
        ],
    })),

    listeners(({ actions, values }) => {
        const updateSnooze = async (
            alertId: string,
            snoozeUntil: string | null,
            { successMessage, errorMessage }: { successMessage?: string; errorMessage: string }
        ): Promise<void> => {
            const projectId = String(values.currentTeamId)
            actions.setSnoozingAlertId(alertId, true)
            try {
                const updatedAlert = await tracingAlertsPartialUpdate(projectId, alertId, { snooze_until: snoozeUntil })
                actions.updateEditingAlert(updatedAlert)
                if (successMessage) {
                    lemonToast.success(successMessage)
                }
                actions.loadAlerts()
            } catch {
                lemonToast.error(errorMessage)
            } finally {
                actions.setSnoozingAlertId(alertId, false)
            }
        }

        return {
            setCreatedByFilter: () => actions.loadAlerts(),
            deleteAlert: async ({ id, onSuccess }) => {
                const projectId = String(values.currentTeamId)
                try {
                    await tracingAlertsDestroy(projectId, id)
                    lemonToast.success('Alert deleted')
                    actions.loadAlerts()
                    onSuccess?.()
                } catch {
                    lemonToast.error('Failed to delete alert')
                }
            },
            toggleAlertEnabled: async ({ alert }) => {
                const projectId = String(values.currentTeamId)
                const update: PatchedTracingAlertConfigurationApi = { enabled: !(alert.enabled ?? true) }
                if (!update.enabled) {
                    update.snooze_until = null
                }
                try {
                    const updatedAlert = await tracingAlertsPartialUpdate(projectId, alert.id, update)
                    actions.updateEditingAlert(updatedAlert)
                    actions.loadAlerts()
                } catch {
                    lemonToast.error('Failed to update alert')
                }
            },
            resetAlert: async ({ id }) => {
                const projectId = String(values.currentTeamId)
                actions.setResettingAlertId(id, true)
                try {
                    await tracingAlertsResetCreate(projectId, id)
                    lemonToast.success('Alert reset — next check will run shortly.')
                    actions.loadAlerts()
                } catch {
                    lemonToast.error('Failed to reset alert')
                } finally {
                    actions.setResettingAlertId(id, false)
                }
            },
            snoozeAlert: ({ alertId, durationMinutes }) =>
                updateSnooze(alertId, dayjs().add(durationMinutes, 'minute').toISOString(), {
                    successMessage: 'Alert snoozed',
                    errorMessage: 'Failed to snooze alert',
                }),
            snoozeAlertUntil: ({ alertId, snoozeUntil }) =>
                updateSnooze(alertId, resolveSnoozeUntil(snoozeUntil), { errorMessage: 'Failed to snooze alert' }),
            unsnoozeAlert: ({ alertId }) =>
                updateSnooze(alertId, null, {
                    successMessage: 'Alert unsnoozed',
                    errorMessage: 'Failed to unsnooze alert',
                }),
        }
    }),

    subscriptions(({ actions }) => ({
        currentTeamId: (currentTeamId, previousTeamId) => {
            if (previousTeamId !== null && currentTeamId !== previousTeamId) {
                actions.setCreatedByFilter(null)
            }
        },
    })),

    afterMount(({ actions, cache }) => {
        actions.loadAlerts()
        cache.disposables.add(() => {
            const intervalId = window.setInterval(() => {
                actions.loadAlerts()
            }, ALERT_POLL_INTERVAL_MS)
            return () => clearInterval(intervalId)
        }, 'pollAlerts')
    }),
])
