from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "projects": {
        "description": "A Railway project — the top-level container that groups services, environments, deployments, and volumes.",
        "docs_url": "https://docs.railway.com/reference/projects",
        "columns": {
            "id": "Unique identifier for the project.",
            "name": "Display name of the project.",
            "description": "User-provided description of the project.",
            "isPublic": "Whether the project is publicly visible.",
            "isTempProject": "Whether the project is a temporary project.",
            "prDeploys": "Whether pull-request environments deploy automatically for this project.",
            "botPrEnvironments": "Whether pull requests opened by bots create PR environments.",
            "workspaceId": "Identifier of the workspace the project belongs to.",
            "baseEnvironmentId": "Identifier of the environment new environments fork from.",
            "primaryEnvironmentId": "Identifier of the project's primary environment.",
            "createdAt": "When the project was created.",
            "updatedAt": "When the project was last updated.",
            "deletedAt": "When the project was deleted, if it has been.",
        },
    },
    "services": {
        "description": "A service within a Railway project — a deployable unit such as an app, database, or worker.",
        "docs_url": "https://docs.railway.com/reference/services",
        "columns": {
            "id": "Unique identifier for the service.",
            "name": "Display name of the service.",
            "icon": "Icon shown for the service in the Railway dashboard.",
            "projectId": "Identifier of the project the service belongs to.",
            "templateId": "Identifier of the template the service was created from, if any.",
            "templateServiceId": "Identifier of the source service within the template, if any.",
            "createdAt": "When the service was created.",
            "updatedAt": "When the service was last updated.",
            "deletedAt": "When the service was deleted, if it has been.",
        },
    },
    "environments": {
        "description": "An environment within a Railway project (e.g. production, staging, or an ephemeral PR environment).",
        "docs_url": "https://docs.railway.com/reference/environments",
        "columns": {
            "id": "Unique identifier for the environment.",
            "name": "Display name of the environment.",
            "projectId": "Identifier of the project the environment belongs to.",
            "isEphemeral": "Whether the environment is ephemeral (e.g. created for a pull request).",
            "unmergedChangesCount": "Number of staged changes not yet merged into the environment.",
            "createdAt": "When the environment was created.",
            "updatedAt": "When the environment was last updated.",
            "deletedAt": "When the environment was deleted, if it has been.",
        },
    },
    "deployments": {
        "description": "A deployment of a Railway service — one build/deploy attempt with its status and timestamps.",
        "docs_url": "https://docs.railway.com/reference/deployments",
        "columns": {
            "id": "Unique identifier for the deployment.",
            "status": "Current status of the deployment (e.g. BUILDING, DEPLOYING, SUCCESS, FAILED, CRASHED, REMOVED).",
            "statusUpdatedAt": "When the deployment's status last changed.",
            "projectId": "Identifier of the project the deployment belongs to.",
            "environmentId": "Identifier of the environment the deployment ran in.",
            "serviceId": "Identifier of the service that was deployed.",
            "snapshotId": "Identifier of the code/config snapshot the deployment was built from.",
            "staticUrl": "Stable URL assigned to the deployment, if any.",
            "url": "Public URL serving the deployment, if any.",
            "meta": "Deployment metadata such as the git branch, commit hash, and commit message.",
            "deploymentStopped": "Whether the deployment has been stopped.",
            "creator": "The user who triggered the deployment (id, name, email).",
            "createdAt": "When the deployment was created.",
            "updatedAt": "When the deployment was last updated.",
        },
    },
    "project_members": {
        "description": "A member of a Railway project and their role.",
        "docs_url": "https://docs.railway.com/reference/teams",
        "columns": {
            "project_id": "Identifier of the project the membership belongs to.",
            "id": "Unique identifier of the member (their Railway user id).",
            "name": "Display name of the member.",
            "email": "Email address of the member.",
            "avatar": "Avatar URL of the member.",
            "role": "The member's role in the project (ADMIN, MEMBER, or VIEWER).",
        },
    },
    "volumes": {
        "description": "A persistent storage volume attached to a Railway project.",
        "docs_url": "https://docs.railway.com/reference/volumes",
        "columns": {
            "id": "Unique identifier for the volume.",
            "name": "Display name of the volume.",
            "projectId": "Identifier of the project the volume belongs to.",
            "createdAt": "When the volume was created.",
        },
    },
}
