from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Sourced from the official CoinMarketCap API docs (https://coinmarketcap.com/api/documentation/v1/).
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "cryptocurrency_map": {
        "description": "Mapping of all cryptocurrencies tracked by CoinMarketCap to their CoinMarketCap ID.",
        "docs_url": "https://coinmarketcap.com/api/documentation/v1/#operation/getV1CryptocurrencyMap",
        "columns": {
            "id": "The unique CoinMarketCap ID for this cryptocurrency.",
            "name": "The name of this cryptocurrency.",
            "symbol": "The ticker symbol for this cryptocurrency.",
            "slug": "The web URL friendly shorthand version of this cryptocurrency name.",
            "rank": "The rank of this cryptocurrency by market capitalization.",
            "is_active": "1 if this cryptocurrency has at least one active market currently being tracked, otherwise 0.",
            "first_historical_data": "Timestamp (ISO 8601) of the earliest market data record available for this cryptocurrency.",
            "last_historical_data": "Timestamp (ISO 8601) of the latest market data record available for this cryptocurrency.",
            "platform": "Metadata about the parent cryptocurrency platform this is a token on, if any.",
        },
    },
    "listings_latest": {
        "description": "Latest market data (price, market cap, volume, supply) for all active cryptocurrencies, ranked.",
        "docs_url": "https://coinmarketcap.com/api/documentation/v1/#operation/getV1CryptocurrencyListingsLatest",
        "columns": {
            "id": "The unique CoinMarketCap ID for this cryptocurrency.",
            "name": "The name of this cryptocurrency.",
            "symbol": "The ticker symbol for this cryptocurrency.",
            "slug": "The web URL friendly shorthand version of this cryptocurrency name.",
            "cmc_rank": "The cryptocurrency's CoinMarketCap rank by market cap.",
            "num_market_pairs": "The number of active trading pairs available for this cryptocurrency across exchanges.",
            "circulating_supply": "The approximate number of coins circulating in the market.",
            "total_supply": "The approximate total amount of coins in existence right now (minus any coins verifiably burned).",
            "max_supply": "The expected maximum limit of coins ever to be available for this cryptocurrency.",
            "date_added": "Timestamp (ISO 8601) of when this cryptocurrency was added to CoinMarketCap.",
            "tags": "Tags associated with this cryptocurrency.",
            "platform": "Metadata about the parent cryptocurrency platform this is a token on, if any.",
            "last_updated": "Timestamp (ISO 8601) of when the market data for this cryptocurrency was last updated.",
            "quote": "Market quote in each currency conversion requested (e.g. USD): price, volume, market cap, and percent changes.",
        },
    },
    "categories": {
        "description": "All cryptocurrency categories (e.g. DeFi, NFTs) with aggregate market data.",
        "docs_url": "https://coinmarketcap.com/api/documentation/v1/#operation/getV1CryptocurrencyCategories",
        "columns": {
            "id": "The unique ID of this cryptocurrency category.",
            "name": "The name of this cryptocurrency category.",
            "title": "The title of this cryptocurrency category.",
            "description": "The description of this cryptocurrency category.",
            "num_tokens": "The number of tokens in this cryptocurrency category.",
            "avg_price_change": "The average price change of all tokens in this category over 24 hours.",
            "market_cap": "The market cap of all tokens within this category.",
            "market_cap_change": "The market cap change of all tokens in this category over 24 hours.",
            "volume": "The 24 hour trading volume of all tokens within this category.",
            "volume_change": "The 24 hour trading volume change of all tokens in this category.",
            "last_updated": "Timestamp (ISO 8601) of when this category was last updated.",
        },
    },
    "fiat_map": {
        "description": "All fiat currencies supported by CoinMarketCap for quote conversions.",
        "docs_url": "https://coinmarketcap.com/api/documentation/v1/#operation/getV1FiatMap",
        "columns": {
            "id": "The unique CoinMarketCap ID for this fiat currency.",
            "name": "The name of this fiat currency.",
            "sign": "The currency sign for this fiat currency.",
            "symbol": "The ticker symbol for this fiat currency.",
        },
    },
    "exchange_map": {
        "description": "Mapping of all exchanges tracked by CoinMarketCap to their CoinMarketCap exchange ID.",
        "docs_url": "https://coinmarketcap.com/api/documentation/v1/#operation/getV1ExchangeMap",
        "columns": {
            "id": "The unique CoinMarketCap ID for this exchange.",
            "name": "The name of this exchange.",
            "slug": "The web URL friendly shorthand version of this exchange name.",
            "is_active": "1 if this exchange is still being actively tracked and updated, otherwise 0.",
            "is_listed": "1 if this exchange is listed (ranked) by CoinMarketCap, otherwise 0.",
            "is_redistributable": "1 if this exchange's data is available for redistribution per CoinMarketCap licensing, otherwise 0.",
            "first_historical_data": "Timestamp (ISO 8601) of the earliest market data record available for this exchange.",
            "last_historical_data": "Timestamp (ISO 8601) of the latest market data record available for this exchange.",
        },
    },
    "exchange_listings_latest": {
        "description": "Latest aggregate market data per exchange: traded volume, liquidity, ranking and market pair count.",
        "docs_url": "https://pro.coinmarketcap.com/api/documentation/pro-api-reference/exchange/listings-latest-2.md",
        "columns": {
            "id": "The unique CoinMarketCap ID for this exchange.",
            "name": "The name of this exchange.",
            "slug": "The web URL friendly shorthand version of this exchange name.",
            "num_market_pairs": "The number of trading pairs actively tracked on this exchange.",
            "date_launched": "Timestamp (ISO 8601) of the date this exchange launched.",
            "exchange_score": "The exchange score. Deprecated by CoinMarketCap on 4 November 2024 and now always null.",
            "liquidity_score": "The liquidity score.",
            "rank": "The exchange rank.",
            "traffic_score": "The traffic score.",
            "last_updated": "Timestamp (ISO 8601) of the last time this record was updated.",
            "quote": "Market quote by currency conversion (default USD): volume_24h, volume_24h_adjusted, volume_7d, volume_30d, the matching percent changes, effective_liquidity_24h, derivative_volume, open_interest and spot_volume_usd.",
        },
    },
    "exchange_info": {
        "description": "Static metadata for each exchange: launch date, logo, description and resource URLs.",
        "docs_url": "https://pro.coinmarketcap.com/api/documentation/pro-api-reference/exchange/metadata-2.md",
        "columns": {
            "id": "The unique CoinMarketCap ID for this exchange.",
            "name": "The name of this exchange.",
            "slug": "The web URL friendly shorthand version of this exchange name.",
            "logo": "Link to a CoinMarketCap hosted logo png for this exchange.",
            "description": "A CoinMarketCap supplied brief description of this exchange.",
            "date_launched": "Timestamp (ISO 8601) of the launch date for this exchange.",
            "notice": "A Markdown formatted message outlining a condition affecting the availability of this exchange's market data, otherwise null.",
            "weekly_visits": "The number of weekly visitors.",
            "spot_volume_usd": "Reported all time spot volume in USD.",
            "urls": "Resource URLs for this exchange: website, blog, chat, fee and twitter.",
        },
    },
    "exchange_quotes_historical": {
        "description": "Historical daily traded volume for the highest-volume exchanges. One row per exchange per interval.",
        "docs_url": "https://pro.coinmarketcap.com/api/documentation/pro-api-reference/exchange/quotes-historical-2.md",
        "columns": {
            "id": "The CoinMarketCap exchange ID this quote belongs to.",
            "name": "The exchange name.",
            "slug": "The exchange slug.",
            "timestamp": "Timestamp (ISO 8601) of when this historical quote was recorded.",
            "num_market_pairs": "Number of market pairs available at this historical interval.",
            "quote": "Market details for this interval by currency conversion (default USD): volume_24h and the conversion timestamp.",
        },
    },
    "listings_historical": {
        "description": "Daily ranked snapshot of the market, taken at the end of each UTC day. One row per cryptocurrency per day, covering the top of the CoinMarketCap ranking.",
        "docs_url": "https://pro.coinmarketcap.com/api/documentation/pro-api-reference/cryptocurrency/listings-historical.md",
        "columns": {
            "snapshot_date": "The UTC day this snapshot was requested for. Added by PostHog, because the response identifies the day only through last_updated.",
            "id": "The unique CoinMarketCap ID for this cryptocurrency.",
            "name": "The name of this cryptocurrency.",
            "symbol": "The ticker symbol for this cryptocurrency.",
            "slug": "The web URL friendly shorthand version of this cryptocurrency name.",
            "cmc_rank": "The cryptocurrency's CoinMarketCap rank at the end of this UTC day.",
            "num_market_pairs": "The number of active trading pairs available for this cryptocurrency across supported exchanges.",
            "circulating_supply": "The approximate number of coins circulating at the end of this UTC day.",
            "total_supply": "The approximate total amount of coins in existence at the end of this UTC day (minus any coins verifiably burned).",
            "max_supply": "The expected maximum limit of coins ever to be available for this cryptocurrency.",
            "last_updated": "Timestamp (ISO 8601) of the last market data update available during this UTC day.",
            "date_added": "Timestamp (ISO 8601) of when this cryptocurrency was added to CoinMarketCap.",
            "tags": "Tags associated with this cryptocurrency.",
            "platform": "Metadata about the parent cryptocurrency platform this is a token on, if any.",
            "quote": "Market quote by currency conversion (default USD) at the end of this UTC day: price, volume_24h, market_cap, the percent changes and the conversion timestamp.",
        },
    },
    "cryptocurrency_info": {
        "description": "Static metadata for each cryptocurrency: category, tags, platform, description and resource URLs.",
        "docs_url": "https://pro.coinmarketcap.com/api/documentation/pro-api-reference/cryptocurrency/metadata.md",
        "columns": {
            "id": "The unique CoinMarketCap ID for this cryptocurrency.",
            "name": "The name of this cryptocurrency.",
            "symbol": "The ticker symbol for this cryptocurrency.",
            "category": "The category for this cryptocurrency: coin or token.",
            "slug": "The web URL friendly shorthand version of this cryptocurrency name.",
            "logo": "Link to a CoinMarketCap hosted logo png for this cryptocurrency.",
            "description": "A CoinMarketCap supplied brief description of this cryptocurrency.",
            "date_added": "Timestamp (ISO 8601) of when this cryptocurrency was added to CoinMarketCap.",
            "date_launched": "Timestamp (ISO 8601) of when this cryptocurrency was launched.",
            "notice": "A Markdown formatted notice highlighting a significant event or condition affecting this cryptocurrency, otherwise null.",
            "tags": "Tags associated with this cryptocurrency.",
            "platform": "Metadata about the parent cryptocurrency platform this is a token on, if any.",
            "self_reported_circulating_supply": "The self reported number of coins circulating for this cryptocurrency.",
            "self_reported_market_cap": "The self reported market cap for this cryptocurrency.",
            "self_reported_tags": "Self reported tags associated with this cryptocurrency.",
            "infinite_supply": "True if this cryptocurrency is known to have an infinite supply.",
            "urls": "Resource URLs for this cryptocurrency: website, technical doc, explorer, source code, message board, chat, announcement, reddit and twitter.",
        },
    },
    "quotes_historical": {
        "description": "Historical daily price, 24 hour volume and market cap for the highest-ranked cryptocurrencies by market cap. One row per cryptocurrency per interval.",
        "docs_url": "https://pro.coinmarketcap.com/api/documentation/pro-api-reference/cryptocurrency/quotes-historical.md",
        "columns": {
            "id": "The CoinMarketCap cryptocurrency ID this quote belongs to.",
            "name": "The cryptocurrency name.",
            "symbol": "The cryptocurrency symbol.",
            "is_active": "1 if this cryptocurrency has at least one active market currently being tracked, otherwise 0.",
            "is_fiat": "1 if this is a fiat currency, otherwise 0.",
            "timestamp": "Timestamp (ISO 8601) of when this historical quote was recorded.",
            "search_interval": "The interval timestamp for the search period that this historical quote was located against.",
            "quote": "Market details for this interval by currency conversion (default USD): price, volume_24hr, market_cap, circulating_supply, total_supply and the conversion timestamp.",
        },
    },
    "ohlcv_historical": {
        "description": "Historical daily OHLCV (open, high, low, close, volume) candles and market cap for the highest-ranked cryptocurrencies by market cap. One row per cryptocurrency per interval.",
        "docs_url": "https://pro.coinmarketcap.com/api/documentation/pro-api-reference/cryptocurrency/ohlcv-historical.md",
        "columns": {
            "id": "The CoinMarketCap cryptocurrency ID this candle belongs to.",
            "name": "The cryptocurrency name.",
            "symbol": "The cryptocurrency symbol.",
            "time_open": "Timestamp (ISO 8601) of the start of this time series interval.",
            "time_close": "Timestamp (ISO 8601) of the end of this time series interval.",
            "time_high": "Timestamp (ISO 8601) of the high of this time series interval.",
            "time_low": "Timestamp (ISO 8601) of the low of this time series interval.",
            "quote": "Market quote by currency conversion (default USD): open, high, low, close, volume, market_cap and the conversion timestamp.",
        },
    },
    "global_metrics_quotes_historical": {
        "description": "Historical aggregate market metrics across all cryptocurrencies: total market cap, BTC and ETH dominance, and altcoin market cap. One row per interval.",
        "docs_url": "https://pro.coinmarketcap.com/api/documentation/pro-api-reference/global-metrics/quotes-historical-3.md",
        "columns": {
            "timestamp": "Timestamp (ISO 8601) of when this historical quote was recorded.",
            "search_interval": "The interval timestamp for the search period that this historical quote was located against.",
            "btc_dominance": "Percent of BTC market dominance by market cap at this interval.",
            "eth_dominance": "Percent of ETH market dominance by market cap at this interval.",
            "active_cryptocurrencies": "Number of active cryptocurrencies tracked by CoinMarketCap at this point in time. Null before 2019-05-10.",
            "active_exchanges": "Number of active exchanges tracked by CoinMarketCap at this point in time. Null before 2019-06-18.",
            "active_market_pairs": "Number of active market pairs tracked across all exchanges at this point in time. Null before 2019-05-10.",
            "quote": "Aggregate market data by currency conversion (default USD): total_market_cap, total_volume_24h, total_volume_24h_reported, altcoin_market_cap, altcoin_volume_24h, altcoin_volume_24h_reported and the conversion timestamp.",
        },
    },
}
