from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "applications": {
        "description": "Argo CD applications with their sync state, health, and full desired/live specification.",
        "docs_url": "https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#applications",
        "columns": {
            "name": "Name of the application.",
            "namespace": "Kubernetes namespace the Application resource lives in (usually the Argo CD control-plane namespace).",
            "uid": "Kubernetes UID of the Application resource; changes if the application is deleted and recreated.",
            "created_at": "Timestamp the Application resource was created.",
            "project": "Argo CD project the application belongs to.",
            "sync_status": "Whether the live state matches the desired Git state (Synced, OutOfSync, or Unknown).",
            "health_status": "Aggregated health of the application's resources (Healthy, Progressing, Degraded, Suspended, Missing, or Unknown).",
            "metadata": "Full Kubernetes object metadata (labels, annotations, finalizers).",
            "spec": "Desired application state: source repository, target revision, destination cluster/namespace, and sync policy.",
            "status": "Observed application state: resources, conditions, sync/health details, and deployment history.",
            "operation": "Currently requested sync operation, if one is in flight.",
        },
    },
    "deployment_history": {
        "description": "One row per recorded deployment, flattened from each application's status.history. Useful for DORA metrics such as deployment frequency.",
        "docs_url": "https://argo-cd.readthedocs.io/en/stable/user-guide/commands/argocd_app_history/",
        "columns": {
            "application_name": "Name of the application that was deployed.",
            "application_namespace": "Namespace of the Application resource.",
            "application_uid": "Kubernetes UID of the Application resource.",
            "project": "Argo CD project the application belongs to.",
            "id": "History entry id, incremented per application on each deployment.",
            "revision": "Git revision (commit SHA) that was deployed.",
            "revisions": "Git revisions deployed, for applications with multiple sources.",
            "deployed_at": "Timestamp the deployment finished.",
            "deploy_started_at": "Timestamp the deployment started.",
            "source": "Application source (repository URL, path, target revision) at deployment time.",
            "sources": "Application sources at deployment time, for applications with multiple sources.",
            "initiated_by": "Who or what triggered the deployment (user or automated sync).",
        },
    },
    "projects": {
        "description": "Argo CD projects (AppProject resources), which group applications and restrict their sources and destinations.",
        "docs_url": "https://argo-cd.readthedocs.io/en/stable/user-guide/projects/",
        "columns": {
            "name": "Name of the project.",
            "uid": "Kubernetes UID of the AppProject resource.",
            "created_at": "Timestamp the project was created.",
            "metadata": "Full Kubernetes object metadata (labels, annotations).",
            "spec": "Project configuration: allowed source repositories, destinations, cluster resource whitelists, and roles.",
            "status": "Observed project state, e.g. jwt token metadata per role.",
        },
    },
    "repositories": {
        "description": "Git and Helm repositories connected to Argo CD. Credential fields are never synced.",
        "docs_url": "https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/",
        "columns": {
            "repo": "Repository URL.",
            "name": "Display name of the repository.",
            "project": "Argo CD project the repository is scoped to, if any.",
            "type": "Repository type (git or helm).",
            "connectionState": "Result of Argo CD's most recent connectivity check for the repository.",
        },
    },
    "clusters": {
        "description": "Kubernetes clusters Argo CD deploys to. Connection credentials are never synced.",
        "docs_url": "https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#clusters",
        "columns": {
            "server": "Kubernetes API server URL of the cluster.",
            "name": "Display name of the cluster.",
            "namespaces": "Namespaces Argo CD is allowed to manage in the cluster.",
            "connectionState": "Result of Argo CD's most recent connectivity check for the cluster.",
            "serverVersion": "Kubernetes version of the cluster.",
            "info": "Cluster statistics such as application count and cache state.",
        },
    },
    "application_events": {
        "description": "Kubernetes events recorded against each Application resource, one row per event. This is the sync and health transition history behind each deployment. Argo CD stores these in Kubernetes, which expires them after about an hour, so the table only holds events seen by a sync.",
        "docs_url": "https://argo-cd.readthedocs.io/en/stable/user-guide/commands/argocd_app/",
        "columns": {
            "application_name": "Name of the application the event was recorded against.",
            "application_namespace": "Namespace of the Application resource.",
            "application_uid": "Kubernetes UID of the Application resource.",
            "project": "Argo CD project the application belongs to.",
            "uid": "Kubernetes UID of the event.",
            "created_at": "Timestamp the event was recorded.",
            "reason": "Short machine-readable reason, for example ResourceUpdated or OperationCompleted.",
            "message": "Human-readable description of what happened.",
            "type": "Event level (Normal or Warning).",
            "action": "Action taken on the application, when the reporting component sets one.",
            "count": "Number of times this event has repeated.",
            "first_timestamp": "Timestamp the event first occurred.",
            "last_timestamp": "Timestamp the event last occurred.",
            "event_time": "Timestamp the event occurred, for components using the newer events API.",
            "involved_object_kind": "Kind of the object the event is about (Application).",
            "involved_object_name": "Name of the object the event is about.",
            "involved_object_namespace": "Namespace of the object the event is about.",
            "involved_object_uid": "Kubernetes UID of the object the event is about.",
            "reporting_component": "Component that reported the event.",
            "reporting_instance": "Instance of the component that reported the event.",
            "source": "Component and host that generated the event.",
            "series": "Count and last-observed time when the event repeats as a series.",
            "metadata": "Full Kubernetes object metadata of the event.",
        },
    },
    "revision_metadata": {
        "description": "Git commit metadata for each revision an application deployed, resolved from the repository. Join it to deployment_history on revision to get the author, message, and commit date behind a deployment. Helm chart revisions are not included.",
        "docs_url": "https://argo-cd.readthedocs.io/en/stable/user-guide/commands/argocd_app_get/",
        "columns": {
            "application_name": "Name of the application that deployed the revision.",
            "application_namespace": "Namespace of the Application resource.",
            "application_uid": "Kubernetes UID of the Application resource.",
            "project": "Argo CD project the application belongs to.",
            "revision": "Git revision (commit SHA) the metadata describes.",
            "source_index": "Index of the application source the revision belongs to; 0 for single-source applications.",
            "author": "Who authored the commit, typically a name and email address.",
            "date": "Timestamp of the commit.",
            "message": "Commit message.",
            "tags": "Git tags currently pointing at the revision.",
            "references": "Related references for the commit, such as the pull request it came from.",
            "signature_info": "Hint about the GPG signer, when signature verification is enabled.",
            "source_integrity_result": "Result of Argo CD's source integrity check for the revision.",
        },
    },
    "managed_resources": {
        "description": "Every Kubernetes resource an application owns, with its live and target state, so you can measure configuration drift. Argo CD masks the values inside Secret resources, but any other manifest is synced as the API returns it.",
        "docs_url": "https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/",
        "columns": {
            "application_name": "Name of the application that manages the resource.",
            "application_namespace": "Namespace of the Application resource.",
            "application_uid": "Kubernetes UID of the Application resource.",
            "project": "Argo CD project the application belongs to.",
            "group": "Kubernetes API group of the resource; empty for core resources.",
            "kind": "Kubernetes kind of the resource, for example Deployment or Service.",
            "namespace": "Namespace the resource lives in; empty for cluster-scoped resources.",
            "name": "Name of the resource.",
            "modified": "Whether the live resource differs from the target state in Git.",
            "hook": "Whether the resource is a sync hook.",
            "resource_version": "Kubernetes resource version of the live resource.",
            "diff": "JSON patch between the live and target state. Argo CD deprecated this in favor of normalized_live_state and predicted_live_state.",
            "live_state": "JSON manifest of the resource as it currently runs in the cluster.",
            "target_state": "JSON manifest of the resource as defined in Git or Helm.",
            "normalized_live_state": "Live manifest after Argo CD's normalizations, such as ignoring defaulted fields.",
            "predicted_live_state": "Manifest Argo CD predicts the cluster would hold after applying the target state.",
        },
    },
    "resource_tree": {
        "description": "Live Kubernetes resources in each application's tree, one row per resource, with its own health status. Use it to find which resource makes an application unhealthy.",
        "docs_url": "https://argo-cd.readthedocs.io/en/stable/operator-manual/health/",
        "columns": {
            "application_name": "Name of the application the resource belongs to.",
            "application_namespace": "Namespace of the Application resource.",
            "application_uid": "Kubernetes UID of the Application resource.",
            "project": "Argo CD project the application belongs to.",
            "group": "Kubernetes API group of the resource; empty for core resources.",
            "kind": "Kubernetes kind of the resource, for example Pod or ReplicaSet.",
            "namespace": "Namespace the resource lives in; empty for cluster-scoped resources.",
            "name": "Name of the resource.",
            "uid": "Kubernetes UID of the live resource.",
            "version": "Kubernetes API version of the resource.",
            "orphaned": "Whether the resource sits in the application's namespace without being managed by it.",
            "created_at": "Timestamp the live resource was created.",
            "health_status": "Health of this resource (Healthy, Progressing, Degraded, Suspended, Missing, or Unknown).",
            "health_message": "Explanation of the resource's health, when Argo CD reports one.",
            "resource_version": "Kubernetes resource version of the live resource.",
            "images": "Container images the resource runs, for workload resources.",
            "info": "Extra details Argo CD surfaces about the resource, such as revision or route.",
            "parent_refs": "Resources that own this one, giving the tree its hierarchy.",
            "networking_info": "Networking details for the resource, such as ingress hosts and labels.",
        },
    },
}
