import { MakeLogicType, connect, kea, path, selectors } from 'kea'

import { FeatureFlagsSet, featureFlagLogic } from 'lib/logic/featureFlagLogic'
import { getProductAccessDisabledReason } from 'lib/utils/accessControlUtils'

import { panelLayoutLogic } from '~/layout/panel-layout/panelLayoutLogic'
import { customProductsLogic } from '~/layout/panel-layout/ProjectTree/customProductsLogic'
import { getDefaultTreeProducts } from '~/layout/panel-layout/ProjectTree/defaultTree'
import { getCategoryOrder, splitPath, unescapePath } from '~/layout/panel-layout/ProjectTree/utils'
import { FileSystemIconType, UserProductListItem } from '~/queries/schema/schema-general'
import { FileSystemIconColor } from '~/types'

import { findActiveProductPath } from './findActiveProductPath'

export interface FlatNavProductItem {
    path: string
    label: string
    href: string
    type?: string
    iconType?: FileSystemIconType
    iconColor?: FileSystemIconColor
    tag?: 'alpha' | 'beta'
    pinned: boolean
}

export interface FlatNavProductGroup {
    category: string
    items: FlatNavProductItem[]
}

const UNCATEGORIZED_ORDER = 9999
const UNORDERED_VISUAL_ORDER = 9999

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface flatNavLogicValues {
    customProducts: UserProductListItem[] // customProductsLogic
    customProductsLoading: boolean // customProductsLogic
    featureFlags: FeatureFlagsSet // featureFlagLogic
    pathname: string // panelLayoutLogic
    activeProductPath: string | null
    productGroups: FlatNavProductGroup[]
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface flatNavLogicMeta {
    __keaTypeGenInternalSelectorTypes: {
        activeProductPath: (pathname: string) => string | null
        productGroups: (
            customProducts: UserProductListItem[],
            featureFlags: FeatureFlagsSet,
            activeProductPath: string | null
        ) => FlatNavProductGroup[]
    }
}

export type flatNavLogicType = MakeLogicType<flatNavLogicValues, {}, Record<string, any>, flatNavLogicMeta>

export const flatNavLogic = kea<flatNavLogicType>([
    path(['layout', 'panel-layout', 'navbar', 'tabs', 'flat-nav', 'flatNavLogic']),
    connect(() => ({
        values: [
            customProductsLogic,
            ['customProducts', 'customProductsLoading'],
            featureFlagLogic,
            ['featureFlags'],
            panelLayoutLogic,
            ['pathname'],
        ],
    })),
    selectors({
        activeProductPath: [
            (s) => [s.pathname],
            (pathname: string): string | null => findActiveProductPath(pathname, getDefaultTreeProducts()),
        ],
        productGroups: [
            (s) => [s.customProducts, s.featureFlags, s.activeProductPath],
            (
                customProducts: UserProductListItem[],
                featureFlags: FeatureFlagsSet,
                activeProductPath: string | null
            ): FlatNavProductGroup[] => {
                const catalog = new Map(getDefaultTreeProducts().map((product) => [product.path, product]))
                const seenPaths = new Set<string>()
                const selected: (FlatNavProductItem & { category: string; sortOrder: number })[] = []
                const candidates = [
                    ...customProducts.map(({ product_path: productPath }) => ({ productPath, pinned: true })),
                    ...(activeProductPath ? [{ productPath: activeProductPath, pinned: false }] : []),
                ]
                for (const { productPath, pinned } of candidates) {
                    if (seenPaths.has(productPath)) {
                        continue
                    }
                    seenPaths.add(productPath)
                    const product = catalog.get(productPath)
                    if (
                        !product?.href ||
                        (product.flag && !(featureFlags as Record<string, boolean | string>)[product.flag]) ||
                        // Tools the user has no access to are hidden instead of shown disabled
                        getProductAccessDisabledReason(product)
                    ) {
                        continue
                    }
                    selected.push({
                        path: product.path,
                        label: product.displayLabel || unescapePath(splitPath(product.path).pop() ?? product.path),
                        href: product.href,
                        type: product.type,
                        iconType: product.iconType ?? (product.type as FileSystemIconType | undefined),
                        iconColor: product.iconColor,
                        tag: product.tags?.[0],
                        pinned,
                        category: product.category ?? '',
                        sortOrder: product.visualOrder ?? UNORDERED_VISUAL_ORDER,
                    })
                }
                selected.sort(
                    (a, b) =>
                        (a.category ? getCategoryOrder(a.category) : UNCATEGORIZED_ORDER) -
                            (b.category ? getCategoryOrder(b.category) : UNCATEGORIZED_ORDER) ||
                        a.category.localeCompare(b.category, undefined, { sensitivity: 'accent' }) ||
                        a.sortOrder - b.sortOrder ||
                        a.label.localeCompare(b.label, undefined, { sensitivity: 'accent' })
                )

                const groups: FlatNavProductGroup[] = []
                for (const { category, sortOrder: _, ...item } of selected) {
                    const lastGroup = groups[groups.length - 1]
                    if (lastGroup && lastGroup.category === category) {
                        lastGroup.items.push(item)
                    } else {
                        groups.push({ category, items: [item] })
                    }
                }

                return groups
            },
        ],
    }),
])
