from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

_DOCS_URL = "https://customapi.goldcast.io/swagger-ui/"

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "organizations": {
        "description": "The Goldcast organization (workspace) that owns the events, including its branding, plan, and integration settings.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Unique identifier for the organization.",
            "name": "Display name of the organization.",
            "short_name": "Short slug used in URLs and vanity domains.",
            "tier": "Subscription tier of the organization.",
            "created_at": "Timestamp when the organization was created.",
            "updated_at": "Timestamp when the organization was last updated.",
            "contract_start_date": "Start date of the organization's contract.",
            "contract_end_date": "End date of the organization's contract.",
            "is_webhook_enabled": "Whether webhooks are enabled for the organization.",
            "hubspot_portal_id": "Connected HubSpot portal id, if the HubSpot integration is set up.",
        },
    },
    "events": {
        "description": "A Goldcast event — the base object of the platform. An event is a virtual or hybrid gathering that can contain sessions, agenda items, tracks, and members.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Unique identifier for the event.",
            "title": "Title of the event.",
            "description": "Description of the event.",
            "timezone": "Timezone the event is scheduled in.",
            "start_time": "Scheduled start time of the event.",
            "end_time": "Scheduled end time of the event.",
            "registrant_count": "Number of people registered for the event.",
            "is_single_session": "Whether the event has a single session (vs multiple sessions).",
            "created_by_user": "The user who created the event.",
            "created_at": "Timestamp when the event was created.",
            "updated_at": "Timestamp when the event was last updated.",
            "deleted": "Whether the event has been deleted.",
        },
    },
    "agenda_items": {
        "description": "Agenda items scheduled within events — the individual slots that make up an event's programme.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Unique identifier for the agenda item.",
            "event": "Id of the event this agenda item belongs to.",
            "title": "Title of the agenda item.",
            "description": "Description of the agenda item.",
            "kind": "Type of agenda item.",
            "start_time": "Scheduled start time of the agenda item.",
            "end_time": "Scheduled end time of the agenda item.",
            "is_live": "Whether the agenda item is currently live.",
            "live_start_time": "Actual time the agenda item went live.",
            "live_end_time": "Actual time the agenda item ended.",
        },
    },
    "discussion_groups": {
        "description": "Discussion groups (breakout rooms and booths) within events, where attendees gather for smaller conversations.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Unique identifier for the discussion group.",
            "event": "Id of the event this discussion group belongs to.",
            "title": "Title of the discussion group.",
            "description": "Description of the discussion group.",
            "capacity": "Maximum number of participants allowed.",
            "is_live": "Whether the discussion group is currently live.",
            "is_booth": "Whether this discussion group is a booth.",
            "is_breakout": "Whether this discussion group is a breakout room.",
            "starts_at": "Scheduled start time of the discussion group.",
            "ends_at": "Scheduled end time of the discussion group.",
            "created_at": "Timestamp when the discussion group was created.",
            "updated_at": "Timestamp when the discussion group was last updated.",
        },
    },
    "tracks": {
        "description": "Tracks group related agenda items within an event, letting attendees follow a themed strand of sessions.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Unique identifier for the track.",
            "event": "Id of the event this track belongs to.",
            "title": "Title of the track.",
            "agenda_items": "Agenda items associated with this track.",
            "allowed_ticket_types": "Ticket types allowed to access this track.",
            "sort_priority": "Ordering priority of the track.",
            "custom": "Whether this is a custom track.",
            "created_at": "Timestamp when the track was created.",
            "updated_at": "Timestamp when the track was last updated.",
        },
    },
    "webinars": {
        "description": "Webinar configuration and schedule for each event. Fetched per event, so `event` identifies the parent event.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Unique identifier for the webinar.",
            "event": "Id of the parent event (injected during sync to make the row unique table-wide).",
            "title": "Title of the webinar.",
            "description": "Description of the webinar.",
            "timezone": "Timezone the webinar is scheduled in.",
            "schedule": "Scheduling details for the webinar.",
            "registrant_count": "Number of people registered for the webinar.",
            "created_at": "Timestamp when the webinar was created.",
            "updated_at": "Timestamp when the webinar was last updated.",
        },
    },
    "event_members": {
        "description": "People associated with an event — registrants and attendees — including their attendance, engagement, and marketing attribution. Fetched per event.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Unique identifier for the event member.",
            "event": "Id of the event this member belongs to.",
            "user": "Id of the underlying user record.",
            "event_role": "Role of the member in the event (e.g. attendee, speaker, organizer).",
            "attended": "Whether the member attended the event.",
            "entered": "Whether the member entered the event.",
            "attendance_status": "Attendance status of the member.",
            "is_engaged": "Whether the member was engaged during the event.",
            "is_in_person": "Whether the member attended in person (for hybrid events).",
            "demo_requested": "Whether the member requested a demo.",
            "quality_rating": "Lead quality rating assigned to the member.",
            "salesforce_member_id": "Corresponding Salesforce campaign member id, if synced.",
            "marketo_lead_id": "Corresponding Marketo lead id, if synced.",
            "utm_campaign": "UTM campaign attributed to the member's registration.",
            "utm_source": "UTM source attributed to the member's registration.",
            "utm_medium": "UTM medium attributed to the member's registration.",
            "created_at": "Timestamp when the event member was created.",
            "updated_at": "Timestamp when the event member was last updated.",
        },
    },
}
