from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "users": {
        "description": "End users of the Auth0 tenant, across every enabled connection (database, social, and enterprise).",
        "docs_url": "https://auth0.com/docs/api/management/v2/users/get-users",
        "columns": {
            "user_id": "Unique identifier of the user, prefixed with the connection strategy (e.g. auth0|abc123).",
            "email": "Email address of the user.",
            "email_verified": "Whether the user has verified their email address.",
            "username": "Username of the user, for connections that enable usernames.",
            "phone_number": "Phone number of the user, for SMS connections.",
            "phone_verified": "Whether the user has verified their phone number.",
            "name": "Full name of the user from the identity provider profile.",
            "nickname": "Preferred nickname or username from the identity provider profile.",
            "given_name": "Given (first) name of the user.",
            "family_name": "Family (last) name of the user.",
            "picture": "URL of the user's profile picture.",
            "created_at": "Timestamp of when the user profile was first created.",
            "updated_at": "Timestamp of the most recent change to the user profile.",
            "last_login": "Timestamp of the user's most recent successful login.",
            "last_ip": "IP address the user most recently logged in from.",
            "logins_count": "Total number of times the user has logged in.",
            "identities": "Linked identity provider accounts for this user, each with its provider, connection, and user_id.",
            "app_metadata": "Application data about the user that the user cannot edit, such as roles or plan.",
            "user_metadata": "User-editable profile data, such as preferences.",
            "blocked": "Whether the user has been blocked from signing in.",
            "multifactor": "Multi-factor authentication providers enrolled for the user.",
        },
    },
    "logs": {
        "description": "Tenant log events, covering authentication attempts, Management API calls, and administrative changes. Retention depends on the Auth0 subscription.",
        "docs_url": "https://auth0.com/docs/api/management/v2/logs/get-logs",
        "columns": {
            "log_id": "Unique identifier of the log event.",
            "date": "Timestamp of when the event occurred.",
            "type": "Short event type code (e.g. s for successful login, f for failed login).",
            "description": "Human-readable description of the event.",
            "client_id": "Identifier of the application the event relates to.",
            "client_name": "Name of the application the event relates to.",
            "ip": "IP address the request originated from.",
            "user_agent": "User agent string of the client that made the request.",
            "user_id": "Identifier of the user the event relates to, when there is one.",
            "user_name": "Username or email of the user the event relates to.",
            "connection": "Name of the connection used for the authentication attempt.",
            "connection_id": "Identifier of the connection used for the authentication attempt.",
            "audience": "API audience requested by the authentication attempt.",
            "scope": "Scopes requested by the authentication attempt.",
            "strategy": "Connection strategy used (e.g. auth0, google-oauth2, samlp).",
            "hostname": "Auth0 hostname that served the request.",
            "location_info": "Geographic information derived from the request IP address.",
            "details": "Event-specific payload, including the request and response when available.",
        },
    },
    "clients": {
        "description": "Applications registered in the tenant, each representing something that authenticates users through Auth0.",
        "docs_url": "https://auth0.com/docs/api/management/v2/clients/get-clients",
        "columns": {
            "client_id": "Unique identifier of the application.",
            "name": "Display name of the application.",
            "description": "Free-text description of the application.",
            "app_type": "Application type (e.g. spa, native, regular_web, non_interactive).",
            "is_first_party": "Whether the application belongs to the tenant owner rather than a third party.",
            "oidc_conformant": "Whether the application uses the OIDC-conformant authentication pipeline.",
            "callbacks": "Allowed callback URLs the authorization response may be redirected to.",
            "allowed_origins": "Origins allowed to make cross-origin authentication requests.",
            "web_origins": "Origins allowed to use cross-origin authentication and silent authentication.",
            "allowed_logout_urls": "URLs a user may be redirected to after logging out.",
            "grant_types": "OAuth grant types the application is allowed to use.",
            "jwt_configuration": "Token lifetime and signing algorithm used for this application's ID tokens.",
            "token_endpoint_auth_method": "How the application authenticates against the token endpoint.",
            "sso": "Whether single sign-on is enabled for the application.",
            "logo_uri": "URL of the application's logo, shown on the login page.",
        },
    },
    "connections": {
        "description": "Identity sources enabled in the tenant, such as database, social, and enterprise connections.",
        "docs_url": "https://auth0.com/docs/api/management/v2/connections/get-connections",
        "columns": {
            "id": "Unique identifier of the connection.",
            "name": "Name of the connection.",
            "display_name": "Name shown to users on the login page.",
            "strategy": "Connection strategy (e.g. auth0, google-oauth2, samlp, ad).",
            "options": "Strategy-specific configuration for the connection, including its provider settings.",
            "enabled_clients": "Identifiers of the applications this connection is enabled for.",
            "realms": "Realms the connection serves, used for home realm discovery.",
            "is_domain_connection": "Whether the connection is a domain-level connection for organizations.",
            "metadata": "Custom key-value metadata attached to the connection.",
        },
    },
    "roles": {
        "description": "Roles defined in the tenant's role-based access control settings.",
        "docs_url": "https://auth0.com/docs/api/management/v2/roles/get-roles",
        "columns": {
            "id": "Unique identifier of the role.",
            "name": "Name of the role.",
            "description": "Free-text description of what the role grants.",
        },
    },
    "organizations": {
        "description": "Organizations in the tenant, used to represent business customers and partners in a B2B setup.",
        "docs_url": "https://auth0.com/docs/api/management/v2/organizations/get-organizations",
        "columns": {
            "id": "Unique identifier of the organization.",
            "name": "Machine-readable name of the organization.",
            "display_name": "Name of the organization shown to users.",
            "branding": "Login page branding for the organization, such as its logo and colors.",
            "metadata": "Custom key-value metadata attached to the organization.",
        },
    },
    "resource_servers": {
        "description": "APIs registered in the tenant, each defining an audience that access tokens can be issued for.",
        "docs_url": "https://auth0.com/docs/api/management/v2/resource-servers/get-resource-servers",
        "columns": {
            "id": "Unique identifier of the API.",
            "name": "Display name of the API.",
            "identifier": "Audience value used when requesting access tokens for this API.",
            "scopes": "Permissions defined on the API, each with a value and description.",
            "signing_alg": "Algorithm used to sign access tokens issued for this API.",
            "token_lifetime": "Lifetime in seconds of access tokens issued for this API.",
            "allow_offline_access": "Whether refresh tokens can be issued for this API.",
            "skip_consent_for_verifiable_first_party_clients": "Whether first-party applications skip the consent prompt.",
            "enforce_policies": "Whether role-based access control policies are enforced for this API.",
        },
    },
    "actions": {
        "description": "Actions defined in the tenant: custom Node.js functions bound to points in the Auth0 authentication and authorization pipelines.",
        "docs_url": "https://auth0.com/docs/api/management/v2/actions/get-actions",
        "columns": {
            "id": "Unique identifier of the action.",
            "name": "Name of the action.",
            "supported_triggers": "Pipeline triggers the action can be bound to, with their versions.",
            "created_at": "Timestamp of when the action was created.",
            "updated_at": "Timestamp of the most recent change to the action.",
            "dependencies": "npm packages the action's code depends on.",
            "secrets": "Names of the secrets configured for the action; values are not returned.",
            "runtime": "Node.js runtime the action executes on.",
            "status": "Build status of the action's most recent version.",
            "all_changes_deployed": "Whether every change to the action has been deployed.",
            "deployed_version": "The action version currently deployed.",
        },
    },
    "log_streams": {
        "description": "Log streams configured in the tenant, each forwarding tenant log events to an external sink.",
        "docs_url": "https://auth0.com/docs/api/management/v2/log-streams/get-log-streams",
        "columns": {
            "id": "Unique identifier of the log stream.",
            "name": "Name of the log stream.",
            "type": "Sink type the stream delivers to (e.g. http, datadog, eventbridge, splunk).",
            "status": "Delivery status of the stream (active, paused, or suspended).",
            "sink": "Sink-specific delivery configuration for the stream.",
            "filters": "Event categories the stream is limited to, when filtering is configured.",
        },
    },
}
