from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Descriptions sourced from the official ClickHouse Cloud OpenAPI spec
# (https://clickhouse.com/docs/cloud/manage/api/swagger).
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "organizations": {
        "description": "The ClickHouse Cloud organization the API key is scoped to (the API returns exactly one organization per key).",
        "docs_url": "https://clickhouse.com/docs/cloud/manage/api/swagger",
        "columns": {
            "id": "Unique organization ID.",
            "createdAt": "The timestamp the organization was created. ISO-8601.",
            "name": "Name of the organization.",
            "privateEndpoints": "List of private endpoints for the organization.",
            "byocConfig": "BYOC (bring your own cloud) configuration for the organization.",
            "enableCoreDumps": "Whether crash report (core dump) collection is enabled for services in the organization.",
        },
    },
    "services": {
        "description": "All ClickHouse Cloud services in the organization, including state, tier, region, and scaling configuration.",
        "docs_url": "https://clickhouse.com/docs/cloud/manage/api/swagger",
        "columns": {
            "id": "Unique service ID.",
            "organizationId": "ID of the organization the service belongs to.",
            "name": "Name of the service.",
            "provider": "Cloud provider (aws, gcp, azure).",
            "region": "Service region.",
            "state": "Current state of the service.",
            "clickhouseVersion": "ClickHouse version of the service.",
            "endpoints": "List of all service endpoints.",
            "tier": "Deprecated service tier; use minReplicaMemoryGb, maxReplicaMemoryGb, and numReplicas instead.",
            "minReplicaMemoryGb": "Minimum total memory of each replica during auto-scaling, in GB.",
            "maxReplicaMemoryGb": "Maximum total memory of each replica during auto-scaling, in GB.",
            "numReplicas": "Number of replicas for the service.",
            "autoscalingMode": "Configured autoscaling mode: vertical (fixed replica count, memory scales) or horizontal (replica count scales at fixed memory).",
            "idleScaling": "When true the service is allowed to scale down to zero when idle.",
            "idleTimeoutMinutes": "Minimum idling timeout in minutes.",
            "ipAccessList": "List of IP addresses allowed to access the service.",
            "createdAt": "Service creation timestamp. ISO-8601.",
            "dataWarehouseId": "Data warehouse containing this service.",
            "isPrimary": "True if this service is the primary service in the data warehouse.",
            "isReadonly": "True if this service is read-only.",
            "releaseChannel": "Release channel of the service: fast, default, or slow.",
            "complianceType": "Type of regulatory compliance for the service.",
            "tags": "Tags associated with the service.",
        },
    },
    "usage_cost": {
        "description": "Daily per-entity usage cost records in ClickHouse Credits (CHCs), broken down by storage, compute, backup, and data transfer. Recent records may be restated until locked.",
        "docs_url": "https://clickhouse.com/docs/cloud/manage/api/swagger",
        "columns": {
            "organizationId": "ID of the organization the usage cost belongs to.",
            "date": "Date of the usage. ISO-8601 date, based on the UTC timezone.",
            "entityType": "Type of the entity: datawarehouse, service, or clickpipe.",
            "entityId": "Unique ID of the entity.",
            "entityName": "Name of the entity.",
            "dataWarehouseId": "ID of the data warehouse this entity belongs to (or is).",
            "serviceId": "ID of the service this entity belongs to (or is). Null for data warehouse entities.",
            "totalCHC": "Total cost of usage in ClickHouse Credits (CHCs) for this entity.",
            "locked": "When true, the record is immutable. Unlocked records are subject to change until locked.",
            "storageCHC": "Cost of storage in ClickHouse Credits (CHCs). Applies to data warehouse entities.",
            "backupCHC": "Cost of backup in ClickHouse Credits (CHCs). Applies to data warehouse entities.",
            "computeCHC": "Cost of compute in ClickHouse Credits (CHCs). Applies to service and ClickPipe entities.",
            "dataTransferCHC": "Cost of data transfer in ClickHouse Credits (CHCs). Applies to ClickPipe entities.",
            "initialLoadCHC": "Cost of initial load and resyncs in ClickHouse Credits (CHCs). Applies to ClickPipe entities.",
            "publicDataTransferCHC": "Cost of public data transfer in ClickHouse Credits (CHCs). Applies to service entities.",
            "interRegionTier1DataTransferCHC": "Cost of tier 1 inter-region data transfer in ClickHouse Credits (CHCs). Applies to service entities.",
            "interRegionTier2DataTransferCHC": "Cost of tier 2 inter-region data transfer in ClickHouse Credits (CHCs). Applies to service entities.",
            "interRegionTier3DataTransferCHC": "Cost of tier 3 inter-region data transfer in ClickHouse Credits (CHCs). Applies to service entities.",
            "interRegionTier4DataTransferCHC": "Cost of tier 4 inter-region data transfer in ClickHouse Credits (CHCs). Applies to service entities.",
        },
    },
    "api_keys": {
        "description": "All API keys in the organization (metadata only — the API never returns key secrets).",
        "docs_url": "https://clickhouse.com/docs/cloud/manage/api/swagger",
        "columns": {
            "id": "Unique API key ID.",
            "organizationId": "ID of the organization the key belongs to.",
            "name": "Name of the key.",
            "state": "State of the key: enabled or disabled.",
            "roles": "Deprecated list of roles assigned to the key; use assignedRoles instead.",
            "assignedRoles": "Custom roles and system roles assigned to this API key.",
            "keySuffix": "Last 4 letters of the key.",
            "createdAt": "Timestamp the key was created. ISO-8601.",
            "expireAt": "Timestamp the key expires. Null or empty if the key never expires. ISO-8601.",
            "usedAt": "Timestamp the key was last used. Absent if the key was never used. ISO-8601.",
            "ipAccessList": "List of IP addresses allowed to use this key.",
        },
    },
    "members": {
        "description": "All members of the organization and their roles.",
        "docs_url": "https://clickhouse.com/docs/cloud/manage/api/swagger",
        "columns": {
            "organizationId": "ID of the organization the member belongs to.",
            "userId": "Unique user ID, stable across organizations.",
            "name": "Name of the member as set in their personal user profile.",
            "email": "Email of the member as set in their personal user profile.",
            "role": "Deprecated role of the member in the organization; use assignedRoles instead.",
            "assignedRoles": "Custom roles and system roles assigned to this member.",
            "joinedAt": "Timestamp the member joined the organization. ISO-8601.",
        },
    },
    "activities": {
        "description": "The organization audit log: service, key, and member changes with actor details.",
        "docs_url": "https://clickhouse.com/docs/cloud/manage/api/swagger",
        "columns": {
            "id": "Unique activity ID.",
            "createdAt": "Timestamp of the activity. ISO-8601.",
            "type": "Type of the activity.",
            "actorType": "Type of the actor: user, support, system, or api.",
            "actorId": "Unique actor ID.",
            "actorDetails": "Additional information about the actor.",
            "actorIpAddress": "IP address of the actor. Defined for user and api actor types.",
            "organizationId": "Organization ID this activity is related to.",
            "serviceId": "Service ID this activity is related to.",
            "userAgent": "User agent of the actor.",
            "targetKeyId": "For openapi_key_update activities: the ID of the API key that was updated.",
            "keyUpdateType": "For openapi_key_update activities: the type of update that was performed.",
        },
    },
    "backups": {
        "description": "Backups for every service in the organization, most recent first.",
        "docs_url": "https://clickhouse.com/docs/cloud/manage/api/swagger",
        "columns": {
            "id": "Unique backup ID.",
            "organizationId": "ID of the organization the backup belongs to.",
            "serviceId": "ID of the service the backup belongs to.",
            "status": "Status of the backup: done, error, or in_progress.",
            "startedAt": "Backup start timestamp. ISO-8601.",
            "finishedAt": "Backup finish timestamp. ISO-8601. Available only for finished backups.",
            "sizeInBytes": "Size of the backup in bytes.",
            "durationInSeconds": "Time in seconds it took to perform the backup.",
            "type": "Backup type: full or incremental.",
            "backupName": "Backup name on the external backup bucket.",
            "bucket": "Backup bucket where the backup is stored.",
        },
    },
}
