from collections.abc import Callable
from typing import Any

from products.replay_vision.backend.temporal.activities import (
    advance_backfill_cursor_activity,
    advance_scanner_watermark_activity,
    call_scanner_provider_activity,
    check_scanner_budget_activity,
    cleanup_gemini_file_activity,
    count_in_flight_applies_activity,
    count_in_flight_by_team_activity,
    create_observation_activity,
    delete_backfill_schedule_activity,
    delete_scanner_schedule_activity,
    embed_observation_activity,
    emit_classifier_tags_activity,
    emit_observation_event_activity,
    emit_observation_signal_activity,
    emit_observation_signal_summaries_activity,
    emit_observation_signals_activity,
    ensure_session_asset_activity,
    fetch_session_events_activity,
    fetch_session_network_activity,
    finalize_observation_media_activity,
    finalize_observation_thumbnail_activity,
    find_backfill_candidates_activity,
    find_scanner_candidates_activity,
    list_enabled_scanners_activity,
    list_scanner_schedules_activity,
    list_stale_scanner_estimates_activity,
    mark_observation_failed_activity,
    mark_observation_ineligible_activity,
    mark_observation_running_activity,
    mark_observation_succeeded_activity,
    meter_scanner_read_bytes_activity,
    pause_backfill_schedule_activity,
    prepare_backfill_tick_activity,
    prepare_observation_media_activity,
    prepare_observation_thumbnail_activity,
    reap_backfill_schedules_activity,
    reap_childless_inline_scanners_activity,
    reap_orphaned_observations_activity,
    refresh_scanner_estimate_activity,
    resolve_experiment_variant_activity,
    start_launched_scanners_activity,
    upload_video_to_gemini_activity,
    upsert_scanner_schedule_activity,
)
from products.replay_vision.backend.temporal.activities.benchmark import (
    load_benchmark_cases_activity,
    prepare_benchmark_case_activity,
    record_benchmark_case_activity,
    snapshot_benchmark_labels_activity,
    write_benchmark_manifest_activity,
)
from products.replay_vision.backend.temporal.activities.refresh_learned_rules import (
    list_due_learned_rules_teams_activity,
    refresh_team_learned_rules_activity,
)
from products.replay_vision.backend.temporal.activities.refresh_search_suggestions import (
    list_stale_search_suggestions_activity,
    refresh_scanner_search_suggestions_activity,
)
from products.replay_vision.backend.temporal.backfill_workflow import BackfillScannerWorkflow
from products.replay_vision.backend.temporal.benchmark_workflow import BuildBenchmarkWorkflow
from products.replay_vision.backend.temporal.estimates import RefreshScannerEstimatesWorkflow
from products.replay_vision.backend.temporal.gemini_cleanup_sweep import (
    ReplayVisionGeminiCleanupSweepWorkflow,
    sweep_gemini_files_activity,
)
from products.replay_vision.backend.temporal.jev_watch_rank import (
    ReplayVisionJevWatchRankWorkflow,
    judge_watch_ranks_activity,
)
from products.replay_vision.backend.temporal.learned_rules import RefreshLearnedRulesWorkflow
from products.replay_vision.backend.temporal.media_workflow import ObservationMediaWorkflow
from products.replay_vision.backend.temporal.read_meter import MeterScannerReadsWorkflow
from products.replay_vision.backend.temporal.reconciler import ReconcileScannerSchedulesWorkflow
from products.replay_vision.backend.temporal.search_suggestions import RefreshSearchSuggestionsWorkflow
from products.replay_vision.backend.temporal.sweep_workflow import SweepScannerWorkflow
from products.replay_vision.backend.temporal.vision_alerts import (
    VisionAlertCheckWorkflow,
    cleanup_vision_alert_history_activity,
    discover_due_vision_alerts_activity,
    drain_vision_alert_matches_activity,
    evaluate_vision_alert_batch_activity,
)
from products.replay_vision.backend.temporal.workflow import ApplyScannerWorkflow

WORKFLOWS = [
    ApplyScannerWorkflow,
    BackfillScannerWorkflow,
    BuildBenchmarkWorkflow,
    MeterScannerReadsWorkflow,
    ObservationMediaWorkflow,
    ReconcileScannerSchedulesWorkflow,
    RefreshScannerEstimatesWorkflow,
    RefreshLearnedRulesWorkflow,
    RefreshSearchSuggestionsWorkflow,
    ReplayVisionGeminiCleanupSweepWorkflow,
    ReplayVisionJevWatchRankWorkflow,
    SweepScannerWorkflow,
    VisionAlertCheckWorkflow,
]
ACTIVITIES: list[Callable[..., Any]] = [
    discover_due_vision_alerts_activity,
    evaluate_vision_alert_batch_activity,
    drain_vision_alert_matches_activity,
    cleanup_vision_alert_history_activity,
    create_observation_activity,
    mark_observation_running_activity,
    mark_observation_failed_activity,
    mark_observation_ineligible_activity,
    mark_observation_succeeded_activity,
    fetch_session_events_activity,
    fetch_session_network_activity,
    ensure_session_asset_activity,
    upload_video_to_gemini_activity,
    call_scanner_provider_activity,
    embed_observation_activity,
    emit_classifier_tags_activity,
    emit_observation_event_activity,
    emit_observation_signal_activity,
    emit_observation_signal_summaries_activity,
    emit_observation_signals_activity,
    cleanup_gemini_file_activity,
    prepare_observation_thumbnail_activity,
    prepare_observation_media_activity,
    finalize_observation_thumbnail_activity,
    finalize_observation_media_activity,
    resolve_experiment_variant_activity,
    find_scanner_candidates_activity,
    count_in_flight_applies_activity,
    count_in_flight_by_team_activity,
    check_scanner_budget_activity,
    advance_scanner_watermark_activity,
    prepare_backfill_tick_activity,
    find_backfill_candidates_activity,
    advance_backfill_cursor_activity,
    pause_backfill_schedule_activity,
    delete_backfill_schedule_activity,
    reap_backfill_schedules_activity,
    list_enabled_scanners_activity,
    list_scanner_schedules_activity,
    upsert_scanner_schedule_activity,
    delete_scanner_schedule_activity,
    list_stale_scanner_estimates_activity,
    refresh_scanner_estimate_activity,
    meter_scanner_read_bytes_activity,
    reap_childless_inline_scanners_activity,
    reap_orphaned_observations_activity,
    start_launched_scanners_activity,
    sweep_gemini_files_activity,
    judge_watch_ranks_activity,
    list_stale_search_suggestions_activity,
    refresh_scanner_search_suggestions_activity,
    list_due_learned_rules_teams_activity,
    refresh_team_learned_rules_activity,
    snapshot_benchmark_labels_activity,
    load_benchmark_cases_activity,
    prepare_benchmark_case_activity,
    record_benchmark_case_activity,
    write_benchmark_manifest_activity,
]

__all__ = [
    "ACTIVITIES",
    "WORKFLOWS",
    "ApplyScannerWorkflow",
    "BackfillScannerWorkflow",
    "MeterScannerReadsWorkflow",
    "ObservationMediaWorkflow",
    "ReconcileScannerSchedulesWorkflow",
    "RefreshScannerEstimatesWorkflow",
    "RefreshLearnedRulesWorkflow",
    "RefreshSearchSuggestionsWorkflow",
    "ReplayVisionGeminiCleanupSweepWorkflow",
    "SweepScannerWorkflow",
    "advance_scanner_watermark_activity",
    "call_scanner_provider_activity",
    "check_scanner_budget_activity",
    "cleanup_gemini_file_activity",
    "count_in_flight_applies_activity",
    "count_in_flight_by_team_activity",
    "create_observation_activity",
    "delete_scanner_schedule_activity",
    "embed_observation_activity",
    "emit_classifier_tags_activity",
    "emit_observation_event_activity",
    "emit_observation_signal_activity",
    "emit_observation_signal_summaries_activity",
    "emit_observation_signals_activity",
    "ensure_session_asset_activity",
    "fetch_session_events_activity",
    "fetch_session_network_activity",
    "find_scanner_candidates_activity",
    "list_enabled_scanners_activity",
    "list_scanner_schedules_activity",
    "list_stale_scanner_estimates_activity",
    "meter_scanner_read_bytes_activity",
    "mark_observation_failed_activity",
    "mark_observation_ineligible_activity",
    "mark_observation_running_activity",
    "mark_observation_succeeded_activity",
    "reap_childless_inline_scanners_activity",
    "reap_orphaned_observations_activity",
    "refresh_scanner_estimate_activity",
    "start_launched_scanners_activity",
    "sweep_gemini_files_activity",
    "upload_video_to_gemini_activity",
    "upsert_scanner_schedule_activity",
]
