"""Canonical, documentation-sourced descriptions for Intercom endpoints and columns.

Sourced from the official Intercom REST API reference (https://developers.intercom.com/docs/references/rest-api).
Keyed by the endpoint names in `settings.py` `INTERCOM_ENDPOINTS`, which match the
`ExternalDataSchema.name` of a synced Intercom table. Columns absent here fall back to LLM enrichment.
"""

from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "admins": {
        "description": "A teammate (admin) in the Intercom workspace who can reply to and manage conversations.",
        "docs_url": "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/admins/listadmins",
        "columns": {
            "id": "Unique identifier for the admin.",
            "type": "The object type, always 'admin'.",
            "name": "The admin's name.",
            "email": "The admin's email address.",
            "job_title": "The admin's job title.",
            "away_mode_enabled": "Whether the admin has away mode turned on.",
            "away_mode_reassign": "Whether conversations are reassigned while the admin is away.",
            "has_inbox_seat": "Whether the admin has a seat in the Intercom inbox.",
            "team_ids": "Identifiers of the teams the admin belongs to.",
        },
    },
    "teams": {
        "description": "A team of admins in the Intercom workspace.",
        "docs_url": "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/teams/listteams",
        "columns": {
            "id": "Unique identifier for the team.",
            "type": "The object type, always 'team'.",
            "name": "The team's name.",
            "admin_ids": "Identifiers of the admins who are members of the team.",
        },
    },
    "tags": {
        "description": "A tag used to label conversations, contacts, and companies in Intercom.",
        "docs_url": "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/tags/listtags",
        "columns": {
            "id": "Unique identifier for the tag.",
            "type": "The object type, always 'tag'.",
            "name": "The tag's name.",
        },
    },
    "segments": {
        "description": "A segment grouping contacts that match a set of conditions in Intercom.",
        "docs_url": "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/segments/listsegments",
        "columns": {
            "id": "Unique identifier for the segment.",
            "type": "The object type, always 'segment'.",
            "name": "The segment's name.",
            "person_type": "Whether the segment applies to users or leads.",
            "count": "Number of contacts currently in the segment.",
            "created_at": "Time at which the segment was created, as a Unix timestamp.",
            "updated_at": "Time at which the segment was last updated, as a Unix timestamp.",
        },
    },
    "companies": {
        "description": "A company (account) in Intercom that contacts can be associated with.",
        "docs_url": "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/companies/listallcompanies",
        "columns": {
            "id": "Unique identifier for the company.",
            "type": "The object type, always 'company'.",
            "company_id": "The external company identifier you assigned.",
            "name": "The company's name.",
            "plan": "The plan the company is on.",
            "size": "The number of employees at the company.",
            "website": "The company's website.",
            "industry": "The company's industry.",
            "monthly_spend": "The company's monthly spend.",
            "session_count": "Number of sessions recorded for the company.",
            "user_count": "Number of contacts associated with the company.",
            "custom_attributes": "Custom attribute values set on the company.",
            "created_at": "Time at which the company was added to Intercom, as a Unix timestamp.",
            "updated_at": "Time at which the company was last updated, as a Unix timestamp.",
            "last_request_at": "Time of the company's most recent activity, as a Unix timestamp.",
        },
    },
    "contacts": {
        "description": "A contact in Intercom — a user or lead you communicate with.",
        "docs_url": "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/contacts/listcontacts",
        "columns": {
            "id": "Unique identifier for the contact.",
            "type": "The object type, always 'contact'.",
            "role": "Whether the contact is a user or a lead.",
            "external_id": "The external identifier you assigned to the contact.",
            "name": "The contact's name.",
            "email": "The contact's email address.",
            "phone": "The contact's phone number.",
            "avatar": "The contact's avatar image.",
            "owner_id": "Identifier of the admin who owns the contact.",
            "custom_attributes": "Custom attribute values set on the contact.",
            "tags": "The tags applied to the contact.",
            "unsubscribed_from_emails": "Whether the contact has unsubscribed from email messages.",
            "enabled_push_messaging": "Whether the contact has enabled push messaging.",
            "android_sdk_version": "Version of the Intercom Android SDK on the contact's most recent Android device.",
            "last_seen_at": "Time the contact was last seen, as a Unix timestamp.",
            "signed_up_at": "Time the contact signed up, as a Unix timestamp.",
            "created_at": "Time at which the contact was created, as a Unix timestamp.",
            "updated_at": "Time at which the contact was last updated, as a Unix timestamp.",
        },
    },
    "conversations": {
        "description": "A conversation between a contact and your team in Intercom.",
        "docs_url": "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/conversations/listconversations",
        "columns": {
            "id": "Unique identifier for the conversation.",
            "type": "The object type, always 'conversation'.",
            "title": "The conversation's title.",
            "state": "Current state of the conversation (e.g. open, closed, snoozed).",
            "open": "Whether the conversation is currently open.",
            "read": "Whether the conversation has been read.",
            "priority": "The priority of the conversation (priority or not_priority).",
            "admin_assignee_id": "Identifier of the admin the conversation is assigned to.",
            "team_assignee_id": "Identifier of the team the conversation is assigned to.",
            "source": "Details of the message that started the conversation.",
            "contacts": "The contacts participating in the conversation.",
            "statistics": "Aggregate statistics about the conversation (response times, counts).",
            "created_at": "Time at which the conversation was created, as a Unix timestamp.",
            "updated_at": "Time at which the conversation was last updated, as a Unix timestamp.",
        },
    },
    "tickets": {
        "description": "A ticket in Intercom tracking a customer request through to resolution.",
        "docs_url": "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/tickets/listtickets",
        "columns": {
            "id": "Unique identifier for the ticket.",
            "type": "The object type, always 'ticket'.",
            "ticket_id": "The user-facing ticket number.",
            "ticket_state": "Current state of the ticket (e.g. submitted, in_progress, resolved).",
            "ticket_type": "The type of the ticket.",
            "category": "The ticket category (e.g. Customer, Back-office, Tracker).",
            "ticket_attributes": "Values of the ticket's attributes.",
            "admin_assignee_id": "Identifier of the admin the ticket is assigned to.",
            "team_assignee_id": "Identifier of the team the ticket is assigned to.",
            "contacts": "The contacts associated with the ticket.",
            "open": "Whether the ticket is currently open.",
            "created_at": "Time at which the ticket was created, as a Unix timestamp.",
            "updated_at": "Time at which the ticket was last updated, as a Unix timestamp.",
        },
    },
    "articles": {
        "description": "A help center article in Intercom.",
        "docs_url": "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/articles/listarticles",
        "columns": {
            "id": "Unique identifier for the article.",
            "type": "The object type, always 'article'.",
            "title": "The article's title.",
            "description": "Short description of the article.",
            "body": "The article's HTML body.",
            "author_id": "Identifier of the admin who authored the article.",
            "state": "Whether the article is published or a draft.",
            "parent_id": "Identifier of the collection the article belongs to.",
            "url": "Public URL of the article.",
            "created_at": "Time at which the article was created, as a Unix timestamp.",
            "updated_at": "Time at which the article was last updated, as a Unix timestamp.",
        },
    },
    "activity_logs": {
        "description": "An entry in the admin activity log recording an action taken in the Intercom workspace.",
        "docs_url": "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/admins/listactivitylogs",
        "columns": {
            "id": "Unique identifier for the activity log entry.",
            "performed_by": "The admin who performed the action.",
            "metadata": "Details about the action that was performed.",
            "activity_type": "The type of action performed (e.g. admin_login, message_state_change).",
            "activity_description": "Human-readable description of the action.",
            "created_at": "Time at which the action was performed, as a Unix timestamp.",
        },
    },
    "company_attributes": {
        "description": "A data attribute (built-in or custom) defined on the company model in Intercom.",
        "docs_url": "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/data-attributes/lisdataattributes",
        "columns": {
            "name": "The attribute's name, unique within the company model.",
            "type": "The object type, always 'data_attribute'.",
            "model": "The model the attribute belongs to, always 'company'.",
            "full_name": "Fully qualified name of the attribute.",
            "label": "Human-readable label for the attribute.",
            "description": "Description of the attribute.",
            "data_type": "The data type of the attribute (e.g. string, integer, boolean, date).",
            "custom": "Whether the attribute is custom (true) or built-in (false).",
            "archived": "Whether the attribute has been archived.",
            "messenger_writable": "Whether the attribute can be updated via the Messenger JavaScript API.",
            "created_at": "Time at which the attribute was created, as a Unix timestamp.",
            "updated_at": "Time at which the attribute was last updated, as a Unix timestamp.",
        },
    },
    "contact_attributes": {
        "description": "A data attribute (built-in or custom) defined on the contact model in Intercom.",
        "docs_url": "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/data-attributes/lisdataattributes",
        "columns": {
            "name": "The attribute's name, unique within the contact model.",
            "type": "The object type, always 'data_attribute'.",
            "model": "The model the attribute belongs to, always 'contact'.",
            "full_name": "Fully qualified name of the attribute.",
            "label": "Human-readable label for the attribute.",
            "description": "Description of the attribute.",
            "data_type": "The data type of the attribute (e.g. string, integer, boolean, date).",
            "custom": "Whether the attribute is custom (true) or built-in (false).",
            "archived": "Whether the attribute has been archived.",
            "messenger_writable": "Whether the attribute can be updated via the Messenger JavaScript API.",
            "created_at": "Time at which the attribute was created, as a Unix timestamp.",
            "updated_at": "Time at which the attribute was last updated, as a Unix timestamp.",
        },
    },
    "conversation_parts": {
        "description": "An individual part (message, note, or assignment) within an Intercom conversation.",
        "docs_url": "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/conversations/retrieveconversation",
        "columns": {
            "id": "Unique identifier for the conversation part.",
            "type": "The object type, always 'conversation_part'.",
            "conversation_id": "Identifier of the conversation this part belongs to.",
            "part_type": "The kind of part (e.g. comment, note, assignment, close).",
            "body": "The HTML body of the part.",
            "author": "The author (admin, contact, or bot) of the part.",
            "assigned_to": "The admin or team the part assigned the conversation to, if any.",
            "created_at": "Time at which the part was created, as a Unix timestamp.",
            "updated_at": "Time at which the part was last updated, as a Unix timestamp.",
            "notified_at": "Time at which participants were notified of the part, as a Unix timestamp.",
        },
    },
    "company_segments": {
        "description": "The link between a company and a segment it belongs to in Intercom.",
        "docs_url": "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/companies/listsegmentsacompanybelongsto",
        "columns": {
            "id": "Unique identifier for the segment.",
            "company_id": "Identifier of the company the segment is associated with.",
            "type": "The object type, always 'segment'.",
            "name": "The segment's name.",
            "person_type": "Whether the segment applies to users or leads.",
            "created_at": "Time at which the segment was created, as a Unix timestamp.",
            "updated_at": "Time at which the segment was last updated, as a Unix timestamp.",
        },
    },
    "help_centers": {
        "description": "A Help Center site in the workspace. Help Centers contain the collections that group articles.",
        "docs_url": "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/help-center/listallhelpcenters",
        "columns": {
            "id": "Unique identifier for the Help Center.",
            "type": "The object type, always 'help_center'.",
            "workspace_id": "Identifier of the workspace the Help Center belongs to.",
            "identifier": "The identifier of the Help Center, used in its URL.",
            "display_name": "The display name of the Help Center, only seen by teammates.",
            "url": "The URL of the Help Center, using the custom domain when one is configured.",
            "custom_domain": "Custom domain configured for the Help Center.",
            "website_turned_on": "Whether the Help Center site is turned on.",
            "default": "Whether this Help Center is the workspace default.",
            "locales": "The locales the Help Center is available in.",
            "created_at": "Time at which the Help Center was created, as a Unix timestamp.",
            "updated_at": "Time at which the Help Center was last updated, as a Unix timestamp.",
        },
    },
    "collections": {
        "description": "A Help Center collection, the top level container that groups articles.",
        "docs_url": "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/help-center/listallcollections",
        "columns": {
            "id": "Unique identifier for the collection.",
            "workspace_id": "Identifier of the workspace the collection belongs to.",
            "name": "The name of the collection. For multilingual collections this is the default language's name.",
            "description": "The description of the collection, in the default language.",
            "url": "The URL of the collection, in the default language.",
            "icon": "The icon of the collection.",
            "order": "The position of the collection relative to others, starting at 0.",
            "default_locale": "The default locale of the Help Center. Only returned for multilingual Help Centers.",
            "translated_content": "The collection's name and description in each configured locale.",
            "parent_id": "Identifier of the parent collection, or null when this is a top level collection.",
            "help_center_id": "Identifier of the Help Center the collection belongs to.",
            "created_at": "Time at which the collection was created, as a Unix timestamp.",
            "updated_at": "Time at which the collection was last updated, as a Unix timestamp.",
        },
    },
    "ticket_types": {
        "description": "A ticket type, defining the category and data fields captured on tickets of that type.",
        "docs_url": "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/tickets/listtickettypes",
        "columns": {
            "id": "Unique identifier for the ticket type.",
            "type": "The object type, always 'ticket_type'.",
            "name": "The name of the ticket type.",
            "description": "The description of the ticket type.",
            "category": "Category of the ticket type: Customer, Back-office, or Tracker.",
            "icon": "The icon of the ticket type.",
            "workspace_id": "Identifier of the workspace the ticket type belongs to.",
            "ticket_type_attributes": "The attributes captured on tickets of this type.",
            "ticket_states": "The ticket states available to tickets of this type.",
            "archived": "Whether the ticket type has been archived.",
            "created_at": "Time at which the ticket type was created, as a Unix timestamp.",
            "updated_at": "Time at which the ticket type was last updated, as a Unix timestamp.",
        },
    },
    "ticket_states": {
        "description": "A ticket state, defining a stage a ticket can be in and how that stage is labelled.",
        "docs_url": "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/tickets/listticketstates",
        "columns": {
            "id": "Unique identifier for the ticket state.",
            "type": "The object type, always 'ticket_state'.",
            "category": "The category of the state: submitted, in_progress, waiting_on_customer, or resolved.",
            "internal_label": "The state in human readable form, visible to teammates in Intercom.",
            "external_label": "The state in human readable form, visible to customers.",
            "archived": "Whether the ticket state has been archived.",
            "ticket_types": "The ticket types this state is available to.",
        },
    },
    "subscription_types": {
        "description": "A subscription type customers can opt in or out of, letting them mute non-essential messages.",
        "docs_url": "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/subscription-types/listsubscriptiontypes",
        "columns": {
            "id": "Unique identifier for the subscription type.",
            "type": "The object type, always 'subscription'.",
            "state": "The state of the subscription type: live, draft, or archived.",
            "consent_type": "Whether consent is opt_in or opt_out.",
            "content_types": "The message types the subscription covers, such as email or sms_message.",
            "default_translation": "The subscription type's name and description in the default locale.",
            "translations": "The subscription type's name and description in each configured locale.",
        },
    },
    "news_items": {
        "description": "A news item, used to announce product updates, company news, promotions, and events to customers.",
        "docs_url": "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/news/listnewsitems",
        "columns": {
            "id": "Unique identifier for the news item.",
            "type": "The object type, always 'news-item'.",
            "workspace_id": "Identifier of the workspace the news item belongs to.",
            "title": "The title of the news item.",
            "body": "The body of the news item, which may contain HTML.",
            "sender_id": "Identifier of the teammate sending the news item.",
            "state": "Whether the news item is a draft or live. Drafts are not visible to customers.",
            "newsfeed_assignments": "The newsfeeds the news item is assigned to, with their publish times.",
            "labels": "Label names shown to customers to categorize the news item.",
            "cover_image_url": "URL of the image used as the news item's cover.",
            "reactions": "The emoji reactions offered on the news item. Empty when reactions are disabled.",
            "deliver_silently": "Whether the news item appears in the newsfeed without a notification badge.",
            "created_at": "Time at which the news item was created, as a Unix timestamp.",
            "updated_at": "Time at which the news item was last updated, as a Unix timestamp.",
        },
    },
    "newsfeeds": {
        "description": "A newsfeed, the collection of news items shown to a targeted audience.",
        "docs_url": "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/news/listnewsfeeds",
        "columns": {
            "id": "Unique identifier for the newsfeed.",
            "type": "The object type, always 'newsfeed'.",
            "name": "The name of the newsfeed. Never visible to customers.",
            "created_at": "Time at which the newsfeed was created, as a Unix timestamp.",
            "updated_at": "Time at which the newsfeed was last updated, as a Unix timestamp.",
        },
    },
}
