from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

_DOCS = "https://developers.etsy.com/documentation/reference"

# Descriptions sourced from the Etsy Open API v3 reference. Partial coverage is fine — any table or
# column not listed here falls back to LLM enrichment. Every timestamp column is Unix epoch seconds.
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "shop": {
        "description": "The Etsy shop this connection syncs, including its policies, currency and listing counts.",
        "docs_url": f"{_DOCS}#operation/getShop",
        "columns": {
            "shop_id": "Unique identifier for the shop.",
            "shop_name": "The shop's name as it appears on Etsy.",
            "user_id": "Numeric id of the Etsy user who owns the shop.",
            "create_date": "Deprecated alias of created_timestamp.",
            "created_timestamp": "Unix epoch seconds when the shop was created.",
            "title": "Short tagline shown under the shop name.",
            "announcement": "Announcement banner text currently shown on the shop page.",
            "currency_code": "ISO currency code the shop lists prices in.",
            "is_vacation": "Whether the shop is currently in vacation mode.",
            "listing_active_count": "Number of listings currently active in the shop.",
            "digital_listing_count": "Number of digital (download) listings in the shop.",
            "url": "Public URL of the shop.",
            "num_favorers": "Number of Etsy users who have favorited the shop.",
            "review_count": "Total number of reviews the shop has received.",
            "review_average": "Average review rating across the shop's reviews.",
        },
    },
    "shop_sections": {
        "description": "Seller-defined sections used to group listings within the shop.",
        "docs_url": f"{_DOCS}#operation/getShopSections",
        "columns": {
            "shop_section_id": "Unique identifier for the section.",
            "title": "Display name of the section.",
            "rank": "Position of the section in the shop's navigation.",
            "user_id": "Numeric id of the Etsy user who owns the shop.",
            "active_listing_count": "Number of active listings assigned to the section.",
        },
    },
    "listings": {
        "description": "Every listing in the shop across all states (active, inactive, sold out, draft and expired).",
        "docs_url": f"{_DOCS}#operation/getListingsByShop",
        "columns": {
            "listing_id": "Unique identifier for the listing.",
            "user_id": "Numeric id of the Etsy user who created the listing.",
            "shop_id": "Numeric id of the shop the listing belongs to.",
            "title": "Listing title.",
            "description": "Full listing description.",
            "state": "Listing state: active, inactive, sold_out, draft or expired.",
            "creation_timestamp": "Unix epoch seconds when the listing was created.",
            "created_timestamp": "Unix epoch seconds when the listing was created.",
            "ending_timestamp": "Unix epoch seconds when the listing expires.",
            "original_creation_timestamp": "Unix epoch seconds when the listing was first created, before any renewal.",
            "last_modified_timestamp": "Unix epoch seconds when the listing was last updated.",
            "updated_timestamp": "Unix epoch seconds when the listing was last updated.",
            "state_timestamp": "Unix epoch seconds when the listing last changed state.",
            "quantity": "Number of units currently available.",
            "price": "Listing price, as an amount/divisor/currency_code object.",
            "currency_code": "ISO currency code of the listing price.",
            "quantity_sold": "Number of units sold for this listing.",
            "tags": "Seller-supplied tags used for search.",
            "taxonomy_id": "Etsy taxonomy node the listing is categorized under.",
            "shop_section_id": "Section of the shop the listing is assigned to.",
            "views": "Number of times the listing has been viewed.",
            "num_favorers": "Number of Etsy users who have favorited the listing.",
            "url": "Public URL of the listing.",
            "is_digital": "Whether the listing delivers a digital download.",
            "who_made": "Who made the item: i_did, someone_else or collective.",
            "when_made": "Production period the seller declared for the item.",
        },
    },
    "receipts": {
        "description": "Orders placed with the shop, one row per receipt, with buyer, shipping, totals and status.",
        "docs_url": f"{_DOCS}#operation/getShopReceipts",
        "columns": {
            "receipt_id": "Unique identifier for the receipt (order).",
            "receipt_type": "Type of receipt; 0 for a standard Etsy order.",
            "seller_user_id": "Numeric id of the selling Etsy user.",
            "buyer_user_id": "Numeric id of the buying Etsy user.",
            "status": "Order status, e.g. paid, completed, open, payment processing or canceled.",
            "created_timestamp": "Unix epoch seconds when the order was placed.",
            "updated_timestamp": "Unix epoch seconds when the receipt was last modified.",
            "is_paid": "Whether the order has been paid.",
            "is_shipped": "Whether the order has been marked shipped.",
            "grandtotal": "Total the buyer paid, as an amount/divisor/currency_code object.",
            "subtotal": "Item subtotal before shipping, discounts and tax.",
            "total_price": "Total price of the items on the receipt.",
            "total_shipping_cost": "Shipping charged on the receipt.",
            "total_tax_cost": "Sales tax charged on the receipt.",
            "total_vat_cost": "VAT charged on the receipt.",
            "discount_amt": "Discount applied to the receipt.",
            "gift_wrap_price": "Gift wrap charge on the receipt.",
            "shipments": "Shipping notifications recorded against the receipt.",
            "transactions": "Line items on the receipt; also synced as the transactions table.",
            "refunds": "Refunds issued against the receipt.",
            "country_iso": "ISO country code of the shipping address.",
            "payment_method": "Payment method the buyer used.",
        },
    },
    "transactions": {
        "description": "Line items on shop orders, one row per purchased listing, expanded from the receipts payload.",
        "docs_url": f"{_DOCS}#operation/getShopReceiptTransactionsByShop",
        "columns": {
            "transaction_id": "Unique identifier for the line item.",
            "receipt_id": "Receipt (order) this line item belongs to.",
            "listing_id": "Listing that was purchased.",
            "product_id": "Specific product variation that was purchased.",
            "title": "Title of the purchased listing at time of sale.",
            "description": "Description of the purchased listing at time of sale.",
            "seller_user_id": "Numeric id of the selling Etsy user.",
            "buyer_user_id": "Numeric id of the buying Etsy user.",
            "created_timestamp": "Unix epoch seconds when the line item was created.",
            "paid_timestamp": "Unix epoch seconds when the line item was paid for.",
            "shipped_timestamp": "Unix epoch seconds when the line item was shipped.",
            "quantity": "Number of units purchased.",
            "price": "Unit price, as an amount/divisor/currency_code object.",
            "shipping_cost": "Shipping attributed to this line item.",
            "is_digital": "Whether the purchased listing is a digital download.",
            "variations": "Buyer-selected variations (size, color, and so on).",
            "shipping_profile_id": "Shipping profile applied to the line item.",
            "sku": "Seller SKU of the purchased product.",
        },
    },
    "reviews": {
        "description": "Buyer reviews left on the shop's transactions, one row per reviewed transaction.",
        "docs_url": f"{_DOCS}#operation/getReviewsByShop",
        "columns": {
            "shop_id": "Numeric id of the reviewed shop.",
            "listing_id": "Listing the review was left on.",
            "transaction_id": "Transaction the review was left on; unique per review.",
            "buyer_user_id": "Numeric id of the reviewing Etsy user, when shared.",
            "rating": "Star rating from 1 to 5.",
            "review": "Free-text review body.",
            "language": "Language the review was written in.",
            "image_url_fullxfull": "URL of the photo the buyer attached, if any.",
            "created_timestamp": "Unix epoch seconds when the review was created.",
            "updated_timestamp": "Unix epoch seconds when the review was last edited.",
        },
    },
    "ledger_entries": {
        "description": "Payment account ledger: every credit and debit against the shop's Etsy Payments balance, including sales, fees, refunds and payouts.",
        "docs_url": f"{_DOCS}#operation/getShopPaymentAccountLedgerEntries",
        "columns": {
            "entry_id": "Unique identifier for the ledger entry.",
            "ledger_id": "Identifier of the shop's payment ledger.",
            "sequence_number": "Position of the entry within the ledger.",
            "amount": "Signed value of the entry in the ledger's smallest currency unit.",
            "currency": "ISO currency code of the entry.",
            "description": "Human-readable description of what the entry is for.",
            "balance": "Ledger balance in the smallest currency unit after the entry was applied.",
            "create_date": "Deprecated alias of created_timestamp.",
            "created_timestamp": "Unix epoch seconds when the entry was recorded.",
            "ledger_type": "Category of the entry, e.g. sale, fee, refund or payout.",
            "reference_type": "Type of the object the entry references.",
            "reference_id": "Identifier of the referenced object, e.g. a receipt id.",
            "payment_adjustment_id": "Payment adjustment this entry belongs to, when it is a refund.",
        },
    },
}
