from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "locations": {
        "description": "Monitoring locations (stations) that report air-quality measurements.",
        "docs_url": "https://docs.openaq.org/resources/locations",
        "columns": {
            "id": "Unique identifier for the location.",
            "name": "Human-readable name of the location.",
            "locality": "City or locality the location sits in.",
            "timezone": "IANA timezone identifier for the location.",
            "country": "Country the location belongs to.",
            "owner": "Entity that owns the location.",
            "provider": "Data provider that supplies the location's measurements.",
            "isMobile": "Whether the location is a mobile (moving) monitor.",
            "isMonitor": "Whether the location is a reference-grade monitor (vs a low-cost sensor).",
            "instruments": "Instruments installed at the location.",
            "sensors": "Sensors at the location, one per measured parameter.",
            "coordinates": "Latitude/longitude of the location.",
            "datetimeFirst": "Timestamp of the first measurement recorded at the location.",
            "datetimeLast": "Timestamp of the most recent measurement recorded at the location.",
        },
    },
    "parameters": {
        "description": "Pollutants and other parameters measured across the network (e.g. PM2.5, O3, NO2).",
        "docs_url": "https://docs.openaq.org/resources/parameters",
        "columns": {
            "id": "Unique identifier for the parameter.",
            "name": "Short parameter code (e.g. pm25, o3, no2).",
            "units": "Unit the parameter is reported in (e.g. µg/m³, ppm).",
            "displayName": "Human-readable parameter name.",
            "description": "Longer description of the parameter.",
        },
    },
    "countries": {
        "description": "Countries with at least one monitoring location in the network.",
        "docs_url": "https://docs.openaq.org/resources/countries",
        "columns": {
            "id": "Unique identifier for the country.",
            "code": "ISO 3166-1 alpha-2 country code.",
            "name": "Country name.",
            "parameters": "Parameters measured somewhere in the country.",
            "datetimeFirst": "Timestamp of the first measurement recorded in the country.",
            "datetimeLast": "Timestamp of the most recent measurement recorded in the country.",
        },
    },
    "providers": {
        "description": "Organizations that supply air-quality data to OpenAQ.",
        "docs_url": "https://docs.openaq.org/resources/providers",
        "columns": {
            "id": "Unique identifier for the provider.",
            "name": "Provider name.",
            "sourceName": "Underlying source name for the provider.",
            "datetimeAdded": "When the provider was added to OpenAQ.",
            "datetimeFirst": "Timestamp of the provider's first measurement.",
            "datetimeLast": "Timestamp of the provider's most recent measurement.",
            "parameters": "Parameters the provider supplies.",
        },
    },
    "instruments": {
        "description": "Instrument models used by monitoring locations.",
        "docs_url": "https://docs.openaq.org/resources/instruments",
        "columns": {
            "id": "Unique identifier for the instrument.",
            "name": "Instrument model name.",
            "isMonitor": "Whether the instrument is a reference-grade monitor.",
            "manufacturer": "Manufacturer of the instrument.",
        },
    },
    "manufacturers": {
        "description": "Manufacturers of the instruments used across the network.",
        "docs_url": "https://docs.openaq.org/resources/manufacturers",
        "columns": {
            "id": "Unique identifier for the manufacturer.",
            "name": "Manufacturer name.",
            "instruments": "Instruments produced by the manufacturer.",
        },
    },
    "owners": {
        "description": "Entities that own monitoring locations.",
        "docs_url": "https://docs.openaq.org/resources/owners",
        "columns": {
            "id": "Unique identifier for the owner.",
            "name": "Owner name.",
        },
    },
    "licenses": {
        "description": "Data licenses that govern how each provider's data may be used.",
        "docs_url": "https://docs.openaq.org/resources/licenses",
        "columns": {
            "id": "Unique identifier for the license.",
            "name": "License name.",
            "commercialUseAllowed": "Whether commercial use is permitted.",
            "attributionRequired": "Whether attribution is required.",
            "shareAlikeRequired": "Whether derivative works must be shared under the same license.",
            "modificationAllowed": "Whether the data may be modified.",
            "redistributionAllowed": "Whether the data may be redistributed.",
            "sourceUrl": "URL of the full license text.",
        },
    },
    "sensors": {
        "description": "Individual sensors, each measuring one parameter at one location. Materialized from the embedded sensor list on each location.",
        "docs_url": "https://docs.openaq.org/resources/sensors",
        "columns": {
            "id": "Unique identifier for the sensor.",
            "name": "Sensor name.",
            "parameter_id": "Identifier of the parameter this sensor measures.",
            "parameter_name": "Short code of the parameter this sensor measures.",
            "parameter_units": "Unit the sensor's measurements are reported in.",
            "location_id": "Identifier of the location the sensor belongs to.",
            "location_name": "Name of the location the sensor belongs to.",
            "timezone": "IANA timezone of the sensor's location.",
            "coordinates": "Latitude/longitude of the sensor's location.",
            "country": "Country the sensor's location belongs to.",
            "provider": "Data provider for the sensor's location.",
        },
    },
    "measurements": {
        "description": "Raw measurements reported by each sensor, one row per sensor per reporting period.",
        "docs_url": "https://docs.openaq.org/resources/measurements",
        "columns": {
            "sensor_id": "Identifier of the sensor that produced the measurement.",
            "datetime_from": "UTC start of the measurement's reporting period (exclusive time-ending convention).",
            "datetime_to": "UTC end of the measurement's reporting period.",
            "value": "Measured value in the parameter's units.",
            "parameter_id": "Identifier of the measured parameter.",
            "parameter_name": "Short code of the measured parameter.",
            "parameter_units": "Unit the value is reported in.",
            "coverage": "Data-coverage summary for the period.",
            "flag_info": "Quality/flag information for the measurement.",
        },
    },
    "measurements_hourly": {
        "description": "Hourly aggregated measurements per sensor.",
        "docs_url": "https://docs.openaq.org/resources/measurements",
        "columns": {
            "sensor_id": "Identifier of the sensor that produced the measurement.",
            "datetime_from": "UTC start of the hourly period.",
            "datetime_to": "UTC end of the hourly period.",
            "value": "Aggregated value for the hour, in the parameter's units.",
            "parameter_id": "Identifier of the measured parameter.",
            "parameter_name": "Short code of the measured parameter.",
            "parameter_units": "Unit the value is reported in.",
            "coordinates": "Latitude/longitude of the sensor's location.",
            "summary": "Statistical summary of the readings aggregated into the hour.",
            "coverage": "Data-coverage summary for the hour.",
            "flag_info": "Quality/flag information for the aggregated measurement.",
        },
    },
    "measurements_daily": {
        "description": "Daily aggregated measurements per sensor.",
        "docs_url": "https://docs.openaq.org/resources/measurements",
        "columns": {
            "sensor_id": "Identifier of the sensor that produced the measurement.",
            "datetime_from": "UTC start of the daily period.",
            "datetime_to": "UTC end of the daily period.",
            "value": "Aggregated value for the day, in the parameter's units.",
            "parameter_id": "Identifier of the measured parameter.",
            "parameter_name": "Short code of the measured parameter.",
            "parameter_units": "Unit the value is reported in.",
            "coordinates": "Latitude/longitude of the sensor's location.",
            "summary": "Statistical summary of the readings aggregated into the day.",
            "coverage": "Data-coverage summary for the day.",
            "flag_info": "Quality/flag information for the aggregated measurement.",
        },
    },
}
