from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

_API_DOCS = "https://developers.google.com/tag-platform/tag-manager/api/v2"

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "accounts": {
        "description": "The connected Tag Manager account and its top-level settings.",
        "docs_url": f"{_API_DOCS}/reference/rest/v2/accounts",
        "columns": {
            "path": "The relative path of the account, e.g. accounts/{account_id}.",
            "accountId": "The account's unique id.",
            "name": "The account's display name.",
            "shareData": "Whether the account shares data anonymously with Google and others.",
            "fingerprint": "A value that changes whenever the account is modified.",
            "tagManagerUrl": "Link to open the account in the Tag Manager UI.",
        },
    },
    "containers": {
        "description": "Containers in the account — each holds the tags for one website or app.",
        "docs_url": f"{_API_DOCS}/reference/rest/v2/accounts.containers",
        "columns": {
            "path": "The relative path of the container.",
            "accountId": "Id of the account that owns the container.",
            "containerId": "The container's unique id.",
            "name": "The container's display name.",
            "publicId": "The public id used to install the container (e.g. GTM-XXXX).",
            "domainName": "Domain names associated with the container.",
            "usageContext": "Where the container runs (web, android, ios, amp, server).",
            "tagIds": "Tag ids (e.g. GA measurement ids) associated with the container.",
            "notes": "Free-text notes on the container.",
            "fingerprint": "A value that changes whenever the container is modified.",
            "tagManagerUrl": "Link to open the container in the Tag Manager UI.",
        },
    },
    "workspaces": {
        "description": "Workspaces — the editable drafts where container changes are staged before publishing.",
        "docs_url": f"{_API_DOCS}/reference/rest/v2/accounts.containers.workspaces",
        "columns": {
            "path": "The relative path of the workspace.",
            "accountId": "Id of the account that owns the workspace.",
            "containerId": "Id of the container that owns the workspace.",
            "workspaceId": "The workspace's unique id.",
            "name": "The workspace's display name.",
            "description": "Free-text description of the workspace.",
            "fingerprint": "A value that changes whenever the workspace is modified.",
            "tagManagerUrl": "Link to open the workspace in the Tag Manager UI.",
        },
    },
    "tags": {
        "description": "Tags — the snippets that fire on a page or event (e.g. a GA4 or conversion tag).",
        "docs_url": f"{_API_DOCS}/reference/rest/v2/accounts.containers.workspaces.tags",
        "columns": {
            "path": "The relative path of the tag.",
            "accountId": "Id of the account that owns the tag.",
            "containerId": "Id of the container that owns the tag.",
            "workspaceId": "Id of the workspace that owns the tag.",
            "tagId": "The tag's unique id within the container.",
            "name": "The tag's display name.",
            "type": "The tag type (e.g. gaawe for a GA4 event tag).",
            "firingTriggerId": "Ids of the triggers that fire this tag.",
            "blockingTriggerId": "Ids of the triggers that block this tag.",
            "parameter": "The tag's configuration parameters.",
            "paused": "Whether the tag is currently paused.",
            "notes": "Free-text notes on the tag.",
            "fingerprint": "A value that changes whenever the tag is modified.",
            "tagManagerUrl": "Link to open the tag in the Tag Manager UI.",
        },
    },
    "triggers": {
        "description": "Triggers — the conditions that decide when a tag fires or is blocked.",
        "docs_url": f"{_API_DOCS}/reference/rest/v2/accounts.containers.workspaces.triggers",
        "columns": {
            "path": "The relative path of the trigger.",
            "accountId": "Id of the account that owns the trigger.",
            "containerId": "Id of the container that owns the trigger.",
            "workspaceId": "Id of the workspace that owns the trigger.",
            "triggerId": "The trigger's unique id within the container.",
            "name": "The trigger's display name.",
            "type": "The trigger type (e.g. pageview, click, customEvent).",
            "filter": "Conditions that must be met for the trigger to fire.",
            "customEventFilter": "Custom event conditions for the trigger.",
            "notes": "Free-text notes on the trigger.",
            "fingerprint": "A value that changes whenever the trigger is modified.",
            "tagManagerUrl": "Link to open the trigger in the Tag Manager UI.",
        },
    },
    "variables": {
        "description": "User-defined variables that supply values to tags and triggers.",
        "docs_url": f"{_API_DOCS}/reference/rest/v2/accounts.containers.workspaces.variables",
        "columns": {
            "path": "The relative path of the variable.",
            "accountId": "Id of the account that owns the variable.",
            "containerId": "Id of the container that owns the variable.",
            "workspaceId": "Id of the workspace that owns the variable.",
            "variableId": "The variable's unique id within the container.",
            "name": "The variable's display name.",
            "type": "The variable type (e.g. c for constant, jsm for custom JavaScript).",
            "parameter": "The variable's configuration parameters.",
            "notes": "Free-text notes on the variable.",
            "fingerprint": "A value that changes whenever the variable is modified.",
            "tagManagerUrl": "Link to open the variable in the Tag Manager UI.",
        },
    },
    "container_versions": {
        "description": "Version headers — one row per saved container version, with its element counts.",
        "docs_url": f"{_API_DOCS}/reference/rest/v2/accounts.containers.version_headers",
        "columns": {
            "path": "The relative path of the container version.",
            "accountId": "Id of the account that owns the version.",
            "containerId": "Id of the container the version belongs to.",
            "containerVersionId": "The version's unique id.",
            "name": "The version's display name.",
            "numTags": "Number of tags in the version.",
            "numTriggers": "Number of triggers in the version.",
            "numVariables": "Number of variables in the version.",
            "numMacros": "Number of macros in the version.",
            "numRules": "Number of rules in the version.",
            "numZones": "Number of zones in the version.",
            "deleted": "Whether the version has been deleted.",
        },
    },
}
