import { MakeLogicType, actions, connect, kea, listeners, path, reducers, selectors } from 'kea'

import { userLogic } from 'scenes/userLogic'

import { UserType } from '~/types'

import { isEmailAction } from '../../steps/types'
import { HogFlow } from '../../types'

interface StoredEmailAddressOverride {
    email: string
    userUuid: string
}

// One visible recipient and no cc/bcc is what keeps a real test send away from the workflow's audience.
export const withTestEmailRecipient = (workflow: HogFlow, recipientEmail: string): HogFlow => ({
    ...workflow,
    actions: workflow.actions.map((action) => {
        if (!isEmailAction(action)) {
            return action
        }
        const email = action.config.inputs?.email
        return {
            ...action,
            config: {
                ...action.config,
                inputs: {
                    ...action.config.inputs,
                    email: {
                        ...email,
                        value: { ...email?.value, to: { email: recipientEmail, name: '' }, cc: '', bcc: '' },
                    },
                },
            },
        }
    }),
})

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface testEmailRecipientLogicValues {
    user: UserType | null // userLogic
    emailAddressOverride: string | null
    storedEmailAddressOverride: StoredEmailAddressOverride | null
    testEmailAddress: string
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface testEmailRecipientLogicActions {
    setEmailAddressOverride: (email: string) => {
        email: string
    }
    storeEmailAddressOverride: (override: StoredEmailAddressOverride | null) => {
        override: StoredEmailAddressOverride | null
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface testEmailRecipientLogicMeta {
    __keaTypeGenInternalSelectorTypes: {
        emailAddressOverride: (storedEmailAddressOverride: any, user: any) => string | null
        testEmailAddress: (emailAddressOverride: any, user: any) => string
    }
}

export type testEmailRecipientLogicType = MakeLogicType<
    testEmailRecipientLogicValues,
    testEmailRecipientLogicActions,
    Record<string, any>,
    testEmailRecipientLogicMeta
>

export const testEmailRecipientLogic = kea<testEmailRecipientLogicType>([
    path(['products', 'workflows', 'frontend', 'Workflows', 'hogflows', 'panel', 'testing', 'testEmailRecipientLogic']),
    connect(() => ({
        values: [userLogic, ['user']],
    })),
    actions({
        setEmailAddressOverride: (email: string) => ({ email }),
        storeEmailAddressOverride: (override: StoredEmailAddressOverride | null) => ({ override }),
    }),
    reducers({
        storedEmailAddressOverride: [
            null as StoredEmailAddressOverride | null,
            { persist: true },
            {
                storeEmailAddressOverride: (_, { override }) => override,
            },
        ],
    }),
    selectors({
        // The browser keeps the address across sessions, so it only applies to the person who typed it.
        emailAddressOverride: [
            (s) => [s.storedEmailAddressOverride, s.user],
            (stored: StoredEmailAddressOverride | null, user: UserType | null): string | null =>
                stored && stored.userUuid === user?.uuid ? stored.email : null,
        ],
        testEmailAddress: [
            (s) => [s.emailAddressOverride, s.user],
            (emailAddressOverride: string | null, user: UserType | null): string =>
                emailAddressOverride ?? user?.email ?? '',
        ],
    }),
    listeners(({ actions, values }) => ({
        setEmailAddressOverride: ({ email }) => {
            actions.storeEmailAddressOverride(email && values.user ? { email, userUuid: values.user.uuid } : null)
        },
    })),
])
