from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Descriptions sourced from the Pipeliner CRM (Coevera) REST API OpenAPI spec and docs
# (https://developers.pipelinersales.com/api-docs).
_DOCS_URL = "https://developers.pipelinersales.com/api-docs/core-api-concepts/understanding-the-crm-concept"

_COMMON_COLUMNS = {
    "id": "Unique identifier of the entity (UUID).",
    "created": "Creation time (UTC).",
    "modified": "Last modification time (UTC).",
    "is_deleted": "Whether the entity is considered deleted.",
    "revision": "Revision when the entity was last changed.",
}

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "accounts": {
        "description": "Companies or organizations tracked in the CRM, including address, industry, and ownership details.",
        "docs_url": _DOCS_URL,
        "columns": {
            **_COMMON_COLUMNS,
            "name": "Name of the account and its default text representation.",
            "owner_id": "Id of the sales user who owns this account.",
            "account_type_id": "Id of the account type assigned to this account.",
            "customer_type_id": "Id of the customer category (e.g. Lead, Prospect, Customer).",
            "industry_id": "Id of the industry classification.",
            "email1": "Primary email address of the account.",
            "phone1": "Primary phone number of the account.",
            "home_page": "Website URL of the account.",
            "address": "Street address of the account.",
            "city": "City of the account address.",
            "state_province": "State or province of the account address.",
            "country": "Country of the account address.",
            "zip_code": "ZIP or postal code of the account address.",
            "parent_account_id": "Id of the parent account in a corporate hierarchy.",
            "unit_id": "Id of the sales unit this account is assigned to.",
            "is_archived": "True when the account has been archived.",
        },
    },
    "appointments": {
        "description": "Calendar appointments (meetings), including start/end times, location, and linked CRM records.",
        "docs_url": _DOCS_URL,
        "columns": {
            **_COMMON_COLUMNS,
            "subject": "Short summary line shown in calendars and lists.",
            "description": "Free-form description of the appointment.",
            "start_date": "Start timestamp of the appointment.",
            "end_date": "End timestamp of the appointment.",
            "duration": "Duration of the appointment, derived from start/end dates.",
            "location": "Free-text physical location of the appointment.",
            "organizer": "Email of the user organizing the appointment.",
            "owner_id": "Id of the sales user who owns this appointment.",
            "activity_type_id": "Id of the appointment type.",
            "status": "Current status of the appointment (NotStarted, InProgress, Completed, Canceled).",
            "unit_id": "Id of the sales unit this appointment is assigned to.",
            "recurrence_rule": "iCalendar RRULE string describing the recurrence pattern; empty for one-off appointments.",
        },
    },
    "clients": {
        "description": "Users of the Pipeliner team space (sales team members), including their role and sales unit membership.",
        "docs_url": _DOCS_URL,
        "columns": {
            **_COMMON_COLUMNS,
            "name": "Display name of the user.",
            "email": "Email address of the user.",
            "first_name": "First name of the user.",
            "last_name": "Last name of the user.",
            "position": "Job title or position of the user.",
            "master_right_id": "Id of the user role, determining what features and entities the user can access.",
            "default_unit_id": "Id of the user's default sales unit.",
            "last_active": "Timestamp of the user's most recent login or API request.",
            "timezone_name": "IANA timezone name from the user profile.",
        },
    },
    "contacts": {
        "description": "People who have a relation to an account, including contact details and their primary account link.",
        "docs_url": _DOCS_URL,
        "columns": {
            **_COMMON_COLUMNS,
            "first_name": "Given name of the contact.",
            "last_name": "Family name of the contact.",
            "formatted_name": "Display version of the contact name (title, first, middle, last).",
            "email1": "Primary email address of the contact.",
            "phone1": "Primary phone number of the contact.",
            "position": "Job title or position of the contact.",
            "owner_id": "Id of the sales user who owns this contact.",
            "contact_type_id": "Id of the contact type assigned to this contact.",
            "address": "Street address of the contact.",
            "city": "City of the contact address.",
            "state_province": "State or province of the contact address.",
            "country": "Country of the contact address.",
            "zip_code": "ZIP or postal code of the contact address.",
            "quick_account_name": "Free-text company name used when the contact is not linked to an Account record.",
            "unit_id": "Id of the sales unit this contact is assigned to.",
            "is_archived": "True when the contact has been archived.",
        },
    },
    "leads": {
        "description": "Potential deals before qualification, with source, ranking, process step, and close details.",
        "docs_url": _DOCS_URL,
        "columns": {
            **_COMMON_COLUMNS,
            "name": "Name of the lead and its default text representation.",
            "owner_id": "Id of the lead owner; may be empty when the lead is unassigned.",
            "lead_source_id": "Id of the lead source (how the lead originated, e.g. Website, Referral).",
            "lead_type_id": "Id of the lead type.",
            "step_id": "Id of the lead process step the lead is currently in.",
            "ranking": "Qualitative ranking score (1-10) indicating the strength of the lead.",
            "status": "Current status of the lead (Open, Lost, Qualified).",
            "is_archived": "True when the lead has been archived (lost).",
            "qualify_date": "Timestamp of when the lead was qualified; empty for unqualified leads.",
            "lost_date": "Timestamp of when the lead was archived (lost).",
            "reason_of_close_id": "Id of the reason recorded when the lead was archived (lost).",
            "unit_id": "Id of the sales unit this lead is assigned to.",
        },
    },
    "notes": {
        "description": "Free-form notes attached to accounts, contacts, leads, opportunities, projects, or quotes.",
        "docs_url": _DOCS_URL,
        "columns": {
            **_COMMON_COLUMNS,
            "note": "Free-form text body of the note (sanitized HTML allowed).",
            "owner_id": "Id of the user who authored the note.",
            "account_id": "Id of the account the note is attached to.",
            "contact_id": "Id of the contact the note is attached to.",
            "lead_oppty_id": "Id of the lead or opportunity the note is attached to.",
            "project_id": "Id of the project the note is attached to.",
            "quote_id": "Id of the quote the note is attached to.",
        },
    },
    "opportunities": {
        "description": "Existing or potential business revenue with a contact or account, moving through pipeline stages.",
        "docs_url": _DOCS_URL,
        "columns": {
            **_COMMON_COLUMNS,
            "name": "Name of the opportunity and its default text representation.",
            "owner_id": "Id of the sales user who owns this opportunity.",
            "oppty_type_id": "Id of the opportunity type; each type maps to one pipeline.",
            "step_id": "Id of the pipeline step the opportunity is currently in.",
            "value": "Monetary value of the opportunity in the team space base currency, with foreign value and currency code.",
            "closing_date": "Expected or actual closing date of the opportunity.",
            "status": "Current status of the opportunity (Open, Won, Lost).",
            "ranking": "Qualitative ranking score (1-10) indicating the strength of the opportunity.",
            "is_archived": "True when the opportunity has been archived (lost).",
            "was_qualified": "True when the opportunity has gone through the qualification step at least once.",
            "qualify_date": "Timestamp of when the opportunity was qualified.",
            "won_date": "Timestamp of when the opportunity was won.",
            "lost_date": "Timestamp of when the opportunity was archived (lost).",
            "reason_of_close_id": "Id of the reason recorded when the opportunity was archived (lost).",
            "lead_source_id": "Id of the lead source (how the opportunity originated).",
            "unit_id": "Id of the sales unit this opportunity is assigned to.",
        },
    },
    "pipelines": {
        "description": "Sales pipelines that opportunities move through, each composed of ordered steps.",
        "docs_url": _DOCS_URL,
        "columns": {
            **_COMMON_COLUMNS,
            "name": "Name of the pipeline and its default text representation.",
        },
    },
    "products": {
        "description": "Products from the catalog that can be attached to opportunities as line items.",
        "docs_url": _DOCS_URL,
        "columns": {
            **_COMMON_COLUMNS,
            "name": "Name of the product, shown in catalogs and pickers.",
            "description": "Free-form description of the product.",
            "sku": "Stock-keeping unit (SKU) identifier of the product; unique across products.",
            "product_category_id": "Id of the product category this product belongs to.",
            "product_type_id": "Id of the product type.",
            "unit_symbol": "Unit of measure shown next to product quantities (e.g. pcs, kg, hours).",
        },
    },
    "steps": {
        "description": "Individual stages within a sales pipeline or lead/quote process, with win probability and expected timeframe.",
        "docs_url": _DOCS_URL,
        "columns": {
            **_COMMON_COLUMNS,
            "name": "Name of the step and its default text representation.",
            "pipeline_id": "Id of the opportunity pipeline this step belongs to.",
            "lead_process_id": "Id of the lead process this step belongs to.",
            "percent": "Probability percent associated with the step (0-100) for opportunity pipeline steps.",
            "sort_order": "Position of the step within its pipeline or process; lower values appear first.",
            "timeframe": "Expected number of days a record should spend in this step.",
        },
    },
    "tasks": {
        "description": "To-do items and logged activities (e.g. tasks, calls), with due dates, priority, and linked CRM records.",
        "docs_url": _DOCS_URL,
        "columns": {
            **_COMMON_COLUMNS,
            "subject": "Short summary line shown in lists and notifications.",
            "description": "Free-form description of what the task entails.",
            "due_date": "Date by which the task is expected to be completed.",
            "start_date": "Date when work on the task is scheduled to begin.",
            "priority": "Priority level of the task (1 - Low, 2 - Medium, 3 - High, 4 - Urgent).",
            "status": "Current status of the task (NotStarted, InProgress, Completed, Deferred).",
            "owner_id": "Id of the task owner; may be empty when the task is unassigned.",
            "activity_type_id": "Id of the task type (e.g. Task, Call, Email).",
            "unit_id": "Id of the sales unit this task is assigned to.",
        },
    },
}
