from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Descriptions sourced from the official Tempo REST API v4 OpenAPI spec (https://apidocs.tempo.io).
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "worklogs": {
        "description": "Time logged against Jira issues: who worked, on what, when, and for how long.",
        "docs_url": "https://apidocs.tempo.io/#tag/Worklogs",
        "columns": {
            "tempoWorklogId": "The worklog id in the Tempo app.",
            "issue": "The Jira issue the time was logged against (self link and numeric issue id).",
            "author": "The Jira user who logged the time (account id and self link).",
            "timeSpentSeconds": "The total amount of time spent, in seconds.",
            "billableSeconds": "The amount of billable time, in seconds.",
            "startDate": "The start date of the worklog.",
            "startTime": "The start time of the worklog.",
            "startDateTimeUtc": "The start date and time of the worklog in UTC.",
            "description": "The description of the worklog.",
            "createdAt": "The date and time when this worklog was created.",
            "updatedAt": "The last date and time when this worklog was updated.",
            "attributes": "The work attribute values recorded on the worklog.",
            "self": "A permanent link to this resource.",
        },
    },
    "accounts": {
        "description": "Tempo accounts used to categorize logged time for billing and reporting.",
        "docs_url": "https://apidocs.tempo.io/#tag/Accounts",
        "columns": {
            "id": "The id of the account.",
            "key": "The key of the account.",
            "name": "The name of the account.",
            "status": "The status of the account (OPEN, CLOSED, or ARCHIVED).",
            "global": "Whether the account is a global account.",
            "monthlyBudget": "The estimated budget for the month.",
            "lead": "The Jira user who leads the account.",
            "contact": "The contact person for the account.",
            "customer": "The customer the account belongs to.",
            "category": "The category of the account.",
            "self": "A permanent link to this resource.",
        },
    },
    "customers": {
        "description": "Customers that Tempo accounts can be linked to.",
        "docs_url": "https://apidocs.tempo.io/#tag/Customers",
        "columns": {
            "id": "The id of the customer.",
            "key": "The key of the customer.",
            "name": "The name of the customer.",
            "self": "A permanent link to this resource.",
        },
    },
    "teams": {
        "description": "Tempo teams that group Jira users for planning and reporting.",
        "docs_url": "https://apidocs.tempo.io/#tag/Teams",
        "columns": {
            "id": "The id of the team.",
            "name": "The team's name.",
            "summary": "Brief description of the team.",
            "lead": "The Jira user who leads the team.",
            "program": "The program the team belongs to.",
            "administrative": "Whether this is an administrative team.",
            "public": "Whether this is a public team.",
            "members": "A link to the team's member list.",
            "self": "A permanent link to this resource.",
        },
    },
    "plans": {
        "description": "Resource allocations: planned time for a user or generic resource against an issue or project.",
        "docs_url": "https://apidocs.tempo.io/#tag/Plans",
        "columns": {
            "id": "The id of the plan.",
            "assignee": "The user or generic resource the time is planned for.",
            "planItem": "The issue or project the time is planned against.",
            "startDate": "The starting date of the plan.",
            "endDate": "The ending date of the plan.",
            "startTime": "The start time of the plan.",
            "plannedSecondsPerDay": "The amount of seconds planned daily when effortPersistenceType is SECONDS_PER_DAY.",
            "totalPlannedSeconds": "The total amount of seconds planned when effortPersistenceType is TOTAL_SECONDS.",
            "totalPlannedSecondsInScope": "The total amount of seconds planned within the queried date range.",
            "effortPersistenceType": "How the planned effort is stored: SECONDS_PER_DAY or TOTAL_SECONDS.",
            "includeNonWorkingDays": "Whether non-working days are included in the plan.",
            "rule": "Recurrence rule of the plan.",
            "recurrenceEndDate": "End date for recurrence of the plan.",
            "planApproval": "The approval status of the plan.",
            "planCreatorId": "The Jira user account id of the plan creator.",
            "syncSource": "JIRA_ISSUE if this is a synced plan, otherwise NONE.",
            "description": "A description containing details of the plan.",
            "createdAt": "Date and time the plan was created.",
            "updatedAt": "Date and time the plan was last updated.",
            "self": "A permanent link to this resource.",
        },
    },
    "workload_schemes": {
        "description": "Workload schemes defining required working hours per weekday for members.",
        "docs_url": "https://apidocs.tempo.io/#tag/Workload-Schemes",
        "columns": {
            "id": "The id of the workload scheme.",
            "name": "The name of the workload scheme.",
            "description": "The description of the workload scheme.",
            "days": "The list of days and their required hours in this workload scheme.",
            "defaultScheme": "Whether this is the default workload scheme.",
            "memberCount": "The number of members in this workload scheme.",
            "self": "A permanent link to this resource.",
        },
    },
    "holiday_schemes": {
        "description": "Holiday schemes defining the holidays that apply to their members.",
        "docs_url": "https://apidocs.tempo.io/#tag/Holiday-Schemes",
        "columns": {
            "id": "The id of the holiday scheme.",
            "name": "The name of the holiday scheme.",
            "description": "The description of the holiday scheme.",
            "defaultScheme": "Whether this is the default holiday scheme.",
            "memberCount": "The number of people working under this holiday scheme.",
            "self": "A permanent link to this resource.",
        },
    },
}
