from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "projects": {
        "description": "A Lightdash project: one dbt project connected to a warehouse, containing spaces, dashboards, and charts.",
        "docs_url": "https://docs.lightdash.com/api-reference/organizations/list-organization-projects",
        "columns": {
            "projectUuid": "Unique identifier for the project.",
            "name": "Display name of the project.",
            "type": "Project type, e.g. DEFAULT or PREVIEW.",
            "organizationUuid": "Unique identifier of the organization the project belongs to.",
            "createdAt": "Timestamp the project was created.",
            "createdByUserUuid": "Unique identifier of the user who created the project.",
            "createdByUserName": "Display name of the user who created the project.",
            "warehouseType": "The connected warehouse type, e.g. bigquery, snowflake, postgres, redshift, databricks.",
            "upstreamProjectUuid": "Unique identifier of the project this preview project was created from, if any.",
        },
    },
    "spaces": {
        "description": "A Lightdash space: a folder within a project that groups dashboards and charts, with its own access controls.",
        "docs_url": "https://docs.lightdash.com/api-reference/spaces/get-space",
        "columns": {
            "uuid": "Unique identifier for the space.",
            "name": "Display name of the space.",
            "slug": "URL-friendly identifier for the space.",
            "projectUuid": "Unique identifier of the project the space belongs to.",
            "organizationUuid": "Unique identifier of the organization the space belongs to.",
            "parentSpaceUuid": "Unique identifier of the parent space, for a nested space.",
            "path": "Slash-separated path of the space through its parent spaces.",
            "isPrivate": "Whether the space is private (only visible to users granted explicit access).",
            "dashboardCount": "Number of dashboards saved in the space.",
            "chartCount": "Number of charts saved in the space.",
            "childSpaceCount": "Number of nested spaces inside the space.",
        },
    },
    "dashboards": {
        "description": "A Lightdash dashboard: a saved collection of charts and other tiles arranged for viewing together.",
        "docs_url": "https://docs.lightdash.com/api-reference/projects/list-dashboards",
        "columns": {
            "uuid": "Unique identifier for the dashboard.",
            "name": "Display name of the dashboard.",
            "description": "Optional description of the dashboard.",
            "projectUuid": "Unique identifier of the project the dashboard belongs to.",
            "organizationUuid": "Unique identifier of the organization the dashboard belongs to.",
            "spaceUuid": "Unique identifier of the space the dashboard is saved in.",
            "updatedAt": "Timestamp the dashboard was last updated.",
            "views": "Number of times the dashboard has been viewed.",
            "firstViewedAt": "Timestamp the dashboard was first viewed, if ever.",
            "pinnedListUuid": "Unique identifier of the pinned list the dashboard belongs to, if pinned.",
            "tileTypes": "Kinds of tiles the dashboard contains, e.g. saved_chart, markdown, loom.",
        },
    },
    "charts": {
        "description": "A Lightdash saved chart: a query result visualization that can be added to one or more dashboards.",
        "docs_url": "https://docs.lightdash.com/api-reference/projects/list-charts-in-project",
        "columns": {
            "uuid": "Unique identifier for the chart.",
            "name": "Display name of the chart.",
            "description": "Optional description of the chart.",
            "slug": "URL-friendly identifier for the chart.",
            "projectUuid": "Unique identifier of the project the chart belongs to.",
            "organizationUuid": "Unique identifier of the organization the chart belongs to.",
            "spaceUuid": "Unique identifier of the space the chart is saved in.",
            "spaceName": "Display name of the space the chart is saved in.",
            "dashboardUuid": "Unique identifier of the dashboard the chart is embedded in, if any.",
            "dashboardName": "Display name of the dashboard the chart is embedded in, if any.",
            "source": "How the chart's query is defined: dbt_explore or sql.",
            "chartKind": "Visualization kind, e.g. line, bar, scatter, pie, table.",
            "chartType": "Underlying chart config type, e.g. cartesian, table, big_number, pie.",
            "updatedAt": "Timestamp the chart was last updated.",
            "views": "Number of times the chart has been viewed.",
            "firstViewedAt": "Timestamp the chart was first viewed, if ever.",
        },
    },
    "metrics_catalog": {
        "description": "An entry in a Lightdash project's data catalog: a metric or dimension field defined in the underlying dbt project, with its usage and ownership metadata.",
        "docs_url": "https://docs.lightdash.com/api-reference/catalog/list-metrics-in-catalog",
        "columns": {
            "catalogSearchUuid": "Unique identifier for the catalog entry.",
            "name": "Field name as defined in the dbt project.",
            "label": "Human-readable label for the field.",
            "description": "Optional description of the field, from the dbt project's metadata.",
            "tableName": "Name of the dbt model (table) the field belongs to.",
            "tableGroupLabel": "Group label of the table the field belongs to, if configured.",
            "fieldValueType": "The field's metric or dimension type, e.g. sum, average, string, date.",
            "basicType": "Simplified value type: string, number, date, timestamp, or boolean.",
            "type": "Whether the catalog entry is a metric, dimension, or table.",
            "chartUsage": "Number of charts that use this field.",
            "verifiedChartUsage": "Number of verified charts that use this field.",
            "tags": "Tags applied to the field in the underlying dbt project.",
        },
    },
    "org_users": {
        "description": "A member of the Lightdash organization, with their role and account status.",
        "docs_url": "https://docs.lightdash.com/api-reference/organizations/list-organization-members",
        "columns": {
            "userUuid": "Unique identifier for the user.",
            "firstName": "User's first name.",
            "lastName": "User's last name.",
            "email": "User's email address.",
            "organizationUuid": "Unique identifier of the organization the user belongs to.",
            "role": "Organization-level role, e.g. member, viewer, editor, developer, admin.",
            "isActive": "Whether the user has an active account.",
            "isPending": "Whether the user's invite is still pending.",
            "isInviteExpired": "Whether the user's invite link has expired.",
            "userCreatedAt": "Timestamp the user account was created.",
            "userUpdatedAt": "Timestamp the user account was last updated.",
        },
    },
}
