from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "bots": {
        "description": "A meeting bot sent to join and record a call. One row per bot, with its meeting URL, scheduled join time, status history, and references to the recordings it produced.",
        "docs_url": "https://docs.recall.ai/reference/bot_list",
        "columns": {
            "id": "Unique identifier for the bot.",
            "meeting_url": "The URL of the meeting the bot joined. Cleared by Recall.ai a few days after the bot has joined a call.",
            "bot_name": "The display name the bot used in the call.",
            "join_at": "The time the bot was scheduled to join the call. For ad-hoc bots, the time the bot was requested to join.",
            "status_changes": "History of the bot's lifecycle states (joining, in call, done, fatal), each with a timestamp.",
            "recordings": "Recordings produced by this bot, referencing rows in the recordings table.",
            "calendar_meetings": "Calendar meetings associated with this bot when it was dispatched via the Calendar V1 integration.",
            "metadata": "Arbitrary key-value metadata attached to the bot at creation.",
        },
    },
    "recordings": {
        "description": "A recording captured by a meeting bot or uploaded through the desktop SDK. One row per recording, with its processing status and shortcuts to the media artifacts produced from it.",
        "docs_url": "https://docs.recall.ai/reference/recording_list",
        "columns": {
            "id": "Unique identifier for the recording.",
            "created_at": "When the recording object was created.",
            "started_at": "When capture started, or null if it never started.",
            "completed_at": "When capture finished, or null while still recording.",
            "status": "Processing status of the recording (processing, paused, done, failed).",
            "media_shortcuts": "Latest artifact per media type (video, audio, transcript, participant events) with temporary download URLs.",
            "bot": "The bot that produced this recording, or null for desktop SDK uploads.",
            "desktop_sdk_upload": "The desktop SDK upload that produced this recording, or null for bot recordings.",
            "expires_at": "When Recall.ai deletes the recording's media.",
            "metadata": "Arbitrary key-value metadata attached to the recording.",
        },
    },
    "transcripts": {
        "description": "Transcript artifacts generated from recordings. Rows carry the transcript's status and a temporary download URL for the transcript content, not the transcript text itself.",
        "docs_url": "https://docs.recall.ai/reference/transcript_list",
        "columns": {
            "id": "Unique identifier for the transcript artifact.",
            "recording": "The recording this transcript was generated from.",
            "created_at": "When the transcript artifact was created.",
            "status": "Processing status of the transcript (processing, done, failed).",
            "data": "Temporary download URL for the transcript content. URLs expire and must be re-fetched from the API.",
            "provider": "The speech-to-text provider that produced the transcript.",
            "diarization": "Speaker diarization configuration used for the transcript.",
        },
    },
    "participant_events": {
        "description": "Participant event artifacts generated from recordings, covering joins, leaves, active speakers, and chat. Rows carry a temporary download URL for the event log, not the events themselves.",
        "docs_url": "https://docs.recall.ai/reference/participant_events_list",
        "columns": {
            "id": "Unique identifier for the participant events artifact.",
            "recording": "The recording this artifact was generated from.",
            "created_at": "When the artifact was created.",
            "status": "Processing status of the artifact (processing, done, failed).",
            "data": "Temporary download URLs for the participant event logs. URLs expire and must be re-fetched from the API.",
        },
    },
    "meeting_metadata": {
        "description": "Meeting metadata artifacts generated from recordings, such as the meeting title and platform details. Rows carry a temporary download URL for the metadata payload.",
        "docs_url": "https://docs.recall.ai/reference/meeting_metadata_list",
        "columns": {
            "id": "Unique identifier for the meeting metadata artifact.",
            "recording": "The recording this artifact was generated from.",
            "created_at": "When the artifact was created.",
            "status": "Processing status of the artifact (processing, done, failed).",
            "data": "Temporary download URL for the meeting metadata payload.",
        },
    },
    "calendars": {
        "description": "Calendar accounts connected through the Calendar V2 integration. One row per connected Google Calendar or Microsoft Outlook account. OAuth client secrets and refresh tokens are removed before rows reach the warehouse.",
        "docs_url": "https://docs.recall.ai/reference/calendars_list",
        "columns": {
            "id": "Unique identifier for the connected calendar.",
            "platform": "The calendar provider (google_calendar or microsoft_outlook).",
            "oauth_client_id": "OAuth client ID of the app the calendar was connected with.",
            "oauth_email": "Email address of the account that authorized the connection.",
            "platform_email": "Email address of the calendar on the provider's side.",
            "status": "Connection status (connecting, connected, disconnected).",
            "status_changes": "History of connection status changes.",
            "created_at": "When the calendar was connected.",
            "updated_at": "When the calendar record last changed.",
        },
    },
    "calendar_events": {
        "description": "Events synced from connected calendars through the Calendar V2 integration. One row per calendar event, including the detected meeting URL and any bots scheduled for it.",
        "docs_url": "https://docs.recall.ai/reference/calendar_events_list",
        "columns": {
            "id": "Unique identifier for the calendar event.",
            "start_time": "When the event starts.",
            "end_time": "When the event ends.",
            "calendar_id": "The connected calendar this event belongs to.",
            "raw": "The raw event payload from the calendar provider.",
            "platform": "The calendar provider the event came from.",
            "platform_id": "The event's identifier on the provider's side.",
            "ical_uid": "The event's iCalendar UID.",
            "meeting_platform": "The meeting platform detected from the event (zoom, google_meet, microsoft_teams, and others).",
            "meeting_url": "The meeting URL detected in the event.",
            "created_at": "When the event was first synced from the provider.",
            "updated_at": "When the event last changed.",
            "is_deleted": "Whether the event has been deleted on the provider's side.",
            "bots": "Bots scheduled to record this event.",
        },
    },
}
