from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "Projects": {
        "description": "A jobsite or work location where photos, videos, and documents are organized.",
        "docs_url": "https://docs.companycam.com/reference/listprojects",
        "columns": {
            "id": "A unique identifier for the Project.",
            "company_id": "A unique identifier for the Company the Project belongs to.",
            "creator_id": "The id of the entity that created the Project.",
            "creator_type": "The type of the entity that created the Project.",
            "creator_name": "The display name of the entity that created the Project.",
            "status": "Indicates the status of the Project (active or deleted).",
            "archived": "Indicates whether the Project is archived.",
            "name": "The title of the Project.",
            "project_url": "The URL to the Project in the web app.",
            "embedded_project_url": "The URL to an embeddable photo feed for the Project.",
            "slug": "A unique identifier for the Project used to construct some public URLs.",
            "public": "Indicates whether the Project's timeline and other public features are enabled.",
            "notepad": "Notes or description of the project.",
            "created_at": "Timestamp when the Project was created.",
            "updated_at": "Timestamp when the Project was updated.",
        },
    },
    "Photos": {
        "description": "A photo captured at a Project, with metadata and links to the image assets.",
        "docs_url": "https://docs.companycam.com/reference/listphotos",
        "columns": {
            "id": "The unique ID for the photo.",
            "company_id": "A unique identifier for the Company the Photo belongs to.",
            "creator_id": "The id of the entity that created the Photo.",
            "creator_type": "The type of the entity that created the Photo.",
            "creator_name": "The display name of the entity that created the Photo.",
            "project_id": "The unique ID of the project the Photo was captured at.",
            "processing_status": "Indicates the Photo's processing status.",
            "status": "The status of the Photo (active or deleted).",
            "hash": "The MD5 hash of the photo.",
            "description": "A description of the photo.",
            "internal": "Indicates whether the photo is for internal use only.",
            "photo_url": "The link to the photo in the web app.",
            "captured_at": "Timestamp when the Photo was captured.",
            "created_at": "Timestamp when the photo was created on the server. May differ from captured_at.",
            "updated_at": "Timestamp when the photo was last updated.",
        },
    },
    "Videos": {
        "description": "A video captured at a Project, with metadata and a link to the playback URL.",
        "docs_url": "https://docs.companycam.com/reference/listvideos",
        "columns": {
            "id": "The unique ID for the video.",
            "company_id": "A unique identifier for the Company the Video belongs to.",
            "creator_id": "The id of the entity that created the Video.",
            "creator_type": "The type of the entity that created the Video.",
            "creator_name": "The display name of the entity that created the Video.",
            "project_id": "The unique ID of the project the Video was captured at.",
            "status": "The video's processing status.",
            "internal": "Indicates whether the video is for internal use only.",
            "captured_at": "Unix timestamp when the Video was captured.",
            "created_at": "Unix timestamp when the video record was created on the server.",
            "updated_at": "Unix timestamp when the video was last updated.",
            "playback_url": "The HLS manifest URL once processed, or the raw upload URL before that.",
            "format": "The video format, e.g. m3u8 once processed.",
            "duration": "Length of the video in seconds.",
        },
    },
    "Users": {
        "description": "A user (team member) on the CompanyCam account.",
        "docs_url": "https://docs.companycam.com/reference/listusers",
        "columns": {
            "id": "A unique identifier for the User.",
            "company_id": "A unique identifier for the Company the User belongs to.",
            "email_address": "The User's email address.",
            "status": "Indicates the status of the User (active or deleted).",
            "first_name": "The User's first name.",
            "last_name": "The User's last name.",
            "phone_number": "The User's phone number.",
            "created_at": "Timestamp when the User was created.",
            "updated_at": "Timestamp when the User was last updated.",
            "user_url": "The link to the user in the web app.",
        },
    },
    "Tags": {
        "description": "A label that can be applied to photos or videos for organization and search.",
        "docs_url": "https://docs.companycam.com/reference/listtags",
        "columns": {
            "id": "A unique ID for the Tag.",
            "company_id": "A unique ID for the Company the Tag belongs to.",
            "display_value": "The display value of the Tag, used to display to the user.",
            "value": "The lowercase version of display_value, useful for searching and sorting.",
            "created_at": "Timestamp when the Tag was created on the server.",
            "updated_at": "Timestamp when the Tag was last updated.",
        },
    },
    "Groups": {
        "description": "A group of users on the CompanyCam account, e.g. a crew.",
        "docs_url": "https://docs.companycam.com/reference/listgroups",
        "columns": {
            "id": "A unique ID for the Group.",
            "company_id": "A unique ID for the Company the Group belongs to.",
            "name": "The title of the Group.",
            "status": "Indicates the status of the Group (active or deleted).",
            "group_url": "The link to the group in the web app.",
            "created_at": "Timestamp when the Group was created on the server.",
            "updated_at": "Timestamp when the Group was last updated.",
        },
    },
    "Checklists": {
        "description": "A checklist filled out at a Project, optionally created from a ChecklistTemplate.",
        "docs_url": "https://docs.companycam.com/reference/listchecklists",
        "columns": {
            "id": "The unique ID for the Checklist.",
            "company_id": "A unique identifier for the Company the Checklist belongs to.",
            "project_id": "A unique identifier for the Project the Checklist belongs to.",
            "name": "The name for the Checklist.",
            "created_at": "Timestamp when the Checklist was created on the server.",
            "updated_at": "Timestamp when the Checklist was last updated.",
            "completed_at": "Timestamp when the Checklist was completed.",
            "creator_id": "A unique identifier for the creator of the Checklist.",
            "checklist_template_id": "A unique identifier for the template used to create the Checklist.",
            "is_populating": "Flag indicating whether the Checklist is still being created.",
        },
    },
    "ChecklistTemplates": {
        "description": "A reusable checklist template that can be used to create Checklists on Projects.",
        "docs_url": "https://docs.companycam.com/reference/listchecklisttemplates",
        "columns": {
            "id": "The unique ID for the ChecklistTemplate.",
            "company_id": "A unique identifier for the Company the ChecklistTemplate belongs to.",
            "name": "The name for the ChecklistTemplate.",
            "description": "The description for the ChecklistTemplate.",
            "created_at": "Timestamp when the ChecklistTemplate was created on the server.",
            "updated_at": "Timestamp when the ChecklistTemplate was last updated.",
        },
    },
}
