"""Canonical, documentation-sourced descriptions for Stripe endpoints and columns.

Sourced from the official Stripe API reference (https://stripe.com/docs/api). Keyed by the resource
names in `constants.py` / `settings.py` `ENDPOINTS`, which match the `ExternalDataSchema.name` of a
synced Stripe table. Covers every endpoint Stripe exposes for sync; a coverage test keeps this in
lockstep with `ENDPOINTS`. Columns absent here fall back to LLM enrichment.
"""

from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)
from products.warehouse_sources.backend.temporal.data_imports.sources.stripe.constants import (
    BALANCE_TRANSACTION_RESOURCE_NAME,
    CHARGE_RESOURCE_NAME,
    COUPON_RESOURCE_NAME,
    CREDIT_NOTE_RESOURCE_NAME,
    CUSTOMER_BALANCE_TRANSACTION_RESOURCE_NAME,
    CUSTOMER_PAYMENT_METHOD_RESOURCE_NAME,
    CUSTOMER_RESOURCE_NAME,
    DISCOUNT_RESOURCE_NAME,
    DISPUTE_RESOURCE_NAME,
    INVOICE_ITEM_RESOURCE_NAME,
    INVOICE_RESOURCE_NAME,
    PAYOUT_RESOURCE_NAME,
    PRICE_RESOURCE_NAME,
    PRODUCT_RESOURCE_NAME,
    REFUND_RESOURCE_NAME,
    SUBSCRIPTION_RESOURCE_NAME,
)

# Common Stripe fields shared by most objects; merged into each entry so we don't repeat them.
_COMMON_COLUMNS = {
    "id": "Unique identifier for the object.",
    "object": "String describing the object's Stripe type (e.g. 'charge', 'customer').",
    "created": "Time at which the object was created, as a Unix timestamp.",
    "livemode": "Whether the object exists in live mode (true) or test mode (false).",
    "metadata": "Set of key-value pairs you can attach to the object for your own bookkeeping.",
}


def _columns(**overrides: str) -> dict[str, str]:
    return {**_COMMON_COLUMNS, **overrides}


CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    CHARGE_RESOURCE_NAME: {
        "description": "A single attempt to move money into your Stripe account by charging a payment source.",
        "docs_url": "https://stripe.com/docs/api/charges",
        "columns": _columns(
            amount="Amount intended to be collected by this charge, in the smallest currency unit (e.g. cents).",
            amount_captured="Amount actually captured from the charge, in the smallest currency unit.",
            amount_refunded="Amount refunded from the charge, in the smallest currency unit.",
            currency="Three-letter ISO currency code of the charge, in lowercase.",
            customer="ID of the customer this charge is for, if one exists.",
            paid="Whether the charge has been fully paid.",
            refunded="Whether the charge has been fully refunded.",
            status="Status of the payment: succeeded, pending, or failed.",
            payment_intent="ID of the PaymentIntent associated with this charge, if any.",
            payment_method="ID of the payment method used in this charge.",
            description="Arbitrary free-form description attached to the charge.",
            invoice="ID of the invoice this charge is for, if one exists.",
            captured="Whether the charge has been captured (uncaptured charges expire after a set number of days).",
            disputed="Whether the charge has been disputed.",
            failure_code="Error code explaining the reason for a failed charge, if applicable.",
            failure_message="Human-readable message explaining the reason for a failed charge, if applicable.",
            receipt_email="Email address to which the charge's receipt is sent.",
            dispute="ID of the dispute associated with the charge, if one exists.",
            shipping="Shipping information (recipient, address, carrier) for the charge.",
            source="The payment source (e.g. card) that was charged; this legacy field is being deprecated in favor of payment_method.",
        ),
    },
    CUSTOMER_RESOURCE_NAME: {
        "description": "A Stripe customer, allowing recurring charges and tracking of payments belonging to the same person.",
        "docs_url": "https://stripe.com/docs/api/customers",
        "columns": _columns(
            email="Customer's email address.",
            name="Customer's full name or business name.",
            currency="Three-letter ISO code for the currency the customer can be charged in for recurring billing.",
            description="Arbitrary free-form description attached to the customer.",
            balance="Current balance, if any, stored on the customer (negative = credit toward future invoices).",
            delinquent="Whether the latest charge for the customer's subscription has failed.",
            phone="Customer's phone number.",
            default_source="ID of the default payment source for the customer.",
            invoice_prefix="Prefix for the customer used to generate unique invoice numbers.",
            tax_exempt="The customer's tax exemption status: none, exempt, or reverse.",
        ),
    },
    INVOICE_RESOURCE_NAME: {
        "description": "A statement of amounts owed by a customer, generated for subscriptions or one-off billing.",
        "docs_url": "https://stripe.com/docs/api/invoices",
        "columns": _columns(
            customer="ID of the customer this invoice belongs to.",
            subscription="ID of the subscription this invoice was prepared for, if any.",
            status="Status of the invoice: draft, open, paid, uncollectible, or void.",
            currency="Three-letter ISO currency code of the invoice, in lowercase.",
            amount_due="Final amount due at this time for this invoice, in the smallest currency unit.",
            amount_paid="Amount that was paid on this invoice, in the smallest currency unit.",
            amount_remaining="Amount remaining to be paid on this invoice, in the smallest currency unit.",
            total="Total of all line items and discounts on the invoice, in the smallest currency unit.",
            subtotal="Total before any discounts or taxes are applied, in the smallest currency unit.",
            due_date="Date on which payment for this invoice is due, as a Unix timestamp.",
            paid="Whether the invoice has been paid.",
            number="Unique, user-facing reference number assigned to the invoice.",
            period_start="Start of the billing period covered by this invoice, as a Unix timestamp.",
            period_end="End of the billing period covered by this invoice, as a Unix timestamp.",
            amount_shipping="Total amount of shipping charged on the invoice, in the smallest currency unit.",
            default_source="ID of the default payment source used to pay this invoice, if set.",
            subtotal_excluding_tax="Subtotal of the invoice excluding tax, in the smallest currency unit.",
        ),
    },
    INVOICE_ITEM_RESOURCE_NAME: {
        "description": "A one-off charge or credit added to a customer's upcoming invoice.",
        "docs_url": "https://stripe.com/docs/api/invoiceitems",
        "columns": _columns(
            amount="Amount of the invoice item, in the smallest currency unit.",
            currency="Three-letter ISO currency code of the invoice item, in lowercase.",
            customer="ID of the customer the invoice item belongs to.",
            description="Free-form description that appears as a line item on the invoice.",
            invoice="ID of the invoice this item is attached to, if any.",
            price="ID of the price object this invoice item is based on.",
            proration="Whether the invoice item was created automatically as a proration adjustment.",
            quantity="Quantity of units for the invoice item.",
            subscription="ID of the subscription this invoice item was created for, if any.",
            unit_amount="Per-unit amount of the invoice item, in the smallest currency unit.",
            date="Date the invoice item was created, as a Unix timestamp.",
            subscription_item="ID of the subscription item this invoice item is associated with, if any.",
        ),
    },
    SUBSCRIPTION_RESOURCE_NAME: {
        "description": "A customer's recurring billing arrangement against one or more prices.",
        "docs_url": "https://stripe.com/docs/api/subscriptions",
        "columns": _columns(
            customer="ID of the customer who owns the subscription.",
            status="Status of the subscription: trialing, active, past_due, canceled, unpaid, or incomplete.",
            current_period_start="Start of the current billing period, as a Unix timestamp.",
            current_period_end="End of the current billing period — the next time the subscription bills, as a Unix timestamp.",
            start_date="Date when the subscription was first created, as a Unix timestamp.",
            canceled_at="Time at which the subscription was canceled, as a Unix timestamp, if applicable.",
            cancel_at_period_end="Whether the subscription will be canceled at the end of the current period.",
            currency="Three-letter ISO currency code the subscription bills in, in lowercase.",
            trial_start="Start of the subscription's trial period, as a Unix timestamp, if any.",
            trial_end="End of the subscription's trial period, as a Unix timestamp, if any.",
            application="ID of the Connect application that created the subscription, if any.",
        ),
    },
    PRODUCT_RESOURCE_NAME: {
        "description": "A good or service that you sell, which prices are attached to.",
        "docs_url": "https://stripe.com/docs/api/products",
        "columns": _columns(
            name="The product's name, shown to customers at checkout and on invoices.",
            description="The product's description, shown to customers at checkout and on invoices.",
            active="Whether the product is currently available for purchase.",
            updated="Time at which the product was last updated, as a Unix timestamp.",
            default_price="ID of the default price this product is sold at, if set.",
        ),
    },
    PRICE_RESOURCE_NAME: {
        "description": "How much and how often to charge for a product — its unit cost, currency, and billing interval.",
        "docs_url": "https://stripe.com/docs/api/prices",
        "columns": _columns(
            product="ID of the product this price is for.",
            currency="Three-letter ISO currency code the price is set in, in lowercase.",
            unit_amount="Amount charged per unit, in the smallest currency unit (e.g. cents).",
            active="Whether the price can be used for new purchases.",
            type="Whether the price is for a one_time purchase or a recurring subscription.",
            nickname="Brief internal description of the price, not shown to customers.",
            lookup_key="A lookup key used to retrieve the price dynamically from a static string.",
        ),
    },
    BALANCE_TRANSACTION_RESOURCE_NAME: {
        "description": "A change to your Stripe account balance — a charge, refund, payout, or fee.",
        "docs_url": "https://stripe.com/docs/api/balance_transactions",
        "columns": _columns(
            amount="Gross amount of the transaction, in the smallest currency unit.",
            net="Net amount of the transaction after fees, in the smallest currency unit.",
            fee="Fees (in the smallest currency unit) taken from this transaction.",
            currency="Three-letter ISO currency code of the transaction, in lowercase.",
            type="Transaction type (e.g. charge, refund, payout, adjustment, stripe_fee).",
            status="Status of the transaction: available or pending.",
            available_on="Time at which the funds become available in the balance, as a Unix timestamp.",
            source="ID of the Stripe object (charge, refund, payout, …) that caused this transaction.",
        ),
    },
    DISPUTE_RESOURCE_NAME: {
        "description": "A customer's challenge of a charge with their card issuer (a chargeback) and its resolution.",
        "docs_url": "https://stripe.com/docs/api/disputes",
        "columns": _columns(
            amount="Disputed amount, in the smallest currency unit (may be less than the original charge).",
            currency="Three-letter ISO currency code of the dispute, in lowercase.",
            charge="ID of the charge that was disputed.",
            payment_intent="ID of the PaymentIntent that was disputed, if any.",
            status="Dispute status (e.g. warning_needs_response, needs_response, under_review, won, lost).",
            reason="Reason given for the dispute (e.g. fraudulent, duplicate, product_not_received).",
            is_charge_refundable="Whether the disputed charge can still be refunded.",
        ),
    },
    REFUND_RESOURCE_NAME: {
        "description": "A refund of all or part of a charge back to the customer.",
        "docs_url": "https://stripe.com/docs/api/refunds",
        "columns": _columns(
            amount="Amount refunded, in the smallest currency unit.",
            currency="Three-letter ISO currency code of the refund, in lowercase.",
            charge="ID of the charge that was refunded.",
            payment_intent="ID of the PaymentIntent that was refunded, if any.",
            status="Status of the refund: pending, succeeded, failed, or canceled.",
            reason="Reason for the refund (duplicate, fraudulent, or requested_by_customer).",
            receipt_number="Transaction number that appears on email receipts for the refund.",
        ),
    },
    PAYOUT_RESOURCE_NAME: {
        "description": "A transfer of funds from your Stripe balance to your bank account or debit card.",
        "docs_url": "https://stripe.com/docs/api/payouts",
        "columns": _columns(
            amount="Amount paid out, in the smallest currency unit.",
            currency="Three-letter ISO currency code of the payout, in lowercase.",
            arrival_date="Date the payout is expected to arrive in the bank, as a Unix timestamp.",
            status="Status of the payout: paid, pending, in_transit, canceled, or failed.",
            method="Whether the payout is standard or instant.",
            type="Type of destination: bank_account or card.",
            automatic="Whether the payout was created automatically by Stripe's schedule.",
            description="Free-form description attached to the payout.",
            failure_code="Error code explaining why the payout failed, if applicable.",
            failure_message="Human-readable message explaining why the payout failed, if applicable.",
            balance_transaction="ID of the balance transaction that describes the impact of this payout on your account balance.",
        ),
    },
    CREDIT_NOTE_RESOURCE_NAME: {
        "description": "An adjustment to an issued invoice that reduces the amount owed or refunds the customer.",
        "docs_url": "https://stripe.com/docs/api/credit_notes",
        "columns": _columns(
            amount="Total amount of the credit note, in the smallest currency unit.",
            currency="Three-letter ISO currency code of the credit note, in lowercase.",
            customer="ID of the customer the credit note is for.",
            invoice="ID of the invoice the credit note adjusts.",
            status="Status of the credit note: issued or void.",
            number="Unique, user-facing reference number for the credit note.",
            reason="Reason for the credit note (duplicate, fraudulent, order_change, product_unsatisfactory).",
            type="Whether the credit note was issued pre_payment or post_payment.",
            total="Total amount of the credit note including tax, in the smallest currency unit.",
            memo="Free-form memo shown to the customer on the credit note.",
            post_payment_amount="Amount of the credit note that was issued after payment and refunded to the customer, in the smallest currency unit.",
        ),
    },
    CUSTOMER_BALANCE_TRANSACTION_RESOURCE_NAME: {
        "description": "An adjustment to a single customer's credit balance (used toward or away from future invoices).",
        "docs_url": "https://stripe.com/docs/api/customer_balance_transactions",
        "columns": _columns(
            amount="Amount of the transaction, in the smallest currency unit (negative reduces what the customer owes).",
            currency="Three-letter ISO currency code of the transaction, in lowercase.",
            customer="ID of the customer whose balance changed.",
            type="Reason for the balance change (e.g. adjustment, applied_to_invoice, credit_note, initial).",
            description="Free-form description of the balance transaction.",
            ending_balance="The customer's balance after this transaction, in the smallest currency unit.",
            invoice="ID of the invoice this transaction was applied to, if any.",
            checkout_session="ID of the Checkout Session that created this balance transaction, if any.",
        ),
    },
    CUSTOMER_PAYMENT_METHOD_RESOURCE_NAME: {
        "description": "A saved payment method (card, bank account, …) attached to a customer.",
        "docs_url": "https://stripe.com/docs/api/payment_methods",
        "columns": _columns(
            customer="ID of the customer this payment method is attached to.",
            type="Type of the payment method (e.g. card, sepa_debit, us_bank_account).",
            card="Details of the card if the payment method is a card (brand, last4, expiry).",
            billing_details="Billing information (name, email, address) associated with the payment method.",
        ),
    },
    COUPON_RESOURCE_NAME: {
        "description": "A discount you can apply to customers, invoices, or subscriptions.",
        "docs_url": "https://stripe.com/docs/api/coupons",
        "columns": _columns(
            name="Name of the coupon shown to customers on invoices and receipts.",
            amount_off="Fixed amount discounted, in the smallest currency unit (mutually exclusive with percent_off).",
            percent_off="Percentage discounted off the invoice (mutually exclusive with amount_off).",
            currency="Three-letter ISO currency code for amount_off, in lowercase.",
            duration="How long the discount lasts: forever, once, or repeating.",
            duration_in_months="Number of months the discount applies when duration is repeating.",
            max_redemptions="Maximum number of times the coupon can be redeemed in total.",
            times_redeemed="Number of times the coupon has already been applied.",
            valid="Whether the coupon can still be applied to new customers.",
            redeem_by="Date after which the coupon can no longer be redeemed, as a Unix timestamp.",
        ),
    },
    DISCOUNT_RESOURCE_NAME: {
        "description": "An applied coupon — the link between a coupon and the customer, subscription, or invoice it discounts.",
        "docs_url": "https://stripe.com/docs/api/discounts",
        "columns": _columns(
            coupon="The coupon object applied to create this discount.",
            customer="ID of the customer this discount applies to, if any.",
            subscription="ID of the subscription this discount applies to, if any.",
            invoice="ID of the invoice this discount applies to, if any.",
            promotion_code="ID of the promotion code that was redeemed to create this discount, if any.",
            start="Date the discount began, as a Unix timestamp.",
            end="Date the discount will end, as a Unix timestamp, if it is time-limited.",
        ),
    },
}
