from products.growth.backend.temporal.sdk_version_snapshot import (
    ACTIVITIES as SDK_VERSION_SNAPSHOT_ACTIVITIES,
    WORKFLOWS as SDK_VERSION_SNAPSHOT_WORKFLOWS,
)

WORKFLOWS = SDK_VERSION_SNAPSHOT_WORKFLOWS
ACTIVITIES = SDK_VERSION_SNAPSHOT_ACTIVITIES
