"""Canonical, documentation-sourced descriptions for Azure DevOps endpoints and columns.

Sourced from the official Azure DevOps REST API reference (https://learn.microsoft.com/en-us/rest/api/azure/devops).
Keyed by the endpoint names in `settings.py` `AZURE_DEVOPS_ENDPOINTS`, which match the
`ExternalDataSchema.name` of a synced Azure DevOps table. Columns absent here fall back to LLM enrichment.
"""

from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "projects": {
        "description": "A team project in the Azure DevOps organization — a container for repos, builds, and work items.",
        "docs_url": "https://learn.microsoft.com/en-us/rest/api/azure/devops/core/projects/list",
        "columns": {
            "id": "Unique identifier for the project.",
            "name": "Name of the project.",
            "description": "Description of the project.",
            "url": "API URL of the project.",
            "state": "State of the project (e.g. wellFormed, createPending, deleting).",
            "revision": "Revision number of the project, incremented on each change.",
            "visibility": "Visibility of the project (private or public).",
            "lastUpdateTime": "Time at which the project was last updated.",
        },
    },
    "repositories": {
        "description": "A Git repository within an Azure DevOps project.",
        "docs_url": "https://learn.microsoft.com/en-us/rest/api/azure/devops/git/repositories/list",
        "columns": {
            "id": "Unique identifier for the repository.",
            "name": "Name of the repository.",
            "url": "API URL of the repository.",
            "project": "The project the repository belongs to.",
            "defaultBranch": "The repository's default branch (e.g. refs/heads/main).",
            "size": "Size of the repository in bytes.",
            "remoteUrl": "HTTPS clone URL of the repository.",
            "sshUrl": "SSH clone URL of the repository.",
            "webUrl": "URL of the repository in the Azure DevOps web UI.",
            "isDisabled": "Whether the repository is disabled.",
        },
    },
    "builds": {
        "description": "A build run produced by a build pipeline in Azure DevOps.",
        "docs_url": "https://learn.microsoft.com/en-us/rest/api/azure/devops/build/builds/list",
        "columns": {
            "id": "Unique identifier for the build.",
            "buildNumber": "Human-readable build number.",
            "status": "Status of the build (e.g. inProgress, completed, cancelling, notStarted).",
            "result": "Result of a completed build (e.g. succeeded, failed, canceled, partiallySucceeded).",
            "queueTime": "Time at which the build was queued.",
            "startTime": "Time at which the build started running.",
            "finishTime": "Time at which the build finished.",
            "sourceBranch": "The branch the build was run against.",
            "sourceVersion": "The commit the build was run against.",
            "definition": "The build pipeline definition that produced the build.",
            "project": "The project the build belongs to.",
            "requestedFor": "The identity the build was requested for.",
            "reason": "Reason the build was triggered (e.g. manual, individualCI, schedule).",
        },
    },
    "pull_requests": {
        "description": "A Git pull request in Azure DevOps.",
        "docs_url": "https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pull-requests/get-pull-requests-by-project",
        "columns": {
            "pullRequestId": "Unique identifier for the pull request.",
            "title": "Title of the pull request.",
            "description": "Description of the pull request.",
            "status": "Status of the pull request (active, abandoned, or completed).",
            "createdBy": "The identity that created the pull request.",
            "creationDate": "Time at which the pull request was created.",
            "closedDate": "Time at which the pull request was closed.",
            "sourceRefName": "The source branch of the pull request.",
            "targetRefName": "The target branch of the pull request.",
            "mergeStatus": "Status of the merge of the source into the target branch.",
            "isDraft": "Whether the pull request is a draft.",
            "repository": "The repository the pull request belongs to.",
        },
    },
    "commits": {
        "description": "A Git commit reachable from a repository in an Azure DevOps project.",
        "docs_url": "https://learn.microsoft.com/en-us/rest/api/azure/devops/git/commits/get-commits",
        "columns": {
            "commitId": "ID (SHA-1) of the commit.",
            "comment": "Comment or message of the commit.",
            "commentTruncated": "Whether the comment is truncated from the full commit message.",
            "author": "Author of the commit, with name, email and authored date.",
            "committer": "Committer of the commit, with name, email and commit date.",
            "committer_date": "Time at which the commit was committed, lifted from the committer object.",
            "parents": "Commit IDs of this commit's parents.",
            "changeCounts": "Counts of the types of changes (edits, deletes, adds) in the commit.",
            "remoteUrl": "URL of the commit in the Azure DevOps web UI.",
            "url": "API URL of the commit.",
            "repository_id": "Identifier of the repository the commit was read from.",
            "repository_name": "Name of the repository the commit was read from.",
            "project_name": "Name of the project the repository belongs to.",
        },
    },
    "pull_request_threads": {
        "description": "A comment thread on a pull request, covering both reviewer discussion and the system events Azure DevOps records as threads (votes, reviewer changes, merge attempts).",
        "docs_url": "https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pull-request-threads/list",
        "columns": {
            "id": "The comment thread ID. Unique within its pull request.",
            "status": "Status of the thread (unknown, active, fixed, wontFix, closed, byDesign, pending).",
            "publishedDate": "Time at which the thread was published.",
            "lastUpdatedDate": "Time at which the thread was last updated.",
            "isDeleted": "Whether the thread is deleted, which happens when all its comments are deleted.",
            "comments": "The comments in the thread. Also synced as their own table.",
            "threadContext": "File path and line positions the thread was left on, for threads on code.",
            "pullRequestThreadContext": "Which diff iterations were being viewed when the thread was created.",
            "properties": "Key-value properties Azure DevOps attaches to the thread, including the thread type for system threads.",
            "identities": "Identities referenced by the thread.",
            "repository_id": "Identifier of the repository the pull request targets.",
            "pull_request_id": "Identifier of the pull request the thread belongs to.",
            "project_name": "Name of the project the pull request belongs to.",
        },
    },
    "pull_request_thread_comments": {
        "description": "A single comment inside a pull request comment thread.",
        "docs_url": "https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pull-request-threads/list",
        "columns": {
            "id": "The comment ID. IDs start at 1 and are unique within a pull request.",
            "parentCommentId": "ID of the comment this one replies to.",
            "author": "The identity that wrote the comment.",
            "content": "The comment content.",
            "commentType": "Type of the comment at creation time (unknown, text, codeChange, system).",
            "publishedDate": "Time at which the comment was first published.",
            "lastUpdatedDate": "Time at which the comment was last updated.",
            "lastContentUpdatedDate": "Time at which the comment content was last edited.",
            "isDeleted": "Whether the comment was soft-deleted.",
            "usersLiked": "Identities that liked the comment.",
            "thread_id": "Identifier of the thread the comment belongs to.",
            "repository_id": "Identifier of the repository the pull request targets.",
            "pull_request_id": "Identifier of the pull request the comment belongs to.",
            "project_name": "Name of the project the pull request belongs to.",
        },
    },
    "pull_request_reviewers": {
        "description": "A reviewer on a pull request, with their approval vote.",
        "docs_url": "https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pull-request-reviewers/list",
        "columns": {
            "id": "Identifier of the reviewer identity.",
            "displayName": "Display name of the reviewer.",
            "uniqueName": "Unique name of the reviewer, usually an email address.",
            "vote": "The reviewer's vote: 10 approved, 5 approved with suggestions, 0 no vote, -5 waiting for author, -10 rejected.",
            "isRequired": "Whether branch policy requires this reviewer on the pull request.",
            "isFlagged": "Whether the reviewer is flagged for attention on the pull request.",
            "hasDeclined": "Whether the reviewer declined to review the pull request.",
            "votedFor": "Votes rolled up from groups or teams this reviewer contributed to.",
            "reviewerUrl": "API URL of this reviewer on the pull request.",
            "url": "API URL of the reviewer identity.",
            "repository_id": "Identifier of the repository the pull request targets.",
            "pull_request_id": "Identifier of the pull request being reviewed.",
            "project_name": "Name of the project the pull request belongs to.",
        },
    },
    "teams": {
        "description": "A team in an Azure DevOps project.",
        "docs_url": "https://learn.microsoft.com/en-us/rest/api/azure/devops/core/teams/get-teams",
        "columns": {
            "id": "Team identifier. Unique across the organization.",
            "name": "Name of the team.",
            "description": "Description of the team.",
            "url": "API URL of the team.",
            "identityUrl": "API URL of the identity backing the team.",
            "project_id": "Identifier of the project the team belongs to.",
            "project_name": "Name of the project the team belongs to.",
        },
    },
    "team_members": {
        "description": "Membership of a team, one row per member.",
        "docs_url": "https://learn.microsoft.com/en-us/rest/api/azure/devops/core/teams/get-team-members-with-extended-properties",
        "columns": {
            "identity": "The member's identity, with display name and unique name.",
            "identity_id": "Identifier of the member identity, lifted from the identity object.",
            "isTeamAdmin": "Whether the member administers the team.",
            "team_id": "Identifier of the team.",
            "team_name": "Name of the team.",
            "project_id": "Identifier of the project the team belongs to.",
        },
    },
    "work_item_revisions": {
        "description": "A historical revision of a work item, from the reporting (append-only) feed.",
        "docs_url": "https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/reporting-work-item-revisions/read-reporting-revisions-get",
        "columns": {
            "id": "Identifier of the work item this revision belongs to.",
            "rev": "Revision number of the work item.",
            "fields": "The work item field values at this revision (title, state, assigned to, etc.).",
            "changed_date": "Time at which this revision was made.",
            "url": "API URL of the work item revision.",
        },
    },
    "build_definitions": {
        "description": "A build pipeline definition — the configuration a build run is produced from.",
        "docs_url": "https://learn.microsoft.com/en-us/rest/api/azure/devops/build/definitions/list",
        "columns": {
            "id": "Identifier of the definition, unique within its project.",
            "project_id": "Identifier of the project the definition belongs to.",
            "project_name": "Name of the project the definition belongs to.",
            "name": "Name of the definition.",
            "path": "Folder path of the definition.",
            "type": "Type of the definition (build or xaml).",
            "queueStatus": "Whether builds can be queued against this definition (enabled, paused, disabled).",
            "revision": "Revision number of the definition, incremented on each change.",
            "createdDate": "Time at which this version of the definition was created.",
            "authoredBy": "The identity that authored the definition.",
            "queue": "The default agent pool queue for builds run against this definition.",
            "uri": "URI of the definition.",
            "url": "API URL of the definition.",
        },
    },
    "build_timeline_records": {
        "description": "One record in a build's timeline — a stage, phase, job or task, with its own timing and result.",
        "docs_url": "https://learn.microsoft.com/en-us/rest/api/azure/devops/build/timeline/get",
        "columns": {
            "id": "Identifier of the timeline record.",
            "build_id": "Identifier of the build the record belongs to.",
            "timeline_id": "Identifier of the timeline the record was read from.",
            "build_queue_time": "Time at which the build was queued.",
            "build_finish_time": "Time at which the build finished.",
            "project_name": "Name of the project the build belongs to.",
            "parentId": "Identifier of the record's parent record.",
            "type": "Type of the record (Stage, Phase, Job, Task, Checkpoint).",
            "name": "Name of the record.",
            "identifier": "String identifier that stays the same across attempts.",
            "attempt": "Attempt number of the record.",
            "state": "State of the record (pending, inProgress, completed).",
            "result": "Result of a completed record (succeeded, failed, canceled, skipped, abandoned, succeededWithIssues).",
            "resultCode": "Result code of the record.",
            "startTime": "Time at which the record started.",
            "finishTime": "Time at which the record finished.",
            "percentComplete": "Completion percentage of the record.",
            "errorCount": "Number of errors produced by the record.",
            "warningCount": "Number of warnings produced by the record.",
            "workerName": "Name of the agent that ran the record.",
            "queueId": "Identifier of the queue the record ran on.",
            "order": "Ordinal value of the record relative to its siblings.",
            "task": "The task the record represents.",
            "log": "Reference to the log the record produced.",
            "issues": "Errors and warnings raised by the record.",
            "lastModified": "Time at which the record was last modified.",
            "url": "API URL of the timeline record.",
        },
    },
    "releases": {
        "description": "A classic release created from a release pipeline definition.",
        "docs_url": "https://learn.microsoft.com/en-us/rest/api/azure/devops/release/releases/list",
        "columns": {
            "id": "Identifier of the release, unique within its project.",
            "project_id": "Identifier of the project the release belongs to.",
            "project_name": "Name of the project the release belongs to.",
            "name": "Name of the release.",
            "status": "Status of the release (draft, active, abandoned).",
            "reason": "Reason the release was created (manual, continuousIntegration, schedule, pullRequest).",
            "createdOn": "Time at which the release was created.",
            "modifiedOn": "Time at which the release was last modified.",
            "createdBy": "The identity that created the release.",
            "modifiedBy": "The identity that last modified the release.",
            "createdFor": "The identity the release was created for.",
            "description": "Description of the release.",
            "releaseDefinition": "The release pipeline definition the release was created from.",
            "releaseDefinitionRevision": "Revision of the release definition used.",
            "definitionSnapshotRevision": "Revision of the definition snapshot taken for the release.",
            "keepForever": "Whether the release is excluded from retention policies.",
            "tags": "Tags attached to the release.",
            "poolName": "Name of the agent pool used.",
            "logsContainerUrl": "URL of the release logs container.",
        },
    },
    "release_deployments": {
        "description": "One deployment of a release to an environment — the grain for deployment frequency and promotion history.",
        "docs_url": "https://learn.microsoft.com/en-us/rest/api/azure/devops/release/deployments/list",
        "columns": {
            "id": "Identifier of the deployment, unique within its project.",
            "project_id": "Identifier of the project the deployment belongs to.",
            "project_name": "Name of the project the deployment belongs to.",
            "release": "The release being deployed.",
            "releaseDefinition": "The release pipeline definition the deployment belongs to.",
            "releaseEnvironment": "The environment the release was deployed to.",
            "definitionEnvironmentId": "Identifier of the environment in the release definition.",
            "deploymentStatus": "Status of the deployment (notDeployed, inProgress, succeeded, partiallySucceeded, failed).",
            "operationStatus": "Operation status of the deployment (queued, approved, rejected, phaseInProgress, canceled, and so on).",
            "reason": "Reason the deployment was started (manual, automated, scheduled, redeployTrigger).",
            "attempt": "Attempt number of the deployment.",
            "queuedOn": "Time at which the deployment was queued.",
            "startedOn": "Time at which the deployment started.",
            "completedOn": "Time at which the deployment completed.",
            "scheduledDeploymentTime": "Time the deployment is scheduled for.",
            "lastModifiedOn": "Time at which the deployment was last modified.",
            "lastModifiedBy": "The identity that last modified the deployment.",
            "requestedBy": "The identity that requested the deployment.",
            "requestedFor": "The identity the deployment was requested for.",
            "preDeployApprovals": "Approvals recorded before the deployment ran.",
            "postDeployApprovals": "Approvals recorded after the deployment ran.",
            "conditions": "Conditions and gates associated with the deployment.",
        },
    },
    "pull_request_work_items": {
        "description": "A link between a pull request and a work item it resolves or references.",
        "docs_url": "https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pull-request-work-items/list",
        "columns": {
            "id": "Identifier of the linked work item.",
            "url": "API URL of the linked work item.",
            "project_name": "Name of the project the pull request belongs to.",
            "repository_id": "Identifier of the repository the pull request belongs to.",
            "pull_request_id": "Identifier of the pull request the work item is linked to.",
        },
    },
    "pipelines": {
        "description": "A YAML pipeline defined in an Azure DevOps project.",
        "docs_url": "https://learn.microsoft.com/en-us/rest/api/azure/devops/pipelines/pipelines/list",
        "columns": {
            "id": "Identifier of the pipeline.",
            "name": "Name of the pipeline.",
            "folder": "Folder the pipeline is filed under.",
            "revision": "Revision number of the pipeline, incremented on each change.",
            "url": "API URL of the pipeline.",
            "project_id": "Identifier of the project the pipeline belongs to.",
            "project_name": "Name of the project the pipeline belongs to.",
        },
    },
    "pipeline_runs": {
        "description": "A run of a YAML pipeline, with its state, result and timings.",
        "docs_url": "https://learn.microsoft.com/en-us/rest/api/azure/devops/pipelines/runs/list",
        "columns": {
            "id": "Identifier of the run.",
            "name": "Name of the run.",
            "state": "State of the run (unknown, inProgress, canceling, completed).",
            "result": "Result of a completed run (unknown, succeeded, failed, canceled).",
            "createdDate": "Time at which the run was created.",
            "finishedDate": "Time at which the run finished.",
            "templateParameters": "Template parameters the run was started with.",
            "pipeline": "The pipeline the run belongs to.",
            "resources": "Repositories, pipelines and containers the run consumed.",
            "url": "API URL of the run.",
            "project_id": "Identifier of the project the run belongs to.",
            "project_name": "Name of the project the run belongs to.",
            "pipeline_id": "Identifier of the pipeline the run belongs to.",
            "pipeline_name": "Name of the pipeline the run belongs to.",
        },
    },
    "work_item_types": {
        "description": "A work item type defined by a project's process, such as Bug, Task or User Story.",
        "docs_url": "https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/work-item-types/list",
        "columns": {
            "name": "Display name of the work item type.",
            "referenceName": "Reference name of the work item type, as used in work item field values.",
            "description": "Description of the work item type.",
            "color": "Colour of the work item type.",
            "icon": "Icon of the work item type.",
            "isDisabled": "Whether the work item type is disabled for the project.",
            "states": "States the work item type can be in.",
            "transitions": "Allowed transitions between the type's states.",
            "fields": "Fields defined on the work item type.",
            "fieldInstances": "Field definitions as instantiated on the work item type.",
            "xmlForm": "XML definition of the work item form.",
            "url": "API URL of the work item type.",
            "project_id": "Identifier of the project the type is defined in.",
            "project_name": "Name of the project the type is defined in.",
        },
    },
    "work_item_type_states": {
        "description": "A state a work item type can be in, with the state category that groups it.",
        "docs_url": "https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/work-item-type-states/list",
        "columns": {
            "name": "Name of the state, as it appears in the System.State field.",
            "color": "Colour of the state.",
            "category": "Category the state belongs to (Proposed, InProgress, Resolved, Completed, Removed).",
            "project_id": "Identifier of the project the state is defined in.",
            "project_name": "Name of the project the state is defined in.",
            "work_item_type": "Name of the work item type the state belongs to.",
            "work_item_type_reference_name": "Reference name of the work item type the state belongs to.",
        },
    },
    "work_item_classification_nodes": {
        "description": "One node of a project's area or iteration tree, resolving the area and iteration paths on work items.",
        "docs_url": "https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/classification-nodes/get-root-nodes",
        "columns": {
            "id": "Identifier of the node within the project.",
            "identifier": "Globally unique identifier of the node.",
            "name": "Name of the node.",
            "path": "Full path of the node, matching the area or iteration path on a work item.",
            "structureType": "Type of tree the node belongs to (area or iteration).",
            "hasChildren": "Whether the node has child nodes.",
            "attributes": "Node attributes; for an iteration node, its start and finish dates.",
            "url": "API URL of the node.",
            "parent_id": "Identifier of the node's parent, or null for a root node.",
            "project_id": "Identifier of the project the node belongs to.",
            "project_name": "Name of the project the node belongs to.",
        },
    },
    "work_iterations": {
        "description": "An iteration (sprint) a team is subscribed to, with its dates and relative timeframe.",
        "docs_url": "https://learn.microsoft.com/en-us/rest/api/azure/devops/work/iterations/list",
        "columns": {
            "id": "Identifier of the iteration.",
            "name": "Name of the iteration.",
            "path": "Full iteration path, matching the iteration path on a work item.",
            "attributes": "Start date, finish date and relative timeframe of the iteration.",
            "url": "API URL of the team's iteration.",
            "project_id": "Identifier of the project the iteration belongs to.",
            "project_name": "Name of the project the iteration belongs to.",
            "team_id": "Identifier of the team subscribed to the iteration.",
            "team_name": "Name of the team subscribed to the iteration.",
        },
    },
    "test_runs": {
        "description": "A test run published against a build or release, with its pass and fail counts.",
        "docs_url": "https://learn.microsoft.com/en-us/rest/api/azure/devops/test/runs/list",
        "columns": {
            "id": "Identifier of the test run.",
            "project_id": "Identifier of the project the run belongs to.",
            "project_name": "Name of the project the run belongs to.",
            "name": "Name of the test run.",
            "state": "State of the run (NotStarted, InProgress, Completed, Waiting, Aborted).",
            "isAutomated": "Whether the run is automated.",
            "totalTests": "Total number of tests in the run.",
            "passedTests": "Number of passed tests in the run.",
            "unanalyzedTests": "Number of failed tests in the run.",
            "incompleteTests": "Number of incomplete tests in the run.",
            "notApplicableTests": "Number of not applicable tests in the run.",
            "runStatistics": "Test counts broken down by outcome.",
            "startedDate": "Time at which the run started.",
            "completedDate": "Time at which the run completed.",
            "createdDate": "Time at which the run was created.",
            "lastUpdatedDate": "Time at which the run was last updated.",
            "build": "The build the run was published against.",
            "buildConfiguration": "Build configuration details for the run.",
            "release": "The release the run was published against.",
            "pipelineReference": "The pipeline stage and job the run belongs to.",
            "plan": "The test plan the run belongs to.",
            "owner": "The identity that owns the run.",
            "errorMessage": "Error message associated with the run.",
            "tags": "Tags attached to the run.",
            "webAccessUrl": "URL of the run in the Azure DevOps web UI.",
            "url": "API URL of the test run.",
        },
    },
}
