from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "sales": {
        "description": "A completed purchase of one of your Gumroad products, including refunds, chargebacks, and recurring subscription charges.",
        "docs_url": "https://gumroad.com/api#sales",
        "columns": {
            "id": "Unique identifier for the sale.",
            "created_at": "When the sale was made.",
            "email": "Email address the purchase is associated with.",
            "purchase_email": "Email address entered at checkout.",
            "seller_id": "Identifier of the seller who made the sale.",
            "product_id": "Identifier of the product that was bought.",
            "product_name": "Name of the product that was bought.",
            "product_permalink": "Short permalink of the product that was bought.",
            "price": "Amount paid, in the smallest unit of the sale currency (for example cents).",
            "currency": "ISO code of the currency the sale is denominated in.",
            "gumroad_fee": "Gumroad's fee for the sale, in the smallest unit of the sale currency.",
            "formatted_display_price": "Sale price formatted with its currency symbol.",
            "formatted_total_price": "Total charged, formatted with its currency symbol.",
            "quantity": "Number of units bought.",
            "order_id": "Numeric order identifier shared by every sale in the same order.",
            "full_name": "Name given by the buyer.",
            "purchaser_id": "Identifier of the buyer's Gumroad account, when they have one.",
            "refunded": "Whether the sale was fully refunded.",
            "partially_refunded": "Whether part of the sale was refunded.",
            "chargedback": "Whether the sale was charged back and the chargeback was not reversed.",
            "disputed": "Whether the sale was disputed.",
            "dispute_won": "Whether a dispute on the sale was resolved in your favor.",
            "subscription_id": "Identifier of the subscription this charge belongs to, for memberships.",
            "recurring_charge": "Whether this is a renewal rather than the first charge of a subscription.",
            "is_recurring_billing": "Whether the product is billed on a recurring basis.",
            "is_product_physical": "Whether the product requires shipping.",
            "variants": "Versions the buyer selected, as a name to value map.",
            "custom_fields": "Values the buyer entered in the product's custom fields.",
            "offer_code": "Discount code applied to the sale, when there was one.",
            "affiliate": "Affiliate credited with the sale, when there was one.",
            "referrer": "Where the buyer came from.",
            "country": "Buyer's country.",
            "country_iso2": "Two-letter ISO code of the buyer's country.",
            "state": "Buyer's state or region.",
            "city": "Buyer's city.",
            "zip_code": "Buyer's postal code.",
            "product_rating": "Rating the buyer left for the product, when they left one.",
            "license_key": "License key issued for the sale, for licensed products.",
        },
    },
    "products": {
        "description": "A product on your Gumroad account, with its pricing, versions, and published state.",
        "docs_url": "https://gumroad.com/api#products",
        "columns": {
            "id": "Unique identifier for the product.",
            "name": "Product name.",
            "description": "Product description.",
            "price": "Default price, in the smallest unit of the product currency.",
            "currency": "ISO code of the currency the product is priced in.",
            "formatted_price": "Default price formatted with its currency symbol.",
            "short_url": "Public URL of the product page.",
            "custom_permalink": "Custom permalink set for the product, when there is one.",
            "published": "Whether the product is published and available to buy.",
            "deleted": "Whether the product has been deleted.",
            "max_purchase_count": "Cap on how many times the product can be bought, when set.",
            "tags": "Tags applied to the product.",
            "taxonomy_id": "Identifier of the category the product is filed under.",
            "category": "Path of the category the product is filed under.",
            "thumbnail_url": "URL of the product thumbnail.",
            "require_shipping": "Whether the product needs a shipping address.",
            "customizable_price": "Whether buyers can pay what they want.",
            "subscription_duration": "Billing period for a membership product.",
            "is_tiered_membership": "Whether the product is a tiered membership.",
            "variants": "Version groupings on the product and the options in each.",
            "custom_fields": "Custom fields buyers fill in at checkout.",
            "sales_count": "Number of successful sales. Needs the view_sales scope.",
            "sales_usd_cents": "Lifetime revenue in US cents. Needs the view_sales scope.",
        },
    },
    "payouts": {
        "description": "A settled payout Gumroad sent to your bank account or PayPal address.",
        "docs_url": "https://gumroad.com/api#payouts",
        "columns": {
            "id": "Unique identifier for the payout.",
            "created_at": "When the payout was created.",
            "processed_at": "When the payout completed, for completed payouts.",
            "amount": "Payout amount, as a decimal string in the payout currency.",
            "currency": "ISO code of the payout currency.",
            "status": "Current state of the payout.",
            "payment_processor": "Processor that sent the payout.",
            "bank_account_visual": "Masked bank account the payout was sent to.",
            "paypal_email": "PayPal address the payout was sent to.",
        },
    },
    "subscribers": {
        "description": "An active subscription to one of your membership products.",
        "docs_url": "https://gumroad.com/api#subscribers",
        "columns": {
            "id": "Unique identifier for the subscription.",
            "product_id": "Identifier of the membership product.",
            "product_name": "Name of the membership product.",
            "email": "Email address of the subscriber.",
            "user_id": "Identifier of the subscriber's Gumroad account, when they have one.",
            "user_email": "Email address on the subscriber's Gumroad account.",
            "purchase_ids": "Identifiers of the sales that make up this subscription.",
            "created_at": "When the subscription started.",
            "recurrence": "How often the subscription is billed.",
            "charge_occurrence_count": "Number of charges the subscription is limited to, when limited.",
            "user_requested_cancellation_at": "When the subscriber asked to cancel.",
            "cancelled_at": "When the subscription was cancelled.",
            "ended_at": "When the subscription ended.",
            "failed_at": "When billing failed permanently.",
            "free_trial_ends_at": "When the free trial ends.",
            "status": "Current state of the subscription.",
            "license_key": "License key issued for the subscription, for licensed products.",
        },
    },
    "product_reviews": {
        "description": "A review left on one of your products, as shown on its public product page.",
        "docs_url": "https://gumroad.com/api#reviews",
        "columns": {
            "id": "Unique identifier for the review.",
            "product_id": "Identifier of the reviewed product, carried down from the product list.",
            "rating": "Star rating the reviewer gave.",
            "message": "Text of the review.",
            "created_at": "When the review was submitted.",
            "purchase_id": "Identifier of the sale the review is attached to.",
            "rater_name": "Name of the reviewer, or Anonymous.",
            "response": "Your reply to the review, with its own message and timestamp.",
        },
    },
    "offer_codes": {
        "description": "A discount code that applies to a product, including universal codes that apply to every product.",
        "docs_url": "https://gumroad.com/api#offer-codes",
        "columns": {
            "id": "Unique identifier for the offer code.",
            "product_id": "Identifier of the product the code was listed under, carried down from the product list.",
            "name": "The code buyers enter at checkout.",
            "amount_cents": "Fixed discount in the smallest unit of the product currency, for fixed-amount codes.",
            "percent_off": "Discount percentage, for percentage codes.",
            "max_purchase_count": "Cap on how many times the code can be used, when set.",
            "minimum_amount_cents": "Minimum order amount the code applies to, when set.",
            "universal": "Whether the code applies to every product on the account.",
            "times_used": "Number of times the code has been used.",
        },
    },
    "variant_categories": {
        "description": "A grouping of versions on a product, such as Tier or Format.",
        "docs_url": "https://gumroad.com/api#variant-categories",
        "columns": {
            "id": "Unique identifier for the version grouping.",
            "product_id": "Identifier of the product the grouping belongs to, carried down from the product list.",
            "title": "Name of the grouping shown at checkout.",
        },
    },
    "custom_fields": {
        "description": "A field buyers fill in at checkout for a product.",
        "docs_url": "https://gumroad.com/api#custom-fields",
        "columns": {
            "id": "Unique identifier for the custom field.",
            "product_id": "Identifier of the product the field was listed under, carried down from the product list.",
            "name": "Label shown to the buyer.",
            "type": "Kind of input the field renders.",
            "required": "Whether the buyer must fill the field in.",
            "global": "Whether the field applies to every product on the account.",
            "collect_per_product": "Whether the value is collected once per product in the cart.",
            "products": "Identifiers of the products the field is attached to.",
        },
    },
}
