from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "customers": {
        "description": "The companies or accounts you bill. Usage events, contracts and invoices all hang off a customer. Only active customers are synced; Metronome's list endpoint returns archived customers only as a separate, exclusive result set.",
        "docs_url": "https://docs.metronome.com/api-reference/customers/list-customers",
        "columns": {
            "id": "The Metronome id of the customer.",
            "external_id": "Your own id for the customer. Deprecated by Metronome in favor of ingest aliases.",
            "ingest_aliases": "Alternate ids that usage events may use to address this customer.",
            "name": "The customer's display name.",
            "customer_config": "Billing-provider configuration for the customer, including its Salesforce account id.",
            "custom_fields": "Arbitrary key/value pairs set on the customer by your account.",
            "created_at": "When the customer was created.",
            "updated_at": "When the customer was last modified.",
            "archived_at": "When the customer was archived. Null while the customer is active.",
            "current_billable_status": "Whether the customer is currently billable, and when that status took effect. Only populated when your account is configured for it.",
        },
    },
    "contracts": {
        "description": "Contracts define what a customer is charged: the rate card in force, plus its commits, credits, overrides, discounts and scheduled charges. Fetched per customer from the v2 endpoint.",
        "docs_url": "https://docs.metronome.com/api-reference/contracts/list-customer-contracts-v2",
        "columns": {
            "id": "The contract's id.",
            "customer_id": "The customer the contract belongs to.",
            "name": "The contract's display name.",
            "starting_at": "When the contract takes effect.",
            "ending_before": "When the contract stops applying. Null for an open-ended contract.",
            "created_at": "When the contract was created.",
            "created_by": "Who created the contract.",
            "archived_at": "When the contract was archived. Null while it is active.",
            "rate_card_id": "The rate card the contract prices against.",
            "package_id": "The package the contract was created from, if any.",
            "commits": "Prepaid or postpaid commitments on the contract. Truncated when `has_more` says so.",
            "credits": "Credits granted on the contract. Truncated when `has_more` says so.",
            "overrides": "Contract-specific rate overrides applied on top of the rate card.",
            "discounts": "Negotiated discounts applied to the contract.",
            "scheduled_charges": "Fixed charges billed on a schedule rather than from usage.",
            "transitions": "Renewals and supersessions linking this contract to others.",
            "subscriptions": "Recurring subscription charges on the contract.",
            "recurring_commits": "Commitments that recur each billing period.",
            "recurring_credits": "Credits that recur each billing period.",
            "usage_filter": "Filter restricting which usage the contract bills.",
            "usage_statement_schedule": "How often usage statements are generated for the contract.",
            "total_contract_value": "The contract's total value.",
            "net_payment_terms_days": "Days the customer has to pay an invoice under this contract.",
            "priority": "Ordering used when several contracts could bill the same usage.",
            "custom_fields": "Arbitrary key/value pairs set on the contract by your account.",
            "has_more": "Flags whether `commits` or `credits` were truncated in this response.",
        },
    },
    "invoices": {
        "description": "Invoices issued to a customer, with their line items. Fetched per customer; Metronome has no account-wide invoice list endpoint.",
        "docs_url": "https://docs.metronome.com/api-reference/invoices/list-invoices",
        "columns": {
            "id": "The invoice's id.",
            "customer_id": "The customer the invoice was issued to.",
            "contract_id": "The contract the invoice bills against, if any.",
            "amendment_id": "The contract amendment the invoice bills against, if any.",
            "type": "The invoice type: usage, consolidated usage, or scheduled.",
            "status": "Where the invoice is in its lifecycle, for example draft, finalized or void.",
            "total": "The invoice total, in the invoice's credit type.",
            "credit_type": "The currency or pricing unit the invoice is denominated in.",
            "line_items": "The individual charges making up the invoice.",
            "start_timestamp": "Start of the billing period the invoice covers.",
            "end_timestamp": "End of the billing period the invoice covers.",
            "issued_at": "When the invoice was issued.",
            "created_at": "When the invoice record was created. Metronome only sets this on correction invoices.",
            "external_invoice": "The matching invoice in your billing provider, when one has been synced.",
            "net_payment_terms_days": "Days the customer has to pay this invoice.",
            "correction_record": "Details of the invoice this one corrects, when it is a correction.",
            "billable_status": "Whether the invoice is billable or was marked unbillable.",
            "regenerated_from_invoice_id": "The invoice this one replaced, when it was regenerated.",
        },
    },
    "products": {
        "description": "Products are the billable things a rate card prices: usage, subscription, composite, fixed, or professional-services. Includes archived products.",
        "docs_url": "https://docs.metronome.com/api-reference/products/list-products",
        "columns": {
            "id": "The product's id.",
            "type": "The product type: USAGE, SUBSCRIPTION, COMPOSITE, FIXED or PRO_SERVICE.",
            "initial": "The product's first version, including its name and billable metric.",
            "current": "The product's version in effect now.",
            "updates": "Every version of the product, in the order it was updated.",
            "archived_at": "When the product was archived. Null while it is active.",
            "custom_fields": "Arbitrary key/value pairs set on the product by your account.",
        },
    },
    "rate_cards": {
        "description": "Rate cards hold the prices charged for products. Contracts reference a rate card rather than carrying prices themselves. The rates on a card are fetched separately and are not part of this table.",
        "docs_url": "https://docs.metronome.com/api-reference/rate-cards/list-rate-cards",
        "columns": {
            "id": "The rate card's id.",
            "name": "The rate card's display name.",
            "description": "The rate card's description.",
            "created_at": "When the rate card was created.",
            "created_by": "Who created the rate card.",
            "fiat_credit_type": "The currency the rate card's fiat prices are denominated in.",
            "credit_type_conversions": "Conversion rates between the card's pricing units and its fiat currency.",
            "aliases": "Alternate names the rate card can be referenced by, with the window each applies in.",
            "custom_fields": "Arbitrary key/value pairs set on the rate card by your account.",
        },
    },
    "packages": {
        "description": "Packages are reusable contract templates: a rate card plus the commits, credits, overrides and charges a new contract should start with. Includes archived packages.",
        "docs_url": "https://docs.metronome.com/api-reference/list-all-packages",
        "columns": {
            "id": "The package's id.",
            "name": "The package's display name.",
            "rate_card_id": "The rate card contracts created from this package price against.",
            "duration": "How long a contract created from this package runs for.",
            "commits": "Commitments a contract created from this package starts with.",
            "credits": "Credits a contract created from this package starts with.",
            "overrides": "Rate overrides applied on top of the rate card.",
            "scheduled_charges": "Fixed charges billed on a schedule.",
            "subscriptions": "Recurring subscription charges included in the package.",
            "recurring_commits": "Commitments that recur each billing period.",
            "recurring_credits": "Credits that recur each billing period.",
            "net_payment_terms_days": "Days a customer has to pay an invoice under contracts from this package.",
            "usage_statement_schedule": "How often usage statements are generated.",
            "created_at": "When the package was created.",
            "created_by": "Who created the package.",
            "archived_at": "When the package was archived. Null while it is active.",
            "uniqueness_key": "Idempotency key supplied when the package was created.",
        },
    },
    "billable_metrics": {
        "description": "Billable metrics turn raw usage events into the quantities products charge for, by filtering events and aggregating a property. Includes archived metrics.",
        "docs_url": "https://docs.metronome.com/api-reference/billable-metrics/list-all-billable-metrics",
        "columns": {
            "id": "The billable metric's id.",
            "name": "The billable metric's display name.",
            "event_type_filter": "Which usage event types the metric counts.",
            "property_filters": "Event property conditions a usage event must meet to be counted.",
            "aggregation_type": "How matching events are aggregated, for example count, sum, max or unique.",
            "aggregation_key": "The event property that is aggregated. Not set for a count.",
            "group_keys": "Event properties the metric is broken down by.",
            "sql": "The SQL definition, for metrics defined in SQL rather than with filters.",
            "archived_at": "When the metric was archived. Null while it is active.",
            "custom_fields": "Arbitrary key/value pairs set on the metric by your account.",
        },
    },
    "pricing_units": {
        "description": "The units prices and balances are denominated in: fiat currencies plus any custom credit types your account defines.",
        "docs_url": "https://docs.metronome.com/api-reference/settings/list-pricing-units",
        "columns": {
            "id": "The pricing unit's id.",
            "name": "The pricing unit's display name, for example USD or a custom credit name.",
            "is_currency": "Whether the unit is a fiat currency rather than a custom credit type.",
        },
    },
    "audit_logs": {
        "description": "One row per change made through the Metronome app or API: who did it, to what, and whether it succeeded. This is the only Metronome endpoint with a server-side time filter, so it is the only table that syncs incrementally.",
        "docs_url": "https://docs.metronome.com/api-reference/security/get-audit-logs",
        "columns": {
            "id": "The audit log entry's id.",
            "timestamp": "When the action happened.",
            "actor": "Who performed the action, whether a user or an API token.",
            "request": "The API request that performed the action, including its id and user agent.",
            "resource_type": "The kind of object acted on, for example customer or contract.",
            "resource_id": "The id of the object acted on.",
            "action": "What was done to the resource.",
            "status": "Whether the action succeeded, failed, or is still pending.",
            "description": "A readable summary of the action.",
        },
    },
}
