"""Canonical, documentation-sourced descriptions for Brex endpoints and columns.

Sourced from the official Brex API reference (https://developer.brex.com/openapi/).
Keyed by the endpoint names in `settings.py` `BREX_ENDPOINTS`, which match the
`ExternalDataSchema.name` of a synced Brex table. Columns absent here fall back to LLM enrichment.
"""

from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "card_transactions": {
        "description": "A transaction on a Brex card — a purchase, refund, or other movement on the primary card account.",
        "docs_url": "https://developer.brex.com/openapi/transactions_api/#tag/Transactions/operation/listPrimaryCardTransactions",
        "columns": {
            "id": "Unique identifier of the transaction.",
            "description": "Description of the transaction (typically the merchant name).",
            "amount": "Monetary amount of the transaction, with amount and currency.",
            "type": "Type of the transaction (e.g. PURCHASE, REFUND, CHARGEBACK).",
            "initiated_at_date": "Date the transaction was initiated.",
            "posted_at_date": "Date the transaction posted to the account.",
            "card_id": "Identifier of the card used for the transaction.",
            "merchant": "Merchant details for the transaction.",
        },
    },
    "cash_transactions": {
        "description": "A transaction on a Brex cash account — a deposit, withdrawal, or transfer.",
        "docs_url": "https://developer.brex.com/openapi/transactions_api/#tag/Transactions/operation/listCashTransactions",
        "columns": {
            "id": "Unique identifier of the transaction.",
            "account_id": "Identifier of the cash account the transaction belongs to.",
            "description": "Description of the transaction.",
            "amount": "Monetary amount of the transaction, with amount and currency.",
            "type": "Type of the transaction (e.g. BOOK_TRANSFER, ACH_TRANSFER, WIRE_TRANSFER).",
            "initiated_at_date": "Date the transaction was initiated.",
            "posted_at_date": "Date the transaction posted to the account.",
        },
    },
    "card_accounts": {
        "description": "A Brex card account, with its current balance, credit limit and current statement period.",
        "docs_url": "https://developer.brex.com/openapi/transactions_api/#tag/Accounts/operation/listCardAccounts",
        "columns": {
            "id": "Unique identifier of the card account, as referenced by card transactions.",
            "status": "Status of the card account.",
            "current_balance": "Balance currently owed on the account, with amount and currency.",
            "available_balance": "Amount still available to spend on the account, with amount and currency.",
            "account_limit": "Total credit limit of the account, with amount and currency.",
            "current_statement_period": "Start and end dates of the statement period in progress.",
        },
    },
    "cash_accounts": {
        "description": "A Brex cash account, with its balances and bank details. Resolves the account_id carried on cash transactions.",
        "docs_url": "https://developer.brex.com/openapi/transactions_api/#tag/Accounts/operation/listAccounts",
        "columns": {
            "id": "Unique identifier of the cash account, as referenced by cash transactions.",
            "name": "Name of the cash account.",
            "status": "Status of the cash account.",
            "current_balance": "Balance held in the account, with amount and currency.",
            "available_balance": "Amount available to spend from the account, with amount and currency.",
            "account_number": "Bank account number of the cash account.",
            "routing_number": "Bank routing number of the cash account.",
            "primary": "Whether this is the account's single primary cash account.",
        },
    },
    "expenses": {
        "description": "An expense in Brex — a recorded spend item with receipts, status, and accounting details.",
        "docs_url": "https://developer.brex.com/openapi/expenses_api/#tag/Expenses/operation/listExpenses",
        "columns": {
            "id": "Unique identifier of the expense.",
            "memo": "Memo or description attached to the expense.",
            "status": "Current status of the expense (e.g. DRAFT, SUBMITTED, APPROVED, SETTLED).",
            "category": "Spend category assigned to the expense.",
            "merchant_id": "Identifier of the merchant for the expense.",
            "amount": "Monetary amount of the expense, with amount and currency.",
            "purchased_at": "Time at which the purchase occurred.",
            "submitted_at": "Time at which the expense was submitted.",
            "updated_at": "Time at which the expense was last updated.",
            "user_id": "Identifier of the user who incurred the expense.",
            "budget_id": "Identifier of the budget the expense is associated with.",
        },
    },
    "users": {
        "description": "A user (employee) in the Brex account.",
        "docs_url": "https://developer.brex.com/openapi/team_api/#tag/Users/operation/listUsers",
        "columns": {
            "id": "Unique identifier of the user.",
            "first_name": "First name of the user.",
            "last_name": "Last name of the user.",
            "email": "Email address of the user.",
            "status": "Account status of the user (e.g. ACTIVE, INVITED, DISABLED).",
            "manager_id": "Identifier of the user's manager.",
            "department_id": "Identifier of the department the user belongs to.",
            "location_id": "Identifier of the location the user belongs to.",
        },
    },
    "departments": {
        "description": "A department defined in the Brex account for organizing users and budgets.",
        "docs_url": "https://developer.brex.com/openapi/team_api/#tag/Departments/operation/listDepartments",
        "columns": {
            "id": "Unique identifier of the department.",
            "name": "Name of the department.",
            "description": "Description of the department.",
        },
    },
    "locations": {
        "description": "A physical location defined in the Brex account for organizing users and budgets.",
        "docs_url": "https://developer.brex.com/openapi/team_api/#tag/Locations/operation/listLocations",
        "columns": {
            "id": "Unique identifier of the location.",
            "name": "Name of the location.",
            "description": "Description of the location.",
        },
    },
    "cards": {
        "description": "A Brex card issued to a user or vendor, with its spend controls. Resolves the card_id carried on card transactions.",
        "docs_url": "https://developer.brex.com/openapi/team_api/#tag/Cards/operation/listCardsByUserId",
        "columns": {
            "id": "Unique identifier of the card.",
            "owner": "The user the card belongs to.",
            "status": "Status of the card (ACTIVE, SHIPPED, LOCKED, or TERMINATED).",
            "last_four": "Last four digits of the card number.",
            "card_name": "Name given to the card.",
            "card_type": "Whether the card is VIRTUAL or PHYSICAL.",
            "limit_type": "CARD for vendor cards with their own limit, USER for corporate cards on the user's limit.",
            "spend_controls": "Spend limit, remaining spend, refresh frequency and merchant restrictions. Only set when limit_type is CARD.",
            "billing_address": "Billing address on the card.",
            "mailing_address": "Shipping address a physical card was sent to.",
            "expiration_date": "Expiration month and year of the card.",
            "has_been_transferred": "Whether the card has been transferred, which restricts it to vendors it was used at before.",
            "budget_id": "Identifier of the budget the card draws from.",
            "partner": "The partner that manages the card, if any.",
            "created_at": "Time at which the card was created.",
        },
    },
    "vendors": {
        "description": "A vendor (payee) configured in Brex for bill payments.",
        "docs_url": "https://developer.brex.com/openapi/payments_api/#tag/Vendors/operation/listVendors",
        "columns": {
            "id": "Unique identifier of the vendor.",
            "name": "Name of the vendor.",
            "email": "Email address of the vendor.",
            "phone": "Phone number of the vendor.",
            "payment_accounts": "Payment account details configured for the vendor.",
        },
    },
    "transfers": {
        "description": "An outbound payment from a Brex account — an ACH, wire, cheque or book transfer. Not covered by the card or cash transaction tables.",
        "docs_url": "https://developer.brex.com/openapi/payments_api/#tag/Transfers/operation/listTransfers",
        "columns": {
            "id": "Unique identifier of the transfer.",
            "counterparty": "Details of the vendor or account the money is sent to.",
            "description": "Description of the transfer.",
            "payment_type": "Payment rail used (e.g. ACH, DOMESTIC_WIRE, CHEQUE, INTERNATIONAL_WIRE).",
            "amount": "Monetary amount of the transfer, with amount and currency.",
            "process_date": "Date the transfer is processed.",
            "originating_account": "The Brex account the money is sent from.",
            "status": "Status of the transfer (PROCESSING, SCHEDULED, PENDING_APPROVAL, FAILED, or PROCESSED).",
            "cancellation_reason": "Why the transfer did not complete, when it failed.",
            "estimated_delivery_date": "Estimated date the money arrives.",
            "creator_user_id": "Identifier of the user who initiated the transfer.",
            "created_at": "Time at which the transfer was created.",
            "display_name": "Human readable name for the transfer.",
            "external_memo": "Memo sent with the payment to the recipient.",
        },
    },
    "budgets": {
        "description": "A budget in Brex that controls and tracks spend for a group or purpose.",
        "docs_url": "https://developer.brex.com/openapi/budgets_api/#tag/Budgets/operation/listBudgets",
        "columns": {
            "budget_id": "Unique identifier of the budget.",
            "name": "Name of the budget.",
            "description": "Description of the budget.",
            "parent_budget_id": "Identifier of the parent budget, if nested.",
            "budget_status": "Status of the budget (e.g. ACTIVE, EXPIRED).",
            "limit": "Spend limit configured for the budget, with amount and currency.",
            "spend_budget_status": "Spend status of the budget relative to its limit.",
            "period_type": "Recurrence period of the budget (e.g. MONTHLY, QUARTERLY, YEARLY, ONE_TIME).",
        },
    },
    "spend_limits": {
        "description": "A spend limit in Brex — the control that caps what a budget or card can spend over a period.",
        "docs_url": "https://developer.brex.com/openapi/budgets_api/#tag/Spend-Limits-v2/operation/listSpendLimits",
        "columns": {
            "id": "Unique identifier of the spend limit.",
            "account_id": "Identifier of the Brex account the spend limit belongs to.",
            "name": "Name of the spend limit.",
            "description": "Description of what the spend limit is used for.",
            "parent_budget_id": "Identifier of the budget the spend limit sits under.",
            "status": "Status of the spend limit (ACTIVE, EXPIRED, ARCHIVED, or DELETED).",
            "period_recurrence_type": "How often the limit refreshes (e.g. PER_MONTH, PER_QUARTER, ONE_TIME).",
            "start_date": "Date the spend limit starts counting.",
            "end_date": "Date the spend limit expires.",
            "start_time_utc": "UTC time the spend limit starts counting.",
            "end_time_utc": "UTC time the spend limit expires.",
            "authorization_settings": "Base limit, buffer percentage, hard or soft authorization, and rollover behavior.",
        },
    },
}
