from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

_DOCS = "https://developer.bluetally.com/reference"

# Descriptions taken from BlueTally's public API reference (https://developer.bluetally.com/reference).
# Partial coverage is fine — any endpoint/column not listed here falls back to LLM enrichment.
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "assets": {
        "description": "Individual tracked IT assets (hardware) in BlueTally, including their lifecycle dates, assignment, and related catalog references.",
        "docs_url": f"{_DOCS}/list-assets",
        "columns": {
            "id": "Unique identifier for the asset.",
            "asset_id": "Human-readable asset tag / ID shown in the BlueTally UI.",
            "asset_name": "Name of the asset.",
            "asset_serial": "Serial number of the asset.",
            "warranty_expiration_date": "Date the asset's warranty expires.",
            "order_number": "Purchase order number associated with the asset.",
            "purchase_date": "Date the asset was purchased.",
            "purchase_cost": "Purchase cost of the asset.",
            "currency": "Currency of the purchase cost.",
            "product_id": "ID of the product (model) this asset is an instance of.",
            "status_id": "ID of the asset's current status.",
            "category_id": "ID of the asset's category.",
            "manufacturer_id": "ID of the asset's manufacturer.",
            "supplier_id": "ID of the supplier the asset was bought from.",
            "depreciation_id": "ID of the depreciation schedule applied to the asset.",
            "location_id": "ID of the asset's location.",
            "department_id": "ID of the department the asset belongs to.",
            "notes": "Free-text notes on the asset.",
            "custom_fields": "Custom field values configured for the asset.",
            "deployed_to": "Employees the asset is currently checked out to, with checkout dates.",
            "end_of_life_date": "Date the asset reaches end of life.",
            "created_at": "Timestamp when the asset was created.",
            "updated_at": "Timestamp when the asset was last updated.",
        },
    },
    "employees": {
        "description": "People in BlueTally that assets, accessories, consumables, and licenses can be checked out to.",
        "docs_url": f"{_DOCS}/list-employees",
        "columns": {
            "id": "Unique identifier for the employee.",
            "name": "Employee's full name.",
            "email": "Employee's email address.",
            "title": "Employee's job title.",
            "location_id": "ID of the employee's location.",
            "department_id": "ID of the employee's department.",
            "manager_id": "ID of the employee's manager.",
            "notes": "Free-text notes on the employee.",
            "archived": "Whether the employee has been archived.",
            "assets": "IDs of assets currently checked out to the employee.",
            "accessories": "IDs of accessories currently checked out to the employee.",
            "consumables": "IDs of consumables checked out to the employee.",
            "licenses": "IDs of licenses checked out to the employee.",
            "created_at": "Timestamp when the employee was created.",
            "updated_at": "Timestamp when the employee was last updated.",
        },
    },
    "licenses": {
        "description": "Software licenses tracked in BlueTally, including seat counts and assignment.",
        "docs_url": f"{_DOCS}/list-licenses",
        "columns": {
            "id": "Unique identifier for the license.",
            "name": "Name of the license.",
            "licensed_to_name": "Name the license is registered to.",
            "licensed_to_email": "Email the license is registered to.",
            "expiration_date": "Date the license expires.",
            "number_of_seats": "Total number of seats for the license.",
            "available": "Number of seats currently available.",
            "license_type": "Type of license.",
            "created_at": "Timestamp when the license was created.",
            "updated_at": "Timestamp when the license was last updated.",
        },
    },
    "accessories": {
        "description": "Accessories (peripherals and other non-serialized hardware) tracked by quantity in BlueTally.",
        "docs_url": f"{_DOCS}/list-all-accessories",
        "columns": {
            "id": "Unique identifier for the accessory.",
            "name": "Name of the accessory.",
            "model_number": "Model number of the accessory.",
            "minimum_quantity": "Minimum stock quantity before a low-stock alert.",
            "quantity": "Total quantity owned.",
            "available": "Quantity currently available (not checked out).",
            "created_at": "Timestamp when the accessory was created.",
            "updated_at": "Timestamp when the accessory was last updated.",
        },
    },
    "consumables": {
        "description": "Consumable items tracked by quantity in BlueTally (e.g. cables, ink) that deplete as they are checked out.",
        "docs_url": f"{_DOCS}/list-consumables",
        "columns": {
            "id": "Unique identifier for the consumable.",
            "name": "Name of the consumable.",
            "minimum_quantity": "Minimum stock quantity before a low-stock alert.",
            "available": "Quantity currently available.",
            "created_at": "Timestamp when the consumable was created.",
            "updated_at": "Timestamp when the consumable was last updated.",
        },
    },
    "components": {
        "description": "Components tracked in BlueTally that can be checked out to assets (e.g. RAM, drives).",
        "docs_url": f"{_DOCS}/list-components",
        "columns": {
            "id": "Unique identifier for the component.",
            "name": "Name of the component.",
            "quantity": "Total quantity owned.",
            "available": "Quantity currently available.",
            "created_at": "Timestamp when the component was created.",
            "updated_at": "Timestamp when the component was last updated.",
        },
    },
    "products": {
        "description": "Product models in BlueTally's catalog that assets are instances of.",
        "docs_url": f"{_DOCS}/list-products",
        "columns": {
            "id": "Unique identifier for the product.",
            "name": "Name of the product.",
            "model_number": "Model number of the product.",
            "category_id": "ID of the product's category.",
            "manufacturer_id": "ID of the product's manufacturer.",
            "end_of_life_date": "End-of-life date for the product.",
            "created_at": "Timestamp when the product was created.",
            "updated_at": "Timestamp when the product was last updated.",
        },
    },
    "categories": {
        "description": "Categories used to group BlueTally assets, accessories, and other items.",
        "docs_url": f"{_DOCS}/list-categories",
        "columns": {
            "id": "Unique identifier for the category.",
            "name": "Name of the category.",
            "type": "Type of item the category applies to.",
            "created_at": "Timestamp when the category was created.",
            "updated_at": "Timestamp when the category was last updated.",
        },
    },
    "manufacturers": {
        "description": "Manufacturers referenced by BlueTally assets, products, and licenses.",
        "docs_url": f"{_DOCS}/list-manufacturers",
        "columns": {
            "id": "Unique identifier for the manufacturer.",
            "name": "Name of the manufacturer.",
            "url": "Manufacturer's website URL.",
            "created_at": "Timestamp when the manufacturer was created.",
            "updated_at": "Timestamp when the manufacturer was last updated.",
        },
    },
    "suppliers": {
        "description": "Suppliers that BlueTally assets and other items were purchased from.",
        "docs_url": f"{_DOCS}/list-suppliers",
        "columns": {
            "id": "Unique identifier for the supplier.",
            "name": "Name of the supplier.",
            "created_at": "Timestamp when the supplier was created.",
            "updated_at": "Timestamp when the supplier was last updated.",
        },
    },
    "locations": {
        "description": "Physical locations where BlueTally assets and employees are based.",
        "docs_url": f"{_DOCS}/list-locations",
        "columns": {
            "id": "Unique identifier for the location.",
            "name": "Name of the location.",
            "city": "City of the location.",
            "country": "Country of the location.",
            "created_at": "Timestamp when the location was created.",
            "updated_at": "Timestamp when the location was last updated.",
        },
    },
    "departments": {
        "description": "Organizational departments used to group BlueTally assets and employees.",
        "docs_url": f"{_DOCS}/list-departments",
        "columns": {
            "id": "Unique identifier for the department.",
            "name": "Name of the department.",
            "created_at": "Timestamp when the department was created.",
            "updated_at": "Timestamp when the department was last updated.",
        },
    },
    "statuses": {
        "description": "Status labels (e.g. Deployable, Archived) that BlueTally assets can be assigned.",
        "docs_url": f"{_DOCS}/list-statuses",
        "columns": {
            "id": "Unique identifier for the status.",
            "name": "Name of the status.",
            "type": "Status type.",
            "created_at": "Timestamp when the status was created.",
            "updated_at": "Timestamp when the status was last updated.",
        },
    },
    "depreciations": {
        "description": "Depreciation schedules applied to BlueTally assets, licenses, and products.",
        "docs_url": f"{_DOCS}/list-depreciations",
        "columns": {
            "id": "Unique identifier for the depreciation schedule.",
            "name": "Name of the depreciation schedule.",
            "months": "Number of months over which the value depreciates.",
            "minimum_value": "Minimum (floor) value after depreciation.",
            "created_at": "Timestamp when the depreciation schedule was created.",
            "updated_at": "Timestamp when the depreciation schedule was last updated.",
        },
    },
    "maintenances": {
        "description": "Maintenance records logged against BlueTally assets.",
        "docs_url": f"{_DOCS}/list-maintenances",
        "columns": {
            "id": "Unique identifier for the maintenance record.",
            "type": "Type of maintenance.",
            "name": "Name of the maintenance record.",
            "start_date": "Date the maintenance started.",
            "end_date": "Date the maintenance ended.",
            "cost": "Cost of the maintenance.",
            "asset_id": "ID of the asset the maintenance applies to.",
            "supplier_id": "ID of the supplier that performed the maintenance.",
            "created_at": "Timestamp when the maintenance record was created.",
            "updated_at": "Timestamp when the maintenance record was last updated.",
        },
    },
    "audits": {
        "description": "Asset audit records in BlueTally, tracking scheduled and completed audits.",
        "docs_url": f"{_DOCS}/list-audits",
        "columns": {
            "id": "Unique identifier for the audit.",
            "audit_date": "Date the audit was performed.",
            "next_audit_date": "Date the next audit is scheduled for.",
            "scheduled": "Whether the audit is scheduled.",
            "completed": "Whether the audit has been completed.",
            "asset_id": "ID of the audited asset.",
            "location_id": "ID of the location where the audit took place.",
            "audit_status": "Status of the audit.",
            "created_at": "Timestamp when the audit was created.",
            "updated_at": "Timestamp when the audit was last updated.",
        },
    },
}
