"""Canonical, documentation-sourced descriptions for LaunchDarkly endpoints and columns.

Sourced from the official LaunchDarkly REST API reference (https://apidocs.launchdarkly.com).
Keyed by the endpoint names in `settings.py` `LAUNCHDARKLY_ENDPOINTS`, which match the
`ExternalDataSchema.name` of a synced LaunchDarkly table. Fan-out endpoints carry an injected
`_project_key` column identifying the project the row was fetched from. Columns absent here fall
back to LLM enrichment.
"""

from sources.sdk import CanonicalDescriptions

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "projects": {
        "description": "A LaunchDarkly project — a container for environments, feature flags, and metrics.",
        "docs_url": "https://apidocs.launchdarkly.com/tag/Projects",
        "columns": {
            "_id": "Unique identifier for the project.",
            "key": "The project's unique key.",
            "name": "The project's human-readable name.",
            "tags": "Tags applied to the project.",
            "environments": "The environments belonging to the project.",
        },
    },
    "members": {
        "description": "A member of the LaunchDarkly account.",
        "docs_url": "https://apidocs.launchdarkly.com/tag/Account-members",
        "columns": {
            "_id": "Unique identifier for the member.",
            "email": "The member's email address.",
            "firstName": "The member's first name.",
            "lastName": "The member's last name.",
            "role": "The member's built-in role (e.g. reader, writer, admin, owner).",
            "customRoles": "Custom roles assigned to the member.",
            "_pendingInvite": "Whether the member has a pending invitation.",
            "_lastSeen": "Time the member was last active, as an epoch-millisecond timestamp.",
        },
    },
    "auditlog": {
        "description": "An entry in the LaunchDarkly audit log recording a change made in the account.",
        "docs_url": "https://apidocs.launchdarkly.com/tag/Audit-log",
        "columns": {
            "_id": "Unique identifier for the audit log entry.",
            "date": "Time the change occurred, as an epoch-millisecond timestamp.",
            "kind": "The kind of resource the entry relates to.",
            "name": "Name of the resource that was changed.",
            "description": "Human-readable description of the change.",
            "member": "The member who made the change.",
            "titleVerb": "The action verb describing what happened.",
            "accesses": "The set of actions performed in this change.",
        },
    },
    "environments": {
        "description": "An environment within a LaunchDarkly project (e.g. production, staging).",
        "docs_url": "https://apidocs.launchdarkly.com/tag/Environments",
        "columns": {
            "_id": "Unique identifier for the environment.",
            "_project_key": "Key of the project this environment belongs to (injected during sync).",
            "key": "The environment's unique key within its project.",
            "name": "The environment's human-readable name.",
            "color": "The environment's display color.",
            "tags": "Tags applied to the environment.",
            "apiKey": "The environment's SDK API key.",
            "mobileKey": "The environment's mobile SDK key.",
            "defaultTtl": "Default time-to-live for the environment's flag settings.",
        },
    },
    "metrics": {
        "description": "A metric used to measure the impact of feature flags and experiments.",
        "docs_url": "https://apidocs.launchdarkly.com/tag/Metrics",
        "columns": {
            "_id": "Unique identifier for the metric.",
            "_project_key": "Key of the project this metric belongs to (injected during sync).",
            "key": "The metric's unique key within its project.",
            "name": "The metric's human-readable name.",
            "description": "Description of the metric.",
            "kind": "The metric's kind (e.g. custom, pageview, click).",
            "tags": "Tags applied to the metric.",
            "isNumeric": "Whether the metric measures a numeric value.",
            "unit": "The unit of the metric's measured value.",
        },
    },
    "flags": {
        "description": "A LaunchDarkly feature flag and its targeting configuration across environments.",
        "docs_url": "https://apidocs.launchdarkly.com/tag/Feature-flags",
        "columns": {
            "_project_key": "Key of the project this flag belongs to (injected during sync).",
            "key": "The flag's unique key within its project.",
            "name": "The flag's human-readable name.",
            "description": "Description of the flag.",
            "kind": "The flag's kind (boolean or multivariate).",
            "tags": "Tags applied to the flag.",
            "variations": "The set of variations the flag can serve.",
            "temporary": "Whether the flag is intended to be temporary.",
            "maintainerId": "ID of the member who maintains the flag.",
            "environments": "Per-environment targeting and rollout configuration for the flag.",
            "creationDate": "Time the flag was created, as an epoch-millisecond timestamp.",
        },
    },
    "segments": {
        "description": "A segment of contexts that flag targeting rules can include or exclude, per environment.",
        "docs_url": "https://apidocs.launchdarkly.com/tag/Segments",
        "columns": {
            "_project_key": "Key of the project this segment belongs to (injected during sync).",
            "_environment_key": "Key of the environment this segment belongs to (injected during sync).",
            "key": "The segment's unique key within its environment.",
            "name": "The segment's human-readable name.",
            "description": "Description of the segment's purpose.",
            "tags": "Tags applied to the segment.",
            "creationDate": "Time the segment was created, as an epoch-millisecond timestamp.",
            "lastModifiedDate": "Time the segment was last modified, as an epoch-millisecond timestamp.",
            "included": "Keys of targets that are always members of the segment.",
            "excluded": "Keys of targets that are never members of the segment through individual targeting.",
            "rules": "The targeting rules for the segment.",
            "version": "Version of the segment.",
            "deleted": "Whether the segment has been deleted.",
            "unbounded": "Whether this is a big segment (true) or a standard segment (false).",
        },
    },
    "flag_statuses": {
        "description": "The status of each feature flag in an environment, with the time it was last requested.",
        "docs_url": "https://apidocs.launchdarkly.com/tag/Feature-flags#operation/getFeatureFlagStatuses",
        "columns": {
            "_project_key": "Key of the project the flag belongs to (injected during sync).",
            "_environment_key": "Key of the environment the status applies to (injected during sync).",
            "_flag_key": "Key of the flag, taken from the status row's link (injected during sync).",
            "name": "The flag's status: new, active, inactive, or launched.",
            "lastRequested": "Time the flag was last requested in this environment.",
            "default": "The default value of the flag seen from code.",
        },
    },
    "experiments": {
        "description": "A LaunchDarkly experiment, including its current, draft, and previous iterations.",
        "docs_url": "https://apidocs.launchdarkly.com/tag/Experiments",
        "columns": {
            "_project_key": "Key of the project this experiment belongs to (injected during sync).",
            "_environment_key": "Key of the environment this experiment runs in (injected during sync).",
            "_id": "Unique identifier for the experiment.",
            "key": "The experiment's unique key.",
            "name": "The experiment's human-readable name.",
            "description": "Description of the experiment.",
            "_maintainerId": "ID of the member who maintains the experiment.",
            "_creationDate": "Time the experiment was created, as an epoch-millisecond timestamp.",
            "archivedDate": "Time the experiment was archived, as an epoch-millisecond timestamp.",
            "methodology": "The results analysis approach.",
            "dataSource": "The source of metric data used to analyze results.",
            "holdoutId": "ID of the holdout the experiment belongs to.",
            "currentIteration": "Details of the current iteration.",
            "draftIteration": "Details of the iteration that has not started yet, if any.",
            "previousIterations": "Details of the iterations before the current one.",
            "analysisConfig": "The analysis configuration of the experiment.",
            "tags": "Tags applied to the experiment.",
            "type": "The experiment type.",
        },
    },
    "holdouts": {
        "description": "A holdout that excludes a percentage of traffic from experiments to measure their overall effect.",
        "docs_url": "https://apidocs.launchdarkly.com/tag/Holdouts",
        "columns": {
            "_project_key": "Key of the project this holdout belongs to (injected during sync).",
            "_environment_key": "Key of the environment this holdout belongs to (injected during sync).",
            "_id": "Unique identifier for the holdout.",
            "key": "The holdout's key.",
            "name": "The holdout's human-readable name.",
            "status": "The holdout's status.",
            "createdAt": "Time the holdout was created, as an epoch-millisecond timestamp.",
            "updatedAt": "Time the holdout was last updated, as an epoch-millisecond timestamp.",
            "experiments": "The experiments that belong to the holdout.",
        },
    },
}
