from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "conversations": {
        "description": "A conversation between a contact and your team in one inbox, grouping the exchanged messages.",
        "docs_url": "https://developers.chatwoot.com/api-reference/conversations/conversations-list",
        "columns": {
            "id": "The conversation's display id, unique within the account. Also the id used in conversation URLs and API paths.",
            "uuid": "Globally unique identifier for the conversation.",
            "inbox_id": "Id of the inbox the conversation belongs to.",
            "status": "Current state of the conversation: open, resolved, pending, or snoozed.",
            "priority": "Priority assigned to the conversation (urgent, high, medium, low), if any.",
            "labels": "Labels attached to the conversation.",
            "muted": "Whether the conversation is muted.",
            "can_reply": "Whether the inbox channel still allows replying (e.g. within a messaging window).",
            "unread_count": "Number of unread messages in the conversation.",
            "custom_attributes": "Values of conversation-scoped custom attributes.",
            "additional_attributes": "Channel-specific metadata such as the browser, referer, or initiated-at details.",
            "snoozed_until": "When the conversation's snooze expires, if snoozed.",
            "waiting_since": "Unix timestamp since when the contact has been waiting for a reply.",
            "first_reply_created_at": "Unix timestamp of the first agent reply.",
            "agent_last_seen_at": "Unix timestamp when an agent last viewed the conversation.",
            "contact_last_seen_at": "Unix timestamp when the contact last viewed the conversation.",
            "last_activity_at": "Unix timestamp of the last activity in the conversation.",
            "created_at": "Unix timestamp when the conversation was created.",
            "updated_at": "Unix timestamp when the conversation was last updated.",
        },
    },
    "messages": {
        "description": "A single message within a conversation, including agent replies, contact messages, and templates.",
        "docs_url": "https://developers.chatwoot.com/api-reference/messages/messages-list",
        "columns": {
            "id": "Unique identifier for the message.",
            "conversation_id": "Display id of the conversation the message belongs to.",
            "content": "Text content of the message.",
            "content_type": "Content type of the message (text, input_select, cards, form, ...).",
            "content_attributes": "Structured attributes for rich content types.",
            "message_type": "Message direction/kind as an integer: 0 incoming, 1 outgoing, 2 activity, 3 template.",
            "private": "Whether the message is a private note visible only to agents.",
            "status": "Delivery status of the message (sent, delivered, read, failed).",
            "source_id": "Id of the message on the origin channel (e.g. the email message id).",
            "sender": "The user or contact who sent the message.",
            "attachments": "Files attached to the message.",
            "created_at": "Unix timestamp when the message was created.",
        },
    },
    "contacts": {
        "description": "A person your team talks to, identified by email, phone number, or an external identifier.",
        "docs_url": "https://developers.chatwoot.com/api-reference/contacts/contacts-list",
        "columns": {
            "id": "Unique identifier for the contact.",
            "name": "The contact's name.",
            "email": "The contact's email address.",
            "phone_number": "The contact's phone number.",
            "identifier": "External identifier you assigned to the contact.",
            "blocked": "Whether the contact is blocked.",
            "custom_attributes": "Values of contact-scoped custom attributes.",
            "additional_attributes": "Extra metadata such as company, location, or social profiles.",
            "last_activity_at": "Unix timestamp of the contact's last activity.",
            "created_at": "Unix timestamp when the contact was created.",
        },
    },
    "inboxes": {
        "description": "A channel through which conversations arrive, such as a website widget, email address, or WhatsApp number.",
        "docs_url": "https://developers.chatwoot.com/api-reference/inboxes/list-all-inboxes",
        "columns": {
            "id": "Unique identifier for the inbox.",
            "name": "Name of the inbox.",
            "channel_type": "The channel backing the inbox (Channel::WebWidget, Channel::Email, ...).",
            "greeting_enabled": "Whether the automatic greeting is enabled.",
            "working_hours_enabled": "Whether working hours are configured for the inbox.",
            "timezone": "Timezone used for the inbox's working hours.",
        },
    },
    "agents": {
        "description": "A user who is a member of the account, including their role and availability.",
        "docs_url": "https://developers.chatwoot.com/api-reference/agents/list-agents-in-account",
        "columns": {
            "id": "Unique identifier for the agent's user.",
            "name": "The agent's full name.",
            "available_name": "Display name shown to contacts.",
            "email": "The agent's email address.",
            "role": "The agent's role in the account: agent or administrator.",
            "availability_status": "Current availability: online, busy, or offline.",
            "auto_offline": "Whether the agent is automatically marked offline when away.",
            "confirmed": "Whether the agent's user account is confirmed.",
        },
    },
    "teams": {
        "description": "A group of agents used to organize and assign conversations.",
        "docs_url": "https://developers.chatwoot.com/api-reference/teams/list-all-teams",
        "columns": {
            "id": "Unique identifier for the team.",
            "name": "Name of the team.",
            "description": "Description of the team.",
            "allow_auto_assign": "Whether conversations assigned to the team are auto-assigned to its members.",
        },
    },
    "labels": {
        "description": "A label that can be attached to conversations and contacts for categorization.",
        "docs_url": "https://developers.chatwoot.com/api-reference/account-labels/list-all-labels",
        "columns": {
            "id": "Unique identifier for the label.",
            "title": "The label text.",
            "description": "Description of the label.",
            "color": "Display color of the label.",
            "show_on_sidebar": "Whether the label is pinned to the sidebar.",
        },
    },
    "custom_attribute_definitions": {
        "description": "Definition of a custom attribute that can be set on conversations, contacts, or companies.",
        "docs_url": "https://developers.chatwoot.com/api-reference/custom-attributes/list-all-custom-attributes-in-an-account",
        "columns": {
            "id": "Unique identifier for the custom attribute definition.",
            "attribute_display_name": "Human-readable name of the attribute.",
            "attribute_key": "Key under which values are stored in custom_attributes.",
            "attribute_display_type": "Input type of the attribute (text, number, date, list, checkbox, ...).",
            "attribute_model": "What the attribute applies to: 0 conversation, 1 contact, 2 company.",
            "attribute_values": "Allowed values for list-type attributes.",
            "created_at": "When the definition was created (ISO 8601 string).",
            "updated_at": "When the definition was last updated (ISO 8601 string).",
        },
    },
}
