#!/bin/sh

DIR_NAME=$(dirname "$0")

# Determine which executable to use based on architecture
case $( uname -m ) in
aarch64) 
    EXECUTABLE_NAME="aggregate_funnel_aarch64"
    ;;
*) 
    EXECUTABLE_NAME="aggregate_funnel_x86_64"
    ;;
esac

# Use mem_exec.py to run the executable from memory
python3 "$DIR_NAME/mem_exec.py" "$DIR_NAME/$EXECUTABLE_NAME" "$@"

