from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Descriptions sourced from the official Alpha Vantage API docs (https://www.alphavantage.co/documentation/).
# Column names match the normalized shape the transport emits (ordinal prefixes stripped, snake_cased).
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "time_series_daily": {
        "description": "Daily open/high/low/close/volume price bars for each configured symbol.",
        "docs_url": "https://www.alphavantage.co/documentation/#daily",
        "columns": {
            "symbol": "The ticker symbol the bar belongs to.",
            "date": "Trading day of the bar (YYYY-MM-DD).",
            "open": "Opening price for the trading day.",
            "high": "Highest price during the trading day.",
            "low": "Lowest price during the trading day.",
            "close": "Closing price for the trading day.",
            "volume": "Number of shares traded during the day.",
        },
    },
    "time_series_weekly": {
        "description": "Weekly open/high/low/close/volume price bars for each configured symbol.",
        "docs_url": "https://www.alphavantage.co/documentation/#weekly",
        "columns": {
            "symbol": "The ticker symbol the bar belongs to.",
            "date": "Last trading day of the week (YYYY-MM-DD).",
            "open": "Opening price for the week.",
            "high": "Highest price during the week.",
            "low": "Lowest price during the week.",
            "close": "Closing price for the week.",
            "volume": "Number of shares traded during the week.",
        },
    },
    "time_series_monthly": {
        "description": "Monthly open/high/low/close/volume price bars for each configured symbol.",
        "docs_url": "https://www.alphavantage.co/documentation/#monthly",
        "columns": {
            "symbol": "The ticker symbol the bar belongs to.",
            "date": "Last trading day of the month (YYYY-MM-DD).",
            "open": "Opening price for the month.",
            "high": "Highest price during the month.",
            "low": "Lowest price during the month.",
            "close": "Closing price for the month.",
            "volume": "Number of shares traded during the month.",
        },
    },
    "global_quote": {
        "description": "Latest price and trading-day snapshot for each configured symbol (one row per symbol).",
        "docs_url": "https://www.alphavantage.co/documentation/#latestprice",
        "columns": {
            "symbol": "The ticker symbol.",
            "open": "Opening price for the latest trading day.",
            "high": "Highest price for the latest trading day.",
            "low": "Lowest price for the latest trading day.",
            "price": "Most recent price.",
            "volume": "Shares traded on the latest trading day.",
            "latest_trading_day": "Date of the latest trading day (YYYY-MM-DD).",
            "previous_close": "Closing price of the previous trading day.",
            "change": "Absolute price change from the previous close.",
            "change_percent": "Percentage price change from the previous close.",
        },
    },
    "company_overview": {
        "description": "Company fundamentals, valuation ratios, and descriptive information per symbol.",
        "docs_url": "https://www.alphavantage.co/documentation/#company-overview",
        "columns": {
            "symbol": "The ticker symbol.",
            "name": "Company name.",
            "description": "Company description.",
            "exchange": "Exchange the security trades on.",
            "currency": "Reporting currency.",
            "country": "Country of incorporation.",
            "sector": "Sector the company operates in.",
            "industry": "Industry classification.",
            "marketcapitalization": "Market capitalization.",
            "peratio": "Price-to-earnings ratio.",
            "dividendyield": "Annual dividend yield.",
            "eps": "Earnings per share.",
        },
    },
    "income_statement": {
        "description": "Annual and quarterly income statements per symbol; one row per report period.",
        "docs_url": "https://www.alphavantage.co/documentation/#income-statement",
        "columns": {
            "symbol": "The ticker symbol.",
            "report_type": "Whether the row is an 'annual' or 'quarterly' report.",
            "fiscalDateEnding": "Fiscal period end date (YYYY-MM-DD).",
            "reportedCurrency": "Currency the figures are reported in.",
            "totalRevenue": "Total revenue for the period.",
            "grossProfit": "Gross profit for the period.",
            "operatingIncome": "Operating income for the period.",
            "netIncome": "Net income for the period.",
        },
    },
    "balance_sheet": {
        "description": "Annual and quarterly balance sheets per symbol; one row per report period.",
        "docs_url": "https://www.alphavantage.co/documentation/#balance-sheet",
        "columns": {
            "symbol": "The ticker symbol.",
            "report_type": "Whether the row is an 'annual' or 'quarterly' report.",
            "fiscalDateEnding": "Fiscal period end date (YYYY-MM-DD).",
            "reportedCurrency": "Currency the figures are reported in.",
            "totalAssets": "Total assets at period end.",
            "totalLiabilities": "Total liabilities at period end.",
            "totalShareholderEquity": "Total shareholder equity at period end.",
        },
    },
    "cash_flow": {
        "description": "Annual and quarterly cash-flow statements per symbol; one row per report period.",
        "docs_url": "https://www.alphavantage.co/documentation/#cash-flow",
        "columns": {
            "symbol": "The ticker symbol.",
            "report_type": "Whether the row is an 'annual' or 'quarterly' report.",
            "fiscalDateEnding": "Fiscal period end date (YYYY-MM-DD).",
            "reportedCurrency": "Currency the figures are reported in.",
            "operatingCashflow": "Cash generated by operating activities.",
            "capitalExpenditures": "Capital expenditures for the period.",
        },
    },
    "earnings": {
        "description": "Annual and quarterly reported earnings per share per symbol; one row per report period.",
        "docs_url": "https://www.alphavantage.co/documentation/#earnings",
        "columns": {
            "symbol": "The ticker symbol.",
            "report_type": "Whether the row is an 'annual' or 'quarterly' report.",
            "fiscalDateEnding": "Fiscal period end date (YYYY-MM-DD).",
            "reportedDate": "Date the earnings were reported (quarterly only).",
            "reportedEPS": "Reported earnings per share.",
            "estimatedEPS": "Analyst-estimated earnings per share (quarterly only).",
            "surprise": "Difference between reported and estimated EPS (quarterly only).",
            "surprisePercentage": "Percentage EPS surprise (quarterly only).",
        },
    },
}
