export interface EventPipelineRunnerOptions {
    SKIP_UPDATE_EVENT_AND_PROPERTIES_STEP: boolean
    PERSON_MERGE_MOVE_DISTINCT_ID_LIMIT: number
    PERSON_MERGE_ASYNC_ENABLED: boolean
    PERSON_MERGE_ASYNC_TOPIC: string
    PERSON_MERGE_SYNC_BATCH_SIZE: number
    PERSON_JSONB_SIZE_ESTIMATE_ENABLE: number
    PERSON_PROPERTIES_UPDATE_ALL: boolean
}
