from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

_ENTITY_DOCS = "https://developers.google.com/display-video/api/reference/rest/v4"
_REPORT_DOCS = "https://developers.google.com/bid-manager/reference/rest/v2/queries"

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "partners": {
        "description": "A Display & Video 360 partner — the top-level account that owns advertisers, billing, and platform-wide settings.",
        "docs_url": f"{_ENTITY_DOCS}/partners",
        "columns": {
            "name": "Resource name of the partner.",
            "partnerId": "Unique ID of the partner. Assigned by the system.",
            "displayName": "Display name of the partner, shown in the Display & Video 360 UI.",
            "entityStatus": "Whether the partner is active, paused, archived, or scheduled for deletion.",
            "updateTime": "Timestamp when the partner was last updated. Assigned by the system.",
            "generalConfig": "General settings for the partner, including its time zone and currency code.",
            "adServerConfig": "Ad server settings, including third-party-only or Campaign Manager 360 configuration.",
            "dataAccessConfig": "Settings controlling how partner data can be accessed, including SDF configuration.",
            "exchangeConfig": "Exchanges enabled for the partner and their seat IDs.",
        },
    },
    "advertisers": {
        "description": "An advertiser under a partner. Advertisers own campaigns, insertion orders, line items, and creatives.",
        "docs_url": f"{_ENTITY_DOCS}/advertisers",
        "columns": {
            "name": "Resource name of the advertiser.",
            "advertiserId": "Unique ID of the advertiser. Assigned by the system.",
            "partnerId": "Unique ID of the partner the advertiser belongs to.",
            "displayName": "Display name of the advertiser.",
            "entityStatus": "Whether the advertiser is active, paused, archived, or scheduled for deletion.",
            "updateTime": "Timestamp when the advertiser was last updated. Assigned by the system.",
            "generalConfig": "General settings for the advertiser, including its domain URL and currency code.",
            "adServerConfig": "Ad server settings for the advertiser.",
            "creativeConfig": "Creative-related settings, such as whether dynamic creatives are enabled.",
            "dataAccessConfig": "Settings controlling how advertiser data can be accessed.",
            "integrationDetails": "Integration details, including the integration code and free-form details.",
            "servingConfig": "Targeting settings related to the advertiser's serving, such as political ads.",
            "prismaEnabled": "Whether integration with Mediaocean Prisma is enabled.",
            "billingConfig": "Billing settings for the advertiser, including the billing profile.",
        },
    },
    "campaigns": {
        "description": "A campaign belonging to an advertiser. Campaigns group insertion orders and hold the overall goal and flight dates.",
        "docs_url": f"{_ENTITY_DOCS}/advertisers.campaigns",
        "columns": {
            "name": "Resource name of the campaign.",
            "campaignId": "Unique ID of the campaign. Assigned by the system.",
            "advertiserId": "Unique ID of the advertiser the campaign belongs to.",
            "displayName": "Display name of the campaign.",
            "entityStatus": "Whether the campaign is active, paused, archived, or scheduled for deletion.",
            "updateTime": "Timestamp when the campaign was last updated. Assigned by the system.",
            "campaignGoal": "The goal of the campaign, including the goal type and performance goal.",
            "campaignFlight": "The planned spend and duration of the campaign.",
            "campaignBudgets": "List of budgets available to the campaign's insertion orders.",
            "frequencyCap": "Frequency cap setting applied to the campaign.",
        },
    },
    "insertion_orders": {
        "description": "An insertion order under a campaign. Insertion orders group line items and carry the budget, pacing, and bidding strategy.",
        "docs_url": f"{_ENTITY_DOCS}/advertisers.insertionOrders",
        "columns": {
            "name": "Resource name of the insertion order.",
            "insertionOrderId": "Unique ID of the insertion order. Assigned by the system.",
            "advertiserId": "Unique ID of the advertiser the insertion order belongs to.",
            "campaignId": "Unique ID of the campaign the insertion order belongs to.",
            "displayName": "Display name of the insertion order.",
            "entityStatus": "Whether the insertion order is active, paused, draft, or archived.",
            "updateTime": "Timestamp when the insertion order was last updated. Assigned by the system.",
            "insertionOrderType": "The type of insertion order, for example RTB or over-the-top.",
            "pacing": "Pacing setting controlling how the budget is spent over time.",
            "frequencyCap": "Frequency cap setting for the insertion order.",
            "kpi": "The key performance indicator the insertion order is measured against.",
            "budget": "Budget allocation settings, including the budget unit and budget segments.",
            "bidStrategy": "Bidding strategy applied to the insertion order.",
            "performanceGoal": "Performance goal of the insertion order.",
            "billableOutcome": "The billable outcome of the insertion order.",
        },
    },
    "line_items": {
        "description": "A line item under an insertion order. Line items hold the targeting, budget, pacing, bidding, and creative assignments that actually serve.",
        "docs_url": f"{_ENTITY_DOCS}/advertisers.lineItems",
        "columns": {
            "name": "Resource name of the line item.",
            "lineItemId": "Unique ID of the line item. Assigned by the system.",
            "advertiserId": "Unique ID of the advertiser the line item belongs to.",
            "campaignId": "Unique ID of the campaign the line item belongs to.",
            "insertionOrderId": "Unique ID of the insertion order the line item belongs to.",
            "displayName": "Display name of the line item.",
            "entityStatus": "Whether the line item is active, paused, draft, or archived.",
            "updateTime": "Timestamp when the line item was last updated. Assigned by the system.",
            "lineItemType": "The type of line item, which determines the settings and options it supports.",
            "flight": "Start and end time of the line item's flight.",
            "budget": "Budget allocation setting for the line item.",
            "pacing": "Pacing setting controlling how the budget is spent over time.",
            "frequencyCap": "Frequency cap setting for the line item.",
            "partnerRevenueModel": "The partner revenue model applied to the line item.",
            "conversionCounting": "Conversion tracking setting for the line item.",
            "creativeIds": "IDs of the creatives assigned to the line item.",
            "bidStrategy": "Bidding strategy applied to the line item.",
            "targetingExpansion": "Optimized targeting settings for the line item.",
            "warningMessages": "Warnings generated for the line item that may affect delivery.",
            "reservationType": "The reservation type of the line item, for example programmatic guaranteed.",
        },
    },
    "creatives": {
        "description": "A creative belonging to an advertiser, including its type, dimensions, review status, and hosted assets.",
        "docs_url": f"{_ENTITY_DOCS}/advertisers.creatives",
        "columns": {
            "name": "Resource name of the creative.",
            "creativeId": "Unique ID of the creative. Assigned by the system, unique within its advertiser.",
            "advertiserId": "Unique ID of the advertiser the creative belongs to.",
            "displayName": "Display name of the creative.",
            "entityStatus": "Whether the creative is active, paused, or archived.",
            "createTime": "Timestamp when the creative was created. Assigned by the system.",
            "updateTime": "Timestamp when the creative was last updated. Assigned by the system.",
            "creativeType": "The type of creative, for example standard, video, or audio.",
            "dimensions": "Width and height of the creative in pixels.",
            "hostingSource": "Where the creative is hosted, for example hosted by Display & Video 360 or a third party.",
            "dynamic": "Whether the creative is dynamic.",
            "mediaDuration": "Duration of the audio or video creative.",
            "creativeAttributes": "Attributes detected for the creative by the system.",
            "reviewStatus": "Review status of the creative, including per-exchange and publisher review results.",
            "assets": "Assets associated with the creative.",
            "exitEvents": "Exit events (click-through URLs) for the creative.",
            "expandingDirection": "The expanding direction of an expandable creative.",
            "iasCampaignMonitoring": "Whether Integral Ad Science campaign monitoring is enabled.",
            "cmTrackingAd": "The Campaign Manager 360 tracking ad associated with the creative.",
        },
    },
    "advertiser_performance": {
        "description": "Daily Bid Manager performance metrics grouped by date and advertiser. Generated by a one-time Bid Manager report per sync window.",
        "docs_url": _REPORT_DOCS,
        "columns": {
            "date": "The day the metrics were recorded, in the partner's reporting time zone.",
            "advertiser": "Display name of the advertiser.",
            "advertiser_id": "Unique ID of the advertiser.",
            "advertiser_currency": "Currency the advertiser's spend is reported in.",
            "impressions": "Number of impressions served.",
            "billable_impressions": "Number of impressions counted as billable.",
            "clicks": "Number of clicks recorded.",
            "click_rate": "Click-through rate: clicks divided by impressions.",
            "total_conversions": "Total post-click and post-view conversions attributed.",
            "post_click_conversions": "Conversions attributed to a click on the ad.",
            "post_view_conversions": "Conversions attributed to an impression without a click.",
            "revenue_advertiser_currency": "Revenue in the advertiser's currency.",
            "media_cost_advertiser_currency": "Media cost in the advertiser's currency.",
        },
    },
    "line_item_performance": {
        "description": "Daily Bid Manager performance metrics grouped by date, advertiser, insertion order, and line item. Generated by a one-time Bid Manager report per sync window.",
        "docs_url": _REPORT_DOCS,
        "columns": {
            "date": "The day the metrics were recorded, in the partner's reporting time zone.",
            "advertiser": "Display name of the advertiser.",
            "advertiser_id": "Unique ID of the advertiser.",
            "advertiser_currency": "Currency the advertiser's spend is reported in.",
            "insertion_order": "Display name of the insertion order.",
            "insertion_order_id": "Unique ID of the insertion order.",
            "line_item": "Display name of the line item.",
            "line_item_id": "Unique ID of the line item.",
            "impressions": "Number of impressions served.",
            "billable_impressions": "Number of impressions counted as billable.",
            "clicks": "Number of clicks recorded.",
            "click_rate": "Click-through rate: clicks divided by impressions.",
            "total_conversions": "Total post-click and post-view conversions attributed.",
            "post_click_conversions": "Conversions attributed to a click on the ad.",
            "post_view_conversions": "Conversions attributed to an impression without a click.",
            "revenue_advertiser_currency": "Revenue in the advertiser's currency.",
            "media_cost_advertiser_currency": "Media cost in the advertiser's currency.",
        },
    },
}
