"""Canonical, documentation-sourced descriptions for HitPay endpoints and columns.

Sourced from the official HitPay API reference (https://docs.hitpayapp.com/reference). Keyed by
the resource names in `settings.py` `ENDPOINTS`, which match the `ExternalDataSchema.name` of a
synced HitPay table. Columns absent here fall back to LLM enrichment.
"""

from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "PaymentRequests": {
        "description": "A payment link a merchant creates to collect a specific amount via card, PayNow, FPX, GrabPay, or another supported method.",
        "docs_url": "https://docs.hitpayapp.com/reference/get_payment-requests",
        "columns": {
            "id": "Unique identifier for the payment request.",
            "name": "Name of the customer the request was created for.",
            "email": "Email address the payment request was sent to.",
            "phone": "Phone number the payment request was sent to.",
            "amount": "Amount requested, as a decimal string in the request's currency.",
            "currency": "Three-letter currency code for the amount (e.g. sgd, myr).",
            "status": "Payment status: pending, completed, failed, expired, canceled, or inactive.",
            "purpose": "Free-text description of what the payment is for.",
            "reference_number": "Merchant-supplied reference number for the request.",
            "payment_methods": "Payment methods enabled for this request (e.g. card, paynow).",
            "url": "Hosted checkout URL the customer pays at.",
            "redirect_url": "URL the customer is redirected to after paying.",
            "webhook": "URL HitPay calls with payment status updates for this request.",
            "allow_repeated_payments": "Whether the same link can be paid more than once.",
            "expiry_date": "Date and time after which the request can no longer be paid.",
            "created_at": "Time the payment request was created.",
            "updated_at": "Time the payment request was last updated.",
        },
    },
    "Charges": {
        "description": "A completed attempt to collect payment, created from a payment request or another checkout flow.",
        "docs_url": "https://docs.hitpayapp.com/reference/get_charges",
        "columns": {
            "id": "Unique identifier for the charge.",
            "currency": "Three-letter currency code the charge was collected in.",
            "home_currency": "Three-letter currency code of the merchant's settlement currency.",
            "exchange_rate": "Exchange rate applied between the charge and home currency, if they differ.",
            "amount": "Amount collected, as a decimal in the charge's currency.",
            "fixed_fee": "Fixed processing fee charged by HitPay for this transaction.",
            "discount_fee": "Percentage-based processing fee charged by HitPay for this transaction.",
            "discount_fee_rate": "Percentage rate used to calculate discount_fee.",
            "remark": "Free-text note attached to the charge.",
            "status": "Charge status (e.g. succeeded, failed, refunded, partially_refunded, void).",
            "payment_method": "Payment method used, including card brand and last 4 digits where applicable.",
            "customer_id": "Identifier of the customer this charge belongs to, if any.",
            "payment_request_id": "Identifier of the payment request this charge fulfilled, if any.",
            "order_reference_number": "Merchant-supplied order reference associated with the charge.",
            "channel": "Origin of the charge (e.g. api, point of sale, checkout link).",
            "closed_at": "Time the charge was finalized (e.g. captured or settled).",
            "created_at": "Time the charge was created.",
            "updated_at": "Time the charge was last updated.",
        },
    },
    "SubscriptionPlans": {
        "description": "A recurring billing plan template merchants can subscribe customers to.",
        "docs_url": "https://docs.hitpayapp.com/reference/get_subscription-plan",
        "columns": {
            "id": "Unique identifier for the subscription plan.",
            "name": "Name of the plan.",
            "description": "Description of the plan.",
            "cycle": "Billing cycle type (e.g. daily, weekly, monthly, custom).",
            "cycle_repeat": "Number of cycle units between charges, for custom cycles.",
            "cycle_frequency": "Unit of the custom cycle (e.g. day, week, month).",
            "currency": "Three-letter currency code for the plan's price.",
            "price": "List price of the plan.",
            "amount": "Amount charged per billing cycle.",
            "reference": "Merchant-supplied reference for the plan.",
            "created_at": "Time the plan was created.",
            "updated_at": "Time the plan was last updated.",
        },
    },
    "Customers": {
        "description": "A saved customer record used to associate charges, payment requests, and recurring billing.",
        "docs_url": "https://docs.hitpayapp.com/reference/get_customers",
        "columns": {
            "id": "Unique identifier for the customer.",
            "name": "Customer's full name.",
            "email": "Customer's email address.",
            "phone_number": "Customer's phone number.",
            "phone_number_country_code": "Country code for the customer's phone number.",
            "birth_date": "Customer's date of birth.",
            "gender": "Customer's gender, if provided.",
            "address": "Customer's billing address (city, state, street, postal code, country).",
            "remark": "Free-text note attached to the customer.",
            "created_at": "Time the customer record was created.",
            "updated_at": "Time the customer record was last updated.",
        },
    },
    "RecurringBilling": {
        "description": "A recurring billing agreement charging a customer on a schedule, either from a subscription plan or a saved card.",
        "docs_url": "https://docs.hitpayapp.com/reference/get_recurring-billing",
        "columns": {
            "id": "Unique identifier for the recurring billing agreement.",
            "business_recurring_plans_id": "Identifier of the subscription plan this billing is based on, if any.",
            "customer_name": "Name of the customer being billed.",
            "customer_email": "Email address of the customer being billed.",
            "name": "Name of the recurring billing agreement.",
            "description": "Description of the recurring billing agreement.",
            "reference": "Merchant-supplied reference for the agreement.",
            "cycle": "Billing cycle type (e.g. daily, weekly, monthly, custom, save_card).",
            "cycle_repeat": "Number of cycle units between charges, for custom cycles.",
            "cycle_frequency": "Unit of the custom cycle (e.g. day, week, month).",
            "currency": "Three-letter currency code for the billed amount.",
            "price": "List price per billing cycle.",
            "amount": "Amount charged per billing cycle.",
            "times_to_be_charged": "Total number of charges planned for this agreement, if limited.",
            "times_charged": "Number of charges collected so far.",
            "status": "Agreement status: active, scheduled, retrying, inactive, or canceled.",
            "payment_methods": "Payment methods enabled for this agreement.",
            "created_at": "Time the agreement was created.",
            "updated_at": "Time the agreement was last updated.",
        },
    },
}
