from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Descriptions sourced from the Fireworks AI API reference (https://docs.fireworks.ai/api-reference).
# Keyed by endpoint name as returned by get_schemas / declared in settings.ENDPOINTS.

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "models": {
        "description": "Models available in your Fireworks AI account, including base models and fine-tuned (PEFT addon) models.",
        "docs_url": "https://docs.fireworks.ai/api-reference/list-models",
        "columns": {
            "name": "Unique resource name of the model, e.g. accounts/my-account/models/my-model.",
            "displayName": "Human-readable display name of the model.",
            "description": "Free-text description of the model.",
            "createTime": "When the model was created.",
            "updateTime": "When the model was last updated.",
            "state": "Lifecycle state of the model (UPLOADING, READY).",
            "kind": "Kind of model (e.g. HF_BASE_MODEL, HF_PEFT_ADDON, EMBEDDING_MODEL).",
            "contextLength": "Maximum context length supported by the model.",
            "supportsImageInput": "Whether the model accepts image input.",
            "supportsTools": "Whether the model supports tool/function calling.",
            "supportsLora": "Whether the model supports LoRA addons.",
            "supportsServerless": "Whether the model can be served serverlessly.",
            "fineTuningJob": "Resource name of the fine-tuning job that produced the model, if any.",
            "public": "Whether the model is publicly visible.",
            "deprecationDate": "Date the model is or will be deprecated, if scheduled.",
        },
    },
    "datasets": {
        "description": "Datasets uploaded to or generated in your Fireworks AI account for fine-tuning and evaluation.",
        "docs_url": "https://docs.fireworks.ai/api-reference/list-datasets",
        "columns": {
            "name": "Unique resource name of the dataset, e.g. accounts/my-account/datasets/my-dataset.",
            "displayName": "Human-readable display name of the dataset.",
            "createTime": "When the dataset was created.",
            "updateTime": "When the dataset was last updated.",
            "state": "Lifecycle state of the dataset (UPLOADING, READY).",
            "status": "Code and message describing the latest operation's outcome.",
            "exampleCount": "Number of examples in the dataset.",
            "format": "Dataset format (CHAT, COMPLETION, RL).",
            "createdBy": "Identity of the user who created the dataset.",
            "sourceJobName": "Resource name of the job that generated the dataset, if any.",
            "estimatedTokenCount": "Estimated number of tokens in the dataset.",
        },
    },
    "deployments": {
        "description": "Dedicated model deployments in your Fireworks AI account, including autoscaling and hardware configuration.",
        "docs_url": "https://docs.fireworks.ai/api-reference/list-deployments",
        "columns": {
            "name": "Unique resource name of the deployment, e.g. accounts/my-account/deployments/my-deployment.",
            "displayName": "Human-readable display name of the deployment.",
            "createTime": "When the deployment was created.",
            "updateTime": "When the deployment was last updated.",
            "state": "Lifecycle state of the deployment (CREATING, READY, DELETING, FAILED, UPDATING, DELETED).",
            "status": "Code and message describing the latest operation's outcome.",
            "baseModel": "Resource name of the model being served.",
            "minReplicaCount": "Autoscaling floor for the number of replicas.",
            "maxReplicaCount": "Autoscaling ceiling for the number of replicas.",
            "replicaCount": "Current number of replicas.",
            "acceleratorCount": "Number of accelerators (GPUs) per replica.",
            "acceleratorType": "Accelerator hardware type (e.g. A100, H100, MI300X).",
            "precision": "Serving precision (e.g. FP16, FP8, BF16).",
            "region": "Region the deployment currently runs in.",
        },
    },
    "deployed_models": {
        "description": "Models loaded onto deployments (including LoRA addons), mapping each model to the deployment serving it.",
        "docs_url": "https://docs.fireworks.ai/api-reference/list-deployed-models",
        "columns": {
            "name": "Unique resource name of the deployed model, e.g. accounts/my-account/deployedModels/my-deployed-model.",
            "displayName": "Human-readable display name of the deployed model.",
            "createTime": "When the deployed model was created.",
            "updateTime": "When the deployed model was last updated.",
            "model": "Resource name of the model being deployed.",
            "deployment": "Resource name of the deployment serving the model.",
            "default": "Whether this target is used when the model is queried without a deployment suffix.",
            "state": "Lifecycle state (DEPLOYING, DEPLOYED, UPDATING, UNDEPLOYING).",
            "serverless": "Whether the underlying deployment is managed by Fireworks.",
            "public": "Whether the deployed model is publicly reachable.",
        },
    },
    "supervised_fine_tuning_jobs": {
        "description": "Supervised fine-tuning (SFT) jobs run in your Fireworks AI account, with training configuration and progress.",
        "docs_url": "https://docs.fireworks.ai/api-reference/list-supervised-fine-tuning-jobs",
        "columns": {
            "name": "Unique resource name of the fine-tuning job.",
            "displayName": "Human-readable display name of the job.",
            "createTime": "When the job was created.",
            "completedTime": "When the job finished.",
            "updateTime": "When the job was last updated.",
            "state": "Job lifecycle state (e.g. JOB_STATE_RUNNING, JOB_STATE_COMPLETED, JOB_STATE_FAILED).",
            "status": "Code and message describing the latest operation's outcome.",
            "createdBy": "Email of the user who created the job.",
            "dataset": "Resource name of the training dataset.",
            "evaluationDataset": "Resource name of the evaluation dataset, if any.",
            "baseModel": "Resource name of the base model being fine-tuned.",
            "outputModel": "Resource name of the model produced by the job.",
            "epochs": "Number of training epochs.",
            "learningRate": "Training learning rate.",
            "loraRank": "LoRA rank used for training.",
            "jobProgress": "Progress details for the job.",
            "estimatedCost": "Estimated cost of the job.",
        },
    },
    "reinforcement_fine_tuning_jobs": {
        "description": "Reinforcement fine-tuning (RFT) jobs run in your Fireworks AI account, with training/rollout configuration and progress.",
        "docs_url": "https://docs.fireworks.ai/api-reference/list-reinforcement-fine-tuning-jobs",
        "columns": {
            "name": "Unique resource name of the reinforcement fine-tuning job.",
            "displayName": "Human-readable display name of the job.",
            "createTime": "When the job was created.",
            "completedTime": "When the job finished.",
            "state": "Job lifecycle state (e.g. running, completed, failed).",
            "status": "Code and message describing the latest operation's outcome.",
            "createdBy": "Email of the user who created the job.",
            "dataset": "Resource name of the training dataset.",
            "evaluator": "Resource name of the evaluator used to score rollouts.",
            "trainingConfig": "Common training settings (base model, learning rate, LoRA, epochs).",
            "jobProgress": "Progress details for the job.",
            "outputMetrics": "Output metrics of the job.",
        },
    },
    "batch_inference_jobs": {
        "description": "Batch inference jobs run in your Fireworks AI account, mapping input datasets to output datasets.",
        "docs_url": "https://docs.fireworks.ai/api-reference/list-batch-inference-jobs",
        "columns": {
            "name": "Unique resource name of the batch inference job.",
            "displayName": "Human-readable display name of the job.",
            "createTime": "When the job was created.",
            "updateTime": "When the job was last updated.",
            "state": "Job lifecycle state (e.g. RUNNING, COMPLETED, FAILED).",
            "status": "Code and message describing the latest operation's outcome.",
            "createdBy": "Email of the user who started the job.",
            "model": "Model used for inference.",
            "inputDatasetId": "Dataset supplying the inputs.",
            "outputDatasetId": "Dataset holding the results (also contains the error file).",
            "inferenceParameters": "Sampling settings (maxTokens, temperature, topP, topK, n).",
            "precision": "Serving precision used for the job.",
            "jobProgress": "Progress stats (percent, request counts, token counts, output rows).",
        },
    },
    "evaluation_jobs": {
        "description": "Evaluation jobs run in your Fireworks AI account, scoring a dataset with an evaluator.",
        "docs_url": "https://docs.fireworks.ai/api-reference/list-evaluation-jobs",
        "columns": {
            "name": "Unique resource name of the evaluation job.",
            "displayName": "Human-readable display name of the job.",
            "createTime": "When the job was created.",
            "updateTime": "When the job was last updated.",
            "state": "Job lifecycle state (e.g. running, completed, failed).",
            "status": "Code and message describing the latest operation's outcome.",
            "createdBy": "Identity of the user who created the job.",
            "evaluator": "Resource name of the evaluator used.",
            "inputDataset": "Resource name of the input dataset.",
            "outputDataset": "Resource name of the dataset created by the job.",
            "metrics": "Map of metric names to numeric values.",
        },
    },
    "evaluators": {
        "description": "Evaluators defined in your Fireworks AI account, used to score fine-tuning rollouts and evaluation jobs.",
        "docs_url": "https://docs.fireworks.ai/api-reference/list-evaluators",
        "columns": {
            "name": "Unique resource name of the evaluator.",
            "displayName": "Human-readable display name of the evaluator.",
            "description": "Free-text description of the evaluator.",
            "createTime": "When the evaluator was created.",
            "updateTime": "When the evaluator was last updated.",
            "createdBy": "Identity of the user who created the evaluator.",
            "state": "Lifecycle state (ACTIVE, BUILDING, BUILD_FAILED).",
            "criteria": "Scoring criteria, each producing a score for its metric.",
            "entryPoint": "Code entry point in module::function or path::function format.",
            "commitHash": "Commit hash from the user's original codebase.",
        },
    },
    "users": {
        "description": "Users and service accounts with access to your Fireworks AI account.",
        "docs_url": "https://docs.fireworks.ai/api-reference/list-users",
        "columns": {
            "name": "Unique resource name of the user, e.g. accounts/my-account/users/my-user.",
            "displayName": "Human-readable display name of the user.",
            "createTime": "When the user was added to the account.",
            "updateTime": "When the user was last updated.",
            "email": "Email address of the user.",
            "role": "Role of the user in the account (admin, user, contributor, inference-user, or custom).",
            "serviceAccount": "Whether this user is a service account.",
            "state": "Lifecycle state of the user (CREATING, READY, UPDATING, DELETING).",
            "status": "Code and message describing the latest operation's outcome.",
        },
    },
}
