import {
    AndroidInstructions,
    AngularInstructions,
    AstroInstructions,
    BubbleInstructions,
    DocusaurusInstructions,
    FlutterInstructions,
    FramerInstructions,
    GoogleTagManagerInstructions,
    HTMLSnippetInstructions,
    JSWebInstructions,
    NextJSInstructions,
    NuxtJSInstructions,
    ReactInstructions,
    RemixInstructions,
    ShopifyInstructions,
    SvelteInstructions,
    VueInstructions,
    WebAnalyticsRNInstructions,
    WebflowInstructions,
    WordpressInstructions,
    iOSInstructions,
} from '.'

import { SDKInstructionsMap, SDKKey } from '~/types'

export const WebAnalyticsSDKInstructions: SDKInstructionsMap = {
    [SDKKey.JS_WEB]: JSWebInstructions,
    [SDKKey.HTML_SNIPPET]: HTMLSnippetInstructions,
    [SDKKey.ANGULAR]: AngularInstructions,
    [SDKKey.ASTRO]: AstroInstructions,
    [SDKKey.BUBBLE]: BubbleInstructions,
    [SDKKey.DOCUSAURUS]: DocusaurusInstructions,
    [SDKKey.FRAMER]: FramerInstructions,
    [SDKKey.GOOGLE_TAG_MANAGER]: GoogleTagManagerInstructions,
    [SDKKey.NEXT_JS]: NextJSInstructions,
    [SDKKey.NUXT_JS]: NuxtJSInstructions,
    [SDKKey.REACT]: ReactInstructions,
    [SDKKey.REMIX]: RemixInstructions,
    [SDKKey.SHOPIFY]: ShopifyInstructions,
    [SDKKey.SVELTE]: SvelteInstructions,
    [SDKKey.TANSTACK_START]: ReactInstructions,
    [SDKKey.VITE]: ReactInstructions,
    [SDKKey.VUE_JS]: VueInstructions,
    [SDKKey.WEBFLOW]: WebflowInstructions,
    [SDKKey.WORDPRESS]: WordpressInstructions,
    [SDKKey.ANDROID]: AndroidInstructions,
    [SDKKey.FLUTTER]: FlutterInstructions,
    [SDKKey.IOS]: iOSInstructions,
    [SDKKey.REACT_NATIVE]: WebAnalyticsRNInstructions,
}
