from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)
from products.warehouse_sources.backend.temporal.data_imports.sources.pardot.settings import PARDOT_ENDPOINTS

_DOCS_BASE = "https://developer.salesforce.com/docs/marketing/pardot/guide"

_SHARED_COLUMNS = {
    "id": "Account Engagement ID of the record.",
    "createdAt": "Timestamp of when the record was created.",
    "updatedAt": "Timestamp of the last update to the record.",
    "createdById": "ID of the user who created the record.",
    "updatedById": "ID of the user who last updated the record.",
    "isDeleted": "Whether the record is in the recycle bin.",
    "salesforceId": "ID of the matching record in Salesforce.",
    "campaignId": "ID of the campaign associated with the record.",
    "folderId": "ID of the folder that contains the record.",
    "name": "Name of the record.",
}


def _shared(endpoint: str) -> dict[str, str]:
    """The shared column blurbs that the endpoint actually returns."""
    fields = set(PARDOT_ENDPOINTS[endpoint].fields)
    return {name: description for name, description in _SHARED_COLUMNS.items() if name in fields}


CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "prospects": {
        "description": "A person tracked in Account Engagement, with their profile, scoring and activity timestamps.",
        "docs_url": f"{_DOCS_BASE}/prospect-v5.html",
        "columns": {
            **_shared("prospects"),
            "email": "Primary email address of the prospect.",
            "firstName": "First name of the prospect.",
            "lastName": "Last name of the prospect.",
            "company": "Company the prospect belongs to.",
            "jobTitle": "Job title of the prospect.",
            "score": "Behavioral score, driven by the prospect's activity.",
            "grade": "Profile grade of the prospect.",
            "source": "Source the prospect came from.",
            "optedOut": "Whether the prospect has opted out of marketing emails.",
            "isDoNotEmail": "Whether the prospect is flagged as do not email.",
            "isDoNotCall": "Whether the prospect is flagged as do not call.",
            "doNotSell": "Whether the prospect asked not to have their data sold.",
            "isEmailHardBounced": "Whether the prospect's email address hard bounced.",
            "emailBouncedAt": "Timestamp of the most recent email bounce.",
            "emailBouncedReason": "Reason given for the most recent email bounce.",
            "firstActivityAt": "Timestamp of the prospect's first tracked activity.",
            "firstAssignedAt": "Timestamp of when the prospect was first assigned to a user.",
            "lastActivityAt": "Timestamp of the prospect's most recent tracked activity.",
            "convertedAt": "Timestamp of when the prospect was converted in Salesforce.",
            "prospectAccountId": "ID of the prospect account the prospect belongs to.",
            "lifecycleStageId": "ID of the prospect's current lifecycle stage.",
            "assignedToId": "ID of the user the prospect is assigned to.",
            "userId": "ID of the user who owns the prospect.",
            "profileId": "ID of the profile used to grade the prospect.",
            "campaignParameter": "utm_campaign value from the prospect's first touch.",
            "mediumParameter": "utm_medium value from the prospect's first touch.",
            "sourceParameter": "utm_source value from the prospect's first touch.",
            "termParameter": "utm_term value from the prospect's first touch.",
            "contentParameter": "utm_content value from the prospect's first touch.",
            "salesforceLeadId": "ID of the matching Salesforce lead.",
            "salesforceContactId": "ID of the matching Salesforce contact.",
            "salesforceAccountId": "ID of the matching Salesforce account.",
            "salesforceLastSync": "Timestamp of the last sync with Salesforce.",
        },
    },
    "prospect_accounts": {
        "description": "A company record that prospects are grouped under, mirroring a Salesforce account.",
        "docs_url": f"{_DOCS_BASE}/prospect-account-v5.html",
        "columns": {
            **_shared("prospect_accounts"),
            "annualRevenue": "Annual revenue of the account.",
            "employees": "Number of employees at the account.",
            "industry": "Industry of the account.",
            "website": "Website of the account.",
            "assignedToId": "ID of the user the account is assigned to.",
            "billingCity": "City of the account's billing address.",
            "billingCountry": "Country of the account's billing address.",
            "type": "Type of the account, as set in Salesforce.",
        },
    },
    "lists": {
        "description": "A static or dynamic list of prospects used for sending and segmentation.",
        "docs_url": f"{_DOCS_BASE}/list-v5.html",
        "columns": {
            **_shared("lists"),
            "description": "Internal description of the list.",
            "title": "Title shown to prospects on the email preference page.",
            "isPublic": "Whether prospects can subscribe to the list themselves.",
            "isDynamic": "Whether membership is maintained by a dynamic list rule.",
        },
    },
    "list_memberships": {
        "description": "The membership of one prospect on one list, including their opt-out state.",
        "docs_url": f"{_DOCS_BASE}/list-membership-v5.html",
        "columns": {
            **_shared("list_memberships"),
            "listId": "ID of the list.",
            "prospectId": "ID of the prospect on the list.",
            "optedOut": "Whether the prospect opted out of this list.",
        },
    },
    "campaigns": {
        "description": "A marketing campaign that prospects and assets are attributed to.",
        "docs_url": f"{_DOCS_BASE}/campaign-v5.html",
        "columns": {
            **_shared("campaigns"),
            "cost": "Cost recorded for the campaign.",
            "parentCampaignId": "ID of the parent campaign in the campaign hierarchy.",
        },
    },
    "opportunities": {
        "description": "A sales opportunity synced from Salesforce and linked to Account Engagement campaigns.",
        "docs_url": f"{_DOCS_BASE}/opportunity-v5.html",
        "columns": {
            **_shared("opportunities"),
            "stage": "Sales stage of the opportunity.",
            "status": "Status of the opportunity (won, lost or open).",
            "probability": "Percentage likelihood the opportunity closes.",
            "value": "Monetary value of the opportunity.",
            "type": "Type of the opportunity.",
            "closedAt": "Timestamp of when the opportunity closed.",
        },
    },
    "users": {
        "description": "A user of the Account Engagement business unit.",
        "docs_url": f"{_DOCS_BASE}/user-v5.html",
        "columns": {
            **_shared("users"),
            "email": "Email address of the user.",
            "firstName": "First name of the user.",
            "lastName": "Last name of the user.",
            "username": "Login username of the user.",
            "jobTitle": "Job title of the user.",
            "role": "Role assigned to the user.",
            "roleName": "Display name of the user's role.",
            "tagReplacementLanguage": "Language used for tag replacement in the user's emails.",
        },
    },
    "visits": {
        "description": "A browsing session on your tracked site, grouped from a visitor's page views.",
        "docs_url": f"{_DOCS_BASE}/visit-v5.html",
        "columns": {
            **_shared("visits"),
            "visitorId": "ID of the visitor the session belongs to.",
            "prospectId": "ID of the prospect the visitor was identified as, if any.",
            "visitorPageViewCount": "Number of page views in the session.",
            "firstVisitorPageViewAt": "Timestamp of the first page view in the session.",
            "lastVisitorPageViewAt": "Timestamp of the last page view in the session.",
            "durationInSeconds": "Length of the session in seconds.",
            "campaignParameter": "utm_campaign value recorded for the session.",
            "mediumParameter": "utm_medium value recorded for the session.",
            "sourceParameter": "utm_source value recorded for the session.",
            "termParameter": "utm_term value recorded for the session.",
            "contentParameter": "utm_content value recorded for the session.",
        },
    },
    "visitors": {
        "description": "An anonymous or identified browser tracked by the Account Engagement tracking code.",
        "docs_url": f"{_DOCS_BASE}/visitor-v5.html",
        "columns": {
            **_shared("visitors"),
            "prospectId": "ID of the prospect the visitor was identified as, if any.",
            "hostname": "Hostname resolved from the visitor's IP address.",
            "ipAddress": "IP address the visitor browsed from.",
            "pageViewCount": "Total page views recorded for the visitor.",
            "isIdentified": "Whether the visitor has been matched to a prospect.",
            "doNotSell": "Whether the visitor asked not to have their data sold.",
        },
    },
    "visitor_activities": {
        "description": "A single tracked action by a prospect or visitor, such as a form submit, email click or page view.",
        "docs_url": f"{_DOCS_BASE}/visitor-activity-v5.html",
        "columns": {
            **_shared("visitor_activities"),
            "type": "Numeric code of the activity type.",
            "typeName": "Human-readable name of the activity type.",
            "details": "Details of the activity, such as the name of the asset involved.",
            "prospectId": "ID of the prospect who performed the activity.",
            "visitorId": "ID of the visitor who performed the activity.",
            "visitId": "ID of the visit the activity belongs to.",
            "visitorPageViewId": "ID of the page view the activity belongs to.",
            "customRedirectId": "ID of the custom redirect involved in the activity.",
            "emailId": "ID of the email involved in the activity.",
            "emailTemplateId": "ID of the email template involved in the activity.",
            "fileId": "ID of the file involved in the activity.",
            "formId": "ID of the form involved in the activity.",
            "formHandlerId": "ID of the form handler involved in the activity.",
            "landingPageId": "ID of the landing page involved in the activity.",
            "listEmailId": "ID of the list email involved in the activity.",
            "opportunityId": "ID of the opportunity involved in the activity.",
            "paidSearchAdId": "ID of the paid search ad involved in the activity.",
            "siteSearchQueryId": "ID of the site search query involved in the activity.",
        },
    },
    "custom_fields": {
        "description": "A custom prospect field defined in the business unit.",
        "docs_url": f"{_DOCS_BASE}/custom-field-v5.html",
        "columns": {
            **_shared("custom_fields"),
            "fieldId": "API name used to reference the field in forms and imports.",
            "type": "Data type of the field.",
            "isRequired": "Whether the field is required on forms.",
            "isRecordMultipleResponses": "Whether every response is kept rather than overwriting the last one.",
            "isUseValues": "Whether the field is limited to a predefined set of values.",
            "valuesPrefill": "Whether the field's values prefill for known prospects.",
            "isAnalyticsSynced": "Whether the field syncs with connected analytics.",
        },
    },
    "forms": {
        "description": "An Account Engagement form used to capture prospect submissions.",
        "docs_url": f"{_DOCS_BASE}/form-v5.html",
        "columns": {
            **_shared("forms"),
            "layoutTemplateId": "ID of the layout template applied to the form.",
            "trackerDomainId": "ID of the tracker domain the form is served from.",
            "submitButtonText": "Label of the form's submit button.",
            "redirectLocation": "URL prospects are sent to after submitting.",
            "isUseRedirectLocation": "Whether the form redirects instead of showing thank-you content.",
            "isAlwaysDisplay": "Whether the form always shows, even to known prospects.",
            "isCaptchaEnabled": "Whether CAPTCHA is enabled on the form.",
            "isCookieless": "Whether the form runs in cookieless tracking mode.",
            "url": "Public URL of the form.",
            "embedCode": "HTML snippet used to embed the form.",
            "salesforceCmsId": "ID of the matching form in Salesforce CMS.",
        },
    },
    "list_emails": {
        "description": "A one-off email sent to lists of prospects.",
        "docs_url": f"{_DOCS_BASE}/list-email-v5.html",
        "columns": {
            **_shared("list_emails"),
            "subject": "Subject line of the email.",
            "emailTemplateId": "ID of the template the email was built from.",
            "trackerDomainId": "ID of the tracker domain used for links in the email.",
            "clientType": "Client the email was created in.",
            "type": "Type of the email.",
            "isOperational": "Whether the email is operational and ignores opt-outs.",
            "isPaused": "Whether sending is paused.",
            "isSent": "Whether the email has been sent.",
            "scheduledTime": "Timestamp the email is scheduled to send at.",
            "sentAt": "Timestamp the email was sent at.",
        },
    },
}
