from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "account": {
        "description": "A snapshot of the SES account's sending status, quota, and reputation enforcement in the connected AWS Region. One row per sync.",
        "docs_url": "https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetAccount.html",
        "columns": {
            "dedicated_ip_auto_warmup_enabled": "Whether the automatic warm-up feature is enabled for dedicated IP addresses associated with the account.",
            "enforcement_status": "The reputation status of the account: HEALTHY, PROBATION, or SHUTDOWN.",
            "production_access_enabled": "Whether the account has production access in the Region. False means the account is still in the sandbox.",
            "sending_enabled": "Whether email sending is enabled for the account in the Region.",
            "send_quota_max24_hour_send": "The maximum number of emails that can be sent in the Region over a 24-hour period. -1 means an unlimited quota.",
            "send_quota_max_send_rate": "The maximum number of emails that can be sent per second in the Region.",
            "send_quota_sent_last24_hours": "The number of emails sent from the account in the Region over the past 24 hours.",
            "suppression_attributes_suppressed_reasons": "The reasons (BOUNCE, COMPLAINT) that cause email addresses to be automatically added to the account's suppression list.",
            "details_mail_type": "The type of email the account sends: MARKETING or TRANSACTIONAL.",
            "details_website_url": "The URL of the sender's website, as submitted in the account details.",
            "details_contact_language": "The preferred language for support cases: ENGLISH or JAPANESE.",
            "details_use_case_description": "A description of the types of email the account plans to send.",
            "details_additional_contact_email_addresses": "Additional email addresses where updates about the account review process are sent.",
            "details_review_details_status": "The status of the latest account review: PENDING, GRANTED, DENIED, or FAILED.",
            "details_review_details_case_id": "The support center case ID associated with the account review, if any.",
            "vdm_attributes_vdm_enabled": "Whether Virtual Deliverability Manager is enabled for the account.",
            "vdm_attributes_dashboard_attributes_engagement_metrics": "Whether VDM engagement metrics collection is enabled for the account.",
            "vdm_attributes_guardian_attributes_optimized_shared_delivery": "Whether VDM optimized shared delivery is enabled for the account.",
        },
    },
    "configuration_sets": {
        "description": "Configuration sets, the groups of rules applied to the emails sent through them, with their tracking, delivery, reputation, sending, and suppression options.",
        "docs_url": "https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetConfigurationSet.html",
        "columns": {
            "configuration_set_name": "The name of the configuration set.",
            "tracking_options_custom_redirect_domain": "The custom domain used for tracking open and click events.",
            "tracking_options_https_policy": "The https policy used for tracking open and click events.",
            "delivery_options_tls_policy": "Whether messages that use the configuration set require a TLS connection: REQUIRE or OPTIONAL.",
            "delivery_options_sending_pool_name": "The dedicated IP pool associated with the configuration set.",
            "delivery_options_max_delivery_seconds": "The maximum amount of time, in seconds, that SES attempts delivery of email.",
            "reputation_options_reputation_metrics_enabled": "Whether tracking of reputation metrics is enabled for the configuration set.",
            "reputation_options_last_fresh_start": "When the configuration set's reputation metrics were last given a fresh start.",
            "sending_options_sending_enabled": "Whether email sending is enabled for the configuration set.",
            "suppression_options_suppressed_reasons": "The reasons (BOUNCE, COMPLAINT) that cause addresses to be automatically suppressed for this configuration set.",
            "vdm_options_dashboard_options_engagement_metrics": "Whether VDM engagement metrics collection is enabled for the configuration set.",
            "vdm_options_guardian_options_optimized_shared_delivery": "Whether VDM optimized shared delivery is enabled for the configuration set.",
            "archiving_options_archive_arn": "The ARN of the MailManager archive where sent emails are archived.",
            "tags": "The tags (keys and values) associated with the configuration set, as JSON.",
        },
    },
    "contact_lists": {
        "description": "Contact lists in the account. A contact list stores contacts and the topics they can subscribe to.",
        "docs_url": "https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetContactList.html",
        "columns": {
            "contact_list_name": "The name of the contact list.",
            "description": "A description of what the contact list is used for.",
            "topics": "The interest groups, themes, or labels within the list, with each topic's default subscription status, as JSON.",
            "created_timestamp": "When the contact list was created.",
            "last_updated_timestamp": "When the contact list was last updated.",
            "tags": "The tags (keys and values) associated with the contact list, as JSON.",
        },
    },
    "custom_verification_email_templates": {
        "description": "Custom verification email templates, used to customize the email SES sends when verifying a new email address.",
        "docs_url": "https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetCustomVerificationEmailTemplate.html",
        "columns": {
            "template_name": "The name of the custom verification email template.",
            "from_email_address": "The email address that the custom verification email is sent from.",
            "template_subject": "The subject line of the custom verification email.",
            "template_content": "The content of the custom verification email, in HTML.",
            "success_redirection_url": "The URL that the recipient of the verification email is sent to if their address is successfully verified.",
            "failure_redirection_url": "The URL that the recipient of the verification email is sent to if their address is not successfully verified.",
        },
    },
    "dedicated_ip_pools": {
        "description": "Dedicated IP pools in the account. A pool groups dedicated IP addresses so configuration sets can send through them.",
        "docs_url": "https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetDedicatedIpPool.html",
        "columns": {
            "pool_name": "The name of the dedicated IP pool.",
            "dedicated_ip_pool_pool_name": "The name of the dedicated IP pool, as returned by the pool detail call.",
            "dedicated_ip_pool_scaling_mode": "The type of the pool: STANDARD (warm-up managed by you) or MANAGED (warm-up managed by SES).",
        },
    },
    "dedicated_ips": {
        "description": "Dedicated IP addresses assigned to the account, with their warm-up progress and pool assignment. Empty for accounts without dedicated IPs.",
        "docs_url": "https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetDedicatedIps.html",
        "columns": {
            "ip": "The dedicated IP address.",
            "warmup_status": "The warm-up status of the address: IN_PROGRESS, DONE, or NOT_APPLICABLE.",
            "warmup_percentage": "How far along the warm-up process is. 100 means the address is fully warmed up and ready to use.",
            "pool_name": "The name of the dedicated IP pool that the address is associated with.",
        },
    },
    "email_identities": {
        "description": "The email identities (domains and addresses) registered with the account, with their DKIM, MAIL FROM, and verification details.",
        "docs_url": "https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetEmailIdentity.html",
        "columns": {
            "identity_name": "The address or domain of the identity.",
            "identity_type": "The identity type: EMAIL_ADDRESS or DOMAIN.",
            "sending_enabled": "Whether email can currently be sent from the identity.",
            "verification_status": "The verification status of the identity: PENDING, SUCCESS, FAILED, TEMPORARY_FAILURE, or NOT_STARTED.",
            "verified_for_sending_status": "Whether the identity is verified. Email can only be sent from verified addresses or domains.",
            "feedback_forwarding_status": "Whether bounce and complaint notifications are forwarded by email for this identity.",
            "configuration_set_name": "The configuration set used by default when sending from this identity.",
            "dkim_attributes_signing_enabled": "Whether messages sent from the identity are signed using DKIM.",
            "dkim_attributes_status": "Whether SES has located the DKIM records in the domain's DNS: PENDING, SUCCESS, FAILED, TEMPORARY_FAILURE, or NOT_STARTED.",
            "dkim_attributes_tokens": "The Easy DKIM tokens used to create the CNAME records for the domain, as JSON.",
            "dkim_attributes_signing_attributes_origin": "How DKIM was configured for the identity: AWS_SES (Easy DKIM) or EXTERNAL (BYODKIM).",
            "dkim_attributes_current_signing_key_length": "The key length of the DKIM key pair in use.",
            "dkim_attributes_next_signing_key_length": "The key length of the future DKIM key pair to be generated.",
            "dkim_attributes_last_key_generation_timestamp": "The last time an Easy DKIM key pair was generated for the identity.",
            "mail_from_attributes_mail_from_domain": "The custom MAIL FROM domain used by the identity.",
            "mail_from_attributes_mail_from_domain_status": "The status of the MAIL FROM domain: PENDING, SUCCESS, FAILED, or TEMPORARY_FAILURE.",
            "mail_from_attributes_behavior_on_mx_failure": "The action taken when the MAIL FROM domain's MX record can't be found: USE_DEFAULT_VALUE or REJECT_MESSAGE.",
            "policies": "The sending authorization policies attached to the identity, as a JSON map of policy names to policy documents.",
            "tags": "The tags (keys and values) associated with the identity, as JSON.",
            "verification_info_last_checked_timestamp": "The last time a verification attempt was made for the identity.",
            "verification_info_last_success_timestamp": "The last time the identity was successfully verified.",
            "verification_info_error_type": "The reason the latest verification attempt failed, if any.",
            "verification_info_soa_record_primary_name_server": "The primary name server from the domain's SOA record.",
            "verification_info_soa_record_admin_email": "The administrative contact email from the domain's SOA record.",
            "verification_info_soa_record_serial_number": "The serial number from the domain's SOA record.",
        },
    },
    "email_templates": {
        "description": "Email templates stored in SES, including the subject line and the HTML and plain-text bodies used when sending templated email.",
        "docs_url": "https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetEmailTemplate.html",
        "columns": {
            "template_name": "The name of the template.",
            "created_timestamp": "When the template was created.",
            "template_content_subject": "The subject line of the email template.",
            "template_content_text": "The plain-text body of the email template.",
            "template_content_html": "The HTML body of the email template.",
        },
    },
    "multi_region_endpoints": {
        "description": "Multi-region endpoints (global endpoints), which route sending across a primary and a secondary AWS Region.",
        "docs_url": "https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_ListMultiRegionEndpoints.html",
        "columns": {
            "endpoint_name": "The name of the multi-region endpoint (global endpoint).",
            "endpoint_id": "The ID of the multi-region endpoint (global endpoint).",
            "status": "The status of the endpoint: CREATING, READY, FAILED, or DELETING.",
            "regions": "The AWS Regions the multi-region endpoint sends email from, as JSON.",
            "created_timestamp": "When the multi-region endpoint was created.",
            "last_updated_timestamp": "When the multi-region endpoint was last updated.",
        },
    },
    "suppressed_destinations": {
        "description": "Email addresses on the account-level suppression list. SES does not attempt delivery to these addresses. Addresses removed from the list upstream are not deleted from this table.",
        "docs_url": "https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_ListSuppressedDestinations.html",
        "columns": {
            "email_address": "The email address that is on the suppression list for the account.",
            "reason": "The reason the address was added to the suppression list: BOUNCE or COMPLAINT.",
            "last_update_time": "When the suppressed destination was last updated.",
        },
    },
}
