from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "users": {
        "description": "Members of your Anthropic organization and their organization-level roles.",
        "docs_url": "https://platform.claude.com/docs/en/api/admin/users/list",
        "columns": {
            "id": "ID of the user.",
            "type": "Object type. Always 'user'.",
            "email": "Email of the user.",
            "name": "Name of the user.",
            "role": "Organization role of the user: admin, billing, claude_code_user, developer, or user.",
            "added_at": "RFC 3339 datetime string indicating when the user joined the organization.",
        },
    },
    "invites": {
        "description": "Pending and historical invitations to join your Anthropic organization.",
        "docs_url": "https://platform.claude.com/docs/en/api/admin/invites/list",
        "columns": {
            "id": "ID of the invite.",
            "type": "Object type. Always 'invite'.",
            "email": "Email of the user being invited.",
            "role": "Organization role the invited user will receive: admin, billing, claude_code_user, developer, or user.",
            "invited_at": "RFC 3339 datetime string indicating when the invite was created.",
            "expires_at": "RFC 3339 datetime string indicating when the invite expires.",
            "status": "Status of the invite: accepted, deleted, expired, or pending.",
        },
    },
    "workspaces": {
        "description": "Workspaces in your Anthropic organization, used to segment API usage, spend limits, and access. Includes archived workspaces.",
        "docs_url": "https://platform.claude.com/docs/en/api/admin/workspaces/list",
        "columns": {
            "id": "ID of the workspace.",
            "type": "Object type. Always 'workspace'.",
            "name": "Name of the workspace.",
            "created_at": "RFC 3339 datetime string indicating when the workspace was created.",
            "archived_at": "RFC 3339 datetime string indicating when the workspace was archived, or null if not archived.",
            "display_color": "Hex color code representing the workspace in the Anthropic Console.",
            "compartment_id": "Identifier for this workspace's encryption compartment, referenced by customer-managed encryption key (CMEK) configurations.",
            "data_residency": "Data residency configuration: allowed inference geos, default inference geo, and workspace geo.",
        },
    },
    "workspace_members": {
        "description": "Membership of users in each workspace, with their workspace-level role. One row per user per workspace.",
        "docs_url": "https://platform.claude.com/docs/en/api/admin/workspace-members/list",
        "columns": {
            "type": "Object type. Always 'workspace_member'.",
            "user_id": "ID of the user.",
            "workspace_id": "ID of the workspace.",
            "workspace_role": "Role of the member within the workspace: workspace_admin, workspace_billing, workspace_developer, workspace_restricted_developer, or workspace_user.",
        },
    },
    "api_keys": {
        "description": "API keys provisioned in your Anthropic organization, with their status, owning workspace, and creator.",
        "docs_url": "https://platform.claude.com/docs/en/api/admin/api-keys/list",
        "columns": {
            "id": "ID of the API key.",
            "type": "Object type. Always 'api_key'.",
            "name": "Name of the API key.",
            "status": "Status of the API key: active, inactive, or archived.",
            "workspace_id": "ID of the workspace the API key belongs to, or null for the default workspace.",
            "created_at": "RFC 3339 datetime string indicating when the API key was created.",
            "created_by": "The ID and type of the actor that created the API key.",
            "partial_key_hint": "Partially redacted hint for the API key.",
        },
    },
    "usage_report": {
        "description": "Daily Claude API token usage for your organization, broken down by API key, workspace, model, service tier, context window, and inference geo. One row per day per unique combination of those dimensions.",
        "docs_url": "https://platform.claude.com/docs/en/api/admin/usage-report/messages",
        "columns": {
            "id": "Synthetic unique key combining the time bucket start and the grouping dimensions.",
            "bucket_starting_at": "Start of the daily time bucket (inclusive) in RFC 3339 format.",
            "bucket_ending_at": "End of the daily time bucket (exclusive) in RFC 3339 format.",
            "api_key_id": "ID of the API key used, or null for usage in the Anthropic Console.",
            "workspace_id": "ID of the workspace used, or null for the default workspace.",
            "model": "Model used (e.g. claude-sonnet-4-5).",
            "service_tier": "Service tier used: batch, flex, flex_discount, priority, priority_on_demand, or standard.",
            "context_window": "Context window used: 0-200k or 200k-1M.",
            "inference_geo": "Inference geo used, or not_available for models that do not support specifying one.",
            "account_id": "ID of the user account that made the request. Null unless grouping by account.",
            "service_account_id": "ID of the service account that made the request. Null unless grouping by service account.",
            "uncached_input_tokens": "The number of uncached input tokens processed.",
            "cache_creation": "Input tokens used to create 1 hour and 5 minute cache entries.",
            "cache_read_input_tokens": "The number of input tokens read from the cache.",
            "output_tokens": "The number of output tokens generated.",
            "server_tool_use": "Server-side tool usage metrics, e.g. the number of web search requests made.",
        },
    },
    "cost_report": {
        "description": "Daily costs for your Anthropic organization in USD, broken down by workspace and line-item description. One row per day per unique cost line item.",
        "docs_url": "https://platform.claude.com/docs/en/api/admin/cost-report/get",
        "columns": {
            "id": "Synthetic unique key combining the time bucket start and the cost breakdown dimensions.",
            "bucket_starting_at": "Start of the daily time bucket (inclusive) in RFC 3339 format.",
            "bucket_ending_at": "End of the daily time bucket (exclusive) in RFC 3339 format.",
            "workspace_id": "ID of the workspace this cost is associated with, or null for the default workspace.",
            "description": "Description of the cost item (e.g. 'Claude Sonnet 4.5 Usage - Input Tokens').",
            "amount": "Cost amount in lowest currency units (e.g. cents) as a decimal string. For example, '123.45' in USD represents $1.23.",
            "currency": "Currency code for the cost amount. Currently always USD.",
            "cost_type": "Type of cost: code_execution, session_usage, tokens, or web_search. Null for costs not grouped by description.",
            "model": "Model name used, or null for non-token costs.",
            "service_tier": "Service tier used: batch or standard. Null for non-token costs.",
            "token_type": "Type of token the cost applies to (e.g. uncached_input_tokens, output_tokens, cache_read_input_tokens).",
            "context_window": "Input context window used: 0-200k or 200k-1M. Null for non-token costs.",
            "inference_geo": "Inference geo used, or not_available for models that do not support specifying one.",
        },
    },
}
