[package]
name = "capture-apm-metrics"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
health = { path = "../common/health" }
axum = { workspace = true }
common-metrics = { path = "../common/metrics" }
common-alloc = { path = "../common/alloc" }
limiters = { path = "../common/limiters" }
capture = { path = "../capture" }
capture-logs = { path = "../capture-logs" }
tower-http = { workspace = true }

[lints]
workspace = true
