export const listWebVitalsAPIResponse = {
    cache_key: 'cache_e7677c1c79088b820b79d0665592f473',
    cache_target_age: '2025-02-01T15:10:46.730769Z',
    calculation_trigger: null,
    error: '',
    hasMore: false,
    hogql: "SELECT\n    arrayMap(number -> plus(toStartOfWeek(assumeNotNull(toDateTime('2025-01-25 00:00:00'))), toIntervalWeek(number)), range(0, plus(coalesce(dateDiff('week', toStartOfWeek(assumeNotNull(toDateTime('2025-01-25 00:00:00'))), toStartOfWeek(assumeNotNull(toDateTime('2025-02-01 23:59:59'))))), 1))) AS date,\n    arrayMap(_match_date -> arraySum(arraySlice(groupArray(ifNull(count, 0)), indexOf(groupArray(day_start) AS _days_for_count, _match_date) AS _index, plus(minus(arrayLastIndex(x -> equals(x, _match_date), _days_for_count), _index), 1))), date) AS total\nFROM\n    (SELECT\n        sum(total) AS count,\n        day_start\n    FROM\n        (SELECT\n            quantile(0.9)(properties.$web_vitals_INP_value) AS total,\n            toStartOfWeek(timestamp) AS day_start\n        FROM\n            events AS e SAMPLE 1\n        WHERE\n            and(greaterOrEquals(timestamp, toStartOfWeek(assumeNotNull(toDateTime('2025-01-25 00:00:00')))), lessOrEquals(timestamp, assumeNotNull(toDateTime('2025-02-01 23:59:59'))), equals(event, '$web_vitals'), equals(properties.$pathname, '/project/1/web/web-vitals'))\n        GROUP BY\n            day_start)\n    GROUP BY\n        day_start\n    ORDER BY\n        day_start ASC)\nORDER BY\n    arraySum(total) DESC\nLIMIT 50000\nUNION ALL\nSELECT\n    arrayMap(number -> plus(toStartOfWeek(assumeNotNull(toDateTime('2025-01-25 00:00:00'))), toIntervalWeek(number)), range(0, plus(coalesce(dateDiff('week', toStartOfWeek(assumeNotNull(toDateTime('2025-01-25 00:00:00'))), toStartOfWeek(assumeNotNull(toDateTime('2025-02-01 23:59:59'))))), 1))) AS date,\n    arrayMap(_match_date -> arraySum(arraySlice(groupArray(ifNull(count, 0)), indexOf(groupArray(day_start) AS _days_for_count, _match_date) AS _index, plus(minus(arrayLastIndex(x -> equals(x, _match_date), _days_for_count), _index), 1))), date) AS total\nFROM\n    (SELECT\n        sum(total) AS count,\n        day_start\n    FROM\n        (SELECT\n            quantile(0.9)(properties.$web_vitals_LCP_value) AS total,\n            toStartOfWeek(timestamp) AS day_start\n        FROM\n            events AS e SAMPLE 1\n        WHERE\n            and(greaterOrEquals(timestamp, toStartOfWeek(assumeNotNull(toDateTime('2025-01-25 00:00:00')))), lessOrEquals(timestamp, assumeNotNull(toDateTime('2025-02-01 23:59:59'))), equals(event, '$web_vitals'), equals(properties.$pathname, '/project/1/web/web-vitals'))\n        GROUP BY\n            day_start)\n    GROUP BY\n        day_start\n    ORDER BY\n        day_start ASC)\nORDER BY\n    arraySum(total) DESC\nLIMIT 50000\nUNION ALL\nSELECT\n    arrayMap(number -> plus(toStartOfWeek(assumeNotNull(toDateTime('2025-01-25 00:00:00'))), toIntervalWeek(number)), range(0, plus(coalesce(dateDiff('week', toStartOfWeek(assumeNotNull(toDateTime('2025-01-25 00:00:00'))), toStartOfWeek(assumeNotNull(toDateTime('2025-02-01 23:59:59'))))), 1))) AS date,\n    arrayMap(_match_date -> arraySum(arraySlice(groupArray(ifNull(count, 0)), indexOf(groupArray(day_start) AS _days_for_count, _match_date) AS _index, plus(minus(arrayLastIndex(x -> equals(x, _match_date), _days_for_count), _index), 1))), date) AS total\nFROM\n    (SELECT\n        sum(total) AS count,\n        day_start\n    FROM\n        (SELECT\n            quantile(0.9)(properties.$web_vitals_CLS_value) AS total,\n            toStartOfWeek(timestamp) AS day_start\n        FROM\n            events AS e SAMPLE 1\n        WHERE\n            and(greaterOrEquals(timestamp, toStartOfWeek(assumeNotNull(toDateTime('2025-01-25 00:00:00')))), lessOrEquals(timestamp, assumeNotNull(toDateTime('2025-02-01 23:59:59'))), equals(event, '$web_vitals'), equals(properties.$pathname, '/project/1/web/web-vitals'))\n        GROUP BY\n            day_start)\n    GROUP BY\n        day_start\n    ORDER BY\n        day_start ASC)\nORDER BY\n    arraySum(total) DESC\nLIMIT 50000\nUNION ALL\nSELECT\n    arrayMap(number -> plus(toStartOfWeek(assumeNotNull(toDateTime('2025-01-25 00:00:00'))), toIntervalWeek(number)), range(0, plus(coalesce(dateDiff('week', toStartOfWeek(assumeNotNull(toDateTime('2025-01-25 00:00:00'))), toStartOfWeek(assumeNotNull(toDateTime('2025-02-01 23:59:59'))))), 1))) AS date,\n    arrayMap(_match_date -> arraySum(arraySlice(groupArray(ifNull(count, 0)), indexOf(groupArray(day_start) AS _days_for_count, _match_date) AS _index, plus(minus(arrayLastIndex(x -> equals(x, _match_date), _days_for_count), _index), 1))), date) AS total\nFROM\n    (SELECT\n        sum(total) AS count,\n        day_start\n    FROM\n        (SELECT\n            quantile(0.9)(properties.$web_vitals_FCP_value) AS total,\n            toStartOfWeek(timestamp) AS day_start\n        FROM\n            events AS e SAMPLE 1\n        WHERE\n            and(greaterOrEquals(timestamp, toStartOfWeek(assumeNotNull(toDateTime('2025-01-25 00:00:00')))), lessOrEquals(timestamp, assumeNotNull(toDateTime('2025-02-01 23:59:59'))), equals(event, '$web_vitals'), equals(properties.$pathname, '/project/1/web/web-vitals'))\n        GROUP BY\n            day_start)\n    GROUP BY\n        day_start\n    ORDER BY\n        day_start ASC)\nORDER BY\n    arraySum(total) DESC\nLIMIT 50000",
    is_cached: false,
    last_refresh: '2025-02-01T03:10:46.730769Z',
    modifiers: {
        bounceRateDurationSeconds: null,
        bounceRatePageViewMode: 'count_pageviews',
        customChannelTypeRules: null,
        dataWarehouseEventsModifiers: [],
        debug: null,
        inCohortVia: 'auto',
        materializationMode: 'legacy_null_as_null',
        optimizeJoinedFilters: false,
        personsArgMaxVersion: 'auto',
        personsJoinMode: null,
        personsOnEventsMode: 'person_id_override_properties_joined',
        propertyGroupsMode: null,
        s3TableUseInvalidColumns: null,
        sessionTableVersion: 'auto',
        useMaterializedViews: null,
    },
    next_allowed_client_refresh: '2025-02-01T03:25:46.730769Z',
    query_status: null,
    results: [
        {
            data: [112, 145],
            labels: ['19-Jan-2025', '26-Jan-2025'],
            days: ['2025-01-19', '2025-01-26'],
            count: 112,
            label: '$web_vitals',
            filter: {
                insight: 'TRENDS',
                properties: [
                    {
                        key: '$pathname',
                        label: null,
                        operator: 'exact',
                        type: 'event',
                        value: ['/project/1/web/web-vitals'],
                    },
                ],
                filter_test_accounts: false,
                date_to: '2025-02-01T23:59:59.999999Z',
                date_from: '2025-01-25T00:00:00Z',
                entity_type: 'events',
                interval: 'week',
                aggregationAxisFormat: 'numeric',
                display: 'ActionsLineGraph',
                resultCustomizationBy: 'value',
                showAlertThresholdLines: false,
                showLegend: false,
                showPercentStackView: false,
                showValuesOnSeries: false,
                smoothingIntervals: 1,
                yAxisScaleType: 'linear',
            },
            action: {
                days: ['2025-01-19T00:00:00Z', '2025-01-26T00:00:00Z'],
                id: '$web_vitals',
                type: 'events',
                order: 0,
                name: '$web_vitals',
                custom_name: 'INP',
                math: 'p90',
                math_property: '$web_vitals_INP_value',
                math_hogql: null,
                math_group_type_index: null,
                properties: {},
            },
        },
        {
            data: [1108.456, 1412.345],
            labels: ['19-Jan-2025', '26-Jan-2025'],
            days: ['2025-01-19', '2025-01-26'],
            count: 1108.456,
            label: '$web_vitals',
            filter: {
                insight: 'TRENDS',
                properties: [
                    {
                        key: '$pathname',
                        label: null,
                        operator: 'exact',
                        type: 'event',
                        value: ['/project/1/web/web-vitals'],
                    },
                ],
                filter_test_accounts: false,
                date_to: '2025-02-01T23:59:59.999999Z',
                date_from: '2025-01-25T00:00:00Z',
                entity_type: 'events',
                interval: 'week',
                aggregationAxisFormat: 'numeric',
                display: 'ActionsLineGraph',
                resultCustomizationBy: 'value',
                showAlertThresholdLines: false,
                showLegend: false,
                showPercentStackView: false,
                showValuesOnSeries: false,
                smoothingIntervals: 1,
                yAxisScaleType: 'linear',
            },
            action: {
                days: ['2025-01-19T00:00:00Z', '2025-01-26T00:00:00Z'],
                id: '$web_vitals',
                type: 'events',
                order: 1,
                name: '$web_vitals',
                custom_name: 'LCP',
                math: 'p90',
                math_property: '$web_vitals_LCP_value',
                math_hogql: null,
                math_group_type_index: null,
                properties: {},
            },
        },
        {
            data: [0.45, 0.45],
            labels: ['19-Jan-2025', '26-Jan-2025'],
            days: ['2025-01-19', '2025-01-26'],
            count: 0.45,
            label: '$web_vitals',
            filter: {
                insight: 'TRENDS',
                properties: [
                    {
                        key: '$pathname',
                        label: null,
                        operator: 'exact',
                        type: 'event',
                        value: ['/project/1/web/web-vitals'],
                    },
                ],
                filter_test_accounts: false,
                date_to: '2025-02-01T23:59:59.999999Z',
                date_from: '2025-01-25T00:00:00Z',
                entity_type: 'events',
                interval: 'week',
                aggregationAxisFormat: 'numeric',
                display: 'ActionsLineGraph',
                resultCustomizationBy: 'value',
                showAlertThresholdLines: false,
                showLegend: false,
                showPercentStackView: false,
                showValuesOnSeries: false,
                smoothingIntervals: 1,
                yAxisScaleType: 'linear',
            },
            action: {
                days: ['2025-01-19T00:00:00Z', '2025-01-26T00:00:00Z'],
                id: '$web_vitals',
                type: 'events',
                order: 2,
                name: '$web_vitals',
                custom_name: 'CLS',
                math: 'p90',
                math_property: '$web_vitals_CLS_value',
                math_hogql: null,
                math_group_type_index: null,
                properties: {},
            },
        },
        {
            data: [1808.1, 1808.1],
            labels: ['19-Jan-2025', '26-Jan-2025'],
            days: ['2025-01-19', '2025-01-26'],
            count: 1808.1,
            label: '$web_vitals',
            filter: {
                insight: 'TRENDS',
                properties: [
                    {
                        key: '$pathname',
                        label: null,
                        operator: 'exact',
                        type: 'event',
                        value: ['/project/1/web/web-vitals'],
                    },
                ],
                filter_test_accounts: false,
                date_to: '2025-02-01T23:59:59.999999Z',
                date_from: '2025-01-25T00:00:00Z',
                entity_type: 'events',
                interval: 'week',
                aggregationAxisFormat: 'numeric',
                display: 'ActionsLineGraph',
                resultCustomizationBy: 'value',
                showAlertThresholdLines: false,
                showLegend: false,
                showPercentStackView: false,
                showValuesOnSeries: false,
                smoothingIntervals: 1,
                yAxisScaleType: 'linear',
            },
            action: {
                days: ['2025-01-19T00:00:00Z', '2025-01-26T00:00:00Z'],
                id: '$web_vitals',
                type: 'events',
                order: 3,
                name: '$web_vitals',
                custom_name: 'FCP',
                math: 'p90',
                math_property: '$web_vitals_FCP_value',
                math_hogql: null,
                math_group_type_index: null,
                properties: {},
            },
        },
    ],
    timezone: 'UTC',
    timings: [],
}
