from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "surveys": {
        "description": "Every survey in the Qualtrics brand the credentials can see, with its owner and status.",
        "docs_url": "https://api.qualtrics.com/",
        "columns": {
            "id": "Unique survey identifier, prefixed with `SV_`.",
            "name": "Name of the survey as shown in the Qualtrics project list.",
            "ownerId": "Identifier of the Qualtrics user who owns the survey.",
            "lastModified": "Timestamp of the most recent change to the survey.",
            "creationDate": "Timestamp the survey was created.",
            "isActive": "Whether the survey is currently collecting responses.",
        },
    },
    "survey_responses": {
        "description": "Recorded responses for every survey, pulled through the Qualtrics response export.",
        "docs_url": "https://api.qualtrics.com/",
        "columns": {
            "responseId": "Unique response identifier, prefixed with `R_`.",
            "surveyId": "Identifier of the survey the response belongs to.",
            "recordedDate": "Timestamp the response was recorded, and the cursor used for incremental syncs.",
            "startDate": "Timestamp the respondent started the survey.",
            "endDate": "Timestamp the respondent last interacted with the survey.",
            "status": "Response type code, for example survey preview, test response, or a real response.",
            "progress": "How far through the survey the respondent got, as a percentage.",
            "duration": "Seconds the respondent spent on the survey.",
            "finished": "Whether the respondent reached the end of the survey.",
            "distributionChannel": "How the response was collected, for example anonymous link or email.",
            "userLanguage": "Language the survey was taken in.",
            "values": "JSON object of raw answer values keyed by question id, plus embedded data.",
            "labels": "JSON object of the human-readable choice labels matching `values`.",
            "displayedFields": "JSON array of the question ids that were displayed to the respondent.",
            "displayedValues": "JSON object of the choices that were displayed for each question.",
        },
    },
    "survey_questions": {
        "description": "Question definitions for each survey, from the survey definition API.",
        "docs_url": "https://api.qualtrics.com/",
        "columns": {
            "QuestionID": "Identifier of the question within its survey, for example `QID3`.",
            "surveyId": "Identifier of the survey the question belongs to.",
            "QuestionText": "Question text as shown to respondents.",
            "QuestionType": "Question type code, for example `MC` for multiple choice or `TE` for text entry.",
            "Selector": "Sub-type that refines the question type, for example single answer or multiple answer.",
            "DataExportTag": "Short tag used as the question's column name in Qualtrics exports.",
            "QuestionDescription": "Internal description of the question.",
            "Choices": "Answer choices defined for the question.",
        },
    },
    "distributions": {
        "description": "Distributions (email, SMS and link invitations) sent for each survey.",
        "docs_url": "https://api.qualtrics.com/",
        "columns": {
            "id": "Unique distribution identifier, prefixed with `EMD_`.",
            "surveyId": "Identifier of the survey the distribution was sent for.",
            "parentDistributionId": "Identifier of the distribution this one follows up on, if any.",
            "ownerId": "Identifier of the Qualtrics user who created the distribution.",
            "organizationId": "Identifier of the Qualtrics organization the distribution belongs to.",
            "requestStatus": "Current state of the distribution request, for example pending or done.",
            "requestType": "Kind of distribution, for example an invite or a reminder.",
            "sendDate": "Timestamp the distribution was scheduled to send.",
            "createdDate": "Timestamp the distribution was created.",
            "modifiedDate": "Timestamp the distribution was last changed.",
            "stats": "Delivery counters for the distribution, such as sent, opened and finished.",
        },
    },
    "users": {
        "description": "Users in the Qualtrics brand, with their division, role and account status.",
        "docs_url": "https://api.qualtrics.com/",
        "columns": {
            "id": "Unique user identifier, prefixed with `UR_`.",
            "username": "Login name of the user.",
            "email": "Email address of the user.",
            "firstName": "First name of the user.",
            "lastName": "Last name of the user.",
            "userType": "Permission set assigned to the user.",
            "divisionId": "Identifier of the division the user belongs to.",
            "organizationId": "Identifier of the Qualtrics organization the user belongs to.",
            "accountStatus": "Whether the account is active or disabled.",
            "unsubscribed": "Whether the user has unsubscribed from Qualtrics emails.",
            "language": "Interface language set for the user.",
        },
    },
    "groups": {
        "description": "Groups used to share surveys, libraries and other assets between Qualtrics users.",
        "docs_url": "https://api.qualtrics.com/",
        "columns": {
            "id": "Unique group identifier, prefixed with `GR_`.",
            "name": "Name of the group.",
            "type": "Group type, which controls the permissions members inherit.",
            "divisionId": "Identifier of the division the group belongs to, if any.",
            "organizationId": "Identifier of the Qualtrics organization the group belongs to.",
        },
    },
    "divisions": {
        "description": "Divisions used to partition users and content inside a Qualtrics brand.",
        "docs_url": "https://api.qualtrics.com/",
        "columns": {
            "divisionId": "Unique division identifier, prefixed with `DV_`.",
            "name": "Name of the division.",
            "divisionStatus": "Whether the division is active or disabled.",
            "creationDate": "Timestamp the division was created.",
            "creatorId": "Identifier of the Qualtrics user who created the division.",
        },
    },
}
