# This file is automatically generated from `SourceRegistry.get_all_sources()`
# Do not edit manually - run `pnpm generate:source-configs` to regenerate.

from typing import Literal

from products.warehouse_sources.backend.temporal.data_imports.sources.common import config


@config.config
class CiscoMerakiSourceConfig(config.Config):
    api_key: str
    organization_id: str
    region: Literal["global", "canada", "china", "india", "us_government"] = config.value(default="global")
