import { MakeLogicType, connect, events, kea, key, path, props, selectors } from 'kea'
import { loaders } from 'kea-loaders'

import { teamLogic } from 'scenes/teamLogic'

import { logsAttributesRetrieve } from '../../../generated/api'
import { customFacetsLogic } from './customFacetsLogic'
import { FACETS, FacetConfig, resolveFacets } from './facets'

// Broad, filter-independent window for the "which resource attributes does this tenant emit" probe.
// Cheap: keys-only group-by on the log_attributes aggregation table (no value scan).
const PRESENCE_LOOKBACK = { date_from: '-90d' }

export interface FacetPresenceLogicProps {
    id: string
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface facetPresenceLogicValues {
    customFacets: FacetConfig[] // customFacetsLogic
    currentTeamId: number | null // teamLogic
    presentResourceKeys: string[]
    presentResourceKeysLoading: boolean
    resolvedFacets: FacetConfig[]
    visibleFacets: FacetConfig[]
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface facetPresenceLogicActions {
    loadPresentResourceKeys: () => any
    loadPresentResourceKeysFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadPresentResourceKeysSuccess: (
        presentResourceKeys: string[],
        payload?: any
    ) => {
        presentResourceKeys: string[]
        payload?: any
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface facetPresenceLogicMeta {
    key: string
    __keaTypeGenInternalSelectorTypes: {
        resolvedFacets: (presentResourceKeys: string[]) => FacetConfig[]
        visibleFacets: (resolvedFacets: FacetConfig[], customFacets: FacetConfig[]) => FacetConfig[]
    }
}

export type facetPresenceLogicType = MakeLogicType<
    facetPresenceLogicValues,
    facetPresenceLogicActions,
    FacetPresenceLogicProps,
    facetPresenceLogicMeta
>

/**
 * Which facets the rail renders. The curated list in FACETS is config, not data: a resource-attribute
 * facet only earns a slot if the tenant emits its key (or an older spelling of it), so this probes the
 * emitted keys once on mount and resolves the list against them. Values and counts are fetched per
 * facet, by facetValuesLogic.
 */
export const facetPresenceLogic = kea<facetPresenceLogicType>([
    props({ id: 'default' } as FacetPresenceLogicProps),
    key((props) => props.id),
    path((key) => ['products', 'logs', 'frontend', 'components', 'LogsViewer', 'FacetRail', 'facetPresenceLogic', key]),

    connect(() => ({
        values: [teamLogic, ['currentTeamId'], customFacetsLogic, ['customFacets']],
    })),

    loaders(({ values }) => ({
        presentResourceKeys: [
            [] as string[],
            {
                // Which resource attribute keys the tenant emits — gates which curated facets render.
                loadPresentResourceKeys: async () => {
                    if (!values.currentTeamId) {
                        return []
                    }
                    const response = await logsAttributesRetrieve(String(values.currentTeamId), {
                        attribute_type: 'resource',
                        dateRange: PRESENCE_LOOKBACK,
                        limit: 100,
                    })
                    return response.results.map((r) => r.name)
                },
            },
        ],
    })),

    selectors({
        // Column facets always render; resource-attribute facets only when the tenant emits the key (or one
        // of its aliases, which resolution rewrites the facet onto). Custom facets skip that presence gate
        // entirely — the user picked them from a live taxonomic list, so they're known to exist already —
        // and render last, after every curated facet.
        // Intermediate so curated facet identities stay stable across custom-facet changes — a fresh
        // alias-resolved FacetConfig would re-render every virtualized value row (see RailFacet).
        resolvedFacets: [
            (s) => [s.presentResourceKeys],
            (presentResourceKeys: string[]): FacetConfig[] => resolveFacets(FACETS, presentResourceKeys),
        ],
        visibleFacets: [
            (s) => [s.resolvedFacets, s.customFacets],
            (resolvedFacets: FacetConfig[], customFacets: FacetConfig[]): FacetConfig[] => [
                ...resolvedFacets,
                ...customFacets,
            ],
        ],
    }),

    events(({ actions }) => ({
        afterMount: () => actions.loadPresentResourceKeys(),
    })),
])
