import { MakeLogicType, actions, connect, kea, key, path, props, reducers, selectors } from 'kea'
import { loaders } from 'kea-loaders'
import { subscriptions } from 'kea-subscriptions'

import { teamLogic } from 'scenes/teamLogic'

import { UniversalFiltersGroup } from '~/types'

import { logsViewerFiltersLogic } from 'products/logs/frontend/components/LogsViewer/Filters/logsViewerFiltersLogic'

import { logsFacetValuesCreate } from '../../../generated/api'
import { _LogFacetValueApi, _LogPropertyFilterApi, _LogsFacetValuesBodyApi } from '../../../generated/api.schemas'
import type { LogsViewerFilters } from '../config/types'
import { facetRailLogic } from './facetRailLogic'
import { FacetConfig, facetScopeSignature, facetSourceKey } from './facets'

export interface FacetValuesLogicProps {
    id: string
    /** Already resolved by resolveFacets, so `source` points at the key the tenant emits. */
    facet: FacetConfig
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface facetValuesLogicValues {
    collapsedFacets: string[] // facetRailLogic
    facetRefreshCounter: number // logsViewerFiltersLogic
    filters: LogsViewerFilters // logsViewerFiltersLogic
    personId: string | undefined // logsViewerFiltersLogic
    queryFilterGroup: UniversalFiltersGroup // logsViewerFiltersLogic
    utcDateRange: {
        date_from: string | null | undefined
        date_to: string | null | undefined
        explicitDate: boolean | null | undefined
    } // logsViewerFiltersLogic
    currentTeamId: number | null // teamLogic
    collapsed: boolean
    facetSearch: string
    facetValues: _LogFacetValueApi[]
    facetValuesLoading: boolean
    fetchSignature: string
    fetchedSignature: string | null
    scopeSignature: string
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface facetValuesLogicActions {
    clearFetchedSignature: () => {
        value: true
    }
    loadFacetValues: (signature: string) => {
        signature: string
    }
    loadFacetValuesFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadFacetValuesSuccess: (
        facetValues: _LogFacetValueApi[],
        payload?: {
            signature: string
        }
    ) => {
        facetValues: _LogFacetValueApi[]
        payload?: {
            signature: string
        }
    }
    setFacetSearch: (search: string) => {
        search: string
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface facetValuesLogicMeta {
    key: string
    __keaTypeGenInternalSelectorTypes: {
        collapsed: (collapsedFacets: string[], arg: any) => boolean
        scopeSignature: (
            filters: LogsViewerFilters,
            queryFilterGroup: UniversalFiltersGroup,
            personId: string | undefined,
            utcDateRange: {
                date_from: string | null | undefined
                date_to: string | null | undefined
                explicitDate: boolean | null | undefined
            },
            currentTeamId: number | null,
            facetRefreshCounter: number,
            arg: FacetConfig
        ) => string
        fetchSignature: (scopeSignature: string, facetSearch: string) => string
    }
}

export type facetValuesLogicType = MakeLogicType<
    facetValuesLogicValues,
    facetValuesLogicActions,
    FacetValuesLogicProps,
    facetValuesLogicMeta
>

/**
 * One facet's values + counts, cross-filtered server-side: the results reflect every active filter
 * except this facet's own selection, which the backend strips from the WHERE clause.
 *
 * One instance per facet, so each fetches on its own schedule and holds its own loading state. What
 * it fetches on is `fetchSignature` — the scope with this facet's own filters removed, plus its
 * type-ahead — so clicking a value here re-scopes the *other* facets and leaves this list alone,
 * and a facet whose section is collapsed doesn't fetch at all until it's expanded.
 */
export const facetValuesLogic = kea<facetValuesLogicType>([
    props({} as FacetValuesLogicProps),
    // The resolved source key is part of the key: when alias resolution moves a facet onto another
    // attribute spelling, that's a different query, so it gets a fresh instance rather than the old
    // key's values.
    key((props) => `${props.id}-${props.facet.key}-${facetSourceKey(props.facet)}`),
    path((key) => ['products', 'logs', 'frontend', 'components', 'LogsViewer', 'FacetRail', 'facetValuesLogic', key]),

    connect((props: FacetValuesLogicProps) => ({
        values: [
            logsViewerFiltersLogic({ id: props.id }),
            ['filters', 'utcDateRange', 'queryFilterGroup', 'personId', 'facetRefreshCounter'],
            teamLogic,
            ['currentTeamId'],
            facetRailLogic({ id: props.id }),
            ['collapsedFacets'],
        ],
    })),

    actions({
        setFacetSearch: (search: string) => ({ search }),
        // Declared here rather than left to the loader: the request is built from current values,
        // and the signature payload is only there for the reducer below to record.
        loadFacetValues: (signature: string) => ({ signature }),
        clearFetchedSignature: true,
    }),

    reducers({
        facetSearch: [
            '',
            {
                setFacetSearch: (_, { search }) => search,
            },
        ],
        // The signature the values in the store were fetched for. Set when the request goes out, not
        // when it lands, so an overlapping trigger (e.g. expanding the facet mid-flight) doesn't
        // restart the same request. Cleared on failure, and when collapsing abandons an in-flight
        // load, so the next trigger retries rather than trusting values that never arrived.
        fetchedSignature: [
            null as string | null,
            {
                loadFacetValues: (_, { signature }) => signature,
                loadFacetValuesFailure: () => null,
                clearFetchedSignature: () => null,
            },
        ],
    }),

    loaders(({ props, values }) => ({
        facetValues: [
            [] as _LogFacetValueApi[],
            {
                loadFacetValues: async (_, breakpoint) => {
                    await breakpoint(300)
                    // Collapsed while this was still debouncing: nobody can see the list, so drop the
                    // request. clearFetchedSignature has already run, so expanding refetches.
                    if (values.collapsed || !values.currentTeamId) {
                        return values.facetValues
                    }
                    const { source } = props.facet
                    const group = values.queryFilterGroup as UniversalFiltersGroup
                    const filterGroup = ((group?.values?.[0] as UniversalFiltersGroup | undefined)?.values ??
                        []) as unknown as _LogPropertyFilterApi[]
                    const target: Partial<_LogsFacetValuesBodyApi> =
                        source.type === 'column'
                            ? { facetField: source.column }
                            : source.type === 'attribute'
                              ? { facetAttribute: source.key }
                              : { facetResourceAttribute: source.key }
                    const response = await logsFacetValuesCreate(String(values.currentTeamId), {
                        query: {
                            ...target,
                            dateRange: values.utcDateRange,
                            searchTerm: values.filters.searchTerm || undefined,
                            facetSearch: values.facetSearch || undefined,
                            filterGroup,
                            personId: values.personId,
                        },
                    })
                    // Bail out right after the round-trip: the rail (and this logic) unmounts when the
                    // user collapses it, and returning into a dead store throws rather than being
                    // discarded.
                    breakpoint()
                    return response.results
                },
            },
        ],
    })),

    selectors({
        collapsed: [
            (s) => [s.collapsedFacets, (_, p) => p.facet],
            (collapsedFacets: string[], facet: FacetConfig): boolean => collapsedFacets.includes(facet.key),
        ],
        // Everything that can change this facet's values, minus its own selection.
        scopeSignature: [
            (s) => [
                s.filters,
                s.queryFilterGroup,
                s.personId,
                s.utcDateRange,
                s.currentTeamId,
                s.facetRefreshCounter,
                (_, p) => p.facet as FacetConfig,
            ],
            (
                filters: LogsViewerFilters,
                queryFilterGroup: UniversalFiltersGroup,
                personId: string | undefined,
                utcDateRange: {
                    date_from: string | null | undefined
                    date_to: string | null | undefined
                    explicitDate: boolean | null | undefined
                },
                currentTeamId: number | null,
                facetRefreshCounter: number,
                facet: FacetConfig
            ): string =>
                `${facetScopeSignature(facet, {
                    currentTeamId,
                    utcDateRange,
                    searchTerm: filters.searchTerm,
                    queryFilterGroup,
                    personId,
                })}|r${facetRefreshCounter}`,
        ],
        // One trigger for the one in-flight request: a scope change and a keystroke in this facet's
        // search box supersede each other rather than racing.
        fetchSignature: [
            (s) => [s.scopeSignature, s.facetSearch],
            (scopeSignature: string, facetSearch: string): string => `${scopeSignature}|${facetSearch}`,
        ],
    }),

    subscriptions(({ actions, values }) => {
        // Subscriptions fire with their initial value, so this is also the mount fetch.
        const loadIfStale = (): void => {
            if (values.collapsed || values.fetchSignature === values.fetchedSignature) {
                return
            }
            actions.loadFacetValues(values.fetchSignature)
        }
        return {
            fetchSignature: loadIfStale,
            collapsed: (collapsed: boolean) => {
                if (collapsed) {
                    // The loader drops a still-debouncing load on collapse, so forget the signature it
                    // recorded — otherwise expanding would trust values that never arrived. Only when
                    // one is in flight: settled values stay valid for their signature.
                    if (values.facetValuesLoading) {
                        actions.clearFetchedSignature()
                    }
                    return
                }
                // Expanding fetches what it missed while collapsed — and nothing if the scope hasn't
                // moved since.
                loadIfStale()
            },
        }
    }),
])
