from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "chart_transactions": {
        "description": "General-ledger transactions (ChartTransaction records) - Campfire's GL transaction log and the recommended endpoint for row-level GL data. Each transaction carries account, department, vendor, entity, and journal/date metadata.",
        "docs_url": "https://docs.campfire.ai/api-reference/core-accounting/list-chart-transactions",
        "columns": {
            "id": "Unique identifier for the GL transaction.",
            "amount": "Amount in the consolidated currency (the root entity's currency).",
            "amount_book": "Amount in the currency of the entity the transaction belongs to.",
            "amount_native": "Amount in the currency the transaction was originally created in.",
            "posted_at": "The transaction date; determines which accounting period the transaction falls in.",
            "vendor": "ID of the linked Campfire Vendor object.",
            "vendor_name": "Name of the linked Campfire Vendor object.",
            "merchant_name": "Free-text merchant name stored directly on the transaction; not linked to any Campfire object.",
            "account": "The Campfire ChartAccount (GL account) the transaction is posted to.",
            "entity": "The Campfire ChartEntity ID the transaction belongs to.",
            "last_modified_at": "Timestamp of the last modification to the transaction.",
        },
    },
    "journal_entries": {
        "description": "Journal entries with their transactions, account information, vendor and department details, tag associations, attachments, and exchange rate data for multi-currency entries.",
        "docs_url": "https://docs.campfire.ai/api-reference/core-accounting/list-journal-entries",
        "columns": {
            "id": "Unique identifier for the journal entry.",
            "date": "The journal entry date, which determines the accounting period.",
            "created_at": "Timestamp when the journal entry was created.",
            "last_modified_at": "Timestamp of the last modification to the journal entry.",
        },
    },
    "invoices": {
        "description": "Accounts receivable invoices, including line items, payment status, client and entity relationships, and totals.",
        "docs_url": "https://docs.campfire.ai/api-reference/accounts-receivable/list-invoices",
        "columns": {
            "id": "Unique identifier for the invoice.",
            "invoice_date": "The invoice date.",
            "created_at": "Timestamp when the invoice was created.",
            "last_modified_at": "Timestamp of the last modification to the invoice.",
        },
    },
    "invoice_payments": {
        "description": "Payments applied against accounts receivable invoices. Voided payments are included with voided_date set, so payments reversed after a previous sync can be detected.",
        "docs_url": "https://docs.campfire.ai/api-reference/accounts-receivable/list-invoice-payments",
        "columns": {
            "id": "Unique identifier for the invoice payment.",
            "amount": "Payment amount.",
            "currency": "Payment currency.",
            "payment_date": "Date the payment was applied.",
            "source": "Where the payment originated.",
            "source_id": "Identifier of the payment in its source system.",
            "voided_date": "Date the payment was voided, when it has been reversed.",
            "created_at": "Timestamp when the payment record was created.",
            "last_modified_at": "Timestamp of the last modification to the payment record.",
        },
    },
    "credit_memos": {
        "description": "Accounts receivable credit memos, including line items, application status (open, partially used, used, voided), and client relationships.",
        "docs_url": "https://docs.campfire.ai/api-reference/accounts-receivable/list-credit-memos",
        "columns": {
            "id": "Unique identifier for the credit memo.",
            "credit_memo_date": "The credit memo date.",
            "created_at": "Timestamp when the credit memo was created.",
            "last_modified_at": "Timestamp of the last modification to the credit memo.",
        },
    },
    "bills": {
        "description": "Accounts payable bills with vendor, entity, currency, aging, and payment status information, including calculated totals, amounts paid, and amounts due.",
        "docs_url": "https://docs.campfire.ai/api-reference/accounts-payable/list-accounting-bills",
        "columns": {
            "id": "Unique identifier for the bill.",
            "last_modified_at": "Timestamp of the last modification to the bill.",
        },
    },
    "bill_payments": {
        "description": "Payments applied against accounts payable bills. Voided payments are included with voided_date set, so payments reversed after a previous sync can be detected.",
        "docs_url": "https://docs.campfire.ai/api-reference/accounts-payable/list-bill-payments",
        "columns": {
            "id": "Unique identifier for the bill payment.",
            "bill_id": "ID of the bill the payment was applied to.",
            "bill_number": "Number of the bill the payment was applied to.",
            "amount": "Payment amount.",
            "currency": "Payment currency.",
            "payment_date": "Date the payment was applied.",
            "source": "Where the payment originated.",
            "source_id": "Identifier of the payment in its source system.",
            "voided_date": "Date the payment was voided, when it has been reversed.",
            "created_at": "Timestamp when the payment record was created.",
            "last_modified_at": "Timestamp of the last modification to the payment record.",
        },
    },
    "debit_memos": {
        "description": "Accounts payable debit memos, including line items, status, and vendor relationships.",
        "docs_url": "https://docs.campfire.ai/api-reference/accounts-payable/list-debit-memos",
        "columns": {
            "id": "Unique identifier for the debit memo.",
            "debit_memo_date": "The debit memo date.",
            "created_at": "Timestamp when the debit memo was created.",
            "last_modified_at": "Timestamp of the last modification to the debit memo.",
        },
    },
    "bank_accounts": {
        "description": "Bank accounts with balances, currency, institution details, and their mapping to chart of accounts types.",
        "docs_url": "https://docs.campfire.ai/api-reference/cash-management/list-bank-accounts",
        "columns": {
            "id": "Unique identifier for the bank account.",
            "created_at": "Timestamp when the bank account record was created.",
            "last_modified_at": "Timestamp of the last modification to the bank account record.",
        },
    },
    "bank_transactions": {
        "description": "Bank transactions from connected bank accounts.",
        "docs_url": "https://docs.campfire.ai/api-reference/cash-management/list-bank-transactions",
        "columns": {
            "id": "Unique identifier for the bank transaction.",
            "posted_at": "Date the transaction posted at the bank.",
            "created_at": "Timestamp when the bank transaction record was created.",
            "last_modified_at": "Timestamp of the last modification to the bank transaction record.",
        },
    },
    "vendors": {
        "description": "Vendors and customers, including contact details, parent vendor metadata, and the full lineage of ancestor vendors so parent/child relationships can be reconstructed.",
        "docs_url": "https://docs.campfire.ai/api-reference/company-objects/list-vendors",
        "columns": {
            "id": "Unique identifier for the vendor.",
            "name": "Vendor or customer name.",
            "vendor_type": "Whether the record is a vendor or a customer.",
            "parent_name": "Name of the parent vendor, when the vendor has one.",
            "created_at": "Timestamp when the vendor record was created.",
            "last_modified_at": "Timestamp of the last modification to the vendor record.",
        },
    },
    "departments": {
        "description": "Departments, including parent department metadata so parent/child relationships can be reconstructed.",
        "docs_url": "https://docs.campfire.ai/api-reference/company-objects/list-departments",
        "columns": {
            "id": "Unique identifier for the department.",
            "created_at": "Timestamp when the department record was created.",
            "last_modified_at": "Timestamp of the last modification to the department record.",
        },
    },
    "chart_of_accounts": {
        "description": "The chart of accounts (GL accounts). Each account includes metadata about its parent account and its full lineage, so parent/child account relationships can be reconstructed.",
        "docs_url": "https://docs.campfire.ai/api-reference/company-objects/list-chart-of-accounts",
        "columns": {
            "id": "Unique identifier for the GL account.",
            "created_at": "Timestamp when the account record was created.",
            "last_modified_at": "Timestamp of the last modification to the account record.",
        },
    },
    "chart_entities": {
        "description": "Legal entities (ChartEntity records) in the company structure. Every transaction, invoice and contract carries an entity ID, and each entity records its parent, its pre-computed lineage, its reporting currency and its fiscal year start, so multi-entity consolidation can be reconstructed.",
        "docs_url": "https://docs.campfire.ai/api-reference/settings/list-chart-entities",
        "columns": {
            "id": "Unique identifier for the entity.",
            "name": "Name of the entity.",
            "currency": "The entity's reporting currency.",
            "parent": "ID of the parent entity, when the entity sits below another one.",
            "parent_name": "Name of the parent entity.",
            "lineage_array": "Pre-computed lineage array from the root entity down to this entity.",
            "elimination_entity": "ID of the entity that holds this entity's consolidation eliminations.",
            "is_elimination_entity": "Whether the entity exists to hold consolidation eliminations.",
            "primary_entity": "ID of the entity this one adjusts, when it is an adjusting entity.",
            "is_adjusting": "Whether the entity is an adjusting entity (it has a primary entity set).",
            "active": "Whether the entity is active.",
            "fiscal_year_month": "Month the entity's fiscal year starts in.",
            "fiscal_year_day": "Day of the month the entity's fiscal year starts on.",
            "tax_identification_number": "The entity's tax identification number.",
            "is_deleted": "Whether the entity has been deleted.",
            "deleted_at": "Timestamp when the entity was deleted.",
            "created_at": "Timestamp when the entity record was created.",
            "last_modified_at": "Timestamp of the last modification to the entity record.",
        },
    },
    "contracts": {
        "description": "Revenue recognition contracts.",
        "docs_url": "https://docs.campfire.ai/api-reference/revenue-recognition/list-contracts",
        "columns": {
            "id": "Unique identifier for the contract.",
            "start_date": "Contract start date.",
            "created_at": "Timestamp when the contract record was created.",
            "last_modified_at": "Timestamp of the last modification to the contract record.",
        },
    },
    "revenue_transactions": {
        "description": "Revenue transactions used for revenue recognition.",
        "docs_url": "https://docs.campfire.ai/api-reference/revenue-recognition/list-revenue-transactions",
        "columns": {
            "id": "Unique identifier for the revenue transaction.",
            "transaction_date": "The revenue transaction date.",
            "created_at": "Timestamp when the revenue transaction record was created.",
            "last_modified_at": "Timestamp of the last modification to the revenue transaction record.",
        },
    },
    "contract_subscriptions": {
        "description": "Subscription schedules on revenue recognition contracts. Each subscription carries its product, rate, quantity, billing cadence and start and end dates, which is what ARR/MRR and revenue recognition waterfalls are built from. Collected by walking the contracts table, so every row names the contract it belongs to.",
        "docs_url": "https://docs.campfire.ai/api-reference/revenue-recognition/list-contract-subscriptions",
        "columns": {
            "id": "Identifier for the subscription within its contract.",
            "contract": "ID of the Campfire contract the subscription belongs to.",
            "product": "ID of the linked product.",
            "product_name": "Name of the linked product.",
            "product_bundle": "ID of the product bundle the subscription was sold in.",
            "product_bundle_name": "Name of the product bundle the subscription was sold in.",
            "rate": "Price per unit for the subscription.",
            "quantity": "Number of units subscribed.",
            "total_value": "Total contracted value of the subscription.",
            "mrr": "Monthly recurring revenue attributed to the subscription.",
            "counts_toward_mrr": "Whether the subscription is included in recurring revenue totals.",
            "discount": "Discount applied to the subscription.",
            "billing_cadence": "How often the subscription is billed (one_time, monthly, quarterly, biannual or annual).",
            "billing_timing": "Whether the subscription bills in advance or in arrears.",
            "first_invoice_date": "Date of the subscription's first invoice.",
            "start_date": "Date the subscription starts.",
            "end_date": "Date the subscription ends.",
            "renewal_behavior": "Whether the subscription follows its contract's renewal or has a fixed end.",
            "revenue_recognition_type": "How revenue is recognized (RATABLE or RELATIVE_TO_PREPAID_COMMIT).",
            "proration_method": "How partial periods are prorated (standard, thirty_day or daily).",
            "is_contract_amendment": "Whether the subscription came from an amendment to the contract.",
            "source": "System the subscription originated in (SALESFORCE, HUBSPOT, STRIPE or MANUAL).",
            "external_id": "Identifier of the subscription in its source system.",
            "is_deleted": "Whether the subscription has been deleted.",
            "deleted_at": "Timestamp when the subscription was deleted.",
            "created_at": "Timestamp when the subscription record was created.",
            "last_modified_at": "Timestamp of the last modification to the subscription record.",
        },
    },
    "products": {
        "description": "The product catalog behind contract line items, including pricing, usage tiers and the GL accounts each product posts revenue, AR and tax to.",
        "docs_url": "https://docs.campfire.ai/api-reference/revenue-recognition/list-contract-products",
        "columns": {
            "id": "Unique identifier for the product.",
            "product_uuid": "Stable UUID for the product.",
            "product_id": "Your own identifier for the product.",
            "product_name": "Name of the product.",
            "product_description": "Description of the product.",
            "display_name": "Name shown for the product in Campfire.",
            "currency": "Currency the product is priced in.",
            "price": "List price of the product.",
            "cost": "Cost of the product.",
            "is_taxable": "Whether the product is taxable.",
            "is_renewable": "Whether the product renews.",
            "recognize_revenue": "Whether revenue is recognized for the product.",
            "is_immediate_recognition": "Whether revenue is recognized immediately rather than over time.",
            "exclude_from_mrr": "Whether the product is excluded from recurring revenue totals.",
            "revenue_account": "ID of the GL account revenue for the product posts to.",
            "revenue_account_name": "Name of the GL account revenue for the product posts to.",
            "ar_account": "ID of the accounts receivable GL account for the product.",
            "ar_account_name": "Name of the accounts receivable GL account for the product.",
            "invoice_account": "ID of the GL account the product's invoices post to.",
            "invoice_account_name": "Name of the GL account the product's invoices post to.",
            "tax_account_name": "Name of the GL account tax on the product posts to.",
            "department": "ID of the department the product belongs to.",
            "department_name": "Name of the department the product belongs to.",
            "usage_group_count": "Number of usage pricing groups defined on the product.",
            "usage_groups": "Usage pricing groups, each with its pricing model, unit of measure and tiers.",
            "tags": "Tags attached to the product.",
            "stripe_product_id": "Identifier of the matching product in Stripe.",
            "customer": "ID of the Campfire customer account the product belongs to.",
            "is_deleted": "Whether the product has been deleted.",
            "deleted_at": "Timestamp when the product was deleted.",
            "created_at": "Timestamp when the product record was created.",
            "last_modified_at": "Timestamp of the last modification to the product record.",
        },
    },
    "customers": {
        "description": "Customer records referenced by contracts, invoices and revenue transactions, with contact and billing details plus Campfire's rolled-up contract, revenue and receivable totals per customer.",
        "docs_url": "https://docs.campfire.ai/api-reference/revenue-recognition/list-contract-customers",
        "columns": {
            "id": "Unique identifier for the customer.",
            "name": "Name of the customer.",
            "display_name": "Name shown for the customer in Campfire.",
            "dba": "The name the customer does business as.",
            "company_name": "Registered company name of the customer.",
            "status": "Whether the customer is ACTIVE or INACTIVE.",
            "currency": "Currency the customer transacts in.",
            "email": "Primary email address for the customer.",
            "phone_number": "Primary phone number for the customer.",
            "website": "Customer's website.",
            "parent": "ID of the parent customer, when the customer sits below another one.",
            "parent_name": "Name of the parent customer.",
            "lineage_array": "Pre-computed lineage array from the root customer down to this one.",
            "contacts": "Contacts attached to the customer.",
            "payment_term": "ID of the payment term applied to the customer.",
            "payment_term_name_display": "Name of the payment term applied to the customer.",
            "active_contracts": "Number of the customer's contracts that are active.",
            "completed_contracts": "Number of the customer's contracts that have completed.",
            "pending_contracts": "Number of the customer's contracts that have not started.",
            "total_contracts": "Total number of contracts for the customer.",
            "total_revenue": "Revenue recognized for the customer.",
            "total_deferred_revenue": "Revenue billed to the customer but not yet recognized.",
            "total_mrr": "Monthly recurring revenue attributed to the customer.",
            "total_billed": "Total amount invoiced to the customer.",
            "total_unbilled": "Contracted amount not yet invoiced to the customer.",
            "total_paid": "Total amount the customer has paid.",
            "total_outstanding": "Invoiced amount the customer still owes.",
            "total_credit_memos": "Total value of credit memos issued to the customer.",
            "credit_memo_applied": "Credit memo value already applied to the customer's invoices.",
            "credit_memo_available": "Credit memo value still available to apply.",
            "vat_number": "The customer's VAT number.",
            "stripe_customer_id": "Identifier of the matching customer in Stripe.",
            "source": "System the customer record originated in (BILL, BREX, HUBSPOT, MANUAL, PAYROLL or SALESFORCE).",
            "external_id": "Identifier of the customer in its source system.",
            "campfire_id": "Campfire's own reference for the customer.",
            "customer": "ID of the Campfire customer account the record belongs to.",
            "is_deleted": "Whether the customer has been deleted.",
            "deleted_at": "Timestamp when the customer was deleted.",
            "created_at": "Timestamp when the customer record was created.",
            "last_modified_at": "Timestamp of the last modification to the customer record.",
        },
    },
}
