from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Descriptions sourced from the inFlow Inventory Cloud API docs (https://cloudapi.inflowinventory.com/docs).
# Partial coverage is fine — uncovered columns fall back to LLM enrichment.
_DOCS_URL = "https://cloudapi.inflowinventory.com/docs"

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "products": {
        "description": "A product (inventory item) tracked in inFlow Inventory.",
        "docs_url": _DOCS_URL,
        "columns": {
            "productId": "The unique ID of the product.",
            "name": "The product name.",
            "sku": "The product's stock keeping unit (SKU).",
            "description": "A description of the product.",
            "itemType": "The type of item (e.g. stocked product, service, or non-stocked).",
            "isActive": "Whether the product is active.",
            "defaultPrice": "The default sales price of the product.",
            "cost": "The cost of the product.",
            "barcode": "The product's barcode value.",
            "categoryId": "The ID of the category the product belongs to.",
            "timestamp": "The row version timestamp used for change tracking.",
        },
    },
    "customers": {
        "description": "A customer in inFlow Inventory that sales orders are placed for.",
        "docs_url": _DOCS_URL,
        "columns": {
            "customerId": "The unique ID of the customer.",
            "name": "The customer name.",
            "email": "The customer's primary email address.",
            "phone": "The customer's phone number.",
            "remarks": "Free-text remarks recorded against the customer.",
            "isActive": "Whether the customer is active.",
            "defaultCarrier": "The default shipping carrier for the customer.",
            "defaultPaymentTerms": "The default payment terms for the customer.",
            "timestamp": "The row version timestamp used for change tracking.",
        },
    },
    "vendors": {
        "description": "A vendor (supplier) that purchase orders are placed with in inFlow Inventory.",
        "docs_url": _DOCS_URL,
        "columns": {
            "vendorId": "The unique ID of the vendor.",
            "name": "The vendor name.",
            "email": "The vendor's primary email address.",
            "phone": "The vendor's phone number.",
            "remarks": "Free-text remarks recorded against the vendor.",
            "isActive": "Whether the vendor is active.",
            "defaultCarrier": "The default shipping carrier for the vendor.",
            "defaultPaymentTerms": "The default payment terms for the vendor.",
            "timestamp": "The row version timestamp used for change tracking.",
        },
    },
    "sales_orders": {
        "description": "A sales order recording products sold to a customer.",
        "docs_url": _DOCS_URL,
        "columns": {
            "salesOrderId": "The unique ID of the sales order.",
            "orderNumber": "The human-readable order number.",
            "customerId": "The ID of the customer the order is for.",
            "orderDate": "The date the order was placed.",
            "orderStatus": "The current status of the order.",
            "total": "The total value of the order.",
            "subTotal": "The order subtotal before tax and shipping.",
            "currencyCode": "The currency the order is denominated in.",
            "lines": "The line items on the order.",
            "timestamp": "The row version timestamp used for change tracking.",
        },
    },
    "purchase_orders": {
        "description": "A purchase order recording products bought from a vendor.",
        "docs_url": _DOCS_URL,
        "columns": {
            "purchaseOrderId": "The unique ID of the purchase order.",
            "orderNumber": "The human-readable order number.",
            "vendorId": "The ID of the vendor the order is placed with.",
            "orderDate": "The date the order was placed.",
            "orderStatus": "The current status of the order.",
            "total": "The total value of the order.",
            "subTotal": "The order subtotal before tax and shipping.",
            "currencyCode": "The currency the order is denominated in.",
            "lines": "The line items on the order.",
            "timestamp": "The row version timestamp used for change tracking.",
        },
    },
    "manufacturing_orders": {
        "description": "A manufacturing order that consumes component products to build finished products.",
        "docs_url": _DOCS_URL,
        "columns": {
            "manufacturingOrderId": "The unique ID of the manufacturing order.",
            "manufacturingOrderNumber": "The human-readable manufacturing order number.",
            "status": "The current status of the manufacturing order.",
            "orderDate": "The date the manufacturing order was created.",
            "dueDate": "The date the manufacturing order is due to be completed.",
            "completedDate": "The date the manufacturing order was completed.",
            "isCompleted": "Whether the manufacturing order is completed.",
            "isCancelled": "Whether the manufacturing order is cancelled.",
            "locationId": "The ID of the location where manufacturing takes place.",
            "primaryFinishedProductId": "The ID of the main finished product the order builds.",
            "numFinishedProducts": "The number of distinct finished products on the order.",
            "lines": "The finished product lines on the manufacturing order.",
            "lastModifiedDateTime": "When the manufacturing order was last modified.",
            "timestamp": "The row version timestamp used for change tracking.",
        },
    },
    "stock_transfers": {
        "description": "A stock transfer that moves inventory from one location to another.",
        "docs_url": _DOCS_URL,
        "columns": {
            "stockTransferId": "The unique ID of the stock transfer.",
            "transferNumber": "The human-readable transfer number.",
            "status": "The current status of the stock transfer.",
            "fromLocationId": "The ID of the location the stock is sent from.",
            "toLocationId": "The ID of the location the stock is sent to.",
            "transferDate": "The date of the stock transfer.",
            "sentDate": "The date the stock was sent.",
            "receivedDate": "The date the stock was received.",
            "isCancelled": "Whether the stock transfer is cancelled.",
            "lines": "The product lines moved by the transfer.",
            "lastModifiedDateTime": "When the stock transfer was last modified.",
            "timestamp": "The row version timestamp used for change tracking.",
        },
    },
    "locations": {
        "description": "A location (warehouse or store) where inventory is kept in inFlow Inventory.",
        "docs_url": _DOCS_URL,
        "columns": {
            "locationId": "The unique ID of the location.",
            "name": "The location name.",
            "address": "The address of the location.",
            "isActive": "Whether the location is active.",
            "isDefault": "Whether this is the default location.",
            "timestamp": "The row version timestamp used for change tracking.",
        },
    },
    "categories": {
        "description": "A product category used to group products in inFlow Inventory.",
        "docs_url": _DOCS_URL,
        "columns": {
            "categoryId": "The unique ID of the category.",
            "name": "The category name.",
            "parentCategoryId": "The ID of the parent category, if the category is nested.",
            "isDefault": "Whether this is the default category.",
            "timestamp": "The row version timestamp used for change tracking.",
        },
    },
    "stock_adjustments": {
        "description": "A stock adjustment that corrects or writes off inventory at a location outside of an order.",
        "docs_url": _DOCS_URL,
        "columns": {
            "stockAdjustmentId": "The unique ID of the stock adjustment.",
            "adjustmentNumber": "The human-readable adjustment number shown on printed documents.",
            "adjustmentReasonId": "The ID of the reason recorded for the adjustment.",
            "date": "The effective date of the stock adjustment.",
            "locationId": "The ID of the location where inventory is adjusted.",
            "isCancelled": "Whether the adjustment is cancelled. A cancelled adjustment voids its inventory movements.",
            "remarks": "Free-text remarks recorded against the stock adjustment.",
            "customFields": "Custom field values recorded against the stock adjustment.",
            "lastModifiedById": "The ID of the team member, system process, or API key that last modified the adjustment.",
            "lastModifiedDateTime": "When the stock adjustment was last modified.",
            "timestamp": "The row version timestamp used for change tracking.",
        },
    },
    "stock_counts": {
        "description": "A physical stock count at a location, used to reconcile recorded inventory with counted inventory.",
        "docs_url": _DOCS_URL,
        "columns": {
            "stockCountId": "The unique ID of the stock count.",
            "stockCountNumber": "The human-readable stock count number.",
            "status": "The current status of the stock count.",
            "locationId": "The ID of the location where the count takes place.",
            "assignedToTeamMemberId": "The ID of the team member assigned to the count.",
            "startedDate": "The date the stock count was started.",
            "completedDate": "The date the stock count was completed.",
            "isStarted": "Whether the stock count is ready for counting.",
            "isCompleted": "Whether the stock count is completed. Inventory is adjusted when the count completes.",
            "isReviewed": "Whether the stock count has been reviewed.",
            "isCancelled": "Whether the stock count is cancelled. A cancelled count voids its inventory adjustments.",
            "remarks": "Free-text remarks recorded against the stock count.",
            "lastModifiedDateTime": "When the stock count was last modified.",
            "timestamp": "The row version timestamp used for change tracking.",
        },
    },
    "product_cost_adjustments": {
        "description": "A change to a product's inventory cost, effective from a given date.",
        "docs_url": _DOCS_URL,
        "columns": {
            "productCostAdjustmentId": "The unique ID of the product cost adjustment.",
            "productId": "The ID of the product whose cost is adjusted.",
            "dateTime": "The effective date of the cost adjustment.",
            "unitCost": "The new inventory cost per standard unit of measure.",
            "serial": "For serialized products, the serial number whose cost is adjusted.",
            "lastModifiedById": "The ID of the team member, system process, or API key that last modified the adjustment.",
            "timestamp": "The row version timestamp used for change tracking.",
        },
    },
    "tax_codes": {
        "description": "A tax code that sets the tax percentages applied to order lines under a taxing scheme.",
        "docs_url": _DOCS_URL,
        "columns": {
            "taxCodeId": "The unique ID of the tax code.",
            "name": "The tax code name.",
            "taxingSchemeId": "The ID of the taxing scheme the tax code belongs to.",
            "tax1Rate": "The percentage of the primary tax for the tax code.",
            "tax2Rate": "The percentage of the secondary tax for the tax code.",
            "isActive": "Whether the tax code is active.",
            "timestamp": "The row version timestamp used for change tracking.",
        },
    },
    "taxing_schemes": {
        "description": "A taxing scheme that defines the primary and secondary taxes and how they are calculated.",
        "docs_url": _DOCS_URL,
        "columns": {
            "taxingSchemeId": "The unique ID of the taxing scheme.",
            "name": "The taxing scheme name.",
            "tax1Name": "The short display name of the primary tax.",
            "tax2Name": "The short display name of the secondary tax.",
            "tax1OnShipping": "Whether the primary tax applies to shipping costs.",
            "tax2OnShipping": "Whether the secondary tax applies to shipping costs.",
            "calculateTax2OnTax1": "Whether the secondary tax is compounded on top of the primary tax.",
            "defaultTaxCodeId": "The ID of the default tax code for the taxing scheme.",
            "isDefault": "Whether this is the company-wide default taxing scheme.",
            "isActive": "Whether the taxing scheme is active.",
            "timestamp": "The row version timestamp used for change tracking.",
        },
    },
}
