from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

_API_REFERENCE = "https://checkmarx.stoplight.io/docs/checkmarx-one-api-reference-guide"

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "projects": {
        "description": "A Checkmarx One project, the unit that groups scans of a single code repository or component.",
        "docs_url": "https://checkmarx.com/resource/documents/en/34965-91104-projects-api.html",
        "columns": {
            "id": "Unique identifier (UUID) of the project.",
            "name": "Display name of the project.",
            "applicationIds": "Identifiers of the applications this project is assigned to.",
            "groups": "Identifiers of the user groups that have access to the project.",
            "repoUrl": "URL of the source code repository the project scans.",
            "mainBranch": "The repository branch designated as the project's primary branch.",
            "origin": "Where the project was created from (e.g. the web UI, CLI, or an SCM integration).",
            "tags": "Key/value tags assigned to the project.",
            "criticality": "Business criticality level assigned to the project (1-5).",
            "privatePackage": "Whether the project's packages are marked as private for SCA.",
            "createdAt": "Timestamp when the project was created.",
            "updatedAt": "Timestamp when the project was last updated.",
        },
    },
    "applications": {
        "description": "A Checkmarx One application, a business-level grouping of related projects.",
        "docs_url": "https://checkmarx.com/resource/documents/en/34965-91099-applications-api.html",
        "columns": {
            "id": "Unique identifier (UUID) of the application.",
            "name": "Display name of the application.",
            "description": "Free-text description of the application.",
            "criticality": "Business criticality level assigned to the application (1-5).",
            "rules": "Rules that automatically assign projects to this application.",
            "projectIds": "Identifiers of the projects assigned to the application.",
            "tags": "Key/value tags assigned to the application.",
            "createdAt": "Timestamp when the application was created.",
            "updatedAt": "Timestamp when the application was last updated.",
        },
    },
    "scans": {
        "description": "A scan run in Checkmarx One, including its status and the engines (SAST, SCA, KICS, etc.) it executed.",
        "docs_url": "https://checkmarx.com/resource/documents/en/34965-90786-scans-api.html",
        "columns": {
            "id": "Unique identifier (UUID) of the scan.",
            "projectId": "Identifier of the project the scan belongs to.",
            "projectName": "Name of the project the scan belongs to.",
            "branch": "Repository branch that was scanned.",
            "status": "Overall execution status of the scan (e.g. Queued, Running, Completed, Failed, Partial, Canceled).",
            "statusDetails": "Per-engine execution status for the scan.",
            "engines": "Analysis engines that ran in this scan (e.g. sast, sca, kics).",
            "sourceType": "Type of source the scan ran against (e.g. github, upload).",
            "sourceOrigin": "Origin that initiated the scan (e.g. the web UI, CLI, or a CI integration).",
            "initiator": "User or integration that started the scan.",
            "tags": "Key/value tags assigned to the scan.",
            "metadata": "Scan configuration metadata, including the engine configurations requested.",
            "createdAt": "Timestamp when the scan was created.",
            "updatedAt": "Timestamp when the scan was last updated.",
        },
    },
    "scan_results": {
        "description": "An individual finding (vulnerability, misconfiguration, or risk) reported by a scan, across all engines.",
        "docs_url": "https://checkmarx.com/resource/documents/en/34965-90822-results-api.html",
        "columns": {
            "result_id": "Finding identifier scoped to its scan, derived from the engine type plus the result's id (falling back to its similarity id). Added by PostHog.",
            "scan_id": "Identifier of the scan that produced this finding. Added by PostHog.",
            "scan_created_at": "Creation timestamp of the scan that produced this finding. Added by PostHog.",
            "type": "Engine that reported the finding (e.g. sast, sca, kics).",
            "id": "Engine-assigned identifier of the finding within the scan.",
            "similarityId": "Stable identifier used to correlate the same finding across scans.",
            "status": "Comparison status of the finding relative to the previous scan (e.g. NEW, RECURRENT, FIXED).",
            "state": "Triage state of the finding (e.g. TO_VERIFY, CONFIRMED, NOT_EXPLOITABLE).",
            "severity": "Severity of the finding (e.g. CRITICAL, HIGH, MEDIUM, LOW, INFO).",
            "confidenceLevel": "Confidence level assigned to the finding.",
            "created": "Timestamp when the finding was created.",
            "firstFoundAt": "Timestamp when this finding was first detected in the project.",
            "foundAt": "Timestamp when this finding was detected in this scan.",
            "firstScanId": "Identifier of the scan in which this finding was first detected.",
            "description": "Human-readable description of the finding.",
            "data": "Engine-specific finding details (e.g. file, line, and attack vector for SAST).",
            "vulnerabilityDetails": "Vulnerability metadata such as CWE id, CVSS scores, and compliance mappings.",
            "comments": "Comments attached to the finding.",
        },
    },
    "scan_results_summary": {
        "description": "Aggregated result counters for a scan, broken down by severity, state, and status per engine.",
        "docs_url": "https://checkmarx.com/resource/documents/en/34965-90823-scan-summary-api.html",
        "columns": {
            "scan_id": "Identifier of the scan the summary belongs to. Added by PostHog.",
            "scan_created_at": "Creation timestamp of the scan the summary belongs to. Added by PostHog.",
            "scanId": "Identifier of the scan the summary belongs to, as reported by Checkmarx One.",
            "tenantId": "Identifier of the Checkmarx One tenant.",
            "sastCounters": "Aggregated SAST finding counters grouped by severity, state, status, and language.",
            "scaCounters": "Aggregated SCA finding counters grouped by severity, state, and status.",
            "kicsCounters": "Aggregated IaC (KICS) finding counters grouped by severity, state, status, and platform.",
            "scaContainersCounters": "Aggregated SCA container image finding counters.",
            "apiSecCounters": "Aggregated API security finding counters.",
            "microEnginesCounters": "Aggregated micro-engine (e.g. secrets) finding counters.",
        },
    },
    "application_rules": {
        "description": "A rule on a Checkmarx One application that assigns projects to it, by project name or project tag.",
        "docs_url": f"{_API_REFERENCE}/b893e178b7eee-retrieve-list-of-application-rules",
        "columns": {
            "id": "Unique identifier (UUID) of the rule.",
            "application_id": "Identifier of the application the rule belongs to. Added by PostHog.",
            "application_created_at": "Creation timestamp of the application the rule belongs to. Added by PostHog.",
            "type": "What the rule matches on (e.g. project.name.contains, project.tag.key-value.exists).",
            "value": "Value the rule matches against, interpreted according to the rule type. Key/value pairs and id lists are separated by a semicolon.",
        },
    },
    "sast_predicates_changelog": {
        "description": "A change made while triaging a project's findings: the state, severity, and comment edits applied to results, with who made each one.",
        "docs_url": f"{_API_REFERENCE}/gmnw4cuhobl2z-retrieve-bulk-predicates",
        "columns": {
            "change_id": "Identifier of the change, derived from the change's own fields because Checkmarx One does not return one. Added by PostHog.",
            "project_id": "Identifier of the project whose findings were triaged. Added by PostHog.",
            "project_created_at": "Creation timestamp of the project whose findings were triaged. Added by PostHog.",
            "change": "Description of the change that was made.",
            "date": "Timestamp when the change was made.",
            "user": "User who made the change.",
            "origin": "Where the change was made from (e.g. the web UI or an integration).",
        },
    },
    "result_states": {
        "description": "The built-in triage states a finding can be assigned, which decode the state column on scan_results.",
        "docs_url": f"{_API_REFERENCE}/h9ryi6k6wcz24-lists-enum-values-rest-api",
        "columns": {
            "value": "The state (e.g. TO_VERIFY, NOT_EXPLOITABLE, PROPOSED_NOT_EXPLOITABLE, CONFIRMED, URGENT).",
        },
    },
    "result_statuses": {
        "description": "The statuses a finding can carry relative to the previous scan, which decode the status column on scan_results.",
        "docs_url": f"{_API_REFERENCE}/h9ryi6k6wcz24-lists-enum-values-rest-api",
        "columns": {
            "value": "The status (e.g. NEW, RECURRENT, FIXED).",
        },
    },
    "result_severities": {
        "description": "The severities a finding can carry, which decode the severity column on scan_results.",
        "docs_url": f"{_API_REFERENCE}/h9ryi6k6wcz24-lists-enum-values-rest-api",
        "columns": {
            "value": "The severity (e.g. CRITICAL, HIGH, MEDIUM, LOW, INFO).",
        },
    },
    "custom_states": {
        "description": "A triage state defined by your tenant, in addition to the built-in states in result_states. Includes states that have since been deleted, so findings left in one still resolve to a name.",
        "docs_url": "https://checkmarx.com/resource/documents/en/34965-378909-custom-states.html",
        "columns": {
            "id": "Unique identifier of the custom state.",
            "name": "Display name of the custom state.",
            "type": "Whether the state is a built-in or a custom one.",
            "isAllowed": "Whether the API key's user has permission to move findings into this state.",
        },
    },
}
