from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Descriptions sourced from Housecall Pro's public API docs (https://docs.housecallpro.com/docs/housecall-public-api).
# Keyed by the endpoint name from ENDPOINTS / get_schemas. Partial coverage is fine — anything not
# listed here falls back to LLM enrichment using the docs_url and column data types.
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "customers": {
        "description": "Customer records in the Housecall Pro account, including contact details and service addresses.",
        "docs_url": "https://docs.housecallpro.com/docs/housecall-public-api/042bd3bf861ae-get-customers",
        "columns": {
            "id": "Unique identifier for the customer.",
            "first_name": "Customer's first name.",
            "last_name": "Customer's last name.",
            "email": "Customer's email address.",
            "company": "Company name, for commercial customers.",
            "mobile_number": "Customer's mobile phone number.",
            "home_number": "Customer's home phone number.",
            "work_number": "Customer's work phone number.",
            "notifications_enabled": "Whether the customer receives automated notifications.",
            "tags": "Tags applied to the customer for segmentation.",
            "lead_source": "Marketing source attributed to the customer.",
            "notes": "Free-text notes on the customer.",
            "addresses": "Service addresses associated with the customer.",
            "created_at": "When the customer was created.",
            "updated_at": "When the customer was last updated.",
        },
    },
    "jobs": {
        "description": "Scheduled and completed jobs (appointments) performed for customers.",
        "docs_url": "https://docs.housecallpro.com/docs/housecall-public-api/6c97704da8bf3-get-jobs",
        "columns": {
            "id": "Unique identifier for the job.",
            "customer_id": "Identifier of the customer the job is for.",
            "address_id": "Identifier of the service address for the job.",
            "notes": "Free-text notes on the job.",
            "lead_source": "Marketing source attributed to the job.",
            "invoice_number": "Invoice number associated with the job.",
            "work_status": "Current status of the job (e.g. scheduled, completed, canceled).",
            "schedule": "Scheduling window for the job, including start and end time.",
            "assigned_employee_ids": "Employees assigned to perform the job.",
            "line_items": "Products and services billed on the job.",
            "tags": "Tags applied to the job.",
            "created_at": "When the job was created.",
            "updated_at": "When the job was last updated.",
        },
    },
    "estimates": {
        "description": "Estimates (quotes) sent to customers before a job is booked.",
        "docs_url": "https://docs.housecallpro.com/docs/housecall-public-api/e430ba3d520a0",
        "columns": {
            "id": "Unique identifier for the estimate.",
            "customer_id": "Identifier of the customer the estimate is for.",
            "address_id": "Identifier of the service address for the estimate.",
            "work_status": "Current status of the estimate (e.g. scheduled, completed, canceled).",
            "options": "Pricing options presented to the customer, each with its own line items.",
            "schedule": "Scheduling window for the estimate visit.",
            "assigned_employee_ids": "Employees assigned to the estimate.",
            "lead_source": "Marketing source attributed to the estimate.",
            "estimate_number": "Estimate number, unique across the company.",
            "created_at": "When the estimate was created.",
            "updated_at": "When the estimate was last updated.",
        },
    },
    "invoices": {
        "description": "Invoices issued to customers for completed work, including payment status.",
        "docs_url": "https://docs.housecallpro.com/docs/housecall-public-api/65ce9f430d605",
        "columns": {
            "id": "Unique identifier for the invoice.",
            "customer_id": "Identifier of the customer the invoice was issued to.",
            "status": "Current status of the invoice (e.g. open, paid, voided).",
            "amount_due": "Amount still owed on the invoice.",
            "payment_method": "Method used to pay the invoice, once paid.",
            "due_at": "When the invoice is due.",
            "paid_at": "When the invoice was paid, if applicable.",
            "created_at": "When the invoice was created. Stable, used for incremental sync.",
        },
    },
    "employees": {
        "description": "Employee (team member) accounts in the Housecall Pro account.",
        "docs_url": "https://docs.housecallpro.com/docs/housecall-public-api/303ee235f23fa-get-employees",
        "columns": {
            "id": "Unique identifier for the employee.",
            "first_name": "Employee's first name.",
            "last_name": "Employee's last name.",
            "email": "Employee's email address.",
            "mobile_number": "Employee's mobile phone number.",
            "role": "Role assigned to the employee in the account.",
            "tags": "Tags applied to the employee.",
        },
    },
    "leads": {
        "description": "Inbound leads not yet converted into a job or estimate.",
        "docs_url": "https://docs.housecallpro.com/docs/housecall-public-api/278974bc87e32-get-leads",
        "columns": {
            "id": "Unique identifier for the lead.",
            "customer_id": "Identifier of the customer the lead is associated with.",
            "address_id": "Identifier of the service address for the lead.",
            "assigned_employee_id": "Employee assigned to follow up on the lead.",
            "status": "Current status of the lead (e.g. open, won, lost).",
            "lead_source": "Marketing source attributed to the lead.",
            "note": "Free-text note on the lead.",
            "tags": "Tags applied to the lead.",
            "line_items": "Products and services proposed on the lead.",
            "created_at": "When the lead was created.",
            "updated_at": "When the lead was last updated.",
        },
    },
}
