CREATE TABLE IF NOT EXISTS writable_session_replay_features 
(
    session_id VARCHAR,
    team_id Int64,
    distinct_id VARCHAR,
    min_first_timestamp SimpleAggregateFunction(min, DateTime64(6, 'UTC')),
    max_last_timestamp SimpleAggregateFunction(max, DateTime64(6, 'UTC')),
    event_count SimpleAggregateFunction(sum, Int64),
    mouse_position_count SimpleAggregateFunction(sum, Int64),
    mouse_sum_x SimpleAggregateFunction(sum, Float64),
    mouse_sum_x_squared SimpleAggregateFunction(sum, Float64),
    mouse_sum_y SimpleAggregateFunction(sum, Float64),
    mouse_sum_y_squared SimpleAggregateFunction(sum, Float64),
    mouse_distance_traveled SimpleAggregateFunction(sum, Float64),
    mouse_direction_change_count SimpleAggregateFunction(sum, Int64),
    mouse_velocity_sum SimpleAggregateFunction(sum, Float64),
    mouse_velocity_sum_of_squares SimpleAggregateFunction(sum, Float64),
    mouse_velocity_count SimpleAggregateFunction(sum, Int64),
    scroll_event_count SimpleAggregateFunction(sum, Int64),
    total_scroll_magnitude SimpleAggregateFunction(sum, Float64),
    scroll_direction_reversal_count SimpleAggregateFunction(sum, Int64),
    rapid_scroll_reversal_count SimpleAggregateFunction(sum, Int64),
    click_count SimpleAggregateFunction(sum, Int64),
    keypress_count SimpleAggregateFunction(sum, Int64),
    mouse_activity_count SimpleAggregateFunction(sum, Int64),
    rage_click_count SimpleAggregateFunction(sum, Int64),
    dead_click_count SimpleAggregateFunction(sum, Int64),
    inter_action_gap_count SimpleAggregateFunction(sum, Int64),
    inter_action_gap_sum_ms SimpleAggregateFunction(sum, Float64),
    inter_action_gap_sum_of_squares_ms SimpleAggregateFunction(sum, Float64),
    max_idle_gap_ms SimpleAggregateFunction(max, Float64),
    quick_back_count SimpleAggregateFunction(sum, Int64),
    page_visit_count SimpleAggregateFunction(sum, Int64),
    unique_url_count AggregateFunction(uniqExact, String),
    console_error_count SimpleAggregateFunction(sum, Int64),
    console_error_after_click_count SimpleAggregateFunction(sum, Int64),
    network_request_count SimpleAggregateFunction(sum, Int64),
    network_failed_request_count SimpleAggregateFunction(sum, Int64),
    network_request_duration_sum SimpleAggregateFunction(sum, Float64),
    network_request_duration_sum_of_squares SimpleAggregateFunction(sum, Float64),
    network_request_duration_count SimpleAggregateFunction(sum, Int64),
    max_scroll_y SimpleAggregateFunction(max, Float64),
    unique_click_target_count AggregateFunction(uniqExact, Int64),
    text_selection_count SimpleAggregateFunction(sum, Int64),
    is_deleted SimpleAggregateFunction(max, UInt8) DEFAULT 0
) ENGINE = Distributed('posthog', 'default', 'sharded_session_replay_features', sipHash64(session_id))

CREATE TABLE IF NOT EXISTS kafka_session_replay_features 
(
    session_id VARCHAR,
    team_id Int64,
    distinct_id VARCHAR,
    batch_id VARCHAR,
    first_timestamp DateTime64(6, 'UTC'),
    last_timestamp DateTime64(6, 'UTC'),
    event_count Int64,
    mouse_position_count Int64,
    mouse_sum_x Float64,
    mouse_sum_x_squared Float64,
    mouse_sum_y Float64,
    mouse_sum_y_squared Float64,
    mouse_distance_traveled Float64,
    mouse_direction_change_count Int64,
    mouse_velocity_sum Float64,
    mouse_velocity_sum_of_squares Float64,
    mouse_velocity_count Int64,
    scroll_event_count Int64,
    total_scroll_magnitude Float64,
    scroll_direction_reversal_count Int64,
    rapid_scroll_reversal_count Int64,
    click_count Int64,
    keypress_count Int64,
    mouse_activity_count Int64,
    rage_click_count Int64,
    dead_click_count Int64,
    inter_action_gap_count Int64,
    inter_action_gap_sum_ms Float64,
    inter_action_gap_sum_of_squares_ms Float64,
    max_idle_gap_ms Float64,
    quick_back_count Int64,
    page_visit_count Int64,
    visited_urls Array(String),
    console_error_count Int64,
    console_error_after_click_count Int64,
    network_request_count Int64,
    network_failed_request_count Int64,
    network_request_duration_sum Float64,
    network_request_duration_sum_of_squares Float64,
    network_request_duration_count Int64,
    max_scroll_y Float64,
    click_target_ids Array(Int64),
    text_selection_count Int64,
    is_deleted UInt8
) ENGINE = Kafka(msk_cluster, kafka_topic_list = 'clickhouse_session_replay_features', kafka_group_name = 'clickhouse_session_replay_features', kafka_format = 'JSONEachRow')

CREATE MATERIALIZED VIEW IF NOT EXISTS session_replay_features_mv 
TO default.writable_session_replay_features
AS SELECT
session_id,
team_id,
any(distinct_id) as distinct_id,
min(first_timestamp) AS min_first_timestamp,
max(last_timestamp) AS max_last_timestamp,
sum(event_count) as event_count,
sum(mouse_position_count) as mouse_position_count,
sum(mouse_sum_x) as mouse_sum_x,
sum(mouse_sum_x_squared) as mouse_sum_x_squared,
sum(mouse_sum_y) as mouse_sum_y,
sum(mouse_sum_y_squared) as mouse_sum_y_squared,
sum(mouse_distance_traveled) as mouse_distance_traveled,
sum(mouse_direction_change_count) as mouse_direction_change_count,
sum(mouse_velocity_sum) as mouse_velocity_sum,
sum(mouse_velocity_sum_of_squares) as mouse_velocity_sum_of_squares,
sum(mouse_velocity_count) as mouse_velocity_count,
sum(scroll_event_count) as scroll_event_count,
sum(total_scroll_magnitude) as total_scroll_magnitude,
sum(scroll_direction_reversal_count) as scroll_direction_reversal_count,
sum(rapid_scroll_reversal_count) as rapid_scroll_reversal_count,
sum(click_count) as click_count,
sum(keypress_count) as keypress_count,
sum(mouse_activity_count) as mouse_activity_count,
sum(rage_click_count) as rage_click_count,
sum(dead_click_count) as dead_click_count,
sum(inter_action_gap_count) as inter_action_gap_count,
sum(inter_action_gap_sum_ms) as inter_action_gap_sum_ms,
sum(inter_action_gap_sum_of_squares_ms) as inter_action_gap_sum_of_squares_ms,
max(max_idle_gap_ms) as max_idle_gap_ms,
sum(quick_back_count) as quick_back_count,
sum(page_visit_count) as page_visit_count,
uniqExactArrayState(visited_urls) as unique_url_count,
sum(console_error_count) as console_error_count,
sum(console_error_after_click_count) as console_error_after_click_count,
sum(network_request_count) as network_request_count,
sum(network_failed_request_count) as network_failed_request_count,
sum(network_request_duration_sum) as network_request_duration_sum,
sum(network_request_duration_sum_of_squares) as network_request_duration_sum_of_squares,
sum(network_request_duration_count) as network_request_duration_count,
max(max_scroll_y) as max_scroll_y,
uniqExactArrayState(click_target_ids) as unique_click_target_count,
sum(text_selection_count) as text_selection_count,
max(is_deleted) as is_deleted
FROM default.kafka_session_replay_features
GROUP BY session_id, team_id
