import { MakeLogicType, kea, path } from 'kea'
import { lazyLoaders } from 'kea-loaders'

import { ApiConfig } from '~/lib/api'

import { llmSkillsTagsRetrieve } from 'products/skills/frontend/generated/api'

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface skillTagsModelValues {
    availableTags: string[]
    availableTagsLoading: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface skillTagsModelActions {
    loadAvailableTags: () => any
    loadAvailableTagsFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadAvailableTagsSuccess: (
        availableTags: string[],
        payload?: any
    ) => {
        availableTags: string[]
        payload?: any
    }
}

export type skillTagsModelType = MakeLogicType<skillTagsModelValues, skillTagsModelActions>

/** The team's skill tag vocabulary, shared by the tag filter on the list and the editor on a skill.
 *
 * Its own model rather than a value on either logic: both surfaces need every tag the team uses, not
 * the tags of the skills currently on screen, and each has to see a tag the other just created.
 */
export const skillTagsModel = kea<skillTagsModelType>([
    path(['products', 'skills', 'skillTagsModel']),
    lazyLoaders(() => ({
        availableTags: {
            __default: [] as string[],
            loadAvailableTags: async () => {
                const response = await llmSkillsTagsRetrieve(String(ApiConfig.getCurrentTeamId()))
                return response.tags
            },
        },
    })),
])
