"""Canonical, documentation-sourced descriptions for AfterShip Tracking API tables and columns.

Sourced from the AfterShip Tracking API 2026-07 OpenAPI schema and reference
(https://www.aftership.com/docs/tracking). Keyed by the table names in `settings.py`
`ENDPOINTS`, which match the `ExternalDataSchema.name` of a synced AfterShip table. Columns
absent here fall back to LLM enrichment.
"""

from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "trackings": {
        "description": "A shipment AfterShip is tracking, including its current delivery status, origin and destination, estimated delivery dates, and the full checkpoint history reported by the carrier.",
        "docs_url": "https://www.aftership.com/docs/tracking/model/tracking",
        "columns": {
            "id": "System-generated tracking ID, which can be customized by the user when creating the tracking.",
            "legacy_id": "The original 24-character tracking ID, kept for compatibility since IDs grew to 32 characters.",
            "created_at": "Date and time the shipment was imported or added to AfterShip, in UTC.",
            "updated_at": "Date and time the shipment was last updated, in UTC.",
            "tracking_number": "Carrier tracking number of the shipment.",
            "slug": "Unique courier code. Set to 'unrecognized' when the tracking number matches no known carrier.",
            "active": "Whether AfterShip is still tracking the shipment. False once there have been no updates for a few days.",
            "custom_fields": "Custom key/value fields set on the tracking when it was created.",
            "transit_time": "Total transit time in days: delivered date minus pickup date, or current date minus pickup date while undelivered. Null when there is no pickup date.",
            "origin_country_region": "ISO Alpha-3 code of the origin country or region.",
            "origin_state": "State of the sender's address.",
            "origin_city": "City of the sender's address.",
            "origin_postal_code": "Postal code of the sender's address.",
            "origin_raw_location": "Sender address the shipment ships from.",
            "destination_country_region": "ISO Alpha-3 code of the destination country or region.",
            "destination_state": "State of the recipient's address.",
            "destination_city": "City of the recipient's address.",
            "destination_postal_code": "Postal code of the recipient's address.",
            "destination_raw_location": "Shipping address the shipment ships to.",
            "courier_destination_country_region": "Destination country or region as reported by the carrier, ISO Alpha-3. Null when the carrier does not provide it.",
            "courier_estimated_delivery_date": "Estimated delivery date provided by the carrier, with its min and max bounds.",
            "note": "Free text note on the tracking.",
            "order_id": "Globally unique identifier for the order.",
            "order_id_path": "URL of the order in your own system or store.",
            "order_date": "Date and time the order was created in your system or store.",
            "shipment_package_count": "Number of packages under the tracking.",
            "shipment_pickup_date": "Date and time the carrier picked the shipment up, in the pickup location's timezone.",
            "shipment_delivery_date": "Date and time the shipment was delivered, in the recipient's timezone.",
            "shipment_type": "Carrier service type used for the shipment.",
            "shipment_weight": "Total weight of the shipment, as a value and unit.",
            "shipment_dimensions": "Physical dimensions of the package: length, width and height.",
            "signed_by": "Name recorded as signing for a delivered shipment.",
            "source": "How the tracking was added to AfterShip.",
            "tag": "Current delivery status, one of Pending, InfoReceived, InTransit, OutForDelivery, AttemptFail, Delivered, AvailableForPickup, Exception or Expired.",
            "subtag": "Current delivery sub-status, a more specific breakdown of the tag.",
            "subtag_message": "Human-readable message for the current sub-status.",
            "title": "Display title for the tracking. Defaults to the tracking number and can be customized.",
            "tracked_count": "Number of times AfterShip has polled the carrier for this shipment.",
            "language": "Recipient's language, used to pick the language of tracking notifications.",
            "checkpoints": "Array of carrier checkpoint events, each with its time, location, status and message.",
            "subscribed_smses": "Phone numbers subscribed to SMS notifications for this shipment.",
            "subscribed_emails": "Email addresses subscribed to email notifications for this shipment.",
            "return_to_sender": "Whether the shipment is being returned to the sender, based on its checkpoint sub-tags.",
            "order_promised_delivery_date": "Delivery date promised to the customer for the order, in the recipient's timezone.",
            "delivery_type": "How the shipment is delivered: pickup_at_store, pickup_at_courier or door_to_door.",
            "pickup_location": "Pickup location for the recipient.",
            "pickup_note": "Pickup note for the recipient.",
            "courier_tracking_link": "Official carrier tracking URL for the shipment, when the carrier has one.",
            "first_attempted_at": "Date and time of the carrier's first delivery attempt, in the recipient's timezone.",
            "courier_redirect_link": "Carrier URL where the recipient can change the delivery date or address, when supported.",
            "tracking_account_number": "Shipper's carrier account number, required by some carriers to retrieve tracking info.",
            "tracking_key": "Extra tracking credential required by some carriers to retrieve tracking info.",
            "tracking_ship_date": "Date the merchant shipped the package and it became ready for carrier pickup.",
            "on_time_status": "Whether the shipment was delivered on time.",
            "on_time_difference": "Number of days the delivery ran early or late.",
            "order_tags": "Tags applied to the order.",
            "aftership_estimated_delivery_date": "Estimated delivery date predicted by AfterShip's model and shown to recipients, with its confidence code and bounds.",
            "custom_estimated_delivery_date": "Estimated delivery time derived from your own custom estimated-delivery-date settings.",
            "order_number": "Human-readable identifier for the order.",
            "first_estimated_delivery": "The shipment's original estimated delivery date, and which source produced it.",
            "latest_estimated_delivery": "The most recently calculated estimated delivery date, its source, and why it was revised.",
            "shipment_tags": "Tags applied to the shipment for categorizing and filtering.",
            "courier_connection_id": "Identifier of the carrier account connection used to fetch updates for this shipment.",
            "carbon_emissions": "Total carbon emissions generated by the shipment, as a value and unit, when AfterShip can calculate it.",
            "location_id": "Identifier of the location the items were fulfilled from, used as the origin address when set.",
            "shipping_method": "Shipping method the customer chose at checkout.",
            "failed_delivery_attempts": "Number of failed delivery attempts recorded during the shipment.",
            "signature_requirement": "Proof-of-delivery signature option required for the shipment.",
            "delivery_location_type": "Secure place the carrier left the package, such as a locker, mailbox or front porch.",
            "aftership_tracking_url": "URL of the AfterShip shipment tracking page for this shipment.",
            "aftership_tracking_order_url": "URL of the AfterShip order tracking page covering every shipment in the order.",
            "first_mile": "Details of the first leg of the shipment, up to the handover to the last-mile carrier.",
            "last_mile": "Details of the last leg of the shipment, from the last-mile carrier through to delivery.",
            "customers": "Customer records associated with the tracking, up to three.",
            "proof_of_delivery": "Proof-of-delivery records captured on delivery, such as a signature or photo.",
            "multi_piece_info": "Details of the other packages when one shipment order is fulfilled by several physical packages.",
            "shipment_direction": "Business direction of the shipment: 'forward' for an outbound order shipment, 'return' for a customer return.",
            "return_shipment": "The return shipment linked to this outbound shipment, when AfterShip has detected one.",
            "forward_shipment": "The original outbound shipment this return traces back to, when AfterShip has detected one.",
        },
    },
    "couriers": {
        "description": "A carrier activated on your AfterShip account, with the extra fields it needs to track a shipment and the countries it serves.",
        "docs_url": "https://www.aftership.com/docs/tracking/model/courier",
        "columns": {
            "slug": "Unique courier code used to identify the carrier across the AfterShip API.",
            "name": "Name of the courier.",
            "phone": "Contact phone number of the courier.",
            "other_name": "Alternative name of the courier.",
            "web_url": "Website of the courier.",
            "required_fields": "Extra fields required to track a shipment with this courier, such as tracking_account_number or tracking_postal_code.",
            "optional_fields": "Extra fields that some of this courier's tracking numbers need.",
            "default_language": "Default language of tracking results from this courier.",
            "support_languages": "Other languages this courier supports for tracking results.",
            "service_from_country_regions": "ISO Alpha-3 codes of the countries or regions where the courier provides service.",
            "credentials": "Shape of the authentication details this courier needs to create a carrier connection.",
        },
    },
    "courier_connections": {
        "description": "A carrier account you connected to AfterShip so it can pull tracking updates directly from that carrier. The stored carrier credentials are dropped during sync and never land in the warehouse.",
        "docs_url": "https://www.aftership.com/docs/tracking/model/courier-connection",
        "columns": {
            "id": "Identifier AfterShip generated for the carrier connection.",
            "courier_slug": "Unique courier code of the connected carrier.",
            "created_at": "Date and time the connection was created, in UTC.",
            "updated_at": "Date and time the connection was last updated, in UTC.",
        },
    },
}
