from posthog.temporal.sync_events_retention.activities import sync_events_retention
from posthog.temporal.sync_events_retention.workflow import SyncEventsRetentionWorkflow

SYNC_EVENTS_RETENTION_WORKFLOWS = [SyncEventsRetentionWorkflow]
SYNC_EVENTS_RETENTION_ACTIVITIES = [sync_events_retention]
