KAFKA_EVENTS = "clickhouse_events_proto"
KAFKA_PERSON = "clickhouse_person"
KAFKA_PERSON_UNIQUE_ID = "clickhouse_person_unique_id"
KAFKA_SESSION_RECORDING_EVENTS = "clickhouse_session_recording_events"
KAFKA_EVENTS_PLUGIN_INGESTION = "events_plugin_ingestion"
KAFKA_PLUGIN_LOG_ENTRIES = "plugin_log_entries"
KAFKA_DEAD_LETTER_QUEUE = "events_dead_letter_queue"
