KAFKA_EVENTS = "clickhouse_events_proto"
KAFKA_PERSON = "clickhouse_person"
KAFKA_PERSON_UNIQUE_ID = "clickhouse_person_unique_id"
KAFKA_SESSION_RECORDING_EVENTS = "clickhouse_session_recording_events"
KAFKA_EVENTS_WAL = "events_write_ahead_log"
KAFKA_EVENTS_INGESTION_HANDOFF = "events_ingestion_handoff"
