from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "page": {
        "description": "The Facebook Page itself — profile details and current follower counts, refreshed on every sync.",
        "docs_url": "https://developers.facebook.com/docs/graph-api/reference/page/",
        "columns": {
            "id": "The Page's numeric ID.",
            "name": "The name of the Page.",
            "username": "The Page's vanity URL name, if it has one.",
            "about": "The short description shown in the Page's header.",
            "category": "The Page's primary category, e.g. Local business.",
            "link": "The public URL of the Page.",
            "website": "The website URL listed on the Page.",
            "description": "The long-form description of the Page.",
            "fan_count": "Number of people who have liked the Page.",
            "followers_count": "Number of people following the Page.",
            "talking_about_count": "Number of people talking about the Page in the last week.",
            "is_published": "Whether the Page is published and visible to the public.",
            "location": "The Page's street address, city, and coordinates, when it has one.",
        },
    },
    "posts": {
        "description": "Posts published by the Page, including the story text, permalink, and share counts.",
        "docs_url": "https://developers.facebook.com/docs/graph-api/reference/page/posts/",
        "columns": {
            "id": "The post ID, formatted as {page-id}_{post-id}.",
            "page_id": "ID of the Page the post belongs to.",
            "created_time": "When the post was published.",
            "updated_time": "When the post was last edited, or last had a comment or like.",
            "message": "The text body of the post.",
            "story": "The auto-generated story text for posts without a message, e.g. a Page changing its picture.",
            "permalink_url": "Permanent public URL of the post.",
            "status_type": "The kind of action the post represents, e.g. added_photos or shared_story.",
            "is_published": "Whether the post is visible to the public.",
            "is_hidden": "Whether the post is hidden from the Page's timeline.",
            "full_picture": "URL of the full-size image attached to the post.",
            "icon": "URL of the icon Facebook shows alongside the post.",
            "shares": "Share count for the post, as a nested count object.",
        },
    },
    "videos": {
        "description": "Videos uploaded to the Page.",
        "docs_url": "https://developers.facebook.com/docs/graph-api/reference/page/videos/",
        "columns": {
            "id": "The video ID.",
            "page_id": "ID of the Page that owns the video.",
            "created_time": "When the video was uploaded.",
            "updated_time": "When the video was last modified.",
            "title": "The title of the video.",
            "description": "The description accompanying the video.",
            "permalink_url": "Permanent public URL of the video.",
            "length": "Duration of the video in seconds.",
            "published": "Whether the video is published and visible to the public.",
            "universal_video_id": "The ID shared by every copy of this video across Pages that crossposted it.",
        },
    },
    "page_insights": {
        "description": "Daily Page metrics from the Insights API, one row per metric and day.",
        "docs_url": "https://developers.facebook.com/docs/graph-api/reference/page/insights/",
        "columns": {
            "page_id": "ID of the Page the metric belongs to.",
            "name": "The metric name, e.g. page_impressions.",
            "period": "The aggregation period the value covers — always day for this table.",
            "title": "Human-readable title Facebook gives the metric.",
            "description": "Facebook's own explanation of what the metric counts.",
            "end_time": "End of the period the value covers, in UTC.",
            "value": "The metric value, when it is a single number.",
            "value_json": "The metric value serialized as JSON, for metrics broken down by dimension.",
        },
    },
}
