from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Descriptions are taken from Canny's official API reference (https://developers.canny.io/api-reference).
# Keys match the endpoint names returned by `get_schemas` / declared in settings.py.
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "boards": {
        "description": "A board is a collection of posts (feature requests, bugs, ideas) shown to your users.",
        "docs_url": "https://developers.canny.io/api-reference#boards",
        "columns": {
            "id": "A unique identifier for the board.",
            "created": "Time at which the board was created, in ISO 8601 format.",
            "name": "The board's name.",
            "postCount": "The number of non-deleted posts associated with the board.",
            "url": "The URL to the board's page.",
            "isPrivate": "Whether the board is set to private in the admin settings.",
            "privateComments": "Whether comments on this board are private to admins.",
            "token": "The board's unique token, used by the widget.",
        },
    },
    "categories": {
        "description": "A category groups posts within a board.",
        "docs_url": "https://developers.canny.io/api-reference#categories",
        "columns": {
            "id": "A unique identifier for the category.",
            "board": "The board this category belongs to.",
            "created": "Time at which the category was created, in ISO 8601 format.",
            "name": "The name of the category.",
            "parentID": "The id of the parent category, if this is a subcategory.",
            "postCount": "The number of posts in this category.",
            "url": "The URL to the category's page.",
        },
    },
    "changelog_entries": {
        "description": "A changelog entry announcing product updates to your users.",
        "docs_url": "https://developers.canny.io/api-reference#changelog",
        "columns": {
            "id": "A unique identifier for the entry.",
            "created": "Time at which the entry was created, in ISO 8601 format.",
            "lastSaved": "Time at which the entry was last edited, in ISO 8601 format.",
            "publishedAt": "Time at which the entry was published, in ISO 8601 format.",
            "scheduledFor": "Time the entry is scheduled to publish, in ISO 8601 format.",
            "labels": "The labels applied to the entry.",
            "markdownDetails": "The entry's body content, in Markdown.",
            "plaintextDetails": "The entry's body content, as plain text.",
            "posts": "The posts linked to this changelog entry.",
            "status": "The publication status of the entry (e.g. draft, published).",
            "title": "The title of the entry.",
            "types": "The types/tags of the entry (e.g. new, improved, fixed).",
            "url": "The URL to the entry's page.",
        },
    },
    "comments": {
        "description": "A comment left by a user or admin on a post.",
        "docs_url": "https://developers.canny.io/api-reference#comments",
        "columns": {
            "id": "A unique identifier for the comment.",
            "author": "The user who authored the comment.",
            "board": "The board the comment's post belongs to.",
            "created": "Time at which the comment was created, in ISO 8601 format.",
            "imageURLs": "Image URLs attached to the comment.",
            "internal": "Whether the comment is an internal (admin-only) comment.",
            "likeCount": "The number of likes the comment has received.",
            "mentions": "Users mentioned in the comment.",
            "parentID": "The id of the parent comment, if this is a reply.",
            "post": "The post the comment was left on.",
            "private": "Whether the comment is private.",
            "value": "The text content of the comment.",
        },
    },
    "companies": {
        "description": "A company that your users belong to, used to segment feedback.",
        "docs_url": "https://developers.canny.io/api-reference#companies",
        "columns": {
            "id": "A unique identifier for the company.",
            "created": "Time at which the company was created, in ISO 8601 format.",
            "customFields": "Custom fields associated with the company.",
            "domain": "The company's domain.",
            "memberCount": "The number of users associated with the company.",
            "monthlySpend": "The company's monthly spend.",
            "name": "The company's name.",
        },
    },
    "groups": {
        "description": "A group is a higher-level initiative or product area that houses ideas, and can nest under a parent group.",
        "docs_url": "https://developers.canny.io/api-reference#groups",
        "columns": {
            "id": "A unique identifier for the group.",
            "name": "The name of the group.",
            "description": "A short description of what this group represents.",
            "parentID": "The ID of the parent group, if any.",
            "urlName": "A URL-friendly identifier for the group.",
        },
    },
    "ideas": {
        "description": "An idea is a feature or improvement tracked in Canny Ideas, optionally grouped and nested under a parent idea.",
        "docs_url": "https://developers.canny.io/api-reference#ideas",
        "columns": {
            "id": "A unique identifier for the idea.",
            "childCount": "The number of child ideas (ideas that have this idea as their parent).",
            "author": "The user who authored the idea, if any.",
            "created": "Time at which the idea was created, in ISO 8601 format.",
            "description": "The description of the idea.",
            "group": "The group this idea belongs to, if any.",
            "owner": "The user who is assigned as owner of this idea, if any.",
            "parent": "The parent idea, if this idea is a child of another idea.",
            "source": "The source where the idea was created from.",
            "status": "The status of the idea.",
            "title": "The title of the idea.",
            "updatedAt": "Time at which the idea was last updated, in ISO 8601 format.",
            "urlName": "The URL name of the idea.",
        },
    },
    "insights": {
        "description": "An insight is a piece of customer feedback or context attached to an idea, captured manually or from comments, votes and other sources.",
        "docs_url": "https://developers.canny.io/api-reference#insights",
        "columns": {
            "id": "A unique identifier for the insight.",
            "author": "The user who created the insight, if available.",
            "company": "The company associated with the insight, if available.",
            "created": "Time at which the insight was created, in ISO 8601 format.",
            "ideaID": "The ID of the idea associated with the insight.",
            "priority": "The priority level of the insight, if set. One of nice-to-have, important, must-have or no-priority.",
            "source": "The source of the insight (e.g. canny, webhook).",
            "url": "A URL associated with the insight, if available.",
            "users": "The users mentioned or associated with the insight.",
            "value": "The text content of the insight.",
        },
    },
    "opportunities": {
        "description": "An opportunity is a revenue deal, synced from your CRM, linked to the posts and ideas it depends on.",
        "docs_url": "https://developers.canny.io/api-reference#opportunities",
        "columns": {
            "id": "A unique identifier for the opportunity.",
            "closed": "Whether the opportunity is closed.",
            "ideaIDs": "The list of idea ids this opportunity is linked to.",
            "name": "The name of the opportunity.",
            "postIDs": "The list of post ids this opportunity is linked to.",
            "salesforceOpportunityID": "The unique identifier for the opportunity in Salesforce.",
            "stage": "The current pipeline stage of the opportunity, as labeled in the source CRM (e.g. Discovery, Closed Won).",
            "value": "The value of the opportunity.",
            "won": "Whether the opportunity has been won.",
        },
    },
    "posts": {
        "description": "A post is a piece of feedback (feature request, bug, idea) on a board.",
        "docs_url": "https://developers.canny.io/api-reference#posts",
        "columns": {
            "id": "A unique identifier for the post.",
            "author": "The user who authored the post.",
            "board": "The board the post is on.",
            "by": "The admin who created the post on behalf of a user, if any.",
            "category": "The category the post belongs to, if any.",
            "commentCount": "The number of comments on the post.",
            "created": "Time at which the post was created, in ISO 8601 format.",
            "details": "The post's body/description.",
            "eta": "The estimated time of delivery for the post.",
            "imageURLs": "Image URLs attached to the post.",
            "owner": "The admin who owns the post, if any.",
            "score": "The post's vote score.",
            "status": "The post's status (e.g. open, planned, in progress, complete, closed).",
            "statusChangedAt": "Time at which the post's status last changed, in ISO 8601 format.",
            "tags": "The tags applied to the post.",
            "title": "The post's title.",
            "url": "The URL to the post's page.",
            "voteCount": "The number of votes the post has received.",
        },
    },
    "status_changes": {
        "description": "A record of a post's status changing (e.g. open → planned).",
        "docs_url": "https://developers.canny.io/api-reference#status_changes",
        "columns": {
            "id": "A unique identifier for the status change.",
            "changeComment": "The comment left by the admin when changing the status.",
            "changer": "The admin who changed the status.",
            "created": "Time at which the status change occurred, in ISO 8601 format.",
            "post": "The post whose status changed.",
            "status": "The new status the post was changed to.",
        },
    },
    "tags": {
        "description": "A tag that can be applied to posts on a board.",
        "docs_url": "https://developers.canny.io/api-reference#tags",
        "columns": {
            "id": "A unique identifier for the tag.",
            "board": "The board the tag belongs to.",
            "created": "Time at which the tag was created, in ISO 8601 format.",
            "name": "The name of the tag.",
            "postCount": "The number of posts with this tag.",
            "url": "The URL to the tag's page.",
        },
    },
    "users": {
        "description": "A user who has interacted with your Canny boards.",
        "docs_url": "https://developers.canny.io/api-reference#users",
        "columns": {
            "id": "A unique identifier for the user.",
            "created": "Time at which the user was created, in ISO 8601 format.",
            "email": "The user's email address.",
            "isAdmin": "Whether the user is an admin of the Canny workspace.",
            "name": "The user's name.",
            "url": "The URL to the user's profile.",
            "userID": "The unique identifier you assigned to the user via the widget/SSO.",
            "avatarURL": "The URL to the user's avatar image.",
            "companies": "The companies the user belongs to.",
            "customFields": "Custom fields associated with the user.",
            "lastActivity": "Time of the user's last activity, in ISO 8601 format.",
        },
    },
    "votes": {
        "description": "A vote cast by a user on a post.",
        "docs_url": "https://developers.canny.io/api-reference#votes",
        "columns": {
            "id": "A unique identifier for the vote.",
            "board": "The board the voted-on post belongs to.",
            "by": "The admin who cast the vote on behalf of a user, if any.",
            "created": "Time at which the vote was cast, in ISO 8601 format.",
            "post": "The post that was voted on.",
            "voter": "The user who cast the vote.",
        },
    },
}
