"""Canonical, documentation-sourced descriptions for Chargify (Maxio Advanced Billing) endpoints.

Sourced from the official Maxio Advanced Billing API reference
(https://developers.maxio.com/http/). Keyed by the resource names in `settings.py` `ENDPOINTS`,
which match the `ExternalDataSchema.name` of a synced Chargify table. Columns absent here fall
back to LLM enrichment.
"""

from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Fields shared by most Chargify objects; merged into each entry so we don't repeat them.
_COMMON_COLUMNS = {
    "id": "Unique identifier for the object within the site.",
    "created_at": "Timestamp for when the object was created (ISO 8601).",
    "updated_at": "Timestamp for when the object was last updated (ISO 8601).",
}


def _columns(**overrides: str) -> dict[str, str]:
    return {**_COMMON_COLUMNS, **overrides}


CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "Customers": {
        "description": "A customer of the site, who owns subscriptions and is billed for them.",
        "docs_url": "https://developers.maxio.com/http/resources/customers",
        "columns": _columns(
            first_name="Customer's first name.",
            last_name="Customer's last name.",
            email="Customer's email address.",
            organization="Company or organization name associated with the customer.",
            reference="Unique value from your own system used to reference the customer.",
            phone="Customer's phone number.",
            address="Customer's street address.",
            address_2="Second line of the customer's street address.",
            city="Customer's city.",
            state="Customer's state or province.",
            zip="Customer's postal code.",
            country="Customer's country (ISO 3166 code).",
            verified="Whether the customer's ACH bank account has been verified.",
            portal_customer_created_at="Timestamp for when the customer's Billing Portal account was created.",
            vat_number="Customer's VAT number, used for tax calculations.",
            tax_exempt="Whether the customer is exempt from tax.",
        ),
    },
    "Subscriptions": {
        "description": "A subscription binding a customer to a product, tracking its billing state and lifecycle.",
        "docs_url": "https://developers.maxio.com/http/resources/subscriptions",
        "columns": _columns(
            state="Current state of the subscription (e.g. active, canceled, past_due, trialing).",
            customer="The customer the subscription belongs to (nested object).",
            product="The product the subscription is for (nested object).",
            balance_in_cents="Outstanding balance owed on the subscription, in cents.",
            current_period_started_at="Timestamp for the start of the current billing period.",
            current_period_ends_at="Timestamp for the end of the current billing period.",
            next_assessment_at="Timestamp for when the next billing assessment runs.",
            trial_started_at="Timestamp for when the trial period started, if any.",
            trial_ended_at="Timestamp for when the trial period ended, if any.",
            activated_at="Timestamp for when the subscription became active.",
            canceled_at="Timestamp for when the subscription was canceled, if applicable.",
            cancellation_message="Message recorded when the subscription was canceled.",
            expires_at="Timestamp for when the subscription is scheduled to expire.",
            currency="Currency the subscription is billed in (ISO 4217 code).",
            total_revenue_in_cents="Total revenue collected on the subscription, in cents.",
            product_price_in_cents="Price of the subscription's product, in cents.",
        ),
    },
    "Products": {
        "description": "A product defining the recurring price and terms a subscription can be created against.",
        "docs_url": "https://developers.maxio.com/http/resources/products",
        "columns": _columns(
            name="Name of the product.",
            handle="Unique, URL-safe handle used to reference the product via the API.",
            description="Description of the product.",
            price_in_cents="Recurring price of the product, in cents.",
            interval="Length of the billing period.",
            interval_unit="Unit of the billing period (day or month).",
            trial_price_in_cents="Price charged during the trial period, in cents.",
            trial_interval="Length of the trial period.",
            trial_interval_unit="Unit of the trial period (day or month).",
            initial_charge_in_cents="One-time setup charge applied at signup, in cents.",
            product_family="The product family this product belongs to (nested object).",
            accounting_code="Accounting code used to categorize the product's revenue.",
            request_credit_card="Whether a credit card is required at signup.",
            archived_at="Timestamp for when the product was archived, if applicable.",
        ),
    },
    "ProductFamilies": {
        "description": "A grouping of related products, components, and coupons within the site.",
        "docs_url": "https://developers.maxio.com/http/resources/product-families",
        "columns": _columns(
            name="Name of the product family.",
            handle="Unique, URL-safe handle used to reference the product family.",
            description="Description of the product family.",
            accounting_code="Accounting code used to categorize the product family.",
        ),
    },
    "Components": {
        "description": "An add-on billed alongside a subscription (metered, quantity, on/off, or prepaid).",
        "docs_url": "https://developers.maxio.com/http/resources/components",
        "columns": _columns(
            name="Name of the component.",
            handle="Unique, URL-safe handle used to reference the component.",
            kind="Type of component (e.g. metered_component, quantity_based_component, on_off_component).",
            pricing_scheme="Pricing scheme used (e.g. per_unit, volume, tiered, stairstep).",
            unit_name="Name of the unit the component is measured in.",
            unit_price="Price per unit of the component.",
            product_family_id="Identifier of the product family the component belongs to.",
            price_per_unit_in_cents="Price per unit of the component, in cents.",
            taxable="Whether the component is taxable.",
            recurring="Whether the component recurs each billing period.",
            archived_at="Timestamp for when the component was archived, if applicable.",
        ),
    },
    "Transactions": {
        "description": "A financial event on a subscription, such as a charge, payment, credit, or refund.",
        "docs_url": "https://developers.maxio.com/http/resources/transactions",
        "columns": _columns(
            transaction_type="Type of transaction (e.g. charge, payment, credit, refund, adjustment).",
            amount_in_cents="Amount of the transaction, in cents.",
            subscription_id="Identifier of the subscription the transaction belongs to.",
            success="Whether the transaction succeeded.",
            memo="Description or memo recorded on the transaction.",
            starting_balance_in_cents="Subscription balance before the transaction, in cents.",
            ending_balance_in_cents="Subscription balance after the transaction, in cents.",
            payment_id="Identifier of the associated payment, if any.",
            product_id="Identifier of the product the transaction relates to.",
            gateway_transaction_id="Identifier of the transaction in the payment gateway.",
            kind="Finer-grained classification of the transaction.",
            gateway_used="Payment gateway used to process the transaction.",
        ),
    },
    "Events": {
        "description": "An append-only record of an event that occurred on a subscription or the site.",
        "docs_url": "https://developers.maxio.com/http/resources/events",
        "columns": _columns(
            key="Machine-readable key identifying the event type (e.g. signup_success, payment_success).",
            message="Human-readable description of the event.",
            subscription_id="Identifier of the subscription the event relates to, if any.",
            customer_id="Identifier of the customer the event relates to, if any.",
            event_specific_data="Structured payload with details specific to the event type.",
        ),
    },
    "Invoices": {
        "description": "An invoice issued for a subscription, listing line items, taxes, and payments.",
        "docs_url": "https://developers.maxio.com/http/resources/invoices",
        "columns": _columns(
            uid="Globally unique identifier for the invoice.",
            number="Sequential invoice number shown to the customer.",
            subscription_id="Identifier of the subscription the invoice was issued for.",
            customer_id="Identifier of the customer the invoice was issued to.",
            status="Current status of the invoice (e.g. draft, open, paid, voided).",
            currency="Currency of the invoice (ISO 4217 code).",
            total_amount="Total amount of the invoice.",
            paid_amount="Amount that has been paid on the invoice.",
            due_amount="Amount still due on the invoice.",
            issue_date="Date the invoice was issued.",
            due_date="Date the invoice payment is due.",
            paid_date="Date the invoice was paid in full, if applicable.",
            product_name="Name of the product the invoice relates to.",
            line_items="Line items itemizing the charges on the invoice.",
        ),
    },
    "CreditNotes": {
        "description": "An inverse invoice that reduces what a customer owes, applied against one or more invoices.",
        "docs_url": "https://developers.maxio.com/http/resources/credit-notes",
        # Credit notes carry none of the shared id/created_at/updated_at fields.
        "columns": {
            "uid": 'Globally unique identifier for the credit note, prefixed with "cn_".',
            "site_id": "Identifier of the site the credit note belongs to.",
            "customer_id": "Identifier of the customer the credit note belongs to.",
            "subscription_id": "Identifier of the subscription that generated the credit note.",
            "number": "Short identifying number shown on the credit note to the customer.",
            "sequence_number": "Monotonically increasing number assigned as credit notes are created, unique within the site.",
            "issue_date": "Date the credit was made available for application (YYYY-MM-DD).",
            "applied_date": "Date the credit note became fully applied to invoices; empty while only partially applied.",
            "status": "Current status of the credit note (e.g. open, partial, applied, refunded).",
            "currency": "Currency of the credit note amounts (ISO 4217 code).",
            "memo": "Description of the reason for the credit, printed on the credit note.",
            "subtotal_amount": "Sum of all line items before discounts or taxes, as a positive credit amount.",
            "discount_amount": "Discount credited back to the customer, as a positive amount.",
            "tax_amount": "Tax credited back to the customer, as a positive amount.",
            "total_amount": "Credit note total, equal to subtotal_amount - discount_amount + tax_amount.",
            "applied_amount": "Amount of the credit note already applied to invoices.",
            "remaining_amount": "Amount of the credit note still available to apply, equal to total_amount - applied_amount.",
            "origin_invoices": "The invoices the credit note originated from.",
        },
    },
    "Coupons": {
        "description": "A discount that can be applied to subscriptions, either site-wide or within a product family.",
        "docs_url": "https://developers.maxio.com/http/resources/coupons",
        "columns": _columns(
            name="Name of the coupon shown in the Chargify interface.",
            code="Code customers enter to redeem the coupon.",
            description="Description of the coupon.",
            amount="Flat discount amount, when the coupon discounts a fixed amount.",
            amount_in_cents="Flat discount amount in cents.",
            percentage="Percentage discount, when the coupon discounts a percentage.",
            discount_type="Whether the coupon discounts an amount or a percentage.",
            product_family_id="Identifier of the product family the coupon is restricted to, if any.",
            product_family_name="Name of the product family the coupon is restricted to, if any.",
            start_date="Timestamp for when the coupon becomes redeemable.",
            end_date="Timestamp for when the coupon stops being redeemable.",
            archived_at="Timestamp for when the coupon was archived, if applicable.",
            recurring="Whether the discount applies to every billing period or only the first.",
            recurring_scheme="How the recurring discount repeats (e.g. do_not_recur, noenddate, limited).",
            duration_period_count="Number of billing periods a limited recurring discount applies for.",
            conversion_limit="Maximum number of times the coupon can be redeemed.",
            stackable="Whether the coupon can be combined with other coupons.",
            compounding_strategy="How the discount compounds when stacked with other coupons.",
            allow_negative_balance="Whether the discount may take the subscription balance below zero.",
            exclude_mid_period_allocations="Whether mid-period allocation charges are excluded from the discount.",
            apply_on_cancel_at_end_of_period="Whether the discount applies to the final invoice when cancelling at period end.",
            use_site_exchange_rate="Whether the site exchange rate converts the discount for other currencies.",
            coupon_restrictions="Products and components the coupon is restricted to.",
        ),
    },
    "ReasonCodes": {
        "description": "A churn code a merchant can pick from when cancelling a subscription.",
        "docs_url": "https://developers.maxio.com/http/resources/reason-codes",
        "columns": _columns(
            site_id="Identifier of the site the reason code belongs to.",
            code="Short code identifying the churn reason.",
            description="Description of the churn reason shown when cancelling.",
            position="Order the reason code appears in when picking a churn reason.",
        ),
    },
}
