-- AUTO-GENERATED from the declarative HCL by ops/gen-sql.sh — do not edit.
-- Full CREATE schema for the prod-eu/sessions node. Apply to a fresh ClickHouse to build it.

CREATE TABLE posthog.channel_definition (
  domain String,
  kind String,
  domain_type Nullable(String),
  type_if_paid Nullable(String),
  type_if_organic Nullable(String)
) ENGINE = Distributed('posthog_single_shard', 'posthog', 'channel_definition');
CREATE TABLE posthog.cohortpeople (
  person_id UUID,
  cohort_id Int64,
  team_id Int64,
  sign Int8,
  version UInt64
) ENGINE = Distributed('posthog_single_shard', 'posthog', 'cohortpeople', rand());
CREATE TABLE posthog.events (
  uuid UUID,
  event String,
  properties String,
  timestamp DateTime64(6, 'UTC'),
  team_id Int64,
  distinct_id String,
  elements_hash String,
  created_at DateTime64(6, 'UTC'),
  _timestamp DateTime,
  _offset UInt64,
  elements_chain String,
  $group_0 String COMMENT 'column_materializer::$group_0',
  $group_1 String COMMENT 'column_materializer::$group_1',
  $group_2 String COMMENT 'column_materializer::$group_2',
  $group_3 String COMMENT 'column_materializer::$group_3',
  $group_4 String COMMENT 'column_materializer::$group_4',
  $window_id String COMMENT 'column_materializer::$window_id',
  $session_id String COMMENT 'column_materializer::$session_id',
  group_0 String ALIAS `$group_0`,
  group_1 String ALIAS `$group_1`,
  group_2 String ALIAS `$group_2`,
  group_3 String ALIAS `$group_3`,
  group_4 String ALIAS `$group_4`,
  person_id UUID,
  person_properties String,
  group0_properties String,
  group1_properties String,
  group2_properties String,
  group3_properties String,
  group4_properties String,
  person_created_at DateTime64(3),
  group0_created_at DateTime64(3),
  group1_created_at DateTime64(3),
  group2_created_at DateTime64(3),
  group3_created_at DateTime64(3),
  group4_created_at DateTime64(3),
  inserted_at Nullable(DateTime64(6, 'UTC')) DEFAULT now64(),
  person_mode Enum8('full'=0, 'propertyless'=1, 'force_upgrade'=2),
  elements_chain_href String COMMENT 'column_materializer::elements_chain::href',
  elements_chain_texts Array(String) COMMENT 'column_materializer::elements_chain::texts',
  elements_chain_ids Array(String) COMMENT 'column_materializer::elements_chain::ids',
  elements_chain_elements Array(Enum8('a'=1, 'button'=2, 'form'=3, 'input'=4, 'select'=5, 'textarea'=6, 'label'=7)) COMMENT 'column_materializer::elements_chain::elements',
  properties_group_custom Map(String, String),
  properties_group_feature_flags Map(String, String),
  is_deleted Bool,
  person_properties_map_custom Map(String, String),
  mat_$ai_trace_id Nullable(String) COMMENT 'column_materializer::properties::$ai_trace_id',
  $session_id_uuid Nullable(UInt128),
  consumer_breadcrumbs Array(String),
  properties_group_ai Map(String, String),
  mat_historical_migration Nullable(String) COMMENT 'column_materializer::properties::historical_migration',
  mat_$ai_session_id Nullable(String) COMMENT 'column_materializer::properties::$ai_session_id',
  mat_$ai_is_error Nullable(String) COMMENT 'column_materializer::properties::$ai_is_error',
  dmat_string_0 Nullable(String),
  dmat_string_1 Nullable(String),
  dmat_string_2 Nullable(String),
  dmat_string_3 Nullable(String),
  dmat_string_4 Nullable(String),
  dmat_string_5 Nullable(String),
  dmat_string_6 Nullable(String),
  dmat_string_7 Nullable(String),
  dmat_string_8 Nullable(String),
  dmat_string_9 Nullable(String),
  historical_migration Bool,
  properties_group_ai_large Map(String, String),
  mat_$ai_prompt_name Nullable(String) COMMENT 'column_materializer::properties::$ai_prompt_name',
  mat_$ai_experiment_id Nullable(String) COMMENT 'column_materializer::properties::$ai_experiment_id'
) ENGINE = Distributed('posthog', 'posthog', 'sharded_events', sipHash64(distinct_id));
CREATE TABLE posthog.person_distinct_id_overrides (
  team_id Int64,
  distinct_id String,
  person_id UUID,
  is_deleted Int8,
  version Int64,
  _timestamp DateTime,
  _offset UInt64,
  _partition UInt64
) ENGINE = Distributed('posthog_single_shard', 'posthog', 'person_distinct_id_overrides', sipHash64(distinct_id));
CREATE TABLE posthog.person_static_cohort (
  id UUID,
  person_id UUID,
  cohort_id Int64,
  team_id Int64,
  _timestamp DateTime,
  _offset UInt64
) ENGINE = Distributed('posthog_single_shard', 'posthog', 'person_static_cohort', rand());
CREATE TABLE posthog.query_log_archive (
  hostname LowCardinality(String),
  user LowCardinality(String),
  query_id String,
  initial_query_id String,
  is_initial_query UInt8,
  type Enum8('QueryStart'=1, 'QueryFinish'=2, 'ExceptionBeforeStart'=3, 'ExceptionWhileProcessing'=4),
  event_date Date,
  event_time DateTime,
  event_time_microseconds DateTime64(6),
  query_start_time DateTime,
  query_start_time_microseconds DateTime64(6),
  query_duration_ms UInt64,
  read_rows UInt64,
  read_bytes UInt64,
  written_rows UInt64,
  written_bytes UInt64,
  result_rows UInt64,
  result_bytes UInt64,
  memory_usage UInt64,
  peak_threads_usage UInt64,
  current_database LowCardinality(String),
  query String,
  formatted_query String,
  normalized_query_hash UInt64,
  query_kind LowCardinality(String),
  exception_code Int32,
  exception String,
  stack_trace String,
  team_id Int64,
  log_comment JSON(max_dynamic_paths=256, access_method LowCardinality(String), alert_config_id String, api_key_label String, api_key_mask String, batch_export_id String, chargeable Bool, client_query_id String, cohort_id Int64, `dagster.job_name` String, `dagster.run_id` String, `dagster.tags.owner` String, dashboard_id Int64, experiment_feature_flag_key String, experiment_id Int64, feature LowCardinality(String), id String, insight_id Int64, is_impersonated Bool, kind LowCardinality(String), name String, org_id String, person_on_events_mode LowCardinality(String), product LowCardinality(String), query_type LowCardinality(String), request_name String, route_id String, service_name String, session_id String, table_id String, team_id Int64, `temporal.activity_id` String, `temporal.activity_type` String, `temporal.attempt` Int64, `temporal.workflow_id` String, `temporal.workflow_namespace` String, `temporal.workflow_run_id` String, `temporal.workflow_type` String, user_id Int64, warehouse_query Bool, workflow LowCardinality(String), workload LowCardinality(String), SKIP cache_key, SKIP filter, SKIP hogql_features, SKIP http_referer, SKIP http_request_id, SKIP http_user_agent, SKIP query_settings, SKIP timings, SKIP user_email),
  ProfileEvents Map(String, UInt64),
  exception_name String ALIAS errorCodeToName(exception_code),
  ProfileEvents_RealTimeMicroseconds Int64 ALIAS ProfileEvents['RealTimeMicroseconds'],
  ProfileEvents_OSCPUVirtualTimeMicroseconds Int64 ALIAS ProfileEvents['OSCPUVirtualTimeMicroseconds'],
  ProfileEvents_S3Clients Int64 ALIAS ProfileEvents['S3Clients'],
  ProfileEvents_S3DeleteObjects Int64 ALIAS ProfileEvents['S3DeleteObjects'],
  ProfileEvents_S3CopyObject Int64 ALIAS ProfileEvents['S3CopyObject'],
  ProfileEvents_S3ListObjects Int64 ALIAS ProfileEvents['S3ListObjects'],
  ProfileEvents_S3HeadObject Int64 ALIAS ProfileEvents['S3HeadObject'],
  ProfileEvents_S3GetObjectAttributes Int64 ALIAS ProfileEvents['S3GetObjectAttributes'],
  ProfileEvents_S3CreateMultipartUpload Int64 ALIAS ProfileEvents['S3CreateMultipartUpload'],
  ProfileEvents_S3UploadPartCopy Int64 ALIAS ProfileEvents['S3UploadPartCopy'],
  ProfileEvents_S3UploadPart Int64 ALIAS ProfileEvents['S3UploadPart'],
  ProfileEvents_S3AbortMultipartUpload Int64 ALIAS ProfileEvents['S3AbortMultipartUpload'],
  ProfileEvents_S3CompleteMultipartUpload Int64 ALIAS ProfileEvents['S3CompleteMultipartUpload'],
  ProfileEvents_S3PutObject Int64 ALIAS ProfileEvents['S3PutObject'],
  ProfileEvents_S3GetObject Int64 ALIAS ProfileEvents['S3GetObject'],
  ProfileEvents_ReadBufferFromS3Bytes Int64 ALIAS ProfileEvents['ReadBufferFromS3Bytes'],
  ProfileEvents_WriteBufferFromS3Bytes Int64 ALIAS ProfileEvents['WriteBufferFromS3Bytes'],
  lc_workflow LowCardinality(String) ALIAS log_comment.workflow,
  lc_kind LowCardinality(String) ALIAS log_comment.kind,
  lc_id String ALIAS CAST(log_comment.id, 'String'),
  lc_route_id String ALIAS CAST(log_comment.route_id, 'String'),
  lc_access_method LowCardinality(String) ALIAS log_comment.access_method,
  lc_api_key_label String ALIAS CAST(log_comment.api_key_label, 'String'),
  lc_api_key_mask String ALIAS CAST(log_comment.api_key_mask, 'String'),
  lc_query_type LowCardinality(String) ALIAS log_comment.query_type,
  lc_product LowCardinality(String) ALIAS log_comment.product,
  lc_chargeable Bool ALIAS log_comment.chargeable,
  lc_name String ALIAS CAST(log_comment.name, 'String'),
  lc_request_name String ALIAS CAST(log_comment.request_name, 'String'),
  lc_client_query_id String ALIAS CAST(log_comment.client_query_id, 'String'),
  lc_org_id String ALIAS CAST(log_comment.org_id, 'String'),
  lc_user_id Int64 ALIAS log_comment.user_id,
  lc_is_impersonated Bool ALIAS log_comment.is_impersonated,
  lc_session_id String ALIAS CAST(log_comment.session_id, 'String'),
  lc_dashboard_id Int64 ALIAS log_comment.dashboard_id,
  lc_insight_id Int64 ALIAS log_comment.insight_id,
  lc_cohort_id Int64 ALIAS log_comment.cohort_id,
  lc_batch_export_id String ALIAS CAST(log_comment.batch_export_id, 'String'),
  lc_experiment_id Int64 ALIAS log_comment.experiment_id,
  lc_experiment_feature_flag_key String ALIAS CAST(log_comment.experiment_feature_flag_key, 'String'),
  lc_alert_config_id String ALIAS CAST(log_comment.alert_config_id, 'String'),
  lc_feature LowCardinality(String) ALIAS log_comment.feature,
  lc_table_id String ALIAS CAST(log_comment.table_id, 'String'),
  lc_warehouse_query Bool ALIAS log_comment.warehouse_query,
  lc_person_on_events_mode LowCardinality(String) ALIAS log_comment.person_on_events_mode,
  lc_service_name String ALIAS CAST(log_comment.service_name, 'String'),
  lc_workload LowCardinality(String) ALIAS log_comment.workload,
  lc_query__kind LowCardinality(String) ALIAS if(JSONHas(toString(log_comment), 'query', 'source'), JSONExtractString(toString(log_comment), 'query', 'source', 'kind'), JSONExtractString(toString(log_comment), 'query', 'kind')),
  lc_query__query String ALIAS multiIf(NOT is_initial_query, '', JSONHas(toString(log_comment), 'query', 'source'), JSONExtractString(toString(log_comment), 'query', 'source', 'query'), JSONExtractString(toString(log_comment), 'query', 'query')),
  lc_query String ALIAS if(is_initial_query, JSONExtractRaw(toString(log_comment), 'query'), ''),
  lc_temporal__workflow_namespace String ALIAS CAST(log_comment.`temporal.workflow_namespace`, 'String'),
  lc_temporal__workflow_type String ALIAS CAST(log_comment.`temporal.workflow_type`, 'String'),
  lc_temporal__workflow_id String ALIAS CAST(log_comment.`temporal.workflow_id`, 'String'),
  lc_temporal__workflow_run_id String ALIAS CAST(log_comment.`temporal.workflow_run_id`, 'String'),
  lc_temporal__activity_type String ALIAS CAST(log_comment.`temporal.activity_type`, 'String'),
  lc_temporal__activity_id String ALIAS CAST(log_comment.`temporal.activity_id`, 'String'),
  lc_temporal__attempt Int64 ALIAS log_comment.`temporal.attempt`,
  lc_dagster__job_name String ALIAS CAST(log_comment.`dagster.job_name`, 'String'),
  lc_dagster__run_id String ALIAS CAST(log_comment.`dagster.run_id`, 'String'),
  lc_dagster__owner String ALIAS CAST(log_comment.`dagster.tags.owner`, 'String'),
  lc_modifiers String ALIAS if(is_initial_query, JSONExtractRaw(toString(log_comment), 'modifiers'), '')
) ENGINE = Distributed('ops', 'posthog', 'sharded_query_log_archive');
CREATE TABLE posthog.raw_sessions (
  team_id Int64,
  session_id_v7 UInt128,
  distinct_id AggregateFunction(argMax, String, DateTime64(6, 'UTC')),
  min_timestamp SimpleAggregateFunction(min, DateTime64(6, 'UTC')),
  max_timestamp SimpleAggregateFunction(max, DateTime64(6, 'UTC')),
  max_inserted_at SimpleAggregateFunction(max, DateTime64(6, 'UTC')),
  urls SimpleAggregateFunction(groupUniqArrayArray, Array(String)),
  entry_url AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  end_url AggregateFunction(argMax, String, DateTime64(6, 'UTC')),
  last_external_click_url AggregateFunction(argMax, String, DateTime64(6, 'UTC')),
  initial_browser AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_browser_version AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_os AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_os_version AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_device_type AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_viewport_width AggregateFunction(argMin, Int64, DateTime64(6, 'UTC')),
  initial_viewport_height AggregateFunction(argMin, Int64, DateTime64(6, 'UTC')),
  initial_geoip_country_code AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_geoip_subdivision_1_code AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_geoip_subdivision_1_name AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_geoip_subdivision_city_name AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_geoip_time_zone AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_referring_domain AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_utm_source AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_utm_campaign AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_utm_medium AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_utm_term AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_utm_content AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_gclid AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_gad_source AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_gclsrc AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_dclid AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_gbraid AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_wbraid AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_fbclid AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_msclkid AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_twclid AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_li_fat_id AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_mc_cid AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_igshid AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_ttclid AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_irclid AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  pageview_count SimpleAggregateFunction(sum, Int64),
  pageview_uniq AggregateFunction(uniq, Nullable(UUID)),
  autocapture_count SimpleAggregateFunction(sum, Int64),
  autocapture_uniq AggregateFunction(uniq, Nullable(UUID)),
  screen_count SimpleAggregateFunction(sum, Int64),
  screen_uniq AggregateFunction(uniq, Nullable(UUID)),
  maybe_has_session_replay SimpleAggregateFunction(max, Bool),
  page_screen_autocapture_uniq_up_to AggregateFunction(uniqUpTo(1), Nullable(UUID)),
  vitals_lcp AggregateFunction(argMin, Nullable(Float64), DateTime64(6, 'UTC')),
  initial__kx AggregateFunction(argMin, String, DateTime64(6, 'UTC'))
) ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/sessions/noshard/posthog.raw_sessions', '{shard}-{replica}') ORDER BY (team_id, toStartOfHour(fromUnixTimestamp(intDiv(toUInt64(bitShiftRight(session_id_v7, 80)), 1000))), cityHash64(session_id_v7), session_id_v7) PARTITION BY toYYYYMM(fromUnixTimestamp(intDiv(toUInt64(bitShiftRight(session_id_v7, 80)), 1000))) SAMPLE BY cityHash64(session_id_v7) SETTINGS index_granularity = 8192;
CREATE TABLE posthog.raw_sessions_v3 (
  team_id Int64,
  session_id_v7 UInt128,
  session_timestamp DateTime64(3) DEFAULT fromUnixTimestamp64Milli(toUInt64(bitShiftRight(session_id_v7, 80))),
  distinct_id AggregateFunction(argMax, String, DateTime64(6, 'UTC')),
  distinct_ids AggregateFunction(groupUniqArray, String),
  min_timestamp SimpleAggregateFunction(min, DateTime64(6, 'UTC')),
  max_timestamp SimpleAggregateFunction(max, DateTime64(6, 'UTC')),
  max_inserted_at SimpleAggregateFunction(max, DateTime64(6, 'UTC')),
  urls SimpleAggregateFunction(groupUniqArrayArray(2000), Array(String)),
  entry_url AggregateFunction(argMin, Nullable(String), DateTime64(6, 'UTC')),
  end_url AggregateFunction(argMax, Nullable(String), DateTime64(6, 'UTC')),
  last_external_click_url AggregateFunction(argMax, Nullable(String), DateTime64(6, 'UTC')),
  browser AggregateFunction(argMin, Nullable(String), DateTime64(6, 'UTC')),
  browser_version AggregateFunction(argMin, Nullable(String), DateTime64(6, 'UTC')),
  os AggregateFunction(argMin, Nullable(String), DateTime64(6, 'UTC')),
  os_version AggregateFunction(argMin, Nullable(String), DateTime64(6, 'UTC')),
  device_type AggregateFunction(argMin, Nullable(String), DateTime64(6, 'UTC')),
  viewport_width AggregateFunction(argMin, Nullable(Int64), DateTime64(6, 'UTC')),
  viewport_height AggregateFunction(argMin, Nullable(Int64), DateTime64(6, 'UTC')),
  geoip_country_code AggregateFunction(argMin, Nullable(String), DateTime64(6, 'UTC')),
  geoip_subdivision_1_code AggregateFunction(argMin, Nullable(String), DateTime64(6, 'UTC')),
  geoip_subdivision_1_name AggregateFunction(argMin, Nullable(String), DateTime64(6, 'UTC')),
  geoip_subdivision_city_name AggregateFunction(argMin, Nullable(String), DateTime64(6, 'UTC')),
  geoip_time_zone AggregateFunction(argMin, Nullable(String), DateTime64(6, 'UTC')),
  entry_referring_domain AggregateFunction(argMin, Nullable(String), DateTime64(6, 'UTC')),
  entry_utm_source AggregateFunction(argMin, Nullable(String), DateTime64(6, 'UTC')),
  entry_utm_campaign AggregateFunction(argMin, Nullable(String), DateTime64(6, 'UTC')),
  entry_utm_medium AggregateFunction(argMin, Nullable(String), DateTime64(6, 'UTC')),
  entry_utm_term AggregateFunction(argMin, Nullable(String), DateTime64(6, 'UTC')),
  entry_utm_content AggregateFunction(argMin, Nullable(String), DateTime64(6, 'UTC')),
  entry_gclid AggregateFunction(argMin, Nullable(String), DateTime64(6, 'UTC')),
  entry_gad_source AggregateFunction(argMin, Nullable(String), DateTime64(6, 'UTC')),
  entry_fbclid AggregateFunction(argMin, Nullable(String), DateTime64(6, 'UTC')),
  entry_has_gclid AggregateFunction(argMin, Bool, DateTime64(6, 'UTC')),
  entry_has_fbclid AggregateFunction(argMin, Bool, DateTime64(6, 'UTC')),
  entry_ad_ids_map AggregateFunction(argMin, Map(String, String), DateTime64(6, 'UTC')),
  entry_ad_ids_set AggregateFunction(argMin, Array(String), DateTime64(6, 'UTC')),
  entry_channel_type_properties AggregateFunction(argMin, Tuple(Nullable(String), Nullable(String), Nullable(String), Nullable(String), Bool, Bool, Nullable(String)), DateTime64(6, 'UTC')),
  pageview_uniq AggregateFunction(uniqExact, Nullable(UUID)),
  autocapture_uniq AggregateFunction(uniqExact, Nullable(UUID)),
  screen_uniq AggregateFunction(uniqExact, Nullable(UUID)),
  page_screen_uniq_up_to AggregateFunction(uniqUpTo(1), Nullable(UUID)),
  has_autocapture SimpleAggregateFunction(max, Bool),
  flag_values AggregateFunction(groupUniqArrayMap, Map(String, String)),
  flag_keys SimpleAggregateFunction(groupUniqArrayArray, Array(String)),
  event_names SimpleAggregateFunction(groupUniqArrayArray, Array(String)),
  hosts SimpleAggregateFunction(groupUniqArrayArray(100), Array(String)),
  emails SimpleAggregateFunction(groupUniqArrayArray(10), Array(String)),
  has_replay_events SimpleAggregateFunction(max, Bool),
  INDEX event_names_bloom_filter event_names TYPE bloom_filter() GRANULARITY 1,
  INDEX flag_keys_bloom_filter flag_keys TYPE bloom_filter() GRANULARITY 1
) ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/sessions/noshard/posthog.raw_sessions_v3', '{shard}-{replica}') ORDER BY (team_id, session_timestamp, session_id_v7) PARTITION BY toYYYYMM(session_timestamp) SETTINGS index_granularity = 8192, storage_policy = 's3_tiered';
CREATE TABLE posthog.sessions (
  session_id String,
  team_id Int64,
  distinct_id SimpleAggregateFunction(any, String),
  min_timestamp SimpleAggregateFunction(min, DateTime64(6, 'UTC')),
  max_timestamp SimpleAggregateFunction(max, DateTime64(6, 'UTC')),
  urls SimpleAggregateFunction(groupUniqArrayArray, Array(String)),
  entry_url AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  exit_url AggregateFunction(argMax, String, DateTime64(6, 'UTC')),
  initial_referring_domain AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_utm_source AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_utm_campaign AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_utm_medium AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_utm_term AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_utm_content AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_gclid AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_gad_source AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_gclsrc AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_dclid AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_gbraid AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_wbraid AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_fbclid AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_msclkid AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_twclid AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_li_fat_id AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_mc_cid AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_igshid AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  initial_ttclid AggregateFunction(argMin, String, DateTime64(6, 'UTC')),
  event_count_map SimpleAggregateFunction(sumMap, Map(String, Int64)),
  pageview_count SimpleAggregateFunction(sum, Int64),
  autocapture_count SimpleAggregateFunction(sum, Int64)
) ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/sessions/noshard/posthog.sessions', '{shard}-{replica}') ORDER BY (toStartOfDay(min_timestamp), team_id, session_id) PARTITION BY toYYYYMM(min_timestamp) SETTINGS index_granularity = 512;
CREATE TABLE posthog.web_pre_aggregated_teams (
  team_id UInt64,
  enabled_by String DEFAULT 'system',
  version UInt32 DEFAULT toUnixTimestamp(now())
) ENGINE = Distributed('posthog_single_shard', 'posthog', 'web_pre_aggregated_teams');
CREATE TABLE posthog.writable_query_log_archive (
  hostname LowCardinality(String),
  user LowCardinality(String),
  query_id String,
  initial_query_id String,
  is_initial_query UInt8,
  type Enum8('QueryStart'=1, 'QueryFinish'=2, 'ExceptionBeforeStart'=3, 'ExceptionWhileProcessing'=4),
  event_date Date,
  event_time DateTime,
  event_time_microseconds DateTime64(6),
  query_start_time DateTime,
  query_start_time_microseconds DateTime64(6),
  query_duration_ms UInt64,
  read_rows UInt64,
  read_bytes UInt64,
  written_rows UInt64,
  written_bytes UInt64,
  result_rows UInt64,
  result_bytes UInt64,
  memory_usage UInt64,
  peak_threads_usage UInt64,
  current_database LowCardinality(String),
  query String,
  formatted_query String,
  normalized_query_hash UInt64,
  query_kind LowCardinality(String),
  exception_code Int32,
  exception String,
  stack_trace String,
  team_id Int64,
  log_comment JSON(max_dynamic_paths=256, access_method LowCardinality(String), alert_config_id String, api_key_label String, api_key_mask String, batch_export_id String, chargeable Bool, client_query_id String, cohort_id Int64, `dagster.job_name` String, `dagster.run_id` String, `dagster.tags.owner` String, dashboard_id Int64, experiment_feature_flag_key String, experiment_id Int64, feature LowCardinality(String), id String, insight_id Int64, is_impersonated Bool, kind LowCardinality(String), name String, org_id String, person_on_events_mode LowCardinality(String), product LowCardinality(String), query_type LowCardinality(String), request_name String, route_id String, service_name String, session_id String, table_id String, team_id Int64, `temporal.activity_id` String, `temporal.activity_type` String, `temporal.attempt` Int64, `temporal.workflow_id` String, `temporal.workflow_namespace` String, `temporal.workflow_run_id` String, `temporal.workflow_type` String, user_id Int64, warehouse_query Bool, workflow LowCardinality(String), workload LowCardinality(String), SKIP cache_key, SKIP filter, SKIP hogql_features, SKIP http_referer, SKIP http_request_id, SKIP http_user_agent, SKIP query_settings, SKIP timings, SKIP user_email),
  ProfileEvents Map(String, UInt64)
) ENGINE = Distributed('ops', 'posthog', 'query_log_archive_buffer');
CREATE MATERIALIZED VIEW posthog.ops_query_log_archive_mv TO posthog.writable_query_log_archive (hostname LowCardinality(String), user LowCardinality(String), query_id String, initial_query_id String, is_initial_query UInt8, type Enum8('QueryStart'=1, 'QueryFinish'=2, 'ExceptionBeforeStart'=3, 'ExceptionWhileProcessing'=4), event_date Date, event_time DateTime, event_time_microseconds DateTime64(6), query_start_time DateTime, query_start_time_microseconds DateTime64(6), query_duration_ms UInt64, read_rows UInt64, read_bytes UInt64, written_rows UInt64, written_bytes UInt64, result_rows UInt64, result_bytes UInt64, memory_usage UInt64, peak_threads_usage UInt64, current_database LowCardinality(String), query String, formatted_query String, normalized_query_hash UInt64, query_kind LowCardinality(String), exception_code Int32, exception String, stack_trace String, team_id Int64, log_comment String, ProfileEvents Map(LowCardinality(String), UInt64)) AS SELECT
  hostname,
  user,
  query_id,
  initial_query_id,
  is_initial_query,
  type,
  event_date,
  event_time,
  event_time_microseconds,
  query_start_time,
  query_start_time_microseconds,
  query_duration_ms,
  read_rows,
  read_bytes,
  written_rows,
  written_bytes,
  result_rows,
  result_bytes,
  memory_usage,
  peak_threads_usage,
  current_database,
  query,
  formatted_query,
  normalized_query_hash,
  query_kind,
  exception_code,
  exception,
  stack_trace,
  JSONExtractInt(log_comment, 'team_id') AS team_id,
  if(isValidJSON(log_comment), log_comment, '{}') AS log_comment,
  ProfileEvents
FROM system.query_log
WHERE type != 'QueryStart';
CREATE VIEW posthog.custom_metrics_backups AS WITH
  ['ClickHouseCustomMetric_BackupFailed', 'ClickHouseCustomMetric_BackupSuccess', 'ClickHouseCustomMetric_BackupCancelled', 'ClickHouseCustomMetric_BackupAttempts'] AS names,
  [toInt64(countIf(status = 'BACKUP_FAILED')), toInt64(countIf(status = 'BACKUP_CREATED')), toInt64(countIf(status = 'BACKUP_CANCELLED')), toInt64(countIf(status = 'CREATING_BACKUP'))] AS `values`,
  ['Number of failed backups', 'Number of successful backups', 'Number of cancelled backups', 'Number of backup attempts'] AS descriptions,
  ['gauge', 'gauge', 'gauge', 'gauge'] AS types,
  arrayJoin(arrayZip(names, `values`, descriptions, types)) AS tpl
SELECT
  tpl.1 AS name,
  map('instance', hostname()) AS labels,
  tpl.2 AS value,
  tpl.3 AS help,
  tpl.4 AS type
FROM system.backup_log
WHERE event_date = today()
GROUP BY
  event_date;
CREATE VIEW posthog.custom_metrics_dictionaries AS SELECT
  'ClickHouseCustomMetric_DictionariesFailed' AS name,
  map(
    'instance',
    hostname(),
    'database',
    d.database,
    'dictionary',
    d.dict_name,
    'uuid',
    toString(d.uuid),
    'status',
    toString(d.status)
  ) AS labels,
  toUInt64(1) AS value,
  'Dictionary is in FAILED or FAILED_AND_RELOADING status' AS help,
  'gauge' AS type
FROM
  (
    SELECT name AS dict_name, database, uuid, status
    FROM system.dictionaries
    WHERE status IN ('FAILED', 'FAILED_AND_RELOADING')
  ) AS d;
CREATE VIEW posthog.custom_metrics_part_counts AS SELECT
  'ClickHouseCustomMetric_MaxPartCountPerPartition' AS name,
  map('instance', hostname(), 'database', database, 'table', `table`, 'partition', partition) AS labels,
  part_count AS value,
  'Maximum number of active parts for any partition in a PostHog table' AS help,
  'gauge' AS type
FROM
  (
    SELECT database, `table`, partition, count() AS part_count
    FROM system.parts
    WHERE
      active
    AND
      (database = 'posthog')
    GROUP BY
      database, `table`, partition
    ORDER BY database ASC, `table` ASC, part_count DESC, partition ASC
    LIMIT 1 BY database, `table`
  );
CREATE VIEW posthog.custom_metrics_replication_queue AS WITH
  ['ClickHouseCustomMetric_ReplicationQueueStuckEntries', 'ClickHouseCustomMetric_ReplicationQueueMaxPostponedEntrySeconds', 'ClickHouseCustomMetric_ReplicationQueueMaxErrorEntrySeconds'] AS names,
  [toInt64(countIf(create_time < (now() - toIntervalDay(15)))), maxIf(dateDiff('seconds', create_time, last_postpone_time), last_postpone_time != '1970-01-01'), maxIf(dateDiff('seconds', create_time, last_exception_time), (last_exception_time != '1970-01-01') AND (last_exception_time > (now() - toIntervalMinute(5))))] AS `values`,
  ['Number of entries that have been in the replication queue for more than 15 days', 'Maximum number of seconds that an entry has been postponed', 'Maximum number of seconds that an entry has been in error'] AS descriptions,
  ['gauge', 'gauge', 'gauge'] AS types,
  arrayJoin(arrayZip(names, `values`, descriptions, types)) AS tpl
SELECT
  tpl.1 AS name,
  map('table', `table`, 'instance', hostname()) AS labels,
  tpl.2 AS value,
  tpl.3 AS help,
  tpl.4 AS type
FROM system.replication_queue
GROUP BY
  `table`
HAVING
  value > 0;
CREATE VIEW posthog.custom_metrics_server_crash AS SELECT
  'ClickHouseCustomMetric_ServerCrash' AS name,
  map('instance', hostname()) AS labels,
  count() AS value,
  'Number of server crashes for current date' AS help,
  'gauge' AS type
FROM system.crash_log
WHERE event_date = today()
GROUP BY
  hostname();
CREATE VIEW posthog.custom_metrics_table_sizes AS SELECT
  'ClickHouseCustomMetric_TableTotalBytes' AS name,
  map('instance', hostname(), 'database', database, 'table', `table`) AS labels,
  CAST(total_bytes, 'Float64') AS value,
  'Size of a database table on a given node (need a sum for sharded)' AS help,
  'gauge' AS type
FROM system.tables
WHERE
  (database NOT IN ('INFORMATION_SCHEMA', 'information_schema'))
AND
  (total_bytes IS NOT NULL);
CREATE VIEW posthog.custom_metrics_test AS SELECT
  'ClickHouseCustomMetric_Test' AS name,
  map('instance', hostname()) AS labels,
  1 AS value,
  'Test to check that the metric endpoint is working' AS help,
  'gauge' AS type;
CREATE OR REPLACE DICTIONARY posthog.channel_definition_dict (`domain` String, `kind` String, `domain_type` Nullable(String), `type_if_paid` Nullable(String), `type_if_organic` Nullable(String)) PRIMARY KEY domain, kind SOURCE(CLICKHOUSE(USER 'dict_reader' TABLE 'channel_definition')) LAYOUT(COMPLEX_KEY_HASHED()) LIFETIME(MIN 3000 MAX 3600);
CREATE OR REPLACE DICTIONARY posthog.web_pre_aggregated_teams_dict (`team_id` UInt64) PRIMARY KEY team_id SOURCE(CLICKHOUSE(USER 'dict_reader' QUERY 'SELECT     team_id FROM     `web_pre_aggregated_teams` FINAL WHERE version > 0')) LAYOUT(HASHED()) LIFETIME(MIN 3000 MAX 3600);
