"""Canonical, documentation-sourced descriptions for OwnerRez endpoints and columns.

Sourced from the official OwnerRez API v2 reference (https://api.ownerreservations.com/help/v2)
and its OpenAPI spec. Keyed by the resource names in `settings.py` `ENDPOINTS`, which match the
`ExternalDataSchema.name` of a synced OwnerRez table. Columns absent here fall back to LLM enrichment.
"""

from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "Bookings": {
        "description": "A guest reservation or blocked-off period against one of the account's properties.",
        "docs_url": "https://api.ownerreservations.com/help/v2/bookings/get-bookings.md",
        "columns": {
            "id": "Unique identifier for the booking.",
            "property_id": "Identifier of the property this booking is for.",
            "guest_id": "Identifier of the guest this booking is for.",
            "status": "Booking status: Active, Pending, or Canceled.",
            "type": "Type of booking (e.g. guest booking or a simple block).",
            "is_block": "Whether this is a simple blocked-off time booking (true) or a full guest booking (false).",
            "arrival": "Arrival date in the property's time zone.",
            "departure": "Departure date in the property's time zone.",
            "adults": "Number of adult guests on the booking.",
            "children": "Number of child guests on the booking.",
            "infants": "Number of infant guests on the booking.",
            "pets": "Number of pets on the booking.",
            "total_amount": "Total amount charged for the booking.",
            "total_paid": "Total amount paid toward the booking so far.",
            "total_owed": "Remaining amount owed on the booking.",
            "total_refunded": "Total amount refunded on the booking.",
            "total_host_fees": "Total host fees charged on the booking.",
            "currency_code": "Three-letter currency code the booking is billed in.",
            "listing_site": "The listing site (channel) the booking came from, if any.",
            "platform_reservation_number": "The OTA's own reservation number, if the booking came from a channel.",
            "quote_id": "Identifier of the quote this booking was created from, if any.",
            "created_utc": "Timestamp the booking was created in OwnerRez.",
            "updated_utc": "Timestamp the booking was last updated in OwnerRez.",
            "booked_utc": "Timestamp the booking was confirmed/booked.",
            "canceled_utc": "Timestamp the booking was canceled, if applicable.",
        },
    },
    "Payments": {
        "description": "A payment collected from a guest against a booking.",
        "docs_url": "https://api.ownerreservations.com/help/v2/payments/get-payments.md",
        "columns": {
            "id": "Unique identifier for the payment.",
            "booking_id": "Identifier of the booking this payment applies to.",
            "amount": "The payment amount.",
            "description": "The payment description.",
            "type": "Type of payment.",
            "collected_utc": "Timestamp the payment was collected.",
            "is_deposited": "Whether the payment has been deposited in full.",
            "total_fees": "The amount of processing fees on this payment.",
        },
    },
    "Guests": {
        "description": "A guest record — the person a booking or quote is made for.",
        "docs_url": "https://api.ownerreservations.com/help/v2/guests/get-guests.md",
        "columns": {
            "id": "Unique identifier for the guest.",
            "first_name": "Guest's first name.",
            "last_name": "Guest's last name.",
            "notes": "Free-text notes about the guest.",
            "is_banned": "Whether the guest is banned from booking.",
            "opt_out_marketing_email": "Whether the guest has opted out of marketing email.",
            "opt_out_marketing_sms": "Whether the guest has opted out of marketing SMS.",
            "opt_out_transactional_sms": "Whether the guest has opted out of transactional SMS.",
        },
    },
    "Properties": {
        "description": "A rental property (listing) managed in the account.",
        "docs_url": "https://api.ownerreservations.com/help/v2/properties/get-properties.md",
        "columns": {
            "id": "Unique identifier for the property.",
            "key": "A globally unique ID for this property.",
            "name": "The internal property display name.",
            "external_name": "The external (public-facing) property display name.",
            "active": "Whether the property is active.",
            "is_snoozed": "Whether the property is snoozed (temporarily hidden from booking).",
            "owner_id": "Identifier of the property's owner.",
            "internal_code": "The internal property identification code.",
            "bedrooms": "Number of bedrooms at the property.",
            "bathrooms": "Total number of full and half bathrooms at the property.",
            "bathrooms_full": "Number of full bathrooms at the property.",
            "bathrooms_half": "Number of half bathrooms at the property.",
            "max_guests": "Maximum number of guests allowed at the property.",
            "max_adults": "Maximum number of adults allowed, or null to use max_guests.",
            "max_children": "Maximum number of children allowed.",
            "max_pets": "Maximum number of pets allowed, or null for any number.",
            "currency_code": "Currency used for transactions at this property.",
            "time_zone": "The property's time zone, in IANA Time Zone format.",
            "check_in": "Check-in start time rule for the property (HH:mm).",
            "check_in_end": "Check-in end time rule for the property (HH:mm).",
            "check_out": "Check-out time rule for the property (HH:mm).",
            "latitude": "Property latitude.",
            "longitude": "Property longitude.",
            "public_url": "The public property website URL.",
        },
    },
    "Quotes": {
        "description": "A price quote generated for a prospective booking, before it's confirmed.",
        "docs_url": "https://api.ownerreservations.com/help/v2/quotes/get-quotes.md",
        "columns": {
            "id": "Unique identifier for the quote.",
            "key": "A globally unique ID for this quote.",
            "guest_id": "Identifier of the guest the quote was created for.",
            "property_id": "Identifier of the quoted property.",
            "arrival": "The quoted date of arrival.",
            "departure": "The quoted date of departure.",
            "adults": "The quoted number of adults.",
            "children": "The quoted number of children.",
            "infants": "The quoted number of infants.",
            "pets": "The quoted number of pets.",
            "notes": "Notes about the quote.",
            "listing_site": "The listing site this quote is attributed to.",
            "created_utc": "Timestamp the quote was created in OwnerRez.",
            "updated_utc": "Timestamp the quote was last updated in OwnerRez.",
            "quoted_utc": "Timestamp the quote was made.",
            "expires_utc": "Timestamp the quote expires.",
        },
    },
    "Deposits": {
        "description": "A batch deposit of payments, refunds, and fees into the host's bank account.",
        "docs_url": "https://api.ownerreservations.com/help/v2/deposits/get-deposits.md",
        "columns": {
            "id": "Unique identifier for the deposit.",
            "deposited_utc": "Timestamp this deposit occurred.",
            "processor": "Payment processor the deposit went through.",
            "processing_status": "Processing status of the deposit.",
            "external_status": "External (processor-reported) status of the deposit.",
            "external_deposit_number": "The third-party (processor) identifier for this deposit, if any.",
            "total_deposited": "Total deposited amount (the final net).",
            "total_fees": "Total processing fees deducted.",
            "total_adjustments": "Total adjustments amount.",
            "total_transactions": "Total amount across every payment, refund, and fee in this deposit.",
        },
    },
    "Fees": {
        "description": "A fee charged on a booking (e.g. a cleaning fee or processing fee).",
        "docs_url": "https://api.ownerreservations.com/help/v2/fees/get-fees.md",
        "columns": {
            "id": "Unique identifier for the fee.",
            "booking_id": "Identifier of the booking this fee applies to.",
            "amount": "The fee amount.",
            "description": "The fee description.",
            "payment_id": "Identifier of the payment this fee was charged against, if any.",
            "refund_id": "Identifier of the refund this fee was charged against, if any.",
            "security_deposit_id": "Identifier of the security deposit this fee was charged against, if any.",
        },
    },
    "Refunds": {
        "description": "A refund issued to a guest against a booking.",
        "docs_url": "https://api.ownerreservations.com/help/v2/refunds/get-refunds.md",
        "columns": {
            "id": "Unique identifier for the refund.",
            "booking_id": "Identifier of the booking this refund applies to.",
            "amount": "The refund amount.",
            "description": "The refund description.",
            "type": "Type of refund.",
            "linked_payment_id": "Identifier of the payment this refund is linked to, if any.",
            "paid_utc": "Timestamp the refund was paid.",
            "is_deposited": "Whether the refund has been deposited in full.",
            "total_fees": "The amount of processing fees on this refund.",
        },
    },
    "Reviews": {
        "description": "A guest or host review left for a stay.",
        "docs_url": "https://api.ownerreservations.com/help/v2/reviews/get-reviews.md",
        "columns": {
            "id": "The review id.",
            "booking_id": "Identifier of the booking this review is for.",
            "guest_id": "Identifier of the guest who left the review.",
            "property_id": "Identifier of the property being reviewed.",
            "title": "The title of the review.",
            "body": "The body of the review.",
            "response": "The host's response to the review, if any.",
            "stars": "The rating out of five stars.",
            "visible": "Whether the review is publicly visible.",
            "listing_site": "The name of the listing site the review was posted to.",
            "display_name": "The reviewer's display name.",
            "display_location": "The reviewer's display location.",
            "month_of_stay": "The month the guest stayed at the property.",
            "year_of_stay": "The year the guest stayed at the property.",
            "date": "The date the review was written.",
            "created_utc": "Timestamp the review was created.",
            "updated_utc": "Timestamp the review was last updated.",
        },
    },
}
