from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "Campaigns": {
        "description": "The affiliate programs (campaigns) advertised on your Impact.com account.",
        "docs_url": "https://integrations.impact.com/brand-api-reference/reference/programs/programs",
        "columns": {
            "Id": "Unique identifier for the campaign (program).",
            "Name": "Name of the campaign.",
            "State": "Current state of the campaign, e.g. ACTIVE, SETUP, CLOSED.",
            "Type": "Type of campaign.",
        },
    },
    "MediaPartners": {
        "description": "The partners (publishers/affiliates) working with your campaigns.",
        "docs_url": "https://integrations.impact.com/brand-api-reference/reference/partners/partners",
        "columns": {
            "Id": "Unique identifier for the partner.",
            "Name": "Display name of the partner.",
            "State": "Account state of the partner, e.g. ACTIVE, PENDING, DEACTIVATED.",
            "PartnerType": "DIRECT or MARKETPLACE.",
            "DateCreated": "When the partner account was created.",
            "DateLastUpdated": "When the partner record was last updated.",
        },
    },
    "Invoices": {
        "description": "Invoices issued for partner payouts.",
        "docs_url": "https://integrations.impact.com/brand-api-reference/reference/invoices/invoices",
        "columns": {
            "Id": "Unique identifier for the invoice.",
            "CreatedDate": "When the invoice was created.",
            "MediaId": "Partner (media) id the invoice was issued to.",
            "MediaName": "Partner (media) name the invoice was issued to.",
            "Currency": "ISO 4217 currency code of the invoice.",
            "TotalAmount": "Total invoice amount.",
        },
    },
    "Actions": {
        "description": "Conversion and commission records tracked against your campaigns.",
        "docs_url": "https://integrations.impact.com/brand-api-reference/reference/actions/actions",
        "columns": {
            "Id": "Unique identifier for the action.",
            "CampaignId": "Campaign the action was tracked against.",
            "CampaignName": "Name of the campaign the action was tracked against.",
            "State": "Approval state of the action: PENDING, APPROVED, or REVERSED.",
            "Payout": "Commission payout for the action.",
            "Amount": "Order/transaction amount associated with the action.",
            "Currency": "ISO 4217 currency code of the payout/amount.",
            "EventDate": "When the tracked conversion event occurred.",
            "CreationDate": "When the action record was created.",
            "LockingDate": "When the action's payout was (or will be) locked/finalized.",
            "MediaPartnerId": "Partner credited with the action.",
            "MediaPartnerName": "Name of the partner credited with the action.",
        },
    },
    "ActionUpdates": {
        "description": "The lifecycle history of actions: one row per state change, including when a payout locks and can no longer be reversed.",
        "docs_url": "https://integrations.impact.com/brand-api-reference/reference/actions/action-updates",
        "columns": {
            "Id": "Unique identifier for the action update record.",
            "ActionId": "The action this update belongs to.",
            "CampaignId": "Campaign the action was tracked against.",
            "State": "Approval state at this update: PENDING, APPROVED, or REVERSED.",
            "StateDetail": "Additional state code for this update.",
            "StateDetailDescription": "Plain-text meaning of the state detail.",
            "Disposition": "The change/disposition code for this update.",
            "DeltaPayout": "Change to the action's payout recorded by this update.",
            "DeltaAmount": "Change to the action's sale amount recorded by this update.",
            "Currency": "ISO 4217 currency code of the payout/amount.",
            "ContractId": "Contract the payout terms for this update came from.",
            "ActionDate": "When the underlying action's tracked event occurred.",
            "UpdateDate": "When this update (state change) was recorded.",
            "LockingDate": "Date after which the action can no longer be modified (payout is finalized).",
            "ClearingDate": "When the payout cleared.",
            "MediaPartnerId": "Partner credited with the action.",
        },
    },
    "Contracts": {
        "description": "Partner contracts and their payout terms per campaign — the expected affiliate cost to reconcile against invoices.",
        "docs_url": "https://integrations.impact.com/brand-api-reference/reference/contracts/contracts",
        "columns": {
            "Id": "Unique identifier for the contract.",
            "CampaignId": "Campaign the contract applies to.",
            "PartnerId": "Partner the contract is with.",
            "Status": "Contract status, e.g. ACTIVE or EXPIRED.",
            "StartDate": "When the contract takes effect.",
            "EndDate": "When the contract expires (null if open-ended).",
            "DateCreated": "When the contract was created.",
            "DateLastUpdated": "When the contract was last updated.",
            "TemplateTerms": "Payout terms (EventPayouts, PayoutGroups, Tiers, Rules) currently in effect.",
            "ScheduledTerms": "Payout terms scheduled to take effect in the future.",
            "CampaignTerms": "Campaign-level payout term overrides.",
        },
    },
    "InvoiceLineItems": {
        "description": "Summary invoice line items, one row per campaign/description on an invoice, split out of the Invoices payload.",
        "docs_url": "https://integrations.impact.com/brand-api-reference/reference/invoices/invoices",
        "columns": {
            "InvoiceId": "The invoice this line item belongs to.",
            "LineNumber": "1-based position of the line within its invoice.",
            "CampaignId": "Campaign the line item is for.",
            "CampaignName": "Name of the campaign the line item is for.",
            "Description": "Line item type, e.g. MEDIA_PAYOUT or BONUS.",
            "EventMonthYear": "Month and year (MYYYY) the underlying actions occurred.",
            "Actions": "Number of actions covered by the line item.",
            "NetItemAmount": "Net amount for the line item.",
            "VatItemAmount": "VAT amount for the line item.",
            "TotalItemAmount": "Total amount for the line item.",
            "Status": "Payment status of the line item: PENDING, PAID, or OVERDUE.",
            "DueDate": "When the line item is due.",
            "PaidDate": "When the line item was paid (null if unpaid).",
        },
    },
    "InvoiceDetailedLineItems": {
        "description": "Detailed invoice line items with a program-level breakdown, split out of the Invoices payload.",
        "docs_url": "https://integrations.impact.com/brand-api-reference/reference/invoices/invoices",
        "columns": {
            "InvoiceId": "The invoice this line item belongs to.",
            "LineNumber": "1-based position of the line within its invoice.",
            "AccountId": "Account the line item is attributed to.",
            "Name": "Name associated with the line item.",
            "ProgramId": "Program (campaign) the line item is for.",
            "ProgramName": "Name of the program the line item is for.",
            "EventMonthYear": "Month and year (MYYYY) the underlying actions occurred.",
            "ActionAmount": "Amount from actions for the line item.",
            "OtherAmount": "Other (non-action) amount for the line item.",
            "TotalAmount": "Total amount for the line item.",
        },
    },
}
