from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "audit_logs": {
        "description": "Immutable audit trail of every action taken in the Harvey workspace - logins, admin changes, user activity, and API access.",
        "docs_url": "https://developers.harvey.ai/guides/audit_logs",
        "columns": {
            "id": "Unique identifier for the log entry (UUID).",
            "timestamp": "Date when the event occurred.",
            "type": "Event type identifying the action performed, e.g. auth:login or admin:add_users. New types may be added over time.",
            "user": "Email of the user who triggered the event.",
            "ip": "IP address of the actor.",
            "user_agent": "User agent of the actor who triggered the event.",
            "data": "Optional metadata for certain event types, JSON-encoded.",
        },
    },
    "usage_history": {
        "description": "Usage events describing how users interact with Harvey - product surface, action, client matter attribution - without prompt or response text.",
        "docs_url": "https://developers.harvey.ai/guides/usage_history",
        "columns": {
            "unique_usage_id": "Unique identifier for the usage event (UUID).",
            "utc_time": "Time the event occurred, in UTC.",
            "user": "Email of the user who performed the action.",
            "action": "Action performed, e.g. CREATE.",
            "access_point": "Where the action originated, e.g. WEB.",
            "product_surface_area": "Harvey product surface used, e.g. ASSISTANT, VAULT, PLAYBOOK, WORKFLOW, WORD, OUTLOOK, DRAFT.",
            "subsurface": "More specific surface within the product area, e.g. ASSISTANT_THREAD, REVIEW_TABLE.",
            "cm_id": "Client matter number the event is attributed to.",
            "parent_thread_id": "Identifier of the parent assistant thread, when applicable.",
            "source": "Source of the event.",
            "space_name": "Name of the shared space involved, when applicable.",
            "playbook_name": "Name of the playbook used, when applicable.",
            "review_table_name": "Name of the Vault review table involved, when applicable.",
            "vault_project_name": "Name of the Vault project involved, when applicable.",
            "workflow_name": "Name of the workflow used, when applicable.",
            "metadata": "Event-type-specific metadata (e.g. num_columns, num_files), JSON-encoded.",
        },
    },
    "query_history": {
        "description": "Query events including the full prompt and response text, feedback, and a deep link into Harvey, alongside the usage attribution fields.",
        "docs_url": "https://developers.harvey.ai/guides/usage_history",
        "columns": {
            "unique_usage_id": "Unique identifier for the query event (UUID).",
            "utc_time": "Time the event occurred, in UTC.",
            "user": "Email of the user who performed the action.",
            "query": "Full prompt text submitted by the user.",
            "response": "Full response text returned by Harvey. May be 'NA' for some event types.",
            "link": "Direct URL to the query within Harvey.",
            "feedback_comments": "Free-text feedback the user left on the response, when any.",
            "feedback_sentiments": "Feedback sentiment the user left on the response, when any.",
            "action": "Action performed, e.g. CREATE.",
            "access_point": "Where the action originated, e.g. WEB.",
            "product_surface_area": "Harvey product surface used, e.g. ASSISTANT, VAULT, PLAYBOOK, WORKFLOW, WORD, OUTLOOK, DRAFT.",
            "subsurface": "More specific surface within the product area, e.g. ASSISTANT_THREAD, REVIEW_TABLE.",
            "cm_id": "Client matter number the event is attributed to.",
            "parent_thread_id": "Identifier of the parent assistant thread, when applicable.",
            "source": "Source of the event.",
            "space_name": "Name of the shared space involved, when applicable.",
            "playbook_name": "Name of the playbook used, when applicable.",
            "review_table_name": "Name of the Vault review table involved, when applicable.",
            "vault_project_name": "Name of the Vault project involved, when applicable.",
            "workflow_name": "Name of the workflow used, when applicable.",
            "metadata": "Event-type-specific metadata, JSON-encoded.",
        },
    },
    "client_matters": {
        "description": "All client matters in the workspace (including deleted ones) with usage statistics.",
        "docs_url": "https://developers.harvey.ai/guides/client_matters",
        "columns": {
            "id": "Unique identifier for the client matter (UUID).",
            "name": "Client matter number, e.g. 1234-5678.",
            "description": "Description of the client matter.",
            "user_email": "Email of the user who created the client matter.",
            "user_count": "Count of unique users associated with the client matter.",
            "total_events": "Count of queries associated with the client matter.",
            "created_at": "When the client matter was created.",
            "deleted_at": "When the client matter was deleted, if it has been.",
        },
    },
    "vault_projects": {
        "description": "Vault projects and knowledge bases in the workspace, with file counts, sizes, and sharing details.",
        "docs_url": "https://developers.harvey.ai/guides/vault",
        "columns": {
            "id": "Unique identifier for the project (UUID).",
            "name": "Name of the project.",
            "client_matter_id": "Client matter the project is attached to, when any (UUID).",
            "created_at": "When the project was created.",
            "updated_at": "When the project's metadata was last updated.",
            "project_updated_at": "When the project's content was last updated.",
            "project_retained_at": "Retention timestamp for the project, when set.",
            "creator_email": "Email of the user who created the project.",
            "is_knowledge_base_project": "Whether the project is designated as a knowledge base.",
            "files_count": "Number of files in the project.",
            "size_bytes": "Total size of the project's files in bytes.",
            "query_count": "Number of queries run against the project.",
            "sharing": "User and workspace sharing details, JSON-encoded.",
        },
    },
}
