from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

_API_REFERENCE = "https://docs.fourthwall.com/api-reference/platform"

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "orders": {
        "description": "A paid order placed in the shop, with its line items, amounts and fulfillment status.",
        "docs_url": f"{_API_REFERENCE}/orders/list-orders",
        "columns": {
            "id": "Unique identifier of the order.",
            "shopId": "Identifier of the shop the order belongs to.",
            "friendlyId": "Human-readable order number shown to the supporter.",
            "checkoutId": "Identifier of the checkout the order was created from.",
            "promotionId": "Identifier of the promotion applied to the order, if any.",
            "status": "Fulfillment state: CONFIRMED, PARTIALLY_IN_PRODUCTION, IN_PRODUCTION, PARTIALLY_SHIPPED, SHIPPED, PARTIALLY_DELIVERED, DELIVERED, CANCELLED or COMPLETED.",
            "email": "Email address of the supporter who placed the order.",
            "emailMarketingOptIn": "Whether the supporter opted in to marketing emails at checkout.",
            "username": "Display name of the supporter who placed the order.",
            "message": "Message the supporter left with the order.",
            "amounts": "Order totals: subtotal, shipping, tax, donation, discount, total and any gift cards.",
            "billing": "Billing address supplied at checkout.",
            "shipping": "Shipping address supplied at checkout.",
            "offers": "Products bought in this order, each with the purchased variant and quantity.",
            "source": "How the order was created: ORDER, SAMPLES_ORDER, GIVEAWAY_LINKS or TWITCH_GIFT_REDEMPTION.",
            "trackingParams": "Marketing attribution captured at checkout (utm_source, utm_medium, utm_campaign, utm_content, utm_term, fbc, fbp).",
            "metadata": "Custom key-value pairs attached when the cart was created.",
            "createdAt": "When the order was placed.",
            "updatedAt": "When the order was last changed.",
        },
    },
    "products": {
        "description": "A product (offer) in the shop, with its variants, pricing, images and availability.",
        "docs_url": f"{_API_REFERENCE}/products/list-products",
        "columns": {
            "id": "Unique identifier of the product.",
            "name": "Product name.",
            "slug": "URL slug of the product in the storefront.",
            "description": "Product description.",
            "type": "Product type: STANDARD, GIFT_CARD or UNKNOWN.",
            "state": "Stock state of the product: available or sold out.",
            "access": "Storefront visibility: public, hidden, private or archived.",
            "thumbnailImage": "Primary image shown in listings.",
            "images": "All images attached to the product.",
            "variants": "Purchasable variants, each with its own SKU, price, colour and size.",
            "additionalInformation": "Extra product details shown on the product page.",
            "sizeGuide": "Size guide attached to the product.",
            "digitalFiles": "Files delivered to the buyer. Only present for digital products.",
            "createdAt": "When the product was created.",
            "updatedAt": "When the product was last changed.",
        },
    },
    "collections": {
        "description": "A storefront collection grouping products together.",
        "docs_url": f"{_API_REFERENCE}/collections/list-collections",
        "columns": {
            "id": "Unique identifier of the collection.",
            "shopId": "Identifier of the shop the collection belongs to.",
            "name": "Collection name.",
            "slug": "URL slug of the collection in the storefront.",
            "description": "Collection description.",
            "available": "Whether the collection is currently available in the storefront.",
            "state": "Storefront visibility: PUBLIC, HIDDEN, PRIVATE or ARCHIVED.",
        },
    },
    "donations": {
        "description": "A tip or donation made to the shop.",
        "docs_url": f"{_API_REFERENCE}/donations/list-donations",
        "columns": {
            "id": "Unique identifier of the donation.",
            "shopId": "Identifier of the shop that received the donation.",
            "status": "Donation state: OPEN, COMPLETED, ABANDONED, CANCELLED or FAILED.",
            "email": "Email address of the donor.",
            "username": "Display name of the donor.",
            "message": "Message the donor left with the donation.",
            "amounts": "Donation total, as a value and currency.",
            "createdAt": "When the donation was made.",
            "updatedAt": "When the donation was last changed.",
        },
    },
    "members": {
        "description": "A membership supporter of the shop and the state of their subscription.",
        "docs_url": f"{_API_REFERENCE}/memberships/list-members",
        "columns": {
            "id": "Unique identifier of the member.",
            "email": "Email address of the member.",
            "nickname": "Display name of the member.",
            "createdAt": "When the member joined.",
            "subscription": "Current subscription state (ACTIVE, CANCELLED, SUSPENDED or NONE) with the tier variant, billing interval and amount.",
        },
    },
    "membership_tiers": {
        "description": "A membership tier offered by the shop, with its monthly and annual variants.",
        "docs_url": f"{_API_REFERENCE}/memberships/list-tiers",
        "columns": {
            "id": "Unique identifier of the tier.",
            "name": "Tier name.",
            "imageUrl": "Image shown for the tier.",
            "variants": "Purchasable variants of the tier, each with its billing interval (MONTHLY or ANNUAL) and price.",
        },
    },
    "promotions": {
        "description": "A discount promotion configured for the shop or for memberships.",
        "docs_url": f"{_API_REFERENCE}/promotions/list-promotions",
        "columns": {
            "id": "Unique identifier of the promotion.",
            "type": "Promotion kind: SHOP_SINGLE, SHOP_MULTI, SHOP_AUTO_APPLYING, MEMBERSHIPS_SINGLE or MEMBERSHIPS_MULTI.",
            "title": "Internal name of the promotion.",
            "code": "Discount code supporters enter at checkout. Single-code promotions only.",
            "codes": "Discount codes generated for the promotion. Multi-code promotions only.",
            "discount": "The discount the promotion applies.",
            "appliesTo": "What the discount applies to, for example the entire order or selected products.",
            "requirements": "Conditions a cart must meet before the promotion applies.",
            "limits": "Usage limits configured on the promotion.",
            "usageCount": "How many times the promotion has been redeemed.",
            "status": "Whether the promotion is live, ended, archived or fully used.",
        },
    },
    "mailing_list_entries": {
        "description": "An email address subscribed to the shop's mailing list.",
        "docs_url": f"{_API_REFERENCE}/mailing-lists/list-entries",
        "columns": {
            "id": "Unique identifier of the mailing list entry.",
            "email": "Subscribed email address.",
        },
    },
}
