from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "categories": {
        "description": "A category groups related topics together, e.g. Support, Feature Requests, or Announcements.",
        "docs_url": "https://docs.discourse.org/#tag/Categories/operation/listCategories",
        "columns": {
            "id": "Unique identifier for the category.",
            "name": "Display name of the category.",
            "slug": "URL-safe identifier for the category.",
            "color": "Hex color used for the category badge.",
            "text_color": "Hex color used for text on the category badge.",
            "description": "HTML description of the category shown on the category page.",
            "description_text": "Plain-text version of the category description.",
            "topic_count": "Number of topics currently in the category.",
            "post_count": "Number of posts currently in the category.",
            "position": "Display order of the category relative to its siblings.",
            "parent_category_id": "id of the parent category, if this is a subcategory.",
            "read_restricted": "Whether the category is only visible to specific groups.",
            "topic_url": 'Path to the category\'s pinned "about this category" topic.',
        },
    },
    "topics": {
        "description": "A discussion thread. Returned from the site's latest-activity topic list, so it covers every topic that has had activity.",
        "docs_url": "https://docs.discourse.org/#tag/Topics/operation/listLatestTopics",
        "columns": {
            "id": "Unique identifier for the topic.",
            "title": "Topic title.",
            "fancy_title": "Title with Markdown/emoji rendered to HTML entities.",
            "slug": "URL-safe identifier for the topic.",
            "posts_count": "Number of posts (replies + original post) in the topic.",
            "reply_count": "Number of replies to the original post.",
            "highest_post_number": "Post number of the most recent post in the topic.",
            "created_at": "When the topic was created.",
            "last_posted_at": "When the most recent post in the topic was made.",
            "bumped_at": "When the topic was last bumped to the top of its list.",
            "archetype": 'Topic type, e.g. "regular" or "private_message".',
            "pinned": "Whether the topic is pinned within its category.",
            "pinned_globally": "Whether the topic is pinned across the whole site.",
            "visible": "Whether the topic is visible (unlisted topics are hidden from lists).",
            "closed": "Whether new replies are disallowed.",
            "archived": "Whether the topic has been archived (read-only).",
            "views": "Number of times the topic has been viewed.",
            "like_count": "Total number of likes across all posts in the topic.",
            "category_id": "id of the category this topic belongs to.",
            "last_poster_username": "Username of the most recent poster.",
        },
    },
    "posts": {
        "description": "A single post (the original post or a reply) within a topic, from the site-wide post stream.",
        "docs_url": "https://docs.discourse.org/#tag/Posts/operation/listPosts",
        "columns": {
            "id": "Unique identifier for the post.",
            "topic_id": "id of the topic this post belongs to.",
            "topic_slug": "URL-safe identifier of the parent topic.",
            "topic_title": "Title of the parent topic at fetch time.",
            "post_number": "1-based position of the post within its topic.",
            "user_id": "id of the user who authored the post.",
            "username": "Username of the post's author.",
            "cooked": "Rendered HTML body of the post.",
            "raw": "Raw Markdown source of the post body, when available.",
            "created_at": "When the post was created.",
            "updated_at": "When the post was last edited.",
            "reply_count": "Number of direct replies to this post.",
            "reply_to_post_number": "Post number this post is a direct reply to, if any.",
            "category_id": "id of the category the parent topic belongs to.",
            "like_count": "Number of likes this post has received (also under actions_summary).",
            "hidden": "Whether the post has been hidden (e.g. by flags).",
            "deleted_at": "When the post was deleted, if applicable.",
            "wiki": "Whether the post is editable by any trusted user (a wiki post).",
        },
    },
    "tags": {
        "description": "A tag that can be applied to topics to aid discovery and filtering.",
        "docs_url": "https://docs.discourse.org/#tag/Tags/operation/listTags",
        "columns": {
            "id": "Unique identifier for the tag.",
            "name": "Tag name as it appears on topics.",
            "text": "Display text of the tag (usually equal to name).",
            "description": "Optional description of what the tag means.",
            "count": "Number of topics currently carrying this tag.",
            "pm_only": "Whether the tag can only be applied to personal messages.",
            "target_tag": "The canonical tag this tag is a synonym for, if any.",
        },
    },
    "groups": {
        "description": "A user group, used for permissions, mentions, and messaging.",
        "docs_url": "https://docs.discourse.org/#tag/Groups/operation/listGroups",
        "columns": {
            "id": "Unique identifier for the group.",
            "name": "Internal group name (used in @mentions and URLs).",
            "full_name": "Human-readable display name of the group.",
            "user_count": "Number of members in the group.",
            "automatic": "Whether the group is system-managed (e.g. Trust Level groups) rather than user-created.",
            "visibility_level": "Who can see the group: 0 public, 1 logged-in users, 2 members/owners, 3 staff.",
            "public_admission": "Whether users can join the group without approval.",
            "public_exit": "Whether users can leave the group without approval.",
            "bio_cooked": "Rendered HTML of the group's bio/description.",
        },
    },
    "users": {
        "description": "A forum member and their aggregate activity stats, from the public user directory leaderboard.",
        "docs_url": "https://docs.discourse.org/#tag/Users/operation/listUserDirectoryItems",
        "columns": {
            "id": "Unique identifier for the user.",
            "username": "The user's unique username.",
            "name": "The user's display name.",
            "admin": "Whether the user has admin (staff) access.",
            "trust_level": "Discourse trust level, 0 (new) through 4 (leader).",
            "title": "The user's custom title, if any (often granted by a group).",
            "likes_received": "Total number of likes this user's posts have received.",
            "likes_given": "Total number of likes this user has given to other posts.",
            "topic_count": "Number of topics this user has created.",
            "post_count": "Number of posts this user has made.",
            "topics_entered": "Number of distinct topics this user has viewed.",
            "posts_read": "Number of posts this user has read.",
            "days_visited": "Number of distinct days this user has visited the forum.",
            "solutions": "Number of accepted-answer posts this user has authored.",
            "time_read": "Total time (in seconds) this user has spent reading.",
        },
    },
    "group_members": {
        "description": "One row per user in a group, linking the groups table to the users who belong to it. Group owners are included.",
        "docs_url": "https://docs.discourse.org/#tag/Groups/operation/listGroupMembers",
        "columns": {
            "id": "id of the member user.",
            "group_id": "id of the group the membership belongs to.",
            "group_name": "Internal name of the group the membership belongs to.",
            "username": "The member's unique username.",
            "name": "The member's display name.",
            "title": "The member's custom title, if any.",
            "added_at": "When the user was added to the group.",
            "last_posted_at": "When the member last posted anywhere on the forum.",
            "last_seen_at": "When the member was last seen on the forum.",
            "timezone": "The member's configured timezone.",
        },
    },
    "admin_users": {
        "description": "The full member list from the admin API, including accounts the public user directory leaves out. Email addresses are not synced.",
        "docs_url": "https://docs.discourse.org/#tag/Users/operation/adminListUsers",
        "columns": {
            "id": "Unique identifier for the user.",
            "username": "The user's unique username.",
            "name": "The user's display name.",
            "active": "Whether the account has been activated.",
            "admin": "Whether the user has admin access.",
            "moderator": "Whether the user has moderator access.",
            "staged": "Whether the account was created by Discourse on the user's behalf (e.g. from an inbound email) and has never been claimed.",
            "created_at": "When the account was created.",
            "last_seen_at": "When the user was last seen on the forum.",
            "last_emailed_at": "When Discourse last sent the user an email.",
            "trust_level": "Discourse trust level, 0 (new) through 4 (leader).",
            "manual_locked_trust_level": "Trust level an admin has pinned the user to, if any.",
            "title": "The user's custom title, if any.",
            "time_read": "Total time (in seconds) the user has spent reading.",
            "days_visited": "Number of distinct days the user has visited the forum.",
            "posts_read_count": "Number of posts the user has read.",
            "topics_entered": "Number of distinct topics the user has viewed.",
            "post_count": "Number of posts the user has made.",
        },
    },
    "user_actions": {
        "description": "One row per public action in a member's activity stream: likes given and received, new topics, replies, mentions, quotes and edits. Actions inside private message topics are excluded, and post text is not synced. Post bodies live in the posts table.",
        "docs_url": "https://docs.discourse.org/#tag/Users/operation/listUserActions",
        "columns": {
            "action_type": "What the action was: 1 like, 2 was liked, 4 new topic, 5 reply, 6 response, 7 mention, 9 quote, 11 edit.",
            "created_at": "When the action happened.",
            "target_user_id": "id of the user whose activity stream this row belongs to.",
            "target_username": "Username of the user whose activity stream this row belongs to.",
            "target_name": "Display name of the user whose activity stream this row belongs to.",
            "acting_user_id": "id of the user who performed the action.",
            "acting_username": "Username of the user who performed the action.",
            "acting_name": "Display name of the user who performed the action.",
            "user_id": "id of the user who wrote the post or topic the action was aimed at.",
            "username": "Username of the user who wrote the post or topic the action was aimed at.",
            "name": "Display name of the user who wrote the post or topic the action was aimed at.",
            "topic_id": "id of the topic the action was aimed at.",
            "title": "Title of that topic.",
            "slug": "URL-safe identifier of that topic.",
            "category_id": "id of the category that topic belongs to.",
            "post_number": "Position within the topic of the post the action was aimed at. 1 when the action targets the topic itself.",
            "post_id": "id of the post the action was aimed at, when the action targets a post.",
            "reply_to_post_number": "Post number this post replies to. Only set on reply actions.",
            "action_code": "Small-action code for posts that record an event (e.g. a topic being closed) rather than content.",
            "post_type": "Type of the target post: regular, moderator action, small action, or whisper.",
            "deleted": "Whether the target post or topic has been deleted.",
            "hidden": "Whether the target post has been hidden.",
            "closed": "Whether the target topic is closed to new replies.",
            "archived": "Whether the target topic has been archived.",
        },
    },
    "badges": {
        "description": "A badge that can be granted to members, used to resolve the badge IDs carried on user badge grants.",
        "docs_url": "https://docs.discourse.org/#tag/Badges/operation/adminListBadges",
        "columns": {
            "id": "Unique identifier for the badge.",
            "name": "Display name of the badge.",
            "slug": "URL-safe identifier for the badge.",
            "description": "Short description of what the badge is for.",
            "long_description": "Full description shown on the badge page.",
            "grant_count": "Number of times the badge has been granted.",
            "badge_type_id": "id of the badge type, which sets the badge's colour (gold, silver, bronze).",
            "badge_grouping_id": "id of the group the badge is listed under on the badges page.",
            "enabled": "Whether the badge is currently being granted.",
            "listable": "Whether the badge appears on the public badges page.",
            "system": "Whether the badge ships with Discourse rather than being created by an admin.",
            "manually_grantable": "Whether staff can grant the badge by hand.",
            "multiple_grant": "Whether one user can hold the badge more than once.",
            "allow_title": "Whether holders can use the badge name as their title.",
            "auto_revoke": "Whether Discourse revokes the badge when its conditions stop holding.",
            "target_posts": "Whether the badge is granted against a specific post.",
            "show_posts": "Whether the granting post is shown on the badge page.",
            "icon": "Font Awesome icon shown for the badge.",
            "image_url": "URL of the custom image shown for the badge, if one is set.",
            "trigger": "Event that makes Discourse re-evaluate the badge query.",
            "query": "SQL query that decides who the badge is granted to, for custom badges.",
        },
    },
}
