from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Table and column descriptions sourced from the official Secureframe API reference
# (https://developer.secureframe.com/).
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "controls": {
        "description": "A security control the company maintains to satisfy framework requirements, with aggregated test-health counts.",
        "docs_url": "https://developer.secureframe.com/",
        "columns": {
            "id": "The identifier for this control.",
            "at_risk_test_count": "The number of associated tests currently at risk of failing.",
            "author_name": "The name of the author if custom, Secureframe otherwise.",
            "created_at": "The date the control was created.",
            "custom": "True if the control is custom, false if it's Secureframe-authored.",
            "description": "The control description.",
            "disabled_justification": "The reason the control was disabled if applicable.",
            "disabled_test_count": "The number of associated tests that are disabled.",
            "enabled": "True if the control is currently enabled.",
            "failing_test_count": "The number of associated tests currently failing.",
            "first_failed_at": "The date the control first failed.",
            "framework_ids": "The IDs of the frameworks that the control is associated with.",
            "framework_keys": "The keys of the frameworks that the control is associated with.",
            "framework_requirement_keys": "The keys of the framework requirements that the control is associated with.",
            "health_status": "The overall health of the control.",
            "implementation_date": "The date when the control is/was to be implemented.",
            "implementation_status": "The current implementation status of the control.",
            "key": "The user-friendly identifier used to reference this control.",
            "name": "The control name.",
            "owner_assigned_at": "The date the control was assigned to its current owner.",
            "owner_name": "The control owner's name.",
            "passing_test_count": "The number of associated tests currently passing.",
            "updated_at": "The date when the control was last updated.",
        },
    },
    "tests": {
        "description": "A compliance test that continuously evaluates a control, with pass/fail health status and evidence timing.",
        "docs_url": "https://developer.secureframe.com/",
        "columns": {
            "id": "The identifier for this test.",
            "control_ids": "The IDs of the controls that the test is associated with.",
            "control_keys": "The keys of the controls that the test is associated with.",
            "created_at": "The date when this test was created.",
            "custom": "True if the test is custom (user generated), false if it's Secureframe-authored.",
            "description": "The description for the test.",
            "detailed_remediation_steps": "Guidance for remediating this test in the event it fails.",
            "disabled_justification": "Reason for disabling the test.",
            "enabled": "True if the test is currently enabled.",
            "enabled_field_updated_by_user_name": "The name of the user who enabled the test, null if wasn't enabled by a user.",
            "failure_message": "The message to be displayed if the test fails.",
            "first_failed_at": "The date the test first failed.",
            "framework_ids": "The IDs of the frameworks that the test is associated with.",
            "framework_keys": "The keys of the frameworks that the test is associated with.",
            "health_status": "The overall health of the test.",
            "key": "The user-friendly identifier used to reference this test.",
            "last_evaluated": "The date the test was last evaluated at.",
            "last_passed_at": "The date the test last had a passing evaluation.",
            "next_due_date": "The date new test evidence is needed by if applicable.",
            "owner_assigned_at": "The date the test owner was assigned.",
            "owner_name": "The test owner's name.",
            "pass": "True if the test is passing, false otherwise.",
            "passed_with_upload": "True if the test passed from the existance of an upload, false otherwise.",
            "passed_with_upload_justification": "The justification used on evidence upload to pass the test if applicable.",
            "promote_at": "The current date set for implementation of the test.",
            "promoted_by_name": "The name of the user who set the implementation date.",
            "recommended_action": "Actions for completing the test.",
            "required_implementation_date": "The pre-configured date the test must be implemented by.",
            "resource_category": "The category the test resource belongs to.",
            "test_domain": "The domain the test belongs to.",
            "test_function": "The purpose of the test.",
            "test_interval_seconds": "The interval in which test evidence should be collected if applicable.",
            "test_type": "The type of test.",
            "title": "The test title.",
            "tolerance_window_seconds": "The time between the test interval elapsing and evidence becoming stale and test failing if applicable.",
            "updated_at": "The date the test was last updated.",
            "vendor_name": "The vendor name associated with the test if applicable.",
        },
    },
    "users": {
        "description": "A person (employee, contractor, or other personnel) tracked for compliance, onboarding, and audit scope.",
        "docs_url": "https://developer.secureframe.com/",
        "columns": {
            "id": "The identifier for this user.",
            "access_role": "The user's access role in the system.",
            "active": "True if the user's account is active, false if it has been deactivated.",
            "active_source": "The integration the active status was sourced from.",
            "created_at": "The date when this user account was created.",
            "department_id": "The identifier of the department the user belongs to.",
            "email": "The user's email.",
            "employee_type": "The type of employee (contractor, employee, non-employee etc).",
            "end_date": "The date of the user's termination if applicable.",
            "first_name": "The user's first name.",
            "image_url": "The user's icon image URL.",
            "in_audit_scope": "True if this user is in scope for being audited, false if they are exempt.",
            "invited": "True if an invitation to Secureframe has been sent to the user's email, false otherwise.",
            "invited_at": "The date the user was invited.",
            "last_name": "The user's last name.",
            "manager_name": "The name of the user's manager if applicable, null otherwise.",
            "middle_name": "The user's middle name.",
            "name": "The first and last name of the user separated by a space.",
            "onboarding_status": "The current onboarding status of the user.",
            "personnel_status": "The current personnel status of the user.",
            "preferred_first_name": "The user's preferred first name if applicable, null otherwise.",
            "role": "The user's role at the company.",
            "secureframe_agent_acknowledged_at": "The date the user completed installation of the Secureframe device agent.",
            "start_date": "The date the user started employment at the company.",
            "title": "The user's job title.",
            "updated_at": "The date this user account was last updated.",
        },
    },
    "user_accounts": {
        "description": "An account discovered on a connected vendor (e.g. a SaaS login), optionally linked to a Secureframe user.",
        "docs_url": "https://developer.secureframe.com/",
        "columns": {
            "id": "The identifier for this UserAccount.",
            "active": "Flag to indicate if this is an active user account on the vendor side. Defaults to true if the vendor does not support or provide this value.",
            "created_at": "The date this UserAccount was created.",
            "email": "The email received from the connection.",
            "first_name": "The first name of the user received from the connection.",
            "has_user": "Flag to indicate if this UserAccount has a User. False indicates that it's an unlinked account.",
            "last_name": "The last name of the user received from the connection.",
            "third_party_id": "The identifier for this UserAccount on the vendor side.",
            "username": "The user name of the UserAccount on the vendor side.",
            "vendor_name": "The name of the vendor that this UserAccount is from.",
            "updated_at": "The date this UserAccount was last updated.",
        },
    },
    "devices": {
        "description": "A managed device reporting security posture such as disk encryption, firewall, and antivirus status.",
        "docs_url": "https://developer.secureframe.com/",
        "columns": {
            "id": "The identifier for this Device.",
            "created_at": "The date this Device object was created.",
            "cpu": "The cpu info available for this Device.",
            "device_name": "The name of the Device.",
            "hard_drive_encrypted": "Flag to indicate if the hard drive is encrypted.",
            "in_audit_scope": "Flag to indicate if this Device is in scope.",
            "last_checkin_at": "The date this Device last checked in.",
            "local_firewall_enabled": "Flag to indicate if the local firewall is enabled.",
            "mac_address": "The MAC address of the Device.",
            "make": "The make of the Device.",
            "memory": "The memory of the Device.",
            "model": "The model of the Device.",
            "native_anti_virus_enabled": "Flag to indicate if the native antivirus is enabled.",
            "os": "The operating system of the Device.",
            "out_of_audit_scope_reason": "Out of scope reason if the Device is not in scope.",
            "password_enforcement_enabled": "Flag to indicate if password enforcement is enabled.",
            "remote_ip": "The remote IP of the Device.",
            "serial_number": "The serial number of the Device.",
            "session_timeout_enabled": "Flag to indicate if session timeout is enabled.",
            "updated_at": "The date this Device was last updated.",
        },
    },
    "vendors": {
        "description": "A third-party vendor tracked in the legacy vendor register, with risk and review metadata.",
        "docs_url": "https://developer.secureframe.com/",
        "columns": {
            "id": "The identifier for this Vendor.",
            "archived": "Flag to indicate if this Vendor is archived.",
            "archived_at": "The date this Vendor was archived (if it is archived).",
            "archived_by": "The identifier of the User that archived this Vendor (if it is archived).",
            "audit_scopes": "The audit scopes for this Vendor.",
            "authentication_type": "The authentication type for this Vendor.",
            "data_collected": "The data collected for this Vendor.",
            "date_of_engagement": "The date of engagement for this Vendor.",
            "domain": "The domain of the Vendor.",
            "environment_types": "The environment types for this Vendor.",
            "last_reviewed_at": "The date this Vendor was last reviewed.",
            "name": "The name of the Vendor.",
            "operational_reliance": "The operational reliance for this Vendor.",
            "other_information": "Other information for this Vendor.",
            "owner_id": "The identifier of the User that is the owner for this Vendor.",
            "risk_level": "The risk level for this Vendor.",
            "security_url": "The security URL for this Vendor.",
            "services": "The services provided by this Vendor.",
            "terminated_at": "The date this Vendor was terminated (if it is archived).",
            "third_party_audit_report_concerns": "The third party audit report concerns for this Vendor.",
            "two_factor_enabled": "Flag to indicate if two factor is enabled for this Vendor.",
            "updated_at": "The date this Vendor was last updated.",
        },
    },
    "tprm_vendors": {
        "description": "A vendor tracked in Third Party Risk Management, with risk level, status, and subassessment responses.",
        "docs_url": "https://developer.secureframe.com/",
        "columns": {
            "id": "The identifier for this Vendor.",
            "archived": "Flag to indicate if this Vendor is archived.",
            "archived_at": "The date this Vendor was archived.",
            "authentication_type": "The authentication type for this Vendor.",
            "created_at": "The date this Vendor was created.",
            "data_collected": "The data collected for this Vendor.",
            "environment_types": "The environments for this Vendor.",
            "last_reviewed_at": "The date this Vendor was last reviewed.",
            "name": "The name of the Vendor.",
            "other_information": "Other information for this Vendor.",
            "owner_id": "The identifier of the User that is the owner for this Vendor.",
            "risk_level": "The risk level for this Vendor.",
            "security_url": "The security URL for this Vendor.",
            "services_provided": "The services provided by this Vendor.",
            "third_party_audit_report_concerns": "The third party audit report concerns for this Vendor.",
            "two_factor_enabled": "Flag to indicate if two factor is enabled for this Vendor.",
            "updated_at": "The date this Vendor was last updated.",
            "vendor_status": "The status of the Vendor.",
            "vendor_risk_subassessment_responses": "The assesments for each risk subcategory.",
            "website": "The website of the Vendor.",
        },
    },
    "frameworks": {
        "description": "A compliance framework (e.g. SOC 2, ISO 27001) with aggregate control and test counts.",
        "docs_url": "https://developer.secureframe.com/",
        "columns": {
            "id": "The identifier for this Framework.",
            "applicable_controls_count": "The number of applicable controls for this Framework.",
            "applicable_framework_requirements_count": "The number of applicable framework requirements for this Framework.",
            "at_risk_test_count": "The number of at risk tests for this Framework.",
            "created_at": "The date this Framework was created.",
            "description": "The description of the Framework.",
            "discarded_at": "The date this Framework was discarded.",
            "disabled_test_count": "The number of non-applicable tests for this Framework.",
            "failing_test_count": "The number of failing tests for this Framework.",
            "key": "The key of the Framework.",
            "title": "The title of the Framework.",
            "passing_test_count": "The number of passing tests for this Framework.",
            "updated_at": "The date this CompanyVendorConnection was updated.",
        },
    },
    "framework_requirements": {
        "description": "A single requirement within a compliance framework and its overall health.",
        "docs_url": "https://developer.secureframe.com/",
        "columns": {
            "id": "The identifier for this Framework Requirement.",
            "company_id": "The identifier for the Company.",
            "created_at": "The date this Framework Requirement was created.",
            "description": "The description of the Framework Requirement.",
            "enabled": "Whether this Framework Requirement is enabled.",
            "health_status": "The overall health of the Framework Requirement.",
            "key": "The key of the Framework Requirement.",
            "name": "The name of the Framework Requirement.",
            "updated_at": "The date this Framework Requirement was updated.",
        },
    },
    "risks": {
        "description": "A risk register entry with impact, likelihood, treatment, and ownership details.",
        "docs_url": "https://developer.secureframe.com/",
        "columns": {
            "id": "The identifier for this CompanyRisk.",
            "annualized_rate_of_occurrence": "The annualized rate of occurrence for this CompanyRisk.",
            "asset_value": "The asset value for this CompanyRisk.",
            "categories": "The categories for this CompanyRisk.",
            "cia": "The CIA for this CompanyRisk.",
            "departments": "The departments for this CompanyRisk.",
            "description": "The description for this CompanyRisk.",
            "exposure_factor": "The exposure factor for this CompanyRisk.",
            "impact_justification": "The impact justification for this CompanyRisk.",
            "likelihood_justification": "The likelihood justification for this CompanyRisk.",
            "notes": "The notes for this CompanyRisk.",
            "reference_url": "The reference URL for this CompanyRisk.",
            "related_tickets": "The related tickets for this CompanyRisk.",
            "reported_by": "The reported by for this CompanyRisk.",
            "residual_impact_justification": "The residual impact justification for this CompanyRisk.",
            "residual_likelihood_justification": "The residual likelihood justification for this CompanyRisk.",
            "responsible_team": "The responsible team for this CompanyRisk.",
            "source": "The source for this CompanyRisk.",
            "status": "The status for this CompanyRisk.",
            "treatment": "The treatment for this CompanyRisk.",
            "treatment_decision_notes": "The treatment decision notes for this CompanyRisk.",
            "uncertainty": "The uncertainty for this CompanyRisk.",
            "created_at": "The date this CompanyRisk was created.",
            "updated_at": "The date this CompanyRisk was updated.",
            "company_id": "The identifier for the company for this CompanyRisk.",
            "owner_id": "The identifier for the owner for this CompanyRisk.",
            "custom_risk_id": "The custom risk ID for this CompanyRisk.",
        },
    },
    "repositories": {
        "description": "A source-code repository discovered from a connected vendor, with audit-scope status.",
        "docs_url": "https://developer.secureframe.com/",
        "columns": {
            "id": "The identifier for this Repository.",
            "created_at": "The date this Repository object was created.",
            "name": "The name of the Repository.",
            "in_audit_scope": "Flag to indicate if this Repository is in scope.",
            "out_of_audit_scope_reason": "Out of scope reason if the repository is not in scope.",
            "private": "Flag to indicate if this Repository is private.",
            "third_party_id": "The identifier for this Repository on the vendor side.",
            "vendor_name": "The name of the vendor that this Repository is from.",
            "updated_at": "The date this Repository was last updated.",
        },
    },
    "integration_connections": {
        "description": "A connection to an integrated vendor and its current sync status.",
        "docs_url": "https://developer.secureframe.com/",
        "columns": {
            "id": "The identifier for this IntegrationConnection.",
            "name": "The name of the IntegrationConnection if applicable.",
            "status": "The status of the IntegrationConnection.",
            "vendor_name": "The name of the vendor for this IntegrationConnection.",
            "updated_at": "The date this IntegrationConnection was last updated.",
        },
    },
    "cloud_resources": {
        "description": "A cloud infrastructure resource discovered from a connected vendor, with audit-scope status.",
        "docs_url": "https://developer.secureframe.com/",
        "columns": {
            "id": "The identifier for this CloudResource.",
            "cloud_resource_type": "The type of this CloudResource.",
            "created_at": "The date this CloudResource was created.",
            "in_audit_scope": "Flag to indicate if this CloudResource is in scope.",
            "out_of_audit_scope_reason": "Out of scope reason if the repository is not in scope.",
            "region": "The region this CloudResource belongs to.",
            "tags": "The tags for this CloudResource.",
            "third_party_id": "The identifier for this CloudResource on the vendor side.",
            "vendor_name": "The name of the vendor that this CloudResource is from.",
            "updated_at": "The date this CloudResource was last updated.",
        },
    },
}
