from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

_DOCS_URL = (
    "https://support.gainsight.com/PX/API_for_Developers/02Usage_of_Different_APIs/Work_with_the_Gainsight_PX_REST_API"
)

# Descriptions curated from the Gainsight PX REST API docs. Date fields are returned by the API as
# epoch-millisecond integers and normalized to timestamps before loading.
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "accounts": {
        "description": "Companies (accounts) tracked in Gainsight PX, aggregating the users that belong to them.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Unique account identifier.",
            "name": "Account (company) name.",
            "trackedSubscriptionId": "Subscription identifier the account is tracked under.",
            "sfdcId": "Salesforce account identifier, when linked.",
            "gsId": "Gainsight CS company identifier, when linked.",
            "industry": "Account industry.",
            "numberOfEmployees": "Reported number of employees.",
            "numberOfUsers": "Number of tracked users belonging to the account.",
            "plan": "Subscription plan the account is on.",
            "website": "Account website.",
            "healthScore": "Gainsight health score for the account.",
            "nps": "Latest NPS score for the account.",
            "csm": "Customer success manager assigned to the account.",
            "renewalDate": "Contract renewal date.",
            "parentGroupId": "Identifier used to group related accounts together.",
            "lastSeenDate": "Timestamp the account was last active.",
            "createDate": "Timestamp the account was created in Gainsight PX.",
            "lastModifiedDate": "Timestamp the account was last modified.",
            "customAttributes": "Map of custom attribute API name to value.",
        },
    },
    "users": {
        "description": "Individual end users tracked in Gainsight PX, with their profile and engagement attributes.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "User identifier (synonym for identifyId).",
            "identifyId": "Customer-supplied identifier used to identify the user.",
            "aptrinsicId": "Gainsight PX-generated user identifier.",
            "globalId": "Global user identifier (workspace-enabled subscriptions only).",
            "email": "User email address.",
            "firstName": "User first name.",
            "lastName": "User last name.",
            "title": "User job title.",
            "role": "User role.",
            "accountId": "Identifier of the account the user belongs to.",
            "subscriptionId": "Subscription the user is tracked under.",
            "score": "User engagement score.",
            "numberOfVisits": "Total number of sessions recorded for the user.",
            "sfdcContactId": "Salesforce contact identifier, when linked.",
            "globalUnsubscribe": "Whether the user has globally unsubscribed from engagements.",
            "signUpDate": "Timestamp the user signed up.",
            "firstVisitDate": "Timestamp of the user's first tracked visit.",
            "lastSeenDate": "Timestamp the user was last active.",
            "createDate": "Timestamp the user was created in Gainsight PX.",
            "lastModifiedDate": "Timestamp the user was last modified.",
            "customAttributes": "Map of custom attribute API name to value.",
        },
    },
    "features": {
        "description": "Product features tagged in Gainsight PX for adoption tracking.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Unique feature identifier.",
            "name": "Feature name.",
            "type": "Feature type.",
            "parentFeatureId": "Identifier of the parent feature, for nested features.",
            "propertyKey": "Aptrinsic tag key the feature belongs to.",
            "status": "Feature status.",
            "featureLabels": "Labels associated with the feature.",
        },
    },
    "segments": {
        "description": "User/account segments defined in Gainsight PX.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Unique segment identifier.",
            "name": "Segment name.",
        },
    },
    "engagements": {
        "description": "In-app engagements (guides, surveys, dialogs) configured in Gainsight PX.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Unique engagement identifier.",
            "name": "Engagement name.",
            "description": "Engagement description.",
            "type": "Engagement type (e.g. guide, survey, dialog).",
            "state": "Engagement lifecycle state.",
            "defaultLanguage": "Default language of the engagement.",
            "languages": "Languages the engagement is localized into.",
            "translationState": "Localization/translation state.",
            "envs": "Environments the engagement is published to.",
        },
    },
    "articles": {
        "description": "Knowledge Center articles published in Gainsight PX.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Unique article identifier.",
            "articleName": "Article title.",
            "author": "Article author.",
            "productId": "Identifier of the product the article belongs to.",
            "productName": "Name of the product the article belongs to.",
            "viewType": "Article view type.",
            "defaultLanguage": "Default language of the article.",
            "languages": "Languages the article is localized into.",
            "translationState": "Localization/translation state.",
            "releaseDate": "Article release date (ISO date string).",
            "createdDate": "Timestamp the article was created.",
            "modifiedDate": "Timestamp the article was last modified.",
        },
    },
    "kc_bots": {
        "description": "Knowledge Center bots configured in Gainsight PX.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Unique Knowledge Center bot identifier.",
            "name": "Bot name.",
            "description": "Bot description.",
            "status": "Bot status.",
            "priority": "Bot display priority.",
            "productId": "Identifier of the product the bot belongs to.",
            "productName": "Name of the product the bot belongs to.",
            "defaultLanguage": "Default language of the bot.",
            "languages": "Languages the bot is localized into.",
            "environments": "Environments the bot is published to.",
            "createdDate": "Timestamp the bot was created.",
            "modifiedDate": "Timestamp the bot was last modified.",
        },
    },
}
