from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "targets": {
        "description": "A system (host, IP, URL, cloud account, or container image) that Intruder scans for vulnerabilities.",
        "docs_url": "https://developers.intruder.io/reference/targets_list-1",
        "columns": {
            "id": "Unique identifier for the target.",
            "address": "The target's address (hostname, IP, URL, or cloud account identifier).",
            "display_address": "Human-readable address (e.g. a cloud account name).",
            "has_api_schemas": "Whether the target has one or more API schemas attached for API scanning.",
            "has_authentications": "Whether the target has authenticated-scan credentials configured.",
            "license_type": "Whether the target consumes an infrastructure or application license.",
            "waf_provider": "The web application firewall provider detected on this target, or null if none.",
            "waf_interference": "Whether a WAF is blocking scans on this target, or null if not applicable.",
            "tags": "Tag names applied to this target.",
            "target_status": "Current status of the target (e.g. live, unscanned, unresponsive, license_exceeded, agent_uninstalled).",
            "target_type": "The kind of target (external, internal, cloud, or container_image).",
        },
    },
    "scans": {
        "description": "A vulnerability scan run against your targets.",
        "docs_url": "https://developers.intruder.io/reference/scans_list-1",
        "columns": {
            "id": "Unique identifier for the scan.",
            "status": "Current status of the scan (e.g. in_progress, completed, cancelled, analysing_results).",
            "created_at": "When the scan was created.",
            "scan_type": "What triggered the scan (e.g. assessment_schedule, new_service, cloudbot_new_target, rapid_remediation, advisory, cloud_security, container_image).",
            "schedule_period": "The cadence of the schedule that produced the scan, if any (e.g. daily, weekly, monthly, quarterly, one_off).",
        },
    },
    "scan_schedules": {
        "description": "A recurring schedule that automatically starts scans against your targets.",
        "docs_url": "https://developers.intruder.io/reference/scans_schedules_list",
        "columns": {
            "id": "Unique identifier for the scan schedule.",
            "name": "Name of the scan schedule.",
            "schedule_period": "How often the schedule runs (e.g. daily, weekly, monthly, quarterly, one_off).",
            "first_scan_time": "When the first scan in the schedule is (or was) due to run.",
            "next_scan_date": "When the next scan in the schedule is due to run.",
            "status": "Current status of the schedule.",
            "web_ports_only": "Whether the schedule only scans web ports.",
            "latest_scan_id": "Identifier of the most recent scan produced by this schedule.",
            "latest_scan_status": "Status of the most recent scan produced by this schedule.",
            "last_scan_start_time": "When the most recent scan produced by this schedule started.",
        },
    },
    "issues": {
        "description": "A distinct type of security weakness Intruder has found, aggregating all of its occurrences across your targets.",
        "docs_url": "https://developers.intruder.io/reference/issues_list-1",
        "columns": {
            "id": "Unique identifier for the issue.",
            "severity": "Severity of the issue (low, medium, high, or critical).",
            "title": "Short title describing the issue.",
            "description": "Detailed description of the security weakness.",
            "remediation": "Recommended steps to fix the issue.",
            "snoozed": "Whether the issue is currently snoozed.",
            "snooze_reason": "Reason the issue was snoozed, if any.",
            "snooze_until": "Date the snooze expires, if any.",
            "occurrences": "URL to the list of occurrences for this issue.",
            "exploit_likelihood": "Intruder's assessment of how likely the weakness is to be exploited.",
            "cvss_score": "CVSS score quantifying the severity of the issue.",
        },
    },
    "occurrences": {
        "description": "A single instance of an issue found on a specific target. Fanned out per issue and tagged with its parent issue_id.",
        "docs_url": "https://developers.intruder.io/reference/issues_occurrences_list-1",
        "columns": {
            "id": "Unique identifier for the occurrence.",
            "issue_id": "Identifier of the parent issue this occurrence belongs to (added by the connector).",
            "occurrence_id": "Stable identifier of the occurrence across scans.",
            "target": "Address of the target the occurrence was found on.",
            "display_address": "Human-readable address of the affected target.",
            "port": "The port the occurrence was found on.",
            "protocol": "The network protocol the occurrence was found on.",
            "extra_info": "Additional scanner-provided context about the occurrence.",
            "age": "How long the occurrence has existed.",
            "snoozed": "Whether the occurrence is currently snoozed.",
            "snooze_reason": "Reason the occurrence was snoozed, if any.",
            "snooze_until": "Date the snooze expires, if any.",
            "exploit_likelihood": "Intruder's assessment of how likely this occurrence is to be exploited.",
            "cvss_score": "CVSS score quantifying the severity of this occurrence.",
            "first_seen_at": "When the occurrence was first seen.",
            "target_last_scanned_at": "When the affected target was last scanned.",
            "cves": "CVE identifiers associated with the occurrence.",
        },
    },
    "fixed_occurrences": {
        "description": "An occurrence of an issue that has since been resolved (remediated).",
        "docs_url": "https://developers.intruder.io/reference/occurrences_fixed_list",
        "columns": {
            "id": "Unique identifier for the fixed occurrence.",
            "occurrence_id": "Stable identifier of the underlying occurrence.",
            "display_address": "Human-readable address of the affected target.",
            "affected_host": "Host the occurrence was found on.",
            "affected_port": "Port the occurrence was found on.",
            "cvss_score": "CVSS score quantifying the severity of the occurrence.",
            "description": "Description of the resolved security weakness.",
            "due_date": "Date by which the occurrence was expected to be remediated.",
            "exploit_likelihood": "Intruder's assessment of how likely the weakness was to be exploited.",
            "extra_info": "Additional scanner-provided context about the occurrence.",
            "first_seen_at": "When the occurrence was first seen.",
            "host_state": "State of the affected host.",
            "remediated_at": "When the occurrence was remediated.",
            "remediation": "Recommended steps that resolved the issue.",
            "severity": "Severity of the occurrence (low, medium, high, or critical).",
            "tags": "Tag names applied to the affected target.",
            "target_last_scanned_at": "When the affected target was last scanned.",
            "title": "Short title describing the resolved issue.",
        },
    },
    "tags": {
        "description": "A tag used to group and filter targets.",
        "docs_url": "https://developers.intruder.io/reference/tags_list",
        "columns": {
            "name": "Name of the tag.",
        },
    },
}
