-- AUTO-GENERATED from the declarative HCL by ops/gen-sql.sh — do not edit.
-- Full CREATE schema for the local-multi/medium node. Apply to a fresh ClickHouse to build it.

CREATE TABLE posthog.kafka_app_metrics2 (
  team_id Int64,
  timestamp DateTime64(6, 'UTC'),
  app_source LowCardinality(String),
  app_source_id String,
  instance_id String,
  metric_kind String,
  metric_name String,
  count Int64
) ENGINE = Kafka() SETTINGS kafka_broker_list = 'msk_cluster', kafka_format = 'kafka_format = \'JSONEachRow\'', kafka_group_name = 'kafka_group_name = \'group1\'', kafka_topic_list = 'kafka_topic_list = \'clickhouse_app_metrics2\'';
CREATE TABLE posthog.kafka_app_metrics2_ws (
  team_id Int64,
  timestamp DateTime64(6, 'UTC'),
  app_source LowCardinality(String),
  app_source_id String,
  instance_id String,
  metric_kind String,
  metric_name String,
  count Int64
) ENGINE = Kafka() SETTINGS kafka_broker_list = 'warpstream_ingestion', kafka_format = 'kafka_format = \'JSONEachRow\'', kafka_group_name = 'kafka_group_name = \'clickhouse_app_metrics2_ws\'', kafka_topic_list = 'kafka_topic_list = \'clickhouse_app_metrics2\'';
CREATE TABLE posthog.kafka_cohort_membership (
  team_id Int64,
  cohort_id Int64,
  person_id UUID,
  status Enum8('entered'=1, 'left'=2, 'member'=3, 'not_member'=4),
  last_updated DateTime64(6)
) ENGINE = Kafka() SETTINGS kafka_broker_list = 'msk_cluster', kafka_format = 'kafka_format = \'JSONEachRow\'', kafka_group_name = 'kafka_group_name = \'clickhouse_cohort_membership_changed\'', kafka_topic_list = 'kafka_topic_list = \'cohort_membership_changed\'';
CREATE TABLE posthog.kafka_distinct_id_usage (
  team_id Int64,
  distinct_id String,
  timestamp DateTime64(6, 'UTC')
) ENGINE = Kafka() SETTINGS kafka_broker_list = 'warpstream_ingestion', kafka_format = 'kafka_format = \'JSONEachRow\'', kafka_group_name = 'kafka_group_name = \'clickhouse_distinct_id_usage\'', kafka_skip_broken_messages = 100, kafka_topic_list = 'kafka_topic_list = \'distinct_id_usage_events_json\'';
CREATE TABLE posthog.kafka_flag_evaluations (
  uuid UUID,
  event LowCardinality(String),
  properties String,
  timestamp DateTime64(6, 'UTC'),
  team_id Int64,
  distinct_id String,
  created_at DateTime64(6, 'UTC'),
  person_id UUID,
  person_properties String,
  group0_properties String,
  group1_properties String,
  group2_properties String,
  group3_properties String,
  group4_properties String,
  inserted_at DateTime64(6, 'UTC')
) ENGINE = Kafka() SETTINGS kafka_broker_list = 'warpstream_ingestion', kafka_format = 'kafka_format = \'JSONEachRow\'', kafka_group_name = 'kafka_group_name = \'clickhouse_flag_evaluations\'', kafka_skip_broken_messages = 100, kafka_topic_list = 'kafka_topic_list = \'clickhouse_flag_evaluations\'';
CREATE TABLE posthog.kafka_heatmaps (
  session_id String,
  team_id Int64,
  distinct_id String,
  timestamp DateTime64(6, 'UTC'),
  x Int16,
  y Int16,
  scale_factor Int16,
  viewport_width Int16,
  viewport_height Int16,
  pointer_target_fixed Bool,
  current_url String,
  type LowCardinality(String)
) ENGINE = Kafka() SETTINGS kafka_broker_list = 'msk_cluster', kafka_format = 'kafka_format = \'JSONEachRow\'', kafka_group_name = 'kafka_group_name = \'group1\'', kafka_topic_list = 'kafka_topic_list = \'clickhouse_heatmap_events\'';
CREATE TABLE posthog.kafka_precalculated_events (
  team_id Int64,
  date Nullable(Date),
  distinct_id String,
  person_id UUID,
  condition String,
  uuid UUID,
  source String
) ENGINE = Kafka() SETTINGS kafka_broker_list = 'msk_cluster', kafka_flush_interval_ms = 7500, kafka_format = 'kafka_format = \'JSONEachRow\'', kafka_group_name = 'kafka_group_name = \'clickhouse_prefiltered_events\'', kafka_max_block_size = 1000000, kafka_num_consumers = 1, kafka_poll_max_batch_size = 100000, kafka_poll_timeout_ms = 1000, kafka_skip_broken_messages = 100, kafka_topic_list = 'kafka_topic_list = \'clickhouse_prefiltered_events\'';
CREATE TABLE posthog.kafka_precalculated_person_properties (
  team_id Int64,
  distinct_id String,
  person_id UUID,
  condition String,
  matches Bool,
  source String
) ENGINE = Kafka() SETTINGS kafka_broker_list = 'msk_cluster', kafka_flush_interval_ms = 7500, kafka_format = 'kafka_format = \'JSONEachRow\'', kafka_group_name = 'kafka_group_name = \'clickhouse_precalculated_person_properties\'', kafka_max_block_size = 1000000, kafka_num_consumers = 1, kafka_poll_max_batch_size = 100000, kafka_poll_timeout_ms = 1000, kafka_skip_broken_messages = 100, kafka_topic_list = 'kafka_topic_list = \'clickhouse_precalculated_person_properties\'';
CREATE TABLE posthog.kafka_precalculated_person_properties_ws (
  team_id Int64,
  distinct_id String,
  person_id UUID,
  condition String,
  matches Bool,
  source String
) ENGINE = Kafka() SETTINGS kafka_broker_list = 'warpstream_calculated_events', kafka_flush_interval_ms = 7500, kafka_format = 'kafka_format = \'JSONEachRow\'', kafka_group_name = 'kafka_group_name = \'clickhouse_precalculated_person_properties_ws\'', kafka_max_block_size = 1000000, kafka_num_consumers = 1, kafka_poll_max_batch_size = 100000, kafka_poll_timeout_ms = 1000, kafka_skip_broken_messages = 100, kafka_topic_list = 'kafka_topic_list = \'clickhouse_precalculated_person_properties\'';
CREATE TABLE posthog.kafka_session_replay_features (
  session_id String,
  team_id Int64,
  distinct_id String,
  batch_id String,
  first_timestamp DateTime64(6, 'UTC'),
  last_timestamp DateTime64(6, 'UTC'),
  event_count Int64,
  mouse_position_count Int64,
  mouse_sum_x Float64,
  mouse_sum_x_squared Float64,
  mouse_sum_y Float64,
  mouse_sum_y_squared Float64,
  mouse_distance_traveled Float64,
  mouse_direction_change_count Int64,
  mouse_velocity_sum Float64,
  mouse_velocity_sum_of_squares Float64,
  mouse_velocity_count Int64,
  scroll_event_count Int64,
  total_scroll_magnitude Float64,
  scroll_direction_reversal_count Int64,
  rapid_scroll_reversal_count Int64,
  scroll_to_top_count Int64,
  click_count Int64,
  keypress_count Int64,
  mouse_activity_count Int64,
  rage_click_count Int64,
  dead_click_count Int64,
  backspace_count Int64,
  inter_action_gap_count Int64,
  inter_action_gap_sum_ms Float64,
  inter_action_gap_sum_of_squares_ms Float64,
  max_idle_gap_ms Float64,
  long_idle_gap_count Int64,
  quick_back_count Int64,
  page_visit_count Int64,
  visited_urls Array(String),
  login_path_visit_count Int64,
  signup_path_visit_count Int64,
  checkout_path_visit_count Int64,
  cart_path_visit_count Int64,
  billing_path_visit_count Int64,
  settings_path_visit_count Int64,
  account_path_visit_count Int64,
  error_path_visit_count Int64,
  not_found_path_visit_count Int64,
  admin_path_visit_count Int64,
  dashboard_path_visit_count Int64,
  onboarding_path_visit_count Int64,
  cancel_path_visit_count Int64,
  refund_path_visit_count Int64,
  console_error_count Int64,
  console_error_after_click_count Int64,
  console_warn_count Int64,
  network_request_count Int64,
  network_failed_request_count Int64,
  network_4xx_count Int64,
  network_5xx_count Int64,
  network_request_duration_sum Float64,
  network_request_duration_sum_of_squares Float64,
  network_request_duration_count Int64,
  mutation_count Int64,
  viewport_resize_count Int64,
  touch_event_count Int64,
  max_scroll_y Float64,
  click_target_ids Array(Int64),
  form_field_ids Array(Int64),
  text_selection_count Int64,
  selection_copy_count Int64,
  is_deleted UInt8
) ENGINE = Kafka() SETTINGS kafka_broker_list = 'msk_cluster', kafka_format = 'kafka_format = \'JSONEachRow\'', kafka_group_name = 'kafka_group_name = \'group1\'', kafka_topic_list = 'kafka_topic_list = \'clickhouse_session_replay_features\'';
CREATE TABLE posthog.kafka_tophog (
  timestamp DateTime64(6, 'UTC'),
  metric LowCardinality(String),
  type LowCardinality(String),
  key Map(LowCardinality(String), String),
  value Float64,
  count UInt64,
  pipeline LowCardinality(String),
  lane LowCardinality(String),
  labels Map(LowCardinality(String), String)
) ENGINE = Kafka() SETTINGS date_time_input_format = 'best_effort', kafka_broker_list = 'msk_cluster', kafka_format = 'kafka_format = \'JSONEachRow\'', kafka_group_name = 'kafka_group_name = \'clickhouse_tophog\'', kafka_skip_broken_messages = 100, kafka_topic_list = 'kafka_topic_list = \'clickhouse_tophog\'';
CREATE TABLE posthog.kafka_tophog_ws (
  timestamp DateTime64(6, 'UTC'),
  metric LowCardinality(String),
  type LowCardinality(String),
  key Map(LowCardinality(String), String),
  value Float64,
  count UInt64,
  pipeline LowCardinality(String),
  lane LowCardinality(String),
  labels Map(LowCardinality(String), String)
) ENGINE = Kafka() SETTINGS date_time_input_format = 'best_effort', kafka_broker_list = 'warpstream_ingestion', kafka_format = 'kafka_format = \'JSONEachRow\'', kafka_group_name = 'kafka_group_name = \'clickhouse_tophog_ws\'', kafka_skip_broken_messages = 100, kafka_topic_list = 'kafka_topic_list = \'clickhouse_tophog\'';
CREATE TABLE posthog.query_log_archive (
  hostname LowCardinality(String),
  user LowCardinality(String),
  query_id String,
  initial_query_id String,
  is_initial_query UInt8,
  type Enum8('QueryStart'=1, 'QueryFinish'=2, 'ExceptionBeforeStart'=3, 'ExceptionWhileProcessing'=4),
  event_date Date,
  event_time DateTime,
  event_time_microseconds DateTime64(6),
  query_start_time DateTime,
  query_start_time_microseconds DateTime64(6),
  query_duration_ms UInt64,
  read_rows UInt64,
  read_bytes UInt64,
  written_rows UInt64,
  written_bytes UInt64,
  result_rows UInt64,
  result_bytes UInt64,
  memory_usage UInt64,
  peak_threads_usage UInt64,
  current_database LowCardinality(String),
  query String,
  formatted_query String,
  normalized_query_hash UInt64,
  query_kind LowCardinality(String),
  exception_code Int32,
  exception String,
  stack_trace String,
  team_id Int64,
  log_comment JSON(max_dynamic_paths=256, access_method LowCardinality(String), alert_config_id String, api_key_label String, api_key_mask String, batch_export_id String, chargeable Bool, client_query_id String, cohort_id Int64, `dagster.job_name` String, `dagster.run_id` String, `dagster.tags.owner` String, dashboard_id Int64, experiment_feature_flag_key String, experiment_id Int64, feature LowCardinality(String), id String, insight_id Int64, is_impersonated Bool, kind LowCardinality(String), name String, org_id String, person_on_events_mode LowCardinality(String), product LowCardinality(String), query_type LowCardinality(String), request_name String, route_id String, service_name String, session_id String, table_id String, team_id Int64, `temporal.activity_id` String, `temporal.activity_type` String, `temporal.attempt` Int64, `temporal.workflow_id` String, `temporal.workflow_namespace` String, `temporal.workflow_run_id` String, `temporal.workflow_type` String, user_id Int64, warehouse_query Bool, workflow LowCardinality(String), workload LowCardinality(String), SKIP cache_key, SKIP filter, SKIP hogql_features, SKIP http_referer, SKIP http_request_id, SKIP http_user_agent, SKIP query_settings, SKIP timings, SKIP user_email),
  ProfileEvents Map(String, UInt64),
  exception_name String ALIAS errorCodeToName(exception_code),
  ProfileEvents_RealTimeMicroseconds Int64 ALIAS ProfileEvents['RealTimeMicroseconds'],
  ProfileEvents_OSCPUVirtualTimeMicroseconds Int64 ALIAS ProfileEvents['OSCPUVirtualTimeMicroseconds'],
  ProfileEvents_S3Clients Int64 ALIAS ProfileEvents['S3Clients'],
  ProfileEvents_S3DeleteObjects Int64 ALIAS ProfileEvents['S3DeleteObjects'],
  ProfileEvents_S3CopyObject Int64 ALIAS ProfileEvents['S3CopyObject'],
  ProfileEvents_S3ListObjects Int64 ALIAS ProfileEvents['S3ListObjects'],
  ProfileEvents_S3HeadObject Int64 ALIAS ProfileEvents['S3HeadObject'],
  ProfileEvents_S3GetObjectAttributes Int64 ALIAS ProfileEvents['S3GetObjectAttributes'],
  ProfileEvents_S3CreateMultipartUpload Int64 ALIAS ProfileEvents['S3CreateMultipartUpload'],
  ProfileEvents_S3UploadPartCopy Int64 ALIAS ProfileEvents['S3UploadPartCopy'],
  ProfileEvents_S3UploadPart Int64 ALIAS ProfileEvents['S3UploadPart'],
  ProfileEvents_S3AbortMultipartUpload Int64 ALIAS ProfileEvents['S3AbortMultipartUpload'],
  ProfileEvents_S3CompleteMultipartUpload Int64 ALIAS ProfileEvents['S3CompleteMultipartUpload'],
  ProfileEvents_S3PutObject Int64 ALIAS ProfileEvents['S3PutObject'],
  ProfileEvents_S3GetObject Int64 ALIAS ProfileEvents['S3GetObject'],
  ProfileEvents_ReadBufferFromS3Bytes Int64 ALIAS ProfileEvents['ReadBufferFromS3Bytes'],
  ProfileEvents_WriteBufferFromS3Bytes Int64 ALIAS ProfileEvents['WriteBufferFromS3Bytes'],
  lc_workflow LowCardinality(String) ALIAS log_comment.workflow,
  lc_kind LowCardinality(String) ALIAS log_comment.kind,
  lc_id String ALIAS CAST(log_comment.id, 'String'),
  lc_route_id String ALIAS CAST(log_comment.route_id, 'String'),
  lc_access_method LowCardinality(String) ALIAS log_comment.access_method,
  lc_api_key_label String ALIAS CAST(log_comment.api_key_label, 'String'),
  lc_api_key_mask String ALIAS CAST(log_comment.api_key_mask, 'String'),
  lc_query_type LowCardinality(String) ALIAS log_comment.query_type,
  lc_product LowCardinality(String) ALIAS log_comment.product,
  lc_chargeable Bool ALIAS log_comment.chargeable,
  lc_name String ALIAS CAST(log_comment.name, 'String'),
  lc_request_name String ALIAS CAST(log_comment.request_name, 'String'),
  lc_client_query_id String ALIAS CAST(log_comment.client_query_id, 'String'),
  lc_org_id String ALIAS CAST(log_comment.org_id, 'String'),
  lc_user_id Int64 ALIAS log_comment.user_id,
  lc_is_impersonated Bool ALIAS log_comment.is_impersonated,
  lc_session_id String ALIAS CAST(log_comment.session_id, 'String'),
  lc_dashboard_id Int64 ALIAS log_comment.dashboard_id,
  lc_insight_id Int64 ALIAS log_comment.insight_id,
  lc_cohort_id Int64 ALIAS log_comment.cohort_id,
  lc_batch_export_id String ALIAS CAST(log_comment.batch_export_id, 'String'),
  lc_experiment_id Int64 ALIAS log_comment.experiment_id,
  lc_experiment_feature_flag_key String ALIAS CAST(log_comment.experiment_feature_flag_key, 'String'),
  lc_alert_config_id String ALIAS CAST(log_comment.alert_config_id, 'String'),
  lc_feature LowCardinality(String) ALIAS log_comment.feature,
  lc_table_id String ALIAS CAST(log_comment.table_id, 'String'),
  lc_warehouse_query Bool ALIAS log_comment.warehouse_query,
  lc_person_on_events_mode LowCardinality(String) ALIAS log_comment.person_on_events_mode,
  lc_service_name String ALIAS CAST(log_comment.service_name, 'String'),
  lc_workload LowCardinality(String) ALIAS log_comment.workload,
  lc_query__kind LowCardinality(String) ALIAS if(JSONHas(toString(log_comment), 'query', 'source'), JSONExtractString(toString(log_comment), 'query', 'source', 'kind'), JSONExtractString(toString(log_comment), 'query', 'kind')),
  lc_query__query String ALIAS multiIf(NOT is_initial_query, '', JSONHas(toString(log_comment), 'query', 'source'), JSONExtractString(toString(log_comment), 'query', 'source', 'query'), JSONExtractString(toString(log_comment), 'query', 'query')),
  lc_query String ALIAS if(is_initial_query, JSONExtractRaw(toString(log_comment), 'query'), ''),
  lc_temporal__workflow_namespace String ALIAS CAST(log_comment.`temporal.workflow_namespace`, 'String'),
  lc_temporal__workflow_type String ALIAS CAST(log_comment.`temporal.workflow_type`, 'String'),
  lc_temporal__workflow_id String ALIAS CAST(log_comment.`temporal.workflow_id`, 'String'),
  lc_temporal__workflow_run_id String ALIAS CAST(log_comment.`temporal.workflow_run_id`, 'String'),
  lc_temporal__activity_type String ALIAS CAST(log_comment.`temporal.activity_type`, 'String'),
  lc_temporal__activity_id String ALIAS CAST(log_comment.`temporal.activity_id`, 'String'),
  lc_temporal__attempt Int64 ALIAS log_comment.`temporal.attempt`,
  lc_dagster__job_name String ALIAS CAST(log_comment.`dagster.job_name`, 'String'),
  lc_dagster__run_id String ALIAS CAST(log_comment.`dagster.run_id`, 'String'),
  lc_dagster__owner String ALIAS CAST(log_comment.`dagster.tags.owner`, 'String'),
  lc_modifiers String ALIAS if(is_initial_query, JSONExtractRaw(toString(log_comment), 'modifiers'), '')
) ENGINE = Distributed('ops', 'posthog', 'sharded_query_log_archive');
CREATE TABLE posthog.writable_app_metrics2 (
  team_id Int64,
  timestamp DateTime64(6, 'UTC'),
  app_source LowCardinality(String),
  app_source_id String,
  instance_id String,
  metric_kind LowCardinality(String),
  metric_name LowCardinality(String),
  count SimpleAggregateFunction(sum, Int64),
  _timestamp DateTime,
  _offset UInt64,
  _partition UInt64
) ENGINE = Distributed('posthog', 'posthog', 'sharded_app_metrics2', rand());
CREATE TABLE posthog.writable_cohort_membership (
  team_id Int64,
  cohort_id Int64,
  person_id UUID,
  status Enum8('entered'=1, 'left'=2),
  last_updated DateTime64(6) DEFAULT now64()
) ENGINE = Distributed('posthog_single_shard', 'posthog', 'cohort_membership');
CREATE TABLE posthog.writable_distinct_id_usage (
  team_id Int64,
  distinct_id String,
  minute DateTime,
  event_count UInt64
) ENGINE = Distributed('posthog', 'posthog', 'sharded_distinct_id_usage', sipHash64(distinct_id));
CREATE TABLE posthog.writable_flag_evaluations (
  uuid UUID,
  event LowCardinality(String),
  properties String,
  timestamp DateTime64(6, 'UTC'),
  team_id Int64,
  distinct_id String,
  created_at DateTime64(6, 'UTC'),
  person_id UUID,
  person_properties String,
  group0_properties String,
  group1_properties String,
  group2_properties String,
  group3_properties String,
  group4_properties String,
  inserted_at DateTime64(6, 'UTC') DEFAULT timestamp,
  _timestamp DateTime,
  _offset UInt64,
  _partition UInt64
) ENGINE = Distributed('posthog', 'posthog', 'sharded_flag_evaluations', sipHash64(distinct_id));
CREATE TABLE posthog.writable_heatmaps (
  session_id String,
  team_id Int64,
  distinct_id String,
  timestamp DateTime64(6, 'UTC'),
  x Int16,
  y Int16,
  scale_factor Int16,
  viewport_width Int16,
  viewport_height Int16,
  pointer_target_fixed Bool,
  current_url String,
  type LowCardinality(String),
  _timestamp DateTime,
  _offset UInt64,
  _partition UInt64
) ENGINE = Distributed('posthog', 'posthog', 'sharded_heatmaps', cityHash64(concat(toString(team_id), '-', session_id, '-', toString(toDate(timestamp)))));
CREATE TABLE posthog.writable_precalculated_events (
  team_id Int64,
  date Date,
  distinct_id String,
  person_id UUID,
  condition String,
  uuid UUID,
  source String,
  _timestamp DateTime64(6),
  _partition UInt64,
  _offset UInt64
) ENGINE = Distributed('posthog', 'posthog', 'sharded_precalculated_events', sipHash64(distinct_id));
CREATE TABLE posthog.writable_precalculated_person_properties (
  team_id Int64,
  distinct_id String,
  person_id UUID,
  condition String,
  matches Bool,
  source String,
  _timestamp DateTime64(6),
  _offset UInt64
) ENGINE = Distributed('posthog', 'posthog', 'sharded_precalculated_person_properties', sipHash64(distinct_id));
CREATE TABLE posthog.writable_session_replay_features (
  session_id String,
  team_id Int64,
  distinct_id String,
  min_first_timestamp SimpleAggregateFunction(min, DateTime64(6, 'UTC')),
  max_last_timestamp SimpleAggregateFunction(max, DateTime64(6, 'UTC')),
  event_count SimpleAggregateFunction(sum, Int64),
  mouse_position_count SimpleAggregateFunction(sum, Int64),
  mouse_sum_x SimpleAggregateFunction(sum, Float64),
  mouse_sum_x_squared SimpleAggregateFunction(sum, Float64),
  mouse_sum_y SimpleAggregateFunction(sum, Float64),
  mouse_sum_y_squared SimpleAggregateFunction(sum, Float64),
  mouse_distance_traveled SimpleAggregateFunction(sum, Float64),
  mouse_direction_change_count SimpleAggregateFunction(sum, Int64),
  mouse_velocity_sum SimpleAggregateFunction(sum, Float64),
  mouse_velocity_sum_of_squares SimpleAggregateFunction(sum, Float64),
  mouse_velocity_count SimpleAggregateFunction(sum, Int64),
  scroll_event_count SimpleAggregateFunction(sum, Int64),
  total_scroll_magnitude SimpleAggregateFunction(sum, Float64),
  scroll_direction_reversal_count SimpleAggregateFunction(sum, Int64),
  rapid_scroll_reversal_count SimpleAggregateFunction(sum, Int64),
  scroll_to_top_count SimpleAggregateFunction(sum, Int64),
  click_count SimpleAggregateFunction(sum, Int64),
  keypress_count SimpleAggregateFunction(sum, Int64),
  mouse_activity_count SimpleAggregateFunction(sum, Int64),
  rage_click_count SimpleAggregateFunction(sum, Int64),
  dead_click_count SimpleAggregateFunction(sum, Int64),
  backspace_count SimpleAggregateFunction(sum, Int64),
  inter_action_gap_count SimpleAggregateFunction(sum, Int64),
  inter_action_gap_sum_ms SimpleAggregateFunction(sum, Float64),
  inter_action_gap_sum_of_squares_ms SimpleAggregateFunction(sum, Float64),
  max_idle_gap_ms SimpleAggregateFunction(max, Float64),
  long_idle_gap_count SimpleAggregateFunction(sum, Int64),
  quick_back_count SimpleAggregateFunction(sum, Int64),
  page_visit_count SimpleAggregateFunction(sum, Int64),
  unique_url_count AggregateFunction(uniqCombined(12), String),
  login_path_visit_count SimpleAggregateFunction(sum, Int64),
  signup_path_visit_count SimpleAggregateFunction(sum, Int64),
  checkout_path_visit_count SimpleAggregateFunction(sum, Int64),
  cart_path_visit_count SimpleAggregateFunction(sum, Int64),
  billing_path_visit_count SimpleAggregateFunction(sum, Int64),
  settings_path_visit_count SimpleAggregateFunction(sum, Int64),
  account_path_visit_count SimpleAggregateFunction(sum, Int64),
  error_path_visit_count SimpleAggregateFunction(sum, Int64),
  not_found_path_visit_count SimpleAggregateFunction(sum, Int64),
  admin_path_visit_count SimpleAggregateFunction(sum, Int64),
  dashboard_path_visit_count SimpleAggregateFunction(sum, Int64),
  onboarding_path_visit_count SimpleAggregateFunction(sum, Int64),
  cancel_path_visit_count SimpleAggregateFunction(sum, Int64),
  refund_path_visit_count SimpleAggregateFunction(sum, Int64),
  console_error_count SimpleAggregateFunction(sum, Int64),
  console_error_after_click_count SimpleAggregateFunction(sum, Int64),
  console_warn_count SimpleAggregateFunction(sum, Int64),
  network_request_count SimpleAggregateFunction(sum, Int64),
  network_failed_request_count SimpleAggregateFunction(sum, Int64),
  network_4xx_count SimpleAggregateFunction(sum, Int64),
  network_5xx_count SimpleAggregateFunction(sum, Int64),
  network_request_duration_sum SimpleAggregateFunction(sum, Float64),
  network_request_duration_sum_of_squares SimpleAggregateFunction(sum, Float64),
  network_request_duration_count SimpleAggregateFunction(sum, Int64),
  mutation_count SimpleAggregateFunction(sum, Int64),
  viewport_resize_count SimpleAggregateFunction(sum, Int64),
  touch_event_count SimpleAggregateFunction(sum, Int64),
  max_scroll_y SimpleAggregateFunction(max, Float64),
  unique_click_target_count AggregateFunction(uniqCombined(12), Int64),
  unique_form_field_count AggregateFunction(uniqCombined(12), Int64),
  text_selection_count SimpleAggregateFunction(sum, Int64),
  selection_copy_count SimpleAggregateFunction(sum, Int64),
  is_deleted SimpleAggregateFunction(max, UInt8) DEFAULT 0
) ENGINE = Distributed('aux', 'posthog', 'sharded_session_replay_features', sipHash64(session_id));
CREATE TABLE posthog.writable_tophog (
  timestamp DateTime64(6, 'UTC'),
  metric LowCardinality(String),
  type LowCardinality(String) DEFAULT 'sum',
  key Map(LowCardinality(String), String),
  value Float64,
  count UInt64 DEFAULT 0,
  pipeline LowCardinality(String),
  lane LowCardinality(String),
  labels Map(LowCardinality(String), String)
) ENGINE = Distributed('posthog', 'posthog', 'sharded_tophog', cityHash64(toString(key)));
CREATE MATERIALIZED VIEW posthog.app_metrics2_mv TO posthog.writable_app_metrics2 (team_id Int64, timestamp DateTime64(6, 'UTC'), app_source LowCardinality(String), app_source_id String, instance_id String, metric_kind String, metric_name String, count Int64, _timestamp Nullable(DateTime), _offset UInt64, _partition UInt64) AS SELECT
  team_id,
  timestamp,
  app_source,
  app_source_id,
  instance_id,
  metric_kind,
  metric_name,
  count,
  _timestamp,
  _offset,
  _partition
FROM posthog.kafka_app_metrics2;
CREATE MATERIALIZED VIEW posthog.app_metrics2_ws_mv TO posthog.writable_app_metrics2 (team_id Int64, timestamp DateTime64(6, 'UTC'), app_source LowCardinality(String), app_source_id String, instance_id String, metric_kind String, metric_name String, count Int64, _timestamp Nullable(DateTime), _offset UInt64, _partition UInt64) AS SELECT
  team_id,
  timestamp,
  app_source,
  app_source_id,
  instance_id,
  metric_kind,
  metric_name,
  count,
  _timestamp,
  _offset,
  _partition
FROM posthog.kafka_app_metrics2_ws;
CREATE MATERIALIZED VIEW posthog.cohort_membership_mv TO posthog.writable_cohort_membership (team_id Int64, cohort_id Int64, person_id UUID, status String, last_updated DateTime64(6)) AS SELECT
  team_id,
  cohort_id,
  person_id,
  multiIf(status = 'member', 'entered', status = 'not_member', 'left', status) AS status,
  last_updated
FROM posthog.kafka_cohort_membership;
CREATE MATERIALIZED VIEW posthog.distinct_id_usage_mv TO posthog.writable_distinct_id_usage (team_id Int64, distinct_id String, minute DateTime('UTC'), event_count UInt8) AS SELECT team_id, distinct_id, toStartOfMinute(timestamp) AS minute, 1 AS event_count
FROM posthog.kafka_distinct_id_usage;
CREATE MATERIALIZED VIEW posthog.flag_evaluations_mv TO posthog.writable_flag_evaluations (uuid UUID, event LowCardinality(String), properties String, timestamp DateTime64(6, 'UTC'), team_id Int64, distinct_id String, created_at DateTime64(6, 'UTC'), person_id UUID, person_properties String, group0_properties String, group1_properties String, group2_properties String, group3_properties String, group4_properties String, inserted_at Nullable(DateTime64(6, 'UTC')), _timestamp Nullable(DateTime), _offset UInt64, _partition UInt64) AS SELECT
  uuid,
  event,
  properties,
  timestamp,
  team_id,
  distinct_id,
  created_at,
  person_id,
  person_properties,
  group0_properties,
  group1_properties,
  group2_properties,
  group3_properties,
  group4_properties,
  if(inserted_at = toDateTime64('1970-01-01 00:00:00', 6, 'UTC'), _timestamp, inserted_at) AS inserted_at,
  _timestamp,
  _offset,
  _partition
FROM posthog.kafka_flag_evaluations;
CREATE MATERIALIZED VIEW posthog.heatmaps_mv TO posthog.writable_heatmaps (session_id String, team_id Int64, distinct_id String, timestamp DateTime64(6, 'UTC'), x Int16, y Int16, scale_factor Int16, viewport_width Int16, viewport_height Int16, pointer_target_fixed Bool, current_url String, type LowCardinality(String), _timestamp Nullable(DateTime), _offset UInt64, _partition UInt64) AS SELECT
  session_id,
  team_id,
  distinct_id,
  timestamp,
  x,
  y,
  scale_factor,
  viewport_width,
  viewport_height,
  pointer_target_fixed,
  current_url,
  type,
  _timestamp,
  _offset,
  _partition
FROM posthog.kafka_heatmaps;
CREATE MATERIALIZED VIEW posthog.precalculated_events_mv TO posthog.writable_precalculated_events (team_id Int64, date Nullable(Date), distinct_id String, person_id UUID, condition String, uuid UUID, source String, _timestamp Nullable(DateTime), _offset UInt64, _partition UInt64) AS SELECT
  team_id,
  ifNull(date, toDate(_timestamp)) AS date,
  distinct_id,
  person_id,
  condition,
  uuid,
  source,
  _timestamp,
  _offset,
  _partition
FROM posthog.kafka_precalculated_events;
CREATE MATERIALIZED VIEW posthog.precalculated_person_properties_mv TO posthog.writable_precalculated_person_properties (team_id Int64, distinct_id String, person_id UUID, condition String, matches Bool, source String, _timestamp Nullable(DateTime), _offset UInt64) AS SELECT
  team_id,
  distinct_id,
  person_id,
  condition,
  matches,
  source,
  _timestamp,
  _offset
FROM posthog.kafka_precalculated_person_properties;
CREATE MATERIALIZED VIEW posthog.precalculated_person_properties_ws_mv TO posthog.writable_precalculated_person_properties (team_id Int64, distinct_id String, person_id UUID, condition String, matches Bool, source String, _timestamp Nullable(DateTime), _offset UInt64) AS SELECT
  team_id,
  distinct_id,
  person_id,
  condition,
  matches,
  source,
  _timestamp,
  _offset
FROM posthog.kafka_precalculated_person_properties_ws;
CREATE MATERIALIZED VIEW posthog.session_replay_features_mv TO posthog.writable_session_replay_features (session_id String, team_id Int64, distinct_id String, min_first_timestamp DateTime64(6, 'UTC'), max_last_timestamp DateTime64(6, 'UTC'), event_count Int64, mouse_position_count Int64, mouse_sum_x Float64, mouse_sum_x_squared Float64, mouse_sum_y Float64, mouse_sum_y_squared Float64, mouse_distance_traveled Float64, mouse_direction_change_count Int64, mouse_velocity_sum Float64, mouse_velocity_sum_of_squares Float64, mouse_velocity_count Int64, scroll_event_count Int64, total_scroll_magnitude Float64, scroll_direction_reversal_count Int64, rapid_scroll_reversal_count Int64, scroll_to_top_count Int64, click_count Int64, keypress_count Int64, mouse_activity_count Int64, rage_click_count Int64, dead_click_count Int64, backspace_count Int64, inter_action_gap_count Int64, inter_action_gap_sum_ms Float64, inter_action_gap_sum_of_squares_ms Float64, max_idle_gap_ms Float64, long_idle_gap_count Int64, quick_back_count Int64, page_visit_count Int64, unique_url_count AggregateFunction(uniqCombinedArray(12), Array(String)), login_path_visit_count Int64, signup_path_visit_count Int64, checkout_path_visit_count Int64, cart_path_visit_count Int64, billing_path_visit_count Int64, settings_path_visit_count Int64, account_path_visit_count Int64, error_path_visit_count Int64, not_found_path_visit_count Int64, admin_path_visit_count Int64, dashboard_path_visit_count Int64, onboarding_path_visit_count Int64, cancel_path_visit_count Int64, refund_path_visit_count Int64, console_error_count Int64, console_error_after_click_count Int64, console_warn_count Int64, network_request_count Int64, network_failed_request_count Int64, network_4xx_count Int64, network_5xx_count Int64, network_request_duration_sum Float64, network_request_duration_sum_of_squares Float64, network_request_duration_count Int64, mutation_count Int64, viewport_resize_count Int64, touch_event_count Int64, max_scroll_y Float64, unique_click_target_count AggregateFunction(uniqCombinedArray(12), Array(Int64)), unique_form_field_count AggregateFunction(uniqCombinedArray(12), Array(Int64)), text_selection_count Int64, selection_copy_count Int64, is_deleted UInt8) AS SELECT
  session_id,
  team_id,
  any(distinct_id) AS distinct_id,
  min(first_timestamp) AS min_first_timestamp,
  max(last_timestamp) AS max_last_timestamp,
  sum(event_count) AS event_count,
  sum(mouse_position_count) AS mouse_position_count,
  sum(mouse_sum_x) AS mouse_sum_x,
  sum(mouse_sum_x_squared) AS mouse_sum_x_squared,
  sum(mouse_sum_y) AS mouse_sum_y,
  sum(mouse_sum_y_squared) AS mouse_sum_y_squared,
  sum(mouse_distance_traveled) AS mouse_distance_traveled,
  sum(mouse_direction_change_count) AS mouse_direction_change_count,
  sum(mouse_velocity_sum) AS mouse_velocity_sum,
  sum(mouse_velocity_sum_of_squares) AS mouse_velocity_sum_of_squares,
  sum(mouse_velocity_count) AS mouse_velocity_count,
  sum(scroll_event_count) AS scroll_event_count,
  sum(total_scroll_magnitude) AS total_scroll_magnitude,
  sum(scroll_direction_reversal_count) AS scroll_direction_reversal_count,
  sum(rapid_scroll_reversal_count) AS rapid_scroll_reversal_count,
  sum(scroll_to_top_count) AS scroll_to_top_count,
  sum(click_count) AS click_count,
  sum(keypress_count) AS keypress_count,
  sum(mouse_activity_count) AS mouse_activity_count,
  sum(rage_click_count) AS rage_click_count,
  sum(dead_click_count) AS dead_click_count,
  sum(backspace_count) AS backspace_count,
  sum(inter_action_gap_count) AS inter_action_gap_count,
  sum(inter_action_gap_sum_ms) AS inter_action_gap_sum_ms,
  sum(inter_action_gap_sum_of_squares_ms) AS inter_action_gap_sum_of_squares_ms,
  max(max_idle_gap_ms) AS max_idle_gap_ms,
  sum(long_idle_gap_count) AS long_idle_gap_count,
  sum(quick_back_count) AS quick_back_count,
  sum(page_visit_count) AS page_visit_count,
  uniqCombinedArrayState(12)(visited_urls) AS unique_url_count,
  sum(login_path_visit_count) AS login_path_visit_count,
  sum(signup_path_visit_count) AS signup_path_visit_count,
  sum(checkout_path_visit_count) AS checkout_path_visit_count,
  sum(cart_path_visit_count) AS cart_path_visit_count,
  sum(billing_path_visit_count) AS billing_path_visit_count,
  sum(settings_path_visit_count) AS settings_path_visit_count,
  sum(account_path_visit_count) AS account_path_visit_count,
  sum(error_path_visit_count) AS error_path_visit_count,
  sum(not_found_path_visit_count) AS not_found_path_visit_count,
  sum(admin_path_visit_count) AS admin_path_visit_count,
  sum(dashboard_path_visit_count) AS dashboard_path_visit_count,
  sum(onboarding_path_visit_count) AS onboarding_path_visit_count,
  sum(cancel_path_visit_count) AS cancel_path_visit_count,
  sum(refund_path_visit_count) AS refund_path_visit_count,
  sum(console_error_count) AS console_error_count,
  sum(console_error_after_click_count) AS console_error_after_click_count,
  sum(console_warn_count) AS console_warn_count,
  sum(network_request_count) AS network_request_count,
  sum(network_failed_request_count) AS network_failed_request_count,
  sum(network_4xx_count) AS network_4xx_count,
  sum(network_5xx_count) AS network_5xx_count,
  sum(network_request_duration_sum) AS network_request_duration_sum,
  sum(network_request_duration_sum_of_squares) AS network_request_duration_sum_of_squares,
  sum(network_request_duration_count) AS network_request_duration_count,
  sum(mutation_count) AS mutation_count,
  sum(viewport_resize_count) AS viewport_resize_count,
  sum(touch_event_count) AS touch_event_count,
  max(max_scroll_y) AS max_scroll_y,
  uniqCombinedArrayState(12)(click_target_ids) AS unique_click_target_count,
  uniqCombinedArrayState(12)(form_field_ids) AS unique_form_field_count,
  sum(text_selection_count) AS text_selection_count,
  sum(selection_copy_count) AS selection_copy_count,
  max(is_deleted) AS is_deleted
FROM posthog.kafka_session_replay_features
GROUP BY
  session_id, team_id;
CREATE MATERIALIZED VIEW posthog.tophog_mv TO posthog.writable_tophog (timestamp DateTime64(6, 'UTC'), metric LowCardinality(String), type LowCardinality(String), key Map(LowCardinality(String), String), value Float64, count UInt64, pipeline LowCardinality(String), lane LowCardinality(String), labels Map(LowCardinality(String), String)) AS SELECT
  timestamp,
  metric,
  type,
  key,
  value,
  count,
  pipeline,
  lane,
  labels
FROM posthog.kafka_tophog;
CREATE MATERIALIZED VIEW posthog.tophog_ws_mv TO posthog.writable_tophog (timestamp DateTime64(6, 'UTC'), metric LowCardinality(String), type LowCardinality(String), key Map(LowCardinality(String), String), value Float64, count UInt64, pipeline LowCardinality(String), lane LowCardinality(String), labels Map(LowCardinality(String), String)) AS SELECT
  timestamp,
  metric,
  type,
  key,
  value,
  count,
  pipeline,
  lane,
  labels
FROM posthog.kafka_tophog_ws;
