import { MakeLogicType, actions, afterMount, connect, kea, listeners, path, reducers, selectors } from 'kea'
import { loaders } from 'kea-loaders'

import { lemonToast } from 'lib/lemon-ui/LemonToast/LemonToast'
import { teamLogic } from 'scenes/teamLogic'

import type { TeamPublicType, TeamType } from '../../../../../frontend/src/types'
import { announcementsChannelsList, announcementsCreate, announcementsList } from '../../generated/api'
import type { AnnouncementApi, AnnouncementChannelApi } from '../../generated/api.schemas'

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface announcementsLogicValues {
    currentTeam: TeamPublicType | TeamType | null // teamLogic
    announcements: AnnouncementApi[]
    announcementsLoading: boolean
    channelOptions: {
        key: string
        label: string
    }[]
    memberChannels: AnnouncementChannelApi[]
    memberChannelsLoading: boolean
    messageDraft: string
    selectedChannelIds: string[]
    slackConnected: boolean
    submitDisabledReason: string | undefined
    submitting: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface announcementsLogicActions {
    loadAnnouncements: () => any
    loadAnnouncementsFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadAnnouncementsSuccess: (
        announcements: AnnouncementApi[],
        payload?: any
    ) => {
        announcements: AnnouncementApi[]
        payload?: any
    }
    loadMemberChannels: () => any
    loadMemberChannelsFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadMemberChannelsSuccess: (
        memberChannels: AnnouncementChannelApi[],
        payload?: any
    ) => {
        memberChannels: AnnouncementChannelApi[]
        payload?: any
    }
    setMessage: (message: string) => {
        message: string
    }
    setSelectedChannelIds: (channelIds: string[]) => {
        channelIds: string[]
    }
    setSubmitting: (submitting: boolean) => {
        submitting: boolean
    }
    submitAnnouncement: () => {
        value: true
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface announcementsLogicMeta {
    __keaTypeGenInternalSelectorTypes: {
        slackConnected: (currentTeam: TeamPublicType | TeamType | null) => boolean
        channelOptions: (memberChannels: AnnouncementChannelApi[]) => {
            key: string
            label: string
        }[]
        submitDisabledReason: (
            messageDraft: string,
            selectedChannelIds: string[],
            submitting: boolean
        ) => string | undefined
    }
}

export type announcementsLogicType = MakeLogicType<
    announcementsLogicValues,
    announcementsLogicActions,
    Record<string, any>,
    announcementsLogicMeta
>

export const announcementsLogic = kea<announcementsLogicType>([
    path(['products', 'customer_analytics', 'frontend', 'components', 'Announcements', 'announcementsLogic']),
    connect(() => ({
        values: [teamLogic, ['currentTeam']],
    })),
    actions({
        setMessage: (message: string) => ({ message }),
        setSelectedChannelIds: (channelIds: string[]) => ({ channelIds }),
        submitAnnouncement: true,
        setSubmitting: (submitting: boolean) => ({ submitting }),
    }),
    loaders(({ values }) => ({
        announcements: [
            [] as AnnouncementApi[],
            {
                loadAnnouncements: async () => {
                    const response = await announcementsList(String(values.currentTeam?.id), { limit: 100 })
                    return response.results ?? []
                },
            },
        ],
        memberChannels: [
            [] as AnnouncementChannelApi[],
            {
                loadMemberChannels: async () => {
                    try {
                        return await announcementsChannelsList(String(values.currentTeam?.id))
                    } catch {
                        lemonToast.error('Failed to load Slack channels')
                        return values.memberChannels
                    }
                },
            },
        ],
    })),
    reducers({
        messageDraft: ['', { setMessage: (_state, { message }) => message }],
        selectedChannelIds: [[] as string[], { setSelectedChannelIds: (_state, { channelIds }) => channelIds }],
        submitting: [false, { setSubmitting: (_state, { submitting }) => submitting }],
    }),
    selectors({
        slackConnected: [
            (s) => [s.currentTeam],
            (currentTeam: TeamPublicType | TeamType | null): boolean =>
                !!currentTeam?.conversations_settings?.slack_enabled,
        ],
        channelOptions: [
            (s) => [s.memberChannels],
            (memberChannels: AnnouncementChannelApi[]): { key: string; label: string }[] =>
                memberChannels.map((channel) => ({
                    key: channel.id,
                    label: channel.customer_name ? `${channel.customer_name} (#${channel.name})` : `#${channel.name}`,
                })),
        ],
        submitDisabledReason: [
            (s) => [s.messageDraft, s.selectedChannelIds, s.submitting],
            (messageDraft: string, selectedChannelIds: string[], submitting: boolean): string | undefined => {
                if (submitting) {
                    return 'Sending…'
                }
                if (!messageDraft.trim()) {
                    return 'Enter a message'
                }
                if (selectedChannelIds.length === 0) {
                    return 'Select at least one channel'
                }
                return undefined
            },
        ],
    }),
    listeners(({ values, actions }) => ({
        submitAnnouncement: async () => {
            // Guard against double-submission while a send is in flight.
            if (values.submitting || values.submitDisabledReason) {
                return
            }
            actions.setSubmitting(true)
            try {
                await announcementsCreate(String(values.currentTeam?.id), {
                    message: values.messageDraft.trim(),
                    channels: values.selectedChannelIds,
                })
                lemonToast.success('Announcement sent')
                actions.setMessage('')
                actions.setSelectedChannelIds([])
                actions.loadAnnouncements()
            } catch {
                lemonToast.error('Failed to send announcement')
            } finally {
                actions.setSubmitting(false)
            }
        },
    })),
    afterMount(({ values, actions }) => {
        actions.loadAnnouncements()
        if (values.slackConnected) {
            actions.loadMemberChannels()
        }
    }),
])
