from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

_REST_DOCS = "https://adobe-commerce.redoc.ly/2.4.7-admin/tag"

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "orders": {
        "description": "Sales orders placed in the store, with their totals, status, addresses, payment and line items.",
        "docs_url": f"{_REST_DOCS}/orders",
        "columns": {
            "entity_id": "Internal numeric identifier of the order.",
            "increment_id": "Human-readable order number shown to the customer and in the admin.",
            "state": "Order state machine value (new, processing, complete, closed, canceled, holded, payment_review).",
            "status": "Order status label, which stores map onto a state.",
            "store_id": "Store view the order was placed in.",
            "customer_id": "Identifier of the registered customer, null for guest checkouts.",
            "customer_email": "Email address the order was placed with.",
            "customer_is_guest": "1 when the order was placed without a customer account.",
            "base_grand_total": "Order grand total in the store's base currency.",
            "grand_total": "Order grand total in the currency the order was placed in.",
            "subtotal": "Sum of the line item row totals, excluding shipping, tax and discounts.",
            "tax_amount": "Total tax charged on the order.",
            "shipping_amount": "Shipping charge applied to the order.",
            "discount_amount": "Total discount applied to the order, as a negative amount.",
            "total_qty_ordered": "Sum of the quantities ordered across all line items.",
            "order_currency_code": "Currency the order was placed in.",
            "base_currency_code": "Base currency of the store the order belongs to.",
            "created_at": "Timestamp the order was placed (UTC).",
            "updated_at": "Timestamp the order row was last modified (UTC).",
            "items": "Line items on the order, each with sku, name, quantities and per-row totals.",
            "billing_address": "Billing address captured at checkout.",
            "extension_attributes": "Extension data such as shipping assignments, applied taxes and gift message.",
            "payment": "Payment record for the order, including method, amounts authorized and captured.",
        },
    },
    "invoices": {
        "description": "Invoices issued against orders, recording the amounts captured for a set of order line items.",
        "docs_url": f"{_REST_DOCS}/invoices",
        "columns": {
            "entity_id": "Internal numeric identifier of the invoice.",
            "increment_id": "Human-readable invoice number.",
            "order_id": "Identifier of the order the invoice belongs to.",
            "state": "Invoice state (1 = pending, 2 = paid, 3 = canceled).",
            "store_id": "Store view the invoice belongs to.",
            "grand_total": "Invoice grand total in the order currency.",
            "base_grand_total": "Invoice grand total in the store's base currency.",
            "subtotal": "Sum of the invoiced line item row totals.",
            "tax_amount": "Tax invoiced.",
            "shipping_amount": "Shipping invoiced.",
            "total_qty": "Total quantity invoiced across line items.",
            "created_at": "Timestamp the invoice was created (UTC).",
            "updated_at": "Timestamp the invoice row was last modified (UTC).",
            "items": "Invoiced line items with sku, quantity invoiced and row totals.",
        },
    },
    "shipments": {
        "description": "Shipments dispatched against orders, with their packages, tracking numbers and shipped items.",
        "docs_url": f"{_REST_DOCS}/shipments",
        "columns": {
            "entity_id": "Internal numeric identifier of the shipment.",
            "increment_id": "Human-readable shipment number.",
            "order_id": "Identifier of the order the shipment belongs to.",
            "store_id": "Store view the shipment belongs to.",
            "total_qty": "Total quantity shipped across line items.",
            "total_weight": "Total weight of the shipment.",
            "created_at": "Timestamp the shipment was created (UTC).",
            "updated_at": "Timestamp the shipment row was last modified (UTC).",
            "items": "Shipped line items with sku, name and quantity shipped.",
            "tracks": "Tracking records attached to the shipment (carrier code, title, tracking number).",
            "packages": "Packages the shipment was split into.",
        },
    },
    "creditmemos": {
        "description": "Credit memos (refunds) issued against orders, recording refunded amounts and returned items.",
        "docs_url": f"{_REST_DOCS}/creditmemos",
        "columns": {
            "entity_id": "Internal numeric identifier of the credit memo.",
            "increment_id": "Human-readable credit memo number.",
            "order_id": "Identifier of the order the credit memo belongs to.",
            "state": "Credit memo state (1 = open, 2 = refunded, 3 = canceled).",
            "store_id": "Store view the credit memo belongs to.",
            "grand_total": "Total refunded in the order currency.",
            "base_grand_total": "Total refunded in the store's base currency.",
            "subtotal": "Sum of the refunded line item row totals.",
            "tax_amount": "Tax refunded.",
            "shipping_amount": "Shipping refunded.",
            "adjustment": "Net manual adjustment applied to the refund.",
            "created_at": "Timestamp the credit memo was created (UTC).",
            "updated_at": "Timestamp the credit memo row was last modified (UTC).",
            "items": "Refunded line items with sku, quantity refunded and row totals.",
        },
    },
    "transactions": {
        "description": "Payment gateway transactions recorded against order payments (authorization, capture, refund, void).",
        "docs_url": f"{_REST_DOCS}/transactions",
        "columns": {
            "transaction_id": "Internal numeric identifier of the transaction.",
            "parent_id": "Identifier of the parent transaction, when this one was derived from another.",
            "order_id": "Identifier of the order the transaction belongs to.",
            "payment_id": "Identifier of the order payment record the transaction belongs to.",
            "txn_id": "Transaction identifier assigned by the payment gateway.",
            "parent_txn_id": "Gateway identifier of the parent transaction.",
            "txn_type": "Transaction type (order, authorization, capture, void, refund).",
            "is_closed": "1 when no further operations are possible on this transaction.",
            "additional_information": "Raw gateway response data stored with the transaction.",
            "created_at": "Timestamp the transaction was recorded (UTC).",
        },
    },
    "products": {
        "description": "Catalog products with their type, price, status, attribute set, custom attributes and media.",
        "docs_url": f"{_REST_DOCS}/products",
        "columns": {
            "id": "Internal numeric identifier of the product.",
            "sku": "Stock keeping unit, the store-unique product code.",
            "name": "Product name.",
            "attribute_set_id": "Attribute set the product's attributes come from.",
            "price": "Product price in the store's base currency.",
            "status": "Product status (1 = enabled, 2 = disabled).",
            "visibility": "Catalog visibility (1 = not visible, 2 = catalog, 3 = search, 4 = catalog and search).",
            "type_id": "Product type (simple, configurable, bundle, grouped, virtual, downloadable).",
            "weight": "Product weight.",
            "created_at": "Timestamp the product was created (UTC).",
            "updated_at": "Timestamp the product was last modified (UTC).",
            "custom_attributes": "EAV attribute values that are not part of the fixed product interface.",
            "media_gallery_entries": "Images and video attached to the product.",
            "extension_attributes": "Extension data such as stock item, category links, website ids and configurable options.",
            "product_links": "Related, up-sell and cross-sell links to other products.",
            "tier_prices": "Quantity- and group-based tier pricing rows.",
        },
    },
    "categories": {
        "description": "Catalog categories, one row per category in the tree, with its position, level and path.",
        "docs_url": f"{_REST_DOCS}/categories",
        "columns": {
            "id": "Internal numeric identifier of the category.",
            "parent_id": "Identifier of the parent category.",
            "name": "Category name.",
            "is_active": "Whether the category is enabled in the storefront.",
            "position": "Sort position among its siblings.",
            "level": "Depth in the category tree, starting at the root.",
            "path": "Slash-separated list of ancestor ids down to this category.",
            "children": "Comma-separated identifiers of the direct child categories.",
            "include_in_menu": "Whether the category appears in the storefront navigation.",
            "created_at": "Timestamp the category was created (UTC).",
            "updated_at": "Timestamp the category was last modified (UTC).",
            "custom_attributes": "EAV attribute values such as url_key, description and display settings.",
        },
    },
    "customers": {
        "description": "Registered customer accounts with their identity, group, store scope and addresses.",
        "docs_url": f"{_REST_DOCS}/customers",
        "columns": {
            "id": "Internal numeric identifier of the customer.",
            "email": "Customer email address, unique within the website.",
            "firstname": "Customer first name.",
            "lastname": "Customer last name.",
            "group_id": "Customer group the account belongs to.",
            "store_id": "Store view the account was created in.",
            "website_id": "Website the account belongs to.",
            "created_in": "Name of the store view the account was created in.",
            "confirmation": "Account confirmation key, set while confirmation is pending.",
            "disable_auto_group_change": "1 when automatic group assignment (e.g. by VAT) is disabled.",
            "created_at": "Timestamp the account was created (UTC).",
            "updated_at": "Timestamp the account was last modified (UTC).",
            "addresses": "Address book entries belonging to the customer.",
            "default_billing": "Identifier of the customer's default billing address.",
            "default_shipping": "Identifier of the customer's default shipping address.",
            "custom_attributes": "EAV attribute values that are not part of the fixed customer interface.",
        },
    },
    "carts": {
        "description": "Shopping carts (quotes), including active carts and the abandoned ones left behind at checkout.",
        "docs_url": f"{_REST_DOCS}/carts",
        "columns": {
            "id": "Internal numeric identifier of the cart (quote).",
            "store_id": "Store view the cart belongs to.",
            "is_active": "Whether the cart is still active, as opposed to converted or abandoned.",
            "is_virtual": "Whether the cart contains only virtual or downloadable products.",
            "items_count": "Number of distinct line items in the cart.",
            "items_qty": "Total quantity across the cart's line items.",
            "customer": "Customer the cart belongs to, or the guest details captured at checkout.",
            "currency": "Base, store, quote and global currency codes with their conversion rates.",
            "customer_is_guest": "1 when the cart belongs to a guest rather than a registered customer.",
            "orig_order_id": "Identifier of the order this cart was reordered from, if any.",
            "converted_at": "Timestamp the cart was converted into an order (UTC).",
            "created_at": "Timestamp the cart was created (UTC).",
            "updated_at": "Timestamp the cart was last modified (UTC).",
            "items": "Cart line items with sku, name, quantity and prices.",
        },
    },
    "coupons": {
        "description": "Coupon codes attached to cart price rules, including auto-generated codes and their usage limits.",
        "docs_url": f"{_REST_DOCS}/coupons",
        "columns": {
            "coupon_id": "Internal numeric identifier of the coupon.",
            "rule_id": "Identifier of the cart price rule the coupon belongs to.",
            "code": "The coupon code a shopper enters at checkout.",
            "usage_limit": "Maximum number of times the coupon can be used overall.",
            "usage_per_customer": "Maximum number of times a single customer can use the coupon.",
            "times_used": "Number of times the coupon has been redeemed.",
            "expiration_date": "Date the coupon stops working.",
            "is_primary": "1 when this is the rule's primary coupon rather than a generated one.",
            "type": "Coupon type (0 = manually specified, 1 = auto-generated).",
            "created_at": "Timestamp the coupon was created (UTC).",
        },
    },
    "customer_groups": {
        "description": "Customer groups used for pricing, tax classes and cart price rule targeting.",
        "docs_url": f"{_REST_DOCS}/customerGroups",
        "columns": {
            "id": "Internal numeric identifier of the customer group.",
            "code": "Display name of the group (e.g. General, Wholesale, NOT LOGGED IN).",
            "tax_class_id": "Identifier of the tax class applied to members of the group.",
            "tax_class_name": "Name of the tax class applied to members of the group.",
        },
    },
    "product_attributes": {
        "description": "Product EAV attribute definitions, describing every field the catalog can store on a product.",
        "docs_url": f"{_REST_DOCS}/productsattributes",
        "columns": {
            "attribute_id": "Internal numeric identifier of the attribute.",
            "attribute_code": "Machine name of the attribute, used as the key in product custom_attributes.",
            "frontend_input": "Input type rendered for the attribute (text, select, boolean, price, ...).",
            "default_frontend_label": "Default admin label of the attribute.",
            "frontend_labels": "Per-store-view labels of the attribute.",
            "is_required": "Whether the attribute must be filled in.",
            "is_unique": "Whether the attribute value must be unique across products.",
            "scope": "Scope the value is stored at (global, website or store).",
            "backend_type": "Storage type of the value (varchar, int, decimal, datetime, text, static).",
            "options": "Selectable option values, for select and multiselect attributes.",
            "is_user_defined": "Whether the attribute was created by an admin rather than shipped with Magento.",
        },
    },
    "tax_classes": {
        "description": "Tax classes that products and customer groups are assigned to when calculating tax rules.",
        "docs_url": f"{_REST_DOCS}/taxClasses",
        "columns": {
            "class_id": "Internal numeric identifier of the tax class.",
            "class_name": "Display name of the tax class.",
            "class_type": "Whether the class applies to PRODUCT or CUSTOMER.",
        },
    },
    "store_views": {
        "description": "Store views configured on the instance — the storefront scope that localizes catalog and prices.",
        "docs_url": f"{_REST_DOCS}/store",
        "columns": {
            "id": "Internal numeric identifier of the store view.",
            "code": "Store view code, used as the scope segment in REST paths.",
            "name": "Display name of the store view.",
            "website_id": "Website the store view belongs to.",
            "store_group_id": "Store group the store view belongs to.",
            "is_active": "Whether the store view is enabled.",
        },
    },
    "store_groups": {
        "description": "Store groups, the middle scope that binds a root category to a set of store views.",
        "docs_url": f"{_REST_DOCS}/store",
        "columns": {
            "id": "Internal numeric identifier of the store group.",
            "code": "Store group code.",
            "name": "Display name of the store group.",
            "website_id": "Website the store group belongs to.",
            "root_category_id": "Root catalog category the group's store views browse.",
            "default_store_id": "Store view used by default for this group.",
        },
    },
    "websites": {
        "description": "Websites configured on the instance — the outermost scope, owning customer accounts and base currency.",
        "docs_url": f"{_REST_DOCS}/store",
        "columns": {
            "id": "Internal numeric identifier of the website.",
            "code": "Website code.",
            "name": "Display name of the website.",
            "default_group_id": "Store group used by default for this website.",
        },
    },
    "countries": {
        "description": "Directory of countries the instance knows about, with their ISO codes, locale names and regions.",
        "docs_url": f"{_REST_DOCS}/directory",
        "columns": {
            "id": "ISO 3166-1 alpha-2 country code, used as the identifier.",
            "two_letter_abbreviation": "ISO 3166-1 alpha-2 country code.",
            "three_letter_abbreviation": "ISO 3166-1 alpha-3 country code.",
            "full_name_locale": "Country name in the admin locale.",
            "full_name_english": "Country name in English.",
            "available_regions": "Regions or states defined for the country.",
        },
    },
}
