[package]
name = "common-grpc"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
futures = { workspace = true }
http = { workspace = true }
metrics = { workspace = true }
pin-project = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
tower = { workspace = true, features = ["util"] }

[lints]
workspace = true
