from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Descriptions sourced from the Fireworks AI API reference (https://docs.fireworks.ai/api-reference).
# Keyed by endpoint name as returned by get_schemas / declared in settings.ENDPOINTS.

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "models": {
        "description": "Models available in your Fireworks AI account, including base models and fine-tuned (PEFT addon) models.",
        "docs_url": "https://docs.fireworks.ai/api-reference/list-models",
        "columns": {
            "name": "Unique resource name of the model, e.g. accounts/my-account/models/my-model.",
            "displayName": "Human-readable display name of the model.",
            "description": "Free-text description of the model.",
            "createTime": "When the model was created.",
            "updateTime": "When the model was last updated.",
            "state": "Lifecycle state of the model (UPLOADING, READY).",
            "kind": "Kind of model (e.g. HF_BASE_MODEL, HF_PEFT_ADDON, EMBEDDING_MODEL).",
            "contextLength": "Maximum context length supported by the model.",
            "supportsImageInput": "Whether the model accepts image input.",
            "supportsTools": "Whether the model supports tool/function calling.",
            "supportsLora": "Whether the model supports LoRA addons.",
            "supportsServerless": "Whether the model can be served serverlessly.",
            "fineTuningJob": "Resource name of the fine-tuning job that produced the model, if any.",
            "public": "Whether the model is publicly visible.",
            "deprecationDate": "Date the model is or will be deprecated, if scheduled.",
        },
    },
    "datasets": {
        "description": "Datasets uploaded to or generated in your Fireworks AI account for fine-tuning and evaluation.",
        "docs_url": "https://docs.fireworks.ai/api-reference/list-datasets",
        "columns": {
            "name": "Unique resource name of the dataset, e.g. accounts/my-account/datasets/my-dataset.",
            "displayName": "Human-readable display name of the dataset.",
            "createTime": "When the dataset was created.",
            "updateTime": "When the dataset was last updated.",
            "state": "Lifecycle state of the dataset (UPLOADING, READY).",
            "status": "Code and message describing the latest operation's outcome.",
            "exampleCount": "Number of examples in the dataset.",
            "format": "Dataset format (CHAT, COMPLETION, RL).",
            "createdBy": "Identity of the user who created the dataset.",
            "sourceJobName": "Resource name of the job that generated the dataset, if any.",
            "estimatedTokenCount": "Estimated number of tokens in the dataset.",
        },
    },
    "deployments": {
        "description": "Dedicated model deployments in your Fireworks AI account, including autoscaling and hardware configuration.",
        "docs_url": "https://docs.fireworks.ai/api-reference/list-deployments",
        "columns": {
            "name": "Unique resource name of the deployment, e.g. accounts/my-account/deployments/my-deployment.",
            "displayName": "Human-readable display name of the deployment.",
            "createTime": "When the deployment was created.",
            "updateTime": "When the deployment was last updated.",
            "state": "Lifecycle state of the deployment (CREATING, READY, DELETING, FAILED, UPDATING, DELETED).",
            "status": "Code and message describing the latest operation's outcome.",
            "baseModel": "Resource name of the model being served.",
            "minReplicaCount": "Autoscaling floor for the number of replicas.",
            "maxReplicaCount": "Autoscaling ceiling for the number of replicas.",
            "replicaCount": "Current number of replicas.",
            "acceleratorCount": "Number of accelerators (GPUs) per replica.",
            "acceleratorType": "Accelerator hardware type (e.g. A100, H100, MI300X).",
            "precision": "Serving precision (e.g. FP16, FP8, BF16).",
            "region": "Region the deployment currently runs in.",
        },
    },
    "deployed_models": {
        "description": "Models loaded onto deployments (including LoRA addons), mapping each model to the deployment serving it.",
        "docs_url": "https://docs.fireworks.ai/api-reference/list-deployed-models",
        "columns": {
            "name": "Unique resource name of the deployed model, e.g. accounts/my-account/deployedModels/my-deployed-model.",
            "displayName": "Human-readable display name of the deployed model.",
            "createTime": "When the deployed model was created.",
            "updateTime": "When the deployed model was last updated.",
            "model": "Resource name of the model being deployed.",
            "deployment": "Resource name of the deployment serving the model.",
            "default": "Whether this target is used when the model is queried without a deployment suffix.",
            "state": "Lifecycle state (DEPLOYING, DEPLOYED, UPDATING, UNDEPLOYING).",
            "serverless": "Whether the underlying deployment is managed by Fireworks.",
            "public": "Whether the deployed model is publicly reachable.",
        },
    },
    "routers": {
        "description": "Routers in your Fireworks AI account. A router distributes inference traffic across deployments for A/B testing, traffic migration, and load distribution, and is what a request's model alias resolves to.",
        "docs_url": "https://docs.fireworks.ai/api-reference/list-routers",
        "columns": {
            "name": "Unique resource name of the router, e.g. accounts/my-account/routers/my-router.",
            "displayName": "Human-readable display name of the router.",
            "createTime": "When the router was created.",
            "createdBy": "Identity of the user who created the router.",
            "state": "Lifecycle state of the router (CREATING, READY, UPDATING, DELETING).",
            "status": "Code and message describing the latest operation's outcome.",
            "deployments": "Resource names of the deployments the router covers.",
            "model": "Resource name of the model requests are routed to. Only set for single-region deployments.",
            "weightedRandom": "Weighted-random routing strategy, when the router uses one.",
            "evenLoad": "Even-load routing strategy, when the router uses one.",
            "aliases": "Alias names that can be used to route requests through this router.",
            "autoGenerated": "Whether Fireworks generated this router for a deployment. Auto-generated routers cannot be updated or deleted.",
            "public": "Whether any account can query the underlying workload, rather than only the owning account.",
        },
    },
    "supervised_fine_tuning_jobs": {
        "description": "Supervised fine-tuning (SFT) jobs run in your Fireworks AI account, with training configuration and progress.",
        "docs_url": "https://docs.fireworks.ai/api-reference/list-supervised-fine-tuning-jobs",
        "columns": {
            "name": "Unique resource name of the fine-tuning job.",
            "displayName": "Human-readable display name of the job.",
            "createTime": "When the job was created.",
            "completedTime": "When the job finished.",
            "updateTime": "When the job was last updated.",
            "state": "Job lifecycle state (e.g. JOB_STATE_RUNNING, JOB_STATE_COMPLETED, JOB_STATE_FAILED).",
            "status": "Code and message describing the latest operation's outcome.",
            "createdBy": "Email of the user who created the job.",
            "dataset": "Resource name of the training dataset.",
            "evaluationDataset": "Resource name of the evaluation dataset, if any.",
            "baseModel": "Resource name of the base model being fine-tuned.",
            "outputModel": "Resource name of the model produced by the job.",
            "epochs": "Number of training epochs.",
            "learningRate": "Training learning rate.",
            "loraRank": "LoRA rank used for training.",
            "jobProgress": "Progress details for the job.",
            "estimatedCost": "Estimated cost of the job.",
        },
    },
    "reinforcement_fine_tuning_jobs": {
        "description": "Reinforcement fine-tuning (RFT) jobs run in your Fireworks AI account, with training/rollout configuration and progress.",
        "docs_url": "https://docs.fireworks.ai/api-reference/list-reinforcement-fine-tuning-jobs",
        "columns": {
            "name": "Unique resource name of the reinforcement fine-tuning job.",
            "displayName": "Human-readable display name of the job.",
            "createTime": "When the job was created.",
            "completedTime": "When the job finished.",
            "state": "Job lifecycle state (e.g. running, completed, failed).",
            "status": "Code and message describing the latest operation's outcome.",
            "createdBy": "Email of the user who created the job.",
            "dataset": "Resource name of the training dataset.",
            "evaluator": "Resource name of the evaluator used to score rollouts.",
            "trainingConfig": "Common training settings (base model, learning rate, LoRA, epochs).",
            "jobProgress": "Progress details for the job.",
            "outputMetrics": "Output metrics of the job.",
        },
    },
    "reinforcement_fine_tuning_steps": {
        "description": "Reinforcement fine-tuning steps (RLOR trainer jobs) in your Fireworks AI account. Each row is one training step under a reinforcement fine-tuning job, so the table holds the per-step progression behind a job's outcome.",
        "docs_url": "https://docs.fireworks.ai/api-reference/list-reinforcement-fine-tuning-steps",
        "columns": {
            "name": "Unique resource name of the step, e.g. accounts/my-account/rlorTrainerJobs/my-job.",
            "displayName": "Human-readable display name of the step.",
            "createTime": "When the step was created.",
            "completedTime": "When the step finished.",
            "state": "Job lifecycle state (e.g. running, completed, failed).",
            "status": "Code and message describing the latest operation's outcome.",
            "createdBy": "Email of the user who created the step.",
            "dataset": "Resource name of the training dataset.",
            "evaluationDataset": "Resource name of a separate evaluation dataset, if any.",
            "evalAutoCarveout": "Whether the dataset is auto-carved for evaluation.",
            "trainingConfig": "Common training settings (base model, learning rate, LoRA, epochs).",
            "rewardWeights": "Reward metrics used for training, each as <reward_name>=<weight>.",
            "jobProgress": "Progress details for the step.",
            "rolloutDeploymentName": "Deployment the trainer syncs weights to for rollouts, if set.",
            "nodeCount": "Number of nodes used for the step.",
            "acceleratorSeconds": "Accelerator seconds used, keyed by accelerator type (e.g. NVIDIA_H100_80GB).",
            "serviceMode": "Whether the trainer is deployed as a service exposing tinker-style API endpoints.",
            "trainerReplicaCount": "Data-parallel replica count for service-mode trainers.",
            "keepAlive": "Whether the trainer runs in keep-alive mode.",
            "forwardOnly": "Whether the trainer runs forward-only, with no backward or optimizer pass.",
            "inactivityTimeout": "How long the trainer may go without tracked activity before it is stopped automatically.",
            "encryptionState": "CMEK encryption state, stamped at creation.",
            "purpose": "Scheduling purpose for the step.",
        },
    },
    "dpo_jobs": {
        "description": "Preference optimization (DPO and ORPO) fine-tuning jobs in your Fireworks AI account, the third job type alongside supervised and reinforcement fine-tuning.",
        "docs_url": "https://docs.fireworks.ai/api-reference/list-dpo-jobs",
        "columns": {
            "name": "Unique resource name of the DPO job, e.g. accounts/my-account/dpoJobs/my-job.",
            "displayName": "Human-readable display name of the job.",
            "createTime": "When the job was created.",
            "completedTime": "When the job finished.",
            "state": "Job lifecycle state (e.g. running, completed, failed).",
            "status": "Code and message describing the latest operation's outcome.",
            "createdBy": "Email of the user who created the job.",
            "dataset": "Resource name of the training dataset of preferred and non-preferred response pairs.",
            "trainingConfig": "Common training settings (base model, learning rate, LoRA, epochs).",
            "lossConfig": "Loss configuration for the job. Defaults to DPO loss; ORPO when the method is set to ORPO.",
            "wandbConfig": "Weights & Biases account used to log job progress.",
            "purpose": "Scheduling purpose for the job.",
            "useReservation": "Whether the job tries the account's reserved capacity before falling back to shared trainer capacity.",
        },
    },
    "batch_inference_jobs": {
        "description": "Batch inference jobs run in your Fireworks AI account, mapping input datasets to output datasets.",
        "docs_url": "https://docs.fireworks.ai/api-reference/list-batch-inference-jobs",
        "columns": {
            "name": "Unique resource name of the batch inference job.",
            "displayName": "Human-readable display name of the job.",
            "createTime": "When the job was created.",
            "updateTime": "When the job was last updated.",
            "state": "Job lifecycle state (e.g. RUNNING, COMPLETED, FAILED).",
            "status": "Code and message describing the latest operation's outcome.",
            "createdBy": "Email of the user who started the job.",
            "model": "Model used for inference.",
            "inputDatasetId": "Dataset supplying the inputs.",
            "outputDatasetId": "Dataset holding the results (also contains the error file).",
            "inferenceParameters": "Sampling settings (maxTokens, temperature, topP, topK, n).",
            "precision": "Serving precision used for the job.",
            "jobProgress": "Progress stats (percent, request counts, token counts, output rows).",
        },
    },
    "evaluation_jobs": {
        "description": "Evaluation jobs run in your Fireworks AI account, scoring a dataset with an evaluator.",
        "docs_url": "https://docs.fireworks.ai/api-reference/list-evaluation-jobs",
        "columns": {
            "name": "Unique resource name of the evaluation job.",
            "displayName": "Human-readable display name of the job.",
            "createTime": "When the job was created.",
            "updateTime": "When the job was last updated.",
            "state": "Job lifecycle state (e.g. running, completed, failed).",
            "status": "Code and message describing the latest operation's outcome.",
            "createdBy": "Identity of the user who created the job.",
            "evaluator": "Resource name of the evaluator used.",
            "inputDataset": "Resource name of the input dataset.",
            "outputDataset": "Resource name of the dataset created by the job.",
            "metrics": "Map of metric names to numeric values.",
        },
    },
    "evaluators": {
        "description": "Evaluators defined in your Fireworks AI account, used to score fine-tuning rollouts and evaluation jobs.",
        "docs_url": "https://docs.fireworks.ai/api-reference/list-evaluators",
        "columns": {
            "name": "Unique resource name of the evaluator.",
            "displayName": "Human-readable display name of the evaluator.",
            "description": "Free-text description of the evaluator.",
            "createTime": "When the evaluator was created.",
            "updateTime": "When the evaluator was last updated.",
            "createdBy": "Identity of the user who created the evaluator.",
            "state": "Lifecycle state (ACTIVE, BUILDING, BUILD_FAILED).",
            "criteria": "Scoring criteria, each producing a score for its metric.",
            "entryPoint": "Code entry point in module::function or path::function format.",
            "commitHash": "Commit hash from the user's original codebase.",
        },
    },
    "users": {
        "description": "Users and service accounts with access to your Fireworks AI account.",
        "docs_url": "https://docs.fireworks.ai/api-reference/list-users",
        "columns": {
            "name": "Unique resource name of the user, e.g. accounts/my-account/users/my-user.",
            "displayName": "Human-readable display name of the user.",
            "createTime": "When the user was added to the account.",
            "updateTime": "When the user was last updated.",
            "email": "Email address of the user.",
            "role": "Role of the user in the account (admin, user, contributor, inference-user, or custom).",
            "serviceAccount": "Whether this user is a service account.",
            "state": "Lifecycle state of the user (CREATING, READY, UPDATING, DELETING).",
            "status": "Code and message describing the latest operation's outcome.",
        },
    },
    "account_usage": {
        "description": "Daily token and spend usage for your Fireworks AI account, from the billingUsage report. One row is one usage bucket for one day. `usageCategory` names which billed surface the row measures, and the columns a row fills depend on it: serverless rows carry token counts, dedicated rows carry accelerator seconds, and training rows carry whichever the job type bills on.",
        "docs_url": "https://docs.fireworks.ai/api-reference/get-billing-usage",
        "columns": {
            "id": "Synthesized identifier for the bucket, derived from the usage category, the day, and the bucket's dimension fields. Not returned by the API.",
            "usageCategory": "Which billed surface the row measures: serverless, dedicated, or training.",
            "startTime": "Start of the usage bucket. Buckets are aggregated daily, so only the date is meaningful.",
            "endTime": "End of the usage bucket. Buckets are aggregated daily, so only the date is meaningful.",
            "group": "Group-by dimension key-values for the bucket, such as model_name, api_key_id, user_id, or deployment_name.",
            "usageType": "Billing usage type for the bucket, distinguishing inference, deployment, and training kinds.",
            "modelName": 'Model the serverless usage was attributed to. Deprecated by the API in favor of group["model_name"].',
            "apiKeyId": 'API key the serverless usage was attributed to. Deprecated by the API in favor of group["api_key_id"].',
            "promptTokens": "Prompt tokens billed for text inference.",
            "completionTokens": "Completion tokens billed for text inference.",
            "cachedPromptTokens": "Prompt tokens served from cache, a subset of promptTokens.",
            "uncachedPromptTokens": "Prompt tokens not served from cache.",
            "audioInputSeconds": "Audio input seconds billed for audio inference.",
            "costNanoUsd": "Cost in nano-USD (1e-9 USD). 0 when the provider stamps no authoritative cost, which does not mean the usage was free.",
            "deploymentId": "Deployment the dedicated usage was attributed to.",
            "acceleratorType": "GPU or accelerator type billed (e.g. NVIDIA_H100_80GB).",
            "acceleratorSeconds": "Accelerator seconds billed. Divide by 3600 for GPU hours.",
            "placement": "Where the deployment ran (e.g. US_IOWA_1, GLOBAL, US, EUROPE).",
            "baseModel": "Base model of the deployment or training job, when known.",
            "jobId": "Managed training job the usage was attributed to. Empty for serverless training token rows.",
            "trainingSessionId": "Serverless training session the usage was attributed to. Empty for managed training jobs.",
            "jobType": "Kind of training job (sft, dpo, rft, trainer).",
            "tokens": "Total tokens billed for the training bucket. 0 for accelerator-second usage types.",
            "annotations": "Custom annotations carried on the usage, such as team, project, or environment.",
        },
    },
}
