"""Canonical, documentation-sourced descriptions for QuickBooks Online entities and columns.

Sourced from Intuit's Accounting API reference
(https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/account). Keyed by
the entity names in `settings.py` `QUICKBOOKS_ENTITIES`, which match the `ExternalDataSchema.name`
of a synced QuickBooks table. Columns absent here fall back to LLM enrichment.

`CreateTime` and `LastUpdatedTime` are documented once below and shared by every entity, because
the transport hoists them out of the `MetaData` complex type onto the row root.
"""

from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

_DOCS_ROOT = "https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities"

_SHARED_COLUMNS = {
    "Id": "Unique identifier for the object within this QuickBooks company.",
    "SyncToken": "Version number of the object, used for optimistic locking on updates.",
    "MetaData": "Descriptive metadata for the object, holding its creation and last-update timestamps.",
    "CreateTime": "Time the object was created, hoisted from MetaData.",
    "LastUpdatedTime": "Time the object was last modified, hoisted from MetaData.",
    "domain": "Origin of the object, `QBO` for QuickBooks Online.",
    "sparse": "Whether the payload is a sparse representation carrying only a subset of fields.",
}

_LINE_COLUMNS = {
    "Line": "Line items of the transaction, each with an amount, detail type, and referenced item or account.",
    "TxnDate": "Date the transaction was entered, which drives the accounting period it lands in.",
    "CurrencyRef": "Currency the transaction is recorded in.",
    "ExchangeRate": "Rate used to convert the transaction currency to the company's home currency.",
    "TotalAmt": "Total amount of the transaction, including tax.",
    "DocNumber": "Reference number for the transaction, unique per transaction type.",
    "PrivateNote": "Internal note on the transaction, not visible to the customer or vendor.",
    "CustomerMemo": "Message displayed to the customer on the transaction.",
    "TxnTaxDetail": "Sales-tax detail for the transaction, including the total tax and per-rate breakdown.",
    "LinkedTxn": "Transactions linked to this one, such as the invoice a payment is applied to.",
    "DepartmentRef": "Department or location the transaction is assigned to.",
}


def _columns(*groups: dict[str, str], **extra: str) -> dict[str, str]:
    merged: dict[str, str] = {}
    for group in groups:
        merged.update(group)
    merged.update(extra)
    return merged


CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "Account": {
        "description": "A chart-of-accounts entry tracking a category of assets, liabilities, income, or expenses.",
        "docs_url": f"{_DOCS_ROOT}/account",
        "columns": _columns(
            _SHARED_COLUMNS,
            Name="Name of the account, unique among its siblings.",
            FullyQualifiedName="Name of the account prefixed by its parent accounts, colon-separated.",
            AccountType="High-level classification of the account, such as Bank, Income, or Expense.",
            AccountSubType="Finer classification within the account type.",
            Classification="Whether the account is an Asset, Liability, Equity, Revenue, or Expense.",
            AcctNum="User-assigned account number from the chart of accounts.",
            Description="Free-text description of what the account is for.",
            Active="Whether the account is active and available for new transactions.",
            SubAccount="Whether the account is a child of another account.",
            ParentRef="Parent account when this account is a sub-account.",
            CurrentBalance="Balance of the account, including sub-account balances for parent accounts.",
            CurrentBalanceWithSubAccounts="Balance of the account plus all of its sub-accounts.",
            CurrencyRef="Currency the account's balances are held in.",
        ),
    },
    "Attachable": {
        "description": "A file or note attached to a QuickBooks transaction or entity.",
        "docs_url": f"{_DOCS_ROOT}/attachable",
        "columns": _columns(
            _SHARED_COLUMNS,
            FileName="Name of the attached file.",
            FileAccessUri="Path used to fetch the attachment's content.",
            TempDownloadUri="Short-lived URL for downloading the attachment.",
            Size="Size of the attached file in bytes.",
            ContentType="MIME type of the attached file.",
            Category="Category of the attachment, such as Image, Document, or Signature.",
            Note="Free-text note stored on the attachment.",
            AttachableRef="Entities this attachment is linked to.",
            Lat="Latitude captured when the attachment was created.",
            Long="Longitude captured when the attachment was created.",
        ),
    },
    "Bill": {
        "description": "An accounts-payable transaction recording money owed to a vendor for goods or services.",
        "docs_url": f"{_DOCS_ROOT}/bill",
        "columns": _columns(
            _SHARED_COLUMNS,
            _LINE_COLUMNS,
            VendorRef="Vendor the bill is owed to.",
            APAccountRef="Accounts-payable account the bill is posted to.",
            SalesTermRef="Payment terms applied to the bill.",
            DueDate="Date payment on the bill is due.",
            Balance="Unpaid amount remaining on the bill.",
        ),
    },
    "BillPayment": {
        "description": "A payment made against one or more vendor bills.",
        "docs_url": f"{_DOCS_ROOT}/billpayment",
        "columns": _columns(
            _SHARED_COLUMNS,
            _LINE_COLUMNS,
            VendorRef="Vendor being paid.",
            PayType="How the payment was made, either Check or CreditCard.",
            CheckPayment="Bank-account and print details when the payment type is Check.",
            CreditCardPayment="Credit-card account details when the payment type is CreditCard.",
            APAccountRef="Accounts-payable account the payment is applied against.",
        ),
    },
    "Budget": {
        "description": "A budget defining expected amounts per account and period for a fiscal year.",
        "docs_url": f"{_DOCS_ROOT}/budget",
        "columns": _columns(
            _SHARED_COLUMNS,
            Name="Name of the budget.",
            StartDate="First date covered by the budget.",
            EndDate="Last date covered by the budget.",
            BudgetType="Basis of the budget, such as ProfitAndLoss or BalanceSheet.",
            BudgetEntryType="Granularity of the budget entries, such as Monthly or Quarterly.",
            Active="Whether the budget is active.",
            BudgetDetail="Per-account, per-period budgeted amounts.",
        ),
    },
    "Class": {
        "description": "A class used to tag transactions for tracking income and expenses by segment.",
        "docs_url": f"{_DOCS_ROOT}/class",
        "columns": _columns(
            _SHARED_COLUMNS,
            Name="Name of the class, unique among its siblings.",
            FullyQualifiedName="Name of the class prefixed by its parent classes, colon-separated.",
            Active="Whether the class is active and available for new transactions.",
            SubClass="Whether the class is a child of another class.",
            ParentRef="Parent class when this class is a sub-class.",
        ),
    },
    "CompanyInfo": {
        "description": "Company-level profile and preferences for the connected QuickBooks company. One row.",
        "docs_url": f"{_DOCS_ROOT}/companyinfo",
        "columns": _columns(
            _SHARED_COLUMNS,
            CompanyName="Legal or display name of the company.",
            LegalName="Legal name of the company as filed.",
            CompanyAddr="Primary address of the company.",
            CustomerCommunicationAddr="Address shown to customers on sales forms.",
            LegalAddr="Legal address of the company.",
            CompanyStartDate="Date the company file's books begin.",
            FiscalYearStartMonth="Month the company's fiscal year starts.",
            Country="Country the company is registered in.",
            Email="Primary email address for the company.",
            WebAddr="Company website.",
            PrimaryPhone="Primary phone number for the company.",
            SupportedLanguages="Languages the company file supports.",
            NameValue="Additional company preferences as name/value pairs.",
        ),
    },
    "CreditMemo": {
        "description": "A credit issued to a customer that can be applied against their open invoices.",
        "docs_url": f"{_DOCS_ROOT}/creditmemo",
        "columns": _columns(
            _SHARED_COLUMNS,
            _LINE_COLUMNS,
            CustomerRef="Customer the credit is issued to.",
            CustomerMemo="Message displayed to the customer on the credit memo.",
            BillAddr="Billing address on the credit memo.",
            ShipAddr="Shipping address on the credit memo.",
            RemainingCredit="Portion of the credit not yet applied to an invoice.",
            Balance="Unapplied balance of the credit memo.",
            ProjectRef="Project the credit memo is associated with.",
        ),
    },
    "Customer": {
        "description": "A customer or sub-customer (job) that sales transactions are recorded against.",
        "docs_url": f"{_DOCS_ROOT}/customer",
        "columns": _columns(
            _SHARED_COLUMNS,
            DisplayName="Name shown for the customer, unique across the company.",
            CompanyName="Company name for the customer.",
            GivenName="Customer's first name.",
            FamilyName="Customer's last name.",
            MiddleName="Customer's middle name.",
            Title="Salutation for the customer, such as Mr or Ms.",
            Suffix="Name suffix for the customer.",
            FullyQualifiedName="Display name prefixed by parent customers, colon-separated.",
            PrintOnCheckName="Name to print on checks issued to the customer.",
            Active="Whether the customer is active.",
            PrimaryEmailAddr="Customer's primary email address.",
            PrimaryPhone="Customer's primary phone number.",
            AlternatePhone="Customer's alternate phone number.",
            Mobile="Customer's mobile phone number.",
            Fax="Customer's fax number.",
            WebAddr="Customer's website.",
            BillAddr="Default billing address for the customer.",
            ShipAddr="Default shipping address for the customer.",
            Notes="Free-text notes about the customer.",
            Balance="Open balance the customer owes, excluding sub-customers.",
            BalanceWithJobs="Open balance the customer owes, including sub-customers and jobs.",
            CurrencyRef="Currency transactions with this customer are recorded in.",
            Taxable="Whether sales to the customer are subject to sales tax.",
            DefaultTaxCodeRef="Default sales-tax code applied to the customer's transactions.",
            SalesTermRef="Default payment terms for the customer.",
            PaymentMethodRef="Default payment method for the customer.",
            Job="Whether the record is a sub-customer representing a job.",
            ParentRef="Parent customer when this record is a sub-customer.",
            Level="Depth of the customer in the parent hierarchy.",
        ),
    },
    "Department": {
        "description": "A department or location used to categorize transactions.",
        "docs_url": f"{_DOCS_ROOT}/department",
        "columns": _columns(
            _SHARED_COLUMNS,
            Name="Name of the department, unique among its siblings.",
            FullyQualifiedName="Name prefixed by parent departments, colon-separated.",
            Active="Whether the department is active.",
            SubDepartment="Whether the department is a child of another department.",
            ParentRef="Parent department when this is a sub-department.",
        ),
    },
    "Deposit": {
        "description": "A deposit recording funds paid into one of the company's accounts.",
        "docs_url": f"{_DOCS_ROOT}/deposit",
        "columns": _columns(
            _SHARED_COLUMNS,
            _LINE_COLUMNS,
            DepositToAccountRef="Account the funds were deposited into.",
            CashBack="Cash-back portion held out of the deposit.",
            TxnSource="System that originated the transaction.",
        ),
    },
    "Employee": {
        "description": "An employee of the company, used for time tracking and payroll references.",
        "docs_url": f"{_DOCS_ROOT}/employee",
        "columns": _columns(
            _SHARED_COLUMNS,
            DisplayName="Name shown for the employee.",
            GivenName="Employee's first name.",
            FamilyName="Employee's last name.",
            MiddleName="Employee's middle name.",
            PrintOnCheckName="Name to print on checks issued to the employee.",
            Active="Whether the employee is active.",
            PrimaryPhone="Employee's primary phone number.",
            PrimaryEmailAddr="Employee's email address.",
            PrimaryAddr="Employee's address.",
            EmployeeNumber="Employee number assigned by the company.",
            SSN="Masked social security number for the employee.",
            HiredDate="Date the employee was hired.",
            ReleasedDate="Date the employee left the company.",
            BillableTime="Whether the employee's time is billable to customers.",
            BillRate="Default hourly rate billed for the employee's time.",
            Organization="Whether the employee record represents an organization rather than a person.",
        ),
    },
    "Estimate": {
        "description": "A quote or proposal sent to a customer that can later become an invoice.",
        "docs_url": f"{_DOCS_ROOT}/estimate",
        "columns": _columns(
            _SHARED_COLUMNS,
            _LINE_COLUMNS,
            CustomerRef="Customer the estimate was sent to.",
            TxnStatus="Status of the estimate, such as Pending, Accepted, Closed, or Rejected.",
            ExpirationDate="Date the estimate stops being valid.",
            AcceptedBy="Name of the person who accepted the estimate.",
            AcceptedDate="Date the estimate was accepted.",
            BillAddr="Billing address on the estimate.",
            ShipAddr="Shipping address on the estimate.",
            BillEmail="Email address the estimate was sent to.",
            EmailStatus="Delivery status of the estimate email.",
            ProjectRef="Project the estimate is associated with.",
        ),
    },
    "Invoice": {
        "description": "A sales transaction billing a customer for goods or services delivered on credit.",
        "docs_url": f"{_DOCS_ROOT}/invoice",
        "columns": _columns(
            _SHARED_COLUMNS,
            _LINE_COLUMNS,
            CustomerRef="Customer being billed.",
            DueDate="Date payment on the invoice is due.",
            Balance="Unpaid amount remaining on the invoice.",
            HomeBalance="Unpaid balance converted to the company's home currency.",
            HomeTotalAmt="Invoice total converted to the company's home currency.",
            SalesTermRef="Payment terms applied to the invoice.",
            BillAddr="Billing address on the invoice.",
            ShipAddr="Shipping address on the invoice.",
            ShipDate="Date the goods were shipped.",
            TrackingNum="Shipping tracking number for the invoice.",
            ShipMethodRef="Shipping method used.",
            BillEmail="Email address the invoice was sent to.",
            EmailStatus="Delivery status of the invoice email, such as NotSet, NeedToSend, or EmailSent.",
            PrintStatus="Print status of the invoice.",
            AllowIPNPayment="Whether the invoice can be paid through Intuit's payment network.",
            AllowOnlinePayment="Whether online payment is enabled for the invoice.",
            AllowOnlineCreditCardPayment="Whether card payment is enabled for the invoice.",
            AllowOnlineACHPayment="Whether ACH payment is enabled for the invoice.",
            Deposit="Amount already deposited against the invoice.",
            ApplyTaxAfterDiscount="Whether sales tax is calculated after the discount is applied.",
            GlobalTaxCalculation="How tax is calculated on the invoice, such as TaxExcluded or TaxInclusive.",
            CustomField="Company-defined custom fields captured on the invoice.",
            ProjectRef="Project the invoice is associated with.",
        ),
    },
    "Item": {
        "description": "A product or service sold or purchased, mapped to income and expense accounts.",
        "docs_url": f"{_DOCS_ROOT}/item",
        "columns": _columns(
            _SHARED_COLUMNS,
            Name="Name of the item, unique among its siblings.",
            FullyQualifiedName="Name prefixed by parent items, colon-separated.",
            Sku="Stock keeping unit for the item.",
            Description="Description shown on sales forms.",
            PurchaseDesc="Description shown on purchase forms.",
            Active="Whether the item is active.",
            Type="Kind of item, such as Inventory, Service, NonInventory, or Group.",
            UnitPrice="Default price charged for the item.",
            PurchaseCost="Default cost paid for the item.",
            Taxable="Whether the item is subject to sales tax.",
            SalesTaxIncluded="Whether the unit price already includes sales tax.",
            SalesTaxCodeRef="Sales-tax code applied when the item is sold.",
            PurchaseTaxCodeRef="Tax code applied when the item is bought.",
            IncomeAccountRef="Account income from selling the item is posted to.",
            ExpenseAccountRef="Account the cost of the item is posted to.",
            AssetAccountRef="Inventory asset account for the item.",
            TrackQtyOnHand="Whether QuickBooks tracks quantity on hand for the item.",
            QtyOnHand="Current quantity on hand for an inventory item.",
            InvStartDate="Date inventory tracking for the item began.",
            SubItem="Whether the item is a child of another item.",
            ParentRef="Parent item when this item is a sub-item.",
            Level="Depth of the item in the parent hierarchy.",
        ),
    },
    "JournalEntry": {
        "description": "A manual double-entry transaction posting debits and credits directly to accounts.",
        "docs_url": f"{_DOCS_ROOT}/journalentry",
        "columns": _columns(
            _SHARED_COLUMNS,
            _LINE_COLUMNS,
            Adjustment="Whether the entry is an adjusting journal entry.",
            HomeTotalAmt="Entry total converted to the company's home currency.",
        ),
    },
    "Payment": {
        "description": "A customer payment received, optionally applied to specific invoices.",
        "docs_url": f"{_DOCS_ROOT}/payment",
        "columns": _columns(
            _SHARED_COLUMNS,
            _LINE_COLUMNS,
            CustomerRef="Customer the payment was received from.",
            TotalAmt="Total amount received.",
            UnappliedAmt="Portion of the payment not yet applied to an invoice.",
            ProcessPayment="Whether the payment was processed through Intuit's payment service.",
            PaymentMethodRef="Method the payment was received by.",
            PaymentRefNum="Reference number for the payment, such as a check number.",
            DepositToAccountRef="Account the payment was deposited into.",
            ARAccountRef="Accounts-receivable account the payment is applied against.",
            CreditCardPayment="Card transaction detail when the payment was made by card.",
            ProjectRef="Project the payment is associated with.",
        ),
    },
    "PaymentMethod": {
        "description": "A method customers can pay by, such as cash, check, or a card brand.",
        "docs_url": f"{_DOCS_ROOT}/paymentmethod",
        "columns": _columns(
            _SHARED_COLUMNS,
            Name="Name of the payment method.",
            Type="Whether the method is a credit card or a non-card method.",
            Active="Whether the payment method is active.",
        ),
    },
    "Preferences": {
        "description": "Company-wide QuickBooks preferences controlling accounting and form behavior. One row.",
        "docs_url": f"{_DOCS_ROOT}/preferences",
        "columns": _columns(
            _SHARED_COLUMNS,
            AccountingInfoPrefs="Accounting preferences, including the fiscal year and class tracking settings.",
            SalesFormsPrefs="Defaults applied to sales forms, such as terms, delivery, and custom fields.",
            VendorAndPurchasesPrefs="Preferences for vendors, bills, and purchase forms.",
            ProductAndServicesPrefs="Preferences controlling quantity, price, and inventory tracking.",
            CurrencyPrefs="Home currency and multicurrency settings.",
            TaxPrefs="Sales-tax configuration for the company.",
            TimeTrackingPrefs="Time-tracking configuration, including the first day of the work week.",
            EmailMessagesPrefs="Default email messages sent with sales forms.",
            ReportPrefs="Default report basis and aging settings.",
            OtherPrefs="Remaining preferences as name/value pairs.",
        ),
    },
    "Purchase": {
        "description": "An expense transaction paid by cash, check, or credit card.",
        "docs_url": f"{_DOCS_ROOT}/purchase",
        "columns": _columns(
            _SHARED_COLUMNS,
            _LINE_COLUMNS,
            PaymentType="How the purchase was paid, either Cash, Check, or CreditCard.",
            AccountRef="Bank or credit-card account the purchase was paid from.",
            EntityRef="Vendor, customer, or employee the purchase was made with.",
            Credit="Whether the transaction is a refund or credit rather than a charge.",
            PrintStatus="Print status of the transaction when it is a check.",
            RemitToAddr="Address the payment is remitted to.",
        ),
    },
    "PurchaseOrder": {
        "description": "A non-posting order sent to a vendor requesting goods or services.",
        "docs_url": f"{_DOCS_ROOT}/purchaseorder",
        "columns": _columns(
            _SHARED_COLUMNS,
            _LINE_COLUMNS,
            VendorRef="Vendor the order was sent to.",
            APAccountRef="Accounts-payable account the order will post to when billed.",
            POStatus="Status of the order, either Open or Closed.",
            DueDate="Date the ordered goods are expected.",
            ShipAddr="Address the goods should be shipped to.",
            ShipMethodRef="Shipping method requested.",
            VendorAddr="Vendor's address on the order.",
            POEmail="Email address the order was sent to.",
            EmailStatus="Delivery status of the order email.",
            TotalTax="Total tax on the order.",
        ),
    },
    "RefundReceipt": {
        "description": "A refund paid back to a customer for a returned sale.",
        "docs_url": f"{_DOCS_ROOT}/refundreceipt",
        "columns": _columns(
            _SHARED_COLUMNS,
            _LINE_COLUMNS,
            CustomerRef="Customer being refunded.",
            PaymentMethodRef="Method the refund was paid by.",
            PaymentRefNum="Reference number for the refund, such as a check number.",
            DepositToAccountRef="Account the refund was paid out of.",
            Balance="Outstanding balance on the refund receipt.",
            BillAddr="Billing address on the refund receipt.",
            ProjectRef="Project the refund is associated with.",
        ),
    },
    "SalesReceipt": {
        "description": "A sale where payment was received at the time of the transaction.",
        "docs_url": f"{_DOCS_ROOT}/salesreceipt",
        "columns": _columns(
            _SHARED_COLUMNS,
            _LINE_COLUMNS,
            CustomerRef="Customer the sale was made to.",
            PaymentMethodRef="Method payment was received by.",
            PaymentRefNum="Reference number for the payment, such as a check number.",
            DepositToAccountRef="Account the payment was deposited into.",
            Balance="Outstanding balance on the receipt, normally zero.",
            BillAddr="Billing address on the receipt.",
            ShipAddr="Shipping address on the receipt.",
            ShipDate="Date the goods were shipped.",
            TrackingNum="Shipping tracking number.",
            BillEmail="Email address the receipt was sent to.",
            EmailStatus="Delivery status of the receipt email.",
            PrintStatus="Print status of the receipt.",
            ProjectRef="Project the sale is associated with.",
        ),
    },
    "TaxCode": {
        "description": "A tax code determining whether and how sales tax applies to a transaction.",
        "docs_url": f"{_DOCS_ROOT}/taxcode",
        "columns": _columns(
            _SHARED_COLUMNS,
            Name="Name of the tax code.",
            Description="Description of what the tax code covers.",
            Active="Whether the tax code is active.",
            Taxable="Whether transactions using the code are taxable.",
            TaxGroup="Whether the code groups several tax rates together.",
            SalesTaxRateList="Tax rates applied when the code is used on a sale.",
            PurchaseTaxRateList="Tax rates applied when the code is used on a purchase.",
        ),
    },
    "TaxRate": {
        "description": "A named tax rate applied through tax codes on transactions.",
        "docs_url": f"{_DOCS_ROOT}/taxrate",
        "columns": _columns(
            _SHARED_COLUMNS,
            Name="Name of the tax rate.",
            Description="Description of the tax rate.",
            Active="Whether the tax rate is active.",
            RateValue="Percentage applied by the rate.",
            AgencyRef="Tax agency the collected tax is remitted to.",
            SpecialTaxType="Special handling applied to the rate, when any.",
            DisplayType="How the rate should be displayed on forms.",
            EffectiveTaxRate="Rate values with their effective date ranges.",
        ),
    },
    "Term": {
        "description": "Payment terms setting when a transaction is due and any early-payment discount.",
        "docs_url": f"{_DOCS_ROOT}/term",
        "columns": _columns(
            _SHARED_COLUMNS,
            Name="Name of the payment terms.",
            Active="Whether the terms are active.",
            Type="Whether the terms are standard (net days) or date-driven.",
            DueDays="Number of days until payment is due for standard terms.",
            DiscountDays="Number of days within which the discount applies.",
            DiscountPercent="Discount percentage for early payment.",
            DayOfMonthDue="Day of the month payment is due for date-driven terms.",
            DueNextMonthDays="Cutoff after which payment rolls into the following month.",
            DiscountDayOfMonth="Day of the month by which the discount applies.",
        ),
    },
    "TimeActivity": {
        "description": "A block of time logged by an employee or vendor, optionally billable to a customer.",
        "docs_url": f"{_DOCS_ROOT}/timeactivity",
        "columns": _columns(
            _SHARED_COLUMNS,
            TxnDate="Date the time was worked.",
            NameOf="Whether the time belongs to an Employee or a Vendor.",
            EmployeeRef="Employee who logged the time.",
            VendorRef="Vendor who logged the time.",
            CustomerRef="Customer the time is attributed to.",
            ItemRef="Service item the time is recorded against.",
            ClassRef="Class the time is tagged with.",
            DepartmentRef="Department or location the time is assigned to.",
            BillableStatus="Whether the time is billable, not billable, or already billed.",
            Taxable="Whether the billed time is subject to tax.",
            HourlyRate="Rate charged per hour for the time.",
            Hours="Whole hours logged.",
            Minutes="Additional minutes logged beyond the whole hours.",
            StartTime="Time the work started.",
            EndTime="Time the work ended.",
            BreakHours="Whole hours of break taken.",
            BreakMinutes="Additional minutes of break taken.",
            Description="Description of the work performed.",
        ),
    },
    "Transfer": {
        "description": "A movement of funds between two of the company's own accounts.",
        "docs_url": f"{_DOCS_ROOT}/transfer",
        "columns": _columns(
            _SHARED_COLUMNS,
            TxnDate="Date of the transfer.",
            Amount="Amount moved between the accounts.",
            FromAccountRef="Account the funds were moved out of.",
            ToAccountRef="Account the funds were moved into.",
            PrivateNote="Internal note on the transfer.",
            CurrencyRef="Currency the transfer is recorded in.",
            ExchangeRate="Rate used to convert to the company's home currency.",
        ),
    },
    "Vendor": {
        "description": "A supplier or contractor the company buys from and owes money to.",
        "docs_url": f"{_DOCS_ROOT}/vendor",
        "columns": _columns(
            _SHARED_COLUMNS,
            DisplayName="Name shown for the vendor, unique across the company.",
            CompanyName="Company name for the vendor.",
            GivenName="Vendor contact's first name.",
            FamilyName="Vendor contact's last name.",
            MiddleName="Vendor contact's middle name.",
            Title="Salutation for the vendor contact.",
            Suffix="Name suffix for the vendor contact.",
            PrintOnCheckName="Name to print on checks issued to the vendor.",
            Active="Whether the vendor is active.",
            PrimaryEmailAddr="Vendor's primary email address.",
            PrimaryPhone="Vendor's primary phone number.",
            AlternatePhone="Vendor's alternate phone number.",
            Mobile="Vendor's mobile phone number.",
            Fax="Vendor's fax number.",
            WebAddr="Vendor's website.",
            BillAddr="Vendor's billing address.",
            Balance="Open balance owed to the vendor.",
            AcctNum="Account number the company holds with the vendor.",
            TaxIdentifier="Vendor's tax identifier, such as an EIN.",
            Vendor1099="Whether the vendor is tracked for 1099 reporting.",
            TermRef="Default payment terms for the vendor.",
            CurrencyRef="Currency transactions with this vendor are recorded in.",
            APAccountRef="Default accounts-payable account for the vendor.",
        ),
    },
    "VendorCredit": {
        "description": "A credit from a vendor that can be applied against open bills.",
        "docs_url": f"{_DOCS_ROOT}/vendorcredit",
        "columns": _columns(
            _SHARED_COLUMNS,
            _LINE_COLUMNS,
            VendorRef="Vendor the credit came from.",
            APAccountRef="Accounts-payable account the credit is posted to.",
            Balance="Unapplied balance of the credit.",
        ),
    },
}
