from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Descriptions sourced from the official Finnhub API docs (https://finnhub.io/docs/api). Keyed by the
# endpoint name returned by `get_schemas`. Partial coverage is fine — anything missing falls back to LLM
# enrichment.
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "stock_symbols": {
        "description": "All tradable symbols for an exchange.",
        "docs_url": "https://finnhub.io/docs/api/stock-symbols",
        "columns": {
            "symbol": "Symbol/ticker used to identify the security.",
            "displaySymbol": "Display symbol shown on the exchange.",
            "description": "Company or security name.",
            "type": "Security type (e.g. Common Stock, ETP).",
            "currency": "Trading currency of the security.",
            "figi": "FIGI identifier for the security.",
            "mic": "ISO 10383 market identifier code of the listing exchange.",
            "isin": "ISIN identifier (premium field; may be empty).",
        },
    },
    "market_news": {
        "description": "Latest general market news articles.",
        "docs_url": "https://finnhub.io/docs/api/market-news",
        "columns": {
            "id": "Unique news article identifier.",
            "category": "News category.",
            "datetime": "Published time as a Unix timestamp (seconds).",
            "headline": "Article headline.",
            "image": "URL of the article's image.",
            "related": "Related stock symbols.",
            "source": "Publisher of the article.",
            "summary": "Article summary.",
            "url": "URL of the original article.",
        },
    },
    "ipo_calendar": {
        "description": "Recent and upcoming IPOs within the requested date window.",
        "docs_url": "https://finnhub.io/docs/api/ipo-calendar",
        "columns": {
            "symbol": "Ticker of the company going public.",
            "date": "IPO date (YYYY-MM-DD).",
            "exchange": "Exchange the company is listing on.",
            "name": "Company name.",
            "numberOfShares": "Number of shares offered.",
            "price": "Offering price or price range.",
            "status": "IPO status (e.g. expected, priced, withdrawn).",
            "totalSharesValue": "Total value of the shares offered.",
        },
    },
    "earnings_calendar": {
        "description": "Recent and upcoming company earnings within the requested date window.",
        "docs_url": "https://finnhub.io/docs/api/earnings-calendar",
        "columns": {
            "symbol": "Company ticker.",
            "date": "Earnings report date (YYYY-MM-DD).",
            "epsActual": "Actual earnings per share.",
            "epsEstimate": "Estimated earnings per share.",
            "revenueActual": "Actual revenue.",
            "revenueEstimate": "Estimated revenue.",
            "hour": "Time of day of the report (bmo = before market open, amc = after market close).",
            "quarter": "Fiscal quarter.",
            "year": "Fiscal year.",
        },
    },
    "country": {
        "description": "Reference list of supported countries and their metadata.",
        "docs_url": "https://finnhub.io/docs/api/country",
        "columns": {
            "code2": "Two-letter ISO country code.",
            "code3": "Three-letter ISO country code.",
            "country": "Country name.",
            "currency": "Country currency name.",
            "currencyCode": "Country currency code.",
        },
    },
    "company_profile": {
        "description": "General profile of a company.",
        "docs_url": "https://finnhub.io/docs/api/company-profile2",
        "columns": {
            "symbol": "Requested ticker the profile was fetched for.",
            "ticker": "Company ticker as reported by Finnhub.",
            "name": "Company name.",
            "country": "Country of the company's headquarters.",
            "currency": "Currency the company reports in.",
            "exchange": "Listing exchange.",
            "ipo": "IPO date.",
            "marketCapitalization": "Market capitalization.",
            "shareOutstanding": "Number of shares outstanding.",
            "finnhubIndustry": "Finnhub industry classification.",
            "weburl": "Company website URL.",
            "logo": "URL of the company logo.",
        },
    },
    "quote": {
        "description": "Latest real-time quote snapshot for a symbol.",
        "docs_url": "https://finnhub.io/docs/api/quote",
        "columns": {
            "symbol": "Requested ticker the quote was fetched for.",
            "c": "Current price.",
            "d": "Change versus the previous close.",
            "dp": "Percentage change versus the previous close.",
            "h": "High price of the day.",
            "l": "Low price of the day.",
            "o": "Open price of the day.",
            "pc": "Previous close price.",
            "t": "Quote time as a Unix timestamp (seconds).",
        },
    },
    "company_news": {
        "description": "Company-specific news articles within the requested date window.",
        "docs_url": "https://finnhub.io/docs/api/company-news",
        "columns": {
            "id": "Unique news article identifier.",
            "symbol": "Requested ticker the article was fetched for.",
            "category": "News category.",
            "datetime": "Published time as a Unix timestamp (seconds).",
            "headline": "Article headline.",
            "image": "URL of the article's image.",
            "related": "Related stock symbols.",
            "source": "Publisher of the article.",
            "summary": "Article summary.",
            "url": "URL of the original article.",
        },
    },
    "basic_financials": {
        "description": "Basic financial metrics (valuation, margins, growth) for a company.",
        "docs_url": "https://finnhub.io/docs/api/company-basic-financials",
        "columns": {
            "symbol": "Requested ticker the metrics were fetched for.",
            "metricType": "The requested metric grouping (e.g. all).",
            "metric": "Object of point-in-time financial metrics.",
            "series": "Object of time-series financial metrics (annual and quarterly).",
        },
    },
    "recommendation_trends": {
        "description": "Analyst recommendation trends for a company over time.",
        "docs_url": "https://finnhub.io/docs/api/recommendation-trends",
        "columns": {
            "symbol": "Company ticker.",
            "period": "Period the recommendation snapshot covers (YYYY-MM-DD).",
            "buy": "Number of analysts recommending buy.",
            "hold": "Number of analysts recommending hold.",
            "sell": "Number of analysts recommending sell.",
            "strongBuy": "Number of analysts recommending strong buy.",
            "strongSell": "Number of analysts recommending strong sell.",
        },
    },
    "earnings_surprises": {
        "description": "Historical EPS estimate versus actual surprises for a company.",
        "docs_url": "https://finnhub.io/docs/api/company-earnings",
        "columns": {
            "symbol": "Company ticker.",
            "period": "Reporting period (YYYY-MM-DD).",
            "actual": "Actual earnings per share.",
            "estimate": "Estimated earnings per share.",
            "surprise": "Difference between actual and estimated EPS.",
            "surprisePercent": "Surprise as a percentage of the estimate.",
            "quarter": "Fiscal quarter.",
            "year": "Fiscal year.",
        },
    },
    "financials_reported": {
        "description": "Financial statements exactly as reported in a company's annual SEC filing.",
        "docs_url": "https://finnhub.io/docs/api/financials-reported",
        "columns": {
            "symbol": "Company ticker.",
            "cik": "SEC Central Index Key of the filer.",
            "accessNumber": "SEC accession number of the filing the report comes from.",
            "year": "Fiscal year the report covers.",
            "quarter": "Fiscal quarter the report covers.",
            "form": "Filing form type (e.g. 10-K).",
            "startDate": "Start of the reporting period.",
            "endDate": "End of the reporting period.",
            "filedDate": "Date the filing was submitted to the SEC.",
            "acceptedDate": "Date the SEC accepted the filing.",
            "report": "Object holding the as-reported balance sheet (bs), cash flow (cf) and income statement (ic) line items.",
        },
    },
    "stock_candles": {
        "description": "Daily open/high/low/close/volume candles for a company, adjusted for splits.",
        "docs_url": "https://finnhub.io/docs/api/stock-candles",
        "columns": {
            "symbol": "Requested ticker the candles were fetched for.",
            "t": "Start of the candle as a Unix timestamp (seconds).",
            "o": "Open price.",
            "h": "High price.",
            "l": "Low price.",
            "c": "Close price.",
            "v": "Volume traded.",
        },
    },
    "sec_filings": {
        "description": "Index of a company's SEC filings, with links to each document.",
        "docs_url": "https://finnhub.io/docs/api/filings",
        "columns": {
            "symbol": "Company ticker.",
            "cik": "SEC Central Index Key of the filer.",
            "accessNumber": "SEC accession number identifying the filing.",
            "form": "Filing form type (e.g. 10-K, 8-K).",
            "filedDate": "Date the filing was submitted to the SEC.",
            "acceptedDate": "Date the SEC accepted the filing.",
            "reportUrl": "URL of the rendered report.",
            "filingUrl": "URL of the filing on EDGAR.",
        },
    },
    "insider_transactions": {
        "description": "Insider buy and sell transactions reported on Form 3, 4 and 5.",
        "docs_url": "https://finnhub.io/docs/api/insider-transactions",
        "columns": {
            "symbol": "Company ticker.",
            "name": "Name of the insider.",
            "share": "Number of shares the insider held after the transaction.",
            "change": "Change in shares. Positive is a buy, negative is a sell.",
            "filingDate": "Date the transaction was filed.",
            "transactionDate": "Date the transaction took place.",
            "transactionPrice": "Average price per share of the transaction.",
            "transactionCode": "SEC Form 4 transaction code (e.g. P for purchase, S for sale).",
        },
    },
    "dividends": {
        "description": "Dividend payouts declared by a company, one row per payout.",
        "docs_url": "https://finnhub.io/docs/api/dividends",
        "columns": {
            "symbol": "Company ticker.",
            "date": "Ex-dividend date.",
            "amount": "Dividend amount in the local currency.",
            "adjustedAmount": "Dividend amount adjusted for later splits.",
            "payDate": "Date the dividend is paid to holders.",
            "recordDate": "Date a holder must be on the register to receive the dividend.",
            "declarationDate": "Date the dividend was declared.",
            "currency": "Currency the dividend is paid in.",
            "freq": "Dividend frequency code (0 annually, 1 monthly, 2 quarterly, 3 semi-annually, 4 other, 5 bimonthly, 6 trimesterly, 7 weekly).",
        },
    },
    "peers": {
        "description": "Comparable companies for a symbol, one row per peer. Finnhub picks peers operating in the same country and sector or industry.",
        "docs_url": "https://finnhub.io/docs/api/company-peers",
        "columns": {
            "symbol": "Requested ticker the peer set was fetched for.",
            "peer": "Ticker of one comparable company.",
        },
    },
    "index_constituents": {
        "description": "Member symbols of a stock index, one row per constituent.",
        "docs_url": "https://finnhub.io/docs/api/indices-constituents",
        "columns": {
            "index_symbol": "Requested index symbol the constituents were fetched for.",
            "symbol": "Ticker of the constituent company.",
            "name": "Name of the constituent company.",
            "weight": "Weight of the constituent in the index.",
            "isin": "ISIN identifier of the constituent.",
            "cusip": "CUSIP identifier of the constituent.",
            "shareClassFIGI": "Global share class FIGI of the constituent.",
        },
    },
    "economic_calendar": {
        "description": "Recent and upcoming macroeconomic releases, one row per scheduled event.",
        "docs_url": "https://finnhub.io/docs/api/economic-calendar",
        "columns": {
            "country": "Country the release covers.",
            "event": "Name of the economic release.",
            "time": "Release time.",
            "actual": "Released figure. Empty until the release lands.",
            "estimate": "Consensus estimate for the release.",
            "prev": "Figure from the previous release.",
            "impact": "Expected market impact of the release (low, medium, high).",
            "unit": "Unit the figures are expressed in.",
        },
    },
}
