from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Descriptions sourced from the official Finnhub API docs (https://finnhub.io/docs/api). Keyed by the
# endpoint name returned by `get_schemas`. Partial coverage is fine — anything missing falls back to LLM
# enrichment.
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "stock_symbols": {
        "description": "All tradable symbols for an exchange.",
        "docs_url": "https://finnhub.io/docs/api/stock-symbols",
        "columns": {
            "symbol": "Symbol/ticker used to identify the security.",
            "displaySymbol": "Display symbol shown on the exchange.",
            "description": "Company or security name.",
            "type": "Security type (e.g. Common Stock, ETP).",
            "currency": "Trading currency of the security.",
            "figi": "FIGI identifier for the security.",
            "mic": "ISO 10383 market identifier code of the listing exchange.",
            "isin": "ISIN identifier (premium field; may be empty).",
        },
    },
    "market_news": {
        "description": "Latest general market news articles.",
        "docs_url": "https://finnhub.io/docs/api/market-news",
        "columns": {
            "id": "Unique news article identifier.",
            "category": "News category.",
            "datetime": "Published time as a Unix timestamp (seconds).",
            "headline": "Article headline.",
            "image": "URL of the article's image.",
            "related": "Related stock symbols.",
            "source": "Publisher of the article.",
            "summary": "Article summary.",
            "url": "URL of the original article.",
        },
    },
    "ipo_calendar": {
        "description": "Recent and upcoming IPOs within the requested date window.",
        "docs_url": "https://finnhub.io/docs/api/ipo-calendar",
        "columns": {
            "symbol": "Ticker of the company going public.",
            "date": "IPO date (YYYY-MM-DD).",
            "exchange": "Exchange the company is listing on.",
            "name": "Company name.",
            "numberOfShares": "Number of shares offered.",
            "price": "Offering price or price range.",
            "status": "IPO status (e.g. expected, priced, withdrawn).",
            "totalSharesValue": "Total value of the shares offered.",
        },
    },
    "earnings_calendar": {
        "description": "Recent and upcoming company earnings within the requested date window.",
        "docs_url": "https://finnhub.io/docs/api/earnings-calendar",
        "columns": {
            "symbol": "Company ticker.",
            "date": "Earnings report date (YYYY-MM-DD).",
            "epsActual": "Actual earnings per share.",
            "epsEstimate": "Estimated earnings per share.",
            "revenueActual": "Actual revenue.",
            "revenueEstimate": "Estimated revenue.",
            "hour": "Time of day of the report (bmo = before market open, amc = after market close).",
            "quarter": "Fiscal quarter.",
            "year": "Fiscal year.",
        },
    },
    "country": {
        "description": "Reference list of supported countries and their metadata.",
        "docs_url": "https://finnhub.io/docs/api/country",
        "columns": {
            "code2": "Two-letter ISO country code.",
            "code3": "Three-letter ISO country code.",
            "country": "Country name.",
            "currency": "Country currency name.",
            "currencyCode": "Country currency code.",
        },
    },
    "company_profile": {
        "description": "General profile of a company.",
        "docs_url": "https://finnhub.io/docs/api/company-profile2",
        "columns": {
            "symbol": "Requested ticker the profile was fetched for.",
            "ticker": "Company ticker as reported by Finnhub.",
            "name": "Company name.",
            "country": "Country of the company's headquarters.",
            "currency": "Currency the company reports in.",
            "exchange": "Listing exchange.",
            "ipo": "IPO date.",
            "marketCapitalization": "Market capitalization.",
            "shareOutstanding": "Number of shares outstanding.",
            "finnhubIndustry": "Finnhub industry classification.",
            "weburl": "Company website URL.",
            "logo": "URL of the company logo.",
        },
    },
    "quote": {
        "description": "Latest real-time quote snapshot for a symbol.",
        "docs_url": "https://finnhub.io/docs/api/quote",
        "columns": {
            "symbol": "Requested ticker the quote was fetched for.",
            "c": "Current price.",
            "d": "Change versus the previous close.",
            "dp": "Percentage change versus the previous close.",
            "h": "High price of the day.",
            "l": "Low price of the day.",
            "o": "Open price of the day.",
            "pc": "Previous close price.",
            "t": "Quote time as a Unix timestamp (seconds).",
        },
    },
    "company_news": {
        "description": "Company-specific news articles within the requested date window.",
        "docs_url": "https://finnhub.io/docs/api/company-news",
        "columns": {
            "id": "Unique news article identifier.",
            "symbol": "Requested ticker the article was fetched for.",
            "category": "News category.",
            "datetime": "Published time as a Unix timestamp (seconds).",
            "headline": "Article headline.",
            "image": "URL of the article's image.",
            "related": "Related stock symbols.",
            "source": "Publisher of the article.",
            "summary": "Article summary.",
            "url": "URL of the original article.",
        },
    },
    "basic_financials": {
        "description": "Basic financial metrics (valuation, margins, growth) for a company.",
        "docs_url": "https://finnhub.io/docs/api/company-basic-financials",
        "columns": {
            "symbol": "Requested ticker the metrics were fetched for.",
            "metricType": "The requested metric grouping (e.g. all).",
            "metric": "Object of point-in-time financial metrics.",
            "series": "Object of time-series financial metrics (annual and quarterly).",
        },
    },
    "recommendation_trends": {
        "description": "Analyst recommendation trends for a company over time.",
        "docs_url": "https://finnhub.io/docs/api/recommendation-trends",
        "columns": {
            "symbol": "Company ticker.",
            "period": "Period the recommendation snapshot covers (YYYY-MM-DD).",
            "buy": "Number of analysts recommending buy.",
            "hold": "Number of analysts recommending hold.",
            "sell": "Number of analysts recommending sell.",
            "strongBuy": "Number of analysts recommending strong buy.",
            "strongSell": "Number of analysts recommending strong sell.",
        },
    },
    "earnings_surprises": {
        "description": "Historical EPS estimate versus actual surprises for a company.",
        "docs_url": "https://finnhub.io/docs/api/company-earnings",
        "columns": {
            "symbol": "Company ticker.",
            "period": "Reporting period (YYYY-MM-DD).",
            "actual": "Actual earnings per share.",
            "estimate": "Estimated earnings per share.",
            "surprise": "Difference between actual and estimated EPS.",
            "surprisePercent": "Surprise as a percentage of the estimate.",
            "quarter": "Fiscal quarter.",
            "year": "Fiscal year.",
        },
    },
}
