import { ConfigOf, defineConfig } from '../config/define-config'
import {
    KAFKA_SESSION_RECORDING_SNAPSHOT_ITEM_DLQ,
    KAFKA_SESSION_RECORDING_SNAPSHOT_ITEM_EVENTS,
    KAFKA_SESSION_RECORDING_SNAPSHOT_ITEM_OVERFLOW,
} from '../config/kafka-topics'
import { isDevEnv } from '../utils/env-utils'
import { KAFKA_CONSUMER_GROUP_ID as SESSION_RECORDING_DEFAULT_GROUP_ID } from './constants'

export const sessionRecordingApiConfigDefs = defineConfig({
    SESSION_RECORDING_API_REDIS_HOST: () => '127.0.0.1',
    SESSION_RECORDING_API_REDIS_PORT: () => 6379,
    SESSION_RECORDING_KMS_ENDPOINT: (): string | undefined => undefined,
    SESSION_RECORDING_DYNAMODB_ENDPOINT: (): string | undefined => undefined,
})

export type SessionRecordingApiConfig = ConfigOf<typeof sessionRecordingApiConfigDefs>

export const sessionRecordingConfigDefs = defineConfig({
    SESSION_RECORDING_LOCAL_DIRECTORY: () => '.tmp/sessions',
    SESSION_RECORDING_MAX_BUFFER_AGE_SECONDS: () => 60 * 10,
    SESSION_RECORDING_MAX_BUFFER_SIZE_KB: () => 1024 * 50, // 50MB
    SESSION_RECORDING_BUFFER_AGE_IN_MEMORY_MULTIPLIER: () => 1.2,
    SESSION_RECORDING_BUFFER_AGE_JITTER: () => 0.3,
    SESSION_RECORDING_REMOTE_FOLDER: () => 'session_recordings',
    SESSION_RECORDING_REDIS_PREFIX: () => '@posthog/replay/',
    SESSION_RECORDING_PARTITION_REVOKE_OPTIMIZATION: () => false,
    SESSION_RECORDING_PARALLEL_CONSUMPTION: () => false,
    SESSION_RECORDING_CONSOLE_LOGS_INGESTION_ENABLED: () => true,
    SESSION_RECORDING_REPLAY_EVENTS_INGESTION_ENABLED: () => true,
    SESSION_RECORDING_DEBUG_PARTITION: (): string | undefined => '',
    SESSION_RECORDING_OVERFLOW_ENABLED: () => false,
    SESSION_RECORDING_OVERFLOW_BUCKET_CAPACITY: () => 200_000_000, // 200MB burst
    SESSION_RECORDING_OVERFLOW_BUCKET_REPLENISH_RATE: () => 5_000_000, // 5MB/second uncompressed, sustained
    SESSION_RECORDING_OVERFLOW_MIN_PER_BATCH: () => 1_000_000, // All sessions consume at least 1MB/batch
    SESSION_RECORDING_MAX_PARALLEL_FLUSHES: () => 10,

    POSTHOG_SESSION_RECORDING_REDIS_HOST: (): string | undefined => undefined,
    POSTHOG_SESSION_RECORDING_REDIS_PORT: (): number | undefined => undefined,

    SESSION_RECORDING_MAX_BATCH_SIZE_KB: () => (isDevEnv() ? 2 * 1024 : 100 * 1024), // 2MB on dev, 100MB on prod and test
    SESSION_RECORDING_MAX_BATCH_AGE_MS: () => 10 * 1000, // 10 seconds
    SESSION_RECORDING_V2_S3_BUCKET: () => 'posthog',
    SESSION_RECORDING_V2_S3_PREFIX: () => 'session_recordings',
    SESSION_RECORDING_V2_S3_ENDPOINT: () => 'http://localhost:8333',
    SESSION_RECORDING_V2_S3_REGION: () => 'us-east-1',
    SESSION_RECORDING_V2_S3_ACCESS_KEY_ID: () => 'any',
    SESSION_RECORDING_V2_S3_SECRET_ACCESS_KEY: () => 'any',
    SESSION_RECORDING_V2_S3_TIMEOUT_MS: (): number => (isDevEnv() ? 120000 : 30000),
    SESSION_RECORDING_V2_REPLAY_EVENTS_KAFKA_TOPIC: () => 'clickhouse_session_replay_events',
    SESSION_RECORDING_V2_CONSOLE_LOG_ENTRIES_KAFKA_TOPIC: () => 'log_entries',
    SESSION_RECORDING_V2_CONSOLE_LOG_STORE_SYNC_BATCH_LIMIT: () => 1000,
    SESSION_RECORDING_V2_MAX_EVENTS_PER_SESSION_PER_BATCH: () => Number.MAX_SAFE_INTEGER,
    SESSION_RECORDING_NEW_SESSION_BUCKET_CAPACITY: () => 3000,
    SESSION_RECORDING_NEW_SESSION_BUCKET_REPLENISH_RATE: () => 300,
    SESSION_RECORDING_NEW_SESSION_BLOCKING_ENABLED: () => false,
    SESSION_RECORDING_SESSION_FILTER_ENABLED: () => true,
    SESSION_RECORDING_SESSION_TRACKER_CACHE_TTL_MS: () => 5 * 60 * 1000, // 5 minutes
    SESSION_RECORDING_SESSION_FILTER_CACHE_TTL_MS: () => 5 * 60 * 1000, // 5 minutes
    SESSION_RECORDING_CRYPTO_INTEGRITY_CHECK_RATE: () => 0.01, // 1% of encrypted blocks

    // Kafka consumer config
    INGESTION_SESSION_REPLAY_CONSUMER_CONSUME_TOPIC: () => KAFKA_SESSION_RECORDING_SNAPSHOT_ITEM_EVENTS,
    INGESTION_SESSION_REPLAY_CONSUMER_GROUP_ID: () => SESSION_RECORDING_DEFAULT_GROUP_ID,
    INGESTION_SESSION_REPLAY_CONSUMER_OVERFLOW_TOPIC: () => KAFKA_SESSION_RECORDING_SNAPSHOT_ITEM_OVERFLOW,
    INGESTION_SESSION_REPLAY_CONSUMER_DLQ_TOPIC: () => KAFKA_SESSION_RECORDING_SNAPSHOT_ITEM_DLQ,
})

export type SessionRecordingConfig = ConfigOf<typeof sessionRecordingConfigDefs>
