from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "secret_incidents": {
        "description": "A secret incident regroups every occurrence of the same secret detected across your monitored perimeter, with its triage status and remediation timeline.",
        "docs_url": "https://api.gitguardian.com/docs#tag/Secret-Incidents",
        "columns": {
            "id": "Unique identifier of the incident.",
            "date": "Date and time the secret was first detected. Immutable.",
            "detector": "Detector that matched the secret (name, family, detector group).",
            "secret_hash": "Hash of the detected secret, used to group occurrences of the same secret.",
            "gitguardian_url": "Link to the incident in the GitGuardian dashboard.",
            "regression": "Whether the incident reappeared after having been resolved.",
            "status": "Triage status of the incident (IGNORED, TRIGGERED, ASSIGNED, RESOLVED).",
            "assignee_id": "Identifier of the workspace member the incident is assigned to.",
            "assignee_email": "Email of the workspace member the incident is assigned to.",
            "occurrences_count": "Number of times the secret occurs across the monitored perimeter.",
            "occurrences": "Up to 20 embedded occurrences of the secret; the full list lives in the secret_occurrences table.",
            "ignore_reason": "Why the incident was ignored (test_credential, false_positive, low_risk).",
            "ignored_at": "Date and time the incident was ignored, if it was.",
            "resolved_at": "Date and time the incident was resolved, if it was.",
            "secret_revoked": "Whether the secret was revoked as part of remediation.",
            "severity": "Severity assigned to the incident (critical, high, medium, low, info, unknown).",
            "validity": "Whether the secret is still valid against its service (valid, invalid, failed_to_check, no_checker, unknown).",
            "tags": "Tags attached to the incident (e.g. PUBLICLY_EXPOSED, SENSITIVE_FILE).",
        },
    },
    "secret_occurrences": {
        "description": "A single place a secret was found: one match of an incident's secret in a specific commit, file, or other monitored location.",
        "docs_url": "https://api.gitguardian.com/docs#tag/Secret-Occurrences",
        "columns": {
            "id": "Unique identifier of the occurrence.",
            "incident_id": "Identifier of the secret incident this occurrence belongs to.",
            "kind": "Kind of occurrence (e.g. realtime, historical).",
            "source": "Monitored source (repository, ...) the occurrence was found in.",
            "author_name": "Name of the commit author who introduced the secret.",
            "author_info": "Email or other contact info of the commit author.",
            "sha": "Commit SHA the secret was found in.",
            "date": "Date and time the occurrence was detected. Immutable.",
            "filepath": "Path of the file containing the secret.",
            "filename": "Name of the file containing the secret.",
            "url": "Link to the occurrence location.",
            "presence": "Whether the secret is still present in the source (present, removed).",
            "matches": "Matched portions of the secret within the file (indices and match kind).",
        },
    },
    "sources": {
        "description": "A monitored source in your GitGuardian perimeter (repository, VCS org, ...), with its scan health and open incident counts.",
        "docs_url": "https://api.gitguardian.com/docs#tag/Sources",
        "columns": {
            "id": "Unique identifier of the source.",
            "url": "URL of the source.",
            "type": "Type of source (github, gitlab, bitbucket, azure_devops, ...).",
            "full_name": "Full name of the source, e.g. the owner/repository slug.",
            "health": "Health of the source based on its open incidents (safe, unknown, at_risk).",
            "default_branch": "Default branch of the repository, when applicable.",
            "open_incidents_count": "Number of open secret incidents detected on this source.",
            "closed_incidents_count": "Number of closed secret incidents detected on this source.",
            "visibility": "Visibility of the source (public, private, internal).",
            "external_id": "Identifier of the source on the external system (e.g. the GitHub repository id).",
            "source_criticality": "Criticality assigned to the source (critical, high, medium, low, unknown).",
            "last_scan": "Status and date of the source's last historical scan.",
            "monitored": "Whether the source is currently monitored.",
        },
    },
    "honeytokens": {
        "description": "A honeytoken (decoy credential) created in your workspace, with its trigger status showing whether it was used.",
        "docs_url": "https://api.gitguardian.com/docs#tag/Honeytokens",
        "columns": {
            "id": "Unique identifier of the honeytoken.",
            "name": "Name given to the honeytoken.",
            "description": "Description of the honeytoken.",
            "type": "Type of honeytoken (e.g. AWS).",
            "status": "Status of the honeytoken (active, triggered, revoked).",
            "created_at": "Date and time the honeytoken was created.",
            "triggered_at": "Date and time the honeytoken was first triggered, if it was.",
            "revoked_at": "Date and time the honeytoken was revoked, if it was.",
            "creator_id": "Identifier of the workspace member who created the honeytoken.",
            "gitguardian_url": "Link to the honeytoken in the GitGuardian dashboard.",
        },
    },
    "members": {
        "description": "A member of your GitGuardian workspace, with their access level and activity.",
        "docs_url": "https://api.gitguardian.com/docs#tag/Members",
        "columns": {
            "id": "Unique identifier of the member.",
            "name": "Name of the member.",
            "email": "Email of the member.",
            "role": "Deprecated in favor of access_level; the member's workspace role.",
            "access_level": "Access level of the member (owner, manager, member, restricted).",
            "created_at": "Date and time the member joined the workspace.",
            "last_login": "Date and time of the member's last login.",
            "active": "Whether the member's account is active.",
        },
    },
    "teams": {
        "description": "A team in your GitGuardian workspace, used to scope incidents and sources to groups of members.",
        "docs_url": "https://api.gitguardian.com/docs#tag/Teams",
        "columns": {
            "id": "Unique identifier of the team.",
            "name": "Name of the team.",
            "description": "Description of the team.",
            "is_global": "Whether this is the built-in All incidents team covering the whole workspace.",
            "gitguardian_url": "Link to the team in the GitGuardian dashboard.",
        },
    },
    "team_memberships": {
        "description": "A membership of a workspace member in a team, with the permissions the member holds in that team.",
        "docs_url": "https://api.gitguardian.com/docs#tag/Team-Memberships",
        "columns": {
            "id": "Unique identifier of the team membership.",
            "team_id": "Identifier of the team.",
            "member_id": "Identifier of the workspace member.",
            "is_team_leader": "Whether the member is a leader of the team.",
            "team_permission": "Deprecated in favor of is_team_leader; whether the member can manage the team (can_manage, cannot_manage).",
            "incident_permission": "Permission of the member on the team's incidents (can_view, can_edit, full_access).",
        },
    },
    "honeytoken_events": {
        "description": "An event recorded when someone uses one of your honeytokens, with the origin IP address and the action performed.",
        "docs_url": "https://api.gitguardian.com/docs#tag/Honeytokens-Events",
        "columns": {
            "id": "Unique identifier of the honeytoken event.",
            "honeytoken_id": "Identifier of the honeytoken that was triggered.",
            "triggered_at": "Date and time the honeytoken was triggered.",
            "gitguardian_url": "Link to the event in the GitGuardian dashboard.",
            "status": "Triage status of the event (open, closed).",
            "ip_address": "IP address the event originates from.",
            "action": "Action performed with the honeytoken.",
            "data": "Additional data related to the event.",
            "tags": "Tags attached to the event (e.g. publicly_exposed).",
        },
    },
    "secret_incident_activity_logs": {
        "description": "One entry in the activity history of a secret incident: a system action (assignment, status change, ...) or a user note, in chronological order.",
        "docs_url": "https://api.gitguardian.com/docs#tag/Secret-Incidents",
        "columns": {
            "id": "Unique identifier of the activity log entry.",
            "incident_id": "Identifier of the secret incident the entry belongs to.",
            "member": "Workspace member at the origin of the entry (id, name, email, access_level). Null for system actions.",
            "api_token_id": "Identifier of the API token at the origin of the entry, if it came through the API.",
            "created_at": "Date and time the entry was created.",
            "updated_at": "Date and time the entry was last updated. Null if it was never modified.",
            "content": "Entry content: a user note (type note, comment) or a system action (type action, content_key, data).",
        },
    },
    "secret_detectors": {
        "description": "A secret detector GitGuardian uses to match secrets, with its category and the incident counts it produced in your workspace.",
        "docs_url": "https://api.gitguardian.com/docs#tag/Secret-Detectors",
        "columns": {
            "name": "Unique name of the detector (e.g. aws_iam).",
            "display_name": "Human-readable name of the detector.",
            "type": "Type of the detector (specific, generic, custom).",
            "category": "Category of the detector (e.g. Cloud Provider).",
            "is_active": "Whether the detector is enabled on the workspace.",
            "scans_code_only": "Whether the detector scans only VCS resources.",
            "checkable": "Whether the detector has a validity checker.",
            "use_with_validity_check_disabled": "Whether the detector is used when secret validity checks are disabled on the workspace.",
            "frequency": "Number of secrets found per million commits in GitGuardian's open-source monitoring.",
            "removed_at": "Date and time GitGuardian disabled the detector, if it did.",
            "open_incidents_count": "Number of open secret incidents on the workspace for this detector.",
            "ignored_incidents_count": "Number of ignored secret incidents on the workspace for this detector.",
            "resolved_incidents_count": "Number of resolved secret incidents on the workspace for this detector.",
        },
    },
}
