from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

_ENTITY_COLUMNS = {
    "entityId": "Unique identifier of the monitored entity (e.g. HOST-ABC123).",
    "displayName": "Display name of the entity as shown in the Dynatrace UI.",
    "type": "Type of the monitored entity (e.g. HOST, SERVICE, APPLICATION).",
    "firstSeenTms": "Timestamp when the entity was first seen, in UTC milliseconds.",
    "lastSeenTms": "Timestamp when the entity was last seen, in UTC milliseconds.",
    "properties": "Type-specific properties of the entity (e.g. OS type, bitness).",
    "tags": "Tags assigned to the entity.",
    "managementZones": "Management zones the entity is part of.",
}

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "problems": {
        "description": "Problems detected by Davis AI within the environment, including their impact, root cause, and lifecycle.",
        "docs_url": "https://docs.dynatrace.com/docs/dynatrace-api/environment-api/problems-v2/problems",
        "columns": {
            "problemId": "Unique identifier of the problem.",
            "displayId": "Human-friendly identifier of the problem (e.g. P-12345).",
            "title": "Short summary of the problem.",
            "status": "Status of the problem: OPEN or CLOSED.",
            "severityLevel": "Severity of the problem (e.g. AVAILABILITY, ERROR, PERFORMANCE, RESOURCE_CONTENTION).",
            "impactLevel": "Level of impact: APPLICATION, ENVIRONMENT, INFRASTRUCTURE, or SERVICES.",
            "startTime": "Start time of the problem, in UTC milliseconds.",
            "endTime": "End time of the problem, in UTC milliseconds. -1 while the problem is still open.",
            "affectedEntities": "Entities affected by the problem.",
            "impactedEntities": "Entities impacted by the problem.",
            "rootCauseEntity": "The entity identified as the root cause of the problem.",
            "entityTags": "Tags of the entities affected by the problem.",
            "managementZones": "Management zones the problem affects.",
            "problemFilters": "Alerting profiles that match the problem.",
            "recentComments": "Most recent comments on the problem.",
        },
    },
    "events": {
        "description": "Events observed within the environment, such as deployments, restarts, and anomaly events.",
        "docs_url": "https://docs.dynatrace.com/docs/dynatrace-api/environment-api/events-v2",
        "columns": {
            "eventId": "Unique identifier of the event.",
            "eventType": "Type of the event (e.g. PROCESS_RESTART, CUSTOM_DEPLOYMENT).",
            "title": "Title of the event.",
            "status": "Status of the event: OPEN or CLOSED.",
            "startTime": "Start time of the event, in UTC milliseconds.",
            "endTime": "End time of the event, in UTC milliseconds. Null while the event is still active.",
            "correlationId": "Correlation ID of the event.",
            "entityId": "The monitored entity the event relates to.",
            "entityTags": "Tags of the related entity.",
            "managementZones": "Management zones the related entity is part of.",
            "properties": "Key/value properties of the event.",
            "underMaintenance": "Whether the event happened while the entity was under maintenance.",
            "suppressAlert": "Whether alerting was suppressed for the event.",
            "suppressProblem": "Whether problem creation was suppressed for the event.",
            "frequentEvent": "Whether the event is a frequent event (does not open problems).",
        },
    },
    "audit_logs": {
        "description": "Audit log of configuration changes, token operations, and user logins in the environment.",
        "docs_url": "https://docs.dynatrace.com/docs/dynatrace-api/environment-api/audit-logs",
        "columns": {
            "logId": "Unique identifier of the log entry.",
            "eventType": "Type of the recorded operation (e.g. CREATE, UPDATE, DELETE, LOGIN).",
            "category": "Category of the recorded operation (e.g. CONFIG, TOKEN, WEB_UI).",
            "entityId": "Identifier of the changed object.",
            "environmentId": "Identifier of the environment where the operation happened.",
            "message": "Description of the recorded operation.",
            "patch": "JSON patch describing the change, including old values.",
            "success": "Whether the recorded operation succeeded.",
            "timestamp": "Timestamp of the operation, in UTC milliseconds.",
            "user": "User or token that performed the operation.",
            "userOrigin": "Origin (IP address or client) of the user.",
            "userType": "Type of the actor: USER_NAME, TOKEN_HASH, PUBLIC_TOKEN_IDENTIFIER, or SERVICE_NAME.",
        },
    },
    "security_problems": {
        "description": "Vulnerabilities (security problems) detected by Dynatrace Application Security.",
        "docs_url": "https://docs.dynatrace.com/docs/dynatrace-api/environment-api/application-security/vulnerabilities",
        "columns": {
            "securityProblemId": "Unique identifier of the security problem.",
            "displayId": "Human-friendly identifier of the security problem (e.g. S-1234).",
            "status": "Status of the security problem: OPEN or RESOLVED.",
            "muted": "Whether the security problem is muted.",
            "externalVulnerabilityId": "Identifier of the vulnerability in the external source (e.g. CVE).",
            "vulnerabilityType": "Type of the vulnerability (e.g. THIRD_PARTY, CODE_LEVEL).",
            "title": "Title of the security problem.",
            "packageName": "Name of the vulnerable package.",
            "technology": "Affected technology (e.g. JAVA, DOTNET).",
            "firstSeenTimestamp": "Timestamp when the security problem was first seen, in UTC milliseconds.",
            "lastUpdatedTimestamp": "Timestamp of the most recent update, in UTC milliseconds.",
        },
    },
    "hosts": {
        "description": "Monitored host entities and their metadata.",
        "docs_url": "https://docs.dynatrace.com/docs/dynatrace-api/environment-api/entity-v2",
        "columns": _ENTITY_COLUMNS,
    },
    "services": {
        "description": "Monitored service entities and their metadata.",
        "docs_url": "https://docs.dynatrace.com/docs/dynatrace-api/environment-api/entity-v2",
        "columns": _ENTITY_COLUMNS,
    },
    "applications": {
        "description": "Monitored application entities and their metadata.",
        "docs_url": "https://docs.dynatrace.com/docs/dynatrace-api/environment-api/entity-v2",
        "columns": _ENTITY_COLUMNS,
    },
    "process_groups": {
        "description": "Monitored process group entities and their metadata.",
        "docs_url": "https://docs.dynatrace.com/docs/dynatrace-api/environment-api/entity-v2",
        "columns": _ENTITY_COLUMNS,
    },
    "metrics": {
        "description": "Catalog of metric descriptors available in the environment (built-in and custom).",
        "docs_url": "https://docs.dynatrace.com/docs/dynatrace-api/environment-api/metric-v2",
        "columns": {
            "metricId": "Fully qualified key of the metric (e.g. builtin:host.cpu.usage).",
            "displayName": "Display name of the metric.",
            "description": "Short description of the metric.",
            "unit": "Unit of the metric.",
            "created": "Timestamp when the metric was created, in UTC milliseconds. Null for built-in metrics.",
            "lastWritten": "Timestamp when the metric last received a data point, in UTC milliseconds.",
            "entityType": "Entity types the metric applies to.",
            "aggregationTypes": "Aggregations available for the metric.",
            "tags": "Tags applied to the metric.",
        },
    },
    "slos": {
        "description": "Service-level objectives with their current evaluation status and error budget.",
        "docs_url": "https://docs.dynatrace.com/docs/dynatrace-api/environment-api/service-level-objectives",
        "columns": {
            "id": "Unique identifier of the SLO.",
            "name": "Name of the SLO.",
            "description": "Description of the SLO.",
            "enabled": "Whether the SLO is enabled.",
            "target": "Target value of the SLO, in percent.",
            "warning": "Warning threshold of the SLO, in percent.",
            "timeframe": "Timeframe the SLO is evaluated over.",
            "status": "Evaluation status: SUCCESS, WARNING, or FAILURE.",
            "evaluatedPercentage": "Calculated value of the SLO, in percent. -1 if the calculation failed.",
            "errorBudget": "Remaining error budget of the SLO, in percent.",
            "metricExpression": "Metric expression the SLO is based on.",
            "filter": "Entity filter of the SLO.",
            "relatedOpenProblems": "Number of open problems related to the SLO.",
        },
    },
}
