import { MakeLogicType, afterMount, connect, kea, key, path, props, selectors } from 'kea'
import type { BuiltLogic } from 'kea'

import { Scene } from 'scenes/sceneTypes'
import { urls } from 'scenes/urls'

import { SIDE_PANEL_CONTEXT_KEY, SidePanelSceneContext } from '~/layout/navigation-3000/sidepanel/types'
import { notebooksModel } from '~/models/notebooksModel'
import { ActivityScope, Breadcrumb, ProjectTreeRef } from '~/types'

import type { JSONContent } from '../../lib/components/RichContentEditor/types'
import { notebookLogic } from './Notebook/notebookLogic'
import type { notebookLogicType } from './Notebook/notebookLogic'
import type { NotebookTarget } from './types'
import type { NotebookType } from './types'

export type NotebookSceneLogicProps = {
    shortId: string
}
// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface notebookSceneLogicValues {
    isLocalOnly: boolean // notebookLogic
    notebook: NotebookType | null // notebookLogic
    notebookLoading: boolean // notebookLogic
    notebooksLoading: boolean // notebooksModel
    breadcrumbs: Breadcrumb[]
    loading: boolean
    notebookId: string
    projectTreeRef: ProjectTreeRef | null
    sidePanelContext: SidePanelSceneContext | null
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface notebookSceneLogicActions {
    loadNotebook: () => {
        value: true
    } // notebookLogic
    createNotebook: (
        location: NotebookTarget,
        title?: string | undefined,
        content?: JSONContent[] | undefined,
        onCreate?: ((notebook: BuiltLogic<notebookLogicType>) => void) | undefined,
        shortId?: string | undefined
    ) => {
        content: JSONContent[] | undefined
        location: NotebookTarget
        onCreate: ((notebook: BuiltLogic<notebookLogicType>) => void) | undefined
        shortId: string | undefined
        title: string | undefined
    } // notebooksModel
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface notebookSceneLogicMeta {
    key: string
    __keaTypeGenInternalSelectorTypes: {
        notebookId: (shortId: string) => string
        loading: (notebookLoading: boolean, notebooksLoading: boolean) => boolean
        breadcrumbs: (notebook: NotebookType | null, loading: boolean) => Breadcrumb[]
        projectTreeRef: (arg: string) => ProjectTreeRef | null
        sidePanelContext: (notebookId: string, isLocalOnly: boolean) => SidePanelSceneContext | null
    }
}

export type notebookSceneLogicType = MakeLogicType<
    notebookSceneLogicValues,
    notebookSceneLogicActions,
    NotebookSceneLogicProps,
    notebookSceneLogicMeta
>

export const notebookSceneLogic = kea<notebookSceneLogicType>([
    path((key) => ['scenes', 'notebooks', 'notebookSceneLogic', key]),
    props({} as NotebookSceneLogicProps),
    key(({ shortId }) => shortId),
    connect((props: NotebookSceneLogicProps) => ({
        values: [
            notebookLogic(props),
            ['notebook', 'notebookLoading', 'isLocalOnly'],
            notebooksModel,
            ['notebooksLoading'],
        ],
        actions: [notebookLogic(props), ['loadNotebook'], notebooksModel, ['createNotebook']],
    })),
    selectors(() => ({
        notebookId: [(_, p) => [p.shortId], (shortId: string) => shortId],

        loading: [
            (s) => [s.notebookLoading, s.notebooksLoading],
            (notebookLoading: boolean, notebooksLoading: boolean) => notebookLoading || notebooksLoading,
        ],

        breadcrumbs: [
            (s) => [s.notebook, s.loading],
            (notebook: NotebookType | null, loading: boolean): Breadcrumb[] => {
                const parent: Breadcrumb =
                    notebook?.parent_resource?.type === 'account'
                        ? {
                              key: Scene.CustomerAnalytics,
                              name: 'Accounts',
                              path: urls.customerAnalyticsAccount(notebook.parent_resource.id),
                              iconType: 'group',
                          }
                        : {
                              key: Scene.Notebooks,
                              name: 'Notebooks',
                              path: urls.notebooks(),
                              iconType: 'notebook',
                          }
                return [
                    parent,
                    {
                        key: [Scene.Notebook, notebook?.short_id || 'new'],
                        name: notebook ? notebook?.title || 'Unnamed' : loading ? null : 'Notebook not found',
                        iconType: 'notebook',
                    },
                ]
            },
        ],

        projectTreeRef: [
            () => [(_, props: NotebookSceneLogicProps) => props.shortId],
            (shortId: string): ProjectTreeRef | null =>
                shortId === 'new' ? null : { type: 'notebook', ref: String(shortId) },
        ],

        [SIDE_PANEL_CONTEXT_KEY]: [
            (s) => [s.notebookId, s.isLocalOnly],
            (notebookId: string, isLocalOnly: boolean): SidePanelSceneContext | null => {
                return notebookId && !isLocalOnly
                    ? {
                          activity_scope: ActivityScope.NOTEBOOK,
                          activity_item_id: notebookId,
                          access_control_resource: 'notebook',
                          access_control_resource_id: notebookId,
                      }
                    : null
            },
        ],
    })),

    afterMount(({ actions, props, values }) => {
        // Skip the fetch when the underlying notebookLogic is already mounted with content —
        // e.g. kept alive by a desktop scene tab, or open in the notebook side panel
        if (props.shortId !== 'new' && !values.notebook && !values.notebookLoading) {
            actions.loadNotebook()
        }
    }),
])
