from .spans import (
    KAFKA_TRACE_SPANS_AVRO_MV,
    KAFKA_TRACE_SPANS_AVRO_TABLE_SQL,
    TRACE_ATTRIBUTES_DISTRIBUTED_TABLE_SQL,
    TRACE_SPAN_TO_ATTRIBUTES2_MV,
    TRACE_SPAN_TO_ATTRIBUTES_MV,
    TRACE_SPAN_TO_RESOURCE_ATTRIBUTES2_MV,
    TRACE_SPAN_TO_RESOURCE_ATTRIBUTES_MV,
    TRACE_SPAN_TO_SPAN_ATTRIBUTES2_MV,
    TRACE_SPAN_TO_SPAN_ATTRIBUTES_MV,
    TRACE_SPANS_DISTRIBUTED_TABLE_SQL,
    TRACE_SPANS_KAFKA_METRICS_TABLE_SQL,
    TRACE_SPANS_TABLE_SQL,
    TRACE_SPANS_TO_KAFKA_METRICS_MV,
)
from .trace_attributes import TRACE_ATTRIBUTES2_TABLE_SQL, TRACE_ATTRIBUTES_TABLE_SQL

__all__ = [
    "TRACE_SPANS_TABLE_SQL",
    "TRACE_SPANS_DISTRIBUTED_TABLE_SQL",
    "TRACE_ATTRIBUTES_TABLE_SQL",
    "TRACE_ATTRIBUTES_DISTRIBUTED_TABLE_SQL",
    "TRACE_ATTRIBUTES2_TABLE_SQL",
    "TRACE_SPAN_TO_ATTRIBUTES_MV",
    "TRACE_SPAN_TO_RESOURCE_ATTRIBUTES_MV",
    "TRACE_SPAN_TO_SPAN_ATTRIBUTES_MV",
    "TRACE_SPAN_TO_ATTRIBUTES2_MV",
    "TRACE_SPAN_TO_RESOURCE_ATTRIBUTES2_MV",
    "TRACE_SPAN_TO_SPAN_ATTRIBUTES2_MV",
    "KAFKA_TRACE_SPANS_AVRO_TABLE_SQL",
    "KAFKA_TRACE_SPANS_AVRO_MV",
    "TRACE_SPANS_KAFKA_METRICS_TABLE_SQL",
    "TRACE_SPANS_TO_KAFKA_METRICS_MV",
]
