from .spans import (
    SPANS_DISTRIBUTED_TABLE_SQL,
    SPANS_TABLE_SQL,
    TRACE_ATTRIBUTES_DISTRIBUTED_TABLE_SQL,
    TRACE_ATTRIBUTES_MV,
    TRACE_RESOURCE_ATTRIBUTES_MV,
)
from .trace_attributes import TRACE_ATTRIBUTES_TABLE_SQL

__all__ = [
    "SPANS_TABLE_SQL",
    "SPANS_DISTRIBUTED_TABLE_SQL",
    "TRACE_ATTRIBUTES_TABLE_SQL",
    "TRACE_ATTRIBUTES_DISTRIBUTED_TABLE_SQL",
    "TRACE_ATTRIBUTES_MV",
    "TRACE_RESOURCE_ATTRIBUTES_MV",
]
