from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Sourced from the Vultr API v2 reference (https://www.vultr.com/api/) and the official govultr client.
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "instances": {
        "description": "Cloud compute and GPU instances (virtual machines) in your Vultr account.",
        "docs_url": "https://www.vultr.com/api/#tag/instances",
        "columns": {
            "id": "Unique identifier for the instance.",
            "region": "Region ID where the instance is deployed.",
            "plan": "Plan ID the instance runs on.",
            "date_created": "Date and time the instance was created (ISO 8601).",
            "status": "Current provisioning status of the instance.",
            "power_status": "Whether the instance is running or stopped.",
            "server_status": "Health of the server's OS/applications.",
            "main_ip": "Primary IPv4 address of the instance.",
            "vcpu_count": "Number of vCPUs allocated to the instance.",
            "ram": "Memory allocated to the instance, in MB.",
            "disk": "Disk size allocated to the instance, in GB.",
            "os": "Operating system name.",
            "label": "User-defined label for the instance.",
            "hostname": "Hostname assigned to the instance.",
            "tags": "User-defined tags applied to the instance.",
        },
    },
    "bare_metals": {
        "description": "Bare metal (dedicated) servers in your Vultr account.",
        "docs_url": "https://www.vultr.com/api/#tag/bare-metal",
        "columns": {
            "id": "Unique identifier for the bare metal server.",
            "region": "Region ID where the server is deployed.",
            "plan": "Plan ID the server runs on.",
            "date_created": "Date and time the server was created (ISO 8601).",
            "status": "Current provisioning status of the server.",
            "main_ip": "Primary IPv4 address of the server.",
            "cpu_count": "Number of CPU cores on the server.",
            "ram": "Memory of the server.",
            "disk": "Disk of the server.",
            "os": "Operating system name.",
            "label": "User-defined label for the server.",
        },
    },
    "kubernetes_clusters": {
        "description": "Vultr Kubernetes Engine (VKE) managed clusters.",
        "docs_url": "https://www.vultr.com/api/#tag/kubernetes",
        "columns": {
            "id": "Unique identifier for the cluster.",
            "label": "User-defined label for the cluster.",
            "date_created": "Date and time the cluster was created (ISO 8601).",
            "region": "Region ID where the cluster is deployed.",
            "version": "Kubernetes version running on the cluster.",
            "status": "Current status of the cluster.",
            "ip": "Cluster control-plane IP address.",
            "endpoint": "Cluster API endpoint.",
            "node_pools": "Node pools attached to the cluster.",
        },
    },
    "block_storage": {
        "description": "Block storage volumes in your Vultr account.",
        "docs_url": "https://www.vultr.com/api/#tag/block",
        "columns": {
            "id": "Unique identifier for the block storage volume.",
            "date_created": "Date and time the volume was created (ISO 8601).",
            "region": "Region ID where the volume is deployed.",
            "size_gb": "Size of the volume, in GB.",
            "status": "Current status of the volume.",
            "cost": "Monthly cost of the volume.",
            "attached_to_instance": "ID of the instance the volume is attached to, if any.",
            "block_type": "Storage class of the volume.",
            "label": "User-defined label for the volume.",
        },
    },
    "snapshots": {
        "description": "Instance snapshots stored in your Vultr account.",
        "docs_url": "https://www.vultr.com/api/#tag/snapshot",
        "columns": {
            "id": "Unique identifier for the snapshot.",
            "date_created": "Date and time the snapshot was taken (ISO 8601).",
            "description": "User-defined description of the snapshot.",
            "size": "Uncompressed size of the snapshot, in bytes.",
            "compressed_size": "Compressed size of the snapshot, in bytes.",
            "status": "Current status of the snapshot.",
        },
    },
    "load_balancers": {
        "description": "Load balancers in your Vultr account.",
        "docs_url": "https://www.vultr.com/api/#tag/load-balancer",
        "columns": {
            "id": "Unique identifier for the load balancer.",
            "date_created": "Date and time the load balancer was created (ISO 8601).",
            "region": "Region ID where the load balancer is deployed.",
            "label": "User-defined label for the load balancer.",
            "status": "Current status of the load balancer.",
            "ipv4": "IPv4 address of the load balancer.",
            "ipv6": "IPv6 address of the load balancer.",
            "instances": "Instance IDs attached to the load balancer.",
        },
    },
    "managed_databases": {
        "description": "Vultr Managed Databases (MySQL, PostgreSQL, Valkey, Kafka).",
        "docs_url": "https://www.vultr.com/api/#tag/managed-databases",
        "columns": {
            "id": "Unique identifier for the managed database.",
            "date_created": "Date and time the database was created (ISO 8601).",
            "plan": "Plan ID the database runs on.",
            "region": "Region ID where the database is deployed.",
            "database_engine": "Database engine (e.g. mysql, pg, valkey, kafka).",
            "database_engine_version": "Version of the database engine.",
            "status": "Current status of the database.",
            "label": "User-defined label for the database.",
            "host": "Connection host for the database.",
            "port": "Connection port for the database.",
        },
    },
    "users": {
        "description": "Sub-users configured on your Vultr account.",
        "docs_url": "https://www.vultr.com/api/#tag/users",
        "columns": {
            "id": "Unique identifier for the user.",
            "name": "Display name of the user.",
            "email": "Email address of the user.",
            "api_enabled": "Whether API access is enabled for the user.",
            "acls": "Access control list granted to the user.",
        },
    },
    "billing_history": {
        "description": "Append-only account billing history line items (charges and payments).",
        "docs_url": "https://www.vultr.com/api/#tag/billing",
        "columns": {
            "id": "Unique identifier for the billing history entry.",
            "date": "Date and time of the billing entry (ISO 8601).",
            "type": "Type of the entry (e.g. invoice, payment).",
            "description": "Description of the billing entry.",
            "amount": "Amount of the entry in account currency.",
            "balance": "Account balance after the entry.",
        },
    },
    "invoices": {
        "description": "Account invoices.",
        "docs_url": "https://www.vultr.com/api/#tag/billing",
        "columns": {
            "id": "Unique identifier for the invoice.",
            "date": "Date and time the invoice was issued (ISO 8601).",
            "description": "Description of the invoice.",
            "amount": "Total amount of the invoice in account currency.",
            "balance": "Account balance after the invoice.",
        },
    },
}
