from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

_DOCS = "https://betterstack.com/docs/uptime/api/getting-started-with-uptime-api/"

# Descriptions are sourced from Better Stack's public Uptime API reference. Partial coverage is
# fine — any endpoint, column, or table-level description not listed here falls back to LLM
# enrichment.
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "incidents": {
        "description": "Downtime and alert incidents recorded by Better Stack, with their cause, acknowledgement, and resolution timeline.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the incident.",
            "name": "Name of the monitor or heartbeat the incident belongs to.",
            "url": "URL of the checked resource the incident relates to.",
            "cause": "What caused the incident (e.g. a status code, timeout, or missed heartbeat).",
            "started_at": "When the incident started.",
            "acknowledged_at": "When the incident was acknowledged.",
            "acknowledged_by": "Who acknowledged the incident.",
            "resolved_at": "When the incident was resolved.",
            "resolved_by": "Who or what resolved the incident.",
            "response_content": "Response content captured when the incident was detected.",
        },
    },
    "monitors": {
        "description": "Uptime monitors configured in Better Stack, with their check settings and current status.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the monitor.",
            "url": "URL or host the monitor checks.",
            "pronounceable_name": "Human-readable name of the monitor.",
            "monitor_type": "Type of check the monitor performs (e.g. status, keyword, ping, tcp).",
            "monitor_group_id": "Identifier of the monitor group this monitor belongs to.",
            "status": "Current status of the monitor (e.g. up, down, paused, validating).",
            "check_frequency": "How often the monitor runs, in seconds.",
            "last_checked_at": "When the monitor was last checked.",
            "paused_at": "When the monitor was paused, if it is paused.",
            "created_at": "When the monitor was created.",
            "updated_at": "When the monitor was last updated.",
        },
    },
    "monitor_availability": {
        "description": "Availability summary per monitor: uptime percentage and downtime totals over the monitor's lifetime.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Identifier of the monitor the summary covers.",
            "monitor_id": "Identifier of the monitor the summary covers.",
            "availability": "Percentage of time the monitor was up.",
            "total_downtime": "Total time the monitor was down, in seconds.",
            "number_of_incidents": "Number of incidents recorded for the monitor.",
            "longest_incident": "Duration of the longest incident, in seconds.",
            "average_incident": "Average incident duration, in seconds.",
        },
    },
    "monitor_response_times": {
        "description": "Response time measurements per monitor and checking region, covering the last 24 hours of each sync.",
        "docs_url": _DOCS,
        "columns": {
            "monitor_id": "Identifier of the monitor the measurement belongs to.",
            "region": "Region the check was run from (e.g. us, eu).",
            "at": "When the check ran.",
            "response_time": "Total time to complete the request, in seconds.",
            "name_lookup_time": "Time spent resolving DNS, in seconds.",
            "connection_time": "Time spent establishing the connection, in seconds.",
            "tls_handshake_time": "Time spent on the TLS handshake, in seconds.",
            "data_transfer_time": "Time spent transferring the response body, in seconds.",
        },
    },
    "monitor_groups": {
        "description": "Groups used to organize uptime monitors.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the monitor group.",
            "name": "Name of the monitor group.",
            "sort_index": "Position of the group when sorting groups.",
            "created_at": "When the group was created.",
            "updated_at": "When the group was last updated.",
        },
    },
    "heartbeats": {
        "description": "Heartbeat (cron/background job) checks configured in Better Stack.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the heartbeat.",
            "name": "Name of the heartbeat.",
            "url": "URL the monitored service pings to report the heartbeat.",
            "period": "Expected interval between heartbeats, in seconds.",
            "grace": "Additional grace period before an incident is raised, in seconds.",
            "heartbeat_group_id": "Identifier of the heartbeat group this heartbeat belongs to.",
            "status": "Current status of the heartbeat.",
            "paused_at": "When the heartbeat was paused, if it is paused.",
            "created_at": "When the heartbeat was created.",
            "updated_at": "When the heartbeat was last updated.",
        },
    },
    "heartbeat_availability": {
        "description": "Availability summary per heartbeat: uptime percentage and downtime totals since the heartbeat was created.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Identifier of the heartbeat the summary covers.",
            "heartbeat_id": "Identifier of the heartbeat the summary covers.",
            "availability": "Percentage of time the heartbeat was up.",
            "total_downtime": "Total time the heartbeat was down, in seconds.",
            "number_of_incidents": "Number of incidents recorded for the heartbeat.",
            "longest_incident": "Duration of the longest incident, in seconds.",
            "average_incident": "Average incident duration, in seconds.",
        },
    },
    "heartbeat_groups": {
        "description": "Groups used to organize heartbeat checks.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the heartbeat group.",
            "name": "Name of the heartbeat group.",
            "sort_index": "Position of the group when sorting groups.",
            "created_at": "When the group was created.",
            "updated_at": "When the group was last updated.",
        },
    },
    "status_pages": {
        "description": "Public status pages hosted on Better Stack.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the status page.",
            "company_name": "Company name shown on the status page.",
            "company_url": "Company website linked from the status page.",
            "subdomain": "Better Stack subdomain the status page is served on.",
            "custom_domain": "Custom domain the status page is served on, if configured.",
            "timezone": "Timezone used to display times on the status page.",
            "history": "Number of days of incident history shown on the status page.",
            "created_at": "When the status page was created.",
            "updated_at": "When the status page was last updated.",
        },
    },
    "incident_comments": {
        "description": "Comments posted on an incident, including acknowledgement and resolution notes, with the incident they belong to.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the comment.",
            "incident_id": "Identifier of the incident the comment was posted on.",
            "content": "Text of the comment.",
            "user_id": "Identifier of the team member who posted the comment, absent for comments posted through the API.",
            "user_email": "Email address of the team member who posted the comment.",
            "created_at": "When the comment was posted.",
            "updated_at": "When the comment was last edited.",
        },
    },
    "on_calls": {
        "description": "On-call calendars defining who is on call and when.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the on-call calendar.",
            "name": "Name of the on-call calendar.",
        },
    },
    "on_call_events": {
        "description": "Resolved on-call shifts per schedule: who was on call over which period, including one-off overrides.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the on-call shift.",
            "on_call_id": "Identifier of the on-call calendar the shift belongs to.",
            "users": "Email addresses of the people on call during the shift.",
            "starts_at": "When the shift starts.",
            "ends_at": "When the shift ends.",
            "override": "Whether the shift is a one-off override of the regular rotation.",
        },
    },
    "on_call_rotations": {
        "description": "The rotation currently driving each on-call calendar: how long a turn lasts and who takes part.",
        "docs_url": _DOCS,
        "columns": {
            "on_call_id": "Identifier of the on-call calendar the rotation belongs to.",
            "rotation_length": "Length of one turn, counted in `rotation_interval` units.",
            "rotation_interval": "Unit the rotation length is counted in (e.g. hour, day, week).",
            "start_rotations_at": "When the rotation starts.",
            "end_rotations_at": "When the rotation ends.",
            "users": "Email addresses of the people taking part in the rotation.",
        },
    },
    "escalation_policies": {
        "description": "Escalation policies describing how incidents are escalated to team members.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the escalation policy.",
            "name": "Name of the escalation policy.",
            "repeat_count": "How many times the escalation steps are repeated.",
            "repeat_delay": "Delay between escalation repeats, in seconds.",
        },
    },
    "severities": {
        "description": "Severities used to route alerts, resolving the severity referenced on incidents. Better Stack's API names these urgencies.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the severity.",
            "name": "Name of the severity.",
            "team_name": "Name of the team the severity belongs to.",
            "sms": "Whether the severity alerts by SMS.",
            "call": "Whether the severity alerts by phone call.",
            "email": "Whether the severity alerts by email.",
            "push": "Whether the severity alerts by mobile push notification.",
        },
    },
    "severity_groups": {
        "description": "Groups used to organize severities.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the severity group.",
            "name": "Name of the severity group.",
            "sort_index": "Position of the group when sorting groups.",
            "team_name": "Name of the team the group belongs to.",
            "created_at": "When the group was created.",
            "updated_at": "When the group was last updated.",
        },
    },
    "status_page_resources": {
        "description": "The monitors and heartbeats each status page publishes, with the name and availability shown to visitors.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the status page resource.",
            "status_page_id": "Identifier of the status page the resource appears on.",
            "status_page_section_id": "Identifier of the section the resource is placed in.",
            "resource_id": "Identifier of the monitor or heartbeat the resource points at.",
            "resource_type": "Kind of thing the resource points at (e.g. Monitor, Heartbeat).",
            "public_name": "Name shown for the resource on the status page.",
            "explanation": "Description shown alongside the resource.",
            "widget_type": "How the resource is rendered on the status page (e.g. history, response times).",
            "history": "Whether past availability is shown for the resource.",
            "position": "Position of the resource within its section.",
            "mark_as_down_for": "Which incidents mark the resource as down.",
            "mark_as_degraded_for": "Which incidents mark the resource as degraded.",
            "availability": "Availability shown for the resource, as a fraction of 1.",
            "status": "Current status shown for the resource (e.g. operational, downtime).",
            "status_history": "Per-day status and downtime totals shown on the resource's history bar.",
        },
    },
    "team_members": {
        "description": "People in the Better Stack team, including pending invitations, resolving the user ids referenced by incidents and on-call schedules.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the team member or invitation.",
            "type": "Whether the row is an accepted team member or a pending invitation.",
            "email": "Email address of the team member.",
            "first_name": "First name of the team member.",
            "last_name": "Last name of the team member.",
            "role": "Role the member holds in the team (e.g. admin, responder, member, or custom).",
            "mobile_app_platforms": "Mobile platforms the member has the Better Stack app installed on.",
            "created_at": "When the member joined the team.",
            "invited_at": "When the invitation was sent, for pending invitations.",
        },
    },
    "roles": {
        "description": "Roles available in the organization, both built-in and custom, resolving the role names carried on team members.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the role.",
            "name": "Display name of the role.",
            "role": "System identifier of the role, or `custom` for user-defined roles.",
        },
    },
}
