# Column lists that more than one object uses.

locals {
  sharded_marketing_touchpoints_preaggregated_columns = [
    { name = "team_id", type = "Int64" },
    { name = "job_id", type = "UUID" },
    { name = "person_id", type = "UUID" },
    { name = "touchpoint_timestamp", type = "DateTime64(6, 'UTC')" },
    { name = "campaign_name", type = "String" },
    { name = "source_name", type = "String" },
    { name = "medium_name", type = "String" },
    { name = "content_name", type = "String" },
    { name = "term_name", type = "String" },
    { name = "referring_domain_name", type = "String" },
    { name = "gclid_name", type = "String" },
    { name = "fbclid_name", type = "String" },
    { name = "gad_source_name", type = "String" },
    { name = "computed_at", type = "DateTime64(6, 'UTC')", default_expression = "now()" },
    { name = "expires_at", type = "Date", default_expression = "today() + toIntervalDay(7)" },
  ]

  sharded_marketing_conversions_preaggregated_columns = [
    { name = "team_id", type = "Int64" },
    { name = "job_id", type = "UUID" },
    { name = "person_id", type = "UUID" },
    { name = "conversion_timestamp", type = "DateTime64(6, 'UTC')" },
    { name = "conversion_math_value", type = "Float64" },
    { name = "session_id", type = "String" },
    { name = "campaign_name", type = "String" },
    { name = "source_name", type = "String" },
    { name = "medium_name", type = "String" },
    { name = "content_name", type = "String" },
    { name = "term_name", type = "String" },
    { name = "referring_domain_name", type = "String" },
    { name = "gclid_name", type = "String" },
    { name = "fbclid_name", type = "String" },
    { name = "gad_source_name", type = "String" },
    { name = "computed_at", type = "DateTime64(6, 'UTC')", default_expression = "now()" },
    { name = "expires_at", type = "Date", default_expression = "today() + toIntervalDay(7)" },
  ]

  sharded_conversion_goal_attributed_preaggregated_columns = [
    { name = "team_id", type = "Int64" },
    { name = "job_id", type = "UUID" },
    { name = "person_id", type = "UUID" },
    { name = "conversion_timestamp", type = "DateTime64(6, 'UTC')" },
    { name = "conversion_value", type = "Float64" },
    { name = "touchpoint_timestamp", type = "DateTime64(6, 'UTC')" },
    { name = "touchpoint_weight", type = "Float64" },
    { name = "campaign_name", type = "String" },
    { name = "source_name", type = "String" },
    { name = "medium_name", type = "String" },
    { name = "content_name", type = "String" },
    { name = "term_name", type = "String" },
    { name = "referring_domain_name", type = "String" },
    { name = "gclid_name", type = "String" },
    { name = "fbclid_name", type = "String" },
    { name = "gad_source_name", type = "String" },
    { name = "computed_at", type = "DateTime64(6, 'UTC')", default_expression = "now()" },
    { name = "expires_at", type = "Date", default_expression = "today() + toIntervalDay(7)" },
  ]

  sharded_marketing_costs_preaggregated_columns = [
    { name = "team_id", type = "Int64" },
    { name = "job_id", type = "UUID" },
    { name = "source_id", type = "String" },
    { name = "source_name", type = "String" },
    { name = "grain", type = "LowCardinality(String)" },
    { name = "match_key", type = "String" },
    { name = "campaign_id", type = "String" },
    { name = "campaign_name", type = "String" },
    { name = "ad_group_id", type = "String" },
    { name = "ad_group_name", type = "String" },
    { name = "ad_id", type = "String" },
    { name = "ad_name", type = "String" },
    { name = "cost_date", type = "Date" },
    { name = "cost", type = "Float64" },
    { name = "clicks", type = "Float64" },
    { name = "impressions", type = "Float64" },
    { name = "reported_conversions", type = "Float64" },
    { name = "reported_conversion_value", type = "Float64" },
    { name = "computed_at", type = "DateTime64(6, 'UTC')", default_expression = "now()" },
    { name = "expires_at", type = "Date", default_expression = "today() + toIntervalDay(7)" },
  ]
}
