import { MakeLogicType, connect, kea, listeners, path } from 'kea'
import { router } from 'kea-router'

import { urls } from 'scenes/urls'

import { parseInvocationOutputRecord } from '../components/tool/widgets/extractors'
import { foregroundStreamLogic } from './foregroundStreamLogic'
import { toolStreamEventsLogic } from './toolStreamEventsLogic'

/**
 * Routes the browser when the agent's tool calls warrant it — creating a workflow or email template
 * follows the user to the new editor, and `navigate-user` is an explicit "take me there" ask. Only
 * reacts to live events from foreground streams (runs the user is actually watching), never to
 * replays or background runs. Mounted by `useForegroundStream`, so it is alive exactly while a
 * watching surface exists.
 */

function pushWithinApp(url: string): void {
    let parsed: URL
    try {
        parsed = new URL(url, window.location.origin)
    } catch {
        return
    }
    if (parsed.origin === window.location.origin) {
        router.actions.push(parsed.pathname + parsed.search + parsed.hash)
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface toolNavigationLogicValues {
    foregroundStreamKeys: Set<string> // foregroundStreamLogic
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface toolNavigationLogicActions {
    emitRunLifecycleEvent: (event: import('../types/streamTypes').RunLifecycleEvent) => {
        event: import('../types/streamTypes').RunLifecycleEvent
    } // toolStreamEventsLogic
    emitToolEvent: (event: import('../types/streamTypes').ToolStreamEvent) => {
        event: import('../types/streamTypes').ToolStreamEvent
    } // toolStreamEventsLogic
    emitTurnCompleteEvent: (event: import('../types/streamTypes').TurnCompleteEvent) => {
        event: import('../types/streamTypes').TurnCompleteEvent
    } // toolStreamEventsLogic
}

export type toolNavigationLogicType = MakeLogicType<toolNavigationLogicValues, toolNavigationLogicActions>

export const toolNavigationLogic = kea<toolNavigationLogicType>([
    path(['products', 'posthog_ai', 'frontend', 'logics', 'toolNavigationLogic']),
    connect(() => ({
        actions: [toolStreamEventsLogic, ['emitToolEvent', 'emitTurnCompleteEvent', 'emitRunLifecycleEvent']],
        values: [foregroundStreamLogic, ['foregroundStreamKeys']],
    })),
    listeners(({ cache, values }) => {
        cache.pendingTemplateRouteByStream = {} as Record<string, string>
        cache.workflowRoutedByStream = {} as Record<string, true>
        // A template created this turn only routes at turn end, and only if the turn didn't also
        // create a workflow — the workflow page is where the user works with the pair.
        const flushPendingRoutes = (streamKey: string): void => {
            const templateId = cache.pendingTemplateRouteByStream[streamKey]
            delete cache.pendingTemplateRouteByStream[streamKey]
            delete cache.workflowRoutedByStream[streamKey]
            if (templateId && !router.values.location.pathname.includes(`/workflows/library/templates/${templateId}`)) {
                router.actions.push(urls.workflowsLibraryTemplate(templateId))
            }
        }
        return {
            emitToolEvent: ({ event }) => {
                if (
                    event.phase !== 'completed' ||
                    event.source !== 'live' ||
                    !values.foregroundStreamKeys.has(event.streamKey)
                ) {
                    return
                }
                if (event.toolName === 'workflows-create') {
                    const record = parseInvocationOutputRecord(event.invocation)
                    const workflowId = typeof record?.id === 'string' ? record.id : null
                    if (!workflowId) {
                        return
                    }
                    // The workflow page wins over any template created in the same turn.
                    cache.workflowRoutedByStream[event.streamKey] = true
                    delete cache.pendingTemplateRouteByStream[event.streamKey]
                    if (!router.values.location.pathname.includes(`/workflows/${workflowId}`)) {
                        router.actions.push(urls.workflow(workflowId, 'workflow'))
                    }
                } else if (
                    event.toolName === 'workflows-create-email-template' &&
                    !cache.workflowRoutedByStream[event.streamKey]
                ) {
                    const record = parseInvocationOutputRecord(event.invocation)
                    const templateId = typeof record?.id === 'string' ? record.id : null
                    if (templateId) {
                        // Deferred to turn end so a workflow created later in the turn takes precedence.
                        cache.pendingTemplateRouteByStream[event.streamKey] = templateId
                    }
                } else if (event.toolName === 'navigate-user') {
                    const record = parseInvocationOutputRecord(event.invocation)
                    const url = typeof record?.url === 'string' ? record.url : null
                    if (url) {
                        // Only ever within this app's origin; foreign URLs stay a link in the reply.
                        pushWithinApp(url)
                    }
                }
            },
            emitTurnCompleteEvent: ({ event }) => flushPendingRoutes(event.streamKey),
            emitRunLifecycleEvent: ({ event }) => flushPendingRoutes(event.streamKey),
        }
    }),
])
