from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "repos": {
        "description": "A repository Codecov tracks for the configured owner, with its latest coverage totals.",
        "docs_url": "https://docs.codecov.com/reference/repos_list",
        "columns": {
            "name": "Repository name, unique within the owner.",
            "private": "Whether the repository is private on the git provider.",
            "updatestamp": "When Codecov last updated its state for this repository.",
            "author": "Owner of the repository (service, username, name).",
            "language": "Primary programming language of the repository.",
            "branch": "Default branch used for coverage reporting.",
            "active": "Whether the repository has received a coverage upload.",
            "activated": "Whether the repository has been manually activated in Codecov.",
            "totals": "Latest coverage totals for the default branch (files, lines, hits, misses, partials, coverage percentage).",
        },
    },
    "branches": {
        "description": "A branch of a repository that has coverage data in Codecov.",
        "docs_url": "https://docs.codecov.com/reference/repos_branches_list",
        "columns": {
            "repo": "Repository the branch belongs to (injected by the import).",
            "name": "Branch name, unique within the repository.",
            "updatestamp": "When coverage data for the branch was last updated.",
        },
    },
    "commits": {
        "description": "A commit with a coverage upload on the repository's default branch.",
        "docs_url": "https://docs.codecov.com/reference/repos_commits_list",
        "columns": {
            "repo": "Repository the commit belongs to (injected by the import).",
            "commitid": "Full git commit SHA.",
            "message": "Commit message.",
            "timestamp": "Commit timestamp.",
            "ci_passed": "Whether CI passed for this commit, if known.",
            "author": "Commit author (service, username, name).",
            "branch": "Branch the coverage upload was reported against.",
            "totals": "Coverage totals for the commit (files, lines, hits, misses, partials, coverage percentage).",
            "state": "Codecov processing state of the commit report (e.g. complete).",
            "parent": "SHA of the parent commit.",
        },
    },
    "pulls": {
        "description": "A pull request Codecov tracks for a repository, with base/head coverage totals.",
        "docs_url": "https://docs.codecov.com/reference/repos_pulls_list",
        "columns": {
            "repo": "Repository the pull request belongs to (injected by the import).",
            "pullid": "Pull request number on the git provider.",
            "title": "Pull request title.",
            "base_totals": "Coverage totals of the base commit.",
            "head_totals": "Coverage totals of the head commit.",
            "updatestamp": "When Codecov last updated its state for this pull request.",
            "state": "Pull request state (open, merged, closed).",
            "ci_passed": "Whether CI passed on the head commit, if known.",
            "author": "Pull request author (service, username, name).",
            "patch": "Patch coverage totals for the lines changed by the pull request.",
        },
    },
    "flags": {
        "description": "Current coverage per flag (a user-defined grouping of coverage uploads) in a repository.",
        "docs_url": "https://docs.codecov.com/reference/repos_flags_list",
        "columns": {
            "repo": "Repository the flag belongs to (injected by the import).",
            "flag_name": "Flag name, unique within the repository.",
            "coverage": "Latest coverage percentage for the flag.",
        },
    },
    "components": {
        "description": "Current coverage per component (a path/flag-based slice of a repository defined in codecov.yml).",
        "docs_url": "https://docs.codecov.com/reference/repos_components_list",
        "columns": {
            "repo": "Repository the component belongs to (injected by the import).",
            "component_id": "Component identifier from the repository's Codecov configuration.",
            "name": "Display name of the component.",
            "coverage": "Latest coverage percentage for the component.",
        },
    },
    "repo_totals": {
        "description": "Current coverage totals for a repository, measured on the head commit of its default branch.",
        "docs_url": "https://docs.codecov.com/reference/repos_totals_retrieve",
        "columns": {
            "repo": "Repository the totals belong to (injected by the import).",
            "files": "Number of files included in the coverage report.",
            "lines": "Number of trackable lines across those files.",
            "hits": "Number of lines covered by at least one test.",
            "misses": "Number of lines not covered by any test.",
            "partials": "Number of lines only partially covered (some branches taken).",
            "coverage": "Coverage percentage of the repository.",
            "branches": "Number of branch points in the report.",
            "methods": "Number of methods in the report.",
            "messages": "Number of messages recorded against the report.",
            "sessions": "Number of coverage uploads merged into the report.",
            "complexity": "Cyclomatic complexity covered, where the language reports it.",
            "complexity_total": "Total cyclomatic complexity, where the language reports it.",
            "complexity_ratio": "Covered complexity as a percentage of total complexity.",
            "diff": "Coverage totals of the commit diff, when Codecov recorded them.",
            "commit_file_url": "Codecov URL to view coverage for the commit these totals came from.",
        },
    },
    "report_files": {
        "description": "Current coverage of a single file in a repository, from the head commit of its default branch.",
        "docs_url": "https://docs.codecov.com/reference/repos_report_retrieve",
        "columns": {
            "repo": "Repository the file belongs to (injected by the import).",
            "name": "File path, relative to the repository root.",
            "totals": "Coverage totals for the file (lines, hits, misses, partials, coverage percentage).",
            "line_coverage": "Line-by-line coverage as [line number, state] pairs, where state is 0 hit, 1 miss, 2 partial.",
        },
    },
    "report_tree": {
        "description": "Coverage rolled up at one node of the repository file tree — a directory or a file.",
        "docs_url": "https://docs.codecov.com/reference/repos_report_tree_retrieve",
        "columns": {
            "repo": "Repository the node belongs to (injected by the import).",
            "name": "Name of the directory or file, without its parent path.",
            "full_path": "Path of the node from the repository root.",
            "coverage": "Coverage percentage of everything under this node.",
            "lines": "Number of trackable lines under this node.",
            "hits": "Number of covered lines under this node.",
            "partials": "Number of partially covered lines under this node.",
            "misses": "Number of uncovered lines under this node.",
        },
    },
    "test_results": {
        "description": "A single run of a single test, recorded by Codecov Test Analytics from an uploaded test report.",
        "docs_url": "https://docs.codecov.com/reference/repos_test_results_list",
        "columns": {
            "repo": "Repository the test ran in (injected by the import).",
            "test_id": "Identifier of the test, stable across runs.",
            "name": "Test name as reported by the test framework.",
            "classname": "Class the test belongs to, where the framework reports one.",
            "testsuite": "Test suite the test belongs to.",
            "computed_name": "Display name Codecov builds from the suite, class and test name.",
            "outcome": "Result of the run: pass, failure, error or skip.",
            "duration_seconds": "How long the test took to run, in seconds.",
            "failure_message": "Failure output captured for a failing run.",
            "framework": "Test framework that produced the result.",
            "filename": "File the test is defined in.",
            "repo_id": "Codecov internal repository id.",
            "commit_sha": "SHA of the commit the test ran against.",
            "branch": "Branch the test ran on.",
            "flags": "Coverage flags attached to the upload this run came from.",
            "upload_id": "Codecov id of the upload that carried this run.",
            "properties": "Extra properties the test framework attached to the run.",
            "timestamp": "When the test run was recorded.",
        },
    },
    "users": {
        "description": "A member of the Codecov organization, including whether they hold an active seat.",
        "docs_url": "https://docs.codecov.com/reference/users_list",
        "columns": {
            "service": "Git hosting provider the member signed in through.",
            "username": "Username on the git provider, unique within the organization.",
            "name": "Display name of the member.",
            "email": "Email address of the member.",
            "activated": "Whether the member holds an activated seat in the organization.",
            "is_admin": "Whether the member is an admin of the organization.",
        },
    },
    "coverage_trend": {
        "description": "Daily coverage time series for a repository's default branch.",
        "docs_url": "https://docs.codecov.com/reference/repos_coverage_list",
        "columns": {
            "repo": "Repository the measurement belongs to (injected by the import).",
            "timestamp": "Start of the measured interval (one day).",
            "min": "Minimum coverage percentage observed in the interval.",
            "max": "Maximum coverage percentage observed in the interval.",
            "avg": "Average coverage percentage observed in the interval.",
        },
    },
}
