from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Timestamp columns are Dagster epoch-seconds floats at the API, normalized to ISO-8601 UTC strings
# on ingest (see dagster_cloud.py:_epoch_to_iso).
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "runs": {
        "description": "Historical job/pipeline run records for the deployment, used to compute reliability, DORA, and SLA metrics.",
        "docs_url": "https://docs.dagster.io/api/graphql",
        "columns": {
            "runId": "Unique identifier for the run.",
            "jobName": "Name of the job (pipeline) the run executed.",
            "pipelineName": "Legacy alias for the job name.",
            "status": "Run status (e.g. QUEUED, STARTED, SUCCESS, FAILURE, CANCELED).",
            "mode": "Execution mode the run used.",
            "creationTime": "When the run record was created.",
            "startTime": "When the run started executing.",
            "endTime": "When the run finished executing.",
            "updateTime": "When the run record was last updated (advances as the run's status changes).",
            "tags": "Key/value tags attached to the run.",
            "repositoryOrigin": "The code location and repository the run originated from.",
            "assetSelection": "Asset keys the run targeted, each as a path list.",
        },
    },
    "backfills": {
        "description": "Partition backfills launched in the deployment, including asset backfills.",
        "docs_url": "https://docs.dagster.io/api/graphql",
        "columns": {
            "id": "Unique identifier for the backfill.",
            "status": "Bulk-action status of the backfill (e.g. REQUESTED, COMPLETED, FAILED, CANCELED).",
            "timestamp": "When the backfill was created.",
            "endTimestamp": "When the backfill finished, if it has.",
            "numPartitions": "Number of partitions targeted by the backfill.",
            "partitionSetName": "Name of the partition set the backfill ran against.",
            "jobName": "Name of the job the backfill executed, if any.",
            "isAssetBackfill": "Whether this is an asset backfill rather than a job backfill.",
            "title": "User-provided title for the backfill.",
            "description": "User-provided description for the backfill.",
            "user": "User who launched the backfill.",
        },
    },
    "assets": {
        "description": "Catalog of assets known to the deployment.",
        "docs_url": "https://docs.dagster.io/api/graphql",
        "columns": {
            "id": "Unique identifier for the asset (its serialized asset key).",
            "key": "The asset key as a path list.",
        },
    },
    "schedules": {
        "description": "Schedule definitions in each code location, with their cron expression and default status.",
        "docs_url": "https://docs.dagster.io/api/graphql",
        "columns": {
            "id": "Unique identifier for the schedule definition.",
            "name": "Name of the schedule.",
            "cronSchedule": "Cron expression the schedule ticks on.",
            "pipelineName": "Name of the job the schedule launches.",
            "mode": "Execution mode the schedule launches runs in.",
            "executionTimezone": "Timezone the cron expression is evaluated in.",
            "description": "Description declared on the schedule.",
            "defaultStatus": "Status the schedule starts in when the code location loads (RUNNING or STOPPED).",
            "scheduleState": "Current instigation state of the schedule, including its live status.",
            "assetSelection": "Assets the schedule targets, if it is an asset schedule.",
            "tags": "Key/value tags declared on the schedule.",
            "repositoryName": "Repository the schedule is defined in.",
            "repositoryLocationName": "Code location the repository is loaded from.",
        },
    },
    "sensors": {
        "description": "Sensor definitions in each code location, with their type, tick interval, and default status.",
        "docs_url": "https://docs.dagster.io/api/graphql",
        "columns": {
            "id": "Unique identifier for the sensor definition.",
            "name": "Name of the sensor.",
            "jobOriginId": "Identifier of the sensor's origin within its code location.",
            "sensorType": "Kind of sensor (e.g. STANDARD, RUN_STATUS, ASSET, AUTOMATION, FRESHNESS_POLICY).",
            "description": "Description declared on the sensor.",
            "defaultStatus": "Status the sensor starts in when the code location loads (RUNNING or STOPPED).",
            "minIntervalSeconds": "Minimum seconds Dagster waits between sensor evaluations.",
            "targets": "Jobs the sensor can launch.",
            "sensorState": "Current instigation state of the sensor, including its live status.",
            "assetSelection": "Assets the sensor targets, if it is an asset sensor.",
            "metadata": "Asset keys the sensor monitors.",
            "tags": "Key/value tags declared on the sensor.",
            "repositoryName": "Repository the sensor is defined in.",
            "repositoryLocationName": "Code location the repository is loaded from.",
        },
    },
    "instigation_states": {
        "description": "Live state of every schedule and sensor, including the cursor a sensor last stored.",
        "docs_url": "https://docs.dagster.io/api/graphql",
        "columns": {
            "id": "Compound identifier for the instigation state.",
            "selectorId": "Stable identifier of the schedule or sensor this state belongs to.",
            "name": "Name of the schedule or sensor.",
            "instigationType": "Whether the state belongs to a SCHEDULE or a SENSOR.",
            "status": "Whether the schedule or sensor is currently RUNNING or STOPPED.",
            "repositoryName": "Repository the schedule or sensor is defined in.",
            "repositoryLocationName": "Code location the repository is loaded from.",
            "repositoryOrigin": "The code location and repository the state originated from.",
            "runsCount": "Number of runs launched by this schedule or sensor.",
            "typeSpecificData": "Schedule cron and start time, or sensor last tick, last run key, and last cursor.",
        },
    },
    "instigation_ticks": {
        "description": "Tick history for every schedule and sensor — one row per evaluation, with its outcome and the runs it requested. Used for orchestration reliability analysis.",
        "docs_url": "https://docs.dagster.io/api/graphql",
        "columns": {
            "id": "Identifier for the tick, scoped to its schedule or sensor.",
            "tickId": "Identifier of the stored tick record.",
            "status": "Outcome of the tick (STARTED, SKIPPED, SUCCESS, or FAILURE).",
            "timestamp": "When the tick was evaluated.",
            "endTimestamp": "When the tick finished, if it has.",
            "runIds": "Identifiers of the runs the tick launched.",
            "runKeys": "Idempotency keys of the run requests the tick produced.",
            "originRunIds": "Identifiers of the runs that caused this tick, for run-status sensors.",
            "skipReason": "Why the tick requested no runs, when it was skipped.",
            "cursor": "Cursor the sensor stored at the end of the tick.",
            "instigationType": "Whether the tick belongs to a SCHEDULE or a SENSOR.",
            "requestedAssetMaterializationCount": "Number of asset materializations the tick requested.",
            "requestedAssetKeys": "Asset keys the tick requested, each as a path list.",
            "error": "Error raised during the tick, when it failed.",
            "instigationName": "Name of the schedule or sensor the tick belongs to.",
            "instigationSelectorId": "Stable identifier of the schedule or sensor the tick belongs to.",
            "repositoryName": "Repository the schedule or sensor is defined in.",
            "repositoryLocationName": "Code location the repository is loaded from.",
        },
    },
    "asset_nodes": {
        "description": "Asset definition metadata — group, owning jobs, dependencies, partitioning, and freshness policy. Resolves the bare asset keys in the assets table.",
        "docs_url": "https://docs.dagster.io/api/graphql",
        "columns": {
            "id": "Unique identifier for the asset definition.",
            "assetKey": "The asset key as a path list.",
            "groupName": "Asset group the definition belongs to.",
            "description": "Description declared on the asset.",
            "computeKind": "Compute kind label declared on the asset (e.g. dbt, python).",
            "opName": "Name of the op that computes the asset.",
            "opNames": "Names of every op that computes the asset.",
            "jobNames": "Jobs that can materialize the asset.",
            "kinds": "Kind labels declared on the asset.",
            "isPartitioned": "Whether the asset is partitioned.",
            "isObservable": "Whether the asset can be observed rather than materialized.",
            "isMaterializable": "Whether the asset can be materialized by Dagster.",
            "isExecutable": "Whether the asset has executable compute attached.",
            "owners": "Owners declared on the asset, each a user email or a team name.",
            "dependencyKeys": "Asset keys this asset reads from.",
            "dependedByKeys": "Asset keys that read from this asset.",
            "freshnessPolicy": "Freshness policy declared on the asset, if any.",
            "autoMaterializePolicy": "Automation policy declared on the asset, if any.",
            "partitionDefinition": "How the asset is partitioned, if it is.",
            "tags": "Key/value tags declared on the asset.",
            "repository": "Repository and code location the definition is loaded from.",
        },
    },
    "asset_materializations": {
        "description": "Materialization event history per asset — one row each time an asset was materialized, with the metadata the run attached. The fact table behind the asset catalog.",
        "docs_url": "https://docs.dagster.io/api/graphql",
        "columns": {
            "assetId": "Identifier of the asset the event belongs to.",
            "runId": "Identifier of the run that materialized the asset.",
            "timestamp": "When the materialization was recorded.",
            "stepKey": "Step within the run that reported the materialization.",
            "partition": "Partition materialized, for a partitioned asset.",
            "label": "Label recorded on the materialization.",
            "description": "Description recorded on the materialization.",
            "assetKey": "The asset key as a path list.",
            "tags": "Key/value tags recorded on the materialization event.",
            "metadataEntries": "Metadata the run attached to the materialization, with each entry's type and label.",
        },
    },
    "asset_observations": {
        "description": "Observation event history per asset — one row each time an observable asset was observed, with the metadata the observation reported.",
        "docs_url": "https://docs.dagster.io/api/graphql",
        "columns": {
            "assetId": "Identifier of the asset the event belongs to.",
            "runId": "Identifier of the run that observed the asset.",
            "timestamp": "When the observation was recorded.",
            "stepKey": "Step within the run that reported the observation.",
            "partition": "Partition observed, for a partitioned asset.",
            "label": "Label recorded on the observation.",
            "description": "Description recorded on the observation.",
            "assetKey": "The asset key as a path list.",
            "tags": "Key/value tags recorded on the observation event.",
            "metadataEntries": "Metadata the run attached to the observation, with each entry's type and label.",
        },
    },
    "deployments": {
        "description": "Every deployment in the organization, both the full deployments and the branch deployments open against them. The lookup resolving which Dagster+ deployment a run or asset belongs to.",
        "docs_url": "https://docs.dagster.io/api/graphql",
        "columns": {
            "organizationId": "Identifier of the organization the deployment belongs to.",
            "organizationName": "Name of the organization the deployment belongs to.",
            "deploymentId": "Unique identifier for the deployment.",
            "deploymentName": "Name of the deployment (e.g. prod).",
            "deploymentStatus": "Whether the deployment is ACTIVE or PENDING_DELETION.",
            "deploymentType": "Whether the deployment is a PRODUCTION or a BRANCH deployment.",
            "isBranchDeployment": "Whether the deployment is an ephemeral branch deployment.",
            "agentType": "Whether the deployment runs on a HYBRID or a SERVERLESS agent.",
            "parentDeployment": "Full deployment a branch deployment was created from.",
            "branchDeploymentGitMetadata": "Branch, repository and pull request a branch deployment tracks.",
            "latestCommit": "Most recent commit deployed to the deployment, with its author and message.",
        },
    },
    "run_logs": {
        "description": "Event log for each run, covering step starts, successes, failures, retries and log messages. Resolves what happened inside the runs table's rows.",
        "docs_url": "https://docs.dagster.io/api/graphql",
        "columns": {
            "runId": "Identifier of the run the event belongs to.",
            "eventIndex": "Position of the event in its run's event stream, counted from zero.",
            "runUpdateTime": "When the run record was last updated. Each incremental sync reads the runs that moved since the previous one.",
            "eventTypename": "GraphQL type of the event (e.g. ExecutionStepFailureEvent, LogMessageEvent).",
            "eventType": "Dagster event type the event reports (e.g. STEP_START, STEP_FAILURE), when it has one.",
            "message": "Human-readable message recorded with the event.",
            "timestamp": "When the event was recorded.",
            "level": "Log level of the event (e.g. DEBUG, INFO, ERROR).",
            "stepKey": "Step within the run that emitted the event.",
            "solidHandleID": "Handle of the op that emitted the event.",
            "pipelineName": "Name of the job the run executed, on run-level events.",
            "markerStart": "Name of the timing marker the event opens, for step and engine timings.",
            "markerEnd": "Name of the timing marker the event closes.",
            "error": "Error the event carries, with its message and exception class.",
        },
    },
    "users": {
        "description": "Organization members and the roles granted to each, for attributing runs and backfills to people. Needs organization-level permissions.",
        "docs_url": "https://docs.dagster.io/api/graphql",
        "columns": {
            "id": "Unique identifier for the user's permission record.",
            "licensedRole": "Highest role the user holds, which is what the organization is billed for.",
            "user": "The user's profile: identifier, email, name, and whether SCIM provisioned them.",
            "organizationPermissionGrant": "Role granted across the whole organization, if any.",
            "allBranchDeploymentsPermissionGrant": "Role granted across every branch deployment, if any.",
            "deploymentPermissionGrants": "Roles granted on individual deployments, each with its location-scoped overrides.",
        },
    },
    "teams": {
        "description": "Teams in the organization, their members, and the roles granted to each team. Needs organization-level permissions.",
        "docs_url": "https://docs.dagster.io/api/graphql",
        "columns": {
            "id": "Unique identifier for the team's permission record.",
            "team": "The team itself: identifier, name, and the users in it.",
            "organizationPermissionGrant": "Role granted across the whole organization, if any.",
            "allBranchDeploymentsPermissionGrant": "Role granted across every branch deployment, if any.",
            "deploymentPermissionGrants": "Roles granted on individual deployments, each with its location-scoped overrides.",
        },
    },
    "custom_roles": {
        "description": "Custom roles defined in the organization and the permissions each one carries. Resolves the custom role identifiers on the users and teams tables. Needs organization-level permissions.",
        "docs_url": "https://docs.dagster.io/api/graphql",
        "columns": {
            "id": "Unique identifier for the custom role.",
            "name": "Name of the custom role.",
            "description": "Description declared on the custom role.",
            "iconName": "Icon chosen for the custom role.",
            "permissions": "Permissions the role grants (e.g. START_AND_STOP_RUNS, EDIT_ALERTS).",
            "deploymentScope": "Whether the role applies at DEPLOYMENT or ORGANIZATION scope.",
        },
    },
    "insights_job_metrics": {
        "description": "Dagster+ Insights metrics per job over time, such as credits consumed, execution time, and materialization and retry counts. One row per metric, job and time bucket.",
        "docs_url": "https://docs.dagster.io/guides/monitor/insights",
        "columns": {
            "metricName": "Name of the Insights metric the row measures (e.g. dagster_credits, execution_time_ms).",
            "entityId": "Stable identifier of the entity the measurement belongs to.",
            "entityType": "Kind of entity the measurement belongs to.",
            "timestamp": "Start of the bucket the value covers.",
            "value": "Value of the metric in that bucket. Buckets the metric did not report are left out.",
            "granularity": "Size of each bucket the metric is reported in.",
            "jobName": "Name of the job the measurement belongs to.",
            "codeLocationName": "Code location the job is loaded from.",
            "repositoryName": "Repository the job is defined in.",
        },
    },
    "insights_asset_metrics": {
        "description": "Dagster+ Insights metrics per asset over time, such as credits consumed, execution time, and materialization and retry counts. One row per metric, asset and time bucket.",
        "docs_url": "https://docs.dagster.io/guides/monitor/insights",
        "columns": {
            "metricName": "Name of the Insights metric the row measures (e.g. dagster_credits, execution_time_ms).",
            "entityId": "Stable identifier of the entity the measurement belongs to.",
            "entityType": "Kind of entity the measurement belongs to.",
            "timestamp": "Start of the bucket the value covers.",
            "value": "Value of the metric in that bucket. Buckets the metric did not report are left out.",
            "granularity": "Size of each bucket the metric is reported in.",
            "assetKey": "The asset key as a path list.",
            "assetGroup": "Asset group the asset belongs to.",
            "codeLocationName": "Code location the asset is loaded from.",
            "repositoryName": "Repository the asset is defined in.",
        },
    },
    "insights_deployment_metrics": {
        "description": "Dagster+ Insights metrics per deployment over time, such as credits consumed, execution time, and materialization and retry counts. One row per metric, deployment and time bucket.",
        "docs_url": "https://docs.dagster.io/guides/monitor/insights",
        "columns": {
            "metricName": "Name of the Insights metric the row measures (e.g. dagster_credits, execution_time_ms).",
            "entityId": "Stable identifier of the entity the measurement belongs to.",
            "entityType": "Kind of entity the measurement belongs to.",
            "timestamp": "Start of the bucket the value covers.",
            "value": "Value of the metric in that bucket. Buckets the metric did not report are left out.",
            "granularity": "Size of each bucket the metric is reported in.",
            "deploymentId": "Identifier of the deployment the measurement belongs to.",
            "deploymentName": "Name of the deployment the measurement belongs to.",
            "deploymentType": "Whether the deployment is a PRODUCTION or a BRANCH deployment.",
            "isBranchDeployment": "Whether the deployment is an ephemeral branch deployment.",
        },
    },
}
