from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Curated from the Buildkite v2 REST API docs (https://buildkite.com/docs/apis/rest-api).
# Keyed by the endpoint/schema name from settings.ENDPOINTS.
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "organizations": {
        "description": "A Buildkite organization the API access token can read.",
        "docs_url": "https://buildkite.com/docs/apis/rest-api/organizations",
        "columns": {
            "id": "Unique identifier for the organization.",
            "slug": "URL-friendly identifier used in API paths and the web UI.",
            "name": "Display name of the organization.",
            "web_url": "URL of the organization in the Buildkite web UI.",
            "url": "API URL for the organization.",
            "pipelines_url": "API URL listing the organization's pipelines.",
            "agents_url": "API URL listing the organization's agents.",
            "created_at": "Time the organization was created (ISO 8601).",
        },
    },
    "pipelines": {
        "description": "A pipeline defines the steps Buildkite runs for a project's builds.",
        "docs_url": "https://buildkite.com/docs/apis/rest-api/pipelines",
        "columns": {
            "id": "Unique identifier for the pipeline.",
            "slug": "URL-friendly identifier for the pipeline within its organization.",
            "name": "Display name of the pipeline.",
            "repository": "Git repository URL the pipeline builds.",
            "web_url": "URL of the pipeline in the Buildkite web UI.",
            "url": "API URL for the pipeline.",
            "builds_url": "API URL listing the pipeline's builds.",
            "default_branch": "Branch builds run against by default.",
            "description": "Human-readable description of the pipeline.",
            "created_at": "Time the pipeline was created (ISO 8601).",
            "archived_at": "Time the pipeline was archived, or null if active (ISO 8601).",
            "builds_count": "Total number of builds run for the pipeline.",
            "running_builds_count": "Number of builds currently running.",
            "scheduled_builds_count": "Number of builds currently scheduled.",
            "visibility": "Whether the pipeline is public or private.",
        },
    },
    "builds": {
        "description": "A single run of a pipeline, made up of one or more jobs.",
        "docs_url": "https://buildkite.com/docs/apis/rest-api/builds",
        "columns": {
            "id": "Unique identifier for the build.",
            "number": "Sequential build number within its pipeline.",
            "state": "Current state of the build (e.g. running, passed, failed, canceled).",
            "blocked": "Whether the build is blocked waiting on a manual unblock step.",
            "message": "Commit message or build message associated with the build.",
            "commit": "Git commit SHA the build ran against.",
            "branch": "Git branch the build ran against.",
            "web_url": "URL of the build in the Buildkite web UI.",
            "url": "API URL for the build.",
            "created_at": "Time the build was created (ISO 8601).",
            "scheduled_at": "Time the build was scheduled (ISO 8601).",
            "started_at": "Time the build started running (ISO 8601).",
            "finished_at": "Time the build finished, or null if still running (ISO 8601).",
            "creator": "The user or trigger that created the build.",
            "pipeline": "The pipeline this build belongs to.",
            "jobs": "The jobs that make up the build.",
            "source": "What triggered the build (e.g. ui, api, webhook, schedule).",
        },
    },
    "agents": {
        "description": "A connected Buildkite agent that runs jobs for the organization.",
        "docs_url": "https://buildkite.com/docs/apis/rest-api/agents",
        "columns": {
            "id": "Unique identifier for the agent.",
            "name": "Name the agent registered with.",
            "connection_state": "Current connection state of the agent (e.g. connected, disconnected, lost).",
            "hostname": "Hostname of the machine running the agent.",
            "ip_address": "IP address the agent connected from.",
            "version": "Version of the Buildkite agent software.",
            "web_url": "URL of the agent in the Buildkite web UI.",
            "url": "API URL for the agent.",
            "created_at": "Time the agent connected (ISO 8601).",
            "last_job_finished_at": "Time the agent last finished a job (ISO 8601).",
            "meta_data": "Agent metadata tags used for targeting jobs.",
        },
    },
    "jobs": {
        "description": "A single job within a build — the unit an agent actually runs.",
        "docs_url": "https://buildkite.com/docs/apis/rest-api/jobs",
        "columns": {
            "id": "Unique identifier for the job.",
            "type": "Kind of job (e.g. script, waiter, manual, trigger).",
            "name": "Display name of the job.",
            "step_key": "Key of the pipeline step that produced the job.",
            "state": "Current state of the job (e.g. scheduled, running, passed, failed, canceled).",
            "command": "Command the job ran.",
            "soft_failed": "Whether the job failed but was configured not to fail the build.",
            "exit_status": "Process exit status of the job, or null if it has not finished.",
            "agent": "The agent that ran the job.",
            "agent_query_rules": "Targeting rules used to pick an agent for the job.",
            "web_url": "URL of the job in the Buildkite web UI.",
            "log_url": "API URL for the job's log output.",
            "artifacts_url": "API URL listing the job's artifacts.",
            "created_at": "Time the job was created (ISO 8601).",
            "scheduled_at": "Time the job was scheduled (ISO 8601).",
            "runnable_at": "Time the job became runnable (ISO 8601).",
            "started_at": "Time the job started running (ISO 8601).",
            "finished_at": "Time the job finished, or null if still running (ISO 8601).",
            "expired_at": "Time the job expired without running (ISO 8601).",
            "concurrency_wait_time_ms": "Milliseconds spent waiting for a concurrency group slot.",
            "retried": "Whether the job was retried.",
            "retried_in_job_id": "Identifier of the job this one was retried into.",
            "retries_count": "Number of times the job has been retried.",
            "retry_source": "What requested the retry.",
            "retry_type": "Whether the retry was automatic or manual.",
            "parallel_group_index": "Index of this job within its parallel group.",
            "parallel_group_total": "Total number of jobs in its parallel group.",
            "matrix": "Matrix values the job was expanded with.",
            "cluster_id": "Identifier of the cluster the job ran on.",
            "cluster_queue_id": "Identifier of the cluster queue the job ran on.",
            "build_id": "Identifier of the build the job belongs to.",
            "build_number": "Number of the build the job belongs to.",
            "build_created_at": "Time the parent build was created (ISO 8601).",
            "pipeline_slug": "Slug of the pipeline the job's build ran for.",
        },
    },
    "teams": {
        "description": "A team within the organization, used to grant access to pipelines and suites.",
        "docs_url": "https://buildkite.com/docs/apis/rest-api/teams",
        "columns": {
            "id": "Unique identifier for the team.",
            "name": "Display name of the team.",
            "slug": "URL-friendly identifier for the team within its organization.",
            "description": "Human-readable description of the team.",
            "privacy": "Whether the team is visible or secret.",
            "default": "Whether new organization members join this team automatically.",
            "created_at": "Time the team was created (ISO 8601).",
            "created_by": "The user who created the team.",
        },
    },
    "test_suites": {
        "description": "A Test Engine suite collecting the test results uploaded for a project.",
        "docs_url": "https://buildkite.com/docs/apis/rest-api/test-engine/suites",
        "columns": {
            "id": "Unique identifier for the suite.",
            "organization_id": "Identifier of the organization the suite belongs to.",
            "slug": "URL-friendly identifier for the suite within its organization.",
            "name": "Display name of the suite.",
            "url": "API URL for the suite.",
            "web_url": "URL of the suite in the Buildkite web UI.",
            "default_branch": "Branch treated as the suite's baseline.",
            "application_name": "Name of the application the suite covers.",
            "color": "Display color of the suite.",
            "emoji": "Display emoji of the suite.",
        },
    },
    "test_suite_runs": {
        "description": "One upload of test results to a Test Engine suite, usually one per CI build.",
        "docs_url": "https://buildkite.com/docs/apis/rest-api/test-engine/runs",
        "columns": {
            "id": "Unique identifier for the run.",
            "branch": "Git branch the run covers.",
            "commit_sha": "Git commit SHA the run covers.",
            "state": "Whether the run is still receiving results or has finished.",
            "result": "Outcome of the run (e.g. passed, failed).",
            "url": "API URL for the run.",
            "web_url": "URL of the run in the Buildkite web UI.",
            "build_id": "Identifier of the build that uploaded the run.",
            "created_at": "Time the run was created (ISO 8601).",
            "suite_id": "Identifier of the suite the run belongs to.",
            "suite_slug": "Slug of the suite the run belongs to.",
        },
    },
    "test_suite_tests": {
        "description": "An individual test tracked by a Test Engine suite, with the labels applied to it.",
        "docs_url": "https://buildkite.com/docs/apis/rest-api/test-engine/tests",
        "columns": {
            "id": "Unique identifier for the test.",
            "url": "API URL for the test.",
            "web_url": "URL of the test in the Buildkite web UI.",
            "scope": "Grouping the test belongs to, such as its describe block or class.",
            "name": "Name of the test.",
            "location": "File and line the test is defined at.",
            "file_name": "File the test is defined in.",
            "labels": "Labels applied to the test, including 'flaky' for tests Buildkite detects as flaky.",
            "suite_id": "Identifier of the suite the test belongs to.",
            "suite_slug": "Slug of the suite the test belongs to.",
        },
    },
}
