from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

_DOCS_URL = "https://apps.babelforce.com/developer-hub/manager"

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "calls": {
        "description": "Call reporting records for every inbound and outbound call leg, including timing, state, and finish reason.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Unique identifier (UUID) of the call.",
            "parentId": "Identifier of the parent call when this call was created by another call (e.g. a transfer).",
            "sessionId": "Identifier of the IVR session the call belongs to.",
            "conversationId": "Identifier of the conversation the call belongs to.",
            "dateCreated": "When the call was created.",
            "lastUpdated": "When the call record was last updated.",
            "dateEstablished": "When the call was answered/established.",
            "dateFinished": "When the call finished.",
            "state": "Current state of the call (e.g. ringing, in-progress, bridged, completed, failed).",
            "finishReason": "Why the call ended (e.g. passive-hangup, timeout, busy, declined, transferred).",
            "type": "Direction of the call: inbound or outbound.",
            "from": "The calling phone number.",
            "to": "The called phone number.",
            "source": "The system component that created the call.",
            "domain": "The telephony domain the call was handled on.",
            "duration": "Total call duration in seconds.",
            "anonymous": "Whether the caller withheld their number.",
            "recordings": "Recordings captured during the call.",
            "bridged": "The agent or endpoint the call was bridged to.",
        },
    },
    "agents": {
        "description": "Contact center agents, including their line state, presence, and group membership.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Unique identifier (UUID) of the agent.",
            "sourceId": "The agent's identifier in an external system (e.g. a CRM or helpdesk).",
            "agentSource": "The external system the agent is synchronized from.",
            "name": "Display name of the agent.",
            "email": "Email address of the agent.",
            "number": "Phone number calls to this agent are delivered to.",
            "enabled": "Whether the agent is enabled.",
            "state": "Current line status of the agent (e.g. available, busy, in-call, wrap-up).",
            "presence": "The agent's presence information.",
            "status": "The agent's status information.",
            "activity": "The agent's current activity.",
            "available": "Whether the agent is currently available to take calls.",
            "tags": "Tags assigned to the agent.",
            "groups": "Agent groups the agent belongs to.",
            "webrtc": "Whether the agent uses WebRTC for calls.",
            "dateCreated": "When the agent was created.",
            "lastUpdated": "When the agent was last updated.",
        },
    },
    "agent_groups": {
        "description": "Groups used to organize agents for routing and reporting.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Unique identifier (UUID) of the agent group.",
            "name": "Name of the agent group.",
            "tags": "Tags assigned to the agent group.",
        },
    },
    "queues": {
        "description": "Call queues with their dialing and wrap-up configuration.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Unique identifier (UUID) of the queue.",
            "name": "Name of the queue.",
            "maxDialCount": "Maximum number of agents dialed in parallel.",
            "wrapUpTime": "Wrap-up time in seconds granted to agents after a call.",
            "defaultRingTimeout": "Default ring timeout in seconds.",
            "maxSize": "Maximum number of waiting calls the queue accepts.",
            "tags": "Tags assigned to the queue.",
        },
    },
    "numbers": {
        "description": "Service phone numbers configured on the account.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Unique identifier (UUID) of the service number.",
            "number": "The phone number.",
            "sms": "Whether the number supports SMS.",
            "enabled": "Whether the number is enabled.",
            "tags": "Tags assigned to the number.",
        },
    },
    "recordings": {
        "description": "Call recordings and their storage state.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Unique identifier (UUID) of the recording.",
            "dateCreated": "When the recording was created.",
            "lastUpdated": "When the recording was last updated.",
            "duration": "Recording duration in seconds.",
            "url": "URL to retrieve the recording.",
            "tags": "Tags assigned to the recording.",
            "file": "The stored file backing the recording.",
            "state": "Storage state of the recording (e.g. stored, failed, recording, missing, stopped).",
            "call": "The call the recording belongs to.",
            "agent": "The agent on the recorded call.",
        },
    },
    "sms": {
        "description": "Inbound and outbound SMS messages.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Unique identifier of the SMS message.",
            "dateCreated": "When the message was created.",
            "type": "Direction of the message: inbound or outbound.",
            "from": "The sending phone number.",
            "to": "The receiving phone number.",
            "state": "Delivery state of the message (e.g. queued, sent, received, failed).",
            "source": "The system component that created the message.",
            "text": "The message body.",
            "conversationId": "Identifier of the conversation the message belongs to.",
        },
    },
    "conversations": {
        "description": "Conversations grouping the calls and messages exchanged with a single phone number.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Unique identifier (UUID) of the conversation.",
            "dateCreated": "When the conversation was created.",
            "state": "Current state of the conversation.",
            "phone": "The customer phone number the conversation is with.",
        },
    },
}
