from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "surveys": {
        "description": "A survey in the environment, including its questions, triggers, and display settings.",
        "docs_url": "https://formbricks.com/docs/api-reference/management-api--survey/get-all-surveys",
        "columns": {
            "id": "Unique identifier of the survey.",
            "name": "Display name of the survey.",
            "type": "How the survey is delivered, e.g. link or app.",
            "status": "Lifecycle status of the survey, e.g. draft, inProgress, paused, or completed.",
            "questions": "Legacy question list, derived from blocks for backwards compatibility.",
            "blocks": "The survey's elements in the newer block structure.",
            "triggers": "Action classes that trigger the survey to be shown.",
            "displayOption": "How often the survey is displayed to the same person.",
            "recontactDays": "Number of days before the same person can be asked again.",
            "createdAt": "Timestamp when the survey was created.",
            "updatedAt": "Timestamp when the survey was last updated.",
        },
    },
    "responses": {
        "description": "A single response to a survey, including the submitted answers and respondent metadata.",
        "docs_url": "https://formbricks.com/docs/api-v2-reference/management-api--responses/get-responses",
        "columns": {
            "id": "Unique identifier of the response.",
            "surveyId": "Identifier of the survey the response belongs to.",
            "contactId": "Identifier of the contact who responded, if identified.",
            "finished": "Whether the respondent completed the survey.",
            "data": "Map of question identifier to the submitted answer.",
            "variables": "Survey variable values captured with the response.",
            "ttc": "Time-to-completion per question, in milliseconds.",
            "meta": "Respondent metadata such as browser, OS, and location.",
            "contactAttributes": "Attributes of the contact at the time of the response.",
            "language": "Language the survey was answered in.",
            "createdAt": "Timestamp when the response was created.",
            "updatedAt": "Timestamp when the response was last updated.",
        },
    },
    "contacts": {
        "description": "A contact (person) tracked in the environment, identified by an optional user id.",
        "docs_url": "https://formbricks.com/docs/api-reference/management-api--contacts/get-all-contacts",
        "columns": {
            "id": "Unique identifier of the contact.",
            "userId": "External user identifier assigned by your application, if any.",
            "createdAt": "Timestamp when the contact was created.",
            "updatedAt": "Timestamp when the contact was last updated.",
        },
    },
    "contact_attributes": {
        "description": "An attribute value set on a contact, linking a contact to an attribute key.",
        "docs_url": "https://formbricks.com/docs/api-reference/management-api--contact-attributes/get-all-contact-attributes",
        "columns": {
            "id": "Unique identifier of the contact attribute record.",
            "contactId": "Identifier of the contact the attribute belongs to.",
            "attributeKeyId": "Identifier of the attribute key this value is for.",
            "value": "The attribute value.",
            "createdAt": "Timestamp when the attribute was created.",
            "updatedAt": "Timestamp when the attribute was last updated.",
        },
    },
    "contact_attribute_keys": {
        "description": "An attribute key definition describing a piece of data that can be stored on contacts.",
        "docs_url": "https://formbricks.com/docs/api-v2-reference/management-api--contact-attribute-keys/get-contact-attribute-keys",
        "columns": {
            "id": "Unique identifier of the attribute key.",
            "key": "Machine name of the attribute, e.g. email.",
            "name": "Human-readable name of the attribute.",
            "description": "Description of what the attribute stores.",
            "type": "Whether the attribute is a default or custom key.",
            "isUnique": "Whether values for this key must be unique across contacts.",
            "createdAt": "Timestamp when the attribute key was created.",
            "updatedAt": "Timestamp when the attribute key was last updated.",
        },
    },
    "action_classes": {
        "description": "An action class (user action) that can trigger surveys, defined by code or no-code config.",
        "docs_url": "https://formbricks.com/docs/api-reference/management-api--action-class/get-all-action-classes",
        "columns": {
            "id": "Unique identifier of the action class.",
            "name": "Display name of the action, e.g. New Session.",
            "description": "Description of when the action fires.",
            "type": "How the action is tracked: automatic, code, or noCode.",
            "noCodeConfig": "Configuration for no-code actions, if any.",
            "createdAt": "Timestamp when the action class was created.",
            "updatedAt": "Timestamp when the action class was last updated.",
        },
    },
    "webhooks": {
        "description": "A webhook registered in the environment, fired when responses are created, updated, or finished.",
        "docs_url": "https://formbricks.com/docs/api-v2-reference/management-api--webhooks/get-webhooks",
        "columns": {
            "id": "Unique identifier of the webhook.",
            "name": "Display name of the webhook.",
            "url": "URL the webhook payload is delivered to.",
            "source": "What created the webhook: user, zapier, make, or n8n.",
            "triggers": "Response events that fire the webhook.",
            "surveyIds": "Surveys the webhook is limited to; empty means all surveys.",
            "createdAt": "Timestamp when the webhook was created.",
            "updatedAt": "Timestamp when the webhook was last updated.",
        },
    },
}
