from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "responses": {
        "description": "Individual survey responses (NPS, CSAT, or 5-star) with the score, comment, and contact details for each respondent.",
        "docs_url": "https://asknicely.asknice.ly/help/apidocs/responses",
        "columns": {
            "response_id": "Unique identifier for the response.",
            "person_id": "Identifier of the person (contact) the survey was sent to.",
            "contact_id": "Identifier of the contact record in AskNicely.",
            "name": "Name of the respondent.",
            "email": "Email address of the respondent.",
            "answer": "The score the respondent gave (e.g. 0-10 for NPS).",
            "answerlabel": "Label associated with the answer, where the survey uses labelled options.",
            "comment": "Free-text comment left by the respondent.",
            "note": "Internal notes attached to the response.",
            "status": "Delivery/response status of the survey (e.g. answered).",
            "dontcontact": "Whether the contact has opted out of further surveys.",
            "sent": "Unix timestamp when the survey was sent.",
            "opened": "Unix timestamp when the survey was opened, or 0 if never opened.",
            "responded": "Unix timestamp when the respondent answered the survey.",
            "lastemailed": "Unix timestamp when the contact was last emailed.",
            "created": "Unix timestamp when the contact record was created.",
            "segment": "Segment the contact belongs to.",
            "question_type": "Survey metric type for this response: nps, csat, or 5star.",
            "published": "Whether the response has been approved for publishing as a testimonial.",
            "publishedname": "Display name used when the response is published as a testimonial.",
            "deliverymethod": "Channel the survey was delivered through (e.g. email).",
        },
    },
    "stats": {
        "description": "Daily survey statistics: one row per calendar day with send, delivery, open and response counts alongside the NPS, CSAT and 5-star scores for that day.",
        "docs_url": "https://asknicely.asknice.ly/help/apidocs/stats",
        "columns": {
            "year": "Year of the day the row covers.",
            "month": "Month of the day the row covers, not zero-padded.",
            "day": "Day of the month the row covers, not zero-padded.",
            "weekday": "Abbreviated weekday name for the day the row covers (e.g. Thu).",
            "sent": "Number of surveys sent that day.",
            "delivered": "Number of sent surveys that were delivered.",
            "opened": "Number of delivered surveys that were opened.",
            "responded": "Number of surveys that were answered.",
            "promoters": "Number of NPS responses scoring 9 or 10.",
            "passives": "Number of NPS responses scoring 7 or 8.",
            "detractors": "Number of NPS responses scoring 0 to 6.",
            "nps": "Net Promoter Score for the day, null when there were no NPS responses.",
            "fivestar": "Average 5-star rating for the day, null when there were no 5-star responses.",
            "csat": "CSAT score for the day, null when there were no CSAT responses.",
            "comment_length": "Average length of the comments left that day.",
            "comment_responded_percent": "Percentage of respondents who also left a comment.",
            "surveys_responded_percent": "Percentage of sent surveys that were answered.",
            "surveys_opened_responded_percent": "Percentage of opened surveys that were answered.",
        },
    },
    "contacts_unsubscribed": {
        "description": "Contacts who opted out through the unsubscribe link in a survey email. Use it to suppress them from send and response analysis.",
        "docs_url": "https://asknicely.asknice.ly/help/apidocs/getunsubscribed",
        "columns": {
            "id": "Identifier of the contact who unsubscribed. Matches contact_id on the responses table.",
            "unsubscribetime": "Unix timestamp when the contact unsubscribed.",
            "email": "Email address of the contact who unsubscribed.",
        },
    },
}
