# Descriptions sourced from the official Heroku Platform API v3 reference
# (https://devcenter.heroku.com/articles/platform-api-reference).
from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "apps": {
        "description": "An app represents the program that you would like to deploy and run on Heroku.",
        "docs_url": "https://devcenter.heroku.com/articles/platform-api-reference#app",
        "columns": {
            "acm": "ACM status of this app.",
            "archived_at": "When the app was archived.",
            "build_stack": "Identity of the stack that will be used for new builds.",
            "buildpack_provided_description": "Description from buildpack of app.",
            "created_at": "When the app was created.",
            "generation": "Generation of the Heroku platform for this app.",
            "git_url": "Git repo URL of app.",
            "id": "Unique identifier of app.",
            "internal_routing": "Describes whether a Private Spaces app is externally routable or not.",
            "maintenance": "Maintenance status of app.",
            "name": "Unique name of app.",
            "organization": "Identity of team.",
            "owner": "Identity of app owner.",
            "region": "Identity of app region.",
            "released_at": "When the app was released.",
            "repo_size": "Git repo size in bytes of app.",
            "slug_size": "Slug size in bytes of app.",
            "space": "Identity of space.",
            "stack": "Identity of app stack.",
            "team": "Identity of team.",
            "updated_at": "When the app was updated.",
            "web_url": "Web URL of app.",
        },
    },
    "addons": {
        "description": "Add-ons represent add-ons that have been provisioned and attached to one or more apps.",
        "docs_url": "https://devcenter.heroku.com/articles/platform-api-reference#add-on",
        "columns": {
            "actions": "Provider actions for this specific add-on.",
            "addon_service": "Identity of add-on service.",
            "app": "Billing application associated with this add-on.",
            "billed_price": "Billed price.",
            "billing_entity": "Billing entity associated with this add-on.",
            "config_vars": "Config vars exposed to the owning app by this add-on.",
            "created_at": "When the add-on was created.",
            "id": "Unique identifier of add-on.",
            "name": "Globally unique name of the add-on.",
            "plan": "Identity of add-on plan.",
            "provider_id": "Id of this add-on with its provider.",
            "state": "State in the add-on's lifecycle.",
            "updated_at": "When the add-on was updated.",
            "web_url": "URL for logging into web interface of add-on (e.g. a dashboard).",
        },
    },
    "builds": {
        "description": "A build represents the process of transforming a code tarball into build artifacts.",
        "docs_url": "https://devcenter.heroku.com/articles/platform-api-reference#build",
        "columns": {
            "app": "App that the build belongs to.",
            "buildpacks": "Buildpacks executed for this build, in order.",
            "created_at": "When the build was created.",
            "generation": "Generation of build.",
            "id": "Unique identifier of build.",
            "output_stream_url": "URL from which the build process output is available as a stream.",
            "release": "Release resulting from the build.",
            "slug": "Slug created by this build (only applicable for Cedar-generation apps).",
            "source_blob": "Location of gzipped tarball of source code used to create build.",
            "stack": "Stack of build.",
            "status": "Status of build.",
            "updated_at": "When the build was updated.",
            "user": "User that started the build.",
        },
    },
    "collaborators": {
        "description": "A collaborator represents an account that has been given access to an app on Heroku.",
        "docs_url": "https://devcenter.heroku.com/articles/platform-api-reference#collaborator",
        "columns": {
            "app": "App the collaborator belongs to.",
            "created_at": "When the collaborator was created.",
            "id": "Unique identifier of collaborator.",
            "permissions": "Permissions the collaborator has on the app.",
            "role": "Role in the team.",
            "updated_at": "When the collaborator was updated.",
            "user": "Identity of collaborated account.",
        },
    },
    "domains": {
        "description": "Domains define what web routes should be routed to an app on Heroku.",
        "docs_url": "https://devcenter.heroku.com/articles/platform-api-reference#domain",
        "columns": {
            "acm_status": "Status of this record's ACM.",
            "acm_status_reason": "Reason for the status of this record's ACM.",
            "app": "App that owns the domain.",
            "cname": "Canonical name record, the address to point a domain at.",
            "created_at": "When the domain was created.",
            "hostname": "Full hostname.",
            "id": "Unique identifier of this domain.",
            "kind": "Type of domain name.",
            "sni_endpoint": "SNI endpoint the domain is associated with.",
            "status": "Status of this record's cname.",
            "updated_at": "When the domain was updated.",
        },
    },
    "dynos": {
        "description": "Dynos encapsulate running processes of an app on Heroku.",
        "docs_url": "https://devcenter.heroku.com/articles/platform-api-reference#dyno",
        "columns": {
            "app": "App the dyno belongs to.",
            "attach_url": "A URL to stream output from for attached processes, or null for non-attached processes.",
            "command": "Command used to start this process.",
            "created_at": "When the dyno was created.",
            "id": "Unique identifier of this dyno.",
            "name": "The name of this process on this dyno.",
            "release": "App release of the dyno.",
            "size": "Dyno size.",
            "state": "Current status of process (either: crashed, down, idle, starting, or up).",
            "type": "Type of process.",
            "updated_at": "When the process last changed state.",
        },
    },
    "formation": {
        "description": "The formation of processes that should be maintained for an app — the process types, dyno sizes, and quantities the app is scaled to.",
        "docs_url": "https://devcenter.heroku.com/articles/platform-api-reference#formation",
        "columns": {
            "app": "App the formation belongs to.",
            "command": "Command to use to launch this process.",
            "created_at": "When the process type was created.",
            "dyno_size": "Dyno size.",
            "id": "Unique identifier of this process type.",
            "quantity": "Number of processes to maintain.",
            "size": "Deprecated, refer to 'dyno_size' instead.",
            "type": "Type of process to maintain.",
            "updated_at": "When the dyno type was updated.",
        },
    },
    "invoices": {
        "description": "An invoice is an itemized bill of goods for an account which includes pricing and charges.",
        "docs_url": "https://devcenter.heroku.com/articles/platform-api-reference#invoice",
        "columns": {
            "charges_total": "Total charges on this invoice.",
            "created_at": "When the invoice was created.",
            "credits_total": "Total credits on this invoice.",
            "id": "Unique identifier of this invoice.",
            "number": "Human readable invoice number.",
            "period_end": "The ending date that the invoice covers.",
            "period_start": "The starting date that this invoice covers.",
            "state": "Payment status for this invoice (pending, successful, failed).",
            "total": "Combined total of charges and credits on this invoice.",
            "updated_at": "When the invoice was updated.",
        },
    },
    "pipelines": {
        "description": "A pipeline allows grouping of apps into different stages.",
        "docs_url": "https://devcenter.heroku.com/articles/platform-api-reference#pipeline",
        "columns": {
            "created_at": "When the pipeline was created.",
            "generation": "The generation of the Heroku platform for this pipeline.",
            "id": "Unique identifier of pipeline.",
            "name": "Name of pipeline.",
            "owner": "Owner of a pipeline.",
            "updated_at": "When the pipeline was updated.",
        },
    },
    "releases": {
        "description": "A release represents a combination of code, config vars and add-ons for an app on Heroku.",
        "docs_url": "https://devcenter.heroku.com/articles/platform-api-reference#release",
        "columns": {
            "addon_plan_names": "Add-on plans installed on the app for this release.",
            "app": "App involved in the release.",
            "artifacts": "Build artifacts for the release.",
            "created_at": "When the release was created.",
            "current": "Indicates this release as being the current one for the app.",
            "description": "Description of changes in this release.",
            "eligible_for_rollback": "Indicates if this release is eligible for rollback.",
            "id": "Unique identifier of release.",
            "output_stream_url": "URL from which the release command output is available as a stream.",
            "slug": "Slug running in this release.",
            "status": "Current status of the release.",
            "updated_at": "When the release was updated.",
            "user": "User that created the release.",
            "version": "Unique version assigned to the release.",
        },
    },
    "teams": {
        "description": "Teams allow you to manage access to a shared group of applications and other resources.",
        "docs_url": "https://devcenter.heroku.com/articles/platform-api-reference#team",
        "columns": {
            "created_at": "When the team was created.",
            "credit_card_collections": "Whether charges incurred by the team are paid by credit card.",
            "default": "Whether to use this team when none is specified.",
            "enterprise_account": "Enterprise account associated with the team.",
            "id": "Unique identifier of team.",
            "identity_provider": "Identity provider associated with the team.",
            "membership_limit": "Upper limit of members allowed in a team.",
            "name": "Unique name of team.",
            "provisioned_licenses": "Whether the team is provisioned licenses by Salesforce.",
            "role": "Role in the team.",
            "type": "Type of team.",
            "updated_at": "When the team was updated.",
        },
    },
}
