import { MakeLogicType, connect, events, kea, key, listeners, path, props } from 'kea'
import { loaders } from 'kea-loaders'

import api from 'lib/api'
import { ErrorTrackingFingerprint } from 'lib/components/Errors/types'

import { ErrorTrackingRelationalIssue } from '~/queries/schema/schema-general'

import { errorTrackingIssueFingerprintsQuery } from '../../queries'
import { errorTrackingIssueSceneLogic } from '../../scenes/ErrorTrackingIssueScene/errorTrackingIssueSceneLogic'

export interface FingerprintSamplesLogicProps {
    issueId: string
}

export interface FingerprintSample {
    type: string
    value: string
    lib?: string
}

export type FingerprintSampleMap = Record<string, FingerprintSample>

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface fingerprintSamplesLogicValues {
    issue: ErrorTrackingRelationalIssue | null // errorTrackingIssueSceneLogic
    issueFingerprints: ErrorTrackingFingerprint[] // errorTrackingIssueSceneLogic
    samples: FingerprintSampleMap
    samplesLoading: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface fingerprintSamplesLogicActions {
    loadIssueFingerprintsSuccess: (
        issueFingerprints: ErrorTrackingFingerprint[],
        payload?: any
    ) => {
        issueFingerprints: ErrorTrackingFingerprint[]
        payload?: any
    } // errorTrackingIssueSceneLogic
    loadSamples: (_: void) => void
    loadSamplesFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadSamplesSuccess: (
        samples: FingerprintSampleMap,
        payload?: void
    ) => {
        samples: FingerprintSampleMap
        payload?: void
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface fingerprintSamplesLogicMeta {
    key: string
}

export type fingerprintSamplesLogicType = MakeLogicType<
    fingerprintSamplesLogicValues,
    fingerprintSamplesLogicActions,
    FingerprintSamplesLogicProps,
    fingerprintSamplesLogicMeta
>

export const fingerprintSamplesLogic = kea<fingerprintSamplesLogicType>([
    path((key) => ['products', 'error_tracking', 'components', 'FingerprintPreview', 'fingerprintSamplesLogic', key]),
    props({} as FingerprintSamplesLogicProps),
    key(({ issueId }) => issueId),

    connect((props: FingerprintSamplesLogicProps) => ({
        values: [errorTrackingIssueSceneLogic({ id: props.issueId }), ['issue', 'issueFingerprints']],
        actions: [errorTrackingIssueSceneLogic({ id: props.issueId }), ['loadIssueFingerprintsSuccess']],
    })),

    loaders(({ values }) => ({
        samples: [
            {} as FingerprintSampleMap,
            {
                loadSamples: async (_: void, breakpoint) => {
                    const { issue, issueFingerprints } = values
                    if (!issue || issueFingerprints.length === 0) {
                        return {}
                    }
                    const response = await api.queryHogQL(
                        errorTrackingIssueFingerprintsQuery(
                            issue.id,
                            issue.first_seen,
                            issueFingerprints.map(({ fingerprint }) => fingerprint)
                        ),
                        { scene: 'ErrorTrackingFingerprintPreview', productKey: 'error_tracking' }
                    )
                    breakpoint()
                    const samples: FingerprintSampleMap = {}
                    for (const [fingerprint, , fingerprintSamples] of response.results as [
                        string,
                        number,
                        FingerprintSample[],
                    ][]) {
                        const sample = fingerprintSamples?.[0]
                        if (sample?.type || sample?.value) {
                            samples[fingerprint] = sample
                        }
                    }
                    return samples
                },
            },
        ],
    })),

    listeners(({ actions }) => ({
        loadIssueFingerprintsSuccess: () => actions.loadSamples(),
    })),

    events(({ actions, values }) => ({
        // The tab usually opens after the scene already loaded its fingerprints, so the success
        // listener above has nothing left to fire on.
        afterMount: () => {
            if (values.issueFingerprints.length > 0) {
                actions.loadSamples()
            }
        },
    })),
])
