from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Doc-sourced descriptions for Jotform's well-known tables. See https://api.jotform.com/docs/.
# Partial coverage is fine — any missing endpoint/column falls back to LLM enrichment.
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "forms": {
        "description": "One row per form on the account, with its title, status, and submission counts.",
        "docs_url": "https://api.jotform.com/docs/#user-forms",
        "columns": {
            "id": "Unique identifier of the form.",
            "username": "Username of the account that owns the form.",
            "title": "Display title of the form.",
            "height": "Configured form height in pixels.",
            "url": "Public URL of the form.",
            "status": "Form status (e.g. ENABLED, DISABLED, DELETED).",
            "created_at": "Timestamp the form was created.",
            "updated_at": "Timestamp the form was last updated.",
            "last_submission": "Timestamp of the most recent submission to the form.",
            "new": "Number of unread submissions.",
            "count": "Total number of submissions to the form.",
            "type": "Form type (e.g. LEGACY, CARD).",
            "favorite": "Whether the form is marked as a favorite.",
            "archived": "Whether the form is archived.",
        },
    },
    "submissions": {
        "description": "One row per submission across all of the account's forms, including answers.",
        "docs_url": "https://api.jotform.com/docs/#user-submissions",
        "columns": {
            "id": "Unique identifier of the submission.",
            "form_id": "Identifier of the form the submission belongs to.",
            "ip": "IP address the submission was made from.",
            "created_at": "Timestamp the submission was created.",
            "updated_at": "Timestamp the submission was last updated.",
            "status": "Submission status (e.g. ACTIVE, OVERQUOTA).",
            "new": "Whether the submission is unread.",
            "flag": "Whether the submission is flagged.",
            "notes": "Free-text notes attached to the submission.",
            "answers": "Object of the submitted answers keyed by question id.",
        },
    },
    "reports": {
        "description": "One row per report (e.g. grid, table, or visual report) created on the account.",
        "docs_url": "https://api.jotform.com/docs/#user-reports",
        "columns": {
            "id": "Unique identifier of the report.",
            "form_id": "Identifier of the form the report is built from.",
            "title": "Display title of the report.",
            "type": "Report type (e.g. excel, csv, grid, table).",
            "status": "Report status.",
            "url": "Public URL of the report.",
            "created_at": "Timestamp the report was created.",
            "updated_at": "Timestamp the report was last updated.",
        },
    },
    "questions": {
        "description": "One row per question (field) of a form. `qid` is unique only within a form, so each row also carries `form_id`.",
        "docs_url": "https://api.jotform.com/docs/#form-id-questions",
        "columns": {
            "form_id": "Identifier of the form the question belongs to.",
            "qid": "Question identifier, unique within its form.",
            "type": "Question/control type (e.g. control_textbox, control_email).",
            "text": "Label shown to respondents for the question.",
            "name": "Internal field name of the question.",
            "order": "Display order of the question within the form.",
        },
    },
    "usage": {
        "description": "Single-row snapshot of the account's usage for the current month. Each sync replaces the row.",
        "docs_url": "https://api.jotform.com/docs/#user-usage",
        "columns": {
            "submissions": "Number of submissions received this month.",
            "ssl_submissions": "Number of secure (SSL) submissions received this month.",
            "payments": "Number of payment submissions received this month.",
            "uploads": "Total disk space used by uploaded files, in bytes.",
            "mobile_submissions": "Number of mobile submissions received this month.",
            "views": "Number of form views received this month.",
            "api": "Number of API calls used today.",
        },
    },
    "history": {
        "description": "Account activity log: account creation, logins, and form creation, update, delete and purge events.",
        "docs_url": "https://api.jotform.com/docs/#user-history",
        "columns": {
            "type": "Activity type (userCreation, userLogin, formCreation, formUpdate, formDelete or formPurge).",
            "formID": "Identifier of the form the activity applies to, for form activities.",
            "username": "Username of the account that performed the activity.",
            "formTitle": "Title of the form at the time of the activity.",
            "formStatus": "Status of the form at the time of the activity.",
            "ip": "IP address the activity came from.",
            "timestamp": "Time of the activity, in seconds since the Unix epoch.",
        },
    },
    "labels": {
        "description": "One row per label (tag) on the account. Labels form a tree: each row links to its parent through `parent_label_id`.",
        "docs_url": "https://api.jotform.com/docs/#get-user-labels",
        "columns": {
            "id": "Unique identifier of the label.",
            "name": "Display name of the label.",
            "color": "Label color as a hex code.",
            "order": "Display order of the label among its siblings.",
            "parent_label_id": "Identifier of the parent label. Empty for the account's root label.",
            "owner": "Username of the account that owns the label.",
            "owner_type": "Type of the owner of the root label (e.g. USER).",
            "created_at": "Timestamp the label was created.",
            "updated_at": "Timestamp the label was last updated.",
        },
    },
    "label_resources": {
        "description": "One row per asset (form, workflow, sheet or app) tagged with a label. The same asset appears once for each label it carries.",
        "docs_url": "https://api.jotform.com/docs/#get-label-id-resources",
        "columns": {
            "label_id": "Identifier of the label the asset is tagged with.",
            "id": "Identifier of the asset, unique within its asset type.",
            "assetType": "Asset type (e.g. form, workflow, sheet, portal).",
            "title": "Display title of the asset.",
            "status": "Asset status (e.g. ENABLED, DISABLED).",
            "created_at": "Timestamp the asset was created.",
            "updated_at": "Timestamp the asset was last updated.",
        },
    },
}
