import { MakeLogicType, actions, connect, kea, key, listeners, path, props, reducers, selectors } from 'kea'
import { actionToUrl, router, urlToAction } from 'kea-router'
import posthog from 'posthog-js'

import { ApiError } from 'lib/api'
import { featureFlagLogic, FeatureFlagsSet } from 'lib/logic/featureFlagLogic'
import { Scene } from 'scenes/sceneTypes'
import { teamLogic } from 'scenes/teamLogic'
import { urls } from 'scenes/urls'

import { Breadcrumb } from '~/types'

import {
    AccountExpansionTab,
    DEFAULT_ACCOUNT_TAB,
    getVisibleAccountExpansionTab,
} from 'products/customer_analytics/frontend/components/Accounts/accountsExpansionLogic'
import { AccountsEvents } from 'products/customer_analytics/frontend/components/Accounts/constants'
import { accountsRetrieve } from 'products/customer_analytics/frontend/generated/api'
import type { AccountApi } from 'products/customer_analytics/frontend/generated/api.schemas'

export interface CustomerAnalyticsAccountSceneLogicProps {
    accountId: string
}

function isAccountNotFound(error: unknown): boolean {
    return error instanceof ApiError && error.status === 404
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface customerAnalyticsAccountSceneLogicValues {
    featureFlags: FeatureFlagsSet // featureFlagLogic
    currentTeamId: number | null // teamLogic
    account: AccountApi | null
    accountLoadError: unknown
    accountLoading: boolean
    activeTab: AccountExpansionTab
    breadcrumbs: Breadcrumb[]
    isAccountMissing: boolean
    requestedTab: string
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface customerAnalyticsAccountSceneLogicActions {
    loadAccount: () => {
        value: true
    }
    loadAccountFailure: (error: unknown) => {
        error: unknown
    }
    loadAccountSuccess: (account: AccountApi) => {
        account: AccountApi
    }
    restoreActiveTab: (tab: string | undefined) => {
        tab: string
    }
    setActiveTab: (tab: AccountExpansionTab) => {
        tab: AccountExpansionTab
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface customerAnalyticsAccountSceneLogicMeta {
    key: string
    __keaTypeGenInternalSelectorTypes: {
        activeTab: (requestedTab: string, featureFlags: FeatureFlagsSet) => AccountExpansionTab
        isAccountMissing: (account: AccountApi | null, accountLoading: boolean, accountLoadError: unknown) => boolean
        breadcrumbs: (account: AccountApi | null) => Breadcrumb[]
    }
}

export type customerAnalyticsAccountSceneLogicType = MakeLogicType<
    customerAnalyticsAccountSceneLogicValues,
    customerAnalyticsAccountSceneLogicActions,
    CustomerAnalyticsAccountSceneLogicProps,
    customerAnalyticsAccountSceneLogicMeta
>

export const customerAnalyticsAccountSceneLogic = kea<customerAnalyticsAccountSceneLogicType>([
    path((key) => [
        'products',
        'customer_analytics',
        'frontend',
        'scenes',
        'CustomerAnalyticsAccountScene',
        'customerAnalyticsAccountSceneLogic',
        key,
    ]),
    props({} as CustomerAnalyticsAccountSceneLogicProps),
    key((props) => props.accountId),
    connect(() => ({
        values: [teamLogic, ['currentTeamId'], featureFlagLogic, ['featureFlags']],
    })),
    actions({
        loadAccount: true,
        loadAccountSuccess: (account: AccountApi) => ({ account }),
        loadAccountFailure: (error: unknown) => ({ error }),
        setActiveTab: (tab: AccountExpansionTab) => ({ tab }),
        restoreActiveTab: (tab: string | undefined) => ({ tab: tab ?? DEFAULT_ACCOUNT_TAB }),
    }),
    reducers({
        account: [
            null as AccountApi | null,
            {
                loadAccountSuccess: (_, { account }) => account,
            },
        ],
        accountLoading: [
            false,
            {
                loadAccount: () => true,
                loadAccountSuccess: () => false,
                loadAccountFailure: () => false,
            },
        ],
        accountLoadError: [
            null as unknown,
            {
                loadAccount: () => null,
                loadAccountSuccess: () => null,
                loadAccountFailure: (_, { error }) => error,
            },
        ],
        requestedTab: [
            DEFAULT_ACCOUNT_TAB as string,
            {
                setActiveTab: (_, { tab }) => tab,
                restoreActiveTab: (_, { tab }) => tab,
            },
        ],
    }),
    selectors({
        activeTab: [
            (s) => [s.requestedTab, s.featureFlags],
            (requestedTab: string, featureFlags: FeatureFlagsSet): AccountExpansionTab =>
                getVisibleAccountExpansionTab(requestedTab, featureFlags),
        ],
        isAccountMissing: [
            (s) => [s.account, s.accountLoading, s.accountLoadError],
            (account: AccountApi | null, accountLoading: boolean, accountLoadError: unknown): boolean =>
                !account && !accountLoading && isAccountNotFound(accountLoadError),
        ],
        breadcrumbs: [
            (s) => [s.account],
            (account: AccountApi | null): Breadcrumb[] => [
                {
                    key: Scene.CustomerAnalytics,
                    name: 'Accounts',
                    path: urls.customerAnalyticsAccounts(),
                    iconType: 'cohort',
                },
                {
                    key: Scene.CustomerAnalyticsAccount,
                    name: account?.name ?? 'Account',
                    iconType: 'cohort',
                },
            ],
        ],
    }),
    listeners(({ actions, props, values }) => ({
        loadAccount: async () => {
            try {
                actions.loadAccountSuccess(await accountsRetrieve(String(values.currentTeamId), props.accountId))
            } catch (error) {
                actions.loadAccountFailure(error)
            }
        },
        loadAccountFailure: ({ error }) => {
            if (isAccountNotFound(error)) {
                return
            }
            posthog.captureException(error instanceof Error ? error : new Error('Could not load account'), {
                scope: 'customerAnalyticsAccountSceneLogic.loadAccount',
            })
        },
        setActiveTab: ({ tab }) => {
            posthog.capture(AccountsEvents.TabViewed, { tab })
        },
    })),
    actionToUrl(({ props }) => ({
        setActiveTab: ({ tab }) => [
            urls.customerAnalyticsAccount(props.accountId, tab === DEFAULT_ACCOUNT_TAB ? undefined : tab),
            router.values.currentLocation.searchParams,
            router.values.currentLocation.hashParams,
        ],
    })),
    urlToAction(({ actions, props }) => ({
        [`${urls.customerAnalyticsAccount(props.accountId)}/:tab`]: ({ tab }) => {
            actions.restoreActiveTab(tab)
        },
        [urls.customerAnalyticsAccount(props.accountId)]: () => {
            actions.restoreActiveTab(DEFAULT_ACCOUNT_TAB)
        },
    })),
])
