"""Canonical, documentation-sourced descriptions for Cortex endpoints and columns.

Sourced from the official Cortex API reference (https://docs.cortex.io/api). Keyed by the
resource names in `settings.py` `ENDPOINTS`, which match the `ExternalDataSchema.name` of a
synced Cortex table. Columns absent here fall back to LLM enrichment.
"""

from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "entities": {
        "description": "A catalog entity (service, resource, or domain) tracked in Cortex.",
        "docs_url": "https://docs.cortex.io/api/readme/catalog-entities",
        "columns": {
            "id": "18-character unique identifier (CID) for the entity.",
            "tag": "Human-readable unique identifier (x-cortex-tag) for the entity.",
            "name": "Display name of the entity.",
            "type": "Entity type: service, resource, or domain (or a custom entity type).",
            "description": "Optional markdown description of the entity.",
            "isArchived": "Whether the entity has been archived.",
            "lastUpdated": "Timestamp the entity was last updated in Cortex.",
            "groups": "List of x-cortex-groups values assigned to the entity.",
            "hierarchy": "Parent and child entities in the ownership hierarchy.",
            "links": "Links attached to the entity (documentation, dashboards, etc.).",
            "slackChannels": "Slack channels associated with the entity.",
            "owners": "Individuals and teams that own the entity.",
            "git": "Linked git repository details, when configured.",
            "metadata": "Custom metadata key/value pairs defined on the entity.",
        },
    },
    "scorecards": {
        "description": "A Cortex scorecard: a set of rules used to grade catalog entities against a standard.",
        "docs_url": "https://docs.cortex.io/api/readme/scorecards",
        "columns": {
            "tag": "Unique identifier (tag) for the scorecard.",
            "name": "Display name of the scorecard.",
            "description": "Description of what the scorecard measures.",
            "dateCreated": "Timestamp the scorecard was created.",
            "lastUpdated": "Timestamp the scorecard was last updated.",
            "isDraft": "Whether the scorecard is still a draft (not yet evaluating entities).",
            "rules": "The rule expressions the scorecard evaluates.",
            "levels": "Ladder levels an entity can achieve based on its rule scores.",
            "notifications": "Notification settings for the scorecard.",
            "exemptions": "Rule exemption settings for the scorecard.",
            "evaluation": "Evaluation settings, such as the scoring window.",
        },
    },
    "scorecard_scores": {
        "description": "A single entity's score against a scorecard, one row per scorecard/entity pair.",
        "docs_url": "https://docs.cortex.io/api/readme/scorecards",
        "columns": {
            "scorecard_tag": "Tag of the scorecard this score belongs to.",
            "service": "The scored entity's identifying fields (tag, id, name, groups, owners).",
            "service_tag": "Tag of the scored entity.",
            "service_id": "CID of the scored entity.",
            "service_name": "Display name of the scored entity.",
            "score": "The score summary, rule-by-rule breakdown, and ladder level achieved.",
            "lastEvaluated": "Timestamp the score was last evaluated.",
            "ruleExemptions": "Rule exemptions requested or granted for this entity on this scorecard.",
        },
    },
    "initiatives": {
        "description": "A Cortex Initiative: a time-boxed campaign to bring entities up to part of a scorecard, with the rules or ladder levels it emphasizes.",
        "docs_url": "https://docs.cortex.io/api/readme/initiatives",
        "columns": {
            "cid": "18-character unique identifier for the Initiative.",
            "name": "Name of the Initiative.",
            "description": "Optional description of the Initiative.",
            "scorecardTag": "Tag of the scorecard the Initiative drives entities against.",
            "scorecardName": "Display name of that scorecard.",
            "targetDate": "Date the Initiative is meant to be completed by.",
            "isDraft": "Whether the Initiative is still a draft and not yet notifying anyone.",
            "emphasizedRules": "Scorecard rules the Initiative asks entities to pass.",
            "emphasizedLevels": "Scorecard ladder levels the Initiative asks entities to reach.",
            "filter": "Entity types, groups, and CQL query limiting which entities are in scope.",
            "notificationSchedule": "Reminder cadence and reply-to addresses for the Initiative.",
            "dateCreated": "Timestamp the Initiative was created.",
            "dateUpdated": "Timestamp the Initiative was last updated.",
        },
    },
    "entity_types": {
        "description": "A custom entity type (definition) available in the Cortex catalog, beyond the built-in service/domain/team types.",
        "docs_url": "https://docs.cortex.io/api/readme/entity-types",
        "columns": {
            "type": "Unique identifier for the entity type.",
            "name": "Display name of the entity type.",
            "description": "Description of the entity type.",
            "schema": "JSON schema describing the entity type's custom fields.",
            "source": "Whether the type is a built-in Cortex type or a custom one.",
            "iconTag": "Icon tag shown for entities of this type in the Cortex UI.",
        },
    },
    "teams": {
        "description": "A team in Cortex, either managed directly in Cortex or backed by an identity provider group.",
        "docs_url": "https://docs.cortex.io/api/readme/teams",
        "columns": {
            "id": "Unique identifier for the team.",
            "teamTag": "Human-readable unique identifier for the team.",
            "catalogEntityTag": "Tag of the catalog entity (of type team) associated with this team.",
            "type": "Whether the team is Cortex-managed (CORTEX) or identity-provider-backed (IDP).",
            "isArchived": "Whether the team has been archived.",
            "metadata": "Team name, description, and summary.",
            "links": "Links attached to the team.",
            "slackChannels": "Slack channels associated with the team.",
            "cortexTeam": "Member list, present for Cortex-managed teams.",
            "idpGroup": "Backing identity-provider group and its members, present for IDP-backed teams.",
        },
    },
    "team_hierarchies": {
        "description": "A parent/child edge between two teams, one row per edge in the team hierarchy.",
        "docs_url": "https://docs.cortex.io/api/readme/team-hierarchies",
        "columns": {
            "parentTeamTag": "Tag of the parent team in the edge.",
            "childTeamTag": "Tag of the child team in the edge.",
            "provider": "Identity provider that supplied the edge, when it was imported rather than set in Cortex.",
        },
    },
    "relationship_types": {
        "description": "A type of relationship (e.g. 'depends-on') that can connect two catalog entities.",
        "docs_url": "https://docs.cortex.io/api/readme/entity-relationship-types",
        "columns": {
            "tag": "Unique identifier for the relationship type.",
            "name": "Display name of the relationship type.",
            "description": "Description of what the relationship type represents.",
            "allowCycles": "Whether cyclical relationships of this type are allowed.",
            "definitionLocation": "Whether the relationship can be defined from the source, destination, or both.",
            "isSingleSource": "Whether a destination entity can have only one source of this type.",
            "isSingleDestination": "Whether a source entity can have only one destination of this type.",
            "isCortexManaged": "Whether this is a built-in Cortex-managed relationship type.",
            "sourcesFilter": "Restrictions on which entity types/providers can be a source of this relationship.",
            "destinationsFilter": "Restrictions on which entity types/providers can be a destination of this relationship.",
            "sourceLabelSingular": "Singular display label for a source entity of this relationship.",
            "sourceLabelPlural": "Plural display label for source entities of this relationship.",
            "destinationLabelSingular": "Singular display label for a destination entity of this relationship.",
            "destinationLabelPlural": "Plural display label for destination entities of this relationship.",
        },
    },
    "users": {
        "description": "A user in the Cortex workspace, with the profile metadata used for access reviews and for resolving entity owners.",
        "docs_url": "https://docs.cortex.io/api/readme/users",
        "columns": {
            "email": "Email address of the user.",
            "name": "Display name of the user.",
            "joinedAt": "Timestamp the user was first added to Cortex.",
            "lastActiveAt": "Timestamp the user last logged in; null if they never have.",
        },
    },
    "custom_events": {
        "description": "A custom event recorded against a catalog entity, such as an incident, a migration, or a release.",
        "docs_url": "https://docs.cortex.io/api/readme/custom-events",
        "columns": {
            "entity_tag": "Tag of the entity the event was recorded against.",
            "entity_id": "CID of the entity the event was recorded against.",
            "uuid": "Automatically generated identifier for the event.",
            "type": "Type of the custom event.",
            "title": "Name of the custom event.",
            "description": "Optional description of the custom event.",
            "timestamp": "Time the event occurred.",
            "url": "Optional URL associated with the event.",
            "customData": "Optional key/value data stored alongside the event.",
        },
    },
    "deploys": {
        "description": "A deployment event recorded against a catalog entity, the grain behind deploy frequency and lead time.",
        "docs_url": "https://docs.cortex.io/api/readme/deploys",
        "columns": {
            "entity_tag": "Tag of the entity that was deployed.",
            "entity_id": "CID of the entity that was deployed.",
            "uuid": "Automatically generated identifier for the deploy.",
            "type": "Kind of deploy event: DEPLOY, SCALE, ROLLBACK, or RESTART.",
            "title": "Human readable title for the deploy, usually the commit message or pull request title.",
            "timestamp": "Time the deploy happened, as a UTC ISO-8601 instant.",
            "environment": "Environment the deploy went out to.",
            "sha": "Commit SHA the deploy corresponds to, when supplied.",
            "deployer": "Name and email of whoever ran the deploy.",
            "url": "Optional URL associated with the deploy.",
            "customData": "Arbitrary key/value data stored alongside the deploy.",
        },
    },
    "dependencies": {
        "description": "A dependency edge from one catalog entity to another, optionally scoped to a single endpoint of the callee.",
        "docs_url": "https://docs.cortex.io/api/readme/dependencies",
        "columns": {
            "caller_entity_id": "CID of the calling entity.",
            "callerTag": "Tag of the calling entity.",
            "callerType": "Entity type of the caller.",
            "calleeTag": "Tag of the entity being depended on.",
            "calleeType": "Entity type of the callee.",
            "method": "HTTP method of the callee endpoint the dependency refers to; empty when the dependency covers the whole entity.",
            "path": "Path of the callee endpoint the dependency refers to; empty when the dependency covers the whole entity.",
            "description": "Description of the dependency.",
            "metadata": "Arbitrary JSON metadata attached to the dependency.",
        },
    },
    "relationships": {
        "description": "A single edge between two catalog entities for a given relationship type.",
        "docs_url": "https://docs.cortex.io/api/readme/entity-relationships",
        "columns": {
            "relationship_type_tag": "Tag of the relationship type this edge belongs to.",
            "relationshipTypeTag": "Tag of the relationship type this edge belongs to, as echoed by the API.",
            "sourceEntity": "Identifying fields of the source entity in the relationship.",
            "source_entity_tag": "Tag of the source entity in the relationship.",
            "source_entity_id": "CID of the source entity in the relationship.",
            "destinationEntity": "Identifying fields of the destination entity in the relationship.",
            "destination_entity_tag": "Tag of the destination entity in the relationship.",
            "destination_entity_id": "CID of the destination entity in the relationship.",
            "providerType": "Provider that supplied the relationship, when it was created via an integration.",
        },
    },
    "entity_groups": {
        "description": "One entity's membership of one group, the tagging dimension most scorecard and Initiative filters are written against.",
        "docs_url": "https://docs.cortex.io/api/readme/groups",
        "columns": {
            "entity_id": "CID of the entity that belongs to the group.",
            "entity_tag": "Tag of the entity that belongs to the group.",
            "tag": "Tag of the group the entity belongs to.",
        },
    },
}
