import { MakeLogicType, actions, afterMount, connect, kea, listeners, path } from 'kea'

import { addProjectIdIfMissing } from 'lib/utils/kea-router'
import { userLogic } from 'scenes/userLogic'

import { osSpotlightLogic } from '../spotlight/osSpotlightLogic'
import { osWindowsLogic } from '../windows/osWindowsLogic'
import type { OsWindowState } from '../windows/osWindowsLogic'
import { OsBridgeMessage, osBridgeSenderWindowId, parseOsBridgeMessage, postToOsFrames } from './osBridgeProtocol'
import { OS_FRAME_NAME_PREFIX, osFrameName } from './osFrame'
import { setOsWindowOpener } from './osFrameConnection'
import { osSidePanelPath } from './osSidePanelPath'

function osWindowFrames(): HTMLIFrameElement[] {
    return Array.from(document.querySelectorAll<HTMLIFrameElement>(`iframe[name^="${OS_FRAME_NAME_PREFIX}"]`))
}

function isCrossOrigin(frame: HTMLIFrameElement): boolean {
    try {
        return !frame.contentWindow?.location.href
    } catch {
        return true
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface osBridgeLogicValues {
    focusedWindow: OsWindowState | null // osWindowsLogic
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface osBridgeLogicActions {
    showSpotlight: () => {
        value: true
    } // osSpotlightLogic
    focusWindow: (id: string) => {
        id: string
    } // osWindowsLogic
    openWindow: (
        path: string,
        options?: import('../windows/osWindowsLogic').OsOpenWindowOptions | undefined
    ) => {
        id: string
        options: import('../windows/osWindowsLogic').OsOpenWindowOptions
        path: string
    } // osWindowsLogic
    runWindowCommand: (command: import('../windows/osWindowShortcuts').OsWindowCommand) => {
        command: import('../windows/osWindowShortcuts').OsWindowCommand
    } // osWindowsLogic
    windowNavigated: (
        id: string,
        path: string,
        title?: string | undefined
    ) => {
        id: string
        path: string
        title: string | undefined
    } // osWindowsLogic
    loadUser: (resetOnFailure?: boolean | undefined) => {
        resetOnFailure: boolean | undefined
    } // userLogic
    updateUserSuccess: (
        user: import('../../../types').UserType,
        payload?:
            | {
                  successCallback: (() => void) | undefined
                  user: Partial<import('../../../types').UserType>
              }
            | undefined
    ) => {
        payload?: {
            successCallback: (() => void) | undefined
            user: Partial<import('../../../types').UserType>
        }
        user: import('../../../types').UserType
    } // userLogic
    messageReceived: (
        windowId: string,
        message: OsBridgeMessage
    ) => {
        message: OsBridgeMessage
        windowId: string
    }
    sidePanelRequested: (
        windowId: string,
        tab: string,
        options?: string
    ) => {
        options: string | undefined
        tab: string
        windowId: string
    }
}

export type osBridgeLogicType = MakeLogicType<osBridgeLogicValues, osBridgeLogicActions>

/**
 * The OS page's side of the bridge: it reads messages from the window frames and acts on them through
 * `osWindowsLogic`. The framed app's side is `osFrameBridgeLogic`.
 */
export const osBridgeLogic = kea<osBridgeLogicType>([
    path(['scenes', 'os', 'bridge', 'osBridgeLogic']),
    connect(() => ({
        values: [osWindowsLogic, ['focusedWindow']],
        actions: [
            osWindowsLogic,
            ['windowNavigated', 'focusWindow', 'openWindow', 'runWindowCommand'],
            osSpotlightLogic,
            ['showSpotlight'],
            userLogic,
            ['loadUser', 'updateUserSuccess'],
        ],
    })),
    actions({
        messageReceived: (windowId: string, message: OsBridgeMessage) => ({ windowId, message }),
        /** A window asked for a side panel. A shell with its own side panel can listen for this. */
        sidePanelRequested: (windowId: string, tab: string, options?: string) => ({ windowId, tab, options }),
    }),
    listeners(({ actions, values }) => ({
        messageReceived: ({ windowId, message }) => {
            switch (message.type) {
                case 'location':
                    actions.windowNavigated(windowId, message.path, message.title)
                    // Back and forward can step a window that is behind others, so that window comes to the front.
                    if (message.traversed) {
                        actions.focusWindow(windowId)
                    }
                    return
                case 'open-window':
                    actions.openWindow(message.path, { newWindow: true })
                    return
                case 'focus':
                    // Every click in a window sends this, and focusing the top window would still save the layout.
                    if (values.focusedWindow?.id !== windowId) {
                        actions.focusWindow(windowId)
                    }
                    return
                case 'user-changed':
                    actions.loadUser()
                    postToOsFrames(
                        osWindowFrames().filter((frame) => frame.name !== osFrameName(windowId)),
                        { type: 'user-changed' },
                        window.location.origin
                    )
                    return
                case 'window-command':
                    // The frame that had keyboard focus may not be on top yet, and the command acts on the top window.
                    actions.focusWindow(windowId)
                    actions.runWindowCommand(message.command)
                    return
                case 'open-top':
                    window.location.assign(message.url)
                    return
                case 'side-panel':
                    actions.sidePanelRequested(windowId, message.tab, message.options)
                    return
                case 'spotlight':
                    actions.showSpotlight()
                    return
            }
        },
        // The frames keep their own copy of the user, so a theme picked in the menu bar would not reach them.
        updateUserSuccess: () => {
            postToOsFrames(osWindowFrames(), { type: 'user-changed' }, window.location.origin)
        },
        sidePanelRequested: ({ tab, options }) => {
            const panelPath = osSidePanelPath(tab, options)
            if (panelPath) {
                actions.openWindow(addProjectIdIfMissing(panelPath))
            }
        },
    })),
    afterMount(({ actions, cache }) => {
        cache.disposables.add(
            () => {
                const onMessage = (event: MessageEvent): void => {
                    const windowId = osBridgeSenderWindowId(event, osWindowFrames(), window.location.origin)
                    const message = windowId ? parseOsBridgeMessage(event.data) : null
                    if (windowId && message) {
                        actions.messageReceived(windowId, message)
                    }
                }
                // A frame on another origin (a sign-in or billing page) cannot report clicks. When the person
                // clicks into one, this page loses focus to it, so that window comes to the front. Same-origin
                // frames are skipped: an app that focuses an input on load would otherwise raise its window.
                const onBlur = (): void => {
                    window.setTimeout(() => {
                        const active = document.activeElement
                        if (
                            active instanceof HTMLIFrameElement &&
                            active.name.startsWith(OS_FRAME_NAME_PREFIX) &&
                            isCrossOrigin(active)
                        ) {
                            actions.focusWindow(active.name.slice(OS_FRAME_NAME_PREFIX.length))
                        }
                    }, 0)
                }
                window.addEventListener('message', onMessage)
                window.addEventListener('blur', onBlur)
                // `newInternalTab` on this page, such as "New SQL query" in the spotlight, opens a window, not a browser tab.
                setOsWindowOpener((path) => actions.openWindow(path, { newWindow: true }))
                return () => {
                    window.removeEventListener('message', onMessage)
                    window.removeEventListener('blur', onBlur)
                    setOsWindowOpener(null)
                }
            },
            'bridge',
            // Windows keep loading and navigating while the tab is hidden, and their reports must not get lost.
            { pauseOnPageHidden: false }
        )
    }),
])
