export { SurveysFinalSteps } from './_snippets/surveys-final-steps'

export { SurveysAngularInstallation } from './angular'
export { SurveysAstroInstallation } from './astro'
export { SurveysBubbleInstallation } from './bubble'
export { SurveysFlutterInstallation } from './flutter'
export { SurveysFramerInstallation } from './framer'
export { SurveysIOSInstallation } from './ios'
export { SurveysNextJSInstallation } from './nextjs'
export { SurveysNuxtInstallation } from './nuxt'
export { SurveysReactInstallation } from './react'
export { SurveysReactNativeInstallation } from './react-native'
export { SurveysRemixInstallation } from './remix'
export { SurveysSvelteInstallation } from './svelte'
export { SurveysVueInstallation } from './vue'
export { SurveysWebflowInstallation } from './webflow'
export { SurveysWebInstallation } from './web'
