connector.name=ducklake

ducklake.catalog.database-url=jdbc:postgresql://db:5432/ducklake
ducklake.catalog.database-user=posthog
ducklake.catalog.database-password=${ENV:TRINO_DUCKLAKE_DB_PASSWORD}
ducklake.data-path=s3://ducklake-dev/

fs.native-s3.enabled=true
s3.endpoint=http://objectstorage:19000
s3.region=us-east-1
s3.aws-access-key=${ENV:TRINO_DUCKLAKE_S3_ACCESS_KEY}
s3.aws-secret-key=${ENV:TRINO_DUCKLAKE_S3_SECRET_KEY}
s3.path-style-access=true
