from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "programs": {
        "description": "An affiliate program with its commission structure, exclusions, and payment settings.",
        "docs_url": "https://aff-api.uppromote.com/docs/v2/get-programs-28435009e0",
        "columns": {
            "id": "Unique identifier for the program.",
            "name": "Name of the program.",
            "is_default": "Whether this is the store's default program.",
            "status": "Program status (active or inactive).",
            "rule": "Commission rule type applied by the program.",
            "description": "Description of the program.",
            "commission_type": "How commissions are calculated (e.g. percent of sale, flat rate).",
            "commission_amount": "Commission amount or rate applied by the program.",
            "commission_advanced": "Tiered commission levels with their conditions and rates.",
            "new_customer_commission": "Extra commission settings for referrals from new customers.",
            "lifetime_commission": "Lifetime commission settings for connected customers.",
            "special_coupon_commission": "Commission settings applied to special coupons.",
            "exclude_product_tax": "Whether product tax is excluded from commission calculation.",
            "exclude_shipping": "Whether shipping is excluded from commission calculation.",
            "exclude_shipping_tax": "Whether shipping tax is excluded from commission calculation.",
            "exclude_tip": "Whether tips are excluded from commission calculation.",
            "exclude_self_referral": "Whether self-referrals are excluded from commission.",
            "payment_methods": "Payment methods available to affiliates in this program.",
            "payment_default": "Default payment method for affiliates in this program.",
            "created_at": "When the program was created.",
        },
    },
    "affiliates": {
        "description": "An affiliate account with profile details, program membership, and commission totals.",
        "docs_url": "https://aff-api.uppromote.com/docs/v2/get-affiliates-21170049e0",
        "columns": {
            "id": "Unique identifier for the affiliate.",
            "email": "Email of the affiliate.",
            "first_name": "First name of the affiliate.",
            "last_name": "Last name of the affiliate.",
            "status": "Affiliate account status (active, inactive, or pending).",
            "email_verified": "Email verification status (verified or unverified).",
            "company": "Company name of the affiliate.",
            "address": "Address of the affiliate.",
            "city": "City of the affiliate.",
            "state": "State of the affiliate.",
            "zipcode": "Zip code of the affiliate.",
            "country": "Country of the affiliate.",
            "phone": "Phone number of the affiliate.",
            "facebook": "Facebook profile of the affiliate.",
            "twitter": "X (formerly Twitter) profile of the affiliate.",
            "youtube": "YouTube channel of the affiliate.",
            "instagram": "Instagram profile of the affiliate.",
            "website": "Website of the affiliate.",
            "tiktok": "TikTok profile of the affiliate.",
            "w9_form": "W9 form uploaded by the affiliate.",
            "internal_note": "Internal note about the affiliate.",
            "personal_detail": "Personal detail text from the affiliate's profile.",
            "created_at": "Affiliate account registration date and time.",
            "default_affiliate_link": "Default affiliate tracking link.",
            "custom_affiliate_link": "Custom affiliate tracking link.",
            "program_id": "ID of the program the affiliate belongs to.",
            "program_name": "Name of the program the affiliate belongs to.",
            "custom_fields": "Custom registration fields (label and value).",
            "coupons": "Coupons assigned to the affiliate.",
            "vat_number": "VAT number of the affiliate.",
            "tax_value": "Tax percentage of the affiliate.",
            "up_line_affiliate_id": "ID of the upline affiliate in a multi-level network.",
            "up_line_affiliate_email": "Email of the upline affiliate.",
            "payment_method": "Payment method of the affiliate (e.g. paypal, bank, store_credit).",
            "payment_info": "Payment details of the affiliate.",
            "paid_amount": "Total commission already paid to the affiliate.",
            "approved_amount": "Total approved commission awaiting payment.",
            "pending_amount": "Total pending commission of the affiliate.",
            "denied_amount": "Total denied commission of the affiliate.",
        },
    },
    "coupons": {
        "description": "A discount coupon assigned to an affiliate for coupon-based referral tracking.",
        "docs_url": "https://aff-api.uppromote.com/docs/v2/get-coupons-21170056e0",
        "columns": {
            "id": "Unique identifier for the coupon assignment.",
            "affiliate_id": "ID of the affiliate the coupon is assigned to.",
            "affiliate_email": "Email of the affiliate the coupon is assigned to.",
            "coupon": "The coupon code.",
            "description": "Description of the coupon (discount details).",
            "created_at": "When the coupon was assigned.",
        },
    },
    "referrals": {
        "description": "A referral (converted order) attributed to an affiliate, with its commission and status.",
        "docs_url": "https://aff-api.uppromote.com/docs/v2/get-list-referrals-21170075e0",
        "columns": {
            "id": "Unique identifier for the referral.",
            "order_id": "ID of the Shopify order the referral belongs to.",
            "order_number": "Order number of the referred order.",
            "customer_id": "ID of the customer who placed the order.",
            "quantity": "Number of items in the referred order.",
            "total_sales": "Total sales amount of the referred order.",
            "commission_rule": "Commission rule applied (program, rate, and type).",
            "commission_adjustment": "Manual adjustment applied to the commission.",
            "status": "Referral status (e.g. pending, approved, denied, paid).",
            "commission": "Commission amount earned by the affiliate.",
            "refund_id": "ID of the refund if the order was refunded.",
            "tracking_type": "How the referral was tracked (e.g. affiliate link, coupon).",
            "affiliate": "The affiliate credited with the referral (id, email, name).",
            "coupon_applied": "Coupon code applied to the order, if any.",
            "customer_email": "Email of the referred customer.",
            "created_at": "When the referral was recorded.",
        },
    },
    "payments_paid": {
        "description": "A completed affiliate payout, with the processed amount and payment method.",
        "docs_url": "https://aff-api.uppromote.com/docs/v2/get-paid-payments-history-21170059e0",
        "columns": {
            "payment_id": "Unique identifier for the payment.",
            "affiliate_id": "ID of the affiliate who was paid.",
            "affiliate_email": "Email of the affiliate who was paid.",
            "status": "Payment status.",
            "total_referrals": "Number of referrals covered by the payment.",
            "total_processed": "Amount processed in the payment.",
            "payment_method": "Payment method used (e.g. paypal, bank, store_credit).",
            "processed_at": "When the payment was processed.",
            "referral_ids": "IDs of the referrals covered by the payment.",
        },
    },
    "payments_unpaid": {
        "description": (
            "A snapshot of outstanding (approved but unpaid) commission per affiliate. "
            "Aggregated totals, refreshed in full on every sync."
        ),
        "docs_url": "https://aff-api.uppromote.com/docs/v2/get-unpaid-payments-21170058e0",
        "columns": {
            "affiliate_id": "ID of the affiliate with outstanding commission.",
            "affiliate_email": "Email of the affiliate with outstanding commission.",
            "total_referrals": "Number of referrals awaiting payment.",
            "payment_method": "Payment method configured by the affiliate.",
            "total_commission": "Total outstanding commission amount.",
            "total_sales": "Total sales amount behind the outstanding commission.",
            "total_products": "Number of products behind the outstanding commission.",
            "referral_ids": "IDs of the referrals awaiting payment.",
        },
    },
}
