import { SDKInstructionsMap, SDKKey } from '~/types'

import {
    FeatureFlagsAndroidInstructions,
    FeatureFlagsAngularInstructions,
    FeatureFlagsAPIInstructions,
    FeatureFlagsAstroInstructions,
    FeatureFlagsBubbleInstructions,
    FeatureFlagsDjangoInstructions,
    FeatureFlagsFlutterInstructions,
    FeatureFlagsFramerInstructions,
    FeatureFlagsGoInstructions,
    FeatureFlagsIOSInstructions,
    FeatureFlagsJSWebInstructions,
    FeatureFlagsLaravelInstructions,
    FeatureFlagsNextJSInstructions,
    FeatureFlagsNodeInstructions,
    FeatureFlagsNuxtJSInstructions,
    FeatureFlagsPHPInstructions,
    FeatureFlagsPythonInstructions,
    FeatureFlagsReactInstructions,
    FeatureFlagsRemixJSInstructions,
    FeatureFlagsRNInstructions,
    FeatureFlagsRubyInstructions,
    FeatureFlagsSvelteInstructions,
    FeatureFlagsVueInstructions,
    FeatureFlagsWebflowInstructions,
} from '.'

export const FeatureFlagsSDKInstructions: SDKInstructionsMap = {
    [SDKKey.JS_WEB]: FeatureFlagsJSWebInstructions,
    [SDKKey.ANGULAR]: FeatureFlagsAngularInstructions,
    [SDKKey.ANDROID]: FeatureFlagsAndroidInstructions,
    [SDKKey.API]: FeatureFlagsAPIInstructions,
    [SDKKey.ASTRO]: FeatureFlagsAstroInstructions,
    [SDKKey.BUBBLE]: FeatureFlagsBubbleInstructions,
    [SDKKey.DJANGO]: FeatureFlagsDjangoInstructions,
    [SDKKey.FLUTTER]: FeatureFlagsFlutterInstructions,
    [SDKKey.FRAMER]: FeatureFlagsFramerInstructions,
    [SDKKey.GO]: FeatureFlagsGoInstructions,
    [SDKKey.IOS]: FeatureFlagsIOSInstructions,
    [SDKKey.LARAVEL]: FeatureFlagsLaravelInstructions,
    [SDKKey.NEXT_JS]: FeatureFlagsNextJSInstructions,
    [SDKKey.NODE_JS]: FeatureFlagsNodeInstructions,
    [SDKKey.NUXT_JS]: FeatureFlagsNuxtJSInstructions,
    [SDKKey.PHP]: FeatureFlagsPHPInstructions,
    [SDKKey.PYTHON]: FeatureFlagsPythonInstructions,
    [SDKKey.REACT]: FeatureFlagsReactInstructions,
    [SDKKey.REACT_NATIVE]: FeatureFlagsRNInstructions,
    [SDKKey.REMIX]: FeatureFlagsRemixJSInstructions,
    [SDKKey.RUBY]: FeatureFlagsRubyInstructions,
    [SDKKey.SVELTE]: FeatureFlagsSvelteInstructions,
    [SDKKey.VUE_JS]: FeatureFlagsVueInstructions,
    [SDKKey.WEBFLOW]: FeatureFlagsWebflowInstructions,
}
