from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "organizations": {
        "description": "The configured HCP Terraform organization. An organization is a shared space for teams to collaborate on workspaces.",
        "docs_url": "https://developer.hashicorp.com/terraform/cloud-docs/api-docs/organizations",
        "columns": {
            "id": "Unique identifier of the organization — its name.",
            "name": "Name of the organization.",
            "external_id": "Immutable external identifier of the organization (org-...).",
            "created_at": "When the organization was created.",
            "email": "Admin email address for the organization.",
            "plan_expired": "Whether the organization's paid plan has expired.",
            "plan_expires_at": "When the organization's paid plan expires.",
            "cost_estimation_enabled": "Whether cost estimation is enabled for the organization.",
            "saml_enabled": "Whether SAML single sign-on is enabled.",
            "default_execution_mode": "Default execution mode for new workspaces (remote, local, or agent).",
        },
    },
    "projects": {
        "description": "Projects in the configured organization. Projects group related workspaces and let teams organize permissions at a higher level.",
        "docs_url": "https://developer.hashicorp.com/terraform/cloud-docs/api-docs/projects",
        "columns": {
            "id": "Unique identifier of the project (prj-...).",
            "name": "Name of the project.",
            "description": "Description of the project.",
            "created_at": "When the project was created.",
            "workspace_count": "Number of workspaces in the project.",
            "team_count": "Number of teams with access to the project.",
            "organization_id": "Name of the organization the project belongs to.",
        },
    },
    "teams": {
        "description": "Teams in the configured organization. Teams group users and are granted permissions on workspaces and projects.",
        "docs_url": "https://developer.hashicorp.com/terraform/cloud-docs/api-docs/teams",
        "columns": {
            "id": "Unique identifier of the team (team-...).",
            "name": "Name of the team.",
            "users_count": "Number of users on the team.",
            "visibility": "Team visibility within the organization (secret or organization).",
            "organization_access": "Organization-level permissions granted to the team.",
            "sso_team_id": "SSO team id mapped to this team, when SSO team management is enabled.",
        },
    },
    "workspaces": {
        "description": "Workspaces in the configured organization. A workspace holds a Terraform configuration, its state, and its run history.",
        "docs_url": "https://developer.hashicorp.com/terraform/cloud-docs/api-docs/workspaces",
        "columns": {
            "id": "Unique identifier of the workspace (ws-...).",
            "name": "Name of the workspace.",
            "created_at": "When the workspace was created.",
            "updated_at": "When the workspace was last updated.",
            "auto_apply": "Whether successful plans are automatically applied.",
            "execution_mode": "How runs execute (remote, local, or agent).",
            "terraform_version": "Terraform version the workspace runs.",
            "working_directory": "Relative path Terraform executes in.",
            "locked": "Whether the workspace is currently locked.",
            "resource_count": "Number of resources tracked in the workspace's current state.",
            "latest_change_at": "When the workspace last changed (run, state, or settings).",
            "organization_id": "Name of the organization the workspace belongs to.",
            "project_id": "Identifier of the project the workspace belongs to.",
            "current_run_id": "Identifier of the workspace's current run.",
        },
    },
    "runs": {
        "description": "Runs across every workspace in the organization. A run is one plan/apply cycle performed against a workspace's configuration.",
        "docs_url": "https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run",
        "columns": {
            "id": "Unique identifier of the run (run-...).",
            "status": "Current status of the run (e.g. planned, applied, errored, canceled).",
            "status_timestamps": "Timestamps for each status transition the run has reached.",
            "created_at": "When the run was created.",
            "message": "Message describing why the run was queued.",
            "is_destroy": "Whether the run destroys all managed infrastructure.",
            "source": "What triggered the run (e.g. tfe-ui, tfe-api, tfe-configuration-version).",
            "trigger_reason": "Why the run was triggered.",
            "has_changes": "Whether the plan detected resource changes.",
            "auto_apply": "Whether the run applies automatically after a successful plan.",
            "plan_only": "Whether the run is speculative (plan only, never applied).",
            "terraform_version": "Terraform version used for the run.",
            "workspace_id": "Identifier of the workspace the run belongs to.",
            "workspace_name": "Name of the workspace the run belongs to.",
            "plan_id": "Identifier of the run's plan.",
            "apply_id": "Identifier of the run's apply.",
            "configuration_version_id": "Identifier of the configuration version the run used.",
        },
    },
    "state_versions": {
        "description": "State versions across every workspace in the organization. A state version is one snapshot of a workspace's Terraform state, created by an apply or an upload.",
        "docs_url": "https://developer.hashicorp.com/terraform/cloud-docs/api-docs/state-versions",
        "columns": {
            "id": "Unique identifier of the state version (sv-...).",
            "serial": "Monotonically increasing serial number of the state within its workspace.",
            "created_at": "When the state version was created.",
            "size": "Size of the state file in bytes.",
            "state_version": "Version of the Terraform state file format.",
            "terraform_version": "Terraform version that produced the state.",
            "resources_processed": "Whether HCP Terraform has finished parsing resources out of the state.",
            "modules": "Resource counts grouped by module.",
            "providers": "Resource counts grouped by provider.",
            "workspace_id": "Identifier of the workspace the state version belongs to.",
            "workspace_name": "Name of the workspace the state version belongs to.",
            "run_id": "Identifier of the run that created the state version, when applicable.",
        },
    },
}
