from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

DETAIL_RECORD_SEARCH_DOCS_URL = "https://developers.telnyx.com/docs/api/v2/detail-records/detail-record-search"

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "MessagingDetailRecords": {
        "description": "Per-message detail records (MDRs) for SMS/MMS sent or received through Telnyx Messaging.",
        "docs_url": DETAIL_RECORD_SEARCH_DOCS_URL,
        "columns": {
            "uuid": "Unique identifier of the message.",
            "user_id": "Identifier of the Telnyx account who owns the message.",
            "completed_at": "Message completion time.",
            "created_at": "Message creation time.",
            "updated_at": "Message updated time.",
            "sent_at": "Time when the message was sent.",
            "carrier": "Country-specific carrier used to send or receive the message.",
            "carrier_fee": "Fee charged by certain carriers to deliver certain message types.",
            "cld": "The recipient of the message (the `to` parameter in the Messaging API).",
            "cli": "The sender of the message (the `from` parameter in the Messaging API).",
            "country_code": "Two-letter ISO 3166-1 alpha-2 country of the `cld` property.",
            "delivery_status": "Final webhook delivery status.",
            "direction": "Logical direction of the message from the Telnyx customer's perspective.",
            "fteu": "Whether this is a Free-To-End-User (FTEU) short code message.",
            "mcc": "Mobile country code, for certain products such as Global Outbound.",
            "mnc": "Mobile network code, for certain products such as Global Outbound.",
            "message_type": "The Messaging service used to send the message (e.g. SMS, MMS).",
            "on_net": "Whether both sender and recipient numbers are Telnyx-managed.",
            "profile_id": "Unique identifier of the Messaging Profile used to send or receive the message.",
            "profile_name": "Name of the Messaging Profile used to send or receive the message.",
            "status": "Final status of the message after the delivery attempt.",
            "tags": "Comma-separated tags assigned to the Telnyx number associated with the message.",
            "rate": "Currency amount per billing unit used to calculate the Telnyx billing cost.",
            "currency": "Telnyx account currency used to describe monetary values.",
            "cost": "Amount, in the account currency, for the Telnyx billing cost.",
            "parts": "Number of message parts the message was broken into.",
            "record_type": "Identifies the record schema.",
        },
    },
    "VerifyDetailRecords": {
        "description": "Detail records for Telnyx Verify (2FA) verification attempts.",
        "docs_url": DETAIL_RECORD_SEARCH_DOCS_URL,
        "columns": {
            "id": "Unique ID of the verification.",
            "verify_profile_id": "Identifier of the Verify profile used for this verification.",
            "delivery_status": "Delivery status of the verification message.",
            "verification_status": "Outcome status of the verification attempt.",
            "destination_phone_number": "E.164 formatted destination phone number.",
            "verify_channel_type": "Channel used for the verification (e.g. SMS, call, flash call).",
            "verify_channel_id": "Identifier of the specific channel resource used.",
            "created_at": "Verification creation time.",
            "updated_at": "Verification updated time.",
            "rate": "Currency amount per billing unit used to calculate the Telnyx billing cost.",
            "verify_usage_fee": "Currency amount for the Verify usage fee.",
            "currency": "Telnyx account currency used to describe monetary values.",
            "record_type": "Identifies the record schema.",
        },
    },
    "WirelessUsageDetailRecords": {
        "description": "SIM card data usage events for Telnyx Wireless.",
        "docs_url": DETAIL_RECORD_SEARCH_DOCS_URL,
        "columns": {
            "id": "Unique identifier for this SIM card usage event.",
            "created_at": "Event creation time.",
            "closed_at": "Event close time.",
            "ip_address": "IP address that generated the event.",
            "downlink_data": "Number of megabytes downloaded.",
            "uplink_data": "Number of megabytes uploaded.",
            "imsi": "International Mobile Subscriber Identity.",
            "mcc": "Mobile country code.",
            "mnc": "Mobile network code.",
            "currency": "Telnyx account currency used to describe monetary values.",
            "data_unit": "Unit of wireless link consumption.",
            "data_rate": "Currency amount per billing unit used to calculate the Telnyx billing cost.",
            "data_cost": "Data cost for this usage event.",
            "sim_group_name": "SIM group name for the SIM card.",
            "sim_group_id": "Unique identifier for the SIM group.",
            "sim_card_id": "Unique identifier for the SIM card.",
            "sim_card_tags": "User-provided tags on the SIM card.",
            "phone_number": "Telephone number associated with the SIM card.",
            "record_type": "Identifies the record schema.",
        },
    },
    "MediaStorageDetailRecords": {
        "description": "Events for Telnyx Media Storage API actions (uploads, downloads, links).",
        "docs_url": DETAIL_RECORD_SEARCH_DOCS_URL,
        "columns": {
            "id": "Unique identifier for the Media Storage event.",
            "created_at": "Event creation time.",
            "asset_id": "Identifier of the stored asset.",
            "user_id": "Identifier of the Telnyx user who owns the asset.",
            "org_id": "Identifier of the organization that owns the asset.",
            "action_type": "Type of action performed against the Media Storage API.",
            "link_channel_type": "Channel type of the sharing link, if any.",
            "link_channel_id": "Identifier of the sharing link channel, if any.",
            "status": "Status of the request.",
            "webhook_id": "Identifier of the webhook associated with this event, if any.",
            "rate": "Currency amount per billing unit used to calculate the Telnyx billing cost.",
            "cost": "Currency amount for the Telnyx billing cost.",
            "currency": "Telnyx account currency used to describe monetary values.",
            "record_type": "Identifies the record schema.",
        },
    },
    "ConferenceDetailRecords": {
        "description": "Detail records for Telnyx Call Control conferences.",
        "docs_url": DETAIL_RECORD_SEARCH_DOCS_URL,
        "columns": {
            "id": "Conference id.",
            "name": "Conference name.",
            "user_id": "Identifier of the Telnyx user who owns the conference.",
            "started_at": "Conference start time.",
            "ended_at": "Conference end time.",
            "expires_at": "Conference expiry time.",
            "region": "Region where the conference is hosted.",
            "call_leg_id": "Telnyx UUID that identifies the conference call leg.",
            "call_session_id": "Telnyx UUID that identifies the conference call session.",
            "connection_id": "Identifier of the Call Control connection used.",
            "call_sec": "Duration of the conference call in seconds.",
            "participant_count": "Number of participants that joined the conference call.",
            "participant_call_sec": "Sum of the conference call duration for all participants, in seconds.",
            "is_telnyx_billable": "Whether Telnyx billing charges might be applicable.",
            "record_type": "Identifies the record schema.",
        },
    },
    "ConferenceParticipantDetailRecords": {
        "description": "Detail records for individual participants of a Telnyx Call Control conference.",
        "docs_url": DETAIL_RECORD_SEARCH_DOCS_URL,
        "columns": {
            "id": "Participant id.",
            "user_id": "Identifier of the Telnyx user who owns the conference.",
            "conference_id": "Identifier of the conference this participant joined.",
            "joined_at": "Participant join time.",
            "left_at": "Participant leave time.",
            "destination_number": "Number called by the participant to join the conference.",
            "originating_number": "Participant's origin number used in the conference call.",
            "call_leg_id": "Telnyx UUID that identifies the conference call leg.",
            "call_session_id": "Telnyx UUID that identifies the conference call session.",
            "call_sec": "Duration of the conference call in seconds.",
            "billed_sec": "Duration of the conference call for billing purposes.",
            "is_telnyx_billable": "Whether Telnyx billing charges might be applicable.",
            "rate": "Currency amount per billing unit used to calculate the Telnyx billing cost.",
            "rate_measured_in": "Billing unit used to calculate the Telnyx billing cost.",
            "cost": "Currency amount for the Telnyx billing cost.",
            "currency": "Telnyx account currency used to describe monetary values.",
            "record_type": "Identifies the record schema.",
        },
    },
    "AmdDetailRecords": {
        "description": "Detail records for Telnyx Answering Machine Detection (AMD) feature invocations.",
        "docs_url": DETAIL_RECORD_SEARCH_DOCS_URL,
        "columns": {
            "id": "Feature invocation id.",
            "invoked_at": "Feature invocation time.",
            "feature": "Feature name.",
            "tags": "User-provided tags.",
            "billing_group_id": "Identifier of the billing group.",
            "billing_group_name": "Name of the billing group specified in `billing_group_id`.",
            "connection_id": "Identifier of the Call Control connection used.",
            "connection_name": "Name of the Call Control connection used.",
            "call_leg_id": "Telnyx UUID that identifies the related call leg.",
            "call_session_id": "Telnyx UUID that identifies the related call session.",
            "is_telnyx_billable": "Whether Telnyx billing charges might be applicable.",
            "rate": "Currency amount per billing unit used to calculate the Telnyx billing cost.",
            "rate_measured_in": "Billing unit used to calculate the Telnyx billing cost.",
            "cost": "Currency amount for the Telnyx billing cost.",
            "currency": "Telnyx account currency used to describe monetary values.",
            "record_type": "Identifies the record schema.",
        },
    },
}
