from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "alerts": {
        "description": "Data quality alerts raised by Monte Carlo monitors — a collection of related anomaly events with severity, status, and triage metadata.",
        "docs_url": "https://docs.getmontecarlo.com/docs/interacting-with-incidents",
        "columns": {
            "uuid": "Unique identifier for the alert.",
            "title": "Human-readable title of the alert.",
            "name": "Internal name of the alert.",
            "type": "Type of alert (e.g. anomalies, schema changes, custom rule breaches).",
            "subTypes": "More specific alert sub-types (e.g. freshness_anomaly, volume_anomaly).",
            "status": "Current status of the alert (e.g. acknowledged, resolved, expected).",
            "severity": "Severity assigned to the alert. Present when the alert has been marked as an incident.",
            "priority": "Priority inherited from the associated monitor.",
            "triagePriority": "Consolidated triage priority derived from the latest triage run.",
            "feedback": "User feedback recorded on the alert.",
            "createdTime": "When the alert was created.",
            "updatedTime": "When the alert was last updated.",
            "sloStatus": "Status of the alert against its service level objective.",
            "sloType": "Type of service level objective associated with the alert.",
            "sloBreachedTime": "When the alert breached its service level objective.",
            "url": "Link to the alert in the Monte Carlo UI.",
            "commentCount": "Number of comments on the alert.",
            "lastCommentText": "Text of the most recent comment.",
            "invalidRows": "Count of invalid rows detected, where applicable.",
            "monitorUuids": "UUIDs of the monitors that produced this alert.",
            "owner": "User the alert is assigned to (email and full name).",
            "tables": "Tables affected by the alert (MCON, table id, key-asset flag).",
            "assets": "Assets affected by the alert (MCON, asset id, asset type).",
            "audiences": "Audiences notified about the alert.",
            "monitorTags": "Tags on the monitors that produced this alert.",
        },
    },
    "monitors": {
        "description": "Monitors configured in Monte Carlo — the table, metric, validation, and custom rule checks that watch data assets and raise alerts.",
        "docs_url": "https://docs.getmontecarlo.com/docs/monitors-overview",
        "columns": {
            "uuid": "Unique identifier for the monitor.",
            "monitorType": "Type of monitor (e.g. stats, categories, custom SQL).",
            "udmType": "User-defined monitor category (rule, monitor, table monitor, bulk monitor).",
            "createdTime": "When the monitor was created (UTC).",
            "lastUpdateTime": "When the monitor was last updated (UTC).",
            "creatorId": "Identifier of the user who created the monitor.",
            "updaterId": "Identifier of the user who last updated the monitor.",
            "resourceId": "UUID of the warehouse/resource the monitor runs against.",
            "entities": "Entities (tables or views) the monitor watches.",
            "entityMcons": "MCONs of the entities the monitor watches.",
            "entityCount": "Number of entities the monitor watches.",
            "scheduleType": "How the monitor is scheduled (e.g. fixed, dynamic).",
            "name": "Name of the monitor.",
            "ruleName": "Name of the underlying rule.",
            "description": "Description of the monitor.",
            "notes": "Free-form notes on the monitor.",
            "labels": "Labels applied to the monitor.",
            "severity": "Default severity for alerts raised by this monitor.",
            "priority": "Priority assigned to the monitor.",
            "isSnoozeable": "Whether the monitor can be snoozed.",
            "isPaused": "Whether the monitor is currently paused.",
            "isDraft": "Whether the monitor is a draft.",
            "isTemplateManaged": "Whether the monitor is managed as code via monitors-as-code.",
            "namespace": "Monitors-as-code namespace the monitor belongs to.",
            "nextExecutionTime": "When the monitor is next scheduled to run.",
            "prevExecutionTime": "When the monitor last ran.",
            "connectionId": "UUID of the connection the monitor uses.",
            "isOotbMonitor": "Whether this is an out-of-the-box monitor.",
            "monitorRunStatus": "Status of the monitor's most recent run.",
            "monitorStatus": "Consolidated status of the monitor.",
            "consolidatedMonitorStatus": "Overall status combining run, configuration, and training state.",
            "exceptions": "Details of any exceptions from the monitor's last run.",
        },
    },
    "tables": {
        "description": "Tables and views Monte Carlo observes across your connected warehouses, with health and activity metadata.",
        "docs_url": "https://docs.getmontecarlo.com/docs/assets",
        "columns": {
            "id": "Globally unique identifier for the table record.",
            "mcon": "Monte Carlo object name — the global identifier for the asset.",
            "tableId": "Table identifier within its project and dataset.",
            "fullTableId": "Fully qualified table identifier (project:dataset.table).",
            "discoveredTime": "When Monte Carlo first discovered the table.",
            "friendlyName": "Display name for the table.",
            "location": "Physical location of the table, where applicable.",
            "projectName": "Project or database the table belongs to.",
            "dataset": "Dataset or schema the table belongs to.",
            "description": "Description of the table.",
            "tableType": "Type of the asset (e.g. table, view, external).",
            "isEncrypted": "Whether the table is encrypted.",
            "createdTime": "When the table was created in the warehouse.",
            "lastModified": "When the table was last modified.",
            "viewIsMaterialized": "Whether the view is materialized.",
            "path": "Storage path of the table, where applicable.",
            "priority": "Priority assigned to the table.",
            "tracked": "Whether Monte Carlo tracks this table.",
            "dynamicTable": "Whether this is a dynamic table.",
            "isDeleted": "Whether the table has been deleted from the warehouse.",
            "deletedAt": "When the table was deleted.",
            "lastObserved": "When Monte Carlo last observed the table.",
            "isExcluded": "Whether the table is excluded from monitoring.",
            "isMonitored": "Whether the table is actively monitored.",
            "dataProvider": "Data provider backing the table.",
            "ingestType": "How metadata for the table is ingested.",
            "importanceScore": "Monte Carlo's computed importance score for the table.",
            "isImportant": "Whether the table is flagged as a key asset.",
            "lastActivity": "Most recent activity observed on the table.",
            "lastRead": "Most recent read observed on the table.",
            "lastWrite": "Most recent write observed on the table.",
            "lastVolumeChange": "Most recent volume change observed on the table.",
            "warehouse": "Warehouse the table belongs to (UUID and name).",
        },
    },
    "users": {
        "description": "Users in your Monte Carlo account, useful for attributing alert ownership and monitor authorship.",
        "docs_url": "https://docs.getmontecarlo.com/docs/authorization-overview",
        "columns": {
            "id": "Globally unique identifier for the user record.",
            "cognitoUserId": "Authentication provider identifier for the user.",
            "email": "Email address of the user.",
            "firstName": "First name of the user.",
            "lastName": "Last name of the user.",
            "displayName": "Display name of the user.",
            "state": "Account state of the user (e.g. active, pending).",
            "createdOn": "When the user was created.",
            "isSso": "Whether the user signs in via SSO.",
            "isDeleted": "Whether the user has been removed from the account.",
            "deletedAt": "When the user was removed.",
        },
    },
    "warehouses": {
        "description": "Warehouse connections integrated with Monte Carlo (e.g. Snowflake, BigQuery, Redshift).",
        "docs_url": "https://docs.getmontecarlo.com/docs/integrations-overview",
        "columns": {
            "uuid": "Unique identifier for the warehouse connection.",
            "name": "Name of the warehouse connection.",
            "connectionType": "Type of the warehouse (e.g. snowflake, bigquery, redshift).",
            "createdTime": "When the warehouse connection was created.",
            "updatedTime": "When the warehouse connection was last updated.",
            "isDeleted": "Whether the warehouse connection has been deleted.",
            "deletedAt": "When the warehouse connection was deleted.",
            "bqProjectId": "BigQuery project id, for BigQuery connections.",
        },
    },
}
