export type LogsIngestionConsumerConfig = {
    LOGS_INGESTION_CONSUMER_GROUP_ID: string
    LOGS_INGESTION_CONSUMER_CONSUME_TOPIC: string
    LOGS_INGESTION_CONSUMER_OVERFLOW_TOPIC: string
    LOGS_INGESTION_CONSUMER_DLQ_TOPIC: string
    LOGS_INGESTION_CONSUMER_CLICKHOUSE_TOPIC: string
    LOGS_REDIS_HOST: string
    LOGS_REDIS_PORT: number
    LOGS_REDIS_PASSWORD: string
    LOGS_REDIS_TLS: boolean
    LOGS_LIMITER_ENABLED_TEAMS: string
    LOGS_LIMITER_DISABLED_FOR_TEAMS: string
    LOGS_LIMITER_BUCKET_SIZE_KB: number
    LOGS_LIMITER_REFILL_RATE_KB_PER_SECOND: number
    LOGS_LIMITER_TTL_SECONDS: number
    LOGS_LIMITER_TEAM_BUCKET_SIZE_KB: string
    LOGS_LIMITER_TEAM_REFILL_RATE_KB_PER_SECOND: string
    REDIS_URL: string
    REDIS_POOL_MIN_SIZE: number
    REDIS_POOL_MAX_SIZE: number
    KAFKA_CLIENT_RACK: string | undefined
}
