"""Canonical, documentation-sourced descriptions for Factorial endpoints and columns.

Sourced from the official Factorial API reference (https://apidoc.factorialhr.com/). Keyed by the
endpoint names in `settings.py` `FACTORIAL_ENDPOINTS`, which match the `ExternalDataSchema.name` of a
synced Factorial table. Columns absent here fall back to LLM enrichment, so partial coverage is fine.
"""

from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

_DOCS = "https://apidoc.factorialhr.com/"

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "employees": {
        "description": "People employed at the company, with their personal and employment details.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the employee.",
            "first_name": "Employee's first name.",
            "last_name": "Employee's last name.",
            "full_name": "Employee's full name.",
            "email": "Employee's work email address.",
            "birthday_on": "Employee's date of birth.",
            "gender": "Employee's gender.",
            "manager_id": "Identifier of the employee's manager.",
            "legal_entity_id": "Identifier of the legal entity the employee belongs to.",
            "location_id": "Identifier of the employee's primary workplace/location.",
            "team_ids": "Identifiers of the teams the employee belongs to.",
            "company_id": "Identifier of the company the employee belongs to.",
            "terminated_on": "Date the employee was terminated, if applicable.",
            "created_at": "Time at which the employee record was created.",
            "updated_at": "Time at which the employee record was last updated.",
        },
    },
    "teams": {
        "description": "Teams used to group employees within the company.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the team.",
            "name": "Name of the team.",
            "description": "Description of the team.",
            "employee_ids": "Identifiers of the employees in the team.",
            "lead_ids": "Identifiers of the team leads.",
        },
    },
    "team_memberships": {
        "description": "Join records mapping employees to the teams they belong to.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the membership.",
            "employee_id": "Identifier of the employee.",
            "team_id": "Identifier of the team.",
            "lead": "Whether the employee is a lead of the team.",
        },
    },
    "locations": {
        "description": "Workplaces/locations the company operates from, including their time zones.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the location.",
            "name": "Name of the location.",
            "country": "Country of the location.",
            "timezone": "Time zone of the location.",
            "company_id": "Identifier of the company the location belongs to.",
        },
    },
    "legal_entities": {
        "description": "Legal entities (companies) configured in the account.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the legal entity.",
            "legal_name": "Registered legal name of the entity.",
            "country": "Country the legal entity is registered in.",
            "currency": "Default currency used by the legal entity.",
        },
    },
    "contract_versions": {
        "description": "Versions of an employee's contract; the latest holds the current job title, salary, and working hours.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the contract version.",
            "employee_id": "Identifier of the employee the contract belongs to.",
            "job_title": "Job title on this contract version.",
            "salary_amount": "Salary amount on this contract version, in cents.",
            "salary_frequency": "Frequency the salary is paid at.",
            "starts_on": "Date this contract version starts.",
            "ends_on": "Date this contract version ends, if applicable.",
            "working_hours": "Contracted working hours.",
            "created_at": "Time at which the contract version was created.",
            "updated_at": "Time at which the contract version was last updated.",
        },
    },
    "compensations": {
        "description": "Salary and compensation lines attached to a contract version, one row per pay concept.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the compensation.",
            "contract_version_id": "Identifier of the contract version the compensation belongs to.",
            "contracts_taxonomy_id": "Identifier of the compensation taxonomy (pay concept) this line uses.",
            "description": "Free-text description of the compensation, for example 'Yearly variable'.",
            "compensation_type": "How the amount is applied: fixed, undefined, up_to, per_worked_day or per_worked_hour.",
            "amount": "Value paid on each recurrence, in the smallest currency unit (for example cents).",
            "unit": "Unit the compensation is paid in.",
            "currency": "Currency the compensation is paid in.",
            "recurrence": "How often the employee is paid (monthly, yearly, one_time). Can be empty.",
            "recurrence_count": "Number of months between payments when `recurrence` is empty; 12 means yearly.",
            "starts_on": "Date the compensation starts applying.",
            "first_payment_on": "Date of the first payout, which can be later than `starts_on`.",
            "calculation": "Human-readable hint about the payroll formula used.",
            "payroll_policy_id": "Identifier of the payroll policy the compensation follows.",
            "sync_with_supplements": "Whether the compensation is kept in sync with payroll supplements.",
            "time_condition": "Time condition the compensation applies under: full_day, half_day or custom.",
            "minimum_amount_of_hours": "Minimum hours that must be worked for the compensation to apply.",
            "minimum_amount_of_hours_in_cents": "Minimum hours for the compensation, in cents.",
        },
    },
    "leaves": {
        "description": "Individual time-off / absence records for employees.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the leave.",
            "employee_id": "Identifier of the employee taking the leave.",
            "company_id": "Identifier of the company.",
            "leave_type_id": "Identifier of the leave type.",
            "start_on": "First day of the leave.",
            "finish_on": "Last day of the leave.",
            "approved": "Whether the leave has been approved.",
            "created_at": "Time at which the leave was created.",
            "updated_at": "Time at which the leave was last updated.",
            "deleted_at": "Time at which the leave was deleted, if applicable.",
        },
    },
    "leave_types": {
        "description": "Types of time off / absence configured for the company (e.g. holiday, sick leave).",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the leave type.",
            "name": "Name of the leave type.",
            "color": "Display color for the leave type.",
            "approval_required": "Whether leaves of this type require approval.",
        },
    },
    "allowances": {
        "description": "Time-off allowance counters (the buckets of days/hours employees can take).",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the allowance.",
            "name": "Name of the allowance.",
        },
    },
    "allowance_stats": {
        "description": "Time-off counters per employee and allowance: how much is accrued, used, carried over and still available at the reference date.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Virtual identifier composed of employee_id, allowance_id and reference date. It cannot be used to fetch the record again.",
            "allowance_id": "Identifier of the allowance these counters belong to.",
            "employee_id": "Identifier of the employee these counters belong to.",
            "year": "Calendar year the cycle calculations are scoped to.",
            "cycles": "Accrual periods that make up the allowance.",
            "cycle_carry_overs": "Carry-over entries between cycles.",
            "accumulated_carry_over": "Units carried over from previous cycles.",
            "used_carry_over": "Carried-over units already used.",
            "available_days": "Units still usable at the reference date, after usage, carry-over and adjustments.",
            "used_days": "Units used in the current cycle.",
            "used_units_until_reference_date": "Units used up to the reference date.",
            "outstanding_units": "Units still owed to the employee.",
            "total_accrued_units": "Units accrued up to the reference date.",
            "total": "Total entitlement for the cycle, including accrual, carry over and incidences.",
            "total_in_decimal": "Total entitlement in decimal form.",
            "policy_allowance": "Base entitlement from the policy, before proration and adjustments.",
            "prorated_allowance_days": "Entitlement after proration for tenure or configuration.",
            "max_balance_cap": "Maximum balance the policy allows, or null when uncapped.",
            "incidences": "Sum of adjustment units applied to the allowance.",
            "accrued_incidences": "Adjustment units scoped to the accrued balance.",
            "available_incidences": "Adjustment units scoped to the available balance.",
        },
    },
    "attendance_shifts": {
        "description": "Attendance shifts: clock-in/clock-out records for employees.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the shift.",
            "employee_id": "Identifier of the employee.",
            "clock_in": "Clock-in timestamp.",
            "clock_out": "Clock-out timestamp.",
            "day": "Calendar day the shift belongs to.",
            "created_at": "Time at which the shift was created.",
            "updated_at": "Time at which the shift was last updated.",
        },
    },
    "worked_times": {
        "description": "Worked time aggregated per employee and day, including tracked, pending and multiplied minutes.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Identifier of the worked time, composed of the employee id and the date.",
            "employee_id": "Identifier of the employee the worked time belongs to.",
            "company_id": "Identifier of the company.",
            "date": "Day the worked time is counted for.",
            "minutes": "Worked minutes counted for the day.",
            "tracked_minutes": "Minutes tracked by the employee for the day.",
            "pending_minutes": "Minutes still pending approval.",
            "multiplied_minutes": "Minutes after multipliers such as overtime rates are applied.",
            "time_unit": "Unit the worked time is measured in: minute, half_day or none.",
            "day_type": "Type of day: workday, saturday, sunday or bank_holiday.",
            "worked_time_blocks": "Individual blocks of time that make up the day's worked time.",
        },
    },
    "expenses": {
        "description": "Employee expenses submitted for reimbursement.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the expense.",
            "employee_id": "Identifier of the employee who submitted the expense.",
            "amount_cents": "Expense amount in cents.",
            "currency": "Currency of the expense amount.",
            "status": "Current status of the expense.",
            "created_at": "Time at which the expense was created.",
            "updated_at": "Time at which the expense was last updated.",
        },
    },
    "payroll_supplements": {
        "description": "Payroll supplements (one-off additions or deductions applied to payroll).",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the supplement.",
            "employee_id": "Identifier of the employee.",
            "amount_in_cents": "Supplement amount in cents.",
            "description": "Description of the supplement.",
            "created_at": "Time at which the supplement was created.",
            "updated_at": "Time at which the supplement was last updated.",
        },
    },
    "flexible_time_records": {
        "description": "Flexible time records logged against projects (project time tracking).",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the time record.",
            "employee_id": "Identifier of the employee.",
            "date": "Date the time was recorded for.",
            "imputed_minutes": "Minutes imputed to the record.",
            "created_at": "Time at which the record was created.",
            "updated_at": "Time at which the record was last updated.",
        },
    },
    "time_records": {
        "description": "Time booked against projects, linking an attendance shift to the project worker and subproject it was spent on.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the time record.",
            "project_worker_id": "Identifier of the project worker the time is booked for.",
            "attendance_shift_id": "Identifier of the attendance shift the time record belongs to.",
            "subproject_id": "Identifier of the subproject the time is booked against, if any.",
            "date": "Reference date of the shift.",
            "imputed_minutes": "Minutes between the clock in and the clock out.",
            "clock_in": "Time the employee clocked in.",
            "clock_out": "Time the employee clocked out.",
            "observations": "Free-text comment on the time record.",
        },
    },
    "projects": {
        "description": "Projects used for time tracking.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the project.",
            "name": "Name of the project.",
            "status": "Current status of the project.",
        },
    },
    "candidates": {
        "description": "Candidates in the applicant tracking system (ATS).",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the candidate.",
            "first_name": "Candidate's first name.",
            "last_name": "Candidate's last name.",
            "email": "Candidate's email address.",
            "created_at": "Time at which the candidate was created.",
            "updated_at": "Time at which the candidate was last updated.",
        },
    },
    "job_postings": {
        "description": "Job postings published in the applicant tracking system (ATS).",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the job posting.",
            "title": "Title of the job posting.",
            "status": "Current status of the job posting.",
            "team_id": "Identifier of the team the posting belongs to.",
            "location_id": "Identifier of the location for the posting.",
        },
    },
    "applications": {
        "description": "Applications linking candidates to job postings in the ATS.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the application.",
            "candidate_id": "Identifier of the candidate.",
            "ats_job_posting_id": "Identifier of the job posting applied to.",
            "phase_id": "Identifier of the current hiring phase.",
            "created_at": "Time at which the application was created.",
            "updated_at": "Time at which the application was last updated.",
        },
    },
}
