from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

_DOCS_URL = "https://scp-api.strato.de/documentation/v1/en/api/documentation.html"

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "Servers": {
        "description": "Cloud servers in the STRATO ServerCloud account, with hardware, image, IP, and status details.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Server ID.",
            "cloudpanel_id": "Public identifier shown in the CloudPanel, used when contacting support.",
            "name": "Server name.",
            "server_type": "Server type.",
            "description": "Server description.",
            "creation_date": "Date when the server was created.",
            "ssh_password": "True when server access through an SSH password is enabled.",
            "status": "Server state.",
            "datacenter": "Data center where the server is located.",
            "hardware": "Hardware features of the server, including vCores, RAM, and HDDs.",
            "image": "Image installed on the server.",
            "dvd": "DVD loaded into the server, if any.",
            "snapshot": "Information about the server's snapshot, if any.",
            "ips": "IPs assigned to the server.",
            "alerts": "Server alerts.",
            "monitoring_policy": "Monitoring policy assigned to the server.",
            "private_networks": "Private networks the server is added to.",
        },
    },
    "Snapshots": {
        "description": "Snapshots of each cloud server.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Snapshot ID.",
            "server_id": "ID of the server the snapshot belongs to.",
            "creation_date": "Date when the snapshot was created.",
        },
    },
    "Images": {
        "description": "Server images, including operating system details and backup frequency.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Image ID.",
            "name": "Image name.",
            "datacenter": "Data center where the image is available.",
            "os_family": "Operating system family.",
            "os": "Operating system version.",
            "os_version": "Operating system distribution.",
            "os_architecture": "Hardware architecture required for the selected OS.",
            "os_image_type": "Operating system image type.",
            "type": "Image type.",
            "min_hdd_size": "Minimum required HDD size.",
            "licenses": "Licenses acquired for the image.",
            "state": "Image state.",
            "description": "Image description.",
            "hdds": "HDDs of the image.",
            "server_id": "ID of the server that is the source of the image.",
            "frequency": "Frequency with which the image is made.",
            "num_images": "Maximum number of images that will be stored.",
            "creation_date": "Date when the image was created.",
        },
    },
    "BlockStorages": {
        "description": "Block storage volumes and the server each one is attached to.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Block storage ID.",
            "size": "Block storage total size.",
            "state": "Block storage state.",
            "description": "Block storage description.",
            "datacenter": "Data center where the block storage is available.",
            "name": "Block storage name.",
            "creation_date": "Date when the block storage was created.",
            "server": "Server the block storage is attached to.",
        },
    },
    "SharedStorages": {
        "description": "Shared storage volumes with CIFS/NFS paths and attached servers.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Shared storage ID.",
            "size": "Shared storage total size.",
            "state": "Shared storage status.",
            "description": "Shared storage description.",
            "datacenter": "Data center where the shared storage is available.",
            "size_used": "Size used of the shared storage, as a percentage.",
            "cifs_path": "CIFS path for accessing the shared storage from Windows systems.",
            "nfs_path": "NFS path for accessing the shared storage from UNIX systems.",
            "name": "Shared storage name.",
            "creation_date": "Date when the shared storage was created.",
            "servers": "Servers with access to the shared storage.",
        },
    },
    "FirewallPolicies": {
        "description": "Firewall policies with their rules and the server IPs they are assigned to.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Firewall policy ID.",
            "name": "Firewall policy name.",
            "description": "Firewall policy description.",
            "state": "Firewall policy state.",
            "creation_date": "Date when the firewall policy was created.",
            "default": "1 when this is a default panel firewall policy.",
            "rules": "Firewall policy rules.",
            "server_ips": "Server IPs assigned to the firewall policy.",
        },
    },
    "LoadBalancers": {
        "description": "Load balancers with health check settings, rules, and assigned server IPs.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Load balancer ID.",
            "name": "Load balancer name.",
            "state": "Load balancer status.",
            "creation_date": "Date when the load balancer was created.",
            "description": "Load balancer description.",
            "ip": "Load balancer IP.",
            "health_check_test": "Type of health check.",
            "health_check_interval": "Health check period.",
            "health_check_path": "URL to call for checking.",
            "health_check_path_parser": "Regular expression to check the health check response against.",
            "persistence": "Whether session persistence is enabled.",
            "persistence_time": "Persistence time.",
            "method": "Balancing procedure.",
            "datacenter": "Data center where the load balancer is available.",
            "rules": "Load balancer rules.",
            "server_ips": "Server IPs assigned to the load balancer.",
        },
    },
    "PublicIps": {
        "description": "Public IP addresses and the resource each one is assigned to.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "IP ID.",
            "ip": "The IP address.",
            "type": "Type of IP (currently only IPv4 is available).",
            "datacenter": "Data center where the IP is available.",
            "assigned_to": "Resource the IP is assigned to.",
            "reverse_dns": "Reverse DNS name.",
            "is_dhcp": "True when the IP is assigned using DHCP.",
            "state": "IP status.",
            "creation_date": "Date when the IP was created.",
        },
    },
    "PrivateNetworks": {
        "description": "Private networks and the servers assigned to each one.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Private network ID.",
            "name": "Private network name.",
            "description": "Private network description.",
            "datacenter": "Data center where the private network is available.",
            "network_address": "Network address.",
            "subnet_mask": "Subnet mask.",
            "state": "State of the private network.",
            "creation_date": "Date when the private network was created.",
            "servers": "Servers assigned to the private network.",
        },
    },
    "Vpns": {
        "description": "VPNs configured in the account.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "VPN ID.",
            "name": "VPN name.",
            "description": "VPN description.",
            "state": "VPN status.",
            "datacenter": "Data center where the VPN is available.",
            "type": "VPN type.",
            "ips": "VPN IPs.",
            "creation_date": "Date when the VPN was created.",
        },
    },
    "MonitoringPolicies": {
        "description": "Monitoring policies with thresholds, monitored ports and processes, and assigned servers.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Monitoring policy ID.",
            "name": "Monitoring policy name.",
            "description": "Monitoring policy description.",
            "default": "1 when this is a default policy.",
            "state": "Monitoring policy status.",
            "creation_date": "Date when the monitoring policy was created.",
            "email": "Email address that receives notifications.",
            "agent": "True when the monitoring agent will be installed.",
            "servers": "Servers assigned to the monitoring policy.",
            "thresholds": "Monitoring thresholds.",
            "ports": "Ports that will be monitored.",
            "processes": "Processes that will be monitored.",
        },
    },
    "SshKeys": {
        "description": "SSH public keys registered in the account and the servers using them.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "SSH key ID.",
            "name": "SSH key name.",
            "description": "SSH key description.",
            "state": "SSH key state.",
            "servers": "Servers using the SSH key.",
            "md5": "MD5 fingerprint of the SSH key.",
            "public_key": "The SSH public key.",
            "creation_date": "Date when the SSH key was created.",
        },
    },
    "Users": {
        "description": "CloudPanel users with their roles and API access settings. The API key itself is removed before rows are stored.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "User ID.",
            "name": "User name.",
            "description": "User description.",
            "email": "User email address.",
            "state": "User status.",
            "creation_date": "Date when the user was created.",
            "api": "API access settings for the user (active flag and allowed IPs; the key is removed).",
            "roles": "Role the user belongs to.",
        },
    },
    "Roles": {
        "description": "CloudPanel roles with their permissions and assigned users.",
        "docs_url": _DOCS_URL,
        "columns": {
            "id": "Role ID.",
            "name": "Role name.",
            "description": "Role description.",
            "state": "Role status.",
            "default": "1 when this is a default panel role.",
            "creation_date": "Date when the role was created.",
            "users": "Users assigned to the role.",
            "permissions": "Actions allowed for the role.",
        },
    },
}
