import { MakeLogicType, actions, connect, kea, path, reducers, selectors } from 'kea'

import {
    MarketingAnalyticsAttributionBreakdown,
    MarketingAnalyticsRetentionInterval,
    MarketingAnalyticsRetentionQuery,
    NodeKind,
} from '~/queries/schema/schema-general'
import { IntervalType } from '~/types'

import { marketingAnalyticsLogic } from './marketingAnalyticsLogic'

/** Keeps the tab's refresh button off the dashboard tiles, which sit in the scene-level collection. */
export const MARKETING_ANALYTICS_RETENTION_COLLECTION_ID = 'marketing-analytics-retention'

export const DEFAULT_TOTAL_INTERVALS: number = 8

export const RETENTION_INTERVAL_LABELS: Record<MarketingAnalyticsRetentionInterval, string> = {
    [MarketingAnalyticsRetentionInterval.Day]: 'Daily',
    [MarketingAnalyticsRetentionInterval.Week]: 'Weekly',
    [MarketingAnalyticsRetentionInterval.Month]: 'Monthly',
}

interface DateFilter {
    dateFrom: string | null
    dateTo: string | null
    interval: IntervalType
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface marketingRetentionLogicValues {
    dateFilter: {
        dateFrom: string | null
        dateTo: string | null
        interval: IntervalType
    } // marketingAnalyticsLogic
    breakdownBy: MarketingAnalyticsAttributionBreakdown
    excludeDirectTraffic: boolean
    excludeUnattributed: boolean
    onlyNewUsers: boolean
    optionsOpen: boolean
    query: MarketingAnalyticsRetentionQuery
    retentionInterval: MarketingAnalyticsRetentionInterval
    totalIntervals: number
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface marketingRetentionLogicActions {
    setBreakdownBy: (breakdownBy: MarketingAnalyticsAttributionBreakdown) => {
        breakdownBy: MarketingAnalyticsAttributionBreakdown
    }
    setExcludeDirectTraffic: (excludeDirectTraffic: boolean) => {
        excludeDirectTraffic: boolean
    }
    setExcludeUnattributed: (excludeUnattributed: boolean) => {
        excludeUnattributed: boolean
    }
    setOnlyNewUsers: (onlyNewUsers: boolean) => {
        onlyNewUsers: boolean
    }
    setOptionsOpen: (optionsOpen: boolean) => {
        optionsOpen: boolean
    }
    setRetentionInterval: (retentionInterval: MarketingAnalyticsRetentionInterval) => {
        retentionInterval: MarketingAnalyticsRetentionInterval
    }
    setTotalIntervals: (totalIntervals: number) => {
        totalIntervals: number
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface marketingRetentionLogicMeta {
    __keaTypeGenInternalSelectorTypes: {
        query: (
            breakdownBy: MarketingAnalyticsAttributionBreakdown,
            retentionInterval: MarketingAnalyticsRetentionInterval,
            totalIntervals: number,
            excludeDirectTraffic: boolean,
            excludeUnattributed: boolean,
            onlyNewUsers: boolean,
            dateFilter: {
                dateFrom: string | null
                dateTo: string | null
                interval: IntervalType
            }
        ) => MarketingAnalyticsRetentionQuery
    }
}

export type marketingRetentionLogicType = MakeLogicType<
    marketingRetentionLogicValues,
    marketingRetentionLogicActions,
    Record<string, any>,
    marketingRetentionLogicMeta
>

export const marketingRetentionLogic = kea<marketingRetentionLogicType>([
    path(['scenes', 'webAnalytics', 'marketingRetentionLogic']),
    connect(() => ({
        values: [marketingAnalyticsLogic, ['dateFilter']],
    })),
    actions({
        setBreakdownBy: (breakdownBy: MarketingAnalyticsAttributionBreakdown) => ({ breakdownBy }),
        setRetentionInterval: (retentionInterval: MarketingAnalyticsRetentionInterval) => ({ retentionInterval }),
        setTotalIntervals: (totalIntervals: number) => ({ totalIntervals }),
        setExcludeDirectTraffic: (excludeDirectTraffic: boolean) => ({ excludeDirectTraffic }),
        setExcludeUnattributed: (excludeUnattributed: boolean) => ({ excludeUnattributed }),
        setOnlyNewUsers: (onlyNewUsers: boolean) => ({ onlyNewUsers }),
        setOptionsOpen: (optionsOpen: boolean) => ({ optionsOpen }),
    }),
    reducers({
        breakdownBy: [
            MarketingAnalyticsAttributionBreakdown.Channel as MarketingAnalyticsAttributionBreakdown,
            { setBreakdownBy: (_, { breakdownBy }) => breakdownBy },
        ],
        retentionInterval: [
            MarketingAnalyticsRetentionInterval.Week as MarketingAnalyticsRetentionInterval,
            { setRetentionInterval: (_, { retentionInterval }) => retentionInterval },
        ],
        totalIntervals: [DEFAULT_TOTAL_INTERVALS, { setTotalIntervals: (_, { totalIntervals }) => totalIntervals }],
        excludeDirectTraffic: [
            false,
            { setExcludeDirectTraffic: (_, { excludeDirectTraffic }) => excludeDirectTraffic },
        ],
        excludeUnattributed: [false, { setExcludeUnattributed: (_, { excludeUnattributed }) => excludeUnattributed }],
        // Defaults on: without it a channel's cohorts are inflated by the users it acquired long ago.
        onlyNewUsers: [true, { setOnlyNewUsers: (_, { onlyNewUsers }) => onlyNewUsers }],
        optionsOpen: [false, { setOptionsOpen: (_, { optionsOpen }) => optionsOpen }],
    }),
    selectors({
        query: [
            (s) => [
                s.breakdownBy,
                s.retentionInterval,
                s.totalIntervals,
                s.excludeDirectTraffic,
                s.excludeUnattributed,
                s.onlyNewUsers,
                s.dateFilter,
            ],
            (
                breakdownBy: MarketingAnalyticsAttributionBreakdown,
                retentionInterval: MarketingAnalyticsRetentionInterval,
                totalIntervals: number,
                excludeDirectTraffic: boolean,
                excludeUnattributed: boolean,
                onlyNewUsers: boolean,
                dateFilter: DateFilter
            ): MarketingAnalyticsRetentionQuery => ({
                kind: NodeKind.MarketingAnalyticsRetentionQuery,
                dateRange: { date_from: dateFilter.dateFrom, date_to: dateFilter.dateTo },
                breakdownBy,
                retentionInterval,
                totalIntervals,
                excludeDirectTraffic,
                excludeUnattributed,
                onlyNewUsers,
                properties: [],
            }),
        ],
    }),
])
