from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "announcement_categories": {
        "description": "A category used to group and label announcements (e.g. New, Improvement, Fix).",
        "docs_url": "https://developers.frill.co/api/reference/announcement-categories",
        "columns": {
            "id": "Category ID.",
            "idx": "Encoded category ID — the unique identifier used across the Frill API.",
            "name": "Category name.",
            "color": "Hex RGB color code displayed in the app.",
            "company_id": "Company ID the category belongs to.",
            "created_at": "The date and time the category was created (UTC).",
            "updated_at": "The date and time the category was last updated (UTC).",
            "translations": "Localized category names.",
        },
    },
    "announcements": {
        "description": "A product announcement (changelog entry) published to your Frill announcements feed.",
        "docs_url": "https://developers.frill.co/api/reference/announcements",
        "columns": {
            "idx": "A unique identifier for the announcement.",
            "name": "Name of the announcement.",
            "slug": "The URL slug of the announcement.",
            "excerpt": "Short textual description of the announcement.",
            "content": "Content of the announcement (as Markdown).",
            "content_html": "Content of the announcement (as HTML).",
            "reaction_count": "Reactions to the announcement.",
            "is_published": "Indicates if the announcement is published or not.",
            "published_at": "The date and time the announcement was published (UTC), or null if still in draft.",
            "created_at": "The date and time the announcement was created (UTC).",
            "updated_at": "The date and time the announcement was last updated (UTC).",
            "author": "Author of this announcement.",
            "categories": "Categories associated with this announcement.",
            "ideas": "Ideas associated with this announcement.",
        },
    },
    "comments": {
        "description": "A public comment or internal note left on an idea.",
        "docs_url": "https://developers.frill.co/api/reference/comments",
        "columns": {
            "idx": "A unique identifier for the comment.",
            "message": "The raw message content of the comment.",
            "content": "Structured content as a JSON array (similar to Slate.js/ProseMirror format).",
            "content_html": "Content rendered as HTML.",
            "content_markdown": "Content rendered as Markdown.",
            "is_private": "Indicates if the comment is private (note) or public (comment).",
            "type": "Type of comment (comment or note).",
            "created_at": "The date and time the comment was created (UTC).",
            "updated_at": "The date and time the comment was last updated (UTC).",
            "follower": "Author of this comment.",
            "idea_id": "ID of the associated idea.",
            "attachments": "Files and images attached to this comment.",
            "_idea_idx": "Unique identifier (idx) of the parent idea, injected during sync for joining to the ideas table.",
        },
    },
    "followers": {
        "description": "A person who follows, votes on, or comments on ideas in your Frill workspace.",
        "docs_url": "https://developers.frill.co/api/reference/followers",
        "columns": {
            "idx": "A unique identifier for the follower.",
            "name": "Name of the follower.",
            "email": "Email address of the follower.",
            "avatar": "Profile image of the follower (URL).",
            "attributes": "Custom attributes for the follower.",
            "companies": "Companies the follower is associated with.",
            "created_at": "The date and time the follower was created (UTC).",
            "updated_at": "The date and time the follower was last updated (UTC).",
        },
    },
    "ideas": {
        "description": "A feature request or piece of feedback submitted to your Frill workspace, with vote and comment counts.",
        "docs_url": "https://developers.frill.co/api/reference/ideas",
        "columns": {
            "idx": "A unique identifier for the idea.",
            "name": "The name of the idea.",
            "slug": "The URL slug of the idea.",
            "excerpt": "A short excerpt or summary of the idea.",
            "description": "The text description of the idea (legacy field; use content fields for structured data).",
            "content": "Structured content as a JSON array (similar to Slate.js/ProseMirror format).",
            "content_html": "Content rendered as HTML.",
            "content_markdown": "Content rendered as Markdown.",
            "cover_image": "URL of the image displayed as the cover on the roadmap view.",
            "vote_count": "Number of votes this idea has received.",
            "comment_count": "Number of comments on this idea.",
            "note_count": "Number of internal notes on this idea.",
            "is_pined": "Has the idea been pinned to the top.",
            "is_bug": "Denotes if this idea is a bug.",
            "is_archived": "Denotes if this idea has been archived.",
            "is_completed": "Denotes if this idea is considered completed / finished.",
            "show_in_roadmap": "Should the idea be displayed in the roadmap view.",
            "approval_status": "The approval status of the idea: approved, needs-approval, or rejected.",
            "created_at": "The date and time the idea was created (UTC).",
            "updated_at": "The date and time the idea was last updated (UTC).",
            "author": "Author of the idea.",
            "status": "Status of the idea.",
            "topics": "Topics associated with the idea.",
            "attachments": "Files and images attached to this idea.",
        },
    },
    "statuses": {
        "description": "A workflow status ideas move through on the roadmap (e.g. Planned, In Progress, Shipped).",
        "docs_url": "https://developers.frill.co/api/reference/statuses",
        "columns": {
            "idx": "A unique identifier for the status.",
            "name": "Name of the status.",
            "color": "Color associated with the status (displayed in the app).",
        },
    },
    "topics": {
        "description": "A topic (tag) used to group and filter ideas.",
        "docs_url": "https://developers.frill.co/api/reference/topics",
        "columns": {
            "idx": "A unique identifier for the topic.",
            "name": "Name of the topic.",
            "idea_count": "Number of ideas that have been tagged with this topic.",
            "order": "The position of the topic in the topic list.",
        },
    },
    "votes": {
        "description": "A single vote cast by a follower on an idea.",
        "docs_url": "https://developers.frill.co/api/reference/votes",
        "columns": {
            "idx": "A unique identifier for the vote.",
            "created_at": "The date and time the vote was created (UTC).",
            "voter": "The user this vote is associated with.",
            "idea": "The idea this vote is associated with.",
        },
    },
}
