from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Descriptions sourced from the Humanitix Public API docs (https://api.humanitix.com/v1/documentation).
# Partial coverage is fine — uncovered columns fall back to LLM enrichment.
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "events": {
        "description": "A Humanitix event — a ticketed event with its dates, location, capacity, and publishing state.",
        "docs_url": "https://humanitix.stoplight.io/docs/humanitix-public-api/476881e4b5d55-get-events",
        "columns": {
            "_id": "The unique ID of the event.",
            "userId": "The ID of the user that owns the event.",
            "name": "The name of the event.",
            "description": "The event description.",
            "slug": "The URL slug of the event.",
            "dates": "The event's date ranges, each with a start and end time.",
            "startDate": "The start date and time of the event.",
            "endDate": "The end date and time of the event.",
            "timezone": "The IANA timezone the event dates are expressed in.",
            "location": "The event's location as an ISO 3166-1 alpha-2 country code.",
            "eventLocation": "The venue details for the event (address, coordinates, and venue type).",
            "totalCapacity": "The maximum number of attendees the event can hold.",
            "currency": "The currency code used for ticket pricing.",
            "published": "Whether the event is published.",
            "public": "Whether the event is publicly visible.",
            "classification": "The event's type and category classification.",
            "ticketTypes": "The ticket types configured for the event.",
            "createdAt": "The date and time the event was created.",
            "updatedAt": "The date and time the event was last modified.",
        },
    },
    "tags": {
        "description": "A Humanitix tag — a label used to group and organise events in an account.",
        "docs_url": "https://api.humanitix.com/v1/documentation",
        "columns": {
            "_id": "The unique ID of the tag.",
            "name": "The display name of the tag.",
            "userId": "The ID of the user that owns the tag.",
            "location": "The tag's location as an ISO 3166-1 alpha-2 country code.",
            "createdAt": "The date and time the tag was created.",
            "updatedAt": "The date and time the tag was last modified.",
        },
    },
    "orders": {
        "description": "A Humanitix order — one checkout for an event, with the buyer's details, payment, and revenue totals.",
        "docs_url": "https://api.humanitix.com/v1/documentation",
        "columns": {
            "_id": "The unique ID of the order.",
            "eventId": "The ID of the event the order is for.",
            "eventDateId": "The ID of the event date (occurrence) the order is for.",
            "userId": "The ID of the user that owns the event.",
            "currency": "The currency code the order was paid in.",
            "status": "The status of the order.",
            "financialStatus": "The payment state of the order: free, paid, partially refunded, or refunded.",
            "firstName": "The buyer's first name.",
            "lastName": "The buyer's last name.",
            "email": "The buyer's email address.",
            "mobile": "The buyer's mobile number.",
            "organisation": "The buyer's organisation.",
            "discounts": "The automatic discount or discount code applied to the order.",
            "paymentType": "The payment type used for the order.",
            "paymentGateway": "The payment gateway that processed the order.",
            "manualOrder": "Whether the order was created manually by the organizer.",
            "salesChannel": "The channel the order came through: an online sale or a manual order.",
            "totals": "The order's financial breakdown (subtotal, fees, taxes, discounts, refunds, net and gross sales, total).",
            "purchaseTotals": "The order's financial breakdown at the time of purchase, before any later changes.",
            "additionalFields": "Answers to the custom checkout questions for the order.",
            "completedAt": "The date and time the order was completed.",
            "incompleteAt": "The date and time the order was marked incomplete.",
            "location": "The region the order is stored in, as an ISO 3166-1 alpha-2 country code.",
            "createdAt": "The date and time the order was created.",
            "updatedAt": "The date and time the order was last modified.",
        },
    },
    "tickets": {
        "description": "A Humanitix ticket — one issued ticket within an order, with its attendee, price, and check-in state.",
        "docs_url": "https://api.humanitix.com/v1/documentation",
        "columns": {
            "_id": "The unique ID of the ticket.",
            "eventId": "The ID of the event the ticket is for.",
            "eventDateId": "The ID of the event date (occurrence) the ticket is for.",
            "orderId": "The ID of the order the ticket belongs to.",
            "orderName": "The human-readable reference of the order the ticket belongs to.",
            "currency": "The currency code the ticket was priced in.",
            "firstName": "The attendee's first name.",
            "lastName": "The attendee's last name.",
            "ticketTypeId": "The ID of the ticket type.",
            "ticketTypeName": "The name of the ticket type.",
            "price": "The ticket price.",
            "discount": "The discount applied to the ticket.",
            "netPrice": "The ticket price after discounts.",
            "taxes": "The taxes charged on the ticket.",
            "fee": "The booking fee charged on the ticket.",
            "total": "The total charged for the ticket.",
            "status": "The status of the ticket: complete or cancelled.",
            "checkIn": "The ticket's current check-in state, with the check-in time and the user that checked it in.",
            "checkInHistory": "Every check-in and check-out recorded for the ticket.",
            "cancelledAt": "The date and time the ticket was cancelled.",
            "salesChannel": "The channel the ticket came through: an online sale or a manual order.",
            "attendeeProfileId": "The ID of the attendee profile linked to the ticket.",
            "location": "The region the ticket is stored in, as an ISO 3166-1 alpha-2 country code.",
            "createdAt": "The date and time the ticket was created.",
            "updatedAt": "The date and time the ticket was last modified.",
        },
    },
}
