import {
    RecurrenceIntervalEnumApi,
    ResourceTypeEnumApi,
    SubscriptionDeliveryStatusEnumApi,
    TargetTypeEnumApi,
    type SubscriptionApi,
    type SubscriptionDeliveryApi,
} from 'products/subscriptions/frontend/generated/api.schemas'

export const MOCK_SUBSCRIPTION_USER = {
    id: 1,
    uuid: '01863799-062b-0000-8a61-b2842d5f8642',
    email: 'matt@posthog.com',
    first_name: 'Matt',
    last_name: 'P',
    hedgehog_config: null,
} as const

export const MOCK_SUBSCRIPTION_INSIGHT: SubscriptionApi = {
    id: 1,
    resource_type: ResourceTypeEnumApi.Insight,
    insight: 101,
    dashboard: null,
    insight_short_id: 'abc123',
    resource_name: 'North star metric',
    title: 'Weekly rollup',
    dashboard_export_insights: [],
    target_type: TargetTypeEnumApi.Email,
    target_value: 'matt.p@posthog.com',
    frequency: RecurrenceIntervalEnumApi.Weekly,
    interval: 1,
    start_date: '2022-01-01T00:00:00Z',
    created_at: '2023-04-27T10:04:37.977401Z',
    created_by: MOCK_SUBSCRIPTION_USER,
    summary: 'sent every week',
    next_delivery_date: '2026-04-07T17:00:00Z',
    deleted: false,
    enabled: true,
}

/** Insight subscription with several email recipients so Resource shows the type label, not the long name. */
export const MOCK_SUBSCRIPTION_INSIGHT_MANY_DESTINATIONS: SubscriptionApi = {
    ...MOCK_SUBSCRIPTION_INSIGHT,
    id: 3,
    target_value: 'rollups@posthog.com, exec@posthog.com, analytics@posthog.com, oncall@posthog.com',
    resource_name: 'North star metric — executive weekly rollup with a very long resource title',
    title: 'Multi-recipient insight digest',
}

export const MOCK_SUBSCRIPTION_DASHBOARD: SubscriptionApi = {
    id: 2,
    resource_type: ResourceTypeEnumApi.Dashboard,
    insight: null,
    dashboard: 501,
    insight_short_id: null,
    resource_name: 'Company overview',
    title: 'Dashboard digest',
    dashboard_export_insights: [101],
    target_type: TargetTypeEnumApi.Slack,
    target_value: 'C12345|#alerts-analytics-platform',
    frequency: RecurrenceIntervalEnumApi.Daily,
    interval: 1,
    start_date: '2022-01-01T00:00:00Z',
    created_at: '2023-04-27T10:04:37.977401Z',
    created_by: MOCK_SUBSCRIPTION_USER,
    summary: 'sent every day',
    next_delivery_date: '2026-04-08T09:00:00Z',
    deleted: false,
    enabled: true,
    integration_id: 1,
}

/** Dashboard subscription with several Slack channels. */
export const MOCK_SUBSCRIPTION_DASHBOARD_MANY_DESTINATIONS: SubscriptionApi = {
    ...MOCK_SUBSCRIPTION_DASHBOARD,
    id: 4,
    target_value: 'C111|#team-a, C222|#team-b, C333|#team-c',
    resource_name: 'Company overview — all-hands dashboard export',
    title: 'Multi-channel dashboard digest',
}

export const MOCK_SUBSCRIPTION_DELIVERIES: SubscriptionDeliveryApi[] = [
    {
        id: 'del-starting',
        subscription: 1,
        temporal_workflow_id: 'wf-starting',
        idempotency_key: 'idem-starting',
        trigger_type: 'manual',
        scheduled_at: null,
        target_type: 'email',
        target_value: 'matt.p@posthog.com',
        exported_asset_ids: [],
        content_snapshot: {},
        ai_report: null,
        ai_report_diagnostics: null,
        ai_report_prompt: null,
        recipient_results: [],
        status: SubscriptionDeliveryStatusEnumApi.Starting,
        error: null,
        change_summary: null,
        created_at: '2026-04-07T10:05:00Z',
        last_updated_at: '2026-04-07T10:05:02Z',
        finished_at: null,
    },
    {
        // AI-prompt delivery: the delivered report markdown, the prompt it was generated from, and the
        // per-query diagnostics (one failed) ship via the typed fields, gated behind query:viewer (the
        // backend scrubs them to null and content_snapshot to {} otherwise). content_snapshot no longer
        // carries the AI keys — the typed fields are the contract. The report embeds an off-PostHog image so
        // the (pre-expanded) story exercises disableImages: it must render as a link, never an auto-loading <img>.
        id: 'del-ai-report',
        subscription: 1,
        temporal_workflow_id: 'wf-ai-report',
        idempotency_key: 'idem-ai-report',
        trigger_type: 'manual',
        scheduled_at: null,
        target_type: 'email',
        target_value: 'matt.p@posthog.com',
        exported_asset_ids: [],
        content_snapshot: {},
        ai_report:
            '## Weekly Hedgebox report\n\n| Metric | Value |\n| --- | --- |\n| Daily active users | 89 |\n| New signups | 56 |\n| File uploads | 429 |\n| File downloads | 324 |\n\nEngagement is up week-over-week, led by uploads.\n\n![Trend chart](https://example.com/trend.png)',
        ai_report_prompt:
            'Summarize weekly Hedgebox engagement: daily active users, new signups, file uploads and downloads, and call out any week-over-week movement.',
        ai_report_diagnostics: [
            {
                description: 'Daily active users (7-day total)',
                hogql: 'SELECT count(DISTINCT person_id) AS dau FROM events WHERE timestamp >= now() - INTERVAL 7 DAY',
                ok: true,
                error_type: null,
                human_readable_error: null,
            },
            {
                description: 'New signups',
                hogql: "SELECT count() AS signups FROM events WHERE event = 'signed_up' AND timestamp >= now() - INTERVAL 7 DAY",
                ok: true,
                error_type: null,
                human_readable_error: null,
            },
            {
                description: 'First-ever signups per user',
                hogql: 'SELECT first_ever(event) OVER (PARTITION BY person_id) FROM events',
                ok: false,
                error_type: 'ExposedHogQLError',
                human_readable_error: "Unknown function: 'first_ever'",
            },
        ],
        recipient_results: [],
        status: SubscriptionDeliveryStatusEnumApi.Completed,
        error: null,
        change_summary: null,
        created_at: '2026-04-07T09:30:00Z',
        last_updated_at: '2026-04-07T09:30:20Z',
        finished_at: '2026-04-07T09:30:22Z',
    },
    {
        id: 'del-1',
        subscription: 1,
        temporal_workflow_id: 'wf-1',
        idempotency_key: 'idem-1',
        trigger_type: 'scheduled',
        scheduled_at: '2026-04-06T17:00:00Z',
        target_type: 'email',
        target_value:
            'matt.p@posthog.com, rollups@posthog.com, exec@posthog.com, analytics@posthog.com, oncall@posthog.com',
        exported_asset_ids: [],
        content_snapshot: {},
        ai_report: null,
        ai_report_diagnostics: null,
        ai_report_prompt: null,
        recipient_results: [],
        status: SubscriptionDeliveryStatusEnumApi.Completed,
        error: null,
        change_summary:
            'Weekly rollup held steady — north star metric is up 3% week-over-week, within the normal band. Enable "Compare to previous period" to make the weekly delta easier to eyeball.',
        created_at: '2026-04-06T17:00:05Z',
        last_updated_at: '2026-04-06T17:00:10Z',
        finished_at: '2026-04-06T17:00:12Z',
    },
    {
        id: 'del-skipped',
        subscription: 1,
        temporal_workflow_id: 'wf-skipped',
        idempotency_key: 'idem-skipped',
        trigger_type: 'scheduled',
        scheduled_at: '2026-04-06T09:00:00Z',
        target_type: 'email',
        target_value: 'matt.p@posthog.com',
        exported_asset_ids: [],
        content_snapshot: {},
        ai_report: null,
        ai_report_diagnostics: null,
        ai_report_prompt: null,
        recipient_results: [],
        status: SubscriptionDeliveryStatusEnumApi.Skipped,
        error: null,
        change_summary: null,
        created_at: '2026-04-06T09:00:01Z',
        last_updated_at: '2026-04-06T09:00:02Z',
        finished_at: '2026-04-06T09:00:02Z',
    },
    {
        id: 'del-2',
        subscription: 1,
        temporal_workflow_id: 'wf-2',
        idempotency_key: 'idem-2',
        trigger_type: 'manual',
        scheduled_at: null,
        target_type: 'email',
        target_value: 'matt.p@posthog.com',
        exported_asset_ids: [],
        content_snapshot: {},
        ai_report: null,
        ai_report_diagnostics: null,
        ai_report_prompt: null,
        recipient_results: [],
        status: SubscriptionDeliveryStatusEnumApi.Failed,
        error: { message: 'SMTP timeout' },
        change_summary: null,
        created_at: '2026-04-05T09:00:00Z',
        last_updated_at: '2026-04-05T09:00:30Z',
        finished_at: '2026-04-05T09:00:30Z',
    },
    {
        id: 'del-slack',
        subscription: 1,
        temporal_workflow_id: 'wf-slack',
        idempotency_key: 'idem-slack',
        trigger_type: 'scheduled',
        scheduled_at: '2026-04-04T14:00:00Z',
        target_type: 'slack',
        target_value: 'C12345|#alerts-analytics-platform',
        exported_asset_ids: [1, 2],
        content_snapshot: {},
        ai_report: null,
        ai_report_diagnostics: null,
        ai_report_prompt: null,
        recipient_results: [],
        status: SubscriptionDeliveryStatusEnumApi.Completed,
        error: null,
        change_summary:
            'Dashboard digest: signups rose 12% on the back of a referral push on Monday; error rate stable inside its usual range.',
        created_at: '2026-04-04T14:00:03Z',
        last_updated_at: '2026-04-04T14:00:08Z',
        finished_at: '2026-04-04T14:00:10Z',
    },
    {
        id: 'del-webhook',
        subscription: 1,
        temporal_workflow_id: 'wf-webhook',
        idempotency_key: 'idem-webhook',
        trigger_type: 'target_change',
        scheduled_at: null,
        target_type: 'webhook',
        target_value: 'https://hooks.example.com/subscription/abc',
        exported_asset_ids: [],
        content_snapshot: {},
        ai_report: null,
        ai_report_diagnostics: null,
        ai_report_prompt: null,
        recipient_results: [],
        status: SubscriptionDeliveryStatusEnumApi.Failed,
        error: { message: 'HTTP 502 from webhook' },
        change_summary: null,
        created_at: '2026-04-03T11:20:00Z',
        last_updated_at: '2026-04-03T11:21:00Z',
        finished_at: '2026-04-03T11:21:00Z',
    },
    {
        id: 'del-manual-ok',
        subscription: 1,
        temporal_workflow_id: 'wf-manual-ok',
        idempotency_key: 'idem-manual-ok',
        trigger_type: 'manual',
        scheduled_at: null,
        target_type: 'email',
        target_value: 'matt.p@posthog.com, qa@posthog.com',
        exported_asset_ids: [],
        content_snapshot: {},
        ai_report: null,
        ai_report_diagnostics: null,
        ai_report_prompt: null,
        recipient_results: [],
        status: SubscriptionDeliveryStatusEnumApi.Completed,
        error: null,
        change_summary: 'Manual test delivery — same shape as yesterday, no regressions to call out.',
        created_at: '2026-04-01T16:45:00Z',
        last_updated_at: '2026-04-01T16:45:20Z',
        finished_at: '2026-04-01T16:45:22Z',
    },
    {
        id: 'del-sched-old',
        subscription: 1,
        temporal_workflow_id: 'wf-sched-old',
        idempotency_key: 'idem-sched-old',
        trigger_type: 'scheduled',
        scheduled_at: '2026-03-28T17:00:00Z',
        target_type: 'email',
        target_value: 'matt.p@posthog.com',
        exported_asset_ids: [],
        content_snapshot: {},
        ai_report: null,
        ai_report_diagnostics: null,
        ai_report_prompt: null,
        recipient_results: [],
        status: SubscriptionDeliveryStatusEnumApi.Completed,
        error: null,
        change_summary: null,
        created_at: '2026-03-28T17:00:02Z',
        last_updated_at: '2026-03-28T17:00:15Z',
        finished_at: '2026-03-28T17:00:18Z',
    },
    {
        id: 'del-sched-fail',
        subscription: 1,
        temporal_workflow_id: 'wf-sched-fail',
        idempotency_key: 'idem-sched-fail',
        trigger_type: 'scheduled',
        scheduled_at: '2026-03-21T17:00:00Z',
        target_type: 'email',
        target_value: 'matt.p@posthog.com',
        exported_asset_ids: [],
        content_snapshot: {},
        ai_report: null,
        ai_report_diagnostics: null,
        ai_report_prompt: null,
        recipient_results: [],
        status: SubscriptionDeliveryStatusEnumApi.Failed,
        error: { message: 'Export timed out' },
        change_summary: null,
        created_at: '2026-03-21T17:00:01Z',
        last_updated_at: '2026-03-21T17:05:00Z',
        finished_at: '2026-03-21T17:05:00Z',
    },
    {
        id: 'del-ancient',
        subscription: 1,
        temporal_workflow_id: 'wf-ancient',
        idempotency_key: 'idem-ancient',
        trigger_type: 'scheduled',
        scheduled_at: '2026-03-14T17:00:00Z',
        target_type: 'email',
        target_value: 'matt.p@posthog.com',
        exported_asset_ids: [],
        content_snapshot: {},
        ai_report: null,
        ai_report_diagnostics: null,
        ai_report_prompt: null,
        recipient_results: [],
        status: SubscriptionDeliveryStatusEnumApi.Completed,
        error: null,
        change_summary: null,
        created_at: '2026-03-14T17:00:04Z',
        last_updated_at: '2026-03-14T17:00:30Z',
        finished_at: '2026-03-14T17:00:35Z',
    },
]
