from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "stacks": {
        "description": "Infrastructure-as-code stacks: the core unit tying a VCS repository to Terraform/OpenTofu/Pulumi state, with current status and drift information.",
        "docs_url": "https://docs.spacelift.io/concepts/stack/",
        "columns": {
            "id": "Unique identifier (slug) of the stack.",
            "name": "Human-readable name of the stack.",
            "administrative": "Whether the stack has administrative permissions on the Spacelift account.",
            "api_host": "API host the stack's VCS provider is served from.",
            "branch": "VCS branch the stack tracks.",
            "created_at": "Unix timestamp (seconds) when the stack was created.",
            "deleted": "Whether the stack has been deleted.",
            "deleting": "Whether the stack is currently being deleted.",
            "description": "Free-form description of the stack.",
            "is_drifted": "Whether drift detection found the live infrastructure differing from the desired state.",
            "labels": "Labels attached to the stack.",
            "locked_at": "Unix timestamp (seconds) when the stack was locked, if locked.",
            "locked_by": "Username that locked the stack, if locked.",
            "manages_state_file": "Whether Spacelift manages the stack's Terraform state file.",
            "namespace": "VCS namespace (organization or user) of the stack's repository.",
            "project_root": "Directory inside the repository the stack operates on.",
            "provider": "VCS provider hosting the stack's repository (e.g. GITHUB, GITLAB).",
            "repository": "Name of the repository the stack tracks.",
            "repository_url": "Full URL of the tracked repository.",
            "space": "ID of the Spacelift space the stack belongs to.",
            "state": "Current state of the stack (e.g. FINISHED, FAILED, UNCONFIRMED).",
            "state_set_at": "Unix timestamp (seconds) when the current state was set.",
            "terraform_version": "Terraform/OpenTofu version the stack uses.",
            "vcs_detached": "Whether the stack's VCS integration has been deleted.",
        },
    },
    "runs": {
        "description": "Historical record of every run across all stacks and modules: deployments (tracked runs), previews (proposed runs), tasks, and drift-detection runs, with timing, state, and change counts.",
        "docs_url": "https://docs.spacelift.io/concepts/run/",
        "columns": {
            "id": "Unique identifier (ULID) of the run.",
            "branch": "VCS branch the run executed against.",
            "commit": "Commit the run executed: author, hash, message, timestamp, and URL.",
            "created_at": "Unix timestamp (seconds) when the run was created.",
            "updated_at": "Unix timestamp (seconds) when the run was last updated.",
            "delta": "Resource change counts produced by the run (added, changed, deleted).",
            "drift_detection": "Whether the run was triggered by drift detection.",
            "expired": "Whether the run expired before being confirmed.",
            "finished": "Whether the run has reached a terminal state.",
            "needs_approval": "Whether the run is blocked waiting for an approval policy.",
            "state": "Current state of the run (e.g. QUEUED, PLANNING, FINISHED, FAILED).",
            "title": "Human-readable title of the run.",
            "triggered_by": "User or trigger that started the run, if any.",
            "type": "Type of the run (e.g. TRACKED, PROPOSED, TASK).",
            "is_module": "Whether the run belongs to a module rather than a stack.",
            "stack_id": "ID of the stack or module the run belongs to.",
            "stack_name": "Name of the stack or module the run belongs to.",
        },
    },
    "policies": {
        "description": "Open Policy Agent (Rego) policies controlling login, access, approval, push, and notification behavior across the account.",
        "docs_url": "https://docs.spacelift.io/concepts/policy/",
        "columns": {
            "id": "Unique identifier (slug) of the policy.",
            "name": "Human-readable name of the policy.",
            "description": "Free-form description of the policy.",
            "type": "Policy type (e.g. ACCESS, APPROVAL, LOGIN, PLAN, PUSH, NOTIFICATION).",
            "body": "Rego source code of the policy.",
            "space": "ID of the Spacelift space the policy belongs to.",
            "labels": "Labels attached to the policy.",
            "created_at": "Unix timestamp (seconds) when the policy was created.",
            "updated_at": "Unix timestamp (seconds) when the policy was last updated.",
        },
    },
    "contexts": {
        "description": "Reusable bundles of environment variables and mounted files attached to stacks.",
        "docs_url": "https://docs.spacelift.io/concepts/configuration/context",
        "columns": {
            "id": "Unique identifier (slug) of the context.",
            "name": "Human-readable name of the context.",
            "description": "Free-form description of the context.",
            "space": "ID of the Spacelift space the context belongs to.",
            "labels": "Labels attached to the context.",
            "created_at": "Unix timestamp (seconds) when the context was created.",
            "updated_at": "Unix timestamp (seconds) when the context was last updated.",
        },
    },
    "modules": {
        "description": "Terraform modules published to the Spacelift module registry, with their tracked repository and current version.",
        "docs_url": "https://docs.spacelift.io/vendors/terraform/module-registry",
        "columns": {
            "id": "Unique identifier (slug) of the module.",
            "name": "Human-readable name of the module.",
            "administrative": "Whether the module has administrative permissions on the Spacelift account.",
            "branch": "VCS branch the module tracks.",
            "created_at": "Unix timestamp (seconds) when the module was created.",
            "current": "Current (latest) published version of the module.",
            "description": "Free-form description of the module.",
            "labels": "Labels attached to the module.",
            "namespace": "VCS namespace (organization or user) of the module's repository.",
            "owner_subdomain": "Subdomain of the Spacelift account that owns the module.",
            "project_root": "Directory inside the repository the module lives in.",
            "provider": "VCS provider hosting the module's repository.",
            "public": "Whether the module is publicly visible.",
            "repository": "Name of the repository the module tracks.",
            "space": "ID of the Spacelift space the module belongs to.",
            "terraform_provider": "Cloud provider the module targets (registry naming).",
            "workflow_tool": "IaC tool the module uses (e.g. TERRAFORM_FOSS, OPEN_TOFU).",
        },
    },
    "worker_pools": {
        "description": "Private worker pools that execute runs, with queue depth and busy-worker counts.",
        "docs_url": "https://docs.spacelift.io/concepts/worker-pools/",
        "columns": {
            "id": "Unique identifier of the worker pool.",
            "name": "Human-readable name of the worker pool.",
            "description": "Free-form description of the worker pool.",
            "space": "ID of the Spacelift space the worker pool belongs to.",
            "labels": "Labels attached to the worker pool.",
            "created_at": "Unix timestamp (seconds) when the worker pool was created.",
            "updated_at": "Unix timestamp (seconds) when the worker pool was last updated.",
            "deleted": "Whether the worker pool has been deleted.",
            "busy_workers": "Number of workers currently processing a run.",
            "pending_runs": "Number of runs queued for this worker pool.",
        },
    },
    "spaces": {
        "description": "Organizational spaces grouping stacks, policies, and other resources into an access-control hierarchy.",
        "docs_url": "https://docs.spacelift.io/concepts/spaces/",
        "columns": {
            "id": "Unique identifier (slug) of the space.",
            "name": "Human-readable name of the space.",
            "description": "Free-form description of the space.",
            "parent_space": "ID of the parent space in the hierarchy, if any.",
            "inherit_entities": "Whether the space inherits entities (contexts, policies, worker pools) from its parent.",
            "labels": "Labels attached to the space.",
        },
    },
    "managed_entities": {
        "description": "Individual infrastructure resources (Terraform/OpenTofu entities) managed across all stacks, including drift status per resource.",
        "docs_url": "https://docs.spacelift.io/concepts/resources",
        "columns": {
            "id": "Identifier of the managed entity within its stack.",
            "address": "Terraform address of the resource (e.g. aws_instance.web).",
            "name": "Name of the resource.",
            "type": "Resource type (e.g. aws_instance).",
            "parent": "Address of the parent module the resource belongs to.",
            "drifted": "Whether the resource has drifted from its desired state.",
            "stack_id": "ID of the stack managing the resource.",
            "stack_name": "Name of the stack managing the resource.",
            "creator": "Run that created the resource.",
            "updater": "Run that last updated the resource.",
        },
    },
}
