from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

_COMMON_MAILPIECE_COLUMNS = {
    "id": "Unique identifier for the mailpiece, prefixed by its type (e.g. `ltr_`, `psc_`).",
    "description": "An internal description that identifies this resource. Up to 255 characters.",
    "metadata": "A set of user-defined key/value pairs attached to the resource.",
    "to": "The recipient address object the mailpiece was sent to.",
    "from": "The sender (return) address object.",
    "url": "A signed link to the rendered PDF of the mailpiece.",
    "carrier": "The carrier used to deliver the mailpiece (e.g. USPS).",
    "tracking_events": "Tracking events recorded as the mailpiece moves through the mail stream.",
    "expected_delivery_date": "Lob's estimated delivery date for the mailpiece.",
    "send_date": "The date Lob will begin processing the mailpiece for printing and mailing.",
    "mail_type": "The USPS mail class used (e.g. `usps_first_class`, `usps_standard`).",
    "use_type": "The declared use type of the mailpiece (`marketing` or `operational`).",
    "date_created": "ISO-8601 timestamp of when the resource was created.",
    "date_modified": "ISO-8601 timestamp of when the resource was last modified.",
    "object": "The resource type string (e.g. `letter`).",
}

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "letters": {
        "description": "Letters created through Lob — printed and mailed physical letters.",
        "docs_url": "https://docs.lob.com/#tag/Letters",
        "columns": {
            **_COMMON_MAILPIECE_COLUMNS,
            "color": "Whether the letter is printed in color (`true`) or black & white (`false`).",
            "double_sided": "Whether the letter is printed on both sides of each page.",
            "address_placement": "Where the recipient address is placed (e.g. `top_first_page`).",
            "return_envelope": "Whether a return envelope was included with the letter.",
            "perforated_page": "The page number that is perforated, if any.",
            "extra_service": "Any extra USPS service applied (e.g. `certified`, `registered`).",
            "template_id": "The template used to render the letter, if any.",
            "template_version_id": "The specific template version used, if any.",
            "tracking_number": "USPS tracking number, available for trackable services.",
        },
    },
    "postcards": {
        "description": "Postcards created through Lob — printed and mailed postcards.",
        "docs_url": "https://docs.lob.com/#tag/Postcards",
        "columns": {
            **_COMMON_MAILPIECE_COLUMNS,
            "size": "The postcard size (e.g. `4x6`, `6x9`, `6x11`).",
            "front_template_id": "Template used to render the front of the postcard, if any.",
            "back_template_id": "Template used to render the back of the postcard, if any.",
        },
    },
    "checks": {
        "description": "Checks created through Lob — printed and mailed checks.",
        "docs_url": "https://docs.lob.com/#tag/Checks",
        "columns": {
            **_COMMON_MAILPIECE_COLUMNS,
            "check_number": "The check number printed on the check.",
            "amount": "The dollar amount of the check.",
            "memo": "The memo printed in the lower-left of the check.",
            "bank_account": "The bank account the check is drawn from.",
        },
    },
    "self_mailers": {
        "description": "Self mailers created through Lob — folded mailers that need no envelope.",
        "docs_url": "https://docs.lob.com/#tag/Self-Mailers",
        "columns": {
            **_COMMON_MAILPIECE_COLUMNS,
            "size": "The self mailer size (e.g. `6x18_bifold`, `12x9_bifold`).",
            "inside_template_id": "Template used to render the inside of the self mailer, if any.",
            "outside_template_id": "Template used to render the outside of the self mailer, if any.",
        },
    },
    "addresses": {
        "description": "Saved addresses in your Lob account, reusable as senders or recipients.",
        "docs_url": "https://docs.lob.com/#tag/Addresses",
        "columns": {
            "id": "Unique identifier for the address, prefixed `adr_`.",
            "description": "An internal description that identifies this address.",
            "name": "Recipient or company name on the address.",
            "company": "Company name on the address.",
            "phone": "Phone number associated with the address.",
            "email": "Email associated with the address.",
            "address_line1": "Primary number, street name and unit/box of the address.",
            "address_line2": "Secondary information such as apartment or suite number.",
            "address_city": "City of the address.",
            "address_state": "State or province of the address.",
            "address_zip": "ZIP or postal code of the address.",
            "address_country": "Country of the address.",
            "metadata": "A set of user-defined key/value pairs attached to the address.",
            "date_created": "ISO-8601 timestamp of when the address was created.",
            "date_modified": "ISO-8601 timestamp of when the address was last modified.",
            "object": "The resource type string (`address`).",
        },
    },
    "bank_accounts": {
        "description": "Bank accounts saved in your Lob account, used as the source of funds for checks.",
        "docs_url": "https://docs.lob.com/#tag/Bank-Accounts",
        "columns": {
            "id": "Unique identifier for the bank account, prefixed `bank_`.",
            "description": "An internal description that identifies this bank account.",
            "routing_number": "The ABA routing number of the bank account.",
            "account_number": "The account number of the bank account.",
            "account_type": "The type of account (`company` or `individual`).",
            "signatory": "The signatory associated with the bank account.",
            "metadata": "A set of user-defined key/value pairs attached to the bank account.",
            "verified": "Whether the bank account has been verified for use with checks.",
            "date_created": "ISO-8601 timestamp of when the bank account was created.",
            "date_modified": "ISO-8601 timestamp of when the bank account was last modified.",
            "object": "The resource type string (`bank_account`).",
        },
    },
    "templates": {
        "description": "Reusable HTML templates used to render mailpieces.",
        "docs_url": "https://docs.lob.com/#tag/Templates",
        "columns": {
            "id": "Unique identifier for the template, prefixed `tmpl_`.",
            "description": "An internal description that identifies this template.",
            "name": "The template's name.",
            "published_version": "The currently published version of the template.",
            "versions": "The list of versions belonging to this template.",
            "metadata": "A set of user-defined key/value pairs attached to the template.",
            "date_created": "ISO-8601 timestamp of when the template was created.",
            "date_modified": "ISO-8601 timestamp of when the template was last modified.",
            "object": "The resource type string (`template`).",
        },
    },
    "campaigns": {
        "description": "Lob campaigns — groups of mailpieces sent together as part of a single send.",
        "docs_url": "https://docs.lob.com/#tag/Campaigns",
        "columns": {
            "id": "Unique identifier for the campaign, prefixed `cmp_`.",
            "name": "The campaign's name.",
            "description": "An internal description that identifies this campaign.",
            "schedule_type": "How the campaign is scheduled (e.g. `immediate`, `scheduled`).",
            "send_date": "The date the campaign is scheduled to send.",
            "status": "The campaign's current status.",
            "use_type": "The declared use type of the campaign (`marketing` or `operational`).",
            "metadata": "A set of user-defined key/value pairs attached to the campaign.",
            "date_created": "ISO-8601 timestamp of when the campaign was created.",
            "date_modified": "ISO-8601 timestamp of when the campaign was last modified.",
            "object": "The resource type string (`campaign`).",
        },
    },
}
