# Summaries
LLM_TRACES_SUMMARIES_MODEL_TO_SUMMARIZE_STRINGIFIED_TRACES = "gemini-2.5-flash-lite-preview-09-2025"

# Embeddings
DOCUMENT_EMBEDDINGS_TOPIC = "document_embeddings_input"
LLM_TRACES_SUMMARIES_PRODUCT = "llm-analytics"
LLM_TRACES_SUMMARIES_DOCUMENT_TYPE = "llm-trace-summary"
LLM_TRACES_SUMMARIES_SEARCH_QUERY_DOCUMENT_TYPE = "trace-summary-search-query"
LLM_TRACES_SUMMARIES_SEARCH_QUERY_POLL_INTERVAL_SECONDS = 3
LLM_TRACES_SUMMARIES_SEARCH_QUERY_MAX_ATTEMPTS = 10
