from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Descriptions sourced from the JobNimbus Open API docs (https://documenter.getpostman.com/view/3919598/S11PpG4x).
# Partial coverage is fine — uncovered columns fall back to LLM enrichment.
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "contacts": {
        "description": "A person or company in your JobNimbus CRM — a lead, customer, or business contact.",
        "docs_url": "https://documenter.getpostman.com/view/3919598/S11PpG4x",
        "columns": {
            "jnid": "The unique ID of the contact.",
            "display_name": "The contact's display name.",
            "first_name": "The contact's first name.",
            "last_name": "The contact's last name.",
            "company": "The company the contact is associated with.",
            "email": "The contact's primary email address.",
            "status_name": "The contact's current status in the workflow.",
            "record_type_name": "The contact record type.",
            "date_created": "When the contact was created (epoch seconds).",
            "date_updated": "When the contact was last updated (epoch seconds).",
        },
    },
    "jobs": {
        "description": "A job or project tracked in JobNimbus, typically linked to one or more contacts.",
        "docs_url": "https://documenter.getpostman.com/view/3919598/S11PpG4x",
        "columns": {
            "jnid": "The unique ID of the job.",
            "name": "The job name.",
            "number": "The human-readable job number.",
            "status_name": "The job's current status in the workflow.",
            "record_type_name": "The job record type.",
            "date_created": "When the job was created (epoch seconds).",
            "date_updated": "When the job was last updated (epoch seconds).",
            "date_status_change": "When the job status last changed (epoch seconds).",
        },
    },
    "tasks": {
        "description": "A to-do or scheduled task linked to a contact or job.",
        "docs_url": "https://documenter.getpostman.com/view/3919598/S11PpG4x",
        "columns": {
            "jnid": "The unique ID of the task.",
            "title": "The task title.",
            "description": "The task description.",
            "record_type_name": "The task record type.",
            "date_start": "When the task starts (epoch seconds).",
            "date_end": "When the task ends (epoch seconds).",
            "is_completed": "Whether the task has been completed.",
            "date_created": "When the task was created (epoch seconds).",
            "date_updated": "When the task was last updated (epoch seconds).",
        },
    },
    "activities": {
        "description": "An activity or note recorded against a contact or job (calls, emails, updates).",
        "docs_url": "https://documenter.getpostman.com/view/3919598/S11PpG4x",
        "columns": {
            "jnid": "The unique ID of the activity.",
            "note": "The activity note or message body.",
            "record_type_name": "The activity record type.",
            "primary": "The primary related record (contact or job) the activity is attached to.",
            "date_created": "When the activity was created (epoch seconds).",
            "date_updated": "When the activity was last updated (epoch seconds).",
        },
    },
    "payments": {
        "description": "A payment collected from a customer, applied against one or more invoices.",
        "docs_url": "https://documenter.getpostman.com/view/3919598/S11PpG4x",
        "columns": {
            "jnid": "The unique ID of the payment.",
            "customer": "The ID of the customer the payment belongs to.",
            "total": "The total payment amount.",
            "credit": "The credit amount applied by the payment.",
            "refunded_amount": "The amount refunded from the payment.",
            "invoices": "The invoices the payment is applied to, with the amount applied to each.",
            "reference": "The payment reference, such as a check number.",
            "date_payment": "When the payment was made (epoch seconds).",
            "sales_rep": "The ID of the sales rep assigned to the payment.",
            "date_created": "When the payment was created (epoch seconds).",
            "date_updated": "When the payment was last updated (epoch seconds).",
        },
    },
    "estimates": {
        "description": "A quote sent to a customer for a job, with line items and totals.",
        "docs_url": "https://documenter.getpostman.com/view/3919598/S11PpG4x",
        "columns": {
            "jnid": "The unique ID of the estimate.",
            "number": "The estimate number.",
            "customer": "The ID of the customer the estimate belongs to.",
            "status": "The numeric status of the estimate.",
            "status_name": "The status name of the estimate.",
            "cost": "The total cost of the estimate.",
            "margin": "The profit margin of the estimate.",
            "subtotal": "The subtotal amount.",
            "tax": "The tax amount.",
            "total": "The total estimate amount.",
            "items": "The line items in the estimate.",
            "related": "The related records (jobs, contacts) the estimate is attached to.",
            "esigned": "Whether the estimate was signed electronically.",
            "date_estimate": "The estimate date (epoch seconds).",
            "date_signed": "When the estimate was signed (epoch seconds).",
            "date_status_change": "When the estimate status last changed (epoch seconds).",
            "date_created": "When the estimate was created (epoch seconds).",
            "date_updated": "When the estimate was last updated (epoch seconds).",
        },
    },
    "invoices": {
        "description": "An invoice billed to a customer for a job, with line items, totals, and payments applied.",
        "docs_url": "https://documenter.getpostman.com/view/3919598/S11PpG4x",
        "columns": {
            "jnid": "The unique ID of the invoice.",
            "number": "The invoice number.",
            "customer": "The ID of the customer the invoice belongs to.",
            "status": "The numeric status of the invoice.",
            "status_name": "The status name of the invoice.",
            "cost": "The total cost of the invoice.",
            "margin": "The profit margin of the invoice.",
            "subtotal": "The subtotal amount.",
            "tax": "The tax amount.",
            "total": "The total invoice amount.",
            "total_paid": "The total amount paid against the invoice.",
            "due": "The amount still due on the invoice.",
            "items": "The line items in the invoice.",
            "payments": "The payments applied to the invoice.",
            "related": "The related records (jobs, contacts) the invoice is attached to.",
            "sales_rep": "The ID of the sales rep assigned to the invoice.",
            "date_invoice": "The invoice date (epoch seconds).",
            "date_due": "When the invoice is due (epoch seconds).",
            "date_paid_in_full": "When the invoice was paid in full (epoch seconds).",
            "date_status_change": "When the invoice status last changed (epoch seconds).",
            "date_created": "When the invoice was created (epoch seconds).",
            "date_updated": "When the invoice was last updated (epoch seconds).",
        },
    },
    "products": {
        "description": "A product or service in the account catalog, referenced by estimate and invoice line items.",
        "docs_url": "https://documenter.getpostman.com/view/3919598/S11PpG4x",
        "columns": {
            "jnid": "The unique ID of the product.",
            "name": "The product name.",
            "description": "The product description.",
            "item_type": "The item type, such as material, labor, or labor+material.",
            "uoms": "The units of measure the product is sold in, with material and labor cost and price for each.",
            "suppliers": "The suppliers of the product.",
            "is_active": "Whether the product is active.",
            "tax_exempt": "Whether the product is exempt from tax.",
            "external_id": "The ID of the product in a third-party system it was imported from.",
            "date_created": "When the product was created (epoch seconds).",
            "date_updated": "When the product was last updated (epoch seconds).",
        },
    },
    "budgets": {
        "description": "A job budget with its revenue, costs, commissions, and resulting profit and margin.",
        "docs_url": "https://documenter.getpostman.com/view/3919598/S11PpG4x",
        "columns": {
            "jnid": "The unique ID of the budget.",
            "number": "The budget number.",
            "customer": "The ID of the customer the budget belongs to.",
            "status_name": "The status name of the budget.",
            "revenue": "The budgeted revenue.",
            "costs": "The cost lines in the budget.",
            "total_cost": "The total budgeted cost.",
            "commissions": "The commission lines in the budget.",
            "total_commissions": "The total commissions.",
            "gross_profit": "The gross profit.",
            "gross_margin": "The gross margin percentage.",
            "net_profit": "The net profit after commissions.",
            "net_margin": "The net margin percentage.",
            "related": "The related records (jobs, contacts) the budget is attached to.",
            "date_budget": "The budget date (epoch seconds).",
            "date_created": "When the budget was created (epoch seconds).",
            "date_updated": "When the budget was last updated (epoch seconds).",
        },
    },
    "users": {
        "description": "A user or team member of the JobNimbus account.",
        "docs_url": "https://documenter.getpostman.com/view/3919598/S11PpG4x",
        "columns": {
            "id": "The user's ID. Matches the owner, sales rep, and assignee IDs on other records.",
            "first_name": "The user's first name.",
            "last_name": "The user's last name.",
            "email": "The user's email address.",
            "is_active": "Whether the user is active or disabled.",
        },
    },
    "workflows": {
        "description": "A workflow configured in the account, with the statuses it contains.",
        "docs_url": "https://documenter.getpostman.com/view/3919598/S11PpG4x",
        "columns": {
            "id": "The unique ID of the workflow.",
            "name": "The workflow name.",
            "object_type": "The record type the workflow applies to, such as contact or job.",
            "status": "The statuses in the workflow. Their IDs match the status IDs on contacts and jobs.",
            "is_active": "Whether the workflow is active.",
        },
    },
    "lead_sources": {
        "description": "A lead source configured in the account.",
        "docs_url": "https://documenter.getpostman.com/view/3919598/S11PpG4x",
        "columns": {
            "JobSourceId": "The unique ID of the lead source. Matches the source ID on contacts and jobs.",
            "SourceName": "The lead source name.",
            "IsActive": "Whether the lead source is active.",
        },
    },
    "groups": {
        "description": "A group of users in the account, such as a team, crew, or office.",
        "docs_url": "https://documenter.getpostman.com/view/3919598/S11PpG4x",
        "columns": {
            "name": "The group name.",
            "managers": "The IDs of the users who manage the group.",
            "members": "The IDs of the users in the group.",
        },
    },
}
