from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "documents": {
        "description": "Signature documents sent from the account, including their status, signers, and lifecycle dates.",
        "docs_url": "https://developers.boldsign.com/documents/list-documents/",
        "columns": {
            "documentId": "Unique identifier of the document.",
            "messageTitle": "Title of the document shown to recipients.",
            "status": "Current status of the document (e.g. InProgress, Completed, Declined, Revoked, Expired, Draft).",
            "displayStatus": "Human-readable status label for display.",
            "senderDetail": "Details of the user who sent the document.",
            "ccDetails": "Recipients copied on the document.",
            "signerDetails": "Recipients required to act on the document, with their roles and status.",
            "createdDate": "Unix epoch timestamp for when the document was created.",
            "activityDate": "Unix epoch timestamp of the most recent activity on the document.",
            "activityBy": "Email of the user responsible for the most recent activity.",
            "expiryDate": "Unix epoch timestamp for when the document expires.",
            "scheduledSendTime": "Unix epoch timestamp for a scheduled send, if configured.",
            "enableSigningOrder": "Whether recipients must sign in a defined order.",
            "isDeleted": "Whether the document has been deleted.",
            "inEditingMode": "Whether the document is currently being edited.",
            "labels": "Labels applied to the document.",
            "brandId": "Identifier of the brand applied to the document.",
            "cursor": "Opaque pagination cursor used to page past the 10,000-record limit.",
        },
    },
    "templates": {
        "description": "Reusable document templates defined in the account.",
        "docs_url": "https://developers.boldsign.com/templates/list-templates/",
        "columns": {
            "documentId": "Unique identifier of the template.",
            "templateName": "Name of the template.",
            "templateDescription": "Description of the template.",
            "messageTitle": "Default title applied to documents created from the template.",
            "status": "Current status of the template.",
            "senderDetail": "Details of the user who owns the template.",
            "ccDetails": "Recipients copied by default on documents from this template.",
            "signerDetails": "Default signer roles configured on the template.",
            "accessType": "Sharing/access type of the template (e.g. mine, shared).",
            "isTemplate": "Always true for template records.",
            "enableSigningOrder": "Whether recipients must sign in a defined order.",
            "createdDate": "Unix epoch timestamp for when the template was created.",
            "activityDate": "Unix epoch timestamp of the most recent activity on the template.",
            "templateLabels": "Labels applied to the template.",
            "brandId": "Identifier of the brand applied to the template.",
        },
    },
    "users": {
        "description": "Users belonging to the BoldSign account, including their team and role.",
        "docs_url": "https://developers.boldsign.com/users/list-users/",
        "columns": {
            "userId": "Unique identifier of the user.",
            "email": "Email address of the user.",
            "firstName": "First name of the user.",
            "lastName": "Last name of the user.",
            "teamId": "Identifier of the team the user belongs to.",
            "teamName": "Name of the team the user belongs to.",
            "role": "Role assigned to the user.",
            "userStatus": "Current status of the user (e.g. active, invited).",
            "createdDate": "Unix epoch timestamp for when the user was created.",
            "modifiedDate": "Unix epoch timestamp for when the user was last modified.",
        },
    },
    "teams": {
        "description": "Teams configured in the BoldSign account.",
        "docs_url": "https://developers.boldsign.com/teams/list-teams/",
        "columns": {
            "teamId": "Unique identifier of the team.",
            "teamName": "Name of the team.",
            "createdDate": "Unix epoch timestamp for when the team was created.",
            "modifiedDate": "Unix epoch timestamp for when the team was last modified.",
        },
    },
    "contacts": {
        "description": "Address-book contacts available when preparing documents.",
        "docs_url": "https://developers.boldsign.com/contacts/list-contacts/",
        "columns": {
            "id": "Unique identifier of the contact.",
            "name": "Full name of the contact.",
            "email": "Email address of the contact.",
            "companyName": "Company the contact belongs to.",
            "jobTitle": "Job title of the contact.",
            "phoneNumber": "Phone number of the contact.",
        },
    },
    "sender_identities": {
        "description": "Verified sender identities that documents can be sent on behalf of.",
        "docs_url": "https://developers.boldsign.com/sender-identities/list-sender-identities/",
        "columns": {
            "id": "Unique identifier of the sender identity.",
            "name": "Display name of the sender identity.",
            "email": "Email address of the sender identity.",
            "status": "Verification status of the sender identity.",
            "createdBy": "Email of the user who created the sender identity.",
            "approvedDate": "Date the sender identity was approved.",
            "brandId": "Identifier of the brand associated with the sender identity.",
            "redirectUrl": "Redirect URL configured for the sender identity.",
            "locale": "Locale configured for the sender identity.",
        },
    },
    "brands": {
        "description": "Branding configurations (logos, colors, disclaimers) applied to documents.",
        "docs_url": "https://developers.boldsign.com/brandings/list-brands/",
        "columns": {
            "brandId": "Unique identifier of the brand.",
            "brandName": "Name of the brand.",
            "brandLogo": "URL of the brand logo.",
            "backgroundColor": "Background color used by the brand.",
            "buttonColor": "Button color used by the brand.",
            "buttonTextColor": "Button text color used by the brand.",
            "emailDisplayName": "Display name shown on outgoing emails for the brand.",
            "isDefault": "Whether this is the account's default brand.",
            "redirectUrl": "Redirect URL configured for the brand.",
            "documentTimeZone": "Time zone applied to documents using this brand.",
        },
    },
}
