from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

_DOCS = "https://docs.clover.com/dev/reference/api-reference-overview"

# Clover timestamps are epoch milliseconds throughout, and money amounts are integers in the
# merchant's smallest currency unit (cents for USD).
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "orders": {
        "description": "Orders rung up on the merchant's Clover devices, with their line items inlined.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the order.",
            "currency": "ISO 4217 currency the order was priced in.",
            "total": "Order total in the smallest currency unit, including tax and service charge.",
            "state": "Order state, such as open or locked.",
            "title": "Optional label given to the order.",
            "note": "Free-text note attached to the order.",
            "taxRemoved": "Whether tax was removed from the order.",
            "isVat": "Whether the order was priced with VAT-inclusive tax.",
            "testMode": "Whether the order was created in test mode rather than by a real sale.",
            "createdTime": "When the order was created on Clover's servers, in epoch milliseconds.",
            "clientCreatedTime": "When the device created the order, in epoch milliseconds.",
            "modifiedTime": "When the order was last changed, in epoch milliseconds.",
            "employee": "Reference to the employee who took the order.",
            "device": "Reference to the device the order was created on.",
            "customers": "Customers associated with the order.",
            "lineItems": "Line items on the order, expanded inline.",
            "payments": "Payments applied to the order.",
        },
    },
    "payments": {
        "description": "Payments taken against orders, one row per tender attempt.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the payment.",
            "order": "Reference to the order the payment was applied to.",
            "device": "Reference to the device that took the payment.",
            "tender": "Reference to the tender type used, such as credit card or cash.",
            "amount": "Amount paid in the smallest currency unit.",
            "tipAmount": "Tip included in the payment, in the smallest currency unit.",
            "taxAmount": "Tax included in the payment, in the smallest currency unit.",
            "cashbackAmount": "Cash back given with the payment, in the smallest currency unit.",
            "cashTendered": "Cash handed over by the customer, in the smallest currency unit.",
            "externalPaymentId": "Identifier supplied by the integration that created the payment.",
            "employee": "Reference to the employee who took the payment.",
            "result": "Outcome of the payment, such as SUCCESS or FAIL.",
            "offline": "Whether the payment was captured while the device was offline.",
            "createdTime": "When the payment was recorded, in epoch milliseconds.",
            "clientCreatedTime": "When the device recorded the payment, in epoch milliseconds.",
            "modifiedTime": "When the payment was last changed, in epoch milliseconds.",
        },
    },
    "refunds": {
        "description": "Refunds issued against payments.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the refund.",
            "orderRef": "Reference to the order being refunded.",
            "payment": "Reference to the payment being refunded.",
            "device": "Reference to the device the refund was issued on.",
            "amount": "Amount refunded in the smallest currency unit.",
            "taxAmount": "Tax portion of the refund, in the smallest currency unit.",
            "serviceCharge": "Service charge returned with the refund.",
            "transactionInfo": "Processor details for the refund transaction.",
            "createdTime": "When the refund was issued, in epoch milliseconds.",
        },
    },
    "credits": {
        "description": "Manual (unlinked) credits paid out to a customer without an originating payment.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the credit.",
            "orderRef": "Reference to the order the credit relates to, when there is one.",
            "device": "Reference to the device the credit was issued on.",
            "tender": "Reference to the tender the credit was returned on.",
            "amount": "Credit amount in the smallest currency unit.",
            "taxAmount": "Tax portion of the credit, in the smallest currency unit.",
            "employee": "Reference to the employee who issued the credit.",
            "createdTime": "When the credit was issued, in epoch milliseconds.",
            "clientCreatedTime": "When the device recorded the credit, in epoch milliseconds.",
        },
    },
    "items": {
        "description": "Inventory items the merchant sells.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the item.",
            "name": "Item name shown on the register.",
            "alternateName": "Secondary name, often used for a second language.",
            "code": "Merchant-defined product code.",
            "sku": "Stock keeping unit.",
            "price": "Item price in the smallest currency unit.",
            "priceType": "How the price is calculated, such as FIXED, VARIABLE or PER_UNIT.",
            "unitName": "Unit the item is sold by when priced per unit.",
            "cost": "Cost of goods for the item, in the smallest currency unit.",
            "isRevenue": "Whether sales of the item count toward revenue.",
            "hidden": "Whether the item is hidden from the register.",
            "stockCount": "Current tracked stock level.",
            "defaultTaxRates": "Whether the merchant's default tax rates apply to the item.",
            "modifiedTime": "When the item was last changed, in epoch milliseconds.",
        },
    },
    "categories": {
        "description": "Categories used to group inventory items on the register.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the category.",
            "name": "Category name.",
            "sortOrder": "Position of the category in the register layout.",
        },
    },
    "modifier_groups": {
        "description": "Groups of modifiers (such as toppings or sizes) that can be applied to items.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the modifier group.",
            "name": "Modifier group name.",
            "showByDefault": "Whether the group is shown automatically when the item is added.",
            "sortOrder": "Position of the group in the register layout.",
            "minRequired": "Minimum number of modifiers the customer must choose.",
            "maxAllowed": "Maximum number of modifiers the customer may choose.",
        },
    },
    "customers": {
        "description": "Customer records saved on the merchant account.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the customer.",
            "firstName": "Customer's first name.",
            "lastName": "Customer's last name.",
            "marketingAllowed": "Whether the customer opted in to marketing.",
            "customerSince": "When the customer record was created, in epoch milliseconds.",
            "emailAddresses": "Email addresses on file for the customer.",
            "phoneNumbers": "Phone numbers on file for the customer.",
            "addresses": "Postal addresses on file for the customer.",
            "metadata": "Additional customer details such as business name and notes.",
        },
    },
    "employees": {
        "description": "Employees who can sign in to the merchant's Clover devices.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the employee.",
            "name": "Employee's full name.",
            "nickname": "Short name shown on the register.",
            "customId": "Merchant-defined employee identifier.",
            "email": "Employee's email address.",
            "role": "Permission role, such as ADMIN, MANAGER or EMPLOYEE.",
            "isOwner": "Whether the employee owns the merchant account.",
            "inviteSent": "Whether an account invitation has been sent.",
        },
    },
    "shifts": {
        "description": "Clock-in and clock-out shifts recorded by employees.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the shift.",
            "employee": "Reference to the employee who worked the shift.",
            "inTime": "Clock-in time, in epoch milliseconds.",
            "outTime": "Clock-out time, in epoch milliseconds; absent while the shift is open.",
            "cashierRole": "Role the employee worked the shift under.",
            "overrideInEmployee": "Employee who adjusted the clock-in time, when it was overridden.",
            "overrideOutEmployee": "Employee who adjusted the clock-out time, when it was overridden.",
        },
    },
    "tenders": {
        "description": "Tender types the merchant accepts, such as cash, credit or a custom tender.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the tender.",
            "label": "Tender name shown on the register.",
            "labelKey": "Stable key identifying built-in tenders.",
            "enabled": "Whether the tender can be used.",
            "visible": "Whether the tender is shown on the register.",
            "editable": "Whether the merchant can edit the tender.",
            "opensCashDrawer": "Whether taking this tender opens the cash drawer.",
            "supportsTipping": "Whether tips can be added to this tender.",
            "instructions": "Instructions shown to the cashier for this tender.",
        },
    },
    "discounts": {
        "description": "Discounts configured on the merchant account and available at the register.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the discount.",
            "name": "Discount name.",
            "amount": "Fixed discount amount in the smallest currency unit, when the discount is a flat amount.",
            "percentage": "Discount percentage, when the discount is proportional.",
        },
    },
    "tax_rates": {
        "description": "Tax rates the merchant applies to items and orders.",
        "docs_url": _DOCS,
        "columns": {
            "id": "Unique identifier for the tax rate.",
            "name": "Tax rate name.",
            "rate": "Tax rate expressed in millionths of a percent.",
            "taxAmount": "Flat tax amount, for per-item flat taxes.",
            "isDefault": "Whether the rate is applied to new items by default.",
        },
    },
}
