# This file is automatically generated from `SourceRegistry.get_all_sources()`
# Do not edit manually - run `pnpm generate:source-configs` to regenerate.

from typing import Literal

from products.warehouse_sources.backend.temporal.data_imports.sources.common import config


@config.config
class SnowflakeAuthTypeConfig(config.Config):
    user: str
    selection: Literal["password", "keypair"] = "password"
    password: str | None = None
    private_key: str | None = None
    passphrase: str | None = None


@config.config
class SnowflakeSourceConfig(config.Config):
    account_id: str
    database: str
    warehouse: str
    auth_type: SnowflakeAuthTypeConfig
    connection_string: str | None = None
    role: str | None = None
    schema: str | None = None
