# This file is automatically generated from `SourceRegistry.get_all_sources()`
# Do not edit manually - run `pnpm generate:source-configs` to regenerate.

from typing import Literal

from products.warehouse_sources.backend.temporal.data_imports.sources.common import config


@config.config
class TrinoAuthTypeConfig(config.Config):
    user: str
    selection: Literal["password", "jwt", "none"] = "password"
    password: str | None = None
    token: str | None = None


@config.config
class TrinoSourceConfig(config.Config):
    host: str
    catalog: str
    auth_type: TrinoAuthTypeConfig
    port: int = config.value(converter=int)
    schema: str | None = None
    use_ssl: bool = config.value(default=config.str_to_bool("true"), converter=config.str_to_bool)
    verify_ssl: bool = config.value(default=config.str_to_bool("true"), converter=config.str_to_bool)
