from posthog.temporal.data_imports.sources.polar.constants import (
    BENEFIT_RESOURCE_NAME,
    CHECKOUT_RESOURCE_NAME,
    CUSTOMER_RESOURCE_NAME,
    ORDER_RESOURCE_NAME,
    ORGANIZATION_RESOURCE_NAME,
    PRODUCT_RESOURCE_NAME,
    REFUND_RESOURCE_NAME,
    SUBSCRIPTION_RESOURCE_NAME,
)

ENDPOINTS = [
    CUSTOMER_RESOURCE_NAME,
    PRODUCT_RESOURCE_NAME,
    ORDER_RESOURCE_NAME,
    SUBSCRIPTION_RESOURCE_NAME,
    REFUND_RESOURCE_NAME,
    CHECKOUT_RESOURCE_NAME,
    BENEFIT_RESOURCE_NAME,
    ORGANIZATION_RESOURCE_NAME,
]
