from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)
from products.warehouse_sources.backend.temporal.data_imports.sources.uk_companies_house.settings import (
    CHARGES,
    COMPANIES,
    EXEMPTIONS,
    FILING_HISTORY,
    INSOLVENCY,
    OFFICERS,
    PERSONS_WITH_SIGNIFICANT_CONTROL,
    PSC_STATEMENTS,
    REGISTERS,
    UK_ESTABLISHMENTS,
)

_REFERENCE_URL = "https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/reference"
_RESOURCES_URL = "https://developer-specs.company-information.service.gov.uk/companies-house-public-data-api/resources"

_COMPANY_NUMBER = "The company number the row was fetched for."

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    COMPANIES: {
        "description": "The Companies House profile of a registered company: name, status, type, incorporation date, registered office and SIC codes.",
        "docs_url": f"{_RESOURCES_URL}/companyprofile?v=latest",
        "columns": {
            "company_number": "The number allocated to the company by Companies House.",
            "company_name": "The name of the company as registered.",
            "company_status": "The status of the company, for example active, dissolved or liquidation.",
            "company_status_detail": "Extra context on the company status.",
            "type": "The legal form of the company, for example ltd, plc or llp.",
            "subtype": "The subtype of the company, for example community interest company.",
            "date_of_creation": "The date the company was incorporated.",
            "date_of_cessation": "The date the company was dissolved, converted or closed.",
            "jurisdiction": "The political body responsible for the company.",
            "sic_codes": "The SIC codes describing what the company does.",
            "registered_office_address": "The address the company's legal correspondence is sent to.",
            "registered_office_is_in_dispute": "Whether the registered office address is disputed.",
            "undeliverable_registered_office_address": "Whether post to the registered office is undeliverable.",
            "service_address": "The correspondence address, for registered overseas entities.",
            "accounts": "Accounting reference dates and the last and next accounts filed.",
            "annual_return": "Annual return dates, superseded by confirmation statements.",
            "confirmation_statement": "The last and next confirmation statement dates.",
            "previous_company_names": "Names the company traded under previously, with the dates they applied.",
            "branch_company_details": "Details of the UK branch of an overseas company.",
            "foreign_company_details": "Details of a company incorporated outside the UK.",
            "links": "Links to the company's other Companies House resources.",
            "can_file": "Whether the company is allowed to file.",
            "has_charges": "Deprecated by Companies House; check the charges link instead.",
            "has_insolvency_history": "Deprecated by Companies House; check the insolvency link instead.",
            "last_full_members_list_date": "The date of the last full members list filed.",
            "partial_data_available": "Set when Companies House is not the primary source of the data.",
            "super_secure_managing_officer_count": "The number of protected officers, for overseas entities.",
            "external_registration_number": "The company's identifier at an external registry.",
            "etag": "The ETag of the resource at Companies House.",
        },
    },
    OFFICERS: {
        "description": "Officers appointed to a company, both current and resigned.",
        "docs_url": f"{_RESOURCES_URL}/officerlist?v=latest",
        "columns": {
            "company_number": _COMPANY_NUMBER,
            "appointment_id": "The appointment identifier taken from the last segment of `links.self`.",
            "name": "The name of the officer.",
            "person_number": "The Companies House identifier for the person.",
            "officer_role": "The role the officer holds, for example director or secretary.",
            "appointed_on": "The date the officer was appointed.",
            "resigned_on": "The date the officer resigned.",
            "nationality": "The nationality of the officer.",
            "country_of_residence": "The country the officer usually lives in.",
            "occupation": "The occupation of the officer.",
            "date_of_birth": "The month and year the officer was born.",
            "former_names": "Names the officer was previously known by.",
            "address": "The correspondence address of the officer.",
            "principal_office_address": "The principal office address of a corporate managing officer.",
            "identification": "Identity type and registration details for a corporate officer.",
            "contact_details": "Contact details recorded for the officer.",
            "identity_verification_details": "Identity verification status and dates for the officer.",
            "responsibilities": "The responsibilities of a managing officer.",
            "is_pre_1992_appointment": "Whether the appointment predates 1992.",
            "links": "Links to the appointment and to the officer's other appointments.",
            "etag": "The ETag of the resource at Companies House.",
        },
    },
    PERSONS_WITH_SIGNIFICANT_CONTROL: {
        "description": "People and entities with significant control over a company, excluding statements filed in place of a person.",
        "docs_url": f"{_REFERENCE_URL}/persons-with-significant-control/list",
        "columns": {
            "company_number": _COMPANY_NUMBER,
            "psc_id": "The notification identifier taken from the last segment of `links.self`.",
            "name": "The full name of the person or entity with significant control.",
            "name_elements": "The name broken into title, forename, middle name and surname.",
            "kind": "The kind of person with significant control, for example individual or corporate entity.",
            "natures_of_control": "The ways in which control is held over the company.",
            "notified_on": "The date Companies House was notified of the person with significant control.",
            "ceased": "Whether the person has ceased to have significant control.",
            "ceased_on": "The date Companies House was notified that control ceased.",
            "date_of_birth": "The month and year the person was born.",
            "nationality": "The nationality of the person.",
            "country_of_residence": "The country the person usually lives in.",
            "address": "The service address of the person or entity.",
            "principal_office_address": "The principal office address of a corporate or legal entity.",
            "identification": "Registration details of a corporate or legal entity.",
            "is_sanctioned": "Whether the person appears on a sanctions list.",
            "identity_verification_details": "Identity verification status and dates.",
            "links": "Links to this notification and its statements.",
            "etag": "The ETag of the resource at Companies House.",
        },
    },
    PSC_STATEMENTS: {
        "description": "Statements a company filed instead of person with significant control details, for example that no person has been identified.",
        "docs_url": f"{_RESOURCES_URL}/statementlist?v=latest",
        "columns": {
            "company_number": _COMPANY_NUMBER,
            "statement_id": "The statement identifier taken from the last segment of `links.self`.",
            "statement": "The statement filed by the company.",
            "kind": "The resource kind, always persons-with-significant-control-statement.",
            "notified_on": "The date Companies House processed the statement.",
            "ceased_on": "The date Companies House was notified that the statement ceased.",
            "linked_psc_name": "The name of the person with significant control the statement refers to.",
            "restrictions_notice_withdrawal_reason": "Why a restrictions notice was withdrawn.",
            "links": "Links to the statement and any linked person with significant control.",
            "etag": "The ETag of the resource at Companies House.",
        },
    },
    FILING_HISTORY: {
        "description": "Documents filed at Companies House for a company, such as accounts, confirmation statements and officer changes.",
        "docs_url": f"{_RESOURCES_URL}/filinghistorylist?v=latest",
        "columns": {
            "company_number": _COMPANY_NUMBER,
            "transaction_id": "The identifier of the filing.",
            "date": "The date the filing was processed.",
            "category": "The category of the filing, for example accounts, officers or mortgage.",
            "subcategory": "A finer classification of the filing.",
            "type": "The filing type code.",
            "description": "A description of the filing.",
            "description_values": "Values used to expand the filing description template.",
            "barcode": "The barcode of the filed document.",
            "pages": "The number of pages in the filed document.",
            "paper_filed": "Whether the document was filed on paper.",
            "action_date": "The date the filing action took effect.",
            "annotations": "Annotations Companies House added to the filing.",
            "associated_filings": "Filings submitted alongside this one.",
            "resolutions": "Resolutions attached to the filing.",
            "links": "Links to the filing and its document metadata.",
        },
    },
    CHARGES: {
        "description": "Mortgages and charges registered against a company.",
        "docs_url": f"{_RESOURCES_URL}/chargelist?v=latest",
        "columns": {
            "company_number": _COMPANY_NUMBER,
            "id": "The identifier of the charge.",
            "charge_code": "The charge code allocated by Companies House.",
            "charge_number": "The number of the charge within the company's charge list.",
            "status": "The status of the charge, for example outstanding or fully-satisfied.",
            "classification": "The classification of the charge.",
            "particulars": "The particulars of the charge, including the property secured.",
            "persons_entitled": "The parties entitled to the charge.",
            "secured_details": "What the charge secures.",
            "transactions": "The filings that created or amended the charge.",
            "insolvency_cases": "Insolvency cases linked to the charge.",
            "scottish_alterations": "Alteration flags that apply to Scottish charges.",
            "created_on": "The date the charge was created.",
            "delivered_on": "The date the charge was delivered to Companies House.",
            "acquired_on": "The date the property subject to the charge was acquired.",
            "satisfied_on": "The date the charge was satisfied.",
            "resolved_on": "The date the charge was resolved.",
            "links": "Links to the charge resource.",
            "etag": "The ETag of the resource at Companies House.",
        },
    },
    INSOLVENCY: {
        "description": "Insolvency status and cases for a company. One row per company, with the cases nested.",
        "docs_url": f"{_RESOURCES_URL}/companyinsolvency?v=latest",
        "columns": {
            "company_number": _COMPANY_NUMBER,
            "status": "The insolvency status of the company, for example liquidation or in-administration.",
            "cases": "The insolvency cases recorded against the company, each with its type, dates, notes and practitioners.",
            "etag": "The ETag of the resource at Companies House.",
        },
    },
    REGISTERS: {
        "description": "Which statutory registers a company keeps at Companies House rather than at its own registered office. One row per company.",
        "docs_url": _REFERENCE_URL,
        "columns": {
            "company_number": _COMPANY_NUMBER,
            "registers": "The registers held, keyed by register type, each with its register entries and moved-on dates.",
            "kind": "The resource kind, always registers.",
            "links": "Links to the company and its register resources.",
            "etag": "The ETag of the resource at Companies House.",
        },
    },
    EXEMPTIONS: {
        "description": "Exemptions a company holds from filing person with significant control information. One row per company.",
        "docs_url": _REFERENCE_URL,
        "columns": {
            "company_number": _COMPANY_NUMBER,
            "exemptions": "The exemptions held, each with the periods it applied for.",
            "kind": "The resource kind, always exemptions.",
            "links": "Links to the company resource.",
            "etag": "The ETag of the resource at Companies House.",
        },
    },
    UK_ESTABLISHMENTS: {
        "description": "UK establishments registered by an overseas company.",
        "docs_url": _REFERENCE_URL,
        "columns": {
            "parent_company_number": "The company number of the overseas company the establishment belongs to.",
            "company_number": "The company number of the UK establishment.",
            "company_name": "The name of the UK establishment.",
            "company_status": "The status of the UK establishment.",
            "locality": "The locality of the UK establishment.",
            "kind": "The resource kind, always uk-establishment.",
            "links": "Links to the establishment's company resource.",
            "etag": "The ETag of the resource at Companies House.",
        },
    },
}
