from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Descriptions taken from the Northpass (Gainsight Customer Education) API reference:
# https://developers.northpass.com/reference
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "people": {
        "description": "Learners and admins in your Northpass school. One row per person.",
        "docs_url": "https://developers.northpass.com/reference/get_v2-people",
        "columns": {
            "id": "Unique identifier (UUID) for the person.",
            "type": "JSON:API resource type, always 'people'.",
            "email": "The person's email address.",
            "first_name": "The person's first name.",
            "last_name": "The person's last name.",
            "full_name": "The person's full name.",
            "name": "Display name for the person.",
            "registration_status": "Where the person is in the registration flow.",
            "disabled": "Whether the person's account is disabled.",
            "unsubscribed": "Whether the person has unsubscribed from emails.",
            "custom_avatar_url": "URL of the person's custom avatar image, if set.",
            "activated_at": "Timestamp when the person's account was activated.",
            "created_at": "Timestamp when the person was created.",
            "updated_at": "Timestamp when the person was last updated.",
        },
    },
    "courses": {
        "description": "Courses available in your Northpass school. One row per course.",
        "docs_url": "https://developers.northpass.com/reference/get_v2-courses",
        "columns": {
            "id": "Unique identifier (UUID) for the course.",
            "type": "JSON:API resource type, always 'courses'.",
            "name": "The course name.",
            "status": "Publication status of the course (e.g. draft, published, archived).",
            "permalink": "URL-safe slug for the course.",
            "short_description": "Short description of the course.",
            "full_description": "Full description of the course.",
            "enrollments_count": "Number of enrollments in the course.",
            "credential_achievement_count": "Number of credentials achieved through the course.",
            "list_image_url": "URL of the course's list image.",
            "ribbon": "Ribbon label shown on the course card, if any.",
            "unpublished_changes": "Whether the course has unpublished draft changes.",
            "dependent_course_names": "Names of courses this course depends on.",
            "created_at": "Timestamp when the course was created.",
            "updated_at": "Timestamp when the course was last updated.",
        },
    },
    "learning_paths": {
        "description": "Learning paths (ordered collections of courses). One row per learning path.",
        "docs_url": "https://developers.northpass.com/reference/get_v2-learning-paths",
        "columns": {
            "id": "Unique identifier (UUID) for the learning path.",
            "type": "JSON:API resource type, always 'learning_paths'.",
            "name": "The learning path name.",
            "description": "Description of the learning path.",
            "navigation_mode": "How learners move through the path (e.g. linear).",
            "picture_url": "URL of the learning path's image.",
            "learning_path_enrollment_link": "Public enrollment link for the learning path.",
            "share_learning_path_link": "Public share link for the learning path.",
            "created_at": "Timestamp when the learning path was created.",
            "updated_at": "Timestamp when the learning path was last updated.",
        },
    },
    "categories": {
        "description": "Categories used to organize courses. One row per category.",
        "docs_url": "https://developers.northpass.com/reference/get_v2-categories",
        "columns": {
            "id": "Unique identifier (UUID) for the category.",
            "type": "JSON:API resource type, always 'categories'.",
            "name": "The category name.",
            "created_at": "Timestamp when the category was created.",
            "updated_at": "Timestamp when the category was last updated.",
        },
    },
    "groups": {
        "description": "Groups that people can belong to. One row per group.",
        "docs_url": "https://developers.northpass.com/reference/get_v2-groups",
        "columns": {
            "id": "Unique identifier (UUID) for the group.",
            "type": "JSON:API resource type, always 'groups'.",
            "name": "The group name.",
            "memberships_count": "Number of members in the group.",
            "membership_count": "Number of members in the group (legacy field).",
            "group_enrollment_link": "Public enrollment link for the group.",
            "created_at": "Timestamp when the group was created.",
            "updated_at": "Timestamp when the group was last updated.",
        },
    },
    "quizzes": {
        "description": "Quizzes configured across your courses. One row per quiz.",
        "docs_url": "https://developers.northpass.com/reference/get_v2-quizzes",
        "columns": {
            "id": "Unique identifier (UUID) for the quiz.",
            "type": "JSON:API resource type, always 'quizzes'.",
            "name": "The quiz name.",
            "quiz_type": "The quiz type (e.g. Quizzes::Static).",
            "legacy_id": "Legacy integer identifier for the quiz.",
            "created_at": "Timestamp when the quiz was created.",
        },
    },
    "course_enrollments": {
        "description": "Course enrollments, one row per person enrolled in a course. Fanned out per course.",
        "docs_url": "https://developers.northpass.com/reference/get_v2-courses-course-uuid-enrollments",
        "columns": {
            "id": "Unique identifier (UUID) for the enrollment.",
            "type": "JSON:API resource type, always 'course_enrollments'.",
            "course_id": "UUID of the course the enrollment belongs to.",
            "person_id": "UUID of the enrolled person.",
            "progress": "Completion progress of the enrollment (0-100).",
            "enrolled_at": "Timestamp when the person enrolled.",
            "last_active_on": "Timestamp of the person's last activity in the course.",
        },
    },
    "learning_path_enrollments": {
        "description": "Learning path enrollments, one row per person enrolled in a learning path. Fanned out per learning path.",
        "docs_url": "https://developers.northpass.com/reference/get_v2-learning-paths-learning-path-uuid-enrollments",
        "columns": {
            "id": "Unique identifier (UUID) for the enrollment.",
            "type": "JSON:API resource type, always 'learning_path_enrollments'.",
            "learning_path_id": "UUID of the learning path the enrollment belongs to.",
            "person_id": "UUID of the enrolled person.",
            "progress": "Completion progress of the enrollment (0-100).",
            "enrolled_at": "Timestamp when the person enrolled.",
            "last_active_on": "Timestamp of the person's last activity in the learning path.",
        },
    },
}
