import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/host-capabilities.ts",
    "src/url-launcher.ts",
    "src/storage-paths.ts",
    "src/app-meta.ts",
    "src/dialog.ts",
    "src/clipboard.ts",
    "src/file-icon.ts",
    "src/secure-storage.ts",
    "src/main-window.ts",
    "src/app-lifecycle.ts",
    "src/power-manager.ts",
    "src/updater.ts",
    "src/notifier.ts",
    "src/speech.ts",
    "src/notifications.ts",
    "src/context-menu.ts",
    "src/bundled-resources.ts",
    "src/image-processor.ts",
    "src/workspace-settings.ts",
    "src/crypto.ts",
    "src/analytics.ts",
    "src/deep-link.ts",
    "src/app-metrics.ts",
    "src/dev-host-actions.ts",
  ],
  format: ["esm"],
  dts: true,
  sourcemap: true,
  clean: true,
  splitting: false,
  outDir: "dist",
  target: "es2022",
});
