from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

# Sourced from the WordPress core REST API handbook (https://developer.wordpress.org/rest-api/reference/).
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "posts": {
        "description": "Blog posts published on the WordPress site.",
        "docs_url": "https://developer.wordpress.org/rest-api/reference/posts/",
        "columns": {
            "id": "Unique identifier for the post.",
            "date": "The post's publication date, in the site's timezone.",
            "date_gmt": "The post's publication date, as GMT.",
            "modified": "The date the post was last modified, in the site's timezone.",
            "modified_gmt": "The date the post was last modified, as GMT.",
            "slug": "An alphanumeric identifier for the post, unique to its type.",
            "status": "A named status for the post (e.g. publish, draft, pending).",
            "type": "Type of post (e.g. post).",
            "link": "URL to the post.",
            "title": "The title for the post.",
            "content": "The content for the post.",
            "excerpt": "The excerpt for the post.",
            "author": "The ID for the author of the post.",
            "featured_media": "The ID of the featured media for the post.",
            "comment_status": "Whether or not comments are open on the post.",
            "ping_status": "Whether or not the post can be pinged.",
            "sticky": "Whether or not the post should be treated as sticky.",
            "categories": "The terms assigned to the post in the category taxonomy.",
            "tags": "The terms assigned to the post in the post_tag taxonomy.",
        },
    },
    "pages": {
        "description": "Static pages published on the WordPress site.",
        "docs_url": "https://developer.wordpress.org/rest-api/reference/pages/",
        "columns": {
            "id": "Unique identifier for the page.",
            "date": "The page's publication date, in the site's timezone.",
            "modified": "The date the page was last modified, in the site's timezone.",
            "slug": "An alphanumeric identifier for the page, unique to its type.",
            "status": "A named status for the page (e.g. publish, draft).",
            "parent": "The ID for the parent of the page.",
            "menu_order": "The order of the page in relation to other pages.",
            "title": "The title for the page.",
            "content": "The content for the page.",
            "author": "The ID for the author of the page.",
        },
    },
    "comments": {
        "description": "Comments left on posts and pages.",
        "docs_url": "https://developer.wordpress.org/rest-api/reference/comments/",
        "columns": {
            "id": "Unique identifier for the comment.",
            "post": "The ID of the associated post object.",
            "parent": "The ID for the parent of the comment.",
            "author": "The ID of the user object, if author was a user.",
            "author_name": "Display name for the comment author.",
            "author_email": "Email address for the comment author.",
            "date": "The date the comment was published, in the site's timezone.",
            "date_gmt": "The date the comment was published, as GMT.",
            "content": "The content of the comment.",
            "link": "URL to the comment.",
            "status": "State of the comment (e.g. approved, hold, spam).",
            "type": "Type of the comment.",
        },
    },
    "media": {
        "description": "Media library items (attachments) such as images and documents.",
        "docs_url": "https://developer.wordpress.org/rest-api/reference/media/",
        "columns": {
            "id": "Unique identifier for the attachment.",
            "date": "The attachment's publication date, in the site's timezone.",
            "modified": "The date the attachment was last modified, in the site's timezone.",
            "slug": "An alphanumeric identifier for the attachment, unique to its type.",
            "status": "A named status for the attachment.",
            "title": "The title for the attachment.",
            "author": "The ID for the author of the attachment.",
            "media_type": "Type of attachment (e.g. image, file).",
            "mime_type": "MIME type of the attachment.",
            "source_url": "URL to the original attachment file.",
            "alt_text": "Alternative text to display when attachment is not displayed.",
            "caption": "The attachment caption.",
            "post": "The ID for the associated post of the attachment.",
        },
    },
    "categories": {
        "description": "Terms in the built-in category taxonomy.",
        "docs_url": "https://developer.wordpress.org/rest-api/reference/categories/",
        "columns": {
            "id": "Unique identifier for the category.",
            "count": "Number of published posts for the category.",
            "description": "HTML description of the category.",
            "name": "HTML title for the category.",
            "slug": "An alphanumeric identifier for the category unique to its type.",
            "parent": "The parent category ID.",
            "taxonomy": "Type attribution for the category (category).",
        },
    },
    "tags": {
        "description": "Terms in the built-in post_tag taxonomy.",
        "docs_url": "https://developer.wordpress.org/rest-api/reference/tags/",
        "columns": {
            "id": "Unique identifier for the tag.",
            "count": "Number of published posts for the tag.",
            "description": "HTML description of the tag.",
            "name": "HTML title for the tag.",
            "slug": "An alphanumeric identifier for the tag unique to its type.",
            "taxonomy": "Type attribution for the tag (post_tag).",
        },
    },
    "users": {
        "description": "Users who have authored published content on the site.",
        "docs_url": "https://developer.wordpress.org/rest-api/reference/users/",
        "columns": {
            "id": "Unique identifier for the user.",
            "name": "Display name for the user.",
            "url": "URL of the user.",
            "description": "Description of the user.",
            "link": "Author URL of the user.",
            "slug": "An alphanumeric identifier for the user.",
        },
    },
}
