import { FunnelLayout, ShownAsValue } from 'lib/constants'

import {
    AccessControlLevel,
    ChartDisplayType,
    DashboardTile,
    DashboardType,
    FunnelVizType,
    InsightColor,
    InsightShortId,
    InsightType,
} from '~/types'

export const dashboard: DashboardType = {
    id: 1,
    name: 'My App Dashboard',
    description: '',
    pinned: true,
    tiles: [
        {
            id: 0,
            layouts: {
                sm: {
                    h: 5,
                    w: 6,
                    x: 0,
                    y: 0,
                    minH: 5,
                    minW: 3,
                },
                xs: {
                    h: 5,
                    w: 1,
                    x: 0,
                    y: 0,
                    minH: 5,
                    minW: 3,
                    moved: false,
                    static: false,
                },
            },
            color: InsightColor.Blue,
            last_refresh: '2022-07-01T13:33:12.871519Z',
            insight: {
                id: 1,
                short_id: 'Bhtk8tjh' as InsightShortId,
                last_refresh: '2022-07-01T13:33:12.871519Z',
                name: 'Daily active users (DAUs)',
                derived_name: null,
                filters: {
                    events: [
                        {
                            id: '$pageview',
                            math: 'dau',
                            type: 'events',
                        },
                    ],
                    insight: InsightType.TRENDS,
                    interval: 'day',
                },
                order: null,
                deleted: false,
                dashboards: [1],
                dashboard_tiles: [{ id: 1, dashboard_id: 1 }],
                result: [
                    {
                        action: {
                            id: '$pageview',
                            type: 'events',
                            order: null,
                            name: '$pageview',
                            custom_name: null,
                            math: 'dau',
                            math_property: null,
                            math_group_type_index: null,
                            properties: {},
                        },
                        label: '$pageview',
                        count: 235.0,
                        data: [0.0, 0.0, 0.0, 0.0, 0.0, 93.0, 0.0, 142.0],
                        labels: [
                            '24-Jun-2022',
                            '25-Jun-2022',
                            '26-Jun-2022',
                            '27-Jun-2022',
                            '28-Jun-2022',
                            '29-Jun-2022',
                            '30-Jun-2022',
                            '1-Jul-2022',
                        ],
                        days: [
                            '2022-06-24',
                            '2022-06-25',
                            '2022-06-26',
                            '2022-06-27',
                            '2022-06-28',
                            '2022-06-29',
                            '2022-06-30',
                            '2022-07-01',
                        ],
                        persons_urls: [
                            {
                                filter: {
                                    entity_id: '$pageview',
                                    entity_type: 'events',
                                    entity_math: 'dau',
                                    date_from: '2022-06-24T00:00:00Z',
                                    date_to: '2022-06-24T00:00:00Z',
                                    entity_order: null,
                                },
                                url: 'api/projects/1/persons/trends/?breakdown_attribution_type=first_touch&display=ActionsLineGraph&events=%5B%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+%22dau%22%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%5D&insight=TRENDS&interval=day&smoothing_intervals=1&entity_id=%24pageview&entity_type=events&entity_math=dau&date_from=2022-06-24T00%3A00%3A00%2B00%3A00&date_to=2022-06-24T00%3A00%3A00%2B00%3A00',
                            },
                            {
                                filter: {
                                    entity_id: '$pageview',
                                    entity_type: 'events',
                                    entity_math: 'dau',
                                    date_from: '2022-06-25T00:00:00Z',
                                    date_to: '2022-06-25T00:00:00Z',
                                    entity_order: null,
                                },
                                url: 'api/projects/1/persons/trends/?breakdown_attribution_type=first_touch&display=ActionsLineGraph&events=%5B%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+%22dau%22%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%5D&insight=TRENDS&interval=day&smoothing_intervals=1&entity_id=%24pageview&entity_type=events&entity_math=dau&date_from=2022-06-25T00%3A00%3A00%2B00%3A00&date_to=2022-06-25T00%3A00%3A00%2B00%3A00',
                            },
                            {
                                filter: {
                                    entity_id: '$pageview',
                                    entity_type: 'events',
                                    entity_math: 'dau',
                                    date_from: '2022-06-26T00:00:00Z',
                                    date_to: '2022-06-26T00:00:00Z',
                                    entity_order: null,
                                },
                                url: 'api/projects/1/persons/trends/?breakdown_attribution_type=first_touch&display=ActionsLineGraph&events=%5B%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+%22dau%22%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%5D&insight=TRENDS&interval=day&smoothing_intervals=1&entity_id=%24pageview&entity_type=events&entity_math=dau&date_from=2022-06-26T00%3A00%3A00%2B00%3A00&date_to=2022-06-26T00%3A00%3A00%2B00%3A00',
                            },
                            {
                                filter: {
                                    entity_id: '$pageview',
                                    entity_type: 'events',
                                    entity_math: 'dau',
                                    date_from: '2022-06-27T00:00:00Z',
                                    date_to: '2022-06-27T00:00:00Z',
                                    entity_order: null,
                                },
                                url: 'api/projects/1/persons/trends/?breakdown_attribution_type=first_touch&display=ActionsLineGraph&events=%5B%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+%22dau%22%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%5D&insight=TRENDS&interval=day&smoothing_intervals=1&entity_id=%24pageview&entity_type=events&entity_math=dau&date_from=2022-06-27T00%3A00%3A00%2B00%3A00&date_to=2022-06-27T00%3A00%3A00%2B00%3A00',
                            },
                            {
                                filter: {
                                    entity_id: '$pageview',
                                    entity_type: 'events',
                                    entity_math: 'dau',
                                    date_from: '2022-06-28T00:00:00Z',
                                    date_to: '2022-06-28T00:00:00Z',
                                    entity_order: null,
                                },
                                url: 'api/projects/1/persons/trends/?breakdown_attribution_type=first_touch&display=ActionsLineGraph&events=%5B%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+%22dau%22%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%5D&insight=TRENDS&interval=day&smoothing_intervals=1&entity_id=%24pageview&entity_type=events&entity_math=dau&date_from=2022-06-28T00%3A00%3A00%2B00%3A00&date_to=2022-06-28T00%3A00%3A00%2B00%3A00',
                            },
                            {
                                filter: {
                                    entity_id: '$pageview',
                                    entity_type: 'events',
                                    entity_math: 'dau',
                                    date_from: '2022-06-29T00:00:00Z',
                                    date_to: '2022-06-29T00:00:00Z',
                                    entity_order: null,
                                },
                                url: 'api/projects/1/persons/trends/?breakdown_attribution_type=first_touch&display=ActionsLineGraph&events=%5B%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+%22dau%22%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%5D&insight=TRENDS&interval=day&smoothing_intervals=1&entity_id=%24pageview&entity_type=events&entity_math=dau&date_from=2022-06-29T00%3A00%3A00%2B00%3A00&date_to=2022-06-29T00%3A00%3A00%2B00%3A00',
                            },
                            {
                                filter: {
                                    entity_id: '$pageview',
                                    entity_type: 'events',
                                    entity_math: 'dau',
                                    date_from: '2022-06-30T00:00:00Z',
                                    date_to: '2022-06-30T00:00:00Z',
                                    entity_order: null,
                                },
                                url: 'api/projects/1/persons/trends/?breakdown_attribution_type=first_touch&display=ActionsLineGraph&events=%5B%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+%22dau%22%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%5D&insight=TRENDS&interval=day&smoothing_intervals=1&entity_id=%24pageview&entity_type=events&entity_math=dau&date_from=2022-06-30T00%3A00%3A00%2B00%3A00&date_to=2022-06-30T00%3A00%3A00%2B00%3A00',
                            },
                            {
                                filter: {
                                    entity_id: '$pageview',
                                    entity_type: 'events',
                                    entity_math: 'dau',
                                    date_from: '2022-07-01T00:00:00Z',
                                    date_to: '2022-07-01T00:00:00Z',
                                    entity_order: null,
                                },
                                url: 'api/projects/1/persons/trends/?breakdown_attribution_type=first_touch&display=ActionsLineGraph&events=%5B%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+%22dau%22%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%5D&insight=TRENDS&interval=day&smoothing_intervals=1&entity_id=%24pageview&entity_type=events&entity_math=dau&date_from=2022-07-01T00%3A00%3A00%2B00%3A00&date_to=2022-07-01T00%3A00%3A00%2B00%3A00',
                            },
                        ],
                        filter: {
                            breakdown_attribution_type: 'first_touch',
                            display: 'ActionsLineGraph',
                            events: [
                                {
                                    id: '$pageview',
                                    type: 'events',
                                    order: null,
                                    name: '$pageview',
                                    custom_name: null,
                                    math: 'dau',
                                    math_property: null,
                                    math_group_type_index: null,
                                    properties: {},
                                },
                            ],
                            insight: InsightType.TRENDS,
                            interval: 'day',
                            smoothing_intervals: 1,
                        },
                    },
                ],
                created_at: '2022-06-29T10:18:57.715671Z',
                created_by: null,
                description: 'Shows the number of unique users that use your app every day.',
                updated_at: '2022-06-29T10:18:57.715760Z',
                favorited: false,
                saved: false,
                last_modified_at: '2022-06-29T10:18:57.714051Z',
                last_modified_by: null,
                is_sample: false,
                effective_restriction_level: 37,
                effective_privilege_level: 37,
                timezone: null,
                tags: [],
                user_access_level: AccessControlLevel.Editor,
            },
        } as DashboardTile,
        {
            id: 1,
            layouts: {
                sm: {
                    h: 5,
                    w: 6,
                    x: 6,
                    y: 0,
                    minH: 5,
                    minW: 3,
                },
                xs: {
                    h: 5,
                    w: 1,
                    x: 0,
                    y: 5,
                    minH: 5,
                    minW: 3,
                    moved: false,
                    static: false,
                },
            },
            color: InsightColor.Green,
            last_refresh: '2022-07-01T13:33:13.630227Z',
            insight: {
                last_refresh: '2022-07-01T13:33:13.630227Z',

                id: 2,
                short_id: 'e8FxXHZ6' as InsightShortId,
                name: 'Weekly active users (WAUs)',
                derived_name: null,
                filters: {
                    events: [
                        {
                            id: '$pageview',
                            math: 'weekly_active',
                            type: 'events',
                        },
                    ],
                    insight: InsightType.TRENDS,
                    interval: 'week',
                },
                order: null,
                deleted: false,
                dashboards: [1],
                dashboard_tiles: [{ id: 1, dashboard_id: 1 }],
                result: [
                    {
                        action: {
                            id: '$pageview',
                            type: 'events',
                            order: null,
                            name: '$pageview',
                            custom_name: null,
                            math: 'weekly_active',
                            math_property: null,
                            math_group_type_index: null,
                            properties: {},
                        },
                        label: '$pageview',
                        count: 327.0,
                        data: [0.0, 0.0, 93.0, 234.0],
                        labels: ['19-Jun-2022', '26-Jun-2022', '29-Jun-2022', '1-Jul-2022'],
                        days: ['2022-06-19', '2022-06-26', '2022-06-29', '2022-07-01'],
                        persons_urls: [
                            {
                                filter: {
                                    entity_id: '$pageview',
                                    entity_type: 'events',
                                    entity_math: 'weekly_active',
                                    date_from: '2022-06-19T00:00:00Z',
                                    date_to: '2022-06-19T00:00:00Z',
                                    entity_order: null,
                                },
                                url: 'api/projects/1/persons/trends/?breakdown_attribution_type=first_touch&display=ActionsLineGraph&events=%5B%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+%22weekly_active%22%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%5D&insight=TRENDS&interval=week&smoothing_intervals=1&entity_id=%24pageview&entity_type=events&entity_math=weekly_active&date_from=2022-06-19T00%3A00%3A00%2B00%3A00&date_to=2022-06-19T00%3A00%3A00%2B00%3A00',
                            },
                            {
                                filter: {
                                    entity_id: '$pageview',
                                    entity_type: 'events',
                                    entity_math: 'weekly_active',
                                    date_from: '2022-06-26T00:00:00Z',
                                    date_to: '2022-06-26T00:00:00Z',
                                    entity_order: null,
                                },
                                url: 'api/projects/1/persons/trends/?breakdown_attribution_type=first_touch&display=ActionsLineGraph&events=%5B%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+%22weekly_active%22%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%5D&insight=TRENDS&interval=week&smoothing_intervals=1&entity_id=%24pageview&entity_type=events&entity_math=weekly_active&date_from=2022-06-26T00%3A00%3A00%2B00%3A00&date_to=2022-06-26T00%3A00%3A00%2B00%3A00',
                            },
                            {
                                filter: {
                                    entity_id: '$pageview',
                                    entity_type: 'events',
                                    entity_math: 'weekly_active',
                                    date_from: '2022-06-29T00:00:00Z',
                                    date_to: '2022-06-29T00:00:00Z',
                                    entity_order: null,
                                },
                                url: 'api/projects/1/persons/trends/?breakdown_attribution_type=first_touch&display=ActionsLineGraph&events=%5B%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+%22weekly_active%22%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%5D&insight=TRENDS&interval=week&smoothing_intervals=1&entity_id=%24pageview&entity_type=events&entity_math=weekly_active&date_from=2022-06-29T00%3A00%3A00%2B00%3A00&date_to=2022-06-29T00%3A00%3A00%2B00%3A00',
                            },
                            {
                                filter: {
                                    entity_id: '$pageview',
                                    entity_type: 'events',
                                    entity_math: 'weekly_active',
                                    date_from: '2022-07-01T00:00:00Z',
                                    date_to: '2022-07-01T00:00:00Z',
                                    entity_order: null,
                                },
                                url: 'api/projects/1/persons/trends/?breakdown_attribution_type=first_touch&display=ActionsLineGraph&events=%5B%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+%22weekly_active%22%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%5D&insight=TRENDS&interval=week&smoothing_intervals=1&entity_id=%24pageview&entity_type=events&entity_math=weekly_active&date_from=2022-07-01T00%3A00%3A00%2B00%3A00&date_to=2022-07-01T00%3A00%3A00%2B00%3A00',
                            },
                        ],
                        filter: {
                            breakdown_attribution_type: 'first_touch',
                            display: 'ActionsLineGraph',
                            events: [
                                {
                                    id: '$pageview',
                                    type: 'events',
                                    order: null,
                                    name: '$pageview',
                                    custom_name: null,
                                    math: 'weekly_active',
                                    math_property: null,
                                    math_group_type_index: null,
                                    properties: {},
                                },
                            ],
                            insight: InsightType.TRENDS,
                            interval: 'week',
                            smoothing_intervals: 1,
                        },
                    },
                ],
                created_at: '2022-06-29T10:18:57.724595Z',
                created_by: null,
                description: 'Shows the number of unique users that use your app every week.',
                updated_at: '2022-06-29T10:18:57.724674Z',
                favorited: false,
                saved: false,
                last_modified_at: '2022-06-29T10:18:57.723355Z',
                last_modified_by: null,
                is_sample: false,
                effective_restriction_level: 37,
                effective_privilege_level: 37,
                timezone: null,
                tags: [],
                user_access_level: AccessControlLevel.Editor,
            },
        } as DashboardTile,
        {
            id: 2,
            layouts: {
                sm: {
                    h: 5,
                    w: 6,
                    x: 0,
                    y: 10,
                    minH: 5,
                    minW: 3,
                },
                xs: {
                    h: 5,
                    w: 1,
                    x: 0,
                    y: 20,
                    minH: 5,
                    minW: 3,
                    moved: false,
                    static: false,
                },
            },
            color: InsightColor.Black,
            last_refresh: '2022-07-01T13:33:13.694015Z',
            insight: {
                id: 5,
                short_id: 'sMPkWHir' as InsightShortId,
                name: 'Referring domain (last 14 days)',
                derived_name: null,
                filters: {
                    events: [
                        {
                            id: '$pageview',
                            math: 'dau',
                            type: 'events',
                        },
                    ],
                    display: ChartDisplayType.ActionsBarValue,
                    insight: InsightType.TRENDS,
                    interval: 'day',
                    breakdown: '$referring_domain',
                    date_from: '-14d',
                    breakdown_type: 'event',
                },
                last_refresh: '2022-07-01T13:33:13.694015Z',
                order: null,
                deleted: false,
                dashboards: [1],
                dashboard_tiles: [{ id: 1, dashboard_id: 1 }],
                result: [
                    {
                        action: {
                            id: '$pageview',
                            type: 'events',
                            order: null,
                            name: '$pageview',
                            custom_name: null,
                            math: 'dau',
                            math_property: null,
                            math_group_type_index: null,
                            properties: {},
                        },
                        label: '$pageview - none',
                        count: 0,
                        data: [],
                        labels: [],
                        days: [
                            '2022-06-17',
                            '2022-06-18',
                            '2022-06-19',
                            '2022-06-20',
                            '2022-06-21',
                            '2022-06-22',
                            '2022-06-23',
                            '2022-06-24',
                            '2022-06-25',
                            '2022-06-26',
                            '2022-06-27',
                            '2022-06-28',
                            '2022-06-29',
                            '2022-06-30',
                            '2022-07-01',
                        ],
                        aggregated_value: 233,
                        filter: {
                            breakdown: '$referring_domain',
                            breakdown_attribution_type: 'first_touch',
                            breakdown_type: 'event',
                            date_from: '-14d',
                            display: 'ActionsBarValue',
                            events: '[{"id": "$pageview", "type": "events", "order": null, "name": "$pageview", "custom_name": null, "math": "dau", "math_property": null, "math_group_type_index": null, "properties": {}}]',
                            insight: InsightType.TRENDS,
                            interval: 'day',
                            smoothing_intervals: 1,
                        },
                        persons: {
                            filter: {
                                entity_id: '$pageview',
                                entity_type: 'events',
                                breakdown_value: '',
                                breakdown_type: 'event',
                            },
                            url: 'api/projects/1/persons/trends/?breakdown=%24referring_domain&breakdown_attribution_type=first_touch&breakdown_type=event&date_from=-14d&display=ActionsBarValue&events=%5B%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+%22dau%22%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%5D&insight=TRENDS&interval=day&smoothing_intervals=1&entity_id=%24pageview&entity_type=events&breakdown_value=',
                        },
                        breakdown_value: '',
                    },
                    {
                        action: {
                            id: '$pageview',
                            type: 'events',
                            order: null,
                            name: '$pageview',
                            custom_name: null,
                            math: 'dau',
                            math_property: null,
                            math_group_type_index: null,
                            properties: {},
                        },
                        label: '$pageview - localhost:8000',
                        count: 0,
                        data: [],
                        labels: [],
                        days: [
                            '2022-06-17',
                            '2022-06-18',
                            '2022-06-19',
                            '2022-06-20',
                            '2022-06-21',
                            '2022-06-22',
                            '2022-06-23',
                            '2022-06-24',
                            '2022-06-25',
                            '2022-06-26',
                            '2022-06-27',
                            '2022-06-28',
                            '2022-06-29',
                            '2022-06-30',
                            '2022-07-01',
                        ],
                        aggregated_value: 1,
                        filter: {
                            breakdown: '$referring_domain',
                            breakdown_attribution_type: 'first_touch',
                            breakdown_type: 'event',
                            date_from: '-14d',
                            display: 'ActionsBarValue',
                            events: '[{"id": "$pageview", "type": "events", "order": null, "name": "$pageview", "custom_name": null, "math": "dau", "math_property": null, "math_group_type_index": null, "properties": {}}]',
                            insight: InsightType.TRENDS,
                            interval: 'day',
                            smoothing_intervals: 1,
                        },
                        persons: {
                            filter: {
                                entity_id: '$pageview',
                                entity_type: 'events',
                                breakdown_value: 'localhost:8000',
                                breakdown_type: 'event',
                            },
                            url: 'api/projects/1/persons/trends/?breakdown=%24referring_domain&breakdown_attribution_type=first_touch&breakdown_type=event&date_from=-14d&display=ActionsBarValue&events=%5B%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+%22dau%22%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%5D&insight=TRENDS&interval=day&smoothing_intervals=1&entity_id=%24pageview&entity_type=events&breakdown_value=localhost%3A8000',
                        },
                        breakdown_value: 'localhost:8000',
                    },
                ],
                created_at: '2022-06-29T10:18:57.750861Z',
                created_by: null,
                description: 'Shows the most common referring domains for your users over the past 14 days.',
                updated_at: '2022-06-29T10:18:57.750934Z',
                favorited: false,
                saved: false,
                last_modified_at: '2022-06-29T10:18:57.749799Z',
                last_modified_by: null,
                is_sample: false,
                effective_restriction_level: 37,
                effective_privilege_level: 37,
                timezone: null,
                tags: [],
                user_access_level: AccessControlLevel.Editor,
            },
        } as DashboardTile,
        {
            id: 3,
            layouts: {
                sm: {
                    h: 5,
                    w: 6,
                    x: 0,
                    y: 5,
                    minH: 5,
                    minW: 3,
                },
                xs: {
                    h: 5,
                    w: 1,
                    x: 0,
                    y: 15,
                    minH: 5,
                    minW: 3,
                    moved: false,
                    static: false,
                },
            },
            color: InsightColor.Purple,
            last_refresh: '2022-07-01T13:33:14.001864Z',
            insight: {
                id: 4,
                short_id: 'KcoMGkag' as InsightShortId,
                name: 'Growth accounting',
                derived_name: null,
                filters: {
                    events: [
                        {
                            id: '$pageview',
                            type: 'events',
                        },
                    ],
                    insight: InsightType.LIFECYCLE,
                    interval: 'week',
                    shown_as: ShownAsValue.LIFECYCLE,
                    date_from: '-30d',
                    entity_type: 'events',
                },

                order: null,
                deleted: false,
                dashboards: [1],
                dashboard_tiles: [{ id: 1, dashboard_id: 1 }],
                last_refresh: '2022-07-01T13:33:14.001864Z',
                result: [
                    {
                        action: {
                            id: '$pageview',
                            type: 'events',
                            order: null,
                            name: '$pageview',
                            custom_name: null,
                            math: null,
                            math_property: null,
                            math_group_type_index: null,
                            properties: {},
                        },
                        label: '$pageview - new',
                        count: 234.0,
                        data: [0.0, 0.0, 0.0, 0.0, 234.0],
                        labels: ['30-May-2022', '6-Jun-2022', '13-Jun-2022', '20-Jun-2022', '27-Jun-2022'],
                        days: ['2022-05-30', '2022-06-06', '2022-06-13', '2022-06-20', '2022-06-27'],
                        status: 'new',
                    },
                    {
                        action: {
                            id: '$pageview',
                            type: 'events',
                            order: null,
                            name: '$pageview',
                            custom_name: null,
                            math: null,
                            math_property: null,
                            math_group_type_index: null,
                            properties: {},
                        },
                        label: '$pageview - dormant',
                        count: 0.0,
                        data: [0.0, 0.0, 0.0, 0.0, 0.0],
                        labels: ['30-May-2022', '6-Jun-2022', '13-Jun-2022', '20-Jun-2022', '27-Jun-2022'],
                        days: ['2022-05-30', '2022-06-06', '2022-06-13', '2022-06-20', '2022-06-27'],
                        status: 'dormant',
                    },
                    {
                        action: {
                            id: '$pageview',
                            type: 'events',
                            order: null,
                            name: '$pageview',
                            custom_name: null,
                            math: null,
                            math_property: null,
                            math_group_type_index: null,
                            properties: {},
                        },
                        label: '$pageview - resurrecting',
                        count: 0.0,
                        data: [0.0, 0.0, 0.0, 0.0, 0.0],
                        labels: ['30-May-2022', '6-Jun-2022', '13-Jun-2022', '20-Jun-2022', '27-Jun-2022'],
                        days: ['2022-05-30', '2022-06-06', '2022-06-13', '2022-06-20', '2022-06-27'],
                        status: 'resurrecting',
                    },
                    {
                        action: {
                            id: '$pageview',
                            type: 'events',
                            order: null,
                            name: '$pageview',
                            custom_name: null,
                            math: null,
                            math_property: null,
                            math_group_type_index: null,
                            properties: {},
                        },
                        label: '$pageview - returning',
                        count: 0.0,
                        data: [0.0, 0.0, 0.0, 0.0, 0.0],
                        labels: ['30-May-2022', '6-Jun-2022', '13-Jun-2022', '20-Jun-2022', '27-Jun-2022'],
                        days: ['2022-05-30', '2022-06-06', '2022-06-13', '2022-06-20', '2022-06-27'],
                        status: 'returning',
                    },
                ],
                created_at: '2022-06-29T10:18:57.743718Z',
                created_by: null,
                description: 'How many of your users are new, returning, resurrecting, or dormant each week.',
                updated_at: '2022-06-29T10:18:57.743797Z',
                favorited: false,
                saved: false,
                last_modified_at: '2022-06-29T10:18:57.738355Z',
                last_modified_by: null,
                is_sample: false,
                effective_restriction_level: 37,
                effective_privilege_level: 37,
                timezone: null,
                tags: [],
                user_access_level: AccessControlLevel.Editor,
            },
        } as DashboardTile,
        {
            id: 4,
            layouts: {
                sm: {
                    h: 5,
                    w: 6,
                    x: 6,
                    y: 5,
                    minH: 5,
                    minW: 3,
                },
                xs: {
                    h: 5,
                    w: 1,
                    x: 0,
                    y: 10,
                    minH: 5,
                    minW: 3,
                    moved: false,
                    static: false,
                },
            },
            color: InsightColor.Blue,
            last_refresh: '2022-07-01T13:33:14.399653Z',
            insight: {
                id: 3,
                short_id: '4nk6BVnw' as InsightShortId,
                name: 'Retention',
                derived_name: null,
                filters: {
                    period: 'Week',
                    insight: InsightType.RETENTION,
                    target_entity: {
                        id: '$pageview',
                        type: 'events',
                    },
                    retention_type: 'retention_first_time',
                    returning_entity: {
                        id: '$pageview',
                        type: 'events',
                    },
                },

                order: null,
                deleted: false,
                dashboards: [1],
                dashboard_tiles: [{ id: 1, dashboard_id: 1 }],
                last_refresh: '2022-07-01T13:33:14.399653Z',
                result: [
                    {
                        values: [
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                        ],
                        label: 'Week 0',
                        date: '2022-04-17T00:00:00Z',
                        people_url:
                            '/api/person/retention/?breakdown_attribution_type=first_touch&breakdown_values=%5B0%5D&display=ActionsTable&insight=RETENTION&period=Week&retention_type=retention_first_time&returning_entity=%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D&target_entity=%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D&total_intervals=11',
                    },
                    {
                        values: [
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                        ],
                        label: 'Week 1',
                        date: '2022-04-24T00:00:00Z',
                        people_url:
                            '/api/person/retention/?breakdown_attribution_type=first_touch&breakdown_values=%5B1%5D&display=ActionsTable&insight=RETENTION&period=Week&retention_type=retention_first_time&returning_entity=%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D&target_entity=%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D&total_intervals=11',
                    },
                    {
                        values: [
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                        ],
                        label: 'Week 2',
                        date: '2022-05-01T00:00:00Z',
                        people_url:
                            '/api/person/retention/?breakdown_attribution_type=first_touch&breakdown_values=%5B2%5D&display=ActionsTable&insight=RETENTION&period=Week&retention_type=retention_first_time&returning_entity=%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D&target_entity=%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D&total_intervals=11',
                    },
                    {
                        values: [
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                        ],
                        label: 'Week 3',
                        date: '2022-05-08T00:00:00Z',
                        people_url:
                            '/api/person/retention/?breakdown_attribution_type=first_touch&breakdown_values=%5B3%5D&display=ActionsTable&insight=RETENTION&period=Week&retention_type=retention_first_time&returning_entity=%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D&target_entity=%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D&total_intervals=11',
                    },
                    {
                        values: [
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                        ],
                        label: 'Week 4',
                        date: '2022-05-15T00:00:00Z',
                        people_url:
                            '/api/person/retention/?breakdown_attribution_type=first_touch&breakdown_values=%5B4%5D&display=ActionsTable&insight=RETENTION&period=Week&retention_type=retention_first_time&returning_entity=%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D&target_entity=%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D&total_intervals=11',
                    },
                    {
                        values: [
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                        ],
                        label: 'Week 5',
                        date: '2022-05-22T00:00:00Z',
                        people_url:
                            '/api/person/retention/?breakdown_attribution_type=first_touch&breakdown_values=%5B5%5D&display=ActionsTable&insight=RETENTION&period=Week&retention_type=retention_first_time&returning_entity=%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D&target_entity=%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D&total_intervals=11',
                    },
                    {
                        values: [
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                        ],
                        label: 'Week 6',
                        date: '2022-05-29T00:00:00Z',
                        people_url:
                            '/api/person/retention/?breakdown_attribution_type=first_touch&breakdown_values=%5B6%5D&display=ActionsTable&insight=RETENTION&period=Week&retention_type=retention_first_time&returning_entity=%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D&target_entity=%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D&total_intervals=11',
                    },
                    {
                        values: [
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                        ],
                        label: 'Week 7',
                        date: '2022-06-05T00:00:00Z',
                        people_url:
                            '/api/person/retention/?breakdown_attribution_type=first_touch&breakdown_values=%5B7%5D&display=ActionsTable&insight=RETENTION&period=Week&retention_type=retention_first_time&returning_entity=%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D&target_entity=%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D&total_intervals=11',
                    },
                    {
                        values: [
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                        ],
                        label: 'Week 8',
                        date: '2022-06-12T00:00:00Z',
                        people_url:
                            '/api/person/retention/?breakdown_attribution_type=first_touch&breakdown_values=%5B8%5D&display=ActionsTable&insight=RETENTION&period=Week&retention_type=retention_first_time&returning_entity=%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D&target_entity=%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D&total_intervals=11',
                    },
                    {
                        values: [
                            {
                                count: 0,
                                people: [],
                            },
                            {
                                count: 0,
                                people: [],
                            },
                        ],
                        label: 'Week 9',
                        date: '2022-06-19T00:00:00Z',
                        people_url:
                            '/api/person/retention/?breakdown_attribution_type=first_touch&breakdown_values=%5B9%5D&display=ActionsTable&insight=RETENTION&period=Week&retention_type=retention_first_time&returning_entity=%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D&target_entity=%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D&total_intervals=11',
                    },
                    {
                        values: [
                            {
                                count: 234,
                                people: [],
                                people_url:
                                    '/api/person/retention/?breakdown_attribution_type=first_touch&breakdown_values=%5B10%5D&display=RetentionTable&insight=RETENTION&period=Week&retention_type=retention_first_time&returning_entity=%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D&target_entity=%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D&total_intervals=11',
                            },
                        ],
                        label: 'Week 10',
                        date: '2022-06-26T00:00:00Z',
                        people_url:
                            '/api/person/retention/?breakdown_attribution_type=first_touch&breakdown_values=%5B10%5D&display=ActionsTable&insight=RETENTION&period=Week&retention_type=retention_first_time&returning_entity=%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D&target_entity=%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+null%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+null%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D&total_intervals=11',
                    },
                ],
                created_at: '2022-06-29T10:18:57.732328Z',
                created_by: null,
                description: 'Weekly retention of your users.',
                updated_at: '2022-06-29T10:18:57.732405Z',
                favorited: false,
                saved: false,
                last_modified_at: '2022-06-29T10:18:57.731207Z',
                last_modified_by: null,
                is_sample: false,
                effective_restriction_level: 37,
                effective_privilege_level: 37,
                timezone: null,
                tags: [],
                user_access_level: AccessControlLevel.Editor,
            },
        } as DashboardTile,
        {
            id: 5,
            layouts: {
                sm: {
                    h: 5,
                    w: 6,
                    x: 6,
                    y: 10,
                    minH: 5,
                    minW: 3,
                },
                xs: {
                    h: 5,
                    w: 1,
                    x: 0,
                    y: 25,
                    minH: 5,
                    minW: 3,
                    moved: false,
                    static: false,
                },
            },
            color: InsightColor.Green,
            last_refresh: '2022-07-01T13:33:15.069874Z',
            insight: {
                id: 6,
                short_id: 'Ht75IvAs' as InsightShortId,
                name: 'Pageview funnel, by browser',
                derived_name: null,
                filters: {
                    events: [
                        {
                            id: '$pageview',
                            type: 'events',
                            order: 0,
                            custom_name: 'First page view',
                        },
                        {
                            id: '$pageview',
                            type: 'events',
                            order: 1,
                            custom_name: 'Second page view',
                        },
                        {
                            id: '$pageview',
                            type: 'events',
                            order: 2,
                            custom_name: 'Third page view',
                        },
                    ],
                    layout: FunnelLayout.horizontal,
                    insight: InsightType.FUNNELS,
                    interval: 'day',
                    breakdowns: [
                        {
                            type: 'event',
                            property: '$browser',
                        },
                    ],
                    exclusions: [],
                    breakdown_type: 'event',
                    funnel_viz_type: FunnelVizType.Steps,
                },
                last_refresh: '2022-07-01T13:33:15.069874Z',
                order: null,
                deleted: false,
                dashboards: [1],
                dashboard_tiles: [{ id: 1, dashboard_id: 1 }],
                result: [
                    [
                        {
                            action_id: '$pageview',
                            name: '$pageview',
                            custom_name: 'First page view',
                            order: 0,
                            people: [],
                            count: 234,
                            type: 'events',
                            average_conversion_time: null,
                            median_conversion_time: null,
                            breakdown: ['Chrome'],
                            breakdown_value: ['Chrome'],
                            converted_people_url:
                                '/api/person/funnel/?breakdown=%5B%22%24browser%22%5D&breakdowns=%5B%7B%22property%22%3A+%22%24browser%22%2C+%22type%22%3A+%22event%22%7D%5D&breakdown_attribution_type=first_touch&breakdown_type=event&date_from=2022-06-24T00%3A00%3A00%2B00%3A00&display=FunnelViz&events=%5B%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+0%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+%22First+page+view%22%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%2C+%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+1%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+%22Second+page+view%22%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%2C+%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+2%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+%22Third+page+view%22%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%5D&funnel_step_breakdown=%5B%22Chrome%22%5D&funnel_step=1&funnel_viz_type=steps&funnel_window_interval=14&funnel_window_interval_unit=day&insight=FUNNELS&interval=day&layout=horizontal&limit=100&smoothing_intervals=1',
                            dropped_people_url: null,
                        },
                        {
                            action_id: '$pageview',
                            name: '$pageview',
                            custom_name: 'Second page view',
                            order: 1,
                            people: [],
                            count: 180,
                            type: 'events',
                            average_conversion_time: 4.977061699111973,
                            median_conversion_time: 0.0,
                            breakdown: ['Chrome'],
                            breakdown_value: ['Chrome'],
                            converted_people_url:
                                '/api/person/funnel/?breakdown=%5B%22%24browser%22%5D&breakdowns=%5B%7B%22property%22%3A+%22%24browser%22%2C+%22type%22%3A+%22event%22%7D%5D&breakdown_attribution_type=first_touch&breakdown_type=event&date_from=2022-06-24T00%3A00%3A00%2B00%3A00&display=FunnelViz&events=%5B%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+0%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+%22First+page+view%22%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%2C+%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+1%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+%22Second+page+view%22%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%2C+%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+2%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+%22Third+page+view%22%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%5D&funnel_step_breakdown=%5B%22Chrome%22%5D&funnel_step=2&funnel_viz_type=steps&funnel_window_interval=14&funnel_window_interval_unit=day&insight=FUNNELS&interval=day&layout=horizontal&limit=100&smoothing_intervals=1',
                            dropped_people_url:
                                '/api/person/funnel/?breakdown=%5B%22%24browser%22%5D&breakdowns=%5B%7B%22property%22%3A+%22%24browser%22%2C+%22type%22%3A+%22event%22%7D%5D&breakdown_attribution_type=first_touch&breakdown_type=event&date_from=2022-06-24T00%3A00%3A00%2B00%3A00&display=FunnelViz&events=%5B%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+0%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+%22First+page+view%22%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%2C+%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+1%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+%22Second+page+view%22%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%2C+%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+2%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+%22Third+page+view%22%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%5D&funnel_step_breakdown=%5B%22Chrome%22%5D&funnel_step=-2&funnel_viz_type=steps&funnel_window_interval=14&funnel_window_interval_unit=day&insight=FUNNELS&interval=day&layout=horizontal&limit=100&smoothing_intervals=1',
                        },
                        {
                            action_id: '$pageview',
                            name: '$pageview',
                            custom_name: 'Third page view',
                            order: 2,
                            people: [],
                            count: 65,
                            type: 'events',
                            average_conversion_time: 6.742016378668548,
                            median_conversion_time: 0.0,
                            breakdown: ['Chrome'],
                            breakdown_value: ['Chrome'],
                            converted_people_url:
                                '/api/person/funnel/?breakdown=%5B%22%24browser%22%5D&breakdowns=%5B%7B%22property%22%3A+%22%24browser%22%2C+%22type%22%3A+%22event%22%7D%5D&breakdown_attribution_type=first_touch&breakdown_type=event&date_from=2022-06-24T00%3A00%3A00%2B00%3A00&display=FunnelViz&events=%5B%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+0%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+%22First+page+view%22%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%2C+%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+1%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+%22Second+page+view%22%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%2C+%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+2%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+%22Third+page+view%22%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%5D&funnel_step_breakdown=%5B%22Chrome%22%5D&funnel_step=3&funnel_viz_type=steps&funnel_window_interval=14&funnel_window_interval_unit=day&insight=FUNNELS&interval=day&layout=horizontal&limit=100&smoothing_intervals=1',
                            dropped_people_url:
                                '/api/person/funnel/?breakdown=%5B%22%24browser%22%5D&breakdowns=%5B%7B%22property%22%3A+%22%24browser%22%2C+%22type%22%3A+%22event%22%7D%5D&breakdown_attribution_type=first_touch&breakdown_type=event&date_from=2022-06-24T00%3A00%3A00%2B00%3A00&display=FunnelViz&events=%5B%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+0%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+%22First+page+view%22%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%2C+%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+1%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+%22Second+page+view%22%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%2C+%7B%22id%22%3A+%22%24pageview%22%2C+%22type%22%3A+%22events%22%2C+%22order%22%3A+2%2C+%22name%22%3A+%22%24pageview%22%2C+%22custom_name%22%3A+%22Third+page+view%22%2C+%22math%22%3A+null%2C+%22math_property%22%3A+null%2C+%22math_group_type_index%22%3A+null%2C+%22properties%22%3A+%7B%7D%7D%5D&funnel_step_breakdown=%5B%22Chrome%22%5D&funnel_step=-3&funnel_viz_type=steps&funnel_window_interval=14&funnel_window_interval_unit=day&insight=FUNNELS&interval=day&layout=horizontal&limit=100&smoothing_intervals=1',
                        },
                    ],
                ],
                created_at: '2022-06-29T10:18:57.757573Z',
                created_by: null,
                description:
                    'This example funnel shows how many of your users have completed 3 page views, broken down by browser.',
                updated_at: '2022-06-29T10:18:57.757644Z',
                favorited: false,
                saved: false,
                last_modified_at: '2022-06-29T10:18:57.756123Z',
                last_modified_by: null,
                is_sample: true,
                effective_restriction_level: 37,
                effective_privilege_level: 37,
                timezone: null,
                tags: [],
                user_access_level: AccessControlLevel.Editor,
            },
        } as DashboardTile,
    ],
    created_at: '2022-06-29T10:18:57.707542Z',
    created_by: null,
    last_accessed_at: null,
    is_shared: true,
    deleted: false,
    creation_mode: 'default',
    filters: {},
    restriction_level: 37,
    effective_restriction_level: 37,
    effective_privilege_level: 37,
    user_access_level: AccessControlLevel.Editor,
    access_control_version: 'v1',
    tags: [],
}
