# Column lists that more than one object uses.

locals {
  sharded_web_goals_preaggregated_columns = [
    { name = "team_id", type = "Int64" },
    { name = "job_id", type = "UUID" },
    { name = "time_window_start", type = "DateTime64(6, 'UTC')" },
    { name = "action_id", type = "Int64" },
    { name = "count_state", type = "AggregateFunction(sum, Int64)" },
    { name = "unique_persons_state", type = "AggregateFunction(uniq, UUID)" },
    { name = "computed_at", type = "DateTime64(6, 'UTC')", default_expression = "now()" },
    { name = "expires_at", type = "DateTime64(6, 'UTC')", default_expression = "now() + toIntervalDay(7)" },
  ]

  sharded_web_stats_frustration_preaggregated_columns = [
    { name = "team_id", type = "Int64" },
    { name = "job_id", type = "UUID" },
    { name = "time_window_start", type = "DateTime64(6, 'UTC')" },
    { name = "breakdown_value", type = "String" },
    { name = "sum_rage_clicks_state", type = "AggregateFunction(sum, Int64)" },
    { name = "sum_dead_clicks_state", type = "AggregateFunction(sum, Int64)" },
    { name = "sum_errors_state", type = "AggregateFunction(sum, Int64)" },
    { name = "computed_at", type = "DateTime64(6, 'UTC')", default_expression = "now()" },
    { name = "expires_at", type = "DateTime64(6, 'UTC')", default_expression = "now() + toIntervalDay(7)" },
  ]

  sharded_web_stats_paths_preaggregated_columns = [
    { name = "team_id", type = "Int64" },
    { name = "job_id", type = "UUID" },
    { name = "time_window_start", type = "DateTime64(6, 'UTC')" },
    { name = "breakdown_value", type = "String" },
    { name = "uniq_users_state", type = "AggregateFunction(uniq, UUID)" },
    { name = "sum_pageviews_state", type = "AggregateFunction(sum, Int64)" },
    { name = "avg_bounce_state", type = "AggregateFunction(avg, Nullable(Float64))" },
    { name = "computed_at", type = "DateTime64(6, 'UTC')", default_expression = "now()" },
    { name = "expires_at", type = "DateTime64(6, 'UTC')", default_expression = "now() + toIntervalDay(7)" },
  ]

  sharded_web_stats_preaggregated_columns = [
    { name = "team_id", type = "Int64" },
    { name = "job_id", type = "UUID" },
    { name = "time_window_start", type = "DateTime64(6, 'UTC')" },
    { name = "breakdown_by", type = "String" },
    { name = "breakdown_value", type = "String" },
    { name = "uniq_users_state", type = "AggregateFunction(uniq, UUID)" },
    { name = "sum_pageviews_state", type = "AggregateFunction(sum, Int64)" },
    { name = "computed_at", type = "DateTime64(6, 'UTC')", default_expression = "now()" },
    { name = "expires_at", type = "DateTime64(6, 'UTC')", default_expression = "now() + toIntervalDay(7)" },
  ]

  sharded_web_overview_preaggregated_columns = [
    { name = "team_id", type = "Int64" },
    { name = "job_id", type = "UUID" },
    { name = "time_window_start", type = "DateTime64(6, 'UTC')" },
    { name = "uniq_users_state", type = "AggregateFunction(uniq, UUID)" },
    { name = "uniq_sessions_state", type = "AggregateFunction(uniq, String)" },
    { name = "sum_pageviews_state", type = "AggregateFunction(sum, Int64)" },
    { name = "avg_duration_state", type = "AggregateFunction(avg, Float64)" },
    { name = "avg_bounce_state", type = "AggregateFunction(avg, Int64)" },
    { name = "computed_at", type = "DateTime64(6, 'UTC')", default_expression = "now()" },
    { name = "expires_at", type = "DateTime64(6, 'UTC')", default_expression = "now() + toIntervalDay(7)" },
  ]

  sharded_web_vitals_paths_preaggregated_columns = [
    { name = "team_id", type = "Int64" },
    { name = "job_id", type = "UUID" },
    { name = "time_window_start", type = "DateTime64(6, 'UTC')" },
    { name = "path", type = "String" },
    { name = "inp_quantiles_state", type = "AggregateFunction(quantiles(0.75, 0.9, 0.99), Float64)" },
    { name = "lcp_quantiles_state", type = "AggregateFunction(quantiles(0.75, 0.9, 0.99), Float64)" },
    { name = "cls_quantiles_state", type = "AggregateFunction(quantiles(0.75, 0.9, 0.99), Float64)" },
    { name = "fcp_quantiles_state", type = "AggregateFunction(quantiles(0.75, 0.9, 0.99), Float64)" },
    { name = "computed_at", type = "DateTime64(6, 'UTC')", default_expression = "now()" },
    { name = "expires_at", type = "DateTime64(6, 'UTC')", default_expression = "now() + toIntervalDay(7)" },
  ]

  sharded_web_sessions_dimensional_preaggregated_columns = [
    { name = "team_id", type = "Int64" },
    { name = "job_id", type = "UUID" },
    { name = "period_bucket", type = "DateTime" },
    { name = "session_id_v7", type = "UInt128" },
    { name = "person_id", type = "UUID" },
    { name = "start_timestamp", type = "DateTime64(6, 'UTC')" },
    { name = "min_event_timestamp", type = "DateTime64(6, 'UTC')" },
    { name = "max_event_timestamp", type = "DateTime64(6, 'UTC')" },
    { name = "channel_type", type = "String" },
    { name = "utm_source", type = "String" },
    { name = "utm_medium", type = "String" },
    { name = "utm_campaign", type = "String" },
    { name = "utm_term", type = "String" },
    { name = "utm_content", type = "String" },
    { name = "referring_domain", type = "String" },
    { name = "entry_pathname", type = "String" },
    { name = "pageview_count", type = "UInt64" },
    { name = "computed_at", type = "DateTime64(6, 'UTC')", default_expression = "now()" },
    { name = "expires_at", type = "DateTime64(6, 'UTC')", default_expression = "now() + toIntervalDay(7)" },
  ]

  web_pre_aggregated_stats_columns = [
    { name = "period_bucket", type = "DateTime" },
    { name = "team_id", type = "UInt64" },
    { name = "host", type = "String" },
    { name = "device_type", type = "String" },
    { name = "pathname", type = "String" },
    { name = "entry_pathname", type = "String" },
    { name = "end_pathname", type = "String" },
    { name = "browser", type = "String" },
    { name = "os", type = "String" },
    { name = "viewport_width", type = "Int64" },
    { name = "viewport_height", type = "Int64" },
    { name = "referring_domain", type = "String" },
    { name = "utm_source", type = "String" },
    { name = "utm_medium", type = "String" },
    { name = "utm_campaign", type = "String" },
    { name = "utm_term", type = "String" },
    { name = "utm_content", type = "String" },
    { name = "country_code", type = "String" },
    { name = "city_name", type = "String" },
    { name = "region_code", type = "String" },
    { name = "region_name", type = "String" },
    { name = "has_gclid", type = "Bool" },
    { name = "has_gad_source_paid_search", type = "Bool" },
    { name = "has_fbclid", type = "Bool" },
    { name = "mat_metadata_loggedIn", type = "Bool" },
    { name = "mat_metadata_backend", type = "String" },
    { name = "persons_uniq_state", type = "AggregateFunction(uniq, UUID)" },
    { name = "sessions_uniq_state", type = "AggregateFunction(uniq, String)" },
    { name = "pageviews_count_state", type = "AggregateFunction(sum, UInt64)" },
  ]

  web_pre_aggregated_bounces_columns = [
    { name = "period_bucket", type = "DateTime" },
    { name = "team_id", type = "UInt64" },
    { name = "host", type = "String" },
    { name = "device_type", type = "String" },
    { name = "entry_pathname", type = "String" },
    { name = "end_pathname", type = "String" },
    { name = "browser", type = "String" },
    { name = "os", type = "String" },
    { name = "viewport_width", type = "Int64" },
    { name = "viewport_height", type = "Int64" },
    { name = "referring_domain", type = "String" },
    { name = "utm_source", type = "String" },
    { name = "utm_medium", type = "String" },
    { name = "utm_campaign", type = "String" },
    { name = "utm_term", type = "String" },
    { name = "utm_content", type = "String" },
    { name = "country_code", type = "String" },
    { name = "city_name", type = "String" },
    { name = "region_code", type = "String" },
    { name = "region_name", type = "String" },
    { name = "has_gclid", type = "Bool" },
    { name = "has_gad_source_paid_search", type = "Bool" },
    { name = "has_fbclid", type = "Bool" },
    { name = "mat_metadata_loggedIn", type = "Bool" },
    { name = "mat_metadata_backend", type = "String" },
    { name = "persons_uniq_state", type = "AggregateFunction(uniq, UUID)" },
    { name = "sessions_uniq_state", type = "AggregateFunction(uniq, String)" },
    { name = "pageviews_count_state", type = "AggregateFunction(sum, UInt64)" },
    { name = "bounces_count_state", type = "AggregateFunction(sum, UInt64)" },
    { name = "total_session_duration_state", type = "AggregateFunction(sum, Int64)" },
    { name = "total_session_count_state", type = "AggregateFunction(sum, UInt64)" },
  ]

  sharded_web_stats_dimensional_preaggregated_columns = [
    { name = "team_id", type = "Int64" },
    { name = "job_id", type = "UUID" },
    { name = "period_bucket", type = "DateTime" },
    { name = "host", type = "String" },
    { name = "device_type", type = "String" },
    { name = "pathname", type = "String" },
    { name = "entry_pathname", type = "String" },
    { name = "end_pathname", type = "String" },
    { name = "browser", type = "String" },
    { name = "os", type = "String" },
    { name = "viewport_width", type = "Int64" },
    { name = "viewport_height", type = "Int64" },
    { name = "referring_domain", type = "String" },
    { name = "utm_source", type = "String" },
    { name = "utm_medium", type = "String" },
    { name = "utm_campaign", type = "String" },
    { name = "utm_term", type = "String" },
    { name = "utm_content", type = "String" },
    { name = "country_code", type = "String" },
    { name = "city_name", type = "String" },
    { name = "region_code", type = "String" },
    { name = "region_name", type = "String" },
    { name = "has_gclid", type = "Bool" },
    { name = "has_gad_source_paid_search", type = "Bool" },
    { name = "has_fbclid", type = "Bool" },
    { name = "mat_metadata_backend", type = "Nullable(String)" },
    { name = "mat_metadata_loggedIn", type = "Nullable(Bool)" },
    { name = "persons_uniq_state", type = "AggregateFunction(uniq, UUID)" },
    { name = "sessions_uniq_state", type = "AggregateFunction(uniq, String)" },
    { name = "pageviews_count_state", type = "AggregateFunction(sum, Int64)" },
    { name = "computed_at", type = "DateTime64(6, 'UTC')", default_expression = "now()" },
    { name = "expires_at", type = "DateTime64(6, 'UTC')", default_expression = "now() + toIntervalDay(7)" },
  ]

  sharded_web_bounces_dimensional_preaggregated_columns = [
    { name = "team_id", type = "Int64" },
    { name = "job_id", type = "UUID" },
    { name = "period_bucket", type = "DateTime" },
    { name = "host", type = "String" },
    { name = "device_type", type = "String" },
    { name = "entry_pathname", type = "String" },
    { name = "end_pathname", type = "String" },
    { name = "browser", type = "String" },
    { name = "os", type = "String" },
    { name = "viewport_width", type = "Int64" },
    { name = "viewport_height", type = "Int64" },
    { name = "referring_domain", type = "String" },
    { name = "utm_source", type = "String" },
    { name = "utm_medium", type = "String" },
    { name = "utm_campaign", type = "String" },
    { name = "utm_term", type = "String" },
    { name = "utm_content", type = "String" },
    { name = "country_code", type = "String" },
    { name = "city_name", type = "String" },
    { name = "region_code", type = "String" },
    { name = "region_name", type = "String" },
    { name = "has_gclid", type = "Bool" },
    { name = "has_gad_source_paid_search", type = "Bool" },
    { name = "has_fbclid", type = "Bool" },
    { name = "mat_metadata_backend", type = "Nullable(String)" },
    { name = "mat_metadata_loggedIn", type = "Nullable(Bool)" },
    { name = "persons_uniq_state", type = "AggregateFunction(uniq, UUID)" },
    { name = "sessions_uniq_state", type = "AggregateFunction(uniq, String)" },
    { name = "pageviews_count_state", type = "AggregateFunction(sum, Int64)" },
    { name = "bounces_count_state", type = "AggregateFunction(sum, Int64)" },
    { name = "total_session_duration_state", type = "AggregateFunction(sum, Int64)" },
    { name = "total_session_count_state", type = "AggregateFunction(sum, Int64)" },
    { name = "computed_at", type = "DateTime64(6, 'UTC')", default_expression = "now()" },
    { name = "expires_at", type = "DateTime64(6, 'UTC')", default_expression = "now() + toIntervalDay(7)" },
  ]
}
