import { HogFunctionTemplateCompiled } from '~/cdp/types'

export const template: HogFunctionTemplateCompiled = {
    free: false,
    status: 'alpha',
    type: 'warehouse_source_webhook',
    id: 'template-warehouse-source-stripe',
    name: 'Stripe warehouse source webhook',
    description: 'Receive Stripe webhook events for data warehouse ingestion',
    icon_url: '/static/services/stripe.png',
    category: ['Data warehouse'],
    code_language: 'hog',
    code: `
if(request.method != 'POST') {
  return {
    'httpResponse': {
      'status': 405,
      'body': 'Method not allowed'
    }
  }
}

if (not inputs.bypass_signature_check) {
  let body := request.stringBody
  let signatureHeader := request.headers['stripe-signature']

  if (empty(signatureHeader)) {
    return {
      'httpResponse': {
        'status': 400,
        'body': 'Missing signature',
      }
    }
  }

  let headerParts := splitByString(',', signatureHeader)
  let timestamp := null
  let v1Signature := null

  for (let _, part in headerParts) {
      let trimmed := trim(part)
      if (trimmed like 't=%') {
          let tParts := splitByString('=', trimmed, 2)
          if (length(tParts) = 2) {
              timestamp := tParts[2]
          }
      }
      if (trimmed like 'v1=%') {
          let v1Parts := splitByString('=', trimmed, 2)
          if (length(v1Parts) = 2) {
              v1Signature := v1Parts[2]
          }
      }
  }

  if (empty(timestamp) or empty(v1Signature)) {
      return {
        'httpResponse': {
          'status': 400,
          'body': 'Could not parse signature',
        }
      }
  }

  let signedPayload := concat(timestamp, '.', body)
  let computedSignature := sha256HmacChainHex([inputs.signing_secret, signedPayload])

  if (computedSignature != v1Signature) {
      return {
        'httpResponse': {
          'status': 400,
          'body': 'Bad signature',
        }
      }
  }
}

return request.body
  `,
    bytecode: [
        '_H',
        1,
        32,
        'POST',
        32,
        'method',
        32,
        'request',
        1,
        2,
        12,
        40,
        15,
        32,
        'httpResponse',
        32,
        'status',
        33,
        405,
        32,
        'body',
        32,
        'Method not allowed',
        42,
        2,
        42,
        1,
        38,
        32,
        'bypass_signature_check',
        32,
        'inputs',
        1,
        2,
        5,
        40,
        258,
        32,
        'stringBody',
        32,
        'request',
        1,
        2,
        32,
        'headers',
        32,
        'request',
        1,
        2,
        32,
        'stripe-signature',
        45,
        36,
        1,
        2,
        'empty',
        1,
        40,
        15,
        32,
        'httpResponse',
        32,
        'status',
        33,
        400,
        32,
        'body',
        32,
        'Missing signature',
        42,
        2,
        42,
        1,
        38,
        32,
        ',',
        36,
        1,
        2,
        'splitByString',
        2,
        31,
        31,
        36,
        2,
        36,
        5,
        2,
        'keys',
        1,
        36,
        5,
        2,
        'values',
        1,
        33,
        1,
        36,
        7,
        2,
        'length',
        1,
        31,
        31,
        36,
        9,
        36,
        8,
        16,
        40,
        97,
        36,
        6,
        36,
        8,
        45,
        37,
        10,
        36,
        7,
        36,
        8,
        45,
        37,
        11,
        36,
        11,
        2,
        'trim',
        1,
        32,
        't=%',
        36,
        12,
        17,
        40,
        27,
        32,
        '=',
        36,
        12,
        33,
        2,
        2,
        'splitByString',
        3,
        33,
        2,
        36,
        13,
        2,
        'length',
        1,
        11,
        40,
        7,
        36,
        13,
        33,
        2,
        45,
        37,
        3,
        35,
        32,
        'v1=%',
        36,
        12,
        17,
        40,
        27,
        32,
        '=',
        36,
        12,
        33,
        2,
        2,
        'splitByString',
        3,
        33,
        2,
        36,
        13,
        2,
        'length',
        1,
        11,
        40,
        7,
        36,
        13,
        33,
        2,
        45,
        37,
        4,
        35,
        35,
        36,
        8,
        33,
        1,
        6,
        37,
        8,
        39,
        -104,
        35,
        35,
        35,
        35,
        35,
        35,
        35,
        36,
        3,
        2,
        'empty',
        1,
        36,
        4,
        2,
        'empty',
        1,
        4,
        2,
        40,
        15,
        32,
        'httpResponse',
        32,
        'status',
        33,
        400,
        32,
        'body',
        32,
        'Could not parse signature',
        42,
        2,
        42,
        1,
        38,
        36,
        3,
        32,
        '.',
        36,
        0,
        2,
        'concat',
        3,
        32,
        'signing_secret',
        32,
        'inputs',
        1,
        2,
        36,
        5,
        43,
        2,
        2,
        'sha256HmacChainHex',
        1,
        36,
        4,
        36,
        6,
        12,
        40,
        15,
        32,
        'httpResponse',
        32,
        'status',
        33,
        400,
        32,
        'body',
        32,
        'Bad signature',
        42,
        2,
        42,
        1,
        38,
        35,
        35,
        35,
        35,
        35,
        35,
        35,
        32,
        'body',
        32,
        'request',
        1,
        2,
        38,
    ],

    inputs_schema: [
        {
            type: 'string',
            key: 'signing_secret',
            label: 'Signing secret',
            required: false,
            secret: true,
            hidden: false,
            description: 'Used to validate the webhook came from Stripe',
        },
        {
            type: 'boolean',
            key: 'bypass_signature_check',
            label: 'Bypass signature check',
            description: 'If set, the stripe-signature header will not be checked. This is not recommended.',
            default: false,
            required: false,
            secret: false,
        },
    ],
}
