from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
    CanonicalEndpoint,
)

_COMPLIANCE_COLUMNS = {
    "account": "The evaluated cloud account or project (id and alias).",
    "evalType": "The evaluation type, such as LW_SA (Lacework security assessment).",
    "id": "The identifier of the evaluated recommendation, such as LW_AWS_IAM_7.",
    "reason": "Why the resource is non-compliant with the recommendation.",
    "recommendation": "The recommendation the resource was evaluated against.",
    "region": "The cloud region of the evaluated resource.",
    "reportTime": "When the compliance evaluation ran.",
    "resource": "The identifier (e.g. ARN) of the evaluated resource.",
    "section": "The compliance report section the recommendation belongs to.",
    "severity": "The severity of the recommendation.",
    "status": "The evaluation result, such as Compliant or NonCompliant.",
}


def _compliance_entry(provider: str) -> CanonicalEndpoint:
    return {
        "description": f"{provider} compliance evaluations: one row per resource per recommendation per report, with the compliance status, reason, and severity.",
        "docs_url": "https://api.lacework.net/api/v2/docs#tag/Configs",
        "columns": _COMPLIANCE_COLUMNS,
    }


_INVENTORY_COLUMNS = {
    "startTime": "When the hourly aggregation period of the collection run started.",
    "endTime": "When the hourly aggregation period of the collection run ended.",
    "urn": "The URN of the resource.",
    "service": "The cloud service the resource belongs to.",
    "status": "The status of the resource.",
    "cloudDetails": "Details of the cloud account or project that owns the resource.",
    "resourceType": "The resource type.",
    "resourceId": "The identifier of the resource.",
    "resourceRegion": "The region the resource belongs to.",
    "resourceConfig": "The configuration of the resource.",
    "resourceTags": "The tags on the resource.",
    "csp": "The cloud provider.",
    "apiKey": "The cloud API call used to collect the resource.",
}


def _inventory_entry(provider: str) -> CanonicalEndpoint:
    return {
        "description": f"{provider} cloud resource inventory: one row per resource per collection run. Compliance evaluations are scored against these resources.",
        "docs_url": "https://api.lacework.net/api/v2/docs#tag/Inventory",
        "columns": _INVENTORY_COLUMNS,
    }


CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "alerts": {
        "description": "Alerts raised by Lacework FortiCNAPP for potential threats, anomalies, and policy violations across your cloud environments.",
        "docs_url": "https://api.lacework.net/api/v2/docs#tag/Alerts",
        "columns": {
            "alertId": "Unique identifier for the alert.",
            "alertType": "The alert type, such as MaliciousFile.",
            "alertName": "The alert name, such as 'Service called GCP API'.",
            "alertInfo": "Details of the alert (subject and description).",
            "severity": "The alert's severity level, such as Critical, High, Medium, Low, or Info.",
            "internetExposure": "Whether any entity involved in the alert is exposed to the internet.",
            "reachability": "Whether any entity in the alert is reachable.",
            "derivedFields": "The alert category, subcategory, and source.",
            "startTime": "When the potential threat started.",
            "endTime": "When the potential threat ended.",
            "lastUserUpdatedTime": "When a user last updated the alert.",
            "status": "The current status of the alert, such as Open or Closed.",
        },
    },
    "audit_logs": {
        "description": "Lacework console audit log: one row per action a user performed in the Lacework FortiCNAPP account.",
        "docs_url": "https://api.lacework.net/api/v2/docs#tag/AuditLogs",
        "columns": {
            "createdTime": "When the logged action happened.",
            "accountName": "The account name associated with the logged action.",
            "userName": "The username of the user associated with the logged action.",
            "eventName": "The name of the logged event, such as User Login.",
            "userAction": "Summary of the action, such as 'Login with OAuth Succeeded' or 'Alert Channel Created'.",
            "eventDescription": "Human-readable summary of the event.",
        },
    },
    "agent_info": {
        "description": "Inventory of Lacework agents: one row per agent with its version, host, status, and tags.",
        "docs_url": "https://api.lacework.net/api/v2/docs#tag/AgentInfo",
        "columns": {
            "agentVersion": "The version of the installed Lacework agent.",
            "createdTime": "When the agent was first seen.",
            "hostname": "The hostname of the machine the agent runs on.",
            "ipAddr": "The IP address of the machine the agent runs on.",
            "lastUpdate": "When the agent last reported in.",
            "mid": "The machine identifier the agent is installed on.",
            "mode": "The agent mode, such as normal.",
            "os": "The operating system of the machine the agent runs on.",
            "status": "The agent status, such as ACTIVE.",
            "tags": "Cloud provider and custom tags of the machine the agent runs on.",
        },
    },
    "vulnerabilities_hosts": {
        "description": "Host vulnerability assessment results: one row per CVE per machine per assessment, with severity, fix, and risk information.",
        "docs_url": "https://api.lacework.net/api/v2/docs#tag/Vulnerabilities",
        "columns": {
            "startTime": "When the assessment window started.",
            "endTime": "When the assessment window ended.",
            "vulnId": "The vulnerability identifier, such as a CVE id.",
            "mid": "The machine identifier the vulnerability was found on.",
            "machineTags": "Cloud provider and custom tags of the machine.",
            "evalCtx": "Evaluation context for the assessment, such as hostname and scan batch.",
            "evalGuid": "Unique identifier of the assessment run.",
            "featureKey": "The affected package (name, namespace, installed version).",
            "packageStatus": "The package status, such as ACTIVE.",
            "severity": "The severity of the vulnerability.",
            "fixInfo": "Fix availability and the fixed version.",
            "status": "The vulnerability status, such as New, Active, or Fixed.",
            "cveProps": "CVE metadata, including description, link, and CVSS scores.",
            "riskScore": "Lacework's risk score for this vulnerability on this machine.",
            "riskInfo": "Factors contributing to the risk score.",
            "cveRiskScore": "Risk score of the CVE itself.",
            "hostRiskScore": "Risk score of the affected host.",
        },
    },
    "vulnerabilities_containers": {
        "description": "Container image vulnerability assessment results: one row per CVE per image per assessment, with severity, fix, and risk information.",
        "docs_url": "https://api.lacework.net/api/v2/docs#tag/Vulnerabilities",
        "columns": {
            "startTime": "When the assessment ran.",
            "vulnId": "The vulnerability identifier, such as a CVE id.",
            "imageId": "The identifier of the affected container image.",
            "evalCtx": "Evaluation context for the assessment, such as the image registry, repo, and tags.",
            "evalGuid": "Unique identifier of the assessment run.",
            "featureKey": "The affected package (name, namespace, version).",
            "featureProps": "Additional properties of the affected package, such as the introducing layer.",
            "packageStatus": "The package status, such as ACTIVE.",
            "fixInfo": "Fix availability and the fixed version.",
            "severity": "The severity of the vulnerability.",
            "status": "The vulnerability status, such as New, Active, or Fixed.",
            "riskScore": "Lacework's risk score for this vulnerability in this image.",
            "riskInfo": "Factors contributing to the risk score.",
            "cveRiskScore": "Risk score of the CVE itself.",
            "imageRiskScore": "Risk score of the affected image.",
        },
    },
    "compliance_evaluations_aws": _compliance_entry("AWS"),
    "compliance_evaluations_azure": _compliance_entry("Azure"),
    "compliance_evaluations_gcp": _compliance_entry("GCP"),
    "compliance_evaluations_k8s": _compliance_entry("Kubernetes"),
    "entities_machines": {
        "description": "Machines observed online in your environment: one row per machine per activity segment.",
        "docs_url": "https://api.lacework.net/api/v2/docs#tag/Entities",
        "columns": {
            "startTime": "When the machine's activity segment started.",
            "endTime": "When the machine's activity segment ended.",
            "mid": "The machine identifier.",
            "hostname": "The hostname of the machine.",
            "machineTags": "Cloud provider and custom tags of the machine.",
            "primaryIpAddr": "The primary IP address of the machine.",
            "entityType": "The entity type (Machine).",
        },
    },
    "entities_containers": {
        "description": "Containers active in your environment: one row per container per hourly aggregation window.",
        "docs_url": "https://api.lacework.net/api/v2/docs#tag/Entities",
        "columns": {
            "startTime": "When the hourly aggregation window started.",
            "endTime": "When the hourly aggregation window ended.",
            "mid": "The identifier of the machine the container runs on.",
            "containerName": "The name of the container.",
            "podName": "The name of the Kubernetes pod the container belongs to.",
            "imageId": "The identifier of the container image. Joins to vulnerabilities_containers and entities_images.",
            "propsContainer": "Properties of the container, such as image repository and tag.",
            "tags": "Tags of the container.",
        },
    },
    "entities_images": {
        "description": "Container images in your environment: one row per image per machine.",
        "docs_url": "https://api.lacework.net/api/v2/docs#tag/Entities",
        "columns": {
            "createdTime": "When the container was created.",
            "mid": "The identifier of the machine the image is on.",
            "imageId": "The identifier of the container image.",
            "repo": "The repository of the image.",
            "tag": "The tag of the image.",
            "size": "The size of the image in bytes.",
            "containerType": "The container runtime type.",
        },
    },
    "inventory_aws": _inventory_entry("AWS"),
    "inventory_azure": _inventory_entry("Azure"),
    "inventory_gcp": _inventory_entry("GCP"),
    "cloud_accounts": {
        "description": "Cloud account integrations configured in Lacework FortiCNAPP. Credentials are removed from the data column.",
        "docs_url": "https://api.lacework.net/api/v2/docs#tag/CloudAccounts",
        "columns": {
            "intgGuid": "Unique identifier for the integration.",
            "name": "The name of the integration.",
            "type": "The integration type, such as AwsCfg or AzureCfg.",
            "enabled": "1 if the integration is enabled, 0 if it is disabled.",
            "state": "The current state of the integration, such as whether the last check succeeded.",
            "cloudId": "The cloud account identifier.",
            "cloudIdType": "The type of cloud account identifier, such as AWS_ACCOUNT_ID or GCP_PROJECT_ID.",
            "data": "The integration's configuration, without credentials.",
            "isOrg": "1 if the integration belongs to an organization-level account, else 0.",
            "props": "The integration's properties.",
            "createdOrUpdatedBy": "The user who created or last updated the integration.",
            "createdOrUpdatedTime": "When the integration was created or last updated.",
        },
    },
    "policies": {
        "description": "Policies registered in Lacework FortiCNAPP. Alerts reference a policy by policyId.",
        "docs_url": "https://api.lacework.net/api/v2/docs#tag/Policies",
        "columns": {
            "policyId": "Unique identifier for the policy.",
            "policyType": "The policy type, such as Violation.",
            "queryId": "The identifier of the query the policy runs.",
            "title": "The title of the policy.",
            "enabled": "Whether the policy is enabled.",
            "description": "The description of the policy.",
            "remediation": "How to remediate events the policy triggers.",
            "severity": "The severity of events the policy triggers.",
            "limit": "The maximum number of records each policy run returns.",
            "evalFrequency": "How often the policy runs (deprecated).",
            "alertEnabled": "Whether the policy sends alerts when it triggers.",
            "alertProfile": "The alert profile used when the policy triggers.",
            "tags": "The tags of the policy.",
            "evaluatorId": "The evaluator identifier of the policy.",
            "owner": "The user who created the policy.",
            "lastUpdateTime": "When the policy was last updated.",
            "lastUpdateUser": "The user who last updated the policy.",
            "exceptionConfiguration": "The configuration of policy exceptions, where applicable.",
        },
    },
}
