from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "parse_jobs": {
        "description": "LlamaParse document parsing jobs, one row per parse job with its status and metadata.",
        "docs_url": "https://developers.llamaindex.ai/python/cloud/api_reference/parsing",
        "columns": {
            "id": "Unique identifier for the parse job.",
            "created_at": "Timestamp when the parse job was created.",
            "updated_at": "Timestamp when the parse job was last updated.",
            "project_id": "Identifier of the LlamaCloud project the job belongs to.",
            "status": "Job status: PENDING, RUNNING, COMPLETED, FAILED, or CANCELLED.",
            "error_message": "Error details when the job failed.",
            "name": "Name of the parsed file or job.",
            "tier": "Parse tier (mode) the job ran with.",
            "user_metadata": "Custom key-value metadata attached to the job by the caller.",
        },
    },
    "extract_jobs": {
        "description": "LlamaExtract structured-extraction jobs, one row per extraction run with its configuration and status.",
        "docs_url": "https://developers.llamaindex.ai/python/cloud/api_reference/extraction",
        "columns": {
            "id": "Unique identifier for the extraction job.",
            "created_at": "Timestamp when the extraction job was created.",
            "updated_at": "Timestamp when the extraction job was last updated.",
            "project_id": "Identifier of the LlamaCloud project the job belongs to.",
            "status": "Job status: PENDING, THROTTLED, RUNNING, COMPLETED, FAILED, or CANCELLED.",
            "error_message": "Error details when the job failed.",
            "file_input": "Identifier or reference of the input file the job extracted from.",
            "configuration_id": "Identifier of the extraction configuration (agent) used.",
        },
    },
    "classify_jobs": {
        "description": "Document classification jobs, one row per classify run with its status and result.",
        "docs_url": "https://developers.llamaindex.ai/python/cloud/api_reference/classifier",
        "columns": {
            "id": "Unique identifier for the classify job.",
            "created_at": "Timestamp when the classify job was created.",
            "updated_at": "Timestamp when the classify job was last updated.",
            "project_id": "Identifier of the LlamaCloud project the job belongs to.",
            "user_id": "Identifier of the user who created the job.",
            "status": "Job status: PENDING, RUNNING, COMPLETED, or FAILED.",
            "error_message": "Error details when the job failed.",
            "file_input": "Identifier or reference of the classified input file.",
            "document_input_type": "How the input document was supplied (e.g. file id or URL).",
            "configuration_id": "Identifier of the classification configuration used.",
            "parse_job_id": "Identifier of the parse job that preprocessed the document, when applicable.",
        },
    },
    "batches": {
        "description": "Batch processing runs that apply parsing or extraction across a directory of files.",
        "docs_url": "https://developers.llamaindex.ai/python/cloud/api_reference/batches",
        "columns": {
            "id": "Unique identifier for the batch.",
            "created_at": "Timestamp when the batch was created.",
            "updated_at": "Timestamp when the batch was last updated.",
            "project_id": "Identifier of the LlamaCloud project the batch belongs to.",
            "source_directory_id": "Identifier of the directory of files the batch processes.",
            "status": "Batch status: PENDING, THROTTLED, RUNNING, COMPLETED, FAILED, or CANCELLED.",
            "config": "Configuration the batch ran with.",
            "results": "Per-file results of the batch run.",
        },
    },
    "split_jobs": {
        "description": "Document splitting jobs that segment a document into categorized sub-documents.",
        "docs_url": "https://developers.llamaindex.ai/python/cloud/api_reference/splitter",
        "columns": {
            "id": "Unique identifier for the split job.",
            "created_at": "Timestamp when the split job was created.",
            "updated_at": "Timestamp when the split job was last updated.",
            "project_id": "Identifier of the LlamaCloud project the job belongs to.",
            "user_id": "Identifier of the user who created the job.",
            "status": "Job status: pending, processing, completed, failed, or cancelled.",
            "error_message": "Error details when the job failed.",
            "file_input": "Identifier or reference of the input file the job split.",
            "categories": "Categories the job splits the document into.",
            "splitting_strategy": "Strategy used to split the document.",
        },
    },
    "sheets_jobs": {
        "description": "Spreadsheet parsing jobs (LlamaSheets), one row per spreadsheet job with per-region results metadata.",
        "docs_url": "https://developers.llamaindex.ai/python/cloud/api_reference/sheets",
        "columns": {
            "id": "Unique identifier for the spreadsheet job.",
            "created_at": "Timestamp when the spreadsheet job was created.",
            "updated_at": "Timestamp when the spreadsheet job was last updated.",
            "project_id": "Identifier of the LlamaCloud project the job belongs to.",
            "user_id": "Identifier of the user who created the job.",
            "status": "Job status: PENDING, SUCCESS, ERROR, PARTIAL_SUCCESS, or CANCELLED.",
            "success": "Whether the job completed successfully.",
            "file_id": "Identifier of the spreadsheet file the job parsed.",
            "regions": "Table regions detected in the spreadsheet.",
            "worksheet_metadata": "Per-worksheet metadata for the parsed spreadsheet.",
            "errors": "Errors encountered while parsing the spreadsheet.",
        },
    },
    "projects": {
        "description": "LlamaCloud projects visible to the API key.",
        "docs_url": "https://developers.llamaindex.ai/python/cloud/api_reference/projects",
        "columns": {
            "id": "Unique identifier for the project.",
            "created_at": "Timestamp when the project was created.",
            "updated_at": "Timestamp when the project was last updated.",
            "name": "Name of the project.",
            "organization_id": "Identifier of the organization the project belongs to.",
            "is_default": "Whether this is the organization's default project.",
        },
    },
    "pipelines": {
        "description": "Managed index pipelines that ingest, chunk, embed, and index documents for retrieval.",
        "docs_url": "https://developers.llamaindex.ai/python/cloud/api_reference/pipelines",
        "columns": {
            "id": "Unique identifier for the pipeline.",
            "created_at": "Timestamp when the pipeline was created.",
            "updated_at": "Timestamp when the pipeline was last updated.",
            "name": "Name of the pipeline.",
            "project_id": "Identifier of the LlamaCloud project the pipeline belongs to.",
            "pipeline_type": "Type of the pipeline (e.g. MANAGED or PLAYGROUND).",
        },
    },
    "files": {
        "description": "Files uploaded to LlamaCloud for parsing, extraction, or indexing.",
        "docs_url": "https://developers.llamaindex.ai/python/cloud/api_reference/files",
        "columns": {
            "id": "Unique identifier for the file.",
            "name": "Name of the file.",
            "external_file_id": "Caller-supplied external identifier for the file.",
            "file_type": "Type (extension) of the file.",
            "project_id": "Identifier of the LlamaCloud project the file belongs to.",
            "last_modified_at": "Timestamp when the file was last modified.",
            "expires_at": "Timestamp when the file expires, when set.",
            "purpose": "Purpose the file was uploaded for.",
        },
    },
    "usage_metrics": {
        "description": "Per-day usage aggregates with credit consumption across LlamaCloud products.",
        "docs_url": "https://developers.llamaindex.ai/python/cloud/api_reference/usage-metrics",
        "columns": {
            "id": "Unique identifier for the usage metric row.",
            "day": "Date (YYYY-MM-DD) the usage was recorded for.",
            "event_type": "Type of usage event the row aggregates.",
            "value": "Aggregated usage count for the day.",
            "credits": "Credits consumed by this usage.",
            "project_id": "Identifier of the LlamaCloud project the usage belongs to.",
            "organization_id": "Identifier of the organization the usage belongs to.",
            "user_id": "Identifier of the user who generated the usage.",
            "event_aggregation_type": "How the usage events were aggregated.",
            "event_aggregation_key": "Key the usage events were aggregated by.",
            "usage_tags": "Tags attached to the usage events.",
        },
    },
}
