CREATE TABLE IF NOT EXISTS posthog.metrics2_input (
  uuid String,
  team_id Int32,
  metric_name LowCardinality(String),
  series_fingerprint UInt64,
  resource_fingerprint UInt64,
  timestamp DateTime64(6),
  observed_timestamp DateTime64(6),
  original_expiry_timestamp DateTime64(6),
  service_name LowCardinality(String),
  metric_type LowCardinality(String),
  value Float64,
  count UInt64,
  histogram_bounds Array(Float64),
  histogram_counts Array(UInt64),
  trace_id String,
  span_id String,
  trace_flags Int32,
  has_labels Bool,
  unit LowCardinality(String),
  aggregation_temporality LowCardinality(String),
  is_monotonic Bool,
  instrumentation_scope String,
  resource_attributes Map(LowCardinality(String), String),
  attributes Map(LowCardinality(String), String),
  _partition UInt32,
  _topic String,
  _offset UInt64
) ENGINE = Null();
