from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "devices": {
        "description": "Devices (nodes) in the tailnet, including connectivity details, routes, and key expiry.",
        "docs_url": "https://tailscale.com/api#tag/devices",
        "columns": {
            "id": "The legacy identifier for the device.",
            "nodeId": "The preferred, stable identifier for the device.",
            "name": "The MagicDNS name of the device.",
            "hostname": "The machine name in the admin console.",
            "addresses": "The list of Tailscale IP addresses for the device.",
            "user": "The user who registered the node (for tagged nodes, the tag owner).",
            "os": "The operating system the device is running.",
            "clientVersion": "The version of the Tailscale client software.",
            "created": "The date the device was added to the tailnet; empty for external devices.",
            "lastSeen": "When the device was last active on the tailnet.",
            "expires": "The expiration date of the device's auth key.",
            "keyExpiryDisabled": "Whether the device's key will never expire.",
            "authorized": "Whether the device has been authorized to join the tailnet.",
            "isExternal": "Whether the device is shared into the tailnet rather than a member of it.",
            "machineKey": "For internal use; do not depend on this value.",
            "nodeKey": "The device's public key, mainly used by internal Tailscale systems.",
            "blocksIncomingConnections": "Whether the device is not allowed to accept connections over Tailscale.",
            "updateAvailable": "Whether a Tailscale client version upgrade is available.",
            "enabledRoutes": "The subnet routes for this device that have been approved by an admin.",
            "advertisedRoutes": "The subnet routes this device intends to expose.",
            "clientConnectivity": "The device's connectivity report (endpoints, DERP latency, NAT traversal).",
            "tags": "The ACL tags applied to the device.",
            "tailnetLockKey": "The node's tailnet lock key.",
            "tailnetLockError": "An issue with the tailnet lock node-key signature on this device, if any.",
        },
    },
    "users": {
        "description": "Users of the tailnet, including their role, status, and device count.",
        "docs_url": "https://tailscale.com/api#tag/users",
        "columns": {
            "id": "The unique identifier for the user.",
            "displayName": "The name of the user.",
            "loginName": "The email-like login name of the user.",
            "profilePicUrl": "The profile picture URL for the user.",
            "tailnetId": "The tailnet that owns the user.",
            "created": "The time the user joined their tailnet.",
            "type": "The type of relation this user has to the tailnet (member or shared).",
            "role": "The role of the user (owner, admin, member, and so on).",
            "status": "The status of the user (active, idle, suspended, needs-approval, over-billing-limit).",
            "deviceCount": "Number of devices the user owns.",
            "lastSeen": "The later of either the last login time or the last time a device owned by the user was active.",
            "currentlyConnected": "Whether the user has a device that is currently connected to the control server.",
        },
    },
    "keys": {
        "description": "Active auth keys and API access tokens in the tailnet, with their capabilities and expiry.",
        "docs_url": "https://tailscale.com/api#tag/keys",
        "columns": {
            "id": "The unique identifier for the key.",
            "keyType": "The type of the key (client for auth keys, api for access tokens).",
            "description": "A short string specifying the purpose of the key.",
            "created": "When the key was created.",
            "expires": "When the key expires.",
            "revoked": "When the key was revoked, if it has been.",
            "invalid": "Whether the key is no longer valid (expired or revoked).",
            "capabilities": "The capabilities granted by the key, such as device creation attributes.",
            "userId": "The user who owns the key.",
        },
    },
    "configuration_audit_logs": {
        "description": "Configuration audit log records: who changed what in the tailnet, with old and new values. Tailscale retains the most recent 90 days; syncing to the warehouse preserves them for longer.",
        "docs_url": "https://tailscale.com/api#tag/logging",
        "columns": {
            "eventGroupID": "Identifier shared by all records of a single configuration change event.",
            "action": "The action taken, e.g. CREATE, UPDATE, or DELETE.",
            "actor": "The user, API key, or system component that performed the action.",
            "target": "The object the action was performed on, such as a device or policy file.",
            "old": "The value before the change, for update actions.",
            "new": "The value after the change.",
            "origin": "Where the change originated from.",
            "eventTime": "The time at which the change occurred.",
        },
    },
}
