/** Status words for a running turn. All hog, on purpose: a wait is one of the
 *  few moments a customer reads our copy word by word, so it may as well sound
 *  like us. `products/posthog_ai/frontend/utils/thinkingMessages.ts` keeps the
 *  same list for Max in the web app, annotated — keep the two together. */
export const THINKING_ACTIVITIES = [
  "Booping",
  "Snuffling",
  "Snouting",
  "Snoutlining",
  "Snoutdiving",
  "Quilling",
  "Requilling",
  "Quillsharpening",
  "Quillcounting",
  "Quillcrafting",
  "Bristling",
  "Prickling",
  "Pincushioning",
  "Curling",
  "Unrolling",
  "Burrowing",
  "Rooting",
  "Foraging",
  "Rummaging",
  "Anointing",
  "Arraying",
  "Purring",
  "Chirping",
  "Scuttling",
  "Waddling",
  "Trundling",
  "Brambling",
  "Hedgerowing",
  "Hedgeclipping",
  "Topiarying",
  "Hedgemazing",
  "Hedgehugging",
  "Leafpiling",
  "Nesting",
  "Nightshifting",
  "Moonlighting",
  "Wheelrunning",
  "Hogletting",
  "Molehilling",
  "Spelunking",
  "Mudlarking",
  "Trufflehunting",
  "Hedgehogging",
  "Posthogging",
  "Hedging",
  "Hoggifying",
  "Hog-easing",
  "Hogitating",
  "Hogorithming",
  "Hogothesizing",
  "Hogtimizing",
  "Hogstimating",
  "Hogsembling",
  "Hogfactoring",
  "Hogpiling",
  "Hogwarming",
  "Hogwrangling",
  "Hogtrotting",
  "Wholehogging",
  "Hedgineering",
  "Hedgeploying",
  "Hogfooding",
  "Hogcasting",
  "Squeaking",
  "Flagging",
  "Funneling",
  "Cohorting",
  "Sessionizing",
  "Replaying",
  "Autocapturing",
  "Dashboarding",
  "Experimenting",
  "Instrumenting",
  "Materializing",
  "HogQLing",
  "Sandboxing",
  "Warehousing",
  "Pipelining",
  "Signaling",
  "Self-driving",
  "Surveying",
  "Heatmapping",
  "Symbolicating",
  "Backfilling",
  "Deduping",
  "Sharding",
  "Batching",
  "Debouncing",
  "Linting",
  "Compiling",
  "Migrating",
  "Rebasing",
  "Merging",
  "Bisecting",
  "Yakshaving",
  "Rubberducking",
  "Prototyping",
  "Shipping",
  "Untangling",
  "Thinking",
] as const;

export function pickThinkingActivity(randomValue: number): string {
  const bounded = Math.max(0, Math.min(randomValue, 0.999999999999));
  return THINKING_ACTIVITIES[Math.floor(bounded * THINKING_ACTIVITIES.length)];
}

export function pickNextThinkingActivity(
  current: string,
  randomValue: number,
): string {
  const picked = pickThinkingActivity(randomValue);
  if (picked !== current || THINKING_ACTIVITIES.length <= 1) return picked;
  const index = THINKING_ACTIVITIES.indexOf(
    current as (typeof THINKING_ACTIVITIES)[number],
  );
  return THINKING_ACTIVITIES[(index + 1) % THINKING_ACTIVITIES.length];
}
