"""Canonical, documentation-sourced descriptions for Deel endpoints and columns.

Sourced from the official Deel API reference (https://developer.deel.com/reference). Keyed by the
endpoint names in `settings.py` `DEEL_ENDPOINTS`, which match the `ExternalDataSchema.name` of a
synced Deel table. Columns absent here fall back to LLM enrichment.
"""

from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "people": {
        "description": "A worker in the organization — an employee or contractor managed in Deel.",
        "docs_url": "https://developer.deel.com/reference/getpeoplelist",
        "columns": {
            "id": "Unique identifier for the person.",
            "first_name": "The person's first name.",
            "last_name": "The person's last name.",
            "full_name": "The person's full name.",
            "emails": "Email addresses associated with the person.",
            "hiring_status": "Current hiring status of the person (e.g. active, inactive).",
            "hiring_type": "Type of engagement (e.g. employee, contractor).",
            "start_date": "Date the person started with the organization.",
            "job_title": "The person's job title.",
            "country": "Country the person is based in.",
        },
    },
    "contracts": {
        "description": "A work agreement between the organization and a worker in Deel.",
        "docs_url": "https://developer.deel.com/reference/getcontractlist",
        "columns": {
            "id": "Unique identifier for the contract.",
            "title": "Title of the contract.",
            "type": "Type of contract (e.g. ongoing_time_based, pay_as_you_go, milestone, eor).",
            "status": "Current status of the contract (e.g. in_progress, completed, cancelled).",
            "created_at": "Time at which the contract was created.",
            "currency": "Currency the contract is denominated in.",
            "client_name": "Name of the client party on the contract.",
            "worker_name": "Name of the worker on the contract.",
        },
    },
    "invoices": {
        "description": "An invoice issued for a contract or payroll cycle in Deel.",
        "docs_url": "https://developer.deel.com/reference/getinvoicelist",
        "columns": {
            "id": "Unique identifier for the invoice.",
            "contract_id": "Identifier of the contract this invoice relates to.",
            "status": "Current status of the invoice (e.g. paid, pending, processing).",
            "currency": "Currency the invoice is denominated in.",
            "total": "Total amount of the invoice.",
            "issued_at": "Date the invoice was issued.",
            "paid_at": "Date the invoice was paid, if applicable.",
        },
    },
    "invoice_adjustments": {
        "description": "An adjustment (bonus, deduction, expense, etc.) applied to a Deel invoice.",
        "docs_url": "https://developer.deel.com/reference/getinvoiceadjustmentslist",
        "columns": {
            "id": "Unique identifier for the invoice adjustment.",
            "contract_id": "Identifier of the contract this adjustment relates to.",
            "type": "Type of adjustment (e.g. bonus, deduction, expense, overtime).",
            "title": "Title or description of the adjustment.",
            "amount": "Amount of the adjustment.",
            "currency": "Currency the adjustment is denominated in.",
            "status": "Current status of the adjustment.",
        },
    },
    "timesheets": {
        "description": "A time entry submitted against a Deel contract, used to bill hourly and pay-as-you-go work.",
        "docs_url": "https://developer.deel.com/reference/listoftimesheets",
        "columns": {
            "id": "Unique identifier for the timesheet.",
            "type": "Type of work reported (e.g. hourly, milestone, bonus).",
            "scale": "Unit the reported quantity is measured in (e.g. hourly, daily, weekly).",
            "status": "Review status of the timesheet (e.g. pending, approved, declined).",
            "contract": "The contract the time was reported against.",
            "quantity": "Amount of work reported, in the units given by the scale.",
            "worksheet": "Breakdown of the reported time into days, hours, weeks and minutes.",
            "created_at": "Time at which the timesheet was created.",
            "description": "Free-text description of the work reported.",
            "reported_by": "The person who submitted the timesheet.",
            "reviewed_by": "The person who reviewed the timesheet, and their remarks.",
            "total_amount": "Total amount payable for the reported work.",
            "currency_code": "Currency the total amount is denominated in.",
            "payment_cycle": "Start and end date of the payment cycle the timesheet falls in.",
            "date_submitted": "Date the timesheet was submitted for review.",
        },
    },
    "payments": {
        "description": "A payment made to Deel, covering the invoices settled in one transaction.",
        "docs_url": "https://developer.deel.com/reference/retrievepaymentreceipts",
        "columns": {
            "id": "Unique identifier for the payment.",
            "label": "Human-readable label for the payment.",
            "total": "Total amount of the payment.",
            "status": "Current status of the payment (e.g. paid, processing).",
            "paid_at": "Time at which the payment was completed.",
            "workers": "Workers covered by the payment, with their contract ids.",
            "invoices": "Invoices settled by the payment.",
            "total_due": "Amount still due on the payment.",
            "created_at": "Time at which the payment was created.",
            "deel_reference": "Deel's own reference for the payment.",
            "payment_method": "Method used to make the payment.",
            "payment_currency": "Currency the payment was made in.",
        },
    },
    "payment_breakdowns": {
        "description": "One contract's share of a payment, split into work, bonuses, expenses and fees.",
        "docs_url": "https://developer.deel.com/reference/retrieveapaymentbreakdown",
        "columns": {
            "payment_id": "Identifier of the payment this line belongs to.",
            "contract_id": "Identifier of the contract this line is for.",
            "invoice_id": "Identifier of the invoice this line was billed on.",
            "date": "Date the line was recorded.",
            "work": "Amount charged for regular work.",
            "bonus": "Amount charged as a bonus.",
            "total": "Total amount for the line, in the contract currency.",
            "others": "Amount charged under other categories.",
            "currency": "Currency the line amounts are denominated in.",
            "expenses": "Amount charged as reimbursed expenses.",
            "overtime": "Amount charged for overtime.",
            "pro_rata": "Amount charged as a pro-rata adjustment.",
            "frequency": "Payment frequency of the contract.",
            "adjustment": "Amount charged as an adjustment.",
            "deductions": "Amount withheld as deductions.",
            "commissions": "Amount charged as commission.",
            "payment_date": "Date the payment was made.",
            "contract_type": "Type of the contract this line is for.",
            "processing_fee": "Deel processing fee charged on the line.",
            "contract_country": "Country of the contract this line is for.",
            "payment_currency": "Currency the payment was made in.",
            "general_ledger_account": "General ledger account the line is booked to.",
            "total_payment_currency": "Total for the line, converted to the payment currency.",
        },
    },
    "legal_entities": {
        "description": "A legal entity in the organization that contracts and invoices are issued under.",
        "docs_url": "https://developer.deel.com/reference/listoflegalentities",
        "columns": {
            "id": "Unique identifier for the legal entity.",
            "name": "Registered name of the legal entity.",
            "phone": "Contact phone number for the legal entity.",
            "vat_id": "VAT identification number of the legal entity.",
            "address": "Registered address of the legal entity.",
            "country": "Country the legal entity is registered in.",
            "created_at": "Time at which the legal entity was created.",
            "updated_at": "Time at which the legal entity was last updated.",
            "archived_at": "Time at which the legal entity was archived, if applicable.",
            "entity_type": "Type of the legal entity.",
            "industry_name": "Industry the legal entity operates in.",
            "entity_subtype": "Subtype of the legal entity.",
            "registrationNumber": "Company registration number of the legal entity.",
        },
    },
    "cost_centers": {
        "description": "A cost center defined on a legal entity, used to book worker costs.",
        "docs_url": "https://developer.deel.com/reference/getcostcentersbylegalentity",
        "columns": {
            "id": "Identifier for the cost center, unique within its legal entity.",
            "legal_entity_id": "Identifier of the legal entity the cost center belongs to.",
            "created_at": "Time at which the cost center was created.",
            "updated_at": "Time at which the cost center was last updated.",
            "cost_center_name": "Name of the cost center.",
            "cost_center_number": "Reference number of the cost center.",
        },
    },
    "time_offs": {
        "description": "A time-off request made by a worker, with the days it covers.",
        "docs_url": "https://developer.deel.com/reference/listtimeoffrequestsfororganization",
        "columns": {
            "id": "Unique identifier for the time-off request.",
            "amount": "Amount of time off requested, in the entitlement unit.",
            "reason": "Reason given for the time off.",
            "status": "Current status of the request (e.g. pending, approved, rejected).",
            "is_paid": "Whether the time off is paid.",
            "end_date": "Last day of the time off.",
            "created_at": "Time at which the request was created.",
            "deleted_at": "Time at which the request was deleted, if applicable.",
            "start_date": "First day of the time off.",
            "updated_at": "Time at which the request was last updated.",
            "approved_at": "Time at which the request was approved, if applicable.",
            "canceled_at": "Time at which the request was cancelled, if applicable.",
            "description": "Free-text description of the request.",
            "contract_oid": "Identifier of the contract the request is against.",
            "requested_at": "Time at which the time off was requested.",
            "time_off_type": "Type of time off, and the policy it draws from.",
            "deduction_amount": "Amount deducted from the worker's entitlement.",
            "entitlement_unit": "Unit the amount is measured in (e.g. days, hours).",
            "time_off_dailies": "Per-day breakdown of the time off.",
            "recipient_profile": "Worker profile the time off is for.",
            "requester_profile": "Worker profile that submitted the request.",
        },
    },
    "time_off_events": {
        "description": "A lifecycle event on a worker's time-off policy, such as a birth or adoption that triggers leave.",
        "docs_url": "https://developer.deel.com/reference/gettimeoffeventsforprofile",
        "columns": {
            "id": "Identifier for the event, unique within its worker profile.",
            "type": "Type of the event.",
            "policy_id": "Identifier of the time-off policy the event applies to.",
            "created_at": "Time at which the event was created.",
            "updated_at": "Time at which the event was last updated.",
            "event_details": "Details of the event, such as the birth or adoption date.",
            "hris_profile_id": "Identifier of the worker profile the event belongs to.",
            "time_off_type_id": "Identifier of the time-off type the event applies to.",
        },
    },
}
