from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "api_requests": {
        "description": "Detailed records for individual requests proxied through Kong Gateway, from Konnect "
        "Advanced Analytics (near real-time). One row per request.",
        "docs_url": "https://developer.konghq.com/api/konnect/analytics-requests/",
        "columns": {
            "request_start": "Timestamp of when the gateway began processing the request. Used as the incremental cursor and partition key.",
            "request_id": "Unique identifier for the request.",
            "trace_id": "Distributed tracing identifier for the request, when tracing is enabled.",
            "api": "Identifier of the API associated with the request.",
            "api_package": "Identifier of the API package associated with the request.",
            "api_product": "Identifier of the API product associated with the request.",
            "api_product_version": "Identifier of the API product version associated with the request.",
            "application": "Identifier of the developer application associated with the request.",
            "auth_type": "Authentication method used for the request (e.g. key-auth or openid-connect).",
            "client_ip": "IP address of the client that made the request.",
            "consumer": "Consumer that made the request, in the form control_plane_id:consumer_id.",
            "control_plane": "Identifier of the control plane that handled the request.",
            "control_plane_group": "Identifier of the control plane group that handled the request.",
            "country_code": "Country code derived from the client IP.",
            "data_plane_node": "Identifier of the data plane node that proxied the request.",
            "data_plane_node_version": "Version of the data plane node that proxied the request.",
            "gateway_service": "Identifier of the gateway service that handled the request (scoped by control plane).",
            "header_host": "Value of the Host header on the request.",
            "header_user_agent": "Value of the User-Agent header on the request.",
            "http_method": "HTTP method of the request (GET, POST, etc.).",
            "latencies_kong_gateway_ms": "Time in milliseconds spent by Kong Gateway processing the request.",
            "latencies_kong_internal_ms": "Time in milliseconds spent in Kong internal processing.",
            "latencies_response_ms": "Total response latency in milliseconds.",
            "latencies_upstream_ms": "Time in milliseconds spent waiting for the upstream service.",
            "portal": "Identifier of the developer portal associated with the request.",
            "principal": "Authenticated principal associated with the request.",
            "realm": "Authentication realm associated with the request.",
            "request_body_size": "Size of the request body in bytes.",
            "request_uri": "URI path of the request.",
            "response_body_size": "Size of the response body in bytes.",
            "response_header_content_length": "Value of the response Content-Length header.",
            "response_header_content_type": "Value of the response Content-Type header.",
            "response_http_status": "HTTP status code returned to the client.",
            "response_source": "Which component produced the response (e.g. upstream or the gateway itself).",
            "route": "Identifier of the route that matched the request (scoped by control plane).",
            "service_port": "Port of the gateway service the request was routed to.",
            "service_protocol": "Protocol of the gateway service the request was routed to.",
            "upstream_status": "HTTP status code returned by the upstream service.",
            "upstream_uri": "URI the request was proxied to on the upstream service.",
            "a2a_info": "Agent-to-agent call details for AI routes (nullable), including per-call method, task, latency, and error.",
            "mcp_info": "Model Context Protocol call details for AI routes (nullable), including session id and per-tool call method, latency, and error.",
        },
    },
}
