"""Canonical, documentation-sourced descriptions for Amazon Ads endpoints and columns.

Sourced from the official Amazon Ads API reference (https://advertising.amazon.com/API/docs/en-us/).
Keyed by the endpoint names in `settings.py` `AMAZON_ADS_ENDPOINTS`, which match the
`ExternalDataSchema.name` of a synced Amazon Ads table. Columns absent here fall back to LLM enrichment.
"""

from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "profiles": {
        "description": "An advertising profile representing an account in a specific marketplace/region.",
        "docs_url": "https://advertising.amazon.com/API/docs/en-us/reference/2/profiles",
        "columns": {
            "profileId": "Unique identifier for the advertising profile.",
            "countryCode": "Two-letter ISO country code of the marketplace the profile belongs to.",
            "currencyCode": "Three-letter ISO currency code used for the profile's spend.",
            "timezone": "Time zone configured for the profile.",
            "marketplaceStringId": "Identifier of the Amazon marketplace the profile is registered in.",
            "dailyBudget": "Default daily budget for the profile, if set.",
            "accountInfo": "Account metadata, including the account type (seller, vendor, agency) and name.",
        },
    },
    "sp_campaigns": {
        "description": "A Sponsored Products campaign that groups ad groups under a budget and targeting strategy.",
        "docs_url": "https://advertising.amazon.com/API/docs/en-us/sponsored-products/3-0/openapi/prod#tag/Campaigns",
        "columns": {
            "campaignId": "Unique identifier for the campaign.",
            "name": "Name of the campaign.",
            "state": "Current state of the campaign: enabled, paused, or archived.",
            "budget": "Budget configuration for the campaign, including amount and budget type.",
            "targetingType": "Targeting strategy of the campaign: manual or auto.",
            "startDate": "Date the campaign starts running.",
            "endDate": "Date the campaign stops running, if set.",
            "dynamicBidding": "Dynamic bidding strategy and placement bid adjustments for the campaign.",
            "portfolioId": "Identifier of the portfolio the campaign belongs to, if any.",
        },
    },
    "sp_ad_groups": {
        "description": "A Sponsored Products ad group within a campaign, grouping ads and keywords under a default bid.",
        "docs_url": "https://advertising.amazon.com/API/docs/en-us/sponsored-products/3-0/openapi/prod#tag/Ad-groups",
        "columns": {
            "adGroupId": "Unique identifier for the ad group.",
            "campaignId": "Identifier of the campaign the ad group belongs to.",
            "name": "Name of the ad group.",
            "state": "Current state of the ad group: enabled, paused, or archived.",
            "defaultBid": "Default bid applied to targets in the ad group, in the profile's currency.",
        },
    },
    "sp_product_ads": {
        "description": "A Sponsored Products ad: one advertised product (ASIN or SKU) inside an ad group.",
        "docs_url": "https://advertising.amazon.com/API/docs/en-us/sponsored-products/3-0/openapi/prod#tag/Product-ads",
        "columns": {
            "adId": "Unique identifier for the product ad.",
            "adGroupId": "Identifier of the ad group the ad belongs to.",
            "campaignId": "Identifier of the campaign the ad belongs to.",
            "asin": "ASIN of the advertised product. Set for vendor accounts only.",
            "sku": "SKU of the advertised product. Set for seller accounts only.",
            "state": "Current state of the ad: enabled, paused, or archived.",
            "customText": "Custom text shown with the ad. Set for custom text ads only.",
            "globalAdId": "Identifier of the ad across marketplaces.",
            "_profile_id": "Advertising profile the ad was synced from.",
        },
    },
    "sp_keywords": {
        "description": "A Sponsored Products keyword target, with the bid and match type used to buy that search.",
        "docs_url": "https://advertising.amazon.com/API/docs/en-us/sponsored-products/3-0/openapi/prod#tag/Keywords",
        "columns": {
            "keywordId": "Unique identifier for the keyword.",
            "adGroupId": "Identifier of the ad group the keyword belongs to.",
            "campaignId": "Identifier of the campaign the keyword belongs to.",
            "keywordText": "Text of the keyword.",
            "matchType": "How the keyword matches a shopper search: broad, phrase, or exact.",
            "bid": "Bid for the keyword. A keyword with no bid inherits the ad group's default bid.",
            "state": "Current state of the keyword: enabled, paused, or archived.",
            "nativeLanguageKeyword": "Keyword text in the advertiser's preferred language.",
            "nativeLanguageLocale": "Locale of the advertiser's preferred language, such as zh_CN.",
            "globalKeywordId": "Identifier of the keyword across marketplaces.",
            "_profile_id": "Advertising profile the keyword was synced from.",
        },
    },
    "sp_targets": {
        "description": "A Sponsored Products targeting clause: a product or category targeting expression with its bid.",
        "docs_url": "https://advertising.amazon.com/API/docs/en-us/sponsored-products/3-0/openapi/prod#tag/Targets",
        "columns": {
            "targetId": "Unique identifier for the target.",
            "adGroupId": "Identifier of the ad group the target belongs to.",
            "campaignId": "Identifier of the campaign the target belongs to.",
            "expression": "Targeting expression, such as a product ASIN or a category with refinements.",
            "resolvedExpression": "Targeting expression with its references resolved to concrete values.",
            "expressionType": "Whether the expression was set manually or generated automatically.",
            "bid": "Bid for the target. A target with no bid inherits the ad group's default bid.",
            "state": "Current state of the target: enabled, paused, or archived.",
            "globalTargetId": "Identifier of the target across marketplaces.",
            "_profile_id": "Advertising profile the target was synced from.",
        },
    },
    "sp_negative_keywords": {
        "description": "A Sponsored Products negative keyword on an ad group, excluding a shopper search from that ad group.",
        "docs_url": "https://advertising.amazon.com/API/docs/en-us/sponsored-products/3-0/openapi/prod#tag/Negative-keywords",
        "columns": {
            "keywordId": "Unique identifier for the negative keyword.",
            "adGroupId": "Identifier of the ad group the negative keyword excludes traffic from.",
            "campaignId": "Identifier of the campaign the ad group belongs to.",
            "keywordText": "Text of the negative keyword.",
            "matchType": "How the negative keyword matches a shopper search: negative broad, phrase, or exact.",
            "state": "Current state of the negative keyword: enabled, paused, or archived.",
            "nativeLanguageKeyword": "Negative keyword text in the advertiser's preferred language.",
            "nativeLanguageLocale": "Locale of the advertiser's preferred language, such as zh_CN.",
            "globalKeywordId": "Identifier of the negative keyword across marketplaces.",
            "_profile_id": "Advertising profile the negative keyword was synced from.",
        },
    },
    "sp_campaign_negative_keywords": {
        "description": "A Sponsored Products negative keyword on a campaign, excluding a shopper search from every ad group in it.",
        "docs_url": "https://advertising.amazon.com/API/docs/en-us/sponsored-products/3-0/openapi/prod#tag/Campaign-negative-keywords",
        "columns": {
            "keywordId": "Unique identifier for the campaign negative keyword.",
            "campaignId": "Identifier of the campaign the negative keyword excludes traffic from.",
            "keywordText": "Text of the negative keyword.",
            "matchType": "How the negative keyword matches a shopper search: negative phrase or negative exact.",
            "state": "Current state of the negative keyword: enabled, paused, or archived.",
            "globalKeywordId": "Identifier of the negative keyword across marketplaces.",
            "_profile_id": "Advertising profile the campaign negative keyword was synced from.",
        },
    },
    "portfolios": {
        "description": "A portfolio: a group of campaigns that shares a budget, which resolves the portfolioId the campaign tables carry.",
        "docs_url": "https://advertising.amazon.com/API/docs/en-us/reference/portfolios",
        "columns": {
            "portfolioId": "Unique identifier for the portfolio.",
            "name": "Name of the portfolio.",
            "state": "Current state of the portfolio: enabled, paused, or archived.",
            "budget": "Budget for the portfolio, including its amount, currency, policy, and date range.",
            "budgetControls": "Extra budget controls on the portfolio, such as how unspent campaign budget is shared.",
            "inBudget": "Whether the portfolio is still within its budget.",
            "extendedData": "Creation and last-update timestamps plus the portfolio's serving status.",
            "_profile_id": "Advertising profile the portfolio was synced from.",
        },
    },
    "sb_campaigns": {
        "description": "A Sponsored Brands campaign that groups ad groups under a budget and a targeting strategy.",
        "docs_url": "https://advertising.amazon.com/API/docs/en-us/sponsored-brands/3-0/openapi/prod",
        "columns": {
            "campaignId": "Unique identifier for the campaign.",
            "name": "Name of the campaign.",
            "adProduct": "Ad product the campaign belongs to.",
            "state": "Current state of the campaign: enabled, paused, or archived.",
            "status": "Serving status of the campaign, which reflects why it is or is not delivering.",
            "budgets": "Budget details for the campaign, including amount, currency, and budget type.",
            "costType": "How the campaign is charged, such as cost per click.",
            "portfolioId": "Identifier of the portfolio the campaign belongs to, if any.",
            "startDateTime": "Date and time the campaign starts running.",
            "endDateTime": "Date and time the campaign stops running, if set.",
            "creationDateTime": "Date and time the campaign was created.",
            "lastUpdatedDateTime": "Date and time the campaign was last updated.",
            "marketplaceScope": "Whether the campaign applies to one marketplace or to several.",
            "marketplaces": "Amazon marketplaces the campaign runs in.",
            "countries": "Countries whose Amazon retail supply the campaign targets.",
            "tags": "Key-value labels applied to the campaign.",
            "_profile_id": "Advertising profile the campaign was synced from.",
        },
    },
    "sb_ad_groups": {
        "description": "A Sponsored Brands ad group within a campaign, grouping its ads and targets.",
        "docs_url": "https://advertising.amazon.com/API/docs/en-us/sponsored-brands/3-0/openapi/prod",
        "columns": {
            "adGroupId": "Unique identifier for the ad group.",
            "campaignId": "Identifier of the campaign the ad group belongs to.",
            "name": "Name of the ad group.",
            "adProduct": "Ad product the ad group belongs to.",
            "state": "Current state of the ad group: enabled, paused, or archived.",
            "status": "Serving status of the ad group, which reflects why it is or is not delivering.",
            "creationDateTime": "Date and time the ad group was created.",
            "lastUpdatedDateTime": "Date and time the ad group was last updated.",
            "marketplaceScope": "Whether the ad group applies to one marketplace or to several.",
            "marketplaces": "Amazon marketplaces the ad group runs in.",
            "_profile_id": "Advertising profile the ad group was synced from.",
        },
    },
    "sb_ads": {
        "description": "A Sponsored Brands ad: one creative inside an ad group.",
        "docs_url": "https://advertising.amazon.com/API/docs/en-us/sponsored-brands/3-0/openapi/prod",
        "columns": {
            "adId": "Unique identifier for the ad.",
            "adGroupId": "Identifier of the ad group the ad belongs to.",
            "campaignId": "Identifier of the campaign the ad belongs to.",
            "name": "Name of the ad.",
            "adProduct": "Ad product the ad belongs to.",
            "adType": "Type of the ad, which determines the creative it carries.",
            "creative": "Creative content of the ad, such as its headline, assets, and promoted products.",
            "state": "Current state of the ad: enabled, paused, or archived.",
            "status": "Serving status of the ad, which reflects why it is or is not delivering.",
            "creationDateTime": "Date and time the ad was created.",
            "lastUpdatedDateTime": "Date and time the ad was last updated.",
            "marketplaceScope": "Whether the ad applies to one marketplace or to several.",
            "marketplaces": "Amazon marketplaces the ad runs in.",
            "_profile_id": "Advertising profile the ad was synced from.",
        },
    },
    "sb_targets": {
        "description": "A Sponsored Brands target: one targeting expression with its bid, positive or negative.",
        "docs_url": "https://advertising.amazon.com/API/docs/en-us/sponsored-brands/3-0/openapi/prod",
        "columns": {
            "targetId": "Unique identifier for the target.",
            "adGroupId": "Identifier of the ad group the target belongs to. Set for ad-group level targets only.",
            "campaignId": "Identifier of the campaign the target belongs to. Set for campaign-level targets only.",
            "adProduct": "Ad product the target belongs to.",
            "targetType": "Type of the target, such as a keyword, a product, or an audience.",
            "targetLevel": "Whether the target applies at the campaign or the ad group level.",
            "targetDetails": "The targeting expression itself, such as the keyword text or the targeted product.",
            "negative": "Whether the target excludes traffic instead of buying it.",
            "bid": "Bid for the target. A target with no bid inherits the ad group's bid.",
            "state": "Current state of the target: enabled, paused, or archived.",
            "status": "Serving status of the target, which reflects why it is or is not delivering.",
            "creationDateTime": "Date and time the target was created.",
            "lastUpdatedDateTime": "Date and time the target was last updated.",
            "_profile_id": "Advertising profile the target was synced from.",
        },
    },
    "sd_campaigns": {
        "description": "A Sponsored Display campaign that groups ad groups under a budget and a targeting strategy.",
        "docs_url": "https://advertising.amazon.com/API/docs/en-us/sponsored-display/3-0/openapi",
        "columns": {
            "campaignId": "Unique identifier for the campaign.",
            "name": "Name of the campaign.",
            "adProduct": "Ad product the campaign belongs to.",
            "state": "Current state of the campaign: enabled, paused, or archived.",
            "status": "Serving status of the campaign, which reflects why it is or is not delivering.",
            "budgets": "Budget details for the campaign, including amount, currency, and budget type.",
            "costType": "How the campaign is charged, such as cost per click.",
            "portfolioId": "Identifier of the portfolio the campaign belongs to, if any.",
            "startDateTime": "Date and time the campaign starts running.",
            "endDateTime": "Date and time the campaign stops running, if set.",
            "creationDateTime": "Date and time the campaign was created.",
            "lastUpdatedDateTime": "Date and time the campaign was last updated.",
            "marketplaceScope": "Whether the campaign applies to one marketplace or to several.",
            "marketplaces": "Amazon marketplaces the campaign runs in.",
            "countries": "Countries whose Amazon retail supply the campaign targets.",
            "tags": "Key-value labels applied to the campaign.",
            "_profile_id": "Advertising profile the campaign was synced from.",
        },
    },
    "sd_ad_groups": {
        "description": "A Sponsored Display ad group within a campaign, grouping its ads and targets.",
        "docs_url": "https://advertising.amazon.com/API/docs/en-us/sponsored-display/3-0/openapi",
        "columns": {
            "adGroupId": "Unique identifier for the ad group.",
            "campaignId": "Identifier of the campaign the ad group belongs to.",
            "name": "Name of the ad group.",
            "adProduct": "Ad product the ad group belongs to.",
            "state": "Current state of the ad group: enabled, paused, or archived.",
            "status": "Serving status of the ad group, which reflects why it is or is not delivering.",
            "creationDateTime": "Date and time the ad group was created.",
            "lastUpdatedDateTime": "Date and time the ad group was last updated.",
            "marketplaceScope": "Whether the ad group applies to one marketplace or to several.",
            "marketplaces": "Amazon marketplaces the ad group runs in.",
            "_profile_id": "Advertising profile the ad group was synced from.",
        },
    },
    "sd_ads": {
        "description": "A Sponsored Display ad: one creative inside an ad group.",
        "docs_url": "https://advertising.amazon.com/API/docs/en-us/sponsored-display/3-0/openapi",
        "columns": {
            "adId": "Unique identifier for the ad.",
            "adGroupId": "Identifier of the ad group the ad belongs to.",
            "campaignId": "Identifier of the campaign the ad belongs to.",
            "name": "Name of the ad.",
            "adProduct": "Ad product the ad belongs to.",
            "adType": "Type of the ad, which determines the creative it carries.",
            "creative": "Creative content of the ad, such as its headline, assets, and promoted products.",
            "state": "Current state of the ad: enabled, paused, or archived.",
            "status": "Serving status of the ad, which reflects why it is or is not delivering.",
            "creationDateTime": "Date and time the ad was created.",
            "lastUpdatedDateTime": "Date and time the ad was last updated.",
            "marketplaceScope": "Whether the ad applies to one marketplace or to several.",
            "marketplaces": "Amazon marketplaces the ad runs in.",
            "_profile_id": "Advertising profile the ad was synced from.",
        },
    },
    "sd_targets": {
        "description": "A Sponsored Display target: one targeting expression with its bid, positive or negative.",
        "docs_url": "https://advertising.amazon.com/API/docs/en-us/sponsored-display/3-0/openapi",
        "columns": {
            "targetId": "Unique identifier for the target.",
            "adGroupId": "Identifier of the ad group the target belongs to. Set for ad-group level targets only.",
            "campaignId": "Identifier of the campaign the target belongs to. Set for campaign-level targets only.",
            "adProduct": "Ad product the target belongs to.",
            "targetType": "Type of the target, such as a keyword, a product, or an audience.",
            "targetLevel": "Whether the target applies at the campaign or the ad group level.",
            "targetDetails": "The targeting expression itself, such as the keyword text or the targeted product.",
            "negative": "Whether the target excludes traffic instead of buying it.",
            "bid": "Bid for the target. A target with no bid inherits the ad group's bid.",
            "state": "Current state of the target: enabled, paused, or archived.",
            "status": "Serving status of the target, which reflects why it is or is not delivering.",
            "creationDateTime": "Date and time the target was created.",
            "lastUpdatedDateTime": "Date and time the target was last updated.",
            "_profile_id": "Advertising profile the target was synced from.",
        },
    },
    "sp_campaign_reports": {
        "description": "Daily Sponsored Products performance for each campaign, from the async reporting API.",
        "docs_url": "https://advertising.amazon.com/API/docs/en-us/guides/reporting/v3/report-types/campaign",
        "columns": {
            "date": "Date the ad activity happened, in YYYY-MM-DD format.",
            "campaignId": "Identifier of the campaign the row reports on.",
            "campaignName": "Name of the campaign.",
            "campaignStatus": "Status of the campaign.",
            "campaignBiddingStrategy": "Bidding strategy the campaign ran with.",
            "campaignBudgetAmount": "Total budget allocated to the campaign.",
            "campaignBudgetType": "Whether the campaign budget is daily or lifetime.",
            "campaignBudgetCurrencyCode": "Currency code of the campaign budget.",
            "campaignRuleBasedBudgetAmount": "Value of the campaign's rule-based budget.",
            "campaignApplicableBudgetRuleId": "Identifier of the budget rule active on the campaign.",
            "campaignApplicableBudgetRuleName": "Name of the budget rule active on the campaign.",
            "impressions": "Total number of ad impressions.",
            "clicks": "Total number of clicks on an ad.",
            "clickThroughRate": "Clicks divided by impressions.",
            "cost": "Total cost of ad clicks.",
            "costPerClick": "Total cost divided by total number of clicks.",
            "spend": "Total cost of ad clicks.",
            "topOfSearchImpressionShare": "Share of eligible top-of-search impressions the campaign won.",
            "addToList": "Times shoppers added a promoted product to a wish list, gift list, or registry.",
            "qualifiedBorrows": "Kindle Unlimited borrows attributed to ad exposure that triggered a royalty payment.",
            "royaltyQualifiedBorrows": "Estimated royalty payment for those Kindle Unlimited borrows.",
            "purchases1d": "Attributed conversion events within 1 day of an ad click.",
            "purchases7d": "Attributed conversion events within 7 days of an ad click.",
            "purchases14d": "Attributed conversion events within 14 days of an ad click.",
            "purchases30d": "Attributed conversion events within 30 days of an ad click.",
            "purchasesSameSku1d": "Attributed conversions within 1 day of a click where the purchased SKU was the advertised SKU.",
            "purchasesSameSku7d": "Attributed conversions within 7 days of a click where the purchased SKU was the advertised SKU.",
            "purchasesSameSku14d": "Attributed conversions within 14 days of a click where the purchased SKU was the advertised SKU.",
            "purchasesSameSku30d": "Attributed conversions within 30 days of a click where the purchased SKU was the advertised SKU.",
            "sales1d": "Total value of sales within 1 day of an ad click.",
            "sales7d": "Total value of sales within 7 days of an ad click.",
            "sales14d": "Total value of sales within 14 days of an ad click.",
            "sales30d": "Total value of sales within 30 days of an ad click.",
            "attributedSalesSameSku1d": "Sales within 1 day of a click where the purchased SKU was the advertised SKU.",
            "attributedSalesSameSku7d": "Sales within 7 days of a click where the purchased SKU was the advertised SKU.",
            "attributedSalesSameSku14d": "Sales within 14 days of a click where the purchased SKU was the advertised SKU.",
            "attributedSalesSameSku30d": "Sales within 30 days of a click where the purchased SKU was the advertised SKU.",
            "unitsSoldClicks1d": "Units ordered within 1 day of an ad click.",
            "unitsSoldClicks7d": "Units ordered within 7 days of an ad click.",
            "unitsSoldClicks14d": "Units ordered within 14 days of an ad click.",
            "unitsSoldClicks30d": "Units ordered within 30 days of an ad click.",
            "unitsSoldSameSku1d": "Units ordered within 1 day of a click where the purchased SKU was the advertised SKU.",
            "unitsSoldSameSku7d": "Units ordered within 7 days of a click where the purchased SKU was the advertised SKU.",
            "unitsSoldSameSku14d": "Units ordered within 14 days of a click where the purchased SKU was the advertised SKU.",
            "unitsSoldSameSku30d": "Units ordered within 30 days of a click where the purchased SKU was the advertised SKU.",
            "kindleEditionNormalizedPagesRead14d": "Attributed Kindle edition normalized pages read within 14 days of an ad click.",
            "kindleEditionNormalizedPagesRoyalties14d": "Estimated royalties for those Kindle edition normalized pages.",
            "_profile_id": "Advertising profile the report was requested for.",
        },
    },
}
