{{- if not .Values.posthog.existingSecret }}
{{- if not .Values.posthog.apiKey }}
{{- fail "posthog.apiKey is required (or set posthog.existingSecret)" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "posthog-metrics-agent.fullname" . }}
    labels:
        {{- include "posthog-metrics-agent.labels" . | nindent 8 }}
type: Opaque
data:
    posthog-api-key: {{ .Values.posthog.apiKey | b64enc }}
{{- end }}
