{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ include "posthog-metrics-agent.serviceAccountName" . }}
    labels:
        {{- include "posthog-metrics-agent.labels" . | nindent 8 }}
{{- end }}
