import { ComponentMeta } from '@storybook/react'
import { ErrorDisplay } from 'lib/components/Errors/ErrorDisplay'

export default {
    title: 'Components/Errors/Error Display',
    component: ErrorDisplay,
} as ComponentMeta<typeof ErrorDisplay>

export function ResizeObserverLoopLimitExceeded(): JSX.Element {
    return (
        <ErrorDisplay
            event={{
                id: '12345',
                elements: [],
                uuid: '018880b6-b781-0008-a2e5-629b2624fd2f',
                event: '$exception',
                properties: {
                    $os: 'Windows',
                    $os_version: '10.0',
                    $browser: 'Chrome',
                    $device_type: 'Desktop',
                    $current_url: 'https://app.posthog.com/home',
                    $host: 'app.posthog.com',
                    $pathname: '/home',
                    $browser_version: 113,
                    $browser_language: 'es-ES',
                    $screen_height: 1080,
                    $screen_width: 1920,
                    $viewport_height: 929,
                    $viewport_width: 1920,
                    $lib: 'web',
                    $lib_version: '1.63.3',
                    distinct_id: 'iOizUPH4RH65nZjvGVBz5zZUmwdHvq2mxzNySQqqYkG',
                    $device_id: '186144e7357245-0cfe8bf1b5b877-26021051-1fa400-186144e7358d3',
                    $active_feature_flags: ['are-the-flags', 'important-for-the-error'],
                    $feature_flag_payloads: {
                        'are-the-flags': '{\n    "flag": "payload"\n}',
                    },
                    $user_id: 'iOizUPH4RH65nZjvGVBz5zZUmwdHvq2mxzNySQqqYkG',
                    $groups: {
                        project: '00000000-0000-0000-1847-88f0ffa23444',
                        organization: '00000000-0000-0000-a050-5d4557279956',
                        customer: 'the-customer',
                        instance: 'https://app.posthog.com',
                    },
                    posthog_version: '1.43.0',
                    $exception_message: 'ResizeObserver loop limit exceeded',
                    $exception_type: 'Error',
                    $exception_personURL: 'https://app.posthog.com/person/the-person-id',
                    $sentry_event_id: 'if-from-the-sentry-integratino',
                    $sentry_exception: {
                        values: [
                            {
                                value: 'ResizeObserver loop limit exceeded',
                                type: 'Error',
                                mechanism: {
                                    type: 'onerror',
                                    handled: false,
                                    synthetic: true,
                                },
                                stacktrace: {
                                    frames: [
                                        {
                                            colno: 0,
                                            filename: 'https://app.posthog.com/home',
                                            function: '?',
                                            in_app: true,
                                            lineno: 0,
                                        },
                                    ],
                                },
                            },
                        ],
                    },
                    $sentry_exception_message: 'ResizeObserver loop limit exceeded',
                    $sentry_exception_type: 'Error',
                    $sentry_tags: {
                        'PostHog Person URL': 'https://app.posthog.com/person/the-person-id',
                        'PostHog Recording URL': 'https://app.posthog.com/replay/the-session-id?t=866',
                    },
                    $sentry_url:
                        'https://sentry.io/organizations/posthog/issues/?project=the-sentry-project-id&query=the-sentry-id',
                    $session_id: 'the-session-id',
                    $window_id: 'the-window-id',
                    $pageview_id: 'the-pageview-id',
                    $sent_at: '2023-06-03T10:03:57.787000+00:00',
                    $geoip_city_name: 'Whoville',
                    $geoip_country_name: 'Wholand',
                    $geoip_country_code: 'WH',
                    $geoip_continent_name: 'Mystery',
                    $geoip_continent_code: 'MY',
                    $geoip_latitude: -30.5023,
                    $geoip_longitude: -71.1545,
                    $geoip_time_zone: 'UTC',
                    $lib_version__major: 1,
                    $lib_version__minor: 63,
                    $lib_version__patch: 3,
                },
                timestamp: '2023-06-03T03:03:57.316-07:00',
                distinct_id: 'the-distinct-id',
                elements_chain: '',
            }}
        />
    )
}

export function SafariScriptError(): JSX.Element {
    return (
        <ErrorDisplay
            event={{
                id: '12345',
                elements: [],
                uuid: '018884fc-27cd-7bb9-bde0-cac3f4f332d1',
                event: '$exception',
                properties: {
                    $os: 'Mac OS X',
                    $os_version: '10.15.7',
                    $browser: 'Safari',
                    $device_type: 'Desktop',
                    $current_url: 'http://127.0.0.1:8000/home',
                    $host: '127.0.0.1:8000',
                    $pathname: '/home',
                    $browser_version: 16.5,
                    $browser_language: 'en-GB',
                    $screen_height: 982,
                    $screen_width: 1512,
                    $viewport_height: 892,
                    $viewport_width: 1280,
                    $lib: 'web',
                    $lib_version: '1.63.2',
                    distinct_id: 'Hgc5d40XTIKjLyFlH0EEkYP2EiIVKC2b4dR9gsZLIEE',
                    $device_id: '18880b8da1a993-0dad7b6e66353d-3b626b4b-16a7f0-18880b8da1b5c42',
                    $console_log_recording_enabled_server_side: true,
                    $session_recording_recorder_version_server_side: 'v2',
                    $autocapture_disabled_server_side: false,
                    $active_feature_flags: [
                        'cloud-announcement',
                        'funnels-cue-opt-out-7301',
                        'retention-breakdown',
                        'hackathon-apm',
                        '7569-insight-cohorts',
                    ],
                    $feature_flag_payloads: {},
                    realm: 'hosted-clickhouse',
                    email_service_available: false,
                    slack_service_available: false,
                    $user_id: 'Hgc5d40XTIKjLyFlH0EEkYP2EiIVKC2b4dR9gsZLIEE',
                    is_demo_project: false,
                    posthog_version: '1.43.0',
                    has_billing_plan: false,
                    'unit_amount_usd.events': null,
                    'free_allocation.events': null,
                    'unit_amount_usd.recordings': null,
                    'free_allocation.recordings': null,
                    $referrer: '$direct',
                    $referring_domain: '$direct',
                    $exception_type: 'Error',
                    $exception_message: 'Script error.',
                    $exception_is_synthetic: true,
                    token: 'phc_uymfYvhMifVEE5rBnycDYmP2UGPQ0eCS1pK6u6O14I7',
                    $session_id: '18884fc025e42b4-0919a8dcd458ce8-3b626b4b-16a7f0-18884fc025f6521',
                    $window_id: '18884fc02606918-00ee95b7b5056c-3b626b4b-16a7f0-18884fc02615d7f',
                    $pageview_id: '18884fc02f02a61-05ef90806b2e74-3b626b4b-16a7f0-18884fc02f1333d',
                    $geoip_city_name: 'Sydney',
                    $geoip_country_name: 'Australia',
                    $geoip_country_code: 'AU',
                    $geoip_continent_name: 'Oceania',
                    $geoip_continent_code: 'OC',
                    $geoip_postal_code: '2000',
                    $geoip_latitude: -33.8715,
                    $geoip_longitude: 151.2006,
                    $geoip_time_zone: 'Australia/Sydney',
                    $geoip_subdivision_1_code: 'NSW',
                    $geoip_subdivision_1_name: 'New South Wales',
                    $plugins_succeeded: ['GeoIP (1)'],
                    $plugins_failed: [],
                    $plugins_deferred: [],
                    $ip: '127.0.0.1',
                    $group_0: '018873e7-5631-0000-fe97-53ce985ebf86',
                    $group_1: '018873e7-4cdd-0000-7d06-221b464d4270',
                    $group_2: 'http://localhost:8000',
                },
                timestamp: '2023-06-04T05:58:17.851Z',
                distinct_id: 'Hgc5d40XTIKjLyFlH0EEkYP2EiIVKC2b4dR9gsZLIEE',
                elements_chain: '',
            }}
        />
    )
}

export function ImportingModule(): JSX.Element {
    return (
        <ErrorDisplay
            event={{
                id: '12345',
                elements: [],
                uuid: '0188852a-f47b-7f7d-b328-80fc4117080e',
                event: '$exception',
                properties: {
                    $os: 'Mac OS X',
                    $os_version: '10.15.7',
                    $browser: 'Safari',
                    $device_type: 'Desktop',
                    $current_url: 'http://127.0.0.1:8000/home',
                    $host: '127.0.0.1:8000',
                    $pathname: '/home',
                    $browser_version: 16.5,
                    $browser_language: 'en-GB',
                    $screen_height: 982,
                    $screen_width: 1512,
                    $viewport_height: 892,
                    $viewport_width: 1280,
                    $lib: 'web',
                    $lib_version: '1.63.2',
                    distinct_id: 'Hgc5d40XTIKjLyFlH0EEkYP2EiIVKC2b4dR9gsZLIEE',
                    $device_id: '18880b8da1a993-0dad7b6e66353d-3b626b4b-16a7f0-18880b8da1b5c42',
                    $console_log_recording_enabled_server_side: true,
                    $session_recording_recorder_version_server_side: 'v2',
                    $autocapture_disabled_server_side: false,
                    $active_feature_flags: [
                        'cloud-announcement',
                        'funnels-cue-opt-out-7301',
                        'retention-breakdown',
                        'hackathon-apm',
                        '7569-insight-cohorts',
                        'smoothing-interval',
                        'billing-limit',
                        'kafka-inspector',
                        'historical-exports-v2',
                        'person-on-events-enabled',
                        'region-select',
                        'ingestion-warnings-enabled',
                        'session-reset-on-load',
                        'recordings-on-feature-flags',
                        'auto-rollback-feature-flags',
                        'onboarding-v2-demo',
                        'feature-flag-rollout-ux',
                        'role-based-access',
                        'yule-hog',
                        'query_running_time',
                        'recording-debugging',
                        'sampling',
                        'recordings-v2-recorder',
                        'enable-prompts',
                        'feedback-scene',
                        'recordings-list-v2-enabled',
                        'hogql',
                        'notebooks',
                        'early-access-feature',
                        'early-access-feature-site-button',
                        'hedgehog-mode-debug',
                        'billing-by-products',
                        'recordings-dom-explorer',
                        'auto-redirect',
                        'session-recording-blob-replay',
                        'session-recording-infinite-list',
                        'session-recording-summary-listing',
                        'surveys',
                        'new-empty-states',
                    ],
                    realm: 'hosted-clickhouse',
                    email_service_available: false,
                    slack_service_available: false,
                    $user_id: 'Hgc5d40XTIKjLyFlH0EEkYP2EiIVKC2b4dR9gsZLIEE',
                    is_demo_project: false,
                    posthog_version: '1.43.0',
                    has_billing_plan: false,
                    'unit_amount_usd.events': null,
                    'free_allocation.events': null,
                    'unit_amount_usd.recordings': null,
                    'free_allocation.recordings': null,
                    $referrer: '$direct',
                    $referring_domain: '$direct',
                    $exception_type: 'UnhandledRejection',
                    $exception_message: "Importing module '/static/chunk-PIJHGO7Q.js' is not found.",
                    $exception_stack_trace_raw: '[]',
                    $exception_handled: false,
                    token: 'phc_uymfYvhMifVEE5rBnycDYmP2UGPQ0eCS1pK6u6O14I7',
                    $session_id: '188852af2e03cdc-03d459051f4b9b-3b626b4b-16a7f0-188852af2e163dc',
                    $window_id: '188852af2e26ad9-047c6904d18229-3b626b4b-16a7f0-188852af2e365dc',
                    $pageview_id: '188852af2c98ba-0e8752fe2e9f3-3b626b4b-16a7f0-188852af2ca5673',
                    $set_once: {
                        $initial_os: 'Mac OS X',
                        $initial_browser: 'Safari',
                        $initial_device_type: 'Desktop',
                        $initial_current_url: 'http://127.0.0.1:8000/home',
                        $initial_pathname: '/home',
                        $initial_browser_version: 16.5,
                        $initial_referrer: '$direct',
                        $initial_referring_domain: '$direct',
                    },
                    $sent_at: '2023-06-04T06:49:27.458000+00:00',
                    $geoip_city_name: 'Sydney',
                    $geoip_country_name: 'Australia',
                    $geoip_country_code: 'AU',
                    $geoip_continent_name: 'Oceania',
                    $geoip_continent_code: 'OC',
                    $geoip_postal_code: '2000',
                    $geoip_latitude: -33.8715,
                    $geoip_longitude: 151.2006,
                    $geoip_time_zone: 'Australia/Sydney',
                    $geoip_subdivision_1_code: 'NSW',
                    $geoip_subdivision_1_name: 'New South Wales',
                    $plugins_succeeded: ['GeoIP (1)'],
                    $plugins_failed: [],
                    $plugins_deferred: [],
                    $ip: '127.0.0.1',
                    $group_0: '018873e7-5631-0000-fe97-53ce985ebf86',
                    $group_1: '018873e7-4cdd-0000-7d06-221b464d4270',
                    $group_2: 'http://localhost:8000',
                },
                timestamp: '2023-06-04T06:49:24.867Z',
                distinct_id: 'Hgc5d40XTIKjLyFlH0EEkYP2EiIVKC2b4dR9gsZLIEE',
                elements_chain: '',
            }}
        />
    )
}
