from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "calls": {
        "description": "A recorded call or meeting analyzed by Leexi, including its transcript, AI summary, chapters, speakers, and tags.",
        "docs_url": "https://docs.public-api.leexi.ai/reference/list-calls",
        "columns": {
            "uuid": "Unique identifier of the call.",
            "title": "Title of the call.",
            "description": "Description of the call.",
            "created_at": "When the call record was created in Leexi.",
            "updated_at": "When the call record was last updated.",
            "performed_at": "When the call actually took place.",
            "direction": "Direction of the call (e.g. inbound or outbound).",
            "duration": "Duration of the call in seconds.",
            "is_video": "Whether the call was a video call.",
            "visible": "Whether the call is visible in Leexi.",
            "locale": "Language locale detected or set for the call.",
            "leexi_url": "Link to the call page in the Leexi app.",
            "recording_url": "Link to the call recording.",
            "transcript_url": "Link to the call transcript.",
            "source": "Integration slug the call was imported from (e.g. aircall).",
            "source_id": "Identifier of the call within the source integration.",
            "simple_transcript": "Plain-text, speaker-labeled transcript of the call.",
            "summary": "AI-generated summary of the call.",
            "conversation_type": "Conversation type assigned to the call (uuid, slug, active).",
            "owner": "User who owns the call (uuid, name, email).",
            "participating_users": "Leexi users who participated in the call.",
            "customers": "External participants on the call (uuid, name, email, phone number).",
            "chapters": "AI-generated chapters with title, text, and start time.",
            "prompts": "AI prompt completions attached to the call (category, title, completions).",
            "speakers": "Speaker-level stats including talk duration and longest monologue.",
            "tags": "Tags applied to the call.",
            "tasks": "Tasks created from the call.",
            "audio_archived_at": "When the call audio was archived, if it was.",
            "video_archived_at": "When the call video was archived, if it was.",
            "transcript_archived_at": "When the call transcript was archived, if it was.",
            "completions_archived_at": "When the call AI completions were archived, if they were.",
        },
    },
    "call_notes": {
        "description": "An AI-generated note attached to a call, from prompts in the summary or text categories, with per-locale translations.",
        "docs_url": "https://docs.public-api.leexi.ai/reference/list-call-notes",
        "columns": {
            "uuid": "Unique identifier of the call note.",
            "call_uuid": "Unique identifier of the call this note belongs to.",
            "created_at": "When the note was created.",
            "updated_at": "When the note was last updated.",
            "call": "Summary of the call the note belongs to (uuid, timestamps, duration, direction).",
            "prompt": "Prompt that generated the note (uuid, title, category).",
            "translations": "Note text per locale, including the original text.",
        },
    },
    "meeting_events": {
        "description": "A scheduled meeting Leexi tracks for recording, including the meeting link, attendees, and notetaker bot runs.",
        "docs_url": "https://docs.public-api.leexi.ai/reference/list-meeting-events",
        "columns": {
            "uuid": "Unique identifier of the meeting event.",
            "title": "Title of the meeting.",
            "organizer": "Organizer of the meeting (email).",
            "attendees": "Meeting attendees (email).",
            "meeting_url": "Join link for the meeting.",
            "meeting_provider": "Meeting platform (e.g. teams_meeting, google_meeting).",
            "internal": "Whether every attendee belongs to the company.",
            "direction": "Direction of the meeting (e.g. outbound).",
            "start_time": "Scheduled start time of the meeting.",
            "end_time": "Scheduled end time of the meeting.",
            "description": "Description of the meeting.",
            "owned": "Whether the API key's company owns the meeting.",
            "to_record": "Whether Leexi is set to record the meeting.",
            "bot_scheduled": "Whether the Leexi notetaker bot is scheduled to join.",
            "bot_running": "Whether the Leexi notetaker bot is currently running.",
            "bot_runs": "Past notetaker bot runs with start, end, and end reason.",
            "origin": "How the event was created (calendar, manual, or api).",
            "created_at": "When the meeting event was created in Leexi.",
            "updated_at": "When the meeting event was last updated.",
            "recording_notified": "Whether attendees were notified about the recording.",
            "active": "Whether the meeting event is active.",
        },
    },
    "users": {
        "description": "A Leexi user account, with license and team membership.",
        "docs_url": "https://docs.public-api.leexi.ai/reference/list-users",
        "columns": {
            "uuid": "Unique identifier of the user.",
            "name": "Full name of the user.",
            "email": "Email address of the user.",
            "active": "Whether the user account is active.",
            "license": "License type assigned to the user.",
            "team": "Team the user belongs to (uuid, name, active).",
            "created_at": "When the user was created.",
            "updated_at": "When the user was last updated.",
        },
    },
    "teams": {
        "description": "A team of users in Leexi.",
        "docs_url": "https://docs.public-api.leexi.ai/reference/list-teams",
        "columns": {
            "uuid": "Unique identifier of the team.",
            "name": "Name of the team.",
            "active": "Whether the team is active.",
            "created_at": "When the team was created.",
            "updated_at": "When the team was last updated.",
        },
    },
}
