import { MakeLogicType, actions, afterMount, connect, kea, listeners, path, reducers, selectors } from 'kea'
import { loaders } from 'kea-loaders'

import { lemonToast } from '@posthog/lemon-ui'

import { dayjs } from 'lib/dayjs'
import { teamLogic } from 'scenes/teamLogic'

import { logsAnomaliesScanCreate, logsServicesCreate } from 'products/logs/frontend/generated/api'
import type { LogsAnomalyScanResponseApi } from 'products/logs/frontend/generated/api.schemas'

export interface ScanWindowOption {
    value: number
    label: string
}

// The endpoint accepts at most 7 days per scan.
export const SCAN_WINDOW_OPTIONS: ScanWindowOption[] = [
    { value: 1, label: 'Last hour' },
    { value: 6, label: 'Last 6 hours' },
    { value: 24, label: 'Last 24 hours' },
    { value: 72, label: 'Last 3 days' },
    { value: 168, label: 'Last 7 days' },
]

export const DEFAULT_SCAN_WINDOW_HOURS = 24

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface logsAnomaliesLogicValues {
    currentTeamId: number | null // teamLogic
    scanDisabledReason: string | null
    scanResult: LogsAnomalyScanResponseApi | null
    scanResultLoading: boolean
    serviceName: string | null
    serviceSuggestions: string[]
    serviceSuggestionsLoading: boolean
    windowHours: number
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface logsAnomaliesLogicActions {
    loadServiceSuggestions: () => any
    loadServiceSuggestionsFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadServiceSuggestionsSuccess: (
        serviceSuggestions: string[],
        payload?: any
    ) => {
        serviceSuggestions: string[]
        payload?: any
    }
    runScan: () => any
    runScanFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    runScanSuccess: (
        scanResult: LogsAnomalyScanResponseApi | null,
        payload?: any
    ) => {
        scanResult: LogsAnomalyScanResponseApi | null
        payload?: any
    }
    setServiceName: (serviceName: string | null) => {
        serviceName: string | null
    }
    setWindowHours: (windowHours: number) => {
        windowHours: number
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface logsAnomaliesLogicMeta {
    __keaTypeGenInternalSelectorTypes: {
        scanDisabledReason: (serviceName: string | null, scanResultLoading: boolean) => string | null
    }
}

export type logsAnomaliesLogicType = MakeLogicType<
    logsAnomaliesLogicValues,
    logsAnomaliesLogicActions,
    Record<string, any>,
    logsAnomaliesLogicMeta
>

export const logsAnomaliesLogic = kea<logsAnomaliesLogicType>([
    path(['products', 'logs', 'frontend', 'logsAnomaliesLogic']),
    connect(() => ({ values: [teamLogic, ['currentTeamId']] })),
    actions({
        setServiceName: (serviceName: string | null) => ({ serviceName }),
        setWindowHours: (windowHours: number) => ({ windowHours }),
    }),
    loaders(({ values }) => ({
        serviceSuggestions: [
            [] as string[],
            {
                loadServiceSuggestions: async () => {
                    const response = await logsServicesCreate(String(values.currentTeamId), {
                        query: { dateRange: { date_from: '-7d' } },
                    })
                    return response.services
                        .map((service) => service.service_name)
                        .filter((name) => !name.startsWith('('))
                },
            },
        ],
        scanResult: [
            null as LogsAnomalyScanResponseApi | null,
            {
                runScan: async () => {
                    if (!values.serviceName) {
                        return values.scanResult
                    }
                    const now = dayjs.utc()
                    return await logsAnomaliesScanCreate(String(values.currentTeamId), {
                        serviceName: values.serviceName,
                        dateRange: {
                            date_from: now.subtract(values.windowHours, 'hour').toISOString(),
                            date_to: now.toISOString(),
                        },
                    })
                },
            },
        ],
    })),
    reducers({
        serviceName: [
            null as string | null,
            {
                setServiceName: (_, { serviceName }) => serviceName,
            },
        ],
        windowHours: [
            DEFAULT_SCAN_WINDOW_HOURS as number,
            {
                setWindowHours: (_, { windowHours }) => windowHours,
            },
        ],
    }),
    selectors({
        scanDisabledReason: [
            (s) => [s.serviceName, s.scanResultLoading],
            (serviceName: string | null, scanResultLoading: boolean): string | null => {
                if (!serviceName) {
                    return 'Pick a service to scan first'
                }
                if (scanResultLoading) {
                    return 'A scan is already running'
                }
                return null
            },
        ],
    }),
    listeners(() => ({
        runScanFailure: ({ error, errorObject }) => {
            // The endpoint returns a plain { error } body when the scan blows
            // its read budget at every degradation step (HTTP 422).
            const detail = errorObject?.data?.error ?? error
            lemonToast.error(detail || 'The anomaly scan failed. Try a shorter window.')
        },
    })),
    afterMount(({ actions }) => {
        actions.loadServiceSuggestions()
    }),
])
