-- AUTO-GENERATED from the declarative HCL by ops/gen-sql.sh — do not edit.
-- Full CREATE schema for the prod-us/aux node. Apply to a fresh ClickHouse to build it.

CREATE TABLE posthog.hog_invocation_results_data (
  team_id Int64,
  function_kind LowCardinality(String),
  function_id String,
  invocation_id String,
  parent_run_id String,
  status LowCardinality(String),
  attempts UInt8,
  is_retry UInt8,
  scheduled_at DateTime64(6, 'UTC'),
  first_scheduled_at DateTime64(6, 'UTC') DEFAULT scheduled_at,
  started_at Nullable(DateTime64(6, 'UTC')),
  finished_at Nullable(DateTime64(6, 'UTC')),
  duration_ms Nullable(UInt32),
  error_kind LowCardinality(String),
  error_message String,
  event_uuid String,
  distinct_id String,
  person_id String,
  invocation_globals String,
  version UInt64,
  is_deleted UInt8 DEFAULT 0,
  _timestamp DateTime,
  _offset UInt64,
  _partition UInt64,
  INDEX status_idx status TYPE set(8) GRANULARITY 1,
  INDEX function_idx function_id TYPE bloom_filter(0.01) GRANULARITY 1,
  INDEX event_uuid_idx event_uuid TYPE bloom_filter(0.01) GRANULARITY 1,
  INDEX is_retry_idx is_retry TYPE set(2) GRANULARITY 1
) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/noshard/posthog.hog_invocation_results_data', '{replica}-{shard}', version) ORDER BY (team_id, function_kind, function_id, invocation_id) PARTITION BY toYYYYMMDD(scheduled_at) TTL toDate(scheduled_at) + toIntervalDay(30) SETTINGS index_granularity = 1024, storage_policy = 's3_tiered', ttl_only_drop_parts = 1;
CREATE TABLE posthog.ingestion_warnings_v2 (
  team_id Int64,
  source LowCardinality(String),
  type LowCardinality(String),
  details String,
  timestamp DateTime64(6, 'UTC'),
  category LowCardinality(String) DEFAULT coalesce(nullIf(JSONExtractString(details, 'category'), ''), 'unknown'),
  severity LowCardinality(String) DEFAULT coalesce(nullIf(JSONExtractString(details, 'severity'), ''), 'warning'),
  pipeline_step LowCardinality(String) DEFAULT coalesce(nullIf(JSONExtractString(details, 'pipelineStep'), ''), 'unknown'),
  event_uuid Nullable(UUID) DEFAULT toUUIDOrNull(JSONExtractString(details, 'eventUuid')),
  distinct_id Nullable(String) DEFAULT nullIf(JSONExtractString(details, 'distinctId'), ''),
  group_key Nullable(String) DEFAULT nullIf(JSONExtractString(details, 'groupKey'), ''),
  person_id Nullable(UUID) DEFAULT toUUIDOrNull(JSONExtractString(details, 'personId')),
  _timestamp DateTime,
  _offset UInt64,
  _partition UInt64
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/noshard/posthog.ingestion_warnings_v2', '{replica}-{shard}') ORDER BY (team_id, type, timestamp) PARTITION BY toYYYYMM(timestamp) TTL toDateTime(timestamp) + toIntervalDay(90) SETTINGS index_granularity = 8192;
CREATE TABLE posthog.ingestion_warnings_v2_distributed (
  team_id Int64,
  source LowCardinality(String),
  type LowCardinality(String),
  details String,
  timestamp DateTime64(6, 'UTC'),
  category LowCardinality(String) DEFAULT coalesce(nullIf(JSONExtractString(details, 'category'), ''), 'unknown'),
  severity LowCardinality(String) DEFAULT coalesce(nullIf(JSONExtractString(details, 'severity'), ''), 'warning'),
  pipeline_step LowCardinality(String) DEFAULT coalesce(nullIf(JSONExtractString(details, 'pipelineStep'), ''), 'unknown'),
  event_uuid Nullable(UUID) DEFAULT toUUIDOrNull(JSONExtractString(details, 'eventUuid')),
  distinct_id Nullable(String) DEFAULT nullIf(JSONExtractString(details, 'distinctId'), ''),
  group_key Nullable(String) DEFAULT nullIf(JSONExtractString(details, 'groupKey'), ''),
  person_id Nullable(UUID) DEFAULT toUUIDOrNull(JSONExtractString(details, 'personId')),
  _timestamp DateTime,
  _offset UInt64,
  _partition UInt64
) ENGINE = Distributed('aux', 'posthog', 'ingestion_warnings_v2');
CREATE TABLE posthog.kafka_hog_invocation_results (
  team_id Int64,
  function_kind LowCardinality(String),
  function_id String,
  invocation_id String,
  parent_run_id String,
  status LowCardinality(String),
  attempts UInt8,
  is_retry UInt8,
  scheduled_at DateTime64(6, 'UTC'),
  first_scheduled_at DateTime64(6, 'UTC'),
  started_at Nullable(DateTime64(6, 'UTC')),
  finished_at Nullable(DateTime64(6, 'UTC')),
  duration_ms Nullable(UInt32),
  error_kind LowCardinality(String),
  error_message String,
  event_uuid String,
  distinct_id String,
  person_id String,
  invocation_globals String,
  version UInt64,
  is_deleted UInt8
) ENGINE = Kafka() SETTINGS kafka_broker_list = 'warpstream_cyclotron', kafka_format = 'kafka_format = \'JSONEachRow\'', kafka_group_name = 'kafka_group_name = \'clickhouse_hog_invocation_results\'', kafka_max_block_size = 100000, kafka_num_consumers = 1, kafka_poll_timeout_ms = 10000, kafka_skip_broken_messages = 100, kafka_thread_per_consumer = 1, kafka_topic_list = 'kafka_topic_list = \'clickhouse_hog_invocation_results\'';
CREATE TABLE posthog.kafka_ingestion_warnings_v2 (
  team_id Int64,
  source LowCardinality(String),
  type String,
  details String,
  timestamp DateTime64(6, 'UTC')
) ENGINE = Kafka() SETTINGS kafka_broker_list = 'warpstream_ingestion', kafka_format = 'kafka_format = \'JSONEachRow\'', kafka_group_name = 'kafka_group_name = \'clickhouse_ingestion_warnings_v2\'', kafka_topic_list = 'kafka_topic_list = \'clickhouse_ingestion_warnings\'';
CREATE TABLE posthog.kafka_message_assets (
  team_id Int64,
  function_kind LowCardinality(String),
  function_id String,
  parent_run_id String,
  invocation_id String,
  action_id String,
  kind LowCardinality(String),
  distinct_id String,
  person_id String,
  recipient String,
  subject String,
  status LowCardinality(String),
  sent_at DateTime64(6, 'UTC'),
  version UInt64,
  is_deleted UInt8,
  html String
) ENGINE = Kafka() SETTINGS kafka_broker_list = 'warpstream_cyclotron', kafka_format = 'kafka_format = \'JSONEachRow\'', kafka_group_name = 'kafka_group_name = \'clickhouse_message_assets\'', kafka_skip_broken_messages = 100, kafka_topic_list = 'kafka_topic_list = \'clickhouse_message_assets\'';
CREATE TABLE posthog.kafka_property_values (
  team_id Int64,
  property_type LowCardinality(String),
  property_key String,
  property_value String,
  property_count UInt64
) ENGINE = Kafka() SETTINGS kafka_broker_list = 'warpstream_ingestion', kafka_format = 'kafka_format = \'JSONEachRow\'', kafka_group_name = 'kafka_group_name = \'clickhouse_property_values\'', kafka_num_consumers = 8, kafka_thread_per_consumer = 1, kafka_topic_list = 'kafka_topic_list = \'clickhouse_property_values\'';
CREATE TABLE posthog.message_assets_data (
  team_id Int64,
  function_kind LowCardinality(String),
  function_id String,
  parent_run_id String,
  invocation_id String,
  action_id String,
  kind LowCardinality(String),
  distinct_id String,
  person_id String,
  recipient String,
  subject String,
  status LowCardinality(String),
  sent_at DateTime64(6, 'UTC'),
  version UInt64,
  is_deleted UInt8 DEFAULT 0,
  html String CODEC(ZSTD(3)),
  _timestamp DateTime,
  _offset UInt64,
  _partition UInt64,
  INDEX parent_run_idx parent_run_id TYPE bloom_filter(0.01) GRANULARITY 1,
  INDEX distinct_id_idx distinct_id TYPE bloom_filter(0.01) GRANULARITY 1,
  INDEX person_id_idx person_id TYPE bloom_filter(0.01) GRANULARITY 1,
  INDEX recipient_idx recipient TYPE bloom_filter(0.01) GRANULARITY 1
) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/noshard/posthog.message_assets_data', '{replica}-{shard}', version) ORDER BY (team_id, function_kind, function_id, invocation_id, action_id) PARTITION BY toYYYYMMDD(sent_at) TTL toDate(sent_at) + toIntervalDay(30) SETTINGS index_granularity = 1024, ttl_only_drop_parts = 1;
CREATE TABLE posthog.property_values (
  team_id Int64 CODEC(DoubleDelta, ZSTD(1)),
  property_type LowCardinality(String),
  property_key LowCardinality(String),
  property_value String,
  property_count SimpleAggregateFunction(sum, UInt64),
  last_seen SimpleAggregateFunction(max, DateTime) DEFAULT now(),
  INDEX idx_property_value_ngrambf lower(property_value) TYPE ngrambf_v1(3, 32768, 3, 0) GRANULARITY 1
) ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/noshard/posthog.property_values', '{replica}-{shard}') ORDER BY (team_id, property_type, property_key, property_value) TTL last_seen + toIntervalDay(30) SETTINGS index_granularity = 8192;
CREATE TABLE posthog.property_values_distributed (
  team_id Int64 CODEC(DoubleDelta, ZSTD(1)),
  property_type LowCardinality(String),
  property_key LowCardinality(String),
  property_value String,
  property_count SimpleAggregateFunction(sum, UInt64),
  last_seen SimpleAggregateFunction(max, DateTime) DEFAULT now()
) ENGINE = Distributed('aux', 'posthog', 'property_values');
CREATE TABLE posthog.query_log_archive (
  hostname LowCardinality(String),
  user LowCardinality(String),
  query_id String,
  initial_query_id String,
  is_initial_query UInt8,
  type Enum8('QueryStart'=1, 'QueryFinish'=2, 'ExceptionBeforeStart'=3, 'ExceptionWhileProcessing'=4),
  event_date Date,
  event_time DateTime,
  event_time_microseconds DateTime64(6),
  query_start_time DateTime,
  query_start_time_microseconds DateTime64(6),
  query_duration_ms UInt64,
  read_rows UInt64,
  read_bytes UInt64,
  written_rows UInt64,
  written_bytes UInt64,
  result_rows UInt64,
  result_bytes UInt64,
  memory_usage UInt64,
  peak_threads_usage UInt64,
  current_database LowCardinality(String),
  query String,
  formatted_query String,
  normalized_query_hash UInt64,
  query_kind LowCardinality(String),
  exception_code Int32,
  exception String,
  stack_trace String,
  team_id Int64,
  log_comment JSON(max_dynamic_paths=256, access_method LowCardinality(String), alert_config_id String, api_key_label String, api_key_mask String, batch_export_id String, chargeable Bool, client_query_id String, cohort_id Int64, `dagster.job_name` String, `dagster.run_id` String, `dagster.tags.owner` String, dashboard_id Int64, experiment_feature_flag_key String, experiment_id Int64, feature LowCardinality(String), id String, insight_id Int64, is_impersonated Bool, kind LowCardinality(String), name String, org_id String, person_on_events_mode LowCardinality(String), product LowCardinality(String), query_type LowCardinality(String), request_name String, route_id String, service_name String, session_id String, table_id String, team_id Int64, `temporal.activity_id` String, `temporal.activity_type` String, `temporal.attempt` Int64, `temporal.workflow_id` String, `temporal.workflow_namespace` String, `temporal.workflow_run_id` String, `temporal.workflow_type` String, user_id Int64, warehouse_query Bool, workflow LowCardinality(String), workload LowCardinality(String), SKIP cache_key, SKIP filter, SKIP hogql_features, SKIP http_referer, SKIP http_request_id, SKIP http_user_agent, SKIP query_settings, SKIP timings, SKIP user_email),
  ProfileEvents Map(String, UInt64),
  exception_name String ALIAS errorCodeToName(exception_code),
  ProfileEvents_RealTimeMicroseconds Int64 ALIAS ProfileEvents['RealTimeMicroseconds'],
  ProfileEvents_OSCPUVirtualTimeMicroseconds Int64 ALIAS ProfileEvents['OSCPUVirtualTimeMicroseconds'],
  ProfileEvents_S3Clients Int64 ALIAS ProfileEvents['S3Clients'],
  ProfileEvents_S3DeleteObjects Int64 ALIAS ProfileEvents['S3DeleteObjects'],
  ProfileEvents_S3CopyObject Int64 ALIAS ProfileEvents['S3CopyObject'],
  ProfileEvents_S3ListObjects Int64 ALIAS ProfileEvents['S3ListObjects'],
  ProfileEvents_S3HeadObject Int64 ALIAS ProfileEvents['S3HeadObject'],
  ProfileEvents_S3GetObjectAttributes Int64 ALIAS ProfileEvents['S3GetObjectAttributes'],
  ProfileEvents_S3CreateMultipartUpload Int64 ALIAS ProfileEvents['S3CreateMultipartUpload'],
  ProfileEvents_S3UploadPartCopy Int64 ALIAS ProfileEvents['S3UploadPartCopy'],
  ProfileEvents_S3UploadPart Int64 ALIAS ProfileEvents['S3UploadPart'],
  ProfileEvents_S3AbortMultipartUpload Int64 ALIAS ProfileEvents['S3AbortMultipartUpload'],
  ProfileEvents_S3CompleteMultipartUpload Int64 ALIAS ProfileEvents['S3CompleteMultipartUpload'],
  ProfileEvents_S3PutObject Int64 ALIAS ProfileEvents['S3PutObject'],
  ProfileEvents_S3GetObject Int64 ALIAS ProfileEvents['S3GetObject'],
  ProfileEvents_ReadBufferFromS3Bytes Int64 ALIAS ProfileEvents['ReadBufferFromS3Bytes'],
  ProfileEvents_WriteBufferFromS3Bytes Int64 ALIAS ProfileEvents['WriteBufferFromS3Bytes'],
  lc_workflow LowCardinality(String) ALIAS log_comment.workflow,
  lc_kind LowCardinality(String) ALIAS log_comment.kind,
  lc_id String ALIAS CAST(log_comment.id, 'String'),
  lc_route_id String ALIAS CAST(log_comment.route_id, 'String'),
  lc_access_method LowCardinality(String) ALIAS log_comment.access_method,
  lc_api_key_label String ALIAS CAST(log_comment.api_key_label, 'String'),
  lc_api_key_mask String ALIAS CAST(log_comment.api_key_mask, 'String'),
  lc_query_type LowCardinality(String) ALIAS log_comment.query_type,
  lc_product LowCardinality(String) ALIAS log_comment.product,
  lc_chargeable Bool ALIAS log_comment.chargeable,
  lc_name String ALIAS CAST(log_comment.name, 'String'),
  lc_request_name String ALIAS CAST(log_comment.request_name, 'String'),
  lc_client_query_id String ALIAS CAST(log_comment.client_query_id, 'String'),
  lc_org_id String ALIAS CAST(log_comment.org_id, 'String'),
  lc_user_id Int64 ALIAS log_comment.user_id,
  lc_is_impersonated Bool ALIAS log_comment.is_impersonated,
  lc_session_id String ALIAS CAST(log_comment.session_id, 'String'),
  lc_dashboard_id Int64 ALIAS log_comment.dashboard_id,
  lc_insight_id Int64 ALIAS log_comment.insight_id,
  lc_cohort_id Int64 ALIAS log_comment.cohort_id,
  lc_batch_export_id String ALIAS CAST(log_comment.batch_export_id, 'String'),
  lc_experiment_id Int64 ALIAS log_comment.experiment_id,
  lc_experiment_feature_flag_key String ALIAS CAST(log_comment.experiment_feature_flag_key, 'String'),
  lc_alert_config_id String ALIAS CAST(log_comment.alert_config_id, 'String'),
  lc_feature LowCardinality(String) ALIAS log_comment.feature,
  lc_table_id String ALIAS CAST(log_comment.table_id, 'String'),
  lc_warehouse_query Bool ALIAS log_comment.warehouse_query,
  lc_person_on_events_mode LowCardinality(String) ALIAS log_comment.person_on_events_mode,
  lc_service_name String ALIAS CAST(log_comment.service_name, 'String'),
  lc_workload LowCardinality(String) ALIAS log_comment.workload,
  lc_query__kind LowCardinality(String) ALIAS if(JSONHas(toString(log_comment), 'query', 'source'), JSONExtractString(toString(log_comment), 'query', 'source', 'kind'), JSONExtractString(toString(log_comment), 'query', 'kind')),
  lc_query__query String ALIAS multiIf(NOT is_initial_query, '', JSONHas(toString(log_comment), 'query', 'source'), JSONExtractString(toString(log_comment), 'query', 'source', 'query'), JSONExtractString(toString(log_comment), 'query', 'query')),
  lc_query String ALIAS if(is_initial_query, JSONExtractRaw(toString(log_comment), 'query'), ''),
  lc_temporal__workflow_namespace String ALIAS CAST(log_comment.`temporal.workflow_namespace`, 'String'),
  lc_temporal__workflow_type String ALIAS CAST(log_comment.`temporal.workflow_type`, 'String'),
  lc_temporal__workflow_id String ALIAS CAST(log_comment.`temporal.workflow_id`, 'String'),
  lc_temporal__workflow_run_id String ALIAS CAST(log_comment.`temporal.workflow_run_id`, 'String'),
  lc_temporal__activity_type String ALIAS CAST(log_comment.`temporal.activity_type`, 'String'),
  lc_temporal__activity_id String ALIAS CAST(log_comment.`temporal.activity_id`, 'String'),
  lc_temporal__attempt Int64 ALIAS log_comment.`temporal.attempt`,
  lc_dagster__job_name String ALIAS CAST(log_comment.`dagster.job_name`, 'String'),
  lc_dagster__run_id String ALIAS CAST(log_comment.`dagster.run_id`, 'String'),
  lc_dagster__owner String ALIAS CAST(log_comment.`dagster.tags.owner`, 'String'),
  lc_modifiers String ALIAS if(is_initial_query, JSONExtractRaw(toString(log_comment), 'modifiers'), '')
) ENGINE = Distributed('ops', 'posthog', 'sharded_query_log_archive');
CREATE TABLE posthog.raw_error_tracking_fingerprint_issue_state (
  team_id Int64,
  fingerprint String,
  issue_id UUID,
  issue_name Nullable(String),
  issue_description Nullable(String),
  issue_status String,
  assigned_user_id Nullable(Int64),
  assigned_role_id Nullable(UUID),
  first_seen DateTime64(3, 'UTC'),
  is_deleted Int8,
  version Int64,
  _timestamp DateTime,
  _offset UInt64,
  _partition UInt64,
  INDEX kafka_timestamp_minmax_raw_error_tracking_fingerprint_issue_state _timestamp TYPE minmax GRANULARITY 3
) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/noshard/posthog.raw_error_tracking_fingerprint_issue_state', '{replica}-{shard}', version) ORDER BY (team_id, fingerprint) SETTINGS index_granularity = 512;
CREATE TABLE posthog.sharded_conversion_goal_attributed_preaggregated (
  team_id Int64,
  job_id UUID,
  person_id UUID,
  conversion_timestamp DateTime64(6, 'UTC'),
  conversion_value Float64,
  touchpoint_timestamp DateTime64(6, 'UTC'),
  touchpoint_weight Float64,
  campaign_name String,
  source_name String,
  medium_name String,
  content_name String,
  term_name String,
  referring_domain_name String,
  gclid_name String,
  fbclid_name String,
  gad_source_name String,
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at Date DEFAULT today() + toIntervalDay(7)
) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/noshard/posthog.conversion_goal_attributed_preaggregated', '{replica}-{shard}', computed_at) ORDER BY (team_id, job_id, person_id, conversion_timestamp, touchpoint_timestamp) PARTITION BY toYYYYMMDD(expires_at) TTL expires_at SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1;
CREATE TABLE posthog.sharded_experiment_metric_events_preaggregated (
  team_id Int64,
  job_id UUID,
  entity_id String,
  timestamp DateTime64(6, 'UTC'),
  event_uuid UUID,
  session_id String,
  numeric_value Float64 DEFAULT 0,
  steps Array(UInt8) DEFAULT [],
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at Date DEFAULT today() + toIntervalDay(7)
) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/noshard/posthog.experiment_metric_events_preaggregated', '{replica}-{shard}', computed_at) ORDER BY (team_id, job_id, entity_id, timestamp, event_uuid) PARTITION BY toYYYYMMDD(expires_at) TTL expires_at SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1;
CREATE TABLE posthog.sharded_ingestion_warnings (
  team_id Int64,
  source LowCardinality(String),
  type String,
  details String,
  timestamp DateTime64(6, 'UTC'),
  _timestamp DateTime,
  _offset UInt64,
  _partition UInt64
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/reshard/{shard}/posthog.sharded_ingestion_warnings', '{replica}') ORDER BY (team_id, toHour(timestamp), type, source, timestamp) PARTITION BY toYear(timestamp) SETTINGS index_granularity = 8192;
CREATE TABLE posthog.sharded_marketing_conversions_preaggregated (
  team_id Int64,
  job_id UUID,
  person_id UUID,
  conversion_timestamp DateTime64(6, 'UTC'),
  conversion_math_value Float64,
  session_id String,
  campaign_name String,
  source_name String,
  medium_name String,
  content_name String,
  term_name String,
  referring_domain_name String,
  gclid_name String,
  fbclid_name String,
  gad_source_name String,
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at Date DEFAULT today() + toIntervalDay(7)
) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/noshard/posthog.marketing_conversions_preaggregated', '{replica}-{shard}', computed_at) ORDER BY (team_id, job_id, person_id, conversion_timestamp) PARTITION BY toYYYYMMDD(expires_at) TTL expires_at SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1;
CREATE TABLE posthog.sharded_marketing_costs_preaggregated (
  team_id Int64,
  job_id UUID,
  source_id String,
  source_name String,
  grain LowCardinality(String),
  match_key String,
  campaign_id String,
  campaign_name String,
  ad_group_id String,
  ad_group_name String,
  ad_id String,
  ad_name String,
  cost_date Date,
  cost Float64,
  clicks Float64,
  impressions Float64,
  reported_conversions Float64,
  reported_conversion_value Float64,
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at Date DEFAULT today() + toIntervalDay(7)
) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/noshard/posthog.marketing_costs_preaggregated', '{replica}-{shard}', computed_at) ORDER BY (team_id, job_id, source_name, grain, campaign_id, ad_group_id, ad_id, cost_date) PARTITION BY toYYYYMMDD(expires_at) TTL expires_at SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1;
CREATE TABLE posthog.sharded_marketing_touchpoints_preaggregated (
  team_id Int64,
  job_id UUID,
  person_id UUID,
  touchpoint_timestamp DateTime64(6, 'UTC'),
  campaign_name String,
  source_name String,
  medium_name String,
  content_name String,
  term_name String,
  referring_domain_name String,
  gclid_name String,
  fbclid_name String,
  gad_source_name String,
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at Date DEFAULT today() + toIntervalDay(7)
) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/noshard/posthog.marketing_touchpoints_preaggregated', '{replica}-{shard}', computed_at) ORDER BY (team_id, job_id, person_id, touchpoint_timestamp) PARTITION BY toYYYYMMDD(expires_at) TTL expires_at SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1;
CREATE TABLE posthog.sharded_session_replay_features (
  session_id String,
  team_id Int64,
  distinct_id String,
  min_first_timestamp SimpleAggregateFunction(min, DateTime64(6, 'UTC')),
  max_last_timestamp SimpleAggregateFunction(max, DateTime64(6, 'UTC')),
  event_count SimpleAggregateFunction(sum, Int64),
  mouse_position_count SimpleAggregateFunction(sum, Int64),
  mouse_sum_x SimpleAggregateFunction(sum, Float64),
  mouse_sum_x_squared SimpleAggregateFunction(sum, Float64),
  mouse_sum_y SimpleAggregateFunction(sum, Float64),
  mouse_sum_y_squared SimpleAggregateFunction(sum, Float64),
  mouse_distance_traveled SimpleAggregateFunction(sum, Float64),
  mouse_direction_change_count SimpleAggregateFunction(sum, Int64),
  mouse_velocity_sum SimpleAggregateFunction(sum, Float64),
  mouse_velocity_sum_of_squares SimpleAggregateFunction(sum, Float64),
  mouse_velocity_count SimpleAggregateFunction(sum, Int64),
  scroll_event_count SimpleAggregateFunction(sum, Int64),
  total_scroll_magnitude SimpleAggregateFunction(sum, Float64),
  scroll_direction_reversal_count SimpleAggregateFunction(sum, Int64),
  rapid_scroll_reversal_count SimpleAggregateFunction(sum, Int64),
  scroll_to_top_count SimpleAggregateFunction(sum, Int64),
  click_count SimpleAggregateFunction(sum, Int64),
  keypress_count SimpleAggregateFunction(sum, Int64),
  mouse_activity_count SimpleAggregateFunction(sum, Int64),
  rage_click_count SimpleAggregateFunction(sum, Int64),
  dead_click_count SimpleAggregateFunction(sum, Int64),
  backspace_count SimpleAggregateFunction(sum, Int64),
  inter_action_gap_count SimpleAggregateFunction(sum, Int64),
  inter_action_gap_sum_ms SimpleAggregateFunction(sum, Float64),
  inter_action_gap_sum_of_squares_ms SimpleAggregateFunction(sum, Float64),
  max_idle_gap_ms SimpleAggregateFunction(max, Float64),
  long_idle_gap_count SimpleAggregateFunction(sum, Int64),
  quick_back_count SimpleAggregateFunction(sum, Int64),
  page_visit_count SimpleAggregateFunction(sum, Int64),
  unique_url_count AggregateFunction(uniqCombined(12), String),
  login_path_visit_count SimpleAggregateFunction(sum, Int64),
  signup_path_visit_count SimpleAggregateFunction(sum, Int64),
  checkout_path_visit_count SimpleAggregateFunction(sum, Int64),
  cart_path_visit_count SimpleAggregateFunction(sum, Int64),
  billing_path_visit_count SimpleAggregateFunction(sum, Int64),
  settings_path_visit_count SimpleAggregateFunction(sum, Int64),
  account_path_visit_count SimpleAggregateFunction(sum, Int64),
  error_path_visit_count SimpleAggregateFunction(sum, Int64),
  not_found_path_visit_count SimpleAggregateFunction(sum, Int64),
  admin_path_visit_count SimpleAggregateFunction(sum, Int64),
  dashboard_path_visit_count SimpleAggregateFunction(sum, Int64),
  onboarding_path_visit_count SimpleAggregateFunction(sum, Int64),
  cancel_path_visit_count SimpleAggregateFunction(sum, Int64),
  refund_path_visit_count SimpleAggregateFunction(sum, Int64),
  console_error_count SimpleAggregateFunction(sum, Int64),
  console_error_after_click_count SimpleAggregateFunction(sum, Int64),
  console_warn_count SimpleAggregateFunction(sum, Int64),
  network_request_count SimpleAggregateFunction(sum, Int64),
  network_failed_request_count SimpleAggregateFunction(sum, Int64),
  network_4xx_count SimpleAggregateFunction(sum, Int64),
  network_5xx_count SimpleAggregateFunction(sum, Int64),
  network_request_duration_sum SimpleAggregateFunction(sum, Float64),
  network_request_duration_sum_of_squares SimpleAggregateFunction(sum, Float64),
  network_request_duration_count SimpleAggregateFunction(sum, Int64),
  mutation_count SimpleAggregateFunction(sum, Int64),
  viewport_resize_count SimpleAggregateFunction(sum, Int64),
  touch_event_count SimpleAggregateFunction(sum, Int64),
  max_scroll_y SimpleAggregateFunction(max, Float64),
  unique_click_target_count AggregateFunction(uniqCombined(12), Int64),
  unique_form_field_count AggregateFunction(uniqCombined(12), Int64),
  text_selection_count SimpleAggregateFunction(sum, Int64),
  selection_copy_count SimpleAggregateFunction(sum, Int64),
  is_deleted SimpleAggregateFunction(max, UInt8) DEFAULT 0
) ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/{shard}/posthog.session_replay_features', '{replica}') ORDER BY (team_id, session_id) PARTITION BY toYYYYMM(min_first_timestamp) SETTINGS index_granularity = 512;
CREATE TABLE posthog.sharded_usage_report_events_preagg (
  date Date,
  team_id Int64,
  person_mode LowCardinality(String),
  lib LowCardinality(String),
  event String,
  distinct_events_unique AggregateFunction(uniqExact, Tuple(UInt64, UInt64, UInt64)),
  event_count AggregateFunction(sum, UInt64)
) ENGINE = ReplicatedAggregatingMergeTree('/clickhouse/tables/{shard}/posthog.sharded_usage_report_events_preagg', '{replica}') ORDER BY (date, team_id, person_mode, lib, event) PARTITION BY date TTL date + toIntervalDay(14) SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1;
CREATE TABLE posthog.sharded_web_bot_definition (
  id UInt64,
  parent_id UInt64,
  regexp String,
  keys Array(String),
  values Array(String)
) ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/posthog.sharded_web_bot_definition', '{replica}') ORDER BY (id) SETTINGS index_granularity = 8192;
CREATE TABLE posthog.sharded_web_bounces_dimensional_preaggregated (
  team_id Int64,
  job_id UUID,
  period_bucket DateTime,
  host String,
  device_type String,
  entry_pathname String,
  end_pathname String,
  browser String,
  os String,
  viewport_width Int64,
  viewport_height Int64,
  referring_domain String,
  utm_source String,
  utm_medium String,
  utm_campaign String,
  utm_term String,
  utm_content String,
  country_code String,
  city_name String,
  region_code String,
  region_name String,
  has_gclid Bool,
  has_gad_source_paid_search Bool,
  has_fbclid Bool,
  mat_metadata_backend Nullable(String),
  mat_metadata_loggedIn Nullable(Bool),
  persons_uniq_state AggregateFunction(uniq, UUID),
  sessions_uniq_state AggregateFunction(uniq, String),
  pageviews_count_state AggregateFunction(sum, Int64),
  bounces_count_state AggregateFunction(sum, Int64),
  total_session_duration_state AggregateFunction(sum, Int64),
  total_session_count_state AggregateFunction(sum, Int64),
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at DateTime64(6, 'UTC') DEFAULT now() + toIntervalDay(7)
) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/posthog.web_bounces_dimensional_preaggregated', '{replica}', computed_at) ORDER BY (team_id, job_id, period_bucket, host, device_type, entry_pathname, end_pathname, browser, os, viewport_width, viewport_height, referring_domain, utm_source, utm_medium, utm_campaign, utm_term, utm_content, country_code, city_name, region_code, region_name, has_gclid, has_gad_source_paid_search, has_fbclid, mat_metadata_backend, mat_metadata_loggedIn) PARTITION BY toYYYYMMDD(expires_at) TTL toDateTime(expires_at) SETTINGS allow_nullable_key = 1, index_granularity = 8192, ttl_only_drop_parts = 1;
CREATE TABLE posthog.sharded_web_goals_preaggregated (
  team_id Int64,
  job_id UUID,
  time_window_start DateTime64(6, 'UTC'),
  action_id Int64,
  count_state AggregateFunction(sum, Int64),
  unique_persons_state AggregateFunction(uniq, UUID),
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at DateTime64(6, 'UTC') DEFAULT now() + toIntervalDay(7)
) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/posthog.web_goals_preaggregated', '{replica}', computed_at) ORDER BY (team_id, job_id, action_id, time_window_start) PARTITION BY toYYYYMMDD(expires_at) TTL toDateTime(expires_at) SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1;
CREATE TABLE posthog.sharded_web_overview_preaggregated (
  team_id Int64,
  job_id UUID,
  time_window_start DateTime64(6, 'UTC'),
  uniq_users_state AggregateFunction(uniq, UUID),
  uniq_sessions_state AggregateFunction(uniq, String),
  sum_pageviews_state AggregateFunction(sum, Int64),
  avg_duration_state AggregateFunction(avg, Float64),
  avg_bounce_state AggregateFunction(avg, Int64),
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at DateTime64(6, 'UTC') DEFAULT now() + toIntervalDay(7)
) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/posthog.web_overview_preaggregated', '{replica}', computed_at) ORDER BY (team_id, job_id, time_window_start) PARTITION BY toYYYYMMDD(expires_at) TTL toDateTime(expires_at) SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1;
CREATE TABLE posthog.sharded_web_stats_dimensional_preaggregated (
  team_id Int64,
  job_id UUID,
  period_bucket DateTime,
  host String,
  device_type String,
  pathname String,
  entry_pathname String,
  end_pathname String,
  browser String,
  os String,
  viewport_width Int64,
  viewport_height Int64,
  referring_domain String,
  utm_source String,
  utm_medium String,
  utm_campaign String,
  utm_term String,
  utm_content String,
  country_code String,
  city_name String,
  region_code String,
  region_name String,
  has_gclid Bool,
  has_gad_source_paid_search Bool,
  has_fbclid Bool,
  mat_metadata_backend Nullable(String),
  mat_metadata_loggedIn Nullable(Bool),
  persons_uniq_state AggregateFunction(uniq, UUID),
  sessions_uniq_state AggregateFunction(uniq, String),
  pageviews_count_state AggregateFunction(sum, Int64),
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at DateTime64(6, 'UTC') DEFAULT now() + toIntervalDay(7)
) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/posthog.web_stats_dimensional_preaggregated', '{replica}', computed_at) ORDER BY (team_id, job_id, period_bucket, host, device_type, pathname, entry_pathname, end_pathname, browser, os, viewport_width, viewport_height, referring_domain, utm_source, utm_medium, utm_campaign, utm_term, utm_content, country_code, city_name, region_code, region_name, has_gclid, has_gad_source_paid_search, has_fbclid, mat_metadata_backend, mat_metadata_loggedIn) PARTITION BY toYYYYMMDD(expires_at) TTL toDateTime(expires_at) SETTINGS allow_nullable_key = 1, index_granularity = 8192, ttl_only_drop_parts = 1;
CREATE TABLE posthog.sharded_web_stats_frustration_preaggregated (
  team_id Int64,
  job_id UUID,
  time_window_start DateTime64(6, 'UTC'),
  breakdown_value String,
  sum_rage_clicks_state AggregateFunction(sum, Int64),
  sum_dead_clicks_state AggregateFunction(sum, Int64),
  sum_errors_state AggregateFunction(sum, Int64),
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at DateTime64(6, 'UTC') DEFAULT now() + toIntervalDay(7)
) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/posthog.web_stats_frustration_preaggregated', '{replica}', computed_at) ORDER BY (team_id, job_id, breakdown_value, time_window_start) PARTITION BY toYYYYMMDD(expires_at) TTL toDateTime(expires_at) SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1;
CREATE TABLE posthog.sharded_web_stats_paths_preaggregated (
  team_id Int64,
  job_id UUID,
  time_window_start DateTime64(6, 'UTC'),
  breakdown_value String,
  uniq_users_state AggregateFunction(uniq, UUID),
  sum_pageviews_state AggregateFunction(sum, Int64),
  avg_bounce_state AggregateFunction(avg, Nullable(Float64)),
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at DateTime64(6, 'UTC') DEFAULT now() + toIntervalDay(7)
) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/posthog.web_stats_paths_preaggregated', '{replica}', computed_at) ORDER BY (team_id, job_id, breakdown_value, time_window_start) PARTITION BY toYYYYMMDD(expires_at) TTL toDateTime(expires_at) SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1;
CREATE TABLE posthog.sharded_web_stats_paths_preaggregated_pathkey (
  team_id Int64,
  job_id UUID,
  time_window_start DateTime64(6, 'UTC'),
  breakdown_value String,
  uniq_users_state AggregateFunction(uniq, UUID),
  sum_pageviews_state AggregateFunction(sum, Int64),
  avg_bounce_state AggregateFunction(avg, Nullable(Float64)),
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at DateTime64(6, 'UTC') DEFAULT now() + toIntervalDay(7)
) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/posthog.web_stats_paths_preaggregated_pathkey', '{replica}', computed_at) ORDER BY (team_id, time_window_start, breakdown_value, job_id) PARTITION BY toYYYYMMDD(expires_at) TTL toDateTime(expires_at) SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1;
CREATE TABLE posthog.sharded_web_stats_preaggregated (
  team_id Int64,
  job_id UUID,
  time_window_start DateTime64(6, 'UTC'),
  breakdown_by String,
  breakdown_value String,
  uniq_users_state AggregateFunction(uniq, UUID),
  sum_pageviews_state AggregateFunction(sum, Int64),
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at DateTime64(6, 'UTC') DEFAULT now() + toIntervalDay(7)
) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/posthog.web_stats_preaggregated', '{replica}', computed_at) ORDER BY (team_id, job_id, breakdown_by, time_window_start, breakdown_value) PARTITION BY toYYYYMMDD(expires_at) TTL toDateTime(expires_at) SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1;
CREATE TABLE posthog.sharded_web_vitals_paths_preaggregated (
  team_id Int64,
  job_id UUID,
  time_window_start DateTime64(6, 'UTC'),
  path String,
  inp_quantiles_state AggregateFunction(quantiles(0.75, 0.9, 0.99), Float64),
  lcp_quantiles_state AggregateFunction(quantiles(0.75, 0.9, 0.99), Float64),
  cls_quantiles_state AggregateFunction(quantiles(0.75, 0.9, 0.99), Float64),
  fcp_quantiles_state AggregateFunction(quantiles(0.75, 0.9, 0.99), Float64),
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at DateTime64(6, 'UTC') DEFAULT now() + toIntervalDay(7)
) ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{shard}/posthog.web_vitals_paths_preaggregated', '{replica}', computed_at) ORDER BY (team_id, job_id, time_window_start, path) PARTITION BY toYYYYMMDD(expires_at) TTL toDateTime(expires_at) SETTINGS index_granularity = 8192, ttl_only_drop_parts = 1;
CREATE TABLE posthog.web_bot_definition (
  id UInt64,
  parent_id UInt64,
  regexp String,
  keys Array(String),
  values Array(String)
) ENGINE = Distributed('aux', 'posthog', 'sharded_web_bot_definition', sipHash64(id));
CREATE TABLE posthog.web_bounces_dimensional_preaggregated (
  team_id Int64,
  job_id UUID,
  period_bucket DateTime,
  host String,
  device_type String,
  entry_pathname String,
  end_pathname String,
  browser String,
  os String,
  viewport_width Int64,
  viewport_height Int64,
  referring_domain String,
  utm_source String,
  utm_medium String,
  utm_campaign String,
  utm_term String,
  utm_content String,
  country_code String,
  city_name String,
  region_code String,
  region_name String,
  has_gclid Bool,
  has_gad_source_paid_search Bool,
  has_fbclid Bool,
  mat_metadata_backend Nullable(String),
  mat_metadata_loggedIn Nullable(Bool),
  persons_uniq_state AggregateFunction(uniq, UUID),
  sessions_uniq_state AggregateFunction(uniq, String),
  pageviews_count_state AggregateFunction(sum, Int64),
  bounces_count_state AggregateFunction(sum, Int64),
  total_session_duration_state AggregateFunction(sum, Int64),
  total_session_count_state AggregateFunction(sum, Int64),
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at DateTime64(6, 'UTC') DEFAULT now() + toIntervalDay(7)
) ENGINE = Distributed('aux', 'posthog', 'sharded_web_bounces_dimensional_preaggregated', sipHash64(job_id));
CREATE TABLE posthog.web_goals_preaggregated (
  team_id Int64,
  job_id UUID,
  time_window_start DateTime64(6, 'UTC'),
  action_id Int64,
  count_state AggregateFunction(sum, Int64),
  unique_persons_state AggregateFunction(uniq, UUID),
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at DateTime64(6, 'UTC') DEFAULT now() + toIntervalDay(7)
) ENGINE = Distributed('aux', 'posthog', 'sharded_web_goals_preaggregated', sipHash64(job_id));
CREATE TABLE posthog.web_stats_dimensional_preaggregated (
  team_id Int64,
  job_id UUID,
  period_bucket DateTime,
  host String,
  device_type String,
  pathname String,
  entry_pathname String,
  end_pathname String,
  browser String,
  os String,
  viewport_width Int64,
  viewport_height Int64,
  referring_domain String,
  utm_source String,
  utm_medium String,
  utm_campaign String,
  utm_term String,
  utm_content String,
  country_code String,
  city_name String,
  region_code String,
  region_name String,
  has_gclid Bool,
  has_gad_source_paid_search Bool,
  has_fbclid Bool,
  mat_metadata_backend Nullable(String),
  mat_metadata_loggedIn Nullable(Bool),
  persons_uniq_state AggregateFunction(uniq, UUID),
  sessions_uniq_state AggregateFunction(uniq, String),
  pageviews_count_state AggregateFunction(sum, Int64),
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at DateTime64(6, 'UTC') DEFAULT now() + toIntervalDay(7)
) ENGINE = Distributed('aux', 'posthog', 'sharded_web_stats_dimensional_preaggregated', sipHash64(job_id));
CREATE TABLE posthog.web_stats_frustration_preaggregated (
  team_id Int64,
  job_id UUID,
  time_window_start DateTime64(6, 'UTC'),
  breakdown_value String,
  sum_rage_clicks_state AggregateFunction(sum, Int64),
  sum_dead_clicks_state AggregateFunction(sum, Int64),
  sum_errors_state AggregateFunction(sum, Int64),
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at DateTime64(6, 'UTC') DEFAULT now() + toIntervalDay(7)
) ENGINE = Distributed('aux', 'posthog', 'sharded_web_stats_frustration_preaggregated', sipHash64(job_id));
CREATE TABLE posthog.web_stats_preaggregated (
  team_id Int64,
  job_id UUID,
  time_window_start DateTime64(6, 'UTC'),
  breakdown_by String,
  breakdown_value String,
  uniq_users_state AggregateFunction(uniq, UUID),
  sum_pageviews_state AggregateFunction(sum, Int64),
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at DateTime64(6, 'UTC') DEFAULT now() + toIntervalDay(7)
) ENGINE = Distributed('aux', 'posthog', 'sharded_web_stats_preaggregated', sipHash64(job_id));
CREATE TABLE posthog.web_vitals_paths_preaggregated (
  team_id Int64,
  job_id UUID,
  time_window_start DateTime64(6, 'UTC'),
  path String,
  inp_quantiles_state AggregateFunction(quantiles(0.75, 0.9, 0.99), Float64),
  lcp_quantiles_state AggregateFunction(quantiles(0.75, 0.9, 0.99), Float64),
  cls_quantiles_state AggregateFunction(quantiles(0.75, 0.9, 0.99), Float64),
  fcp_quantiles_state AggregateFunction(quantiles(0.75, 0.9, 0.99), Float64),
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at DateTime64(6, 'UTC') DEFAULT now() + toIntervalDay(7)
) ENGINE = Distributed('aux', 'posthog', 'sharded_web_vitals_paths_preaggregated', sipHash64(job_id));
CREATE TABLE posthog.writable_error_tracking_fingerprint_issue_state (
  team_id Int64,
  fingerprint String,
  issue_id UUID,
  issue_name Nullable(String),
  issue_description Nullable(String),
  issue_status String,
  assigned_user_id Nullable(Int64),
  assigned_role_id Nullable(UUID),
  first_seen DateTime64(3, 'UTC'),
  is_deleted Int8,
  version Int64,
  _timestamp DateTime,
  _offset UInt64,
  _partition UInt64
) ENGINE = Distributed('aux', 'posthog', 'raw_error_tracking_fingerprint_issue_state');
CREATE TABLE posthog.writable_query_log_archive (
  hostname LowCardinality(String),
  user LowCardinality(String),
  query_id String,
  initial_query_id String,
  is_initial_query UInt8,
  type Enum8('QueryStart'=1, 'QueryFinish'=2, 'ExceptionBeforeStart'=3, 'ExceptionWhileProcessing'=4),
  event_date Date,
  event_time DateTime,
  event_time_microseconds DateTime64(6),
  query_start_time DateTime,
  query_start_time_microseconds DateTime64(6),
  query_duration_ms UInt64,
  read_rows UInt64,
  read_bytes UInt64,
  written_rows UInt64,
  written_bytes UInt64,
  result_rows UInt64,
  result_bytes UInt64,
  memory_usage UInt64,
  peak_threads_usage UInt64,
  current_database LowCardinality(String),
  query String,
  formatted_query String,
  normalized_query_hash UInt64,
  query_kind LowCardinality(String),
  exception_code Int32,
  exception String,
  stack_trace String,
  team_id Int64,
  log_comment JSON(max_dynamic_paths=256, access_method LowCardinality(String), alert_config_id String, api_key_label String, api_key_mask String, batch_export_id String, chargeable Bool, client_query_id String, cohort_id Int64, `dagster.job_name` String, `dagster.run_id` String, `dagster.tags.owner` String, dashboard_id Int64, experiment_feature_flag_key String, experiment_id Int64, feature LowCardinality(String), id String, insight_id Int64, is_impersonated Bool, kind LowCardinality(String), name String, org_id String, person_on_events_mode LowCardinality(String), product LowCardinality(String), query_type LowCardinality(String), request_name String, route_id String, service_name String, session_id String, table_id String, team_id Int64, `temporal.activity_id` String, `temporal.activity_type` String, `temporal.attempt` Int64, `temporal.workflow_id` String, `temporal.workflow_namespace` String, `temporal.workflow_run_id` String, `temporal.workflow_type` String, user_id Int64, warehouse_query Bool, workflow LowCardinality(String), workload LowCardinality(String), SKIP cache_key, SKIP filter, SKIP hogql_features, SKIP http_referer, SKIP http_request_id, SKIP http_user_agent, SKIP query_settings, SKIP timings, SKIP user_email),
  ProfileEvents Map(String, UInt64)
) ENGINE = Distributed('ops', 'posthog', 'query_log_archive_buffer');
CREATE MATERIALIZED VIEW posthog.hog_invocation_results_mv TO posthog.hog_invocation_results_data (team_id Int64, function_kind LowCardinality(String), function_id String, invocation_id String, parent_run_id String, status LowCardinality(String), attempts UInt8, is_retry UInt8, scheduled_at DateTime64(6, 'UTC'), first_scheduled_at DateTime64(6, 'UTC'), started_at Nullable(DateTime64(6, 'UTC')), finished_at Nullable(DateTime64(6, 'UTC')), duration_ms Nullable(UInt32), error_kind LowCardinality(String), error_message String, event_uuid String, distinct_id String, person_id String, invocation_globals String, version UInt64, is_deleted UInt8, _timestamp Nullable(DateTime), _offset UInt64, _partition UInt64) AS SELECT
  team_id,
  function_kind,
  function_id,
  invocation_id,
  parent_run_id,
  status,
  attempts,
  is_retry,
  scheduled_at,
  if(
    first_scheduled_at = toDateTime64('1970-01-01 00:00:00', 6, 'UTC'),
    scheduled_at,
    first_scheduled_at
  ) AS first_scheduled_at,
  started_at,
  finished_at,
  duration_ms,
  error_kind,
  error_message,
  event_uuid,
  distinct_id,
  person_id,
  invocation_globals,
  version,
  is_deleted,
  _timestamp,
  _offset,
  _partition
FROM posthog.kafka_hog_invocation_results;
CREATE MATERIALIZED VIEW posthog.ingestion_warnings_v2_mv TO posthog.ingestion_warnings_v2 (team_id Int64, source LowCardinality(String), type String, details String, timestamp DateTime64(6, 'UTC'), _timestamp Nullable(DateTime), _offset UInt64, _partition UInt64) AS SELECT
  team_id,
  source,
  type,
  details,
  timestamp,
  _timestamp,
  _offset,
  _partition
FROM posthog.kafka_ingestion_warnings_v2;
CREATE MATERIALIZED VIEW posthog.message_assets_mv TO posthog.message_assets_data (team_id Int64, function_kind LowCardinality(String), function_id String, parent_run_id String, invocation_id String, action_id String, kind LowCardinality(String), distinct_id String, person_id String, recipient String, subject String, status LowCardinality(String), sent_at DateTime64(6, 'UTC'), version UInt64, is_deleted UInt8, html String, _timestamp Nullable(DateTime), _offset UInt64, _partition UInt64) AS SELECT
  team_id,
  function_kind,
  function_id,
  parent_run_id,
  invocation_id,
  action_id,
  kind,
  distinct_id,
  person_id,
  recipient,
  subject,
  status,
  sent_at,
  version,
  is_deleted,
  html,
  _timestamp,
  _offset,
  _partition
FROM posthog.kafka_message_assets;
CREATE MATERIALIZED VIEW posthog.ops_query_log_archive_mv TO posthog.writable_query_log_archive (hostname LowCardinality(String), user LowCardinality(String), query_id String, initial_query_id String, is_initial_query UInt8, type Enum8('QueryStart'=1, 'QueryFinish'=2, 'ExceptionBeforeStart'=3, 'ExceptionWhileProcessing'=4), event_date Date, event_time DateTime, event_time_microseconds DateTime64(6), query_start_time DateTime, query_start_time_microseconds DateTime64(6), query_duration_ms UInt64, read_rows UInt64, read_bytes UInt64, written_rows UInt64, written_bytes UInt64, result_rows UInt64, result_bytes UInt64, memory_usage UInt64, peak_threads_usage UInt64, current_database LowCardinality(String), query String, formatted_query String, normalized_query_hash UInt64, query_kind LowCardinality(String), exception_code Int32, exception String, stack_trace String, team_id Int64, log_comment String, ProfileEvents Map(LowCardinality(String), UInt64)) AS SELECT
  hostname,
  user,
  query_id,
  initial_query_id,
  is_initial_query,
  type,
  event_date,
  event_time,
  event_time_microseconds,
  query_start_time,
  query_start_time_microseconds,
  query_duration_ms,
  read_rows,
  read_bytes,
  written_rows,
  written_bytes,
  result_rows,
  result_bytes,
  memory_usage,
  peak_threads_usage,
  current_database,
  query,
  formatted_query,
  normalized_query_hash,
  query_kind,
  exception_code,
  exception,
  stack_trace,
  JSONExtractInt(log_comment, 'team_id') AS team_id,
  if(isValidJSON(log_comment), log_comment, '{}') AS log_comment,
  ProfileEvents
FROM system.query_log
WHERE type != 'QueryStart';
CREATE MATERIALIZED VIEW posthog.property_values_mv TO posthog.property_values (team_id Int64, property_type LowCardinality(String), property_key String, property_value String, property_count UInt64, last_seen DateTime) AS SELECT
  team_id,
  property_type,
  property_key,
  property_value,
  property_count,
  coalesce(_timestamp, now()) AS last_seen
FROM posthog.kafka_property_values;
CREATE VIEW posthog.custom_metrics_backups AS WITH
  ['ClickHouseCustomMetric_BackupFailed', 'ClickHouseCustomMetric_BackupSuccess', 'ClickHouseCustomMetric_BackupCancelled', 'ClickHouseCustomMetric_BackupAttempts'] AS names,
  [toInt64(countIf(status = 'BACKUP_FAILED')), toInt64(countIf(status = 'BACKUP_CREATED')), toInt64(countIf(status = 'BACKUP_CANCELLED')), toInt64(countIf(status = 'CREATING_BACKUP'))] AS values,
  ['Number of failed backups', 'Number of successful backups', 'Number of cancelled backups', 'Number of backup attempts'] AS descriptions,
  ['gauge', 'gauge', 'gauge', 'gauge'] AS types,
  arrayJoin(arrayZip(names, values, descriptions, types)) AS tpl
SELECT
  tpl.1 AS name,
  map('instance', hostname()) AS labels,
  tpl.2 AS value,
  tpl.3 AS help,
  tpl.4 AS type
FROM system.backup_log
WHERE event_date = today()
GROUP BY
  event_date;
CREATE VIEW posthog.custom_metrics_dictionaries AS SELECT
  'ClickHouseCustomMetric_DictionariesFailed' AS name,
  map(
    'instance',
    hostname(),
    'database',
    d.database,
    'dictionary',
    d.dict_name,
    'uuid',
    toString(d.uuid),
    'status',
    toString(d.status)
  ) AS labels,
  toUInt64(1) AS value,
  'Dictionary is in FAILED or FAILED_AND_RELOADING status' AS help,
  'gauge' AS type
FROM
  (
    SELECT name AS dict_name, database, uuid, status
    FROM system.dictionaries
    WHERE status IN ('FAILED', 'FAILED_AND_RELOADING')
  ) AS d;
CREATE VIEW posthog.custom_metrics_part_counts AS SELECT
  'ClickHouseCustomMetric_MaxPartCountPerPartition' AS name,
  map('instance', hostname(), 'database', database, 'table', `table`, 'partition', partition) AS labels,
  part_count AS value,
  'Maximum number of active parts for any partition in a PostHog table' AS help,
  'gauge' AS type
FROM
  (
    SELECT database, `table`, partition, count() AS part_count
    FROM system.parts
    WHERE
      active
    AND
      (database = 'posthog')
    GROUP BY
      database, `table`, partition
    ORDER BY database ASC, `table` ASC, part_count DESC, partition ASC
    LIMIT 1 BY database, `table`
  );
CREATE VIEW posthog.custom_metrics_replication_queue AS WITH
  ['ClickHouseCustomMetric_ReplicationQueueStuckEntries', 'ClickHouseCustomMetric_ReplicationQueueMaxPostponedEntrySeconds', 'ClickHouseCustomMetric_ReplicationQueueMaxErrorEntrySeconds'] AS names,
  [toInt64(countIf(create_time < (now() - toIntervalDay(15)))), maxIf(dateDiff('seconds', create_time, last_postpone_time), last_postpone_time != '1970-01-01'), maxIf(dateDiff('seconds', create_time, last_exception_time), (last_exception_time != '1970-01-01') AND (last_exception_time > (now() - toIntervalMinute(5))))] AS values,
  ['Number of entries that have been in the replication queue for more than 15 days', 'Maximum number of seconds that an entry has been postponed', 'Maximum number of seconds that an entry has been in error'] AS descriptions,
  ['gauge', 'gauge', 'gauge'] AS types,
  arrayJoin(arrayZip(names, values, descriptions, types)) AS tpl
SELECT
  tpl.1 AS name,
  map('table', `table`, 'instance', hostname()) AS labels,
  tpl.2 AS value,
  tpl.3 AS help,
  tpl.4 AS type
FROM system.replication_queue
GROUP BY
  `table`
HAVING
  value > 0;
CREATE VIEW posthog.custom_metrics_server_crash AS SELECT
  'ClickHouseCustomMetric_ServerCrash' AS name,
  map('instance', hostname()) AS labels,
  count() AS value,
  'Number of server crashes for current date' AS help,
  'gauge' AS type
FROM system.crash_log
WHERE event_date = today()
GROUP BY
  hostname();
CREATE VIEW posthog.custom_metrics_table_sizes AS SELECT
  'ClickHouseCustomMetric_TableTotalBytes' AS name,
  map('instance', hostname(), 'database', database, 'table', `table`) AS labels,
  CAST(total_bytes, 'Float64') AS value,
  'Size of a database table on a given node (need a sum for sharded)' AS help,
  'gauge' AS type
FROM system.tables
WHERE
  (database NOT IN ('INFORMATION_SCHEMA', 'information_schema'))
AND
  (total_bytes IS NOT NULL);
CREATE VIEW posthog.custom_metrics_test AS SELECT
  'ClickHouseCustomMetric_Test' AS name,
  map('instance', hostname()) AS labels,
  1 AS value,
  'Test to check that the metric endpoint is working' AS help,
  'gauge' AS type;
CREATE OR REPLACE DICTIONARY posthog.web_bot_definition_dict (`regexp` String, `name` String, `category` String, `traffic_type` String, `operator` String) PRIMARY KEY regexp SOURCE(CLICKHOUSE(USER 'default' DB 'posthog' TABLE 'web_bot_definition')) LAYOUT(REGEXP_TREE()) LIFETIME(MIN 3000 MAX 3600);
CREATE TABLE posthog.conversion_goal_attributed_preaggregated (
  team_id Int64,
  job_id UUID,
  person_id UUID,
  conversion_timestamp DateTime64(6, 'UTC'),
  conversion_value Float64,
  touchpoint_timestamp DateTime64(6, 'UTC'),
  touchpoint_weight Float64,
  campaign_name String,
  source_name String,
  medium_name String,
  content_name String,
  term_name String,
  referring_domain_name String,
  gclid_name String,
  fbclid_name String,
  gad_source_name String,
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at Date DEFAULT today() + toIntervalDay(7)
) ENGINE = Distributed('aux', 'posthog', 'sharded_conversion_goal_attributed_preaggregated', cityHash64(person_id));
CREATE TABLE posthog.error_tracking_fingerprint_issue_state (
  team_id Int64,
  fingerprint String,
  issue_id UUID,
  issue_name Nullable(String),
  issue_description Nullable(String),
  issue_status String,
  assigned_user_id Nullable(Int64),
  assigned_role_id Nullable(UUID),
  first_seen DateTime64(3, 'UTC'),
  is_deleted Int8,
  version Int64,
  _timestamp DateTime,
  _offset UInt64,
  _partition UInt64
) ENGINE = Distributed('aux', 'posthog', 'raw_error_tracking_fingerprint_issue_state');
CREATE TABLE posthog.experiment_metric_events_preaggregated (
  team_id Int64,
  job_id UUID,
  entity_id String,
  timestamp DateTime64(6, 'UTC'),
  event_uuid UUID,
  session_id String,
  numeric_value Float64 DEFAULT 0,
  steps Array(UInt8) DEFAULT [],
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at Date DEFAULT today() + toIntervalDay(7)
) ENGINE = Distributed('aux', 'posthog', 'sharded_experiment_metric_events_preaggregated', cityHash64(entity_id));
CREATE TABLE posthog.hog_invocation_results (
  team_id Int64,
  function_kind LowCardinality(String),
  function_id String,
  invocation_id String,
  parent_run_id String,
  status LowCardinality(String),
  attempts UInt8,
  is_retry UInt8,
  scheduled_at DateTime64(6, 'UTC'),
  first_scheduled_at DateTime64(6, 'UTC'),
  started_at Nullable(DateTime64(6, 'UTC')),
  finished_at Nullable(DateTime64(6, 'UTC')),
  duration_ms Nullable(UInt32),
  error_kind LowCardinality(String),
  error_message String,
  event_uuid String,
  distinct_id String,
  person_id String,
  invocation_globals String,
  version UInt64,
  is_deleted UInt8,
  _timestamp DateTime,
  _offset UInt64,
  _partition UInt64
) ENGINE = Distributed('aux', 'posthog', 'hog_invocation_results_data');
CREATE TABLE posthog.ingestion_warnings_main (
  team_id Int64,
  source LowCardinality(String),
  type String,
  details String CODEC(ZSTD(3)),
  timestamp DateTime64(6, 'UTC'),
  _timestamp DateTime,
  _offset UInt64,
  _partition UInt64
) ENGINE = Distributed('posthog', 'posthog', 'sharded_ingestion_warnings', rand());
CREATE TABLE posthog.marketing_conversions_preaggregated (
  team_id Int64,
  job_id UUID,
  person_id UUID,
  conversion_timestamp DateTime64(6, 'UTC'),
  conversion_math_value Float64,
  session_id String,
  campaign_name String,
  source_name String,
  medium_name String,
  content_name String,
  term_name String,
  referring_domain_name String,
  gclid_name String,
  fbclid_name String,
  gad_source_name String,
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at Date DEFAULT today() + toIntervalDay(7)
) ENGINE = Distributed('aux', 'posthog', 'sharded_marketing_conversions_preaggregated', cityHash64(person_id));
CREATE TABLE posthog.marketing_costs_preaggregated (
  team_id Int64,
  job_id UUID,
  source_id String,
  source_name String,
  grain LowCardinality(String),
  match_key String,
  campaign_id String,
  campaign_name String,
  ad_group_id String,
  ad_group_name String,
  ad_id String,
  ad_name String,
  cost_date Date,
  cost Float64,
  clicks Float64,
  impressions Float64,
  reported_conversions Float64,
  reported_conversion_value Float64,
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at Date DEFAULT today() + toIntervalDay(7)
) ENGINE = Distributed('aux', 'posthog', 'sharded_marketing_costs_preaggregated', cityHash64(source_name, campaign_id));
CREATE TABLE posthog.marketing_touchpoints_preaggregated (
  team_id Int64,
  job_id UUID,
  person_id UUID,
  touchpoint_timestamp DateTime64(6, 'UTC'),
  campaign_name String,
  source_name String,
  medium_name String,
  content_name String,
  term_name String,
  referring_domain_name String,
  gclid_name String,
  fbclid_name String,
  gad_source_name String,
  computed_at DateTime64(6, 'UTC') DEFAULT now(),
  expires_at Date DEFAULT today() + toIntervalDay(7)
) ENGINE = Distributed('aux', 'posthog', 'sharded_marketing_touchpoints_preaggregated', cityHash64(person_id));
CREATE TABLE posthog.message_assets (
  team_id Int64,
  function_kind LowCardinality(String),
  function_id String,
  parent_run_id String,
  invocation_id String,
  action_id String,
  kind LowCardinality(String),
  distinct_id String,
  person_id String,
  recipient String,
  subject String,
  status LowCardinality(String),
  sent_at DateTime64(6, 'UTC'),
  version UInt64,
  is_deleted UInt8,
  html String,
  _timestamp DateTime,
  _offset UInt64,
  _partition UInt64
) ENGINE = Distributed('aux', 'posthog', 'message_assets_data');
CREATE TABLE posthog.session_replay_features (
  session_id String,
  team_id Int64,
  distinct_id String,
  min_first_timestamp SimpleAggregateFunction(min, DateTime64(6, 'UTC')),
  max_last_timestamp SimpleAggregateFunction(max, DateTime64(6, 'UTC')),
  event_count SimpleAggregateFunction(sum, Int64),
  mouse_position_count SimpleAggregateFunction(sum, Int64),
  mouse_sum_x SimpleAggregateFunction(sum, Float64),
  mouse_sum_x_squared SimpleAggregateFunction(sum, Float64),
  mouse_sum_y SimpleAggregateFunction(sum, Float64),
  mouse_sum_y_squared SimpleAggregateFunction(sum, Float64),
  mouse_distance_traveled SimpleAggregateFunction(sum, Float64),
  mouse_direction_change_count SimpleAggregateFunction(sum, Int64),
  mouse_velocity_sum SimpleAggregateFunction(sum, Float64),
  mouse_velocity_sum_of_squares SimpleAggregateFunction(sum, Float64),
  mouse_velocity_count SimpleAggregateFunction(sum, Int64),
  scroll_event_count SimpleAggregateFunction(sum, Int64),
  total_scroll_magnitude SimpleAggregateFunction(sum, Float64),
  scroll_direction_reversal_count SimpleAggregateFunction(sum, Int64),
  rapid_scroll_reversal_count SimpleAggregateFunction(sum, Int64),
  scroll_to_top_count SimpleAggregateFunction(sum, Int64),
  click_count SimpleAggregateFunction(sum, Int64),
  keypress_count SimpleAggregateFunction(sum, Int64),
  mouse_activity_count SimpleAggregateFunction(sum, Int64),
  rage_click_count SimpleAggregateFunction(sum, Int64),
  dead_click_count SimpleAggregateFunction(sum, Int64),
  backspace_count SimpleAggregateFunction(sum, Int64),
  inter_action_gap_count SimpleAggregateFunction(sum, Int64),
  inter_action_gap_sum_ms SimpleAggregateFunction(sum, Float64),
  inter_action_gap_sum_of_squares_ms SimpleAggregateFunction(sum, Float64),
  max_idle_gap_ms SimpleAggregateFunction(max, Float64),
  long_idle_gap_count SimpleAggregateFunction(sum, Int64),
  quick_back_count SimpleAggregateFunction(sum, Int64),
  page_visit_count SimpleAggregateFunction(sum, Int64),
  unique_url_count AggregateFunction(uniqCombined(12), String),
  login_path_visit_count SimpleAggregateFunction(sum, Int64),
  signup_path_visit_count SimpleAggregateFunction(sum, Int64),
  checkout_path_visit_count SimpleAggregateFunction(sum, Int64),
  cart_path_visit_count SimpleAggregateFunction(sum, Int64),
  billing_path_visit_count SimpleAggregateFunction(sum, Int64),
  settings_path_visit_count SimpleAggregateFunction(sum, Int64),
  account_path_visit_count SimpleAggregateFunction(sum, Int64),
  error_path_visit_count SimpleAggregateFunction(sum, Int64),
  not_found_path_visit_count SimpleAggregateFunction(sum, Int64),
  admin_path_visit_count SimpleAggregateFunction(sum, Int64),
  dashboard_path_visit_count SimpleAggregateFunction(sum, Int64),
  onboarding_path_visit_count SimpleAggregateFunction(sum, Int64),
  cancel_path_visit_count SimpleAggregateFunction(sum, Int64),
  refund_path_visit_count SimpleAggregateFunction(sum, Int64),
  console_error_count SimpleAggregateFunction(sum, Int64),
  console_error_after_click_count SimpleAggregateFunction(sum, Int64),
  console_warn_count SimpleAggregateFunction(sum, Int64),
  network_request_count SimpleAggregateFunction(sum, Int64),
  network_failed_request_count SimpleAggregateFunction(sum, Int64),
  network_4xx_count SimpleAggregateFunction(sum, Int64),
  network_5xx_count SimpleAggregateFunction(sum, Int64),
  network_request_duration_sum SimpleAggregateFunction(sum, Float64),
  network_request_duration_sum_of_squares SimpleAggregateFunction(sum, Float64),
  network_request_duration_count SimpleAggregateFunction(sum, Int64),
  mutation_count SimpleAggregateFunction(sum, Int64),
  viewport_resize_count SimpleAggregateFunction(sum, Int64),
  touch_event_count SimpleAggregateFunction(sum, Int64),
  max_scroll_y SimpleAggregateFunction(max, Float64),
  unique_click_target_count AggregateFunction(uniqCombined(12), Int64),
  unique_form_field_count AggregateFunction(uniqCombined(12), Int64),
  text_selection_count SimpleAggregateFunction(sum, Int64),
  selection_copy_count SimpleAggregateFunction(sum, Int64),
  is_deleted SimpleAggregateFunction(max, UInt8) DEFAULT 0
) ENGINE = Distributed('aux', 'posthog', 'sharded_session_replay_features', sipHash64(session_id));
