import { MakeLogicType, actions, connect, kea, key, listeners, path, props, reducers, selectors } from 'kea'

import { lemonToast } from '@posthog/lemon-ui'

import api from 'lib/api'
import { FEATURE_FLAGS } from 'lib/constants'
import { dayjs } from 'lib/dayjs'
import { FeatureFlagsSet, featureFlagLogic } from 'lib/logic/featureFlagLogic'
import { createCohortFormData } from 'scenes/cohorts/cohortUtils'

import { cohortsModel } from '~/models/cohortsModel'
import { AnyPropertyFilter, CohortType, PropertyFilterType, PropertyOperator } from '~/types'

import { cohortsRetrieve } from 'products/cohorts/frontend/generated/api'

import { workflowPeopleImportsCreate } from '../../generated/api'
import type { PeopleImportApi } from '../../generated/api.schemas'
import { BroadcastWizardLogicProps, broadcastWizardLogic } from '../broadcastWizardLogic'
import { csvListError, defaultListCohortName, peopleImportMessage, readCsvText } from './audienceList'
import { parsePeopleCsv } from './peopleCsv'

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface broadcastAudienceListLogicValues {
    audienceProperties: AnyPropertyFilter[] // broadcastWizardLogic
    currentProjectId: number | null // broadcastWizardLogic
    name: string // broadcastWizardLogic
    featureFlags: FeatureFlagsSet // featureFlagLogic
    cohortName: string
    createError: string | null
    creating: boolean
    file: File | null
    importsPeople: boolean
    isListModalOpen: boolean
    submitDisabledReason: string | null
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface broadcastAudienceListLogicActions {
    setAudienceProperties: (properties: AnyPropertyFilter[]) => {
        properties: AnyPropertyFilter[]
    } // broadcastWizardLogic
    cohortCreated: (cohort: CohortType) => {
        cohort: CohortType
    } // cohortsModel
    closeListModal: () => {
        value: true
    }
    createListCohort: () => {
        value: true
    }
    createListCohortFinished: (error: string | null) => {
        error: string | null
    }
    openListModal: () => {
        value: true
    }
    setCohortName: (cohortName: string) => {
        cohortName: string
    }
    setFile: (file: File | null) => {
        file: File | null
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface broadcastAudienceListLogicMeta {
    key: string
    __keaTypeGenInternalSelectorTypes: {
        importsPeople: (featureFlags: FeatureFlagsSet) => boolean
        submitDisabledReason: (file: File | null, cohortName: string) => string | null
    }
}

export type broadcastAudienceListLogicType = MakeLogicType<
    broadcastAudienceListLogicValues,
    broadcastAudienceListLogicActions,
    BroadcastWizardLogicProps,
    broadcastAudienceListLogicMeta
>

export const broadcastAudienceListLogic = kea<broadcastAudienceListLogicType>([
    path(['products', 'workflows', 'frontend', 'Broadcasts', 'audience', 'broadcastAudienceListLogic']),
    props({} as BroadcastWizardLogicProps),
    key((props) => props.id),
    connect((props: BroadcastWizardLogicProps) => ({
        values: [
            broadcastWizardLogic(props),
            ['name', 'audienceProperties', 'currentProjectId'],
            featureFlagLogic,
            ['featureFlags'],
        ],
        actions: [broadcastWizardLogic(props), ['setAudienceProperties'], cohortsModel, ['cohortCreated']],
    })),
    actions({
        openListModal: true,
        closeListModal: true,
        setFile: (file: File | null) => ({ file }),
        setCohortName: (cohortName: string) => ({ cohortName }),
        createListCohort: true,
        createListCohortFinished: (error: string | null) => ({ error }),
    }),
    reducers({
        isListModalOpen: [
            false,
            {
                openListModal: () => true,
                closeListModal: () => false,
            },
        ],
        file: [
            null as File | null,
            {
                setFile: (_, { file }) => file,
                openListModal: () => null,
            },
        ],
        cohortName: [
            '',
            {
                setCohortName: (_, { cohortName }) => cohortName,
            },
        ],
        creating: [
            false,
            {
                createListCohort: () => true,
                createListCohortFinished: () => false,
            },
        ],
        createError: [
            null as string | null,
            {
                createListCohortFinished: (_, { error }) => error,
                openListModal: () => null,
                setFile: () => null,
            },
        ],
    }),
    selectors({
        // With the flag on, each row creates or updates a person and the columns become person properties.
        importsPeople: [
            (s) => [s.featureFlags],
            (featureFlags: FeatureFlagsSet): boolean =>
                !!featureFlags[FEATURE_FLAGS.WORKFLOWS_BROADCAST_RECIPIENT_LISTS],
        ],
        submitDisabledReason: [
            (s) => [s.file, s.cohortName],
            (file: File | null, cohortName: string): string | null => {
                if (!file) {
                    return 'Choose a CSV file'
                }
                if (!cohortName.trim()) {
                    return 'Give the cohort a name'
                }
                return null
            },
        ],
    }),
    listeners(({ actions, values }) => {
        const addCohortToAudience = (cohort: CohortType): void => {
            actions.cohortCreated(cohort)
            actions.setAudienceProperties([
                ...values.audienceProperties,
                {
                    type: PropertyFilterType.Cohort,
                    key: 'id',
                    value: cohort.id as number,
                    operator: PropertyOperator.In,
                    cohort_name: cohort.name,
                },
            ])
            actions.closeListModal()
            actions.createListCohortFinished(null)
        }

        const importPeople = async (csv: File): Promise<void> => {
            if (values.currentProjectId === null) {
                actions.createListCohortFinished("Couldn't find the project. Reload the page and try again.")
                return
            }
            const projectId = String(values.currentProjectId)
            let rows: Record<string, string>[]
            try {
                rows = parsePeopleCsv(await readCsvText(csv))
            } catch (error: any) {
                actions.createListCohortFinished(error?.message ?? "Couldn't read the file.")
                return
            }
            let summary: PeopleImportApi
            try {
                summary = await workflowPeopleImportsCreate(projectId, { name: values.cohortName.trim(), rows })
            } catch (error: any) {
                actions.createListCohortFinished(
                    `Couldn't import the people: ${error?.detail ?? error?.message ?? 'unknown error'}`
                )
                return
            }
            // The import has started, so a failed read must not let a retry start a second one.
            let cohort: CohortType
            try {
                cohort = (await cohortsRetrieve(projectId, summary.cohort_id)) as unknown as CohortType
            } catch {
                cohort = {
                    id: summary.cohort_id,
                    name: values.cohortName.trim(),
                    is_static: true,
                    is_calculating: true,
                } as CohortType
            }
            addCohortToAudience(cohort)
            const skippedRows =
                summary.dropped_invalid_email + summary.dropped_duplicate_email + summary.dropped_too_large
            const toast = skippedRows ? lemonToast.warning : lemonToast.success
            toast(peopleImportMessage(cohort.name ?? values.cohortName.trim(), summary))
        }

        return {
            openListModal: () => {
                actions.setCohortName(defaultListCohortName(values.name, dayjs().format('MMM D')))
            },
            createListCohort: async () => {
                if (values.submitDisabledReason) {
                    actions.createListCohortFinished(values.submitDisabledReason)
                    return
                }
                const csv = values.file!
                if (values.importsPeople) {
                    await importPeople(csv)
                    return
                }
                let fileError: string | null
                try {
                    fileError = csvListError(await readCsvText(csv))
                } catch (error: any) {
                    actions.createListCohortFinished(
                        error?.message ?? "Couldn't read the file. Try uploading it again."
                    )
                    return
                }
                if (fileError) {
                    actions.createListCohortFinished(fileError)
                    return
                }
                let cohort: CohortType
                try {
                    const formData = createCohortFormData({
                        name: values.cohortName.trim(),
                        description: 'Created from a list in a broadcast audience.',
                        is_static: true,
                        csv,
                    } as CohortType)
                    // nosemgrep: prefer-codegen-api -- the CSV goes up as multipart form data, which the generated JSON client can't send.
                    cohort = await api.cohorts.create(formData as Partial<CohortType>)
                } catch (error: any) {
                    const message = error?.data?.csv?.[0] ?? error?.detail ?? error?.message ?? 'unknown error'
                    actions.createListCohortFinished(`Couldn't create the cohort: ${message}`)
                    return
                }
                addCohortToAudience(cohort)
                lemonToast.success(
                    `Added "${cohort.name}" to the audience. Matching the people on it can take a minute.`
                )
            },
        }
    }),
])
