from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

_SOAP_DOCS = "https://developer.salesforce.com/docs/marketing/marketing-cloud/references/mc_soap_api"
_TRACKING_EVENT_DOCS = (
    "https://developer.salesforce.com/docs/marketing/marketing-cloud/guide/tracking_events_overview.html"
)

_TRACKING_EVENT_COLUMNS = {
    "SendID": "Identifier of the send job the event belongs to. Joins to the sends table.",
    "SubscriberKey": "Unique subscriber identifier the event was recorded against.",
    "EventDate": "Date and time the event occurred, in the account's timezone.",
    "EventType": "Type of tracking event recorded.",
    "BatchID": "Identifier of the batch the send was processed in.",
    "TriggeredSendDefinitionObjectID": "Object identifier of the triggered send definition, when the send came from a triggered send.",
    "PartnerKey": "External key assigned by the client application, when one is set.",
}


CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "subscribers": {
        "description": "All contacts in the Marketing Cloud account, with their subscription status and preferences.",
        "docs_url": _SOAP_DOCS,
        "columns": {
            "ID": "Marketing Cloud identifier of the subscriber.",
            "SubscriberKey": "Unique identifier for the subscriber, assigned by the account.",
            "EmailAddress": "Email address on the subscriber record.",
            "Status": "Subscription status, such as Active, Bounced, Held or Unsubscribed.",
            "EmailTypePreference": "Preferred email format for this subscriber, HTML or Text.",
            "CreatedDate": "Date and time the subscriber was created.",
            "ModifiedDate": "Date and time the subscriber was last modified.",
            "UnsubscribedDate": "Date and time the subscriber unsubscribed, when applicable.",
            "PartnerKey": "External key assigned by the client application, when one is set.",
        },
    },
    "lists": {
        "description": "Subscriber lists defined in the account, including publication and suppression lists.",
        "docs_url": _SOAP_DOCS,
        "columns": {
            "ID": "Marketing Cloud identifier of the list.",
            "ObjectID": "System-generated object identifier of the list.",
            "ListName": "Name of the list.",
            "Description": "Description of the list.",
            "Category": "Identifier of the folder the list is stored in.",
            "Type": "List type, such as Public, Private, Salesforce or Suppression.",
            "ListClassification": "Classification of the list, such as ExactTargetList or PublicationList.",
            "CreatedDate": "Date and time the list was created.",
            "ModifiedDate": "Date and time the list was last modified.",
            "PartnerKey": "External key assigned by the client application, when one is set.",
        },
    },
    "sends": {
        "description": "Send jobs and their aggregate delivery and engagement counts.",
        "docs_url": _SOAP_DOCS,
        "columns": {
            "ID": "Identifier of the send job.",
            "EmailName": "Name of the email used for the send.",
            "Subject": "Subject line of the sent email.",
            "FromAddress": "From address the email was sent with.",
            "FromName": "From name the email was sent with.",
            "SendDate": "Date and time the send was scheduled for.",
            "SentDate": "Date and time the send was actually processed.",
            "Status": "Status of the send job.",
            "IsMultipart": "Whether the email was sent as multipart MIME.",
            "NumberSent": "Number of messages sent.",
            "NumberDelivered": "Number of messages delivered.",
            "NumberTargeted": "Number of subscribers targeted by the send.",
            "NumberErrored": "Number of messages that errored during the send.",
            "UniqueOpens": "Number of unique subscribers who opened the email.",
            "UniqueClicks": "Number of unique subscribers who clicked a link in the email.",
            "HardBounces": "Number of hard bounces recorded for the send.",
            "SoftBounces": "Number of soft bounces recorded for the send.",
            "OtherBounces": "Number of bounces that were neither hard nor soft.",
            "Unsubscribes": "Number of unsubscribes resulting from the send.",
            "MissingAddresses": "Number of targeted subscribers with no email address.",
            "InvalidAddresses": "Number of targeted addresses that failed validation.",
            "ExistingUndeliverables": "Number of targeted subscribers already marked undeliverable.",
            "ExistingUnsubscribes": "Number of targeted subscribers already unsubscribed.",
            "Duplicates": "Number of duplicate subscribers excluded from the send.",
            "ForwardedEmails": "Number of forwards recorded via forward-to-a-friend.",
            "CreatedDate": "Date and time the send job was created.",
            "ModifiedDate": "Date and time the send job was last modified.",
            "PartnerKey": "External key assigned by the client application, when one is set.",
        },
    },
    "sent_events": {
        "description": "One row per message Marketing Cloud sent to a subscriber.",
        "docs_url": _TRACKING_EVENT_DOCS,
        "columns": _TRACKING_EVENT_COLUMNS,
    },
    "open_events": {
        "description": "One row per recorded open of a sent message.",
        "docs_url": _TRACKING_EVENT_DOCS,
        "columns": _TRACKING_EVENT_COLUMNS,
    },
    "click_events": {
        "description": "One row per link click recorded against a sent message.",
        "docs_url": _TRACKING_EVENT_DOCS,
        "columns": {
            **_TRACKING_EVENT_COLUMNS,
            "URL": "URL the subscriber clicked.",
            "URLID": "Identifier of the clicked link within the email.",
            "LinkName": "Alias given to the link in the email content.",
            "LinkContent": "Content of the link as it appeared in the email.",
        },
    },
    "bounce_events": {
        "description": "One row per bounced message, with the bounce classification returned by the receiving server.",
        "docs_url": _TRACKING_EVENT_DOCS,
        "columns": {
            **_TRACKING_EVENT_COLUMNS,
            "BounceCategory": "Category Marketing Cloud assigned to the bounce.",
            "BounceType": "Bounce type, such as hard, soft or block.",
            "SMTPCode": "SMTP status code returned by the receiving mail server.",
            "SMTPReason": "SMTP reason text returned by the receiving mail server.",
        },
    },
    "unsub_events": {
        "description": "One row per unsubscribe recorded against a send.",
        "docs_url": _TRACKING_EVENT_DOCS,
        "columns": {
            **_TRACKING_EVENT_COLUMNS,
            "ListID": "Identifier of the list the subscriber unsubscribed from.",
            "IsMasterUnsubscribed": "Whether the subscriber unsubscribed from all communications for the account.",
        },
    },
    "data_extensions": {
        "description": "Catalog of the account's data extensions. Row contents are not synced — this is the table definition list.",
        "docs_url": _SOAP_DOCS,
        "columns": {
            "ObjectID": "System-generated object identifier of the data extension.",
            "CustomerKey": "External key of the data extension, unique within the account.",
            "Name": "Name of the data extension.",
            "Description": "Description of the data extension.",
            "CategoryID": "Identifier of the folder the data extension is stored in.",
            "IsSendable": "Whether the data extension can be used as a send audience.",
            "IsTestable": "Whether the data extension can be used for test sends.",
            "CreatedDate": "Date and time the data extension was created.",
            "ModifiedDate": "Date and time the data extension was last modified.",
            "PartnerKey": "External key assigned by the client application, when one is set.",
        },
    },
    "data_extension_fields": {
        "description": "Field definitions for every data extension in the account.",
        "docs_url": _SOAP_DOCS,
        "columns": {
            "ObjectID": "System-generated object identifier of the field.",
            "CustomerKey": "External key of the field.",
            "Name": "Name of the field.",
            "FieldType": "Data type of the field, such as Text, Number, Date or EmailAddress.",
            "DefaultValue": "Default value applied when no value is supplied.",
            "MaxLength": "Maximum length allowed for text fields.",
            "Scale": "Number of decimal places for decimal fields.",
            "IsRequired": "Whether the field must have a value.",
            "IsPrimaryKey": "Whether the field is part of the data extension's primary key.",
            "Ordinal": "Position of the field within the data extension.",
            "CreatedDate": "Date and time the field was created.",
            "ModifiedDate": "Date and time the field was last modified.",
            "DataExtension_CustomerKey": "External key of the data extension the field belongs to.",
        },
    },
    "assets": {
        "description": "Content Builder assets, including emails, templates, images and blocks.",
        "docs_url": "https://developer.salesforce.com/docs/marketing/marketing-cloud/references/mc_rest_asset",
        "columns": {
            "id": "Identifier of the asset.",
            "customerKey": "External key of the asset.",
            "objectID": "System-generated object identifier of the asset.",
            "name": "Name of the asset.",
            "description": "Description of the asset.",
            "assetType": "Asset type object, including its id and name.",
            "category": "Folder the asset is stored in.",
            "createdDate": "Date and time the asset was created.",
            "modifiedDate": "Date and time the asset was last modified.",
            "status": "Status of the asset.",
            "version": "Version number of the asset.",
        },
    },
    "journeys": {
        "description": "Journey Builder journeys (interactions) defined in the account.",
        "docs_url": "https://developer.salesforce.com/docs/marketing/marketing-cloud/references/mc_rest_interaction",
        "columns": {
            "id": "Identifier of the journey.",
            "key": "External key of the journey.",
            "name": "Name of the journey.",
            "description": "Description of the journey.",
            "version": "Version number of the journey. A journey id is reused across versions.",
            "workflowApiVersion": "Journey Builder API version the journey was built with.",
            "createdDate": "Date and time the journey version was created.",
            "modifiedDate": "Date and time the journey version was last modified.",
            "status": "Status of the journey version, such as Draft, Published or Stopped.",
            "definitionId": "Identifier shared by every version of the journey.",
        },
    },
    "campaigns": {
        "description": "Campaigns used to group Marketing Cloud assets and sends.",
        "docs_url": "https://developer.salesforce.com/docs/marketing/marketing-cloud/references/mc_rest_campaign",
        "columns": {
            "id": "Identifier of the campaign.",
            "name": "Name of the campaign.",
            "description": "Description of the campaign.",
            "campaignCode": "Code assigned to the campaign.",
            "color": "Display color assigned to the campaign.",
            "favorite": "Whether the campaign is marked as a favorite.",
            "createdDate": "Date and time the campaign was created.",
            "modifiedDate": "Date and time the campaign was last modified.",
        },
    },
}
