export const KAFKA_EVENTS = 'clickhouse_events_proto'
export const KAFKA_PERSON = 'clickhouse_person'
export const KAFKA_PERSON_UNIQUE_ID = 'clickhouse_person_unique_id'
export const KAFKA_SESSION_RECORDING_EVENTS = 'clickhouse_session_recording_events'
export const KAFKA_EVENTS_WAL = 'events_write_ahead_log'
