import { MakeLogicType, afterMount, kea, path } from 'kea'
import { loaders } from 'kea-loaders'

import api, { CountedPaginatedResponse } from 'lib/api'
import { OrganizationMembershipLevel } from 'lib/constants'

import { OrganizationMemberType } from '~/types'

/** One more than the banner lists, so it can also say how many admins it left out. */
const ADMINS_FETCHED = 4

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface askAdminToUpgradeLogicValues {
    admins: CountedPaginatedResponse<OrganizationMemberType> | null
    adminsLoading: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface askAdminToUpgradeLogicActions {
    loadAdmins: () => any
    loadAdminsFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadAdminsSuccess: (
        admins: CountedPaginatedResponse<OrganizationMemberType>,
        payload?: any
    ) => {
        admins: CountedPaginatedResponse<OrganizationMemberType>
        payload?: any
    }
}

export type askAdminToUpgradeLogicType = MakeLogicType<askAdminToUpgradeLogicValues, askAdminToUpgradeLogicActions>

export const askAdminToUpgradeLogic = kea<askAdminToUpgradeLogicType>([
    path(['lib', 'components', 'payGateMini', 'askAdminToUpgradeLogic']),
    loaders({
        admins: [
            null as CountedPaginatedResponse<OrganizationMemberType> | null,
            {
                loadAdmins: async () =>
                    await api.organizationMembers.list({
                        levels: `${OrganizationMembershipLevel.Admin},${OrganizationMembershipLevel.Owner}`,
                        limit: ADMINS_FETCHED,
                    }),
            },
        ],
    }),
    afterMount(({ actions }) => {
        actions.loadAdmins()
    }),
])
