name: Dockerfile lint

on:
    - pull_request

jobs:
    build:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Check if any Dockerfile has changed
              id: changed-files
              uses: tj-actions/changed-files@v9.3
              with:
                  files: |
                      **Dockerfile
                  separator: ' '

            - name: Lint changed Dockerfile(s) with Hadolint
              uses: jbergstroem/hadolint-gh-action@v1
              if: steps.changed-files.outputs.any_changed == 'true'
              with:
                  dockerfile: '${{ steps.changed-files.outputs.all_modified_files }}'
