version: 1
owners: [team-devex]
rules:
    - match: '/ci-llm-gateway.yml'
      owners: [team-devex, team-ai-gateway]
    - match: '/llm-gateway-cd.yml'
      owners: [team-devex, team-ai-gateway]
    - match: '/update-ai-costs.yml'
      owners: [team-devex, team-ai-gateway]
    - match: '/cd-llm-analytics-image.yml'
      owners: [team-devex, team-ai-observability]
