# Column lists that more than one object uses.

locals {
  metric_names3_columns = [
    { name = "team_id", type = "Int32" },
    { name = "metric_name", type = "LowCardinality(String)" },
    { name = "time_bucket", type = "DateTime64(0)" },
    { name = "original_expiry_time_bucket", type = "DateTime64(0)" },
    { name = "original_expiry_timestamp", type = "SimpleAggregateFunction(max, DateTime64(6))" },
  ]

  metric_attributes2_columns = [
    { name = "team_id", type = "Int32" },
    { name = "time_bucket", type = "DateTime64(0)" },
    { name = "original_expiry_time_bucket", type = "DateTime64(0)" },
    { name = "service_name", type = "LowCardinality(String)" },
    { name = "attribute_key", type = "LowCardinality(String)" },
    { name = "attribute_value", type = "String" },
    { name = "attribute_type", type = "LowCardinality(String)" },
    { name = "attribute_count", type = "SimpleAggregateFunction(sum, UInt64)" },
  ]

  metric_attributes3_columns = [
    { name = "team_id", type = "Int32" },
    { name = "metric_name", type = "LowCardinality(String)" },
    { name = "time_bucket", type = "DateTime64(0)" },
    { name = "original_expiry_time_bucket", type = "DateTime64(0)" },
    { name = "service_name", type = "LowCardinality(String)" },
    { name = "attribute_key", type = "LowCardinality(String)" },
    { name = "attribute_value", type = "String" },
    { name = "attribute_type", type = "LowCardinality(String)" },
    { name = "attribute_count", type = "SimpleAggregateFunction(sum, UInt64)" },
  ]

  metric_samples1_columns = [
    { name = "team_id", type = "Int32" },
    { name = "metric_name", type = "LowCardinality(String)" },
    { name = "series_fingerprint", type = "UInt64", codec = "DoubleDelta" },
    { name = "timestamp", type = "DateTime64(6)", codec = "DoubleDelta" },
    { name = "value", type = "Float64", codec = "Gorilla(8)" },
    { name = "count", type = "UInt64", default_expression = "1" },
    { name = "histogram_bounds", type = "Array(Float64)" },
    { name = "histogram_counts", type = "Array(UInt64)" },
    { name = "trace_id", type = "String" },
    { name = "span_id", type = "String" },
    { name = "trace_flags", type = "Int32" },
  ]

  metric_series1_columns = [
    { name = "team_id", type = "Int32" },
    { name = "metric_name", type = "LowCardinality(String)" },
    { name = "series_fingerprint", type = "UInt64", codec = "DoubleDelta" },
    { name = "metric_type", type = "LowCardinality(String)" },
    { name = "unit", type = "LowCardinality(String)" },
    { name = "aggregation_temporality", type = "LowCardinality(String)" },
    { name = "is_monotonic", type = "Bool", default_expression = "false" },
    { name = "service_name", type = "LowCardinality(String)" },
    { name = "resource_attributes", type = "Map(LowCardinality(String), String)" },
    { name = "attributes", type = "Map(LowCardinality(String), String)" },
    { name = "last_seen", type = "DateTime64(6)", codec = "DoubleDelta" },
  ]

  metric_series2_columns = [
    { name = "team_id", type = "Int32" },
    { name = "metric_name", type = "LowCardinality(String)" },
    { name = "series_fingerprint", type = "UInt64", codec = "Delta(8), Default" },
    { name = "metric_type", type = "LowCardinality(String)" },
    { name = "unit", type = "LowCardinality(String)" },
    { name = "aggregation_temporality", type = "LowCardinality(String)" },
    { name = "is_monotonic", type = "Bool", default_expression = "false" },
    { name = "service_name", type = "LowCardinality(String)" },
    { name = "instrumentation_scope", type = "String" },
    { name = "resource_attributes", type = "Map(LowCardinality(String), String)" },
    { name = "resource_fingerprint", type = "UInt64", materialized_expression = "cityHash64(resource_attributes)" },
    { name = "attributes", type = "Map(LowCardinality(String), String)" },
    { name = "last_seen", type = "DateTime64(6)" },
    { name = "original_expiry_timestamp", type = "DateTime64(6)" },
  ]

  kafka_metrics_avro2_columns = [
    { name = "uuid", type = "String" },
    { name = "trace_id", type = "String" },
    { name = "span_id", type = "String" },
    { name = "trace_flags", type = "Nullable(Int32)" },
    { name = "timestamp", type = "DateTime64(6)" },
    { name = "observed_timestamp", type = "DateTime64(6)" },
    { name = "service_name", type = "Nullable(String)" },
    { name = "metric_name", type = "Nullable(String)" },
    { name = "metric_type", type = "Nullable(String)" },
    { name = "value", type = "Nullable(Float64)" },
    { name = "count", type = "Nullable(Int64)" },
    { name = "histogram_bounds", type = "Array(Float64)" },
    { name = "histogram_counts", type = "Array(Int64)" },
    { name = "unit", type = "Nullable(String)" },
    { name = "aggregation_temporality", type = "Nullable(String)" },
    { name = "is_monotonic", type = "Nullable(UInt8)" },
    { name = "resource_attributes", type = "Map(String, String)" },
    { name = "instrumentation_scope", type = "Nullable(String)" },
    { name = "attributes", type = "Map(String, String)" },
    { name = "series_fingerprint", type = "Nullable(Int64)" },
    { name = "has_labels", type = "Nullable(UInt8)" },
    { name = "retention_days", type = "Nullable(Int32)" },
  ]

  metrics1_columns = [
    { name = "time_bucket", type = "DateTime", materialized_expression = "toStartOfDay(timestamp)" },
    { name = "uuid", type = "String" },
    { name = "team_id", type = "Int32" },
    { name = "trace_id", type = "String" },
    { name = "span_id", type = "String" },
    { name = "trace_flags", type = "Int32" },
    { name = "timestamp", type = "DateTime64(6)" },
    { name = "observed_timestamp", type = "DateTime64(6)" },
    { name = "created_at", type = "DateTime64(6)", materialized_expression = "now()" },
    { name = "service_name", type = "LowCardinality(String)" },
    { name = "metric_name", type = "LowCardinality(String)" },
    { name = "metric_type", type = "LowCardinality(String)" },
    { name = "value", type = "Float64", codec = "Gorilla(8)" },
    { name = "count", type = "UInt64", default_expression = "1", codec = "T64" },
    { name = "histogram_bounds", type = "Array(Float64)" },
    { name = "histogram_counts", type = "Array(UInt64)" },
    { name = "unit", type = "LowCardinality(String)" },
    { name = "aggregation_temporality", type = "LowCardinality(String)" },
    { name = "is_monotonic", type = "Bool", default_expression = "false" },
    { name = "resource_attributes", type = "Map(LowCardinality(String), String)" },
    { name = "resource_fingerprint", type = "UInt64", materialized_expression = "cityHash64(resource_attributes)" },
    { name = "instrumentation_scope", type = "String" },
    { name = "attributes_map_str", type = "Map(LowCardinality(String), String)" },
    { name = "attributes_map_float", type = "Map(LowCardinality(String), Float64)" },
    { name = "time_minute", type = "DateTime", alias_expression = "toStartOfMinute(timestamp)" },
    { name = "attributes", type = "Map(String, String)", alias_expression = "mapApply((k, v) -> (left(k, -5), v), attributes_map_str)" },
  ]

  metrics2_columns = [
    { name = "team_id", type = "Int32" },
    { name = "metric_name", type = "LowCardinality(String)" },
    { name = "time_bucket", type = "DateTime", materialized_expression = "toStartOfHour(timestamp)" },
    { name = "series_fingerprint", type = "UInt64", codec = "Delta(8), Default" },
    { name = "resource_fingerprint", type = "UInt64", default_expression = "0" },
    { name = "timestamp", type = "DateTime64(6)", codec = "DoubleDelta" },
    { name = "observed_timestamp", type = "DateTime64(6)" },
    { name = "original_expiry_timestamp", type = "DateTime64(6)" },
    { name = "created_at", type = "DateTime64(6)", materialized_expression = "now()" },
    { name = "service_name", type = "LowCardinality(String)" },
    { name = "metric_type", type = "LowCardinality(String)" },
    { name = "value", type = "Float64", codec = "Gorilla(8)" },
    { name = "count", type = "UInt64", default_expression = "1", codec = "T64" },
    { name = "histogram_bounds", type = "Array(Float64)" },
    { name = "histogram_counts", type = "Array(UInt64)" },
    { name = "trace_id", type = "String" },
    { name = "span_id", type = "String" },
    { name = "trace_flags", type = "Int32" },
    { name = "has_labels", type = "Bool", default_expression = "false" },
    { name = "unit", type = "LowCardinality(String)" },
    { name = "aggregation_temporality", type = "LowCardinality(String)" },
    { name = "is_monotonic", type = "Bool", default_expression = "false" },
    { name = "instrumentation_scope", type = "String" },
    { name = "_partition", type = "UInt32" },
    { name = "_topic", type = "String" },
    { name = "_offset", type = "UInt64" },
  ]

  metrics2_input_columns = [
    { name = "uuid", type = "String" },
    { name = "team_id", type = "Int32" },
    { name = "metric_name", type = "LowCardinality(String)" },
    { name = "series_fingerprint", type = "UInt64" },
    { name = "resource_fingerprint", type = "UInt64" },
    { name = "timestamp", type = "DateTime64(6)" },
    { name = "observed_timestamp", type = "DateTime64(6)" },
    { name = "original_expiry_timestamp", type = "DateTime64(6)" },
    { name = "service_name", type = "LowCardinality(String)" },
    { name = "metric_type", type = "LowCardinality(String)" },
    { name = "value", type = "Float64" },
    { name = "count", type = "UInt64" },
    { name = "histogram_bounds", type = "Array(Float64)" },
    { name = "histogram_counts", type = "Array(UInt64)" },
    { name = "trace_id", type = "String" },
    { name = "span_id", type = "String" },
    { name = "trace_flags", type = "Int32" },
    { name = "has_labels", type = "Bool" },
    { name = "unit", type = "LowCardinality(String)" },
    { name = "aggregation_temporality", type = "LowCardinality(String)" },
    { name = "is_monotonic", type = "Bool" },
    { name = "instrumentation_scope", type = "String" },
    { name = "resource_attributes", type = "Map(LowCardinality(String), String)" },
    { name = "attributes", type = "Map(LowCardinality(String), String)" },
    { name = "_partition", type = "UInt32" },
    { name = "_topic", type = "String" },
    { name = "_offset", type = "UInt64" },
  ]
}
