from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

_JSON_API_DOCS = "https://docs.pypi.org/api/json/"

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "projects": {
        "description": "Project (package) metadata from the PyPI JSON API `info` block, one row per configured package.",
        "docs_url": _JSON_API_DOCS,
        "columns": {
            "name": "Normalized (canonical) project name.",
            "version": "The project's latest release version.",
            "summary": "Short one-line summary of the project.",
            "description": "Long description (README), rendered per `description_content_type`.",
            "description_content_type": "Content type of `description` (e.g. text/markdown).",
            "author": "Project author name.",
            "author_email": "Project author email.",
            "maintainer": "Project maintainer name.",
            "maintainer_email": "Project maintainer email.",
            "license": "License string as declared by the project.",
            "license_expression": "SPDX license expression, where declared.",
            "license_files": "List of declared license file paths.",
            "keywords": "Comma-separated keywords declared by the project.",
            "classifiers": "List of Trove classifiers (audience, license, supported Python versions, etc.).",
            "home_page": "Project home page URL.",
            "project_url": "Canonical PyPI project URL.",
            "package_url": "PyPI package URL (alias of project_url).",
            "release_url": "URL of the latest release on PyPI.",
            "project_urls": "Map of labelled project URLs (Homepage, Source, Documentation, etc.).",
            "docs_url": "Hosted documentation URL, if set.",
            "bugtrack_url": "Bug tracker URL, if set.",
            "download_url": "Legacy manual download URL, if set.",
            "downloads": "Deprecated download counts; always {last_day: -1, last_week: -1, last_month: -1}.",
            "requires_python": "Python version specifier required to install the project.",
            "requires_dist": "List of distribution dependencies (PEP 508 requirement strings).",
            "provides_extra": "List of optional dependency groups (extras) the project provides.",
            "platform": "Declared platform, if any.",
            "dynamic": "PEP 643 fields declared dynamic in the metadata.",
            "yanked": "Whether the latest release has been yanked.",
            "yanked_reason": "Reason the latest release was yanked, if any.",
            "last_serial": "Monotonic serial of the most recent event for the project (global change counter).",
        },
    },
    "releases": {
        "description": "Uploaded distribution files across every version of a project, one row per file.",
        "docs_url": _JSON_API_DOCS,
        "columns": {
            "package": "Canonical project name the file belongs to (injected by the connector).",
            "version": "Release version the file belongs to (injected by the connector).",
            "filename": "Distribution file name.",
            "url": "Direct download URL for the file.",
            "packagetype": "Distribution type (e.g. sdist, bdist_wheel).",
            "python_version": "Python tag for the distribution (e.g. py3, source).",
            "requires_python": "Python version specifier required by this file, if declared.",
            "size": "File size in bytes.",
            "upload_time": "Upload time (naive UTC).",
            "upload_time_iso_8601": "Upload time as an ISO 8601 UTC string; used as the partition key.",
            "digests": "Map of file hashes (e.g. blake2b_256, md5, sha256).",
            "md5_digest": "MD5 digest of the file.",
            "core-metadata": "Whether PEP 658 core metadata is available, and its hashes.",
            "has_sig": "Whether a PGP signature was uploaded alongside the file (deprecated).",
            "comment_text": "Optional comment supplied at upload time.",
            "downloads": "Deprecated download count; always -1.",
            "yanked": "Whether this file's release has been yanked.",
            "yanked_reason": "Reason the release was yanked, if any.",
        },
    },
    "vulnerabilities": {
        "description": "Known vulnerabilities affecting the latest version of a project, as reported by the PyPI JSON API.",
        "docs_url": _JSON_API_DOCS,
        "columns": {
            "package": "Canonical project name the advisory affects (injected by the connector).",
            "id": "Advisory identifier (e.g. a PYSEC id).",
            "aliases": "Other identifiers for the same advisory (e.g. CVE, GHSA).",
            "details": "Full description of the vulnerability.",
            "summary": "Short summary of the vulnerability, if provided.",
            "fixed_in": "List of versions in which the vulnerability is fixed.",
            "link": "URL to the advisory details.",
            "source": "Advisory database that reported the vulnerability (e.g. osv).",
            "withdrawn": "Timestamp the advisory was withdrawn, or null if still active.",
        },
    },
}
