from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "leads": {
        "description": "People records in Marketo, exported through the Bulk Extract API. Columns follow your instance's lead field set, so custom fields appear alongside the standard ones.",
        "docs_url": "https://developer.adobe.com/marketo-apis/api/bulk-extract/",
        "columns": {
            "id": "Unique identifier of the lead in Marketo.",
            "email": "Email address of the lead.",
            "firstName": "First name of the lead.",
            "lastName": "Last name of the lead.",
            "company": "Company name on the lead record.",
            "title": "Job title of the lead.",
            "phone": "Phone number of the lead.",
            "country": "Country on the lead record.",
            "createdAt": "Datetime the lead was created in Marketo.",
            "updatedAt": "Datetime the lead record was last modified.",
            "leadSource": "Source the lead was acquired from.",
            "leadStatus": "Current lifecycle status of the lead.",
            "leadScore": "Numeric score assigned by your scoring campaigns.",
            "unsubscribed": "Whether the lead has unsubscribed from marketing email.",
            "unsubscribedReason": "Reason recorded when the lead unsubscribed.",
            "marketingSuspended": "Whether marketing communication to this lead is suspended.",
            "emailInvalid": "Whether Marketo has marked the email address as invalid.",
            "sfdcContactId": "Salesforce contact id linked to this lead, when CRM sync is enabled.",
            "sfdcLeadId": "Salesforce lead id linked to this lead, when CRM sync is enabled.",
            "sfdcAccountId": "Salesforce account id linked to this lead, when CRM sync is enabled.",
        },
    },
    "activities": {
        "description": "Lead activity records (email opens, clicks, form fills, page visits, score changes and more) exported through the Bulk Extract API.",
        "docs_url": "https://developer.adobe.com/marketo-apis/api/bulk-extract/",
        "columns": {
            "marketoGUID": "Globally unique identifier of the activity record.",
            "leadId": "Identifier of the lead the activity belongs to.",
            "activityDate": "Datetime the activity occurred.",
            "activityTypeId": "Identifier of the activity type, joinable to the activity_types table.",
            "campaignId": "Identifier of the campaign that produced the activity, when applicable.",
            "primaryAttributeValueId": "Identifier of the activity's primary attribute (for example the email or form involved).",
            "primaryAttributeValue": "Display value of the activity's primary attribute.",
            "attributes": "JSON encoded list of the activity's remaining attributes.",
        },
    },
    "activity_types": {
        "description": "Catalog of activity types available in your Marketo instance, including the attributes each type records.",
        "docs_url": "https://developer.adobe.com/marketo-apis/api/mapi/#tag/Activities/operation/getAllActivityTypesUsingGET",
        "columns": {
            "id": "Unique identifier of the activity type.",
            "name": "Name of the activity type.",
            "description": "Description of what the activity type records.",
            "primaryAttribute": "The attribute that primarily identifies an activity of this type.",
            "attributes": "List of additional attributes recorded for this activity type.",
        },
    },
    "campaigns": {
        "description": "Smart campaigns and trigger campaigns in your Marketo instance.",
        "docs_url": "https://developer.adobe.com/marketo-apis/api/mapi/#tag/Campaigns",
        "columns": {
            "id": "Unique identifier of the campaign.",
            "name": "Name of the campaign.",
            "description": "Description of the campaign.",
            "type": "Campaign type, either batch or trigger.",
            "programName": "Name of the program the campaign belongs to.",
            "programId": "Identifier of the program the campaign belongs to.",
            "workspaceName": "Workspace the campaign lives in.",
            "createdAt": "Datetime the campaign was created.",
            "updatedAt": "Datetime the campaign was last modified.",
            "active": "Whether a trigger campaign is currently active.",
        },
    },
    "lists": {
        "description": "Static lists defined in your Marketo instance.",
        "docs_url": "https://developer.adobe.com/marketo-apis/api/mapi/#tag/Static-Lists",
        "columns": {
            "id": "Unique identifier of the list.",
            "name": "Name of the list.",
            "description": "Description of the list.",
            "programName": "Program the list belongs to, when it is a program-local list.",
            "workspaceName": "Workspace the list lives in.",
            "createdAt": "Datetime the list was created.",
            "updatedAt": "Datetime the list was last modified.",
        },
    },
    "programs": {
        "description": "Marketing programs, the containers Marketo uses to group assets, campaigns and costs.",
        "docs_url": "https://developer.adobe.com/marketo-apis/api/asset/#tag/Programs",
        "columns": {
            "id": "Unique identifier of the program.",
            "name": "Name of the program.",
            "description": "Description of the program.",
            "type": "Program type, for example Default, Event, Email or Engagement.",
            "channel": "Channel assigned to the program.",
            "status": "Current status of the program.",
            "url": "Link to the program inside Marketo.",
            "folder": "Folder the program is stored in.",
            "workspace": "Workspace the program belongs to.",
            "createdAt": "Datetime the program was created.",
            "updatedAt": "Datetime the program was last modified.",
            "costs": "Period costs recorded against the program.",
            "tags": "Tags applied to the program.",
        },
    },
    "emails": {
        "description": "Email assets in your Marketo instance.",
        "docs_url": "https://developer.adobe.com/marketo-apis/api/asset/#tag/Emails",
        "columns": {
            "id": "Unique identifier of the email asset.",
            "name": "Name of the email.",
            "description": "Description of the email.",
            "subject": "Subject line of the email.",
            "fromName": "Sender name shown to recipients.",
            "fromEmail": "Sender address the email is sent from.",
            "replyEmail": "Reply-to address for the email.",
            "status": "Approval status of the email, either draft or approved.",
            "template": "Identifier of the email template the asset is built on.",
            "folder": "Folder the email is stored in.",
            "workspace": "Workspace the email belongs to.",
            "operational": "Whether the email is operational and therefore ignores subscription status.",
            "createdAt": "Datetime the email was created.",
            "updatedAt": "Datetime the email was last modified.",
        },
    },
    "forms": {
        "description": "Form assets used to capture leads on landing pages and external sites.",
        "docs_url": "https://developer.adobe.com/marketo-apis/api/asset/#tag/Forms",
        "columns": {
            "id": "Unique identifier of the form.",
            "name": "Name of the form.",
            "description": "Description of the form.",
            "status": "Approval status of the form, either draft or approved.",
            "locale": "Locale the form renders in.",
            "buttonLabel": "Label shown on the form's submit button.",
            "buttonLocation": "Horizontal position of the submit button.",
            "folder": "Folder the form is stored in.",
            "createdAt": "Datetime the form was created.",
            "updatedAt": "Datetime the form was last modified.",
        },
    },
    "landing_pages": {
        "description": "Landing page assets in your Marketo instance.",
        "docs_url": "https://developer.adobe.com/marketo-apis/api/asset/#tag/Landing-Pages",
        "columns": {
            "id": "Unique identifier of the landing page.",
            "name": "Name of the landing page.",
            "description": "Description of the landing page.",
            "title": "Browser title of the landing page.",
            "URL": "Public URL of the landing page.",
            "status": "Approval status of the landing page, either draft or approved.",
            "template": "Identifier of the landing page template used.",
            "folder": "Folder the landing page is stored in.",
            "workspace": "Workspace the landing page belongs to.",
            "mobileEnabled": "Whether the landing page renders a mobile view.",
            "createdAt": "Datetime the landing page was created.",
            "updatedAt": "Datetime the landing page was last modified.",
        },
    },
    "smart_campaigns": {
        "description": "Smart campaign assets, including their smart list and flow configuration.",
        "docs_url": "https://developer.adobe.com/marketo-apis/api/asset/#tag/Smart-Campaigns",
        "columns": {
            "id": "Unique identifier of the smart campaign.",
            "name": "Name of the smart campaign.",
            "description": "Description of the smart campaign.",
            "type": "Smart campaign type, either batch or trigger.",
            "status": "Current status of the smart campaign.",
            "isActive": "Whether the smart campaign is currently active.",
            "isSystem": "Whether the smart campaign is managed by Marketo rather than a user.",
            "isCommunicationLimitEnabled": "Whether the campaign respects the instance's communication limit.",
            "folder": "Folder the smart campaign is stored in.",
            "workspace": "Workspace the smart campaign belongs to.",
            "createdAt": "Datetime the smart campaign was created.",
            "updatedAt": "Datetime the smart campaign was last modified.",
        },
    },
}
