from sources.sdk import CanonicalDescriptions

# Descriptions are taken from the official lemlist API reference
# (https://developer.lemlist.com/api-reference). Keys match the endpoint/schema names returned by
# `get_schemas` (see settings.LEMLIST_ENDPOINTS). Columns not listed here fall back to LLM enrichment.
CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "campaigns": {
        "description": "Cold-outreach campaigns in your lemlist team, each a multichannel email/LinkedIn sequence sent to leads.",
        "docs_url": "https://developer.lemlist.com/api-reference/endpoints/campaigns/get-many-campaigns",
        "columns": {
            "_id": "Unique campaign identifier (e.g. cam_xxx).",
            "name": "Campaign name.",
            "labels": "Labels applied to the campaign.",
            "status": "Campaign status (running, draft, archived, ended, paused, errors).",
            "createdAt": "When the campaign was created.",
            "createdBy": "User ID of the campaign creator.",
            "teamId": "ID of the team that owns the campaign.",
            "hasError": "Whether the campaign currently has a configuration error.",
            "errors": "List of campaign error messages.",
        },
    },
    "activities": {
        "description": "Per-lead activity events in your campaigns (emails opened, clicked, replied, LinkedIn actions, etc.). Append-only event log filterable by createdAt.",
        "docs_url": "https://developer.lemlist.com/api-reference/endpoints/activities/get-many-activities",
        "columns": {
            "_id": "Unique activity identifier.",
            "type": "Activity type (e.g. emailsOpened, emailsClicked, emailsReplied, linkedinReplied).",
            "leadId": "ID of the lead the activity relates to.",
            "campaignId": "ID of the campaign the activity belongs to.",
            "sequenceId": "ID of the sequence the activity belongs to.",
            "stepId": "ID of the sequence step that produced the activity.",
            "createdAt": "When the activity occurred.",
        },
    },
    "team": {
        "description": "Your lemlist team account, including configured webhooks and invited users.",
        "docs_url": "https://developer.lemlist.com/api-reference/endpoints/team/get-team",
        "columns": {
            "_id": "Unique team identifier.",
            "name": "Team name.",
            "userIds": "User IDs that belong to the team.",
            "createdBy": "User ID that created the team.",
            "createdAt": "When the team was created.",
            "users": "Team members, each with userId, name, email and role. Returned on lemlist API v2.",
        },
    },
    "team_senders": {
        "description": "Sender accounts configured for the team and the campaigns each sender is attached to.",
        "docs_url": "https://developer.lemlist.com/api-reference/endpoints/team/get-team-senders",
        "columns": {
            "userId": "User ID of the sender.",
            "campaigns": "Campaigns the sender is attached to, with id, name, status and sending channels.",
        },
    },
    "unsubscribes": {
        "description": "Contacts that have unsubscribed from your team's outreach.",
        "docs_url": "https://developer.lemlist.com/api-reference/endpoints/unsubscribes/get-many-unsubscribes",
        "columns": {
            "_id": "Unique unsubscribe identifier.",
            "email": "Email address that unsubscribed.",
            "createdAt": "When the unsubscribe was recorded.",
            "campaignId": "Campaign the contact unsubscribed from, if scoped to a campaign.",
            "scope": "Scope of the unsubscribe (campaign, team or global).",
        },
    },
    "contacts": {
        "description": "Contacts in your lemlist team: the people record that campaign leads point at through contactId.",
        "docs_url": "https://developer.lemlist.com/api-reference/endpoints/contacts/get-many-contacts",
        "columns": {
            "_id": "Unique contact identifier.",
            "teamId": "ID of the team that owns the contact.",
            "fullName": "Full name of the contact.",
            "email": "Email address of the contact.",
            "firstName": "First name of the contact.",
            "lastName": "Last name of the contact.",
            "phone": "Phone number of the contact.",
            "jobTitle": "Job title of the contact.",
            "linkedinUrl": "LinkedIn profile URL of the contact.",
            "ownerId": "User ID of the contact owner.",
            "companyId": "ID of the company the contact is attached to.",
            "createdAt": "When the contact was created.",
            "createdBy": "User ID that created the contact.",
            "unsubscribed": "Whether the contact has unsubscribed.",
            "campaignCount": "Number of campaigns the contact is in.",
        },
    },
    "campaign_leads": {
        "description": "Leads in each campaign, with their latest state. A lead is a contact enrolled in one campaign.",
        "docs_url": "https://developer.lemlist.com/api-reference/endpoints/campaigns/export-campaign-leads-v2",
        "columns": {
            "_id": "Unique lead identifier within the campaign.",
            "campaignId": "ID of the campaign the lead belongs to.",
            "email": "Email address of the lead.",
            "emailStatus": "Email deliverability status (deliverable, risky, undeliverable).",
            "firstName": "First name of the lead.",
            "lastName": "Last name of the lead.",
            "companyName": "Company name of the lead.",
            "companyDomain": "Company domain of the lead.",
            "jobTitle": "Job title of the lead.",
            "linkedinUrl": "LinkedIn profile URL of the lead.",
            "lastState": "Latest state the lead reached in the campaign (e.g. contacted, interested).",
            "status": "Status of the lead in the campaign.",
        },
    },
    "campaign_reports": {
        "description": "All-time headline statistics per campaign: lead counts, emails and LinkedIn messages sent, opened, clicked and replied, and interest.",
        "docs_url": "https://developer.lemlist.com/api-reference/endpoints/campaigns/get-campaign-reports",
        "columns": {
            "_id": "Campaign ID.",
            "name": "Campaign name.",
            "createdAt": "When the campaign was created.",
            "state": "Campaign state (running, paused, etc.).",
            "status": "Campaign status (draft, ended, etc.).",
            "totalCount": "Total number of leads in the campaign.",
            "inSequenceLeadCount": "Number of leads in the sequence.",
            "emailsSent": "Number of emails sent.",
            "emailsOpened": "Number of emails opened.",
            "emailsClicked": "Number of emails with links clicked.",
            "emailsReplied": "Number of emails replied to.",
            "emailsUnsubscribed": "Number of leads that unsubscribed by email.",
            "linkedinSent": "Number of LinkedIn messages sent.",
            "linkedinReplied": "Number of LinkedIn messages replied to.",
            "interested": "Number of leads marked as interested.",
            "notInterested": "Number of leads marked as not interested.",
        },
    },
    "campaign_sequences": {
        "description": "Sequences of each campaign with their ordered steps. Resolves the sequenceId and stepId on activities.",
        "docs_url": "https://developer.lemlist.com/api-reference/endpoints/sequences/get-campaign-sequences",
        "columns": {
            "_id": "Unique sequence identifier.",
            "campaignId": "ID of the campaign the sequence belongs to.",
            "steps": "Ordered steps of the sequence, each with _id, type, delay, index, subject and message.",
        },
    },
}
