from products.warehouse_sources.backend.temporal.data_imports.sources.common.canonical_descriptions import (
    CanonicalDescriptions,
)

CANONICAL_DESCRIPTIONS: CanonicalDescriptions = {
    "Customers": {
        "description": "A customer with their subscriptions, purchases, balances, and billing controls.",
        "docs_url": "https://docs.useautumn.com/api-reference/customers/listCustomers",
        "columns": {
            "id": "Your unique identifier for the customer.",
            "name": "The name of the customer.",
            "email": "The email address of the customer.",
            "created_at": "Time the customer was created, as a Unix timestamp in milliseconds.",
            "fingerprint": "Unique identifier (e.g. serial number) used to detect duplicate customers and prevent free trial abuse.",
            "stripe_id": "The Stripe customer ID linked to this customer.",
            "env": "Environment the customer belongs to: sandbox or live.",
            "metadata": "Arbitrary key-value metadata attached to the customer.",
            "subscriptions": "The customer's subscriptions, each with its plan, status, and billing period.",
            "purchases": "One-off (non-recurring) plan purchases made by the customer.",
            "balances": "The customer's feature balances, including usage and remaining allowances.",
            "billing_controls": "Overage behavior, spend limits, usage alerts, and auto top-up configuration for the customer.",
        },
    },
    "Events": {
        "description": "A usage event recorded for a customer feature, with the balance deductions it caused.",
        "docs_url": "https://docs.useautumn.com/api-reference/events/listEvents",
        "columns": {
            "id": "Unique identifier for the event.",
            "timestamp": "Time the event was recorded, as a Unix timestamp in milliseconds.",
            "feature_id": "ID of the feature this event tracked usage for.",
            "customer_id": "ID of the customer the event belongs to.",
            "value": "Usage amount recorded by the event.",
            "properties": "Arbitrary properties attached to the event.",
            "deductions": "Balance deductions applied by this event, per feature balance.",
        },
    },
    "Features": {
        "description": "A feature configured for the organization: boolean access, metered usage, or a credit system.",
        "docs_url": "https://docs.useautumn.com/api-reference/features/listFeatures",
        "columns": {
            "id": "The unique identifier for this feature, used in check and track calls.",
            "name": "Human-readable name displayed in the dashboard and billing UI.",
            "type": "Feature type: boolean for on/off access, metered for usage-tracked features, credit_system for unified credit pools, ai_credit_system for model-based token pricing.",
            "consumable": "For metered features: true if usage resets periodically, false if allocated persistently (seats, storage).",
            "event_names": "Event names that trigger this feature's balance. Allows multiple features to respond to a single event.",
            "credit_schema": "For credit systems: the metered features that draw from this credit pool and their costs.",
        },
    },
    "Plans": {
        "description": "A pricing plan with its base price and feature configurations.",
        "docs_url": "https://docs.useautumn.com/api-reference/plans/listPlans",
        "columns": {
            "id": "Unique identifier for the plan.",
            "name": "Display name of the plan.",
            "description": "Optional description of the plan.",
            "group": "Group identifier for organizing related plans.",
            "version": "Version number of the plan; updating a plan creates a new version.",
            "add_on": "Whether the plan is an add-on that can be attached alongside a main plan.",
            "auto_enable": "Whether the plan is automatically enabled for new customers.",
            "price": "Base price of the plan, with amount, currency options, and billing interval.",
            "items": "The plan's items: features included, allowances, and usage prices.",
        },
    },
    "Entities": {
        "description": "A feature entity (e.g. a seat or workspace) tracking balances separately under a parent customer.",
        "docs_url": "https://docs.useautumn.com/api-reference/entities/listEntities",
        "columns": {
            "id": "Your unique identifier for the entity, unique within its parent customer.",
            "name": "The name of the entity.",
            "customer_id": "ID of the parent customer the entity belongs to.",
            "feature_id": "ID of the feature this entity was created for.",
            "created_at": "Time the entity was created, as a Unix timestamp in milliseconds.",
            "env": "Environment the entity belongs to: sandbox or live.",
            "subscriptions": "Subscriptions attached to the entity, including plans inherited from the parent customer.",
        },
    },
    "Invoices": {
        "description": "An invoice issued to a customer through the connected billing processor.",
        "docs_url": "https://docs.useautumn.com/api-reference/invoices/listInvoices",
        "columns": {
            "id": "Unique identifier for the invoice.",
            "customer_id": "ID of the customer the invoice belongs to.",
            "entity_id": "ID of the entity the invoice belongs to, if entity-scoped.",
            "plan_ids": "IDs of the plans billed on this invoice.",
            "stripe_id": "The Stripe invoice ID.",
            "processor_type": "Billing processor that issued the invoice: stripe or revenuecat.",
            "status": "Invoice status: draft, open, paid, void, or uncollectible.",
            "total": "Total amount of the invoice.",
            "amount_paid": "Amount paid on the invoice so far.",
            "refunded_amount": "Amount refunded on the invoice.",
            "currency": "Three-letter currency code of the invoice.",
            "created_at": "Time the invoice was created, as a Unix timestamp in milliseconds.",
            "hosted_invoice_url": "URL of the hosted invoice page, when available.",
        },
    },
    "Coupons": {
        "description": "A coupon (discount reward) configured for the organization, with its promo codes.",
        "docs_url": "https://docs.useautumn.com/api-reference/rewards/listRewards",
        "columns": {
            "id": "The unique identifier for the coupon.",
            "name": "A human-readable name for the coupon.",
            "type": "The type of discount: percentage_discount, fixed_discount, or invoice_credits.",
            "value": "The discount value: a percentage for percentage_discount, or an amount for fixed_discount and invoice_credits.",
            "duration": "How long the discount lasts: one_off, a number of months, or forever.",
            "plan_ids": "Plans the coupon is restricted to, if any.",
            "promo_codes": "Redeemable promo codes for this coupon, with redemption limits.",
            "created_at": "Time the coupon was created, as a Unix timestamp in milliseconds.",
        },
    },
    "FeatureGrants": {
        "description": "A feature-grant reward that gives customers extra feature allowance when redeemed.",
        "docs_url": "https://docs.useautumn.com/api-reference/rewards/listRewards",
        "columns": {
            "id": "The unique identifier for the feature grant.",
            "name": "A human-readable name for the feature grant.",
            "grants": "Features granted on redemption, with included amounts and optional expiry.",
            "promo_codes": "Redeemable promo codes for this grant, with usage limits.",
            "created_at": "Time the feature grant was created, as a Unix timestamp in milliseconds.",
        },
    },
}
